FFM-4195: partial draft of new erlang sdk
harness/developer-hub pull request #1013
Opened 2023-03-16 15:19 UTC by StrawberryPad

2023-03-27 12:19 UTC, SmritiSatya submitted a review, later dismissed

2023-03-28 10:29 UTC, erdirowlands approved these changes

2023-03-28 10:58 UTC, erdirowlands commented on docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md
> +
```suggestion
  * You can also find a sample Erlang apllication that uses the Erlang SDK in [GitHub](https://github.com/harness-apps/ff-erlang-server-sample)
  
```

Last minute addition @StrawberryPad !  See our offline conversation, the TLDR is I was able to place this repo in a public location in the "harness-apps" github accoubt.

2023-03-28 11:10 UTC, erdirowlands submitted a review, later dismissed

2023-03-28 11:27 UTC, erdirowlands requested changes
Another addition there which I missed - see suggested change

2023-03-28 11:39 UTC, erdirowlands commented on docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md
> +  :cfclient:close()
```suggestion
  :cfclient.close()
```

Syntax error

2023-03-28 11:39 UTC, erdirowlands commented on docs/feature-flags/ff-sdks/server-sdks/erlang-sdk-reference.md
> +  :cfclient:close(:instance_name_1)
```suggestion
  :cfclient.close(:instance_name_1)
```

2023-03-28 13:15 UTC, merged