Add new important best practice for variable loops
harness/developer-hub pull request #1029
Opened 2023-03-17 19:00 UTC by gacerioni

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [X] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [X] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-03-23 17:13 UTC, gacerioni commented
Just taking the opp to fix a small typo in the Cache Intelligence docs.
cc: @ravilach @rashminandasahoo

2023-03-30 13:59 UTC, aimurphy commented
Removing myself as a reviewer - Cache Intelligence typo was fixed during the bug bash

2023-03-31 04:51 UTC, rashminandasahoo requested changes

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +### How to use variables representing lists/arrays to loop and repeat for each item
```suggestion
### What is the best way to loop over items in a list or array using variables?
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +With that in mind, you can define a Harness string variable containing a comma-separated list of items represented by other strings. You can even get this values list from inputs at runtime.
```suggestion
You can create a Harness string variable containing a comma-separated list of other strings that represent items. At runtime, you can even get this list from the input.   
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +You can use all Java String class built-in methods on Harness variable expressions.
```suggestion
Harness variable expressions support all Java String class built-in methods.
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +For example, this Pipeline variable that contains a list of Jira Tickets:
```suggestion
The following example shows a pipeline variable that contains a list of Jira tickets:
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +By using the `split()` method, you can split that variable string into an array of substrings:
```suggestion
To split the variable into an array of substrings, use the `split()` method:
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +You can use this expression in your **repeat** Looping Strategy. For example:
```suggestion
The following example shows how to use the above expression in the `repeat` looping strategy:
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +Finally, you refer to each item in the loop with the `<+repeat.item>` expression.
```suggestion
To refer to each item in the loop use the `<+repeat. Item>` expression:
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +**Extra:** You can also dynamically create an axis for your Matrix.
```suggestion
You can also create an axis for your matrix dynamically using the following expression:
```

2023-03-31 04:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/best-practices-for-looping-strategies.md
> +And use the `<+matrix.jira>` expression instead.
To reference this axis use `<+matrix.jira>`.

2023-03-31 04:57 UTC, rashminandasahoo commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +There are several ways to configure caching in Harness CI: save and restore cache steps, mounting volumes, and Cache Intelligence. Mounting volumes or using save and restore cache steps requires you
```suggestion
You can configure caching in Harness CI in the following ways:

- Save and restore the cache steps
- Mounting volumes
- Cache Intelligence

When you mount volumes or use save and restore cache steps, you must manage the cache. Harness automatically caches and restores common dependencies with Cache Intelligence. Additionally, Cache Intelligence does not require you to provide your storage, since the cache is stored in the Harness Cloud environment.
```

2023-03-31 04:57 UTC, rashminandasahoo commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +There are several ways to configure caching in Harness CI: save and restore cache steps, mounting volumes, and Cache Intelligence. Mounting volumes or using save and restore cache steps requires you
I am not too familiar with CI, but please see if the above suggestion looks ok :).

2023-04-04 15:26 UTC, gacerioni commented
All good!

2023-04-24 05:33 UTC, rashminandasahoo approved these changes

2023-04-24 05:33 UTC, merged