DOC-2831 Auto-upgrade and expiration policy
harness/developer-hub pull request #1119
Opened 2023-03-27 19:03 UTC by KimberlyFields

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [X] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* DOC-2831

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [X] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-03-28 14:47 UTC, KimberlyFields commented on docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md
> +### Find the expiration date for your delegate
I changed the title.

2023-03-28 18:21 UTC, KimberlyFields commented on docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md
> +        schedule: "0 */1 * * *"
I added a sentence above the yaml file to indicate users can modify the cron job's execution time.

2023-03-28 18:23 UTC, KimberlyFields commented on docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md
> +N = 78705, released March 15th
I adjusted the example.

2023-03-28 18:44 UTC, KimberlyFields commented on docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md
> +2. Replace **account id** with your Harness account ID.
Added these steps.

2023-03-28 22:36 UTC, raghuAtWings commented on docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md
> +4. Replace **PUT_YOUR_MANAGER_ENDPOINT_HERE** with `https://app.harness.io/gratis`
the end point is not always https://app.harness.io/gratis, i would either remove this section of ask users to go to "new delegate" -> "kubernetes" -> "kubernetes manifest" -> "custom" and follow directions

![Screen Shot 2023-03-28 at 3 35 30 PM](https://user-images.githubusercontent.com/27451456/228382048-1ca9f9f5-b18f-4efb-a8f9-2ec29df2e343.png)

2023-03-28 22:39 UTC, raghuAtWings requested changes

2023-03-28 22:39 UTC, raghuAtWings commented on docs/platform/2_Delegates/install-delegates/delegate-upgrades-and-expiration.md
> +To find the delegate status, go to **Projects**, select a project, and then select **Delegates**.
the delegates can be at account and org level too, e.g. i can go to [Account Settings] -> [Account Resources] -> [Delegates] to see delegates.

2023-03-29 20:00 UTC, KimberlyFields commented
Closing without merging. The entire delegate doc set was refactored, which created several conflicts in this file. It's easier to create a new PR than to fix the conflicts. This content will be in a new PR.

2023-03-29 20:00 UTC, closed without merging