[DOC-2869] Update images
harness/developer-hub pull request #1166
Opened 2023-03-30 14:28 UTC by SmritiSatya

Change 'Chaos Access' to 'Chaos Infrastructure' in images 
Replace 'Chaos Access' with 'Chaos Infrastructure' in the architecture documentation
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

2023-03-30 14:43 UTC, SudheendraKatte submitted a review, later dismissed

2023-03-30 14:59 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/architecture.md
> +**Harness control plane** is the single source to collaboratively create, schedule, and monitor chaos experiments. It comes with a set of chaos faults that are defined in a sequence, which helps achi
```suggestion
**Harness control plane** is the single source to collaboratively create, schedule, and monitor chaos experiments. It comes with a set of chaos faults that are defined in a sequence, which helps achieve the desired chaos impact on the target resources. You can sign in to the Harness platform and leverage the interactive UI dashboard to enable chaos access in your infrastructure, define your chaos experiments and target the infrastructure. You can also monitor the experiments during their execution.
```

2023-03-30 15:03 UTC, neelanjan00 requested changes

2023-03-30 15:03 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/architecture.md
>  #### Authentication server
Auth server is no more there, we just use Harness auth now. We can remove this entirely.

2023-03-30 15:03 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/architecture.md
>  #### Backend server
```suggestion
#### Chaos manager
```
Backend server is called chaos manager now

2023-03-30 15:03 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/architecture.md
> +The backend server is a GraphQL-based Golang microservice that serves the requests received from the chaos infrastructure either by querying the database for relevant information or fetching informat
```suggestion
The chaos manager is a GraphQL-based Golang microservice that serves the requests either by querying the database for relevant information or fetching information from the execution plane.
```

2023-03-31 01:41 UTC, SmritiSatya commented on docs/chaos-engineering/technical-reference/architecture.md
> +**Harness control plane** is the single source to collaboratively create, schedule, and monitor chaos experiments. It comes with a set of chaos faults that are defined in a sequence, which helps achi
We don't use 'Chaos Access' anymore, no? @neelanjan00

2023-03-31 05:38 UTC, merged

2023-03-31 05:40 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/architecture.md
> +**Harness control plane** is the single source to collaboratively create, schedule, and monitor chaos experiments. It comes with a set of chaos faults that are defined in a sequence, which helps achi
chaos access is merely a verb, we can use it as such. We are only prohibiting the use of chaos access as a noun. But we can use what you suggested as well.