New topics - SRM get started
harness/developer-hub pull request #1197
Opened 2023-04-02 18:20 UTC by SudheendraKatte

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ x ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-04-03 09:36 UTC, StrawberryPad requested changes
Per conversation

2023-04-03 09:36 UTC, StrawberryPad commented on docs/service-reliability-management/getting-started/slo-dashboard.md
> +## Navigate to the SLO dashboard
This is more of a step instruction, not a heading. Maybe: "## View the SLO dashboard"

2023-04-03 09:36 UTC, StrawberryPad commented on docs/service-reliability-management/getting-started/slo-dashboard.md
> +
Instead of the 4 1st level headings below, make either a bullet list or 4 2nd level headings (and organize the heading for **SLO details page** accordingly).

2023-04-03 09:36 UTC, StrawberryPad commented on docs/service-reliability-management/getting-started/slo-dashboard.md
> +### SLO details page
This might deserve its own 1st level heading (##)

2023-04-03 12:23 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/srm-intro.md
> +- Harness Service Reliability Management (SRM) module offers users the ability to define and configure Service Level Indicators (SLIs), Service Level Objectives (SLOs), and Error Budgets through a us
Incorporated

2023-04-03 12:23 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/srm-intro.md
> +- Performance Analytics: Provides detailed analytics and insights into the performance of your applications and services. This enables you to identify trends and make data-driven decisions to optimiz
Incorporated

2023-04-03 12:24 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/srm-intro.md
> +
Good idea :).. converted to a table.

2023-04-03 12:27 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +- Ensure that you have installed a Harness Delegate, and it can communicate with Harness, your health source, and change sources. To learn more about delegates, go to [Get started with delegates](htt
Implemented

2023-04-03 12:35 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +A Harness project is a group of Harness modules and resources. For example, a project might have a Harness SRM module to create an SLO.
Corrected

2023-04-03 12:36 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +To create a project, perform the following steps:
Opted for "do the following"

2023-04-03 13:08 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/slo-dashboard.md
> +## Navigate to the SLO dashboard
Incorporated

2023-04-04 08:46 UTC, StrawberryPad requested changes
Looks much better, @SudheendraKatte. There's just some organization tweaks on create-first-slo and indentations here and there.

2023-04-04 08:46 UTC, StrawberryPad commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +
Indent the <details> so they fall underneath the bullet.

2023-04-04 08:46 UTC, StrawberryPad commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +## Navigate to the "Create SLO" page
Maybe the procedure (at ## level) is **Create a SLO**. Then subheading levels (###):

**## Create a SLO**

Summary of high level steps:

* SLO identification...
* SLIs...
* Set our SLO
* (Optional) Error budget...

### Define SLO Identification
1. Go to [navigation path, for exampe **SRM demo > SLOs**...].
2. In **Define SLO Identification**, enter a Name, etc....
3. Follow the steps below to:
- Create a monitored service [link to below]
- Select a user journey [link to below]

#### Create a monitored service

#### Select a user journey

**### Configure SLIs**

**### Set your SLO**

etc...

2023-04-04 08:46 UTC, StrawberryPad commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +:::info note
indent note

2023-04-04 15:19 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +## Navigate to the "Create SLO" page
Updated

2023-04-04 15:19 UTC, SudheendraKatte commented on docs/service-reliability-management/getting-started/create-first-slo.md
> +:::info note
Done

2023-04-07 22:52 UTC, michaelcretzman submitted a review, later dismissed
approved with suggestions

2023-04-07 22:52 UTC, michaelcretzman commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +You can set up notifications for monitored services. This means that your team can receive alerts when any changes occur to a service's code, configuration, behavior, deployment, or infrastructure. T
```suggestion
You can configure notifications for monitored services. Your team will receive alerts whenever there are modifications made to a service's code, configuration, behavior, deployment, or infrastructure. These notifications can help your team stay up to date and ensure that any problems are resolved promptly.
```

2023-04-07 22:52 UTC, michaelcretzman commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +     | Condition | Settings    |
I would have used a note because MD tables are pretty fragile. You're braver than I am :)

2023-04-07 22:52 UTC, michaelcretzman commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +      If you choose Slack, PagerDuty, or Microsoft Teams as your notification method, you can select a Harness user group that is part of a **Project**, **Organization**, or an **Account**. Notificat
```suggestion
      If you choose Slack, PagerDuty, or Microsoft Teams as your notification method, you can select a Harness user group that is part of a Harness project, organization, or an account. Notifications are sent to the Slack or Microsoft Teams channels that are associated with the selected user group.
```

2023-04-07 22:52 UTC, michaelcretzman commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +      If you choose Slack, PagerDuty, or Microsoft Teams as your notification method, you can select a Harness user group that is part of a **Project**, **Organization**, or an **Account**. Notificat
no need for capitalizing Harness entities like project. No need to bold then either. you might want to add a like to the user group notification docs instead of providing step that might need to be updated at some point.

2023-04-07 22:52 UTC, michaelcretzman commented on docs/service-reliability-management/notifications/slo-notifications.md
> +1. In your Harness project, navigate to **Service Reliability Management** > **SLOs**, and then select the SLO for which you want to set up notifications.
```suggestion
1. In your Harness project, navigate to **Service Reliability Management** > **SLOs**, and then select the SLO for  notifications.
```

2023-04-07 22:52 UTC, michaelcretzman commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +1. In your Harness project, navigate to **Service Reliability Management** > **Monitored Services**, and then select the monitored service for which you want to configure notification.
```suggestion
1. In your Harness project, navigate to **Service Reliability Management** > **Monitored Services**, and then select the monitored service for notifications.
```

2023-04-07 22:52 UTC, michaelcretzman commented on docs/service-reliability-management/notifications/slo-notifications.md
> +      If you choose Slack, PagerDuty, or Microsoft Teams as your notification method, you can select a Harness user group that is part of a **Project**, **Organization**, or an **Account**. Notificat
```suggestion
      If you choose Slack, PagerDuty, or Microsoft Teams as your notification method, you can select a Harness user group that is part of a project, organization, or an account. Notifications are sent to the Slack or Microsoft Teams channels that are associated with the selected user group.
```

2023-04-08 14:35 UTC, SudheendraKatte commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +You can set up notifications for monitored services. This means that your team can receive alerts when any changes occur to a service's code, configuration, behavior, deployment, or infrastructure. T
Updated

2023-04-08 14:36 UTC, SudheendraKatte commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +      If you choose Slack, PagerDuty, or Microsoft Teams as your notification method, you can select a Harness user group that is part of a **Project**, **Organization**, or an **Account**. Notificat
Updated

2023-04-08 14:39 UTC, SudheendraKatte commented on docs/service-reliability-management/notifications/slo-notifications.md
> +1. In your Harness project, navigate to **Service Reliability Management** > **SLOs**, and then select the SLO for which you want to set up notifications.
Updated

2023-04-08 14:39 UTC, SudheendraKatte commented on docs/service-reliability-management/notifications/monitoredservice-notifications.md
> +1. In your Harness project, navigate to **Service Reliability Management** > **Monitored Services**, and then select the monitored service for which you want to configure notification.
Updated

2023-04-08 14:39 UTC, SudheendraKatte commented on docs/service-reliability-management/notifications/slo-notifications.md
> +      If you choose Slack, PagerDuty, or Microsoft Teams as your notification method, you can select a Harness user group that is part of a **Project**, **Organization**, or an **Account**. Notificat
Updated

2023-04-11 09:42 UTC, charanya-j submitted a review, later dismissed

2023-04-11 12:36 UTC, SudheendraKatte commented
This PR was meant for getting the peer review of the content that changed as part of the SRM docs left nav reorg. Closing this PR as the all the new and updated content have been reviewed and approved (see the comments trail for review details).

2023-04-11 12:36 UTC, closed without merging