Add files via upload
harness/developer-hub pull request #1219
Opened 2023-04-04 23:04 UTC by thisrohangupta

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-04-05 05:36 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/aws_lambda.md
> +## Product Demo Video
```suggestion
## Visual summary
```

2023-04-05 05:42 UTC, roshnisarangadharan submitted a review, later dismissed

2023-04-05 05:56 UTC, roshnisarangadharan approved these changes

2023-04-05 22:32 UTC, michaelcretzman commented
@roshnisarangadharan @thisrohangupta this PR is broken. It can't be built without errors.
Let me look into it and integrate the content later this week.

2023-04-05 22:32 UTC, michaelcretzman requested changes
@roshnisarangadharan @thisrohangupta this PR is broken. It can't be built without errors.
Let me look into it and integrate the content later this week.

2023-04-19 22:59 UTC, michaelcretzman commented
Duplicate of https://github.com/harness/developer-hub/pull/1362

2023-04-19 22:59 UTC, closed without merging