[DOC-1235] GameDay documentation
harness/developer-hub pull request #1232
Opened 2023-04-06 05:21 UTC by SmritiSatya

Add GameDay documentation
Add screenshots
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

2023-04-06 06:10 UTC, Saranya-jena requested changes

2023-04-06 06:10 UTC, Saranya-jena commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +2. Click **Start GameDay**. This prepares your GameDay to run the experiments within the GameDay.
On clicking `start gameday` it actually *creates* the experiment. And after going inside a particular gameday run, we can run the experiments. 
Maybe we can mention the experiment creation part?

2023-04-06 06:10 UTC, Saranya-jena commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +2. You can mark an experiment run as complete by clicking **Mark Run as Complete**. This way, you will not be able to run the experiment again. This completed run serves as a checkpoint within the Ga
- You can mark an experiment run as complete -> You can mark gameday run as complete
We can rephrase this entire paragraph. We actually mark a gameday run as complete, once marked we won't be able to rerun the experiments inside that gameday run. We will have to start a new gameday run.

2023-04-06 15:53 UTC, SmritiSatya commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +2. You can add experiments by selecting the ones available in the chaos hub.
I think we are changing chaoshub to chaos hub.

2023-04-17 05:45 UTC, Saranya-jena commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +2. You can add experiments by selecting the ones available in the chaos hub.
okay, I wasn't aware of that. Resolving all the similar comments

2023-04-18 08:14 UTC, deepakbolangady requested changes

2023-04-18 08:14 UTC, deepakbolangady commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +2. Access to a cluster
Is this a K8s cluster? If yes, can we specify that? Which brings me to my next question: are we supporting GameDays only with K8s clusters today?

2023-04-18 08:14 UTC, deepakbolangady commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +### Step 1: Plan your GameDay
Per our style guide, begin with the most meaningful words. Do not include “Step”, “Review”, “Option” at the beginning of headings.

2023-04-18 08:14 UTC, deepakbolangady commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +3. What will you verify or determine by the end of the GameDay?
```suggestion
Address the following questions before proceeding to run a Gameday:
1. Which services should I test?
2. What is the goal of the GameDay? 
3. What should I verify or determine by the end of the GameDay?
```

2023-04-18 08:14 UTC, deepakbolangady commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +1. After creating a GameDay, add experiments to the GameDay by clicking **New Chaos Experiment**.
About "After creating a GameDay": have we created the GameDay at this point? I thought adding experiments was part of creating the GameDay (per the seven-step process outlined earlier).

2023-04-18 08:14 UTC, deepakbolangady commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +You can add up to 20 experiments to every GameDay, and every chaos experiment can be executed on a different chaos infrastructure!
```suggestion
You can add up to 20 experiments to every GameDay, and every chaos experiment can be executed on a different chaos infrastructure.
```

2023-04-18 08:14 UTC, deepakbolangady commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +5. To view the pipeline of an experiment, you can select one by clicking it. This displays a preview of the experiment.
```suggestion
5. To view a preview of the experiment's pipeline, select the experiment.
```
(Is that accurate?)

2023-04-18 15:47 UTC, SmritiSatya commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +At every step in implementing a GameDay, you will either find a glitch in the system that is addressed or gain confidence in your application.
Yes, @deepakbolangady

2023-04-18 15:49 UTC, SmritiSatya commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +Running a GameDay verifies the system at scale, and in production.
I somehow think production environment isn't safe, so I removed that sentence. Safe environment is something that is not in production I believe.

2023-04-18 15:53 UTC, SmritiSatya commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +2. Access to a cluster
Any experiment would run on cluster, but the type depends on the platform- AWS, Kubernetes, etc. Hence I did not specify K8s.

2023-04-18 15:59 UTC, SmritiSatya commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +1. After creating a GameDay, add experiments to the GameDay by clicking **New Chaos Experiment**.
By 'creating a GameDay', we are creating a template. Adding experiments is another step. I will rephrase it.

2023-04-18 16:03 UTC, SmritiSatya commented on docs/chaos-engineering/configure-chaos-experiments/gameday/run-gameday.md
> +5. To view the pipeline of an experiment, you can select one by clicking it. This displays a preview of the experiment.
Can we say "5. Select the experiment to see a preview of the experiment's pipeline."?

2023-05-04 05:50 UTC, Jonsy13 approved these changes

2023-05-05 11:49 UTC, merged