Cds 57915 terraform cloud docs
harness/developer-hub pull request #1342
Opened 2023-04-18 22:20 UTC by michaelcretzman

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* https://harness.atlassian.net/browse/CDS-57915

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-04-19 09:13 UTC, alebuh requested changes

2023-04-19 09:13 UTC, alebuh commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +A workspace version refers to a specific version of the Terraform configuration files associated with a particular workspace. Each time a change is made to the Terraform configuration files in a work
Terraform version has nothing with the version of Terraform configuration files. We are just specifying terraform version that we want to be used for this command (ex: 1.3.0, 1.0.2...). Terraform Cloud has to have this Terraform version supported in order to execute this run.

2023-04-19 09:13 UTC, alebuh commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +This setting is supported in the following run types: Plan, Refresh, Plan Only, Plan and Apply, Plan and Destroy.
Only for Refresh

2023-04-19 09:13 UTC, alebuh commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +This setting is supported in the following run types: Plan, Refresh, Plan Only, Plan and Apply, Plan and Destroy.
Only for Plan and Plan Only

2023-04-19 09:13 UTC, alebuh commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +cat "<+execution.steps.Plan_Step.plan.jsonFilePath>"
same here

2023-04-19 09:13 UTC, alebuh commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +<+pipeline.stages.TfStage.spec.execution.steps.TfPlan.plan.jsonFilePath>
same here

2023-04-19 09:13 UTC, alebuh commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +<+execution.steps.[Terraform Plan step Id].plan.jsonFilePath>
An example is not valid, as we don't use step fqn, we are using provisionerId instead of it. It's explained under the Print plan expression section. <+terraformCloudPlanJson."id">

2023-04-19 23:15 UTC, michaelcretzman commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +This setting is supported in the following run types: Plan, Refresh, Plan Only, Plan and Apply, Plan and Destroy.
I see it in Plan, Plan Only, Plan and Apply, Plan and Destroy.

2023-04-19 23:23 UTC, michaelcretzman commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +- **Destroy**: The plan will be applied by a Terraform Cloud step using the **Plan and Destroy** run type later in your stage.
thanks. I'll add think link.

2023-04-19 23:23 UTC, michaelcretzman commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +This setting is supported in the following run types: Plan, Refresh, Plan Only, Plan and Apply, Plan and Destroy.
I only see it in Plan Only.

2023-04-19 23:23 UTC, michaelcretzman commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +Select the workspace version to run.
ah, thanks.

2023-04-19 23:23 UTC, michaelcretzman commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +<+execution.steps.[Terraform Plan step Id].plan.jsonFilePath>
got it. thanks.

2023-04-20 07:45 UTC, alebuh commented on docs/continuous-delivery/cd-infrastructure/terraform-infra/terraform-cloud-deployments.md
> +This setting is supported in the following run types: Plan, Refresh, Plan Only, Plan and Apply, Plan and Destroy.
you are right, my mistake. It's for Plan Only

2023-04-20 07:46 UTC, alebuh approved these changes

2023-04-20 16:37 UTC, merged