SRM Docs Migration
harness/developer-hub pull request #139
Opened 2022-11-22 19:53 UTC by SudheendraKatte

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?
Migration. for SRM docs from "Help Docs" to "Developers Hub"

If tied to an Issue, list the Issue(s) here:

[
](https://harness.atlassian.net/browse/DOC-2276)

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

Tested Locally

2022-11-22 20:46 UTC, KimberlyFields requested changes
I found a few issues with numbering and a table.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +1. The **Overall Health Score** timeline provides a high level overview of the health of a service. You can hover over the timeline to view the latest health score along with date and time. The timel
The number resets to 1 instead of continuing to 6.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +1. To view the service health score for a specific time slot along with the count of anomalies, metrics, and logs, click the time slot on the **Health Score Timeline**. A time window gets selected wh
The number resets to 1.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +1. In **Changes**, you can view breakdown of the following events:
The number resets to 1.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +1. Click an event in **Changes** to drill down following details:
The number resets to 1.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +2. In **Metrics & Logs**, you can view metrics collected at regular intervals and log data.
The numbering resets again.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +1. The **Changes Timeline** provides an instant high-level overview of your Services. You can hover over the timeline to view the status of change events associated with deployment, infrastructure ch
The number resets to 1.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +1. In **Changes**, you can view the list of all the change events along with the following details:
The number resets to 1.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/slo-management-quickstart.md
> +![](./static/slo-management-quickstart-05.png
Missing a closing parentheses, so the graphic does not display.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/slo-management-quickstart.md
> +1. You can view the summary of each SLO on the SLO card with the following details:
The number resets to 1. It should be 5.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/slo-management-quickstart.md
> +1. Click the vertical ellipsis icon at the top-right of the SLO card to perform the following actions:![](./static/slo-management-quickstart-22.png)
The number resets to 5.

2022-11-22 20:46 UTC, KimberlyFields commented on docs/service-reliability-management/use-service-reliability-management/error-tracking-category/install-the-error-tracking-agent.md
> + |
This table does not render correctly.

2022-11-23 17:45 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis-quickstart.md
> +1. The **Overall Health Score** timeline provides a high level overview of the health of a service. You can hover over the timeline to view the latest health score along with date and time. The timel
Corrected the numbering and did content reorg.

2022-11-23 18:20 UTC, KimberlyFields submitted a review, later dismissed
@SudheendraKatte I found a few more little errors. After you fix those items, you can go ahead and merge this PR.

2022-11-23 18:20 UTC, KimberlyFields commented on docs/service-reliability-management/howtos-service-reliability-management/slo-management-quickstart.md
> +	3. Click **Save**. The recalculated Error Budget appears in the **Error Budget Remaining** donut chart**.**
This should be number 4.

2022-11-23 18:20 UTC, KimberlyFields commented on docs/service-reliability-management/use-service-reliability-management/error-tracking-category/install-the-error-tracking-agent.md
> +| HotSpot | `-Xshare:off -XX:-UseTypeSpeculation` |
This table does not render correctly.

2022-11-23 18:20 UTC, KimberlyFields commented on docs/service-reliability-management/use-service-reliability-management/monitored-service-template/monitored-service-template-quickstart.md
> +Environments represent your deployment targets QA, Prod, and so on. When you add an Environment to a Monitored Service, it allows you to associate change records, actions, logs, metrics, and SLO’s to
Incorrect numbering

2022-11-23 19:08 UTC, SudheendraKatte commented on docs/service-reliability-management/use-service-reliability-management/error-tracking-category/install-the-error-tracking-agent.md
> +| HotSpot | `-Xshare:off -XX:-UseTypeSpeculation` |
Known issue. Will be fixed later.

2022-11-23 19:09 UTC, SudheendraKatte commented on docs/service-reliability-management/use-service-reliability-management/monitored-service-template/monitored-service-template-quickstart.md
> +Environments represent your deployment targets QA, Prod, and so on. When you add an Environment to a Monitored Service, it allows you to associate change records, actions, logs, metrics, and SLO’s to
Renders as expected in HTML output.

2022-11-23 19:09 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/slo-management-quickstart.md
> +	3. Click **Save**. The recalculated Error Budget appears in the **Error Budget Remaining** donut chart**.**
Corrected

2022-11-23 19:42 UTC, KimberlyFields approved these changes

2022-11-23 19:49 UTC, merged