Chore(lambda-chaos): Adds docs for AWS Lambda chaos to update function memory and timeout
harness/developer-hub pull request #143
Opened 2022-11-24 07:15 UTC by uditgaurav

# Harness Developer Pull Request

It will add the docs for lambda function chaos to update memory limit and timeout value for a certain chaos duration to check the function stability.

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-11-24 09:12 UTC, avaakash requested changes

2022-11-24 09:12 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +        <td> </td>
We can give an example here

2022-11-24 09:12 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-memory.md
> +        <td> Period to wait before and after injection of chaos in sec </td>
```suggestion
        <td> Period to wait before and after injection of chaos in seconds </td>
```

2022-11-24 09:12 UTC, avaakash commented on docs/chaos-engineering/chaos-faults/aws/lambda-update-function-timeout.md
> +        <td> Period to wait before and after injection of chaos in sec </td>
```suggestion
        <td> Period to wait before and after injection of chaos in seconds </td>
```

2022-11-24 10:12 UTC, avaakash submitted a review, later dismissed

2022-11-29 14:03 UTC, neelanjan00 approved these changes

2022-12-06 06:44 UTC, SmritiSatya approved these changes

2022-12-06 06:44 UTC, merged