CDS-57577-CDS-54890
harness/developer-hub pull request #1436
Opened 2023-04-24 17:47 UTC by roshnisarangadharan

Added info about Bitbucket connector and GitOpsSync step

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-04-25 02:07 UTC, meenaravichandran1 approved these changes

2023-04-25 08:49 UTC, StrawberryPad requested changes
I was a bit confused by the expandable sections, and made some other style/formatting comments.

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +When you select **Sync**, Harness will use the ApplicationSet to create the new Harness Applications for the dev and prod clusters.
```suggestion
When you select **Sync**, Harness uses the ApplicationSet to create the new Harness Applications for the dev and prod clusters.
```

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +2. In the Sync settings, select **Synchronize**. Synchronization will take a minute.
I'm not sure what the image above this is showing me. I also don't see Sync settings in the image, so this step is a bit confusing. Maybe in Step 1 you could give a bit more context or explain what the image is... like 'the xx page appears' or something before the image.

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +<summary>SYNC button</summary>
If this is a procedure the user should do or can do, I don't think it should be hidden in an expandable block.

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +<summary>GitOpsSync execution step</summary>
Same comment. Is this a procedure the user can/should do? If so, it shouldn't be in an expandable.

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +```mdx-code-block
Can the tabs code block be indented?

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
>  2. Enter the following Github Connector settings:
The settings shouldn't be numbered steps. More of a bullet list.

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
>  2. Enter the following Github Connector settings:
(I know that's beyond what you're doing. :-) But it's glaring.

2023-04-25 08:49 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
>     You will store the PAT in a [Harness Text Secret](/docs/platform/Secrets/add-use-text-secrets). For details on Secrets Management, go to [Harness Secrets Management Overview](/docs/platform/Secret
Please indent lines 394 (image) and 396 ("You will store the PAT...")

2023-04-26 06:12 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
>  2. Enter the following Github Connector settings:
@StrawberryPad It is a procedure, shouldn't it be numbered?

2023-04-26 08:13 UTC, SudheendraKatte approved these changes
Approved with comments.

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +    5. **Authentication:** select **Username and Token**. For the Token, you'll need to use a Personal Access Token (PAT) from Bitbucket. If you are logged into Bitbucket, just go to [HTTP access tok
Use a Personal Access Token (PAT) from Bitbucket. If you are logged into Bitbucket, go to [HTTP access tokens](https://confluence.atlassian.com/bitbucketserver/http-access-tokens-939515499.html). You must provide an account-level app password or token. Repo-level tokens are not supported.

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +       You will store the PAT in a [Harness Text Secret](/docs/platform/Secrets/add-use-text-secrets). For details on Secrets Management, go to [Harness Secrets Management Overview](/docs/platform/Se
```suggestion
       Store the PAT in a [Harness Text Secret](/docs/platform/Secrets/add-use-text-secrets). For details on Secrets Management, go to [Harness Secrets Management Overview](/docs/platform/Secrets/Secrets-Management/harness-secret-manager-overview).
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +4. In **Connect to the provider**, select **Connect through Harness Platform**., and then click **Save and Continue**.
```suggestion
4. In **Connect to the provider**, select **Connect through Harness Platform**, and then click **Save and Continue**.
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/harness-git-ops-application-set-tutorial.md
> +5. When the **Connection Test** in complete, click **Continue**.
```suggestion
5. After the Connection Test is complete, click **Continue**.
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +A sync brings the live state to its desired state by applying the declarative description. Sync will sync the desired Git state with the live cluster state.
Suggestion:

Sync is a process that ensures that the live state of a system matches its desired state by applying a declarative description. This process involves synchronizing the desired Git state with the live cluster state.

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +1. In your GitOps project, go to **Deployments >** **GitOps>** **Applications**, and select your application.
```suggestion
1. In your GitOps project, go to **Deployments** > **GitOps** > **Applications**, and then select your application.
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +   * Select the more options icon, then select **Sync**.
```suggestion
   * Select the more options icon, and then select **Sync**.
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +   * Select the application, then select **SYNC**.
```suggestion
   * Select the application, and then select **SYNC**. 
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +3. Configure the sync options, then select **Synchronize**.
```suggestion
3. Configure the sync options, and then select **Synchronize**.
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +   :::
```suggestion
   ::: 
   
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +   :::info
```suggestion
   
   :::info
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +2. Select **Add Step**, then select the **GitOpsSync** step.
```suggestion
2. Select **Add Step**, and then select the **GitOpsSync** step.
```

2023-04-26 08:13 UTC, SudheendraKatte commented on docs/continuous-delivery/gitops/sync-gitops-applications.md
> +After the sync, the resources will look like this in Harness:
Suggestion:

Here is how the resources would look in Harness after the sync process is complete.

2023-04-26 08:45 UTC, merged