[SMP-1201] Add air-gapped installation topic
harness/developer-hub pull request #1437
Opened 2023-04-24 18:17 UTC by brian-f-harness

Add SMP air-gapped installation topic

For reviewers, a preview is available.

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-04-24 20:29 UTC, pratmit requested changes
Modified the file to remove the cluster requirements.

2023-04-24 22:43 UTC, swapnil-harness reviewed
Please hold off on this for one more day, there will be some delta, I'll confirm by tomorrow.

2023-04-25 23:25 UTC, brian-f-harness commented
> Please hold off on this for one more day, there will be some delta, I'll confirm by tomorrow.

@swapnil-harness is there an update on this feature?

2023-04-26 04:34 UTC, swapnil-harness commented
> > Please hold off on this for one more day, there will be some delta, I'll confirm by tomorrow.
> 
> @swapnil-harness is there an update on this feature?

Hi Brian, yes made the changes in code and updated the doc as well. Thanks!

2023-04-26 18:46 UTC, pratmit approved these changes
LGTM

2023-04-26 19:45 UTC, douglas-j-bothwell submitted a review, later dismissed

2023-04-26 19:45 UTC, douglas-j-bothwell commented on docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
> +This document explains how to use Helm to install the Harness Self-Managed Enterprise Edition in an air-gapped environment and how to obtain and transfer Docker images to a private registry secure ac
```suggestion
This topic explains how to use Helm to install the Harness Self-Managed Enterprise Edition in an air-gapped environment and how to obtain and transfer Docker images to a private registry with secure access. The steps include pulling Docker images, saving images as .tgz files, uploading to Google Cloud storage, downloading Helm charts, and pushing charts to your private repositories. This process ensures secure and seamless deployment of the Harness Self-Managed Enterprise Edition in restricted, offline environments.
```

2023-04-26 19:45 UTC, douglas-j-bothwell commented on docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
> +Air-gapped environments are characterized by a lack of direct access to the internet, which provides an added layer of security for sensitive data and systems. This isolation poses unique challenges
```suggestion
Air-gapped environments are characterized by a lack of direct access to the internet, which provides an added layer of security for sensitive data and systems. This isolation poses unique challenges to deploy and update software applications, as standard methods of accessing resources, such as Docker images, are not possible.
```

2023-04-26 19:45 UTC, douglas-j-bothwell commented on docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-in-an-air-gapped-environment.md
> +**To save your Docker images**
Note sure you need this paragraph, just repeats the heading

2023-04-26 21:07 UTC, douglas-j-bothwell approved these changes

2023-04-26 21:12 UTC, merged