chore(chaos): Update 'experiment' to 'fault' in fault docs and update tutorials
harness/developer-hub pull request #150
Opened 2022-11-28 11:46 UTC by neelanjan00

# Harness Developer Pull Request
- Update 'experiment' to 'fault' in all fault docs
- Update chaos tutorials to update demo app repo to `githuub.com/chaosnative/harness-chaos-demo`

## What Type of PR is This?
- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-11-29 14:48 UTC, avaakash requested changes

2022-11-29 14:51 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/common-tunables-for-all-faults.md
> +[embedmd]:# (./static/manifest/common/chaos-interval.yaml yaml)
Actually the title is wrong, it is for Chaos Interval.

2022-11-29 14:54 UTC, neelanjan00 commented on docs/chaos-engineering/chaos-faults/common-tunables-for-all-faults.md
>  It defines the period to wait before and after the injection of chaos. You can tune it using the `RAMP_TIME` environment variable. It is in unit of seconds.
I don't think that the example is of chaos lib, please recheck, chaos lib is at line #172.

2022-11-30 22:55 UTC, ravilach commented
Looks like a few broken links. Can always run `yarn build` locally to find also.

```
- On source page path = /docs/chaos-engineering/chaos-faults/aws/ecs-agent-stop:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)

   -> linking to ./aws-experiments-tunables (resolved as: /docs/chaos-engineering/chaos-faults/aws/aws-experiments-tunables)


- On source page path = /docs/chaos-engineering/chaos-faults/aws/ecs-container-cpu-hog:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)

   -> linking to ./aws-experiments-tunables (resolved as: /docs/chaos-engineering/chaos-faults/aws/aws-experiments-tunables)


- On source page path = /docs/chaos-engineering/chaos-faults/aws/ecs-container-io-stress:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)

   -> linking to ./aws-experiments-tunables (resolved as: /docs/chaos-engineering/chaos-faults/aws/aws-experiments-tunables)


- On source page path = /docs/chaos-engineering/chaos-faults/aws/ecs-container-memory-hog:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)

   -> linking to ./aws-experiments-tunables (resolved as: /docs/chaos-engineering/chaos-faults/aws/aws-experiments-tunables)


- On source page path = /docs/chaos-engineering/chaos-faults/aws/ecs-container-network-latency:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)

   -> linking to ./aws-experiments-tunables (resolved as: /docs/chaos-engineering/chaos-faults/aws/aws-experiments-tunables)


- On source page path = /docs/chaos-engineering/chaos-faults/aws/ecs-container-network-loss:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)

   -> linking to ./aws-experiments-tunables (resolved as: /docs/chaos-engineering/chaos-faults/aws/aws-experiments-tunables)


- On source page path = /docs/chaos-engineering/chaos-faults/aws/ecs-instance-stop:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)

   -> linking to ./aws-experiments-tunables (resolved as: /docs/chaos-engineering/chaos-faults/aws/aws-experiments-tunables)


- On source page path = /docs/chaos-engineering/chaos-faults/azure/azure-web-app-access-restrict:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)


- On source page path = /docs/chaos-engineering/chaos-faults/azure/azure-web-app-stop:

   -> linking to ../common-tunables-for-all-experiments (resolved as: /docs/chaos-engineering/chaos-faults/common-tunables-for-all-experiments)
```

2022-12-01 05:44 UTC, neelanjan00 commented
Thanks for pointing put @ravilach! These faults were added later and hence had not been updated for the changed file names. FIxed.

2022-12-02 11:50 UTC, SmritiSatya commented on docs/chaos-engineering/chaos-faults/aws/aws-fault-tunables.md
> +
It specifies whether or not AWS EC2 instances are part of managed nodeGroups. If the instances belong to the managed nodeGroups, provide `MANAGED_NODEGROUP` as `enable` else provide it as `disable`. The default value is `disabled`.

Use the following example to tune it:

2022-12-07 06:50 UTC, merged