PL Migrated Doc Updates
harness/developer-hub pull request #152
Opened 2022-11-29 14:37 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-11-29 23:48 UTC, KimberlyFields requested changes
The image files are missing from this PR. All of the references to screenshots still point to the images in Helpdocs.

2022-11-30 22:56 UTC, ravilach commented
Some broken links. Can find locally also by running `yarn build`.

Links:

```
 On source page path = /docs/platform/Connectors/connect-to-an-artifact-repo:

   -> linking to ../6_Security/add-secrets-manager.md (resolved as: /docs/platform/6_Security/add-secrets-manager.md)


- On source page path = /docs/platform/Connectors/git-hub-app-support:

   -> linking to ../6_Security/harness-secret-manager-overview.md (resolved as: /docs/platform/6_Security/harness-secret-manager-overview.md)


- On source page path = /docs/platform/Git-Experience/harness-git-experience-quickstart:

   -> linking to ../6_Security/harness-secret-manager-overview.md (resolved as: /docs/platform/6_Security/harness-secret-manager-overview.md)


- On source page path = /docs/platform/Role-Based-Access-Control/ref-access-management/api-permissions-reference:

   -> linking to /article/e5p4hdq6bd

   -> linking to /article/tdoad7xrh9


- On source page path = /docs/platform/Role-Based-Access-Control/ref-access-management/permissions-reference:

   -> linking to /article/vz5cq0nfg2-rbac-in-harness#rbac_scope (resolved as: /article/vz5cq0nfg2-rbac-in-harness)


- On source page path = /docs/platform/Security/add-a-google-cloud-secret-manager:

   -> linking to add-google-kms-secrets-manager.md (resolved as: /docs/platform/Security/add-google-kms-secrets-manager.md)

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)

   -> linking to add-file-secrets.md (resolved as: /docs/platform/Security/add-file-secrets.md)

   -> linking to add-an-aws-kms-secrets-manager.md (resolved as: /docs/platform/Security/add-an-aws-kms-secrets-manager.md)

   -> linking to add-an-aws-secret-manager.md (resolved as: /docs/platform/Security/add-an-aws-secret-manager.md)

   -> linking to azure-key-vault.md (resolved as: /docs/platform/Security/azure-key-vault.md)

   -> linking to /s65mzbyags-add-hashicorp-vault


- On source page path = /docs/platform/Security/add-an-aws-kms-secrets-manager:

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)

   -> linking to add-use-text-secrets.md (resolved as: /docs/platform/Security/add-use-text-secrets.md)


- On source page path = /docs/platform/Security/add-google-kms-secrets-manager:

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)

   -> linking to add-file-secrets.md (resolved as: /docs/platform/Security/add-file-secrets.md)


- On source page path = /docs/platform/Security/add-hashicorp-vault:

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)

   -> linking to add-use-text-secrets.md (resolved as: /docs/platform/Security/add-use-text-secrets.md)


- On source page path = /docs/platform/Security/add-secrets-manager:

   -> linking to add-an-aws-kms-secrets-manager.md (resolved as: /docs/platform/Security/add-an-aws-kms-secrets-manager.md)

   -> linking to add-hashicorp-vault.md (resolved as: /docs/platform/Security/add-hashicorp-vault.md)

   -> linking to azure-key-vault.md (resolved as: /docs/platform/Security/azure-key-vault.md)

   -> linking to add-google-kms-secrets-manager.md (resolved as: /docs/platform/Security/add-google-kms-secrets-manager.md)

   -> linking to add-an-aws-secret-manager.md (resolved as: /docs/platform/Security/add-an-aws-secret-manager.md)

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)


- On source page path = /docs/platform/Security/azure-key-vault:

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)

   -> linking to azure-key-vault.md#create-azure-reader-role (resolved as: /docs/platform/Security/azure-key-vault.md)

   -> linking to add-use-text-secrets.md (resolved as: /docs/platform/Security/add-use-text-secrets.md)


- On source page path = /docs/platform/Security/custom-secret-manager:

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)

   -> linking to add-use-text-secrets.md (resolved as: /docs/platform/Security/add-use-text-secrets.md)


- On source page path = /docs/platform/Security/disable-harness-secret-manager:

   -> linking to add-secrets-manager.md (resolved as: /docs/platform/Security/add-secrets-manager.md)

   -> linking to harness-secret-manager-overview.md (resolved as: /docs/platform/Security/harness-secret-manager-overview.md)

   -> linking to add-google-kms-secrets-manager.md (resolved as: /docs/platform/Security/add-google-kms-secrets-manager.md)

   -> linking to add-an-aws-kms-secrets-manager.md (resolved as: /docs/platform/Security/add-an-aws-kms-secrets-manager.md)

   -> linking to add-an-aws-secret-manager.md (resolved as: /docs/platform/Security/add-an-aws-secret-manager.md)

   -> linking to azure-key-vault.md (resolved as: /docs/platform/Security/azure-key-vault.md)

   -> linking to add-hashicorp-vault.md (resolved as: /docs/platform/Security/add-hashicorp-vault.md)


- On source page path = /docs/platform/Security/ref-security/secrets-and-log-sanitization:

   -> linking to ../add-use-text-secrets.md (resolved as: /docs/platform/Security/add-use-text-secrets.md)

   -> linking to ../add-file-secrets.md (resolved as: /docs/platform/Security/add-file-secrets.md)

   -> linking to ../add-use-ssh-secrets.md (resolved as: /docs/platform/Security/add-use-ssh-secrets.md)

   -> linking to ../add-secrets-manager.md (resolved as: /docs/platform/Security/add-secrets-manager.md)


- On source page path = /docs/platform/Security/reference-existing-secret-manager-secrets:

   -> linking to add-an-aws-kms-secrets-manager.md (resolved as: /docs/platform/Security/add-an-aws-kms-secrets-manager.md)

   -> linking to add-an-aws-secret-manager.md (resolved as: /docs/platform/Security/add-an-aws-secret-manager.md)

   -> linking to add-hashicorp-vault.md (resolved as: /docs/platform/Security/add-hashicorp-vault.md)


- On source page path = /docs/platform/Templates/create-a-secret-manager-template:

   -> linking to ../6_Security/harness-secret-manager-overview.md (resolved as: /docs/platform/6_Security/harness-secret-manager-overview.md)

   -> linking to ../6_Security/add-use-ssh-secrets.md (resolved as: /docs/platform/6_Security/add-use-ssh-secrets.md)

   -> linking to ../6_Security/custom-secret-manager.md (resolved as: /docs/platform/6_Security/custom-secret-manager.md)


- On source page path = /docs/platform/Terraform/harness-terraform-provider:

   -> linking to ../3_Authentication/provision-users-with-okta-scim.md (resolved as: /docs/platform/3_Authentication/provision-users-with-okta-scim.md)

   -> linking to ../3_Authentication/provision-users-and-groups-with-one-login-scim.md (resolved as: /docs/platform/3_Authentication/provision-users-and-groups-with-one-login-scim.md)

   -> linking to ../3_Authentication/provision-users-and-groups-using-azure-ad-scim.md (resolved as: /docs/platform/3_Authentication/provision-users-and-groups-using-azure-ad-scim.md)
```

2022-12-02 19:57 UTC, KimberlyFields requested changes

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/13_Templates/create-pipeline-template.md
> +* Review [Permissions Reference](../4_Role-Based Access Control/ref-access-management/permissions-reference.md#sort=relevancy&f:@commonsource=[NextGen%20Docs]) to know about the permissions required
The link syntax appears instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/13_Templates/create-pipeline-template.md
> +You need Create/Edit, Delete, and Access permissions on Templates to create a Pipeline Template. See [Permissions Reference](../4_Role-Based Access Control/ref-access-management/permissions-reference
The link syntax appears instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/13_Templates/create-pipeline-template.md
> +You can add Templates at any [scope](../4_Role-Based Access Control/rbac-in-harness.md) in Harness.
The link syntax appears instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/13_Templates/create-pipeline-template.md
> +
Check the rendered output and fix text that wraps around images instead of displaying below them.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/13_Templates/template.md
> +title: Templates Overview
Move this topic to the beginning of the Templates section. It's currently near the bottom.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/harness-governance-quickstart.md
> +
Check the rendered content and fix text that wraps around images instead of appearing below the images.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +
The numbering is incorrect.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +1. Click **Save**.
Numbering is incorrect.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +1. Click **Test**. Depending on whether the updated policy successfully applies to the existing Feature Flag, you receive one of the following:
Numbering is incorrect.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +* **I****nput failed Policy Evaluation**: The Feature Flag doesn’t adhere to the updated policy.
Remove the asterisks from the middle of Input.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +![](https://lh4.googleusercontent.com/f2GbzvnKR5dw5iVaHRfr695eq16qFYya38-I9tSzDH37UZRPljOzGaLmGuGBLdtsWvtQzWDgL8uNRfmLjy-gsWepN1HKw8XXrgpAFo71o13aT0VAp-JJ3noiRvPlumo_-NfG0crI)1. In **Name**, enter th
The image does not appear. Also, the step should be on a separate line. Be sure the step number is step 2. Currently, step 1 is repeated.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +4. In **On what event should the Policy Set be evaluated**, select **On save**, then click **Continue**.
These steps are merged into a paragraph.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +2. The Policy Set is automatically set to Enforced, to make it unenforced, toggle off the **Enforced** button.
Numbering is incorrect.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +* **Error and exit:** If a policy isn’t met when the Feature Flag is evaluated, you receive an error and are exited without saving the flag.
All of this text is merged into one paragraph.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +2. When you've made all the changes, click **Save**.
Numbering is incorrect.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +2. Click **Apply**, then click **Finish**.
Numbering is incorrect.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +1. To view further details of a particular evaluation, click on it and expand the relevant evaluation.
Numbering is incorrect.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/15_Audit-Trail/audit-trail.md
> +* [Access Management (RBAC) Overview](../4_Role-Based Access Control/rbac-in-harness.md)
The link syntax displays instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/16_APIs/api-quickstart.md
> +**Looking for the API reference docs?** See [Harness API Reference Docs](https://harness.io/docs/api/).### Objectives
Move ### Objectives to a separate line.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/16_APIs/api-quickstart.md
> +The API requests in this topic use curl, but Harness supports multiple languages, such as Go, Java, and Node.js. The [Harness API Reference Docs](https://harness.io/docs/api/) provides examples for a
Move ### Before you begin to a separate line.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/16_APIs/api-quickstart.md
> +* Make sure your Harness account has the required permissions to Create, Edit, Delete, and View the Harness resources you are creating via API. Any of the following default roles are sufficient: Acco
The link syntax appears instead of the links for these 3 bullet items.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/16_APIs/api-quickstart.md
> +For an overview of Harness API keys, see [Add and Manage API Keys](../4_Role-Based Access Control/add-and-manage-api-keys.md).Let's create the API key and its Personal Access Token.
The link syntax appears instead of the link

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/16_APIs/harness-rest-api-reference.md
> +For an overview of Harness API keys, see [Add and Manage API Keys](../4_Role-Based Access Control/add-and-manage-api-keys.md).Let's create the API key and its Personal Access Token.
The link syntax appears instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/18_Dashboards/create-dashboards.md
> +
Check the rendered content and fix the text that wraps around the images instead of displaying below the images.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/18_Dashboards/download-dashboard-data.md
> +8. Click **Download** to initiate the download. A new tab in your browser will open, showing the status of your download.![](./static/download-dashboard-data-23.png)
All of these steps are merged into a single paragraph instead of displaying on separate lines.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/18_Dashboards/share-dashboards.md
> +![](https://docs.looker.com/assets/images/hourly-dash-beta-2100.png)
These images do not display.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/20_References/permissions-and-ports-for-harness-connections.md
> +|  |  |  |  |
This table does not render correctly.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/20_References/renaming-entities-and-resources.md
> +
Check the rendered output and fix text that appears next to images instead of below them.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/20_References/renaming-entities-and-resources.md
> +For information on Organizations and Projects, see [Organizations and Projects Overview](../1_Organizations and Projects/projects-and-organizations.md).For example, here are two GitHub Connectors wit
The link syntax displays instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/20_References/runtime-inputs.md
> +
Check the rendered output and fix text that appears next to images instead of below them.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/20_References/tags-reference.md
> +* Harness variable expressions cannot be used in Tags. See [Built-in Harness Variables Reference](../12_Variables and Expressions/harness-variables.md).
The link syntax appears instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/20_References/tags-reference.md
> +You can reference Tags using [Harness expressions](../12_Variables and Expressions/harness-variables.md).
The link syntax appears instead of the link.

2022-12-02 19:57 UTC, KimberlyFields commented on docs/platform/20_References/tags-reference.md
> +* [Built-in Harness Variables Reference](../12_Variables and Expressions/harness-variables.md)
The link syntax appears instead of the link.

2022-12-05 05:01 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-guide/build-custom-delegate-images-with-third-party-tools.md
> +For information about creating a Terraform Plan, see [Provision with the Terraform Apply Step](https://docs.harness.io/article/hdclyshiho).
Not sure why the SaaS Release Notes wiki link is here. I have formatted the image and sentence space.

2022-12-05 06:58 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-guide/secure-delegates-with-tokens.md
> +![](./static/secure-delegates-with-tokens-03
Done.

2022-12-05 06:58 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-guide/secure-delegates-with-tokens.md
> +![](./static/secure-delegates-with-tokens-02
Done.

2022-12-05 06:59 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-guide/secure-delegates-with-tokens.md
> +The new token is created and its value is copied to your system clipboard. The new token also appears in the list using the name you gave it.
Done.

2022-12-05 07:01 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-guide/select-delegates-with-selectors.md
> +For detailed information on how delegates are selected during execution, see [Delegates Overview](../delegates-overview.md).
Done.

2022-12-05 07:05 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +* [Projects and Organizations](../../1_Organizations and Projects/projects-and-organizations.md)
Done.

2022-12-05 07:19 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +|  |  |  |
Done.

2022-12-05 07:30 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-kubernetes/install-harness-delegate-on-kubernetes.md
> +![](./static/install-harness-delegate-on-kubernetes-15
Done.

2022-12-05 07:32 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-kubernetes/install-harness-delegate-using-helm.md
> +3. Modify the proxy settings and save the file.![](./static/install-harness-delegate-using-helm-04.png)
Done.

2022-12-05 07:44 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-kubernetes/install-harness-delegate-using-helm.md
> +2. In **Delegate Permissions**, select the permissions you want to grant the Delegate.
Done.

2022-12-05 07:44 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-kubernetes/install-harness-delegate-using-helm.md
> +Installation could take several minutes.
Done.

2022-12-05 07:45 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-kubernetes/install-harness-delegate-using-helm.md
> +1. Copy and run the provided commands.![](./static/install-harness-delegate-using-helm-05.png)
Done.

2022-12-05 07:46 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-kubernetes/install-harness-delegate-using-helm.md
> +1. If Harness Delegate was successfully installed, click **Done**.
Done.

2022-12-05 07:46 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegate-install-kubernetes/install-harness-delegate-using-helm.md
> +From **Apply YAML and verify connection**, copy the instructions to the command line.
Done.

2022-12-05 07:50 UTC, rashminandasahoo commented on docs/platform/2_Delegates/delegates-overview.md
> +---
I have fixed this. However, I have not reorganised any content for Delegates, Pipelines and Triggers. I would leave it to the assigned writer to take care of it post my migration activity.

2022-12-05 08:51 UTC, rashminandasahoo commented on docs/platform/3_Authentication/2-two-factor-authentication.md
> +5. Obtain the code from your 2FA token generator app, and enter it. You can then log into your Harness account.
Done

2022-12-05 08:56 UTC, rashminandasahoo commented on docs/platform/3_Authentication/2-two-factor-authentication.md
> +6. Slide the **Enforce Two Factor Authentication** setting on. This prompt asks for a confirmation to enable 2FA for all the users:
Done.

2022-12-05 09:01 UTC, rashminandasahoo commented on docs/platform/3_Authentication/3-single-sign-on-saml.md
> +![](./static/single-sign-on-saml-59.png)1. Click **Next** and then click **Finish.**
Done.

2022-12-05 09:04 UTC, rashminandasahoo commented on docs/platform/3_Authentication/3-single-sign-on-saml.md
> +6. Link the SAML SSO Provider to the Harness User Group. You can create a new User Group or use an existing Group so long as your Harness User account is a member and that User account is registered
Done.

2022-12-05 13:19 UTC, rashminandasahoo commented on docs/platform/3_Authentication/3-single-sign-on-saml.md
> +2. Enter **app.harness.io** in the **Identifier (Entity ID)** field.![](./static/single-sign-on-saml-82.png)
Done.

2022-12-05 13:25 UTC, rashminandasahoo commented on docs/platform/3_Authentication/3-single-sign-on-saml.md
> +If you use a custom Harness subdomain in any Harness version, like **example.harness.io**, use that URL.1. In **Home**, click **Authentication** under **ACCOUNT SETUP**. **The Authentication: Configu
Done.

2022-12-05 13:27 UTC, rashminandasahoo commented on docs/platform/3_Authentication/3-single-sign-on-saml.md
> +4. Select **Azure** under **Select a SAML Provider**. The settings for Azure setup are displayed:![](./static/single-sign-on-saml-84.png)
Done.

2022-12-05 13:38 UTC, rashminandasahoo commented on docs/platform/3_Authentication/3-single-sign-on-saml.md
> +(./static/single-sign-on-saml-111.png)
Done.

2022-12-05 13:39 UTC, rashminandasahoo commented on docs/platform/3_Authentication/4-single-sign-on-sso-with-oauth.md
> +2. Click **Home**, and then click **Access Control** under **ACCOUNT SETUP**. The **Access Control** page appears.![](./static/single-sign-on-sso-with-oauth-122.png)
Done.

2022-12-05 13:43 UTC, rashminandasahoo commented on docs/platform/3_Authentication/4-single-sign-on-sso-with-oauth.md
> +1. Log into Harness using a Harness User account that is a member of the Administrator User Group with Create/Edit, Delete permissions for Authentication Settings. For information on Harness RBAC, se
Done.

2022-12-05 13:51 UTC, rashminandasahoo commented on docs/platform/3_Authentication/4-single-sign-on-sso-with-oauth.md
> +7. Enable each public OAuth 2.0 provider you want to use for SSO.![](./static/single-sign-on-sso-with-oauth-123.png)
Done.

2022-12-05 13:56 UTC, rashminandasahoo commented on docs/platform/3_Authentication/5-single-sign-on-sso-with-ldap.md
> +4. In **Name Attribute**, enter the common name attribute for the users in your LDAP directory. Typically, this is **cn**. To list all attributes for a user, enter the following dsquery:
Done.

2022-12-05 13:59 UTC, rashminandasahoo commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +* [Access Management (RBAC) Overview](../4_Role-Based Access Control/rbac-in-harness.md)
Done.

2022-12-05 14:00 UTC, rashminandasahoo commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +* Make sure you have a Harness [API Key](../4_Role-Based Access Control/add-and-manage-api-keys.md) and a valid Token under it. The API Key must have all permissions on the Users and User Groups.
Done.

2022-12-05 15:35 UTC, rashminandasahoo commented on docs/platform/3_Authentication/9-switch-account.md
> +|  |  |  |
Done.

2022-12-05 15:43 UTC, rashminandasahoo commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +* [Access Management (RBAC) Overview](../4_Role-Based Access Control/rbac-in-harness.md)
Done.

2022-12-05 15:45 UTC, rashminandasahoo commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +* Make sure you have a Harness [API Key](../4_Role-Based Access Control/add-and-manage-api-keys.md) and a valid Token under it. The API Key must have all permissions on the Users and User Groups.
Done.

2022-12-05 15:49 UTC, rashminandasahoo commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +4. In **SCIM Base URL**, paste the Harness URL you copied.
Done.

2022-12-05 15:51 UTC, rashminandasahoo commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +1. Click **Save**.
Done.

2022-12-05 15:52 UTC, rashminandasahoo commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +7. Click **Approve**. The Provisioning status will turn to Provisioned.
Done.

2022-12-05 15:55 UTC, rashminandasahoo commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +(./static/provision-users-and-groups-with-one-login-scim-130.png)
Done.

2022-12-05 15:58 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/1-rbac-in-harness.md
> +* **Service Account****:** A Service Account is a set of [API Keys](../4_Role-Based-Access-Control/7-add-and-manage-api-keys.md) with a set of permissions assigned to them via role assignment. API Ke
Done.

2022-12-05 16:00 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/4-add-user-groups.md
> +In your **Project/Org/****Account**, and click **Project/Org/Account SETUP**.
Done.

2022-12-05 16:02 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/8-add-resource-groups.md
> +Click **Resource Groups** and then click **New Resource** **Group****.** The New Resource Group settings appear.
Done.

2022-12-05 16:02 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/9-add-manage-roles.md
> +Select your **Project/Org/****Account**, and click **Access Control**.
Done.

2022-12-05 16:12 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/10-set-up-rbac-pipelines.md
> +|  |  |  |  |  |
Done.

2022-12-05 16:13 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/10-set-up-rbac-pipelines.md
> +3. In **User Groups,** click **New User** **Group****.** The New User Group settings appear.
Done.

2022-12-05 16:14 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/10-set-up-rbac-pipelines.md
> +3. In **Resource Groups**, click **New Resource** **Group****.** The New Resource Group settings appear.
Done.

2022-12-05 16:15 UTC, rashminandasahoo commented on docs/platform/5_Notifications/add-smtp-configuration.md
> +* [User Group Notification Preferences](../4_Role-Based Access Control/add-user-groups.md#option-notification-preferences)
Done.

2022-12-05 16:17 UTC, rashminandasahoo commented on docs/platform/5_Notifications/send-notifications-to-microsoft-teams.md
> +* See [User Group Notification Preferences](../4_Role-Based Access Control/add-user-groups.md#option-notification-preferences)
Done

2022-12-05 16:18 UTC, rashminandasahoo commented on docs/platform/5_Notifications/send-notifications-using-slack.md
> +* See [User Group Notification Preferences](../4_Role-Based Access Control/add-user-groups.md#option-notification-preferences)
Done

2022-12-05 16:24 UTC, rashminandasahoo commented on docs/platform/6_Security/4-add-use-ssh-secrets.md
> +1. Enter a **Name** for the SSH Credential and click **Continue**.
Done

2022-12-05 16:25 UTC, rashminandasahoo commented on docs/platform/6_Security/3-add-file-secrets.md
> +This topic assumes you have a Harness Project set up. If not, see [Create Organizations and Projects](../1_Organizations and Projects/create-an-organization.md).
Done

2022-12-05 16:26 UTC, rashminandasahoo commented on docs/platform/6_Security/5-add-secrets-manager.md
> +2. Select **Connectors** in **Setup****.**
Done

2022-12-05 16:27 UTC, rashminandasahoo commented on docs/platform/6_Security/5-add-secrets-manager.md
> +3. Click **Finish**.
Done

2022-12-05 16:40 UTC, rashminandasahoo commented on docs/platform/6_Security/7-add-an-aws-kms-secrets-manager.md
> +This topic assumes you have a Harness Project set up. If not, see [Create Organizations and Projects](../1_Organizations and Projects/create-an-organization.md).
DOne

2022-12-05 16:42 UTC, rashminandasahoo commented on docs/platform/6_Security/7-add-an-aws-kms-secrets-manager.md
> +In **Delegates** **Setup****,** enter [**Selectors**](../2_Delegates/delegate-guide/select-delegates-with-selectors.md#option-select-a-delegate-for-a-connector-using-tags) for specific **Delegates** 
Done

2022-12-05 16:51 UTC, rashminandasahoo commented on docs/platform/6_Security/9-custom-secret-manager.md
> +9. In **Delegates** **Setup****,** enter [**Selectors**](../2_Delegates/delegate-guide/select-delegates-with-selectors.md#option-select-a-delegate-for-a-connector-using-tags) for specific **Delegates
Done

2022-12-05 16:52 UTC, rashminandasahoo commented on docs/platform/6_Security/10-add-google-kms-secrets-manager.md
> +In **Delegates** **Setup****,** use [**Selectors**](../2_Delegates/delegate-guide/select-delegates-with-selectors.md#option-select-a-delegate-for-a-connector-using-tags) to select any specific **Dele
Done

2022-12-05 16:53 UTC, rashminandasahoo commented on docs/platform/6_Security/11-add-a-google-cloud-secret-manager.md
> +1. In **Delegates** **Setup****,** enter [**Selectors**](../2_Delegates/delegate-guide/select-delegates-with-selectors.md#option-select-a-delegate-for-a-connector-using-tags) for specific delegates t
Done

2022-12-05 16:54 UTC, rashminandasahoo commented on docs/platform/6_Security/12-add-hashicorp-vault.md
> +1. 3. The policy attached to the Token/AppRole does not provide the **write**permission in the specified path. Make sure you update the policies and permissions.
Done

2022-12-05 16:57 UTC, rashminandasahoo commented on docs/platform/6_Security/ref-security/secrets-and-log-sanitization.md
> +You can reference a file secret created in the Org [scope](../../4_Role-Based Access Control/rbac-in-harness.md#scope) using the expression `<+secrets.getValue(“org.file-secret-Id”)>`.
Done

2022-12-06 03:48 UTC, rashminandasahoo commented on docs/platform/3_Authentication/5-single-sign-on-sso-with-ldap.md
> +```
Done

2022-12-06 04:01 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/2-attribute-based-access-control.md
> +|  |  |
Done

2022-12-06 04:02 UTC, rashminandasahoo commented on docs/platform/4_Role-Based-Access-Control/4-add-user-groups.md
> +In **User Groups** click **New User** **Group****.** The New User Group settings appear.
Done

2022-12-06 04:04 UTC, rashminandasahoo commented on docs/platform/6_Security/ref-security/secrets-and-log-sanitization.md
> +You can reference an Encrypted Text secret created in the Org [scope](../../4_Role-Based Access Control/rbac-in-harness.md#scope) using the secret identifier in the expression: `<+secrets.getValue("o
Done

2022-12-06 04:09 UTC, rashminandasahoo commented on docs/platform/7_Connectors/add-a-microsoft-azure-connector.md
> +For security reasons, Harness uses an application object and service principal rather than a user identity. The process is described in [How to: Use the portal to create an Azure AD application and s
Done

2022-12-06 04:11 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-an-artifact-repo.md
> +For details on settings and permissions, see [Artifactory Connector Settings Reference](ref-cloud-providers/artifactory-connector-settings-reference.md).1. Open a Harness Project.
Done

2022-12-06 04:12 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-an-artifact-repo.md
> +For details on settings and permissions, see [Docker Connector Settings Reference](ref-cloud-providers/docker-registry-connector-settings-reference.md).The Docker Connector is platform-agnostic and c
Done

2022-12-06 04:12 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-an-artifact-repo.md
> +10. In **Delegates Setup****,**use any Delegate or enter [Tags](../2_Delegates/delegate-guide/select-delegates-with-selectors.md) for specific Delegates that you want to allow to connect to his Conne
DOne

2022-12-06 04:14 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-an-artifact-repo.md
> +For details on settings and permissions, see [HTTP Helm Repo Connector Settings Reference](ref-source-repo-provider/http-helm-repo-connector-settings-reference.md).1. Open a Harness Project.
Done

2022-12-06 04:18 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-code-repo.md
> +For more details on the settings to create this connector, see [Git Connector Settings Reference](ref-source-repo-provider/git-connector-settings-reference.md).1. In your **Project** select a module
Done

2022-12-06 04:21 UTC, rashminandasahoo commented on docs/platform/20_References/renaming-entities-and-resources.md
> +For information on Organizations and Projects, see [Organizations and Projects Overview](../1_Organizations and Projects/projects-and-organizations.md).For example, here are two GitHub Connectors wit
Done

2022-12-06 04:26 UTC, rashminandasahoo commented on docs/platform/20_References/runtime-inputs.md
> +
Done

2022-12-06 04:27 UTC, rashminandasahoo commented on docs/platform/20_References/tags-reference.md
> +* Harness variable expressions cannot be used in Tags. See [Built-in Harness Variables Reference](../12_Variables and Expressions/harness-variables.md).
Done

2022-12-06 04:28 UTC, rashminandasahoo commented on docs/platform/20_References/tags-reference.md
> +You can reference Tags using [Harness expressions](../12_Variables and Expressions/harness-variables.md).
Done

2022-12-06 04:28 UTC, rashminandasahoo commented on docs/platform/20_References/tags-reference.md
> +* [Built-in Harness Variables Reference](../12_Variables and Expressions/harness-variables.md)
Done

2022-12-06 04:31 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-code-repo.md
> +3. Click **New Connector**, and click **Git** in **Code Repositories**. The Git settings appear.![](./static/connect-to-code-repo-08.png)
Done

2022-12-06 04:34 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-code-repo.md
> +6. Once the Test Connection succeeds, click **Finish**. The Connector is listed in Connectors.
Done

2022-12-06 04:35 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-code-repo.md
> +For more details on the settings to create this connector, see [Bitbucket Connector Settings Reference](ref-source-repo-provider/bitbucket-connector-settings-reference.md).Harness supports both Cloud
Done

2022-12-06 04:36 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-code-repo.md
> +For more details on the settings to create this connector, see [GitLab Connector Settings Reference](ref-source-repo-provider/git-lab-connector-settings-reference.md).1. Open a Harness Project.
Done

2022-12-06 04:59 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-harness-container-image-registry-using-docker-connector.md
> +You must create the Harness Docker Connector at the Account level. Make sure that you have the **Account** > **Connectors** > **Create/Edit/View** permission for Harness Platform. See [Permission Ref
Done

2022-12-06 05:00 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-harness-container-image-registry-using-docker-connector.md
> +3. Click **Continue**.
Done

2022-12-06 05:06 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-jenkins.md
> +For token-based authentication, go to **http://*****Jenkins-IP-address*****/jobs/me/configure** to check and change your API access token. The token is added as part of the HTTP header.
This is not a link. Users need to replace the IP address with a value.

2022-12-06 06:15 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-monitoring-and-logging-systems.md
> +5. Once the Test Connection succeeds, click **Finish**. AppDynamics is listed under the list of Connectors.
Done

2022-12-06 06:25 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-monitoring-and-logging-systems.md
> +
Done

2022-12-06 06:26 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-monitoring-and-logging-systems.md
> +(./static/connect-to-monitoring-and-logging-systems-20.png)
Done

2022-12-06 06:31 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-monitoring-and-logging-systems.md
> +4. Once the Test Connection succeeds, click **Finish**. Splunk is listed under the list of Connectors.
Done

2022-12-06 06:34 UTC, rashminandasahoo commented on docs/platform/7_Connectors/ref-cloud-providers/artifactory-connector-settings-reference.md
> +(./static/artifactory-connector-settings-reference-09.png)
Done

2022-12-06 07:02 UTC, rashminandasahoo commented on docs/platform/7_Connectors/ref-cloud-providers/aws-connector-settings-reference.md
> +|  |  |
Not sure how to render code snippets inside table cells. Have formatted manually for now.

2022-12-06 07:07 UTC, rashminandasahoo commented on docs/platform/7_Connectors/ref-source-repo-provider/source-code-manager-settings.md
> +**My Source Code Manager** is required for Harness Git Experience. For details on Harness Git Experience, see [Harness Git Experience Overview](../../10_Git Experience/harness-git-experience-overview
Done

2022-12-06 07:11 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/add-a-custom-stage.md
> +See [Built-in and Custom Harness Variables Reference](../12_Variables and Expressions/harness-variables.md).
Done

2022-12-06 07:12 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/add-a-custom-stage.md
> +* [Add a Policy Engine Step to a Pipeline](../14_Policy as code/add-a-governance-policy-step-to-a-pipeline.md)
Done

2022-12-06 07:15 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/harness-yaml-quickstart.md
> +This quickstart shows you how to create a Harness Pipelines using YAML. It's not an exhaustive reference for all of the YAML entries, but a quick procedure to get you started with Harness Pipeline YA
Done

2022-12-06 07:28 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/input-sets.md
> +|  |  |
Have posted a query on developer hub. Would need some assistance on how to insert images inside markdown table cells.

2022-12-06 08:23 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/resume-pipeline-deployments.md
> +This topic assumes you have a Harness Project set up. If not, see [Create Organizations and Projects](../1_Organizations and Projects/create-an-organization.md).
Done

2022-12-06 08:26 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/run-pipelines-using-input-sets-and-overlays.md
> +3. Click **Save as Input Set**. The Input Set setup appears.![](./static/run-pipelines-using-input-sets-and-overlays-08.png)
Done

2022-12-06 08:27 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/run-pipelines-using-input-sets-and-overlays.md
> +2. In the **Run Pipeline** page, click the Input Sets option.![](./static/run-pipelines-using-input-sets-and-overlays-09.png)
Done

2022-12-06 08:28 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/run-specific-stage-in-pipeline.md
> +* [Create Organizations and Projects](../1_Organizations and Projects/create-an-organization.md)
Done

2022-12-06 08:28 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/run-specific-stage-in-pipeline.md
> +* Make sure you have **Execute** permissions for Pipeline to run a specific Stage of the Pipeline. For example, the [Pipeline Executor](../4_Role-Based Access Control/ref-access-management/permission
Done

2022-12-06 08:29 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/speed-up-ci-test-pipelines-using-parallelism.md
> +*P**arallelism* is one of the [looping strategies](looping-strategies-matrix-repeat-and-parallelism.md) available in Harness pipelines. Parallelism is useful whenever you can split a step or stage in
Done

2022-12-06 08:33 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/speed-up-ci-test-pipelines-using-parallelism.md
> +5. Run your Pipeline to make sure all your Steps complete successfully. You can see the parallel copies of your Step running in the Build UI.
Done

2022-12-06 08:40 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/speed-up-ci-test-pipelines-using-parallelism.md
> +**Figure 2: Parallel steps in a build**![](./static/speed-up-ci-test-pipelines-using-parallelism-51.png)
Done

2022-12-06 08:41 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/speed-up-ci-test-pipelines-using-parallelism.md
> +7. Now that Harness has collected timing data, you can split your tests by time and reduce your build times further. Go to [Define test splitting](#define-test-splitting).
Done

2022-12-06 08:42 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/speed-up-ci-test-pipelines-using-parallelism.md
> +**Figure 4: Define parallelism in a Run step**![](./static/speed-up-ci-test-pipelines-using-parallelism-53.png)
Done

2022-12-06 08:44 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/view-and-compare-pipeline-executions.md
> +Compiled execution YAML is the Pipeline YAML used in the execution, including all resolved [Runtime Inputs, Expressions](../20_References/runtime-inputs.md), and [variables](../12_Variables and Expre
Done

2022-12-06 08:51 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/w_pipeline-steps-reference/step-failure-strategy-settings.md
> +* Rollback Stage
Done

2022-12-06 08:52 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/w_pipeline-steps-reference/step-failure-strategy-settings.md
> +| **Rollback Step Group** | N/A | The step group is rolled back to the state prior to step group execution. How the step group rolls back depends on the type of build or deployment it was preforming.
Done

2022-12-06 09:05 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/w_pipeline-steps-reference/yaml-reference-cd-pipeline.md
> +*
Done

2022-12-06 09:07 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-experience-overview.md
> +
We can remove this post Jan 31st.

2022-12-06 09:09 UTC, rashminandasahoo commented on docs/platform/9_Approvals/service-now-approvals.md
> +
Done

2022-12-06 09:16 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/import-a-pipeline.md
> +The **Import Pipeline From Git** settings appear.![](./static/import-a-pipeline-30.png)
Done

2022-12-06 09:16 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/import-input-sets.md
> +The **Import Input Set From Git** settings appear.![](./static/import-input-sets-01.png)
Done

2022-12-06 09:18 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/manage-a-harness-pipeline-repo-using-git-experience.md
> +For the YAML path, enter **.harness/{*****PIPELINE\_SUBFOLDER*****}/{PIPELINE\_NAME}.yml**. The root folder **.harness** is required. The **{*****PIPELINE\_SUBFOLDER*****}** is not required, but it i
Done

2022-12-06 09:20 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/manage-a-harness-pipeline-repo-using-git-experience.md
> +Every Input Set is associated with a specific Pipeline, which is specified by the `pipeline : identifier` element in the Input Set YAML.![](./static/manage-a-harness-pipeline-repo-using-git-experienc
DOne

2022-12-06 09:20 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/manage-a-harness-pipeline-repo-using-git-experience.md
> +Set up your Build Stage in the Pipeline Studio: define the build infrastructure and add at least one Step. Click **Save**. The **Save Pipelines to Git** window appears.
Done

2022-12-06 09:22 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/manage-input-sets-in-simplified-git-experience.md
> +Once you have saved your Pipeline in your repo, you can set up your Input Sets and Triggers. You can set up your Input Set definitions in your repo along with your Pipeline. You can then set up your
Done

2022-12-06 10:18 UTC, rashminandasahoo commented on docs/platform/11_Triggers/trigger-on-a-new-artifact.md
> +4. Select the artifact registry where your artifact is hosted. If you artifact is hosted on Docker Hub and you select GCR, you won't be able to set up your Trigger.
Done

2022-12-06 10:23 UTC, rashminandasahoo commented on docs/platform/11_Triggers/trigger-pipelines-on-new-helm-chart.md
> +4. In **Configuration**, in **Name**, enter a name for the Trigger.
Done

2022-12-06 10:26 UTC, rashminandasahoo commented on docs/platform/11_Triggers/trigger-pipelines-using-custom-payload-conditions.md
> +If you want to specify multiple paths, use the Regex operator.![](./static/trigger-pipelines-using-custom-payload-conditions-30.png)#### Option 2: Header Condition
Done

2022-12-06 10:37 UTC, rashminandasahoo commented on docs/platform/11_Triggers/triggering-pipelines.md
> +You can trigger Pipelines in response to Git events automatically.
Done

2022-12-06 10:44 UTC, rashminandasahoo commented on docs/platform/12_Variables-and-Expressions/add-a-variable.md
> +![](./static/add-a-variable-01.png)### Step 1: Add Account, Org, and Project Variables
Done

2022-12-06 10:45 UTC, rashminandasahoo commented on docs/platform/12_Variables-and-Expressions/add-a-variable.md
> +You can add a Variable to the Account, Organization, or Project [scope](../4_Role-Based Access Control/rbac-in-harness.md#rbac-scope).
Done

2022-12-06 10:46 UTC, rashminandasahoo commented on docs/platform/12_Variables-and-Expressions/add-a-variable.md
> +In your Pipelines, Variables can be added at the Pipeline-level, which makes them available to all Stages in the Pipeline. Within a Stage, you can add Variables at the Stage and Service-level. Here's
Done

2022-12-06 10:55 UTC, rashminandasahoo commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +
Done

2022-12-06 10:55 UTC, rashminandasahoo commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +(./static/harness-variables-28.png)
Done

2022-12-06 10:55 UTC, rashminandasahoo commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +
Done

2022-12-06 11:02 UTC, rashminandasahoo commented on docs/platform/13_Templates/add-a-stage-template.md
> +* You can add Templates to Template Libraries at any [scope](../4_Role-Based Access Control/rbac-in-harness.md#scope).
Done

2022-12-06 11:03 UTC, rashminandasahoo commented on docs/platform/13_Templates/add-a-stage-template.md
> +
Done

2022-12-06 11:07 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-pipeline-template.md
> +You can add Templates at any [scope](../4_Role-Based Access Control/rbac-in-harness.md) in Harness.
Done

2022-12-06 11:08 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-pipeline-template.md
> +
Done

2022-12-06 11:09 UTC, rashminandasahoo commented on docs/platform/13_Templates/template.md
> +title: Templates Overview
Done

2022-12-06 11:20 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/harness-governance-quickstart.md
> +
Done

2022-12-06 11:33 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +
Done

2022-12-06 11:36 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +1. Click **Save**.
DOne

2022-12-06 11:37 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +* **I****nput failed Policy Evaluation**: The Feature Flag doesn’t adhere to the updated policy.
Done

2022-12-06 11:40 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +![](https://lh4.googleusercontent.com/f2GbzvnKR5dw5iVaHRfr695eq16qFYya38-I9tSzDH37UZRPljOzGaLmGuGBLdtsWvtQzWDgL8uNRfmLjy-gsWepN1HKw8XXrgpAFo71o13aT0VAp-JJ3noiRvPlumo_-NfG0crI)1. In **Name**, enter th
Done

2022-12-06 11:41 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +4. In **On what event should the Policy Set be evaluated**, select **On save**, then click **Continue**.
Done

2022-12-06 11:41 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +2. The Policy Set is automatically set to Enforced, to make it unenforced, toggle off the **Enforced** button.
Done

2022-12-06 11:42 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +* **Error and exit:** If a policy isn’t met when the Feature Flag is evaluated, you receive an error and are exited without saving the flag.
Done

2022-12-06 11:42 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +2. When you've made all the changes, click **Save**.
Done

2022-12-06 11:43 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +2. Click **Apply**, then click **Finish**.
Done

2022-12-06 11:44 UTC, rashminandasahoo commented on docs/platform/14_Policy-as-code/using-harness-policy-engine-for-feature-flags.md
> +1. To view further details of a particular evaluation, click on it and expand the relevant evaluation.
Done

2022-12-06 11:44 UTC, rashminandasahoo commented on docs/platform/15_Audit-Trail/audit-trail.md
> +* [Access Management (RBAC) Overview](../4_Role-Based Access Control/rbac-in-harness.md)
Done

2022-12-06 11:45 UTC, rashminandasahoo commented on docs/platform/16_APIs/api-quickstart.md
> +**Looking for the API reference docs?** See [Harness API Reference Docs](https://harness.io/docs/api/).### Objectives
Done

2022-12-06 11:48 UTC, rashminandasahoo commented on docs/platform/16_APIs/api-quickstart.md
> +The API requests in this topic use curl, but Harness supports multiple languages, such as Go, Java, and Node.js. The [Harness API Reference Docs](https://harness.io/docs/api/) provides examples for a
DOne

2022-12-06 11:49 UTC, rashminandasahoo commented on docs/platform/16_APIs/api-quickstart.md
> +For an overview of Harness API keys, see [Add and Manage API Keys](../4_Role-Based Access Control/add-and-manage-api-keys.md).Let's create the API key and its Personal Access Token.
Done

2022-12-06 11:50 UTC, rashminandasahoo commented on docs/platform/16_APIs/harness-rest-api-reference.md
> +For an overview of Harness API keys, see [Add and Manage API Keys](../4_Role-Based Access Control/add-and-manage-api-keys.md).Let's create the API key and its Personal Access Token.
Done

2022-12-06 11:52 UTC, rashminandasahoo commented on docs/platform/18_Dashboards/create-dashboards.md
> +
Done

2022-12-06 11:55 UTC, rashminandasahoo commented on docs/platform/18_Dashboards/download-dashboard-data.md
> +8. Click **Download** to initiate the download. A new tab in your browser will open, showing the status of your download.![](./static/download-dashboard-data-23.png)
Done

2022-12-06 12:00 UTC, rashminandasahoo commented on docs/platform/18_Dashboards/share-dashboards.md
> +![](https://docs.looker.com/assets/images/hourly-dash-beta-2100.png)
I don't have information on this. The images do not display on docs.harness.io too. Need to check with the corresponding writer. I have removed them for now.

2022-12-06 12:27 UTC, rashminandasahoo commented on docs/platform/20_References/permissions-and-ports-for-harness-connections.md
> +|  |  |  |  |
Done

2022-12-06 12:39 UTC, rashminandasahoo commented on docs/platform/20_References/renaming-entities-and-resources.md
> +
Done

2022-12-06 12:39 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-pipeline-template.md
> +* Review [Permissions Reference](../4_Role-Based Access Control/ref-access-management/permissions-reference.md#sort=relevancy&f:@commonsource=[NextGen%20Docs]) to know about the permissions required
Done

2022-12-06 12:41 UTC, rashminandasahoo commented on docs/platform/7_Connectors/connect-to-monitoring-and-logging-systems.md
> +4. Once the Test Connection succeeds, click **Finish**. Prometheus is listed under the list of Connectors.
Done

2022-12-06 13:10 UTC, KimberlyFields approved these changes

2022-12-06 13:41 UTC, merged