CD release notes 792xx
harness/developer-hub pull request #1537
Opened 2023-04-28 13:52 UTC by roshnisarangadharan

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-05-01 16:52 UTC, thisrohangupta submitted a review, later dismissed
These changes look good, thanks

2023-05-01 18:02 UTC, michaelcretzman requested changes

2023-05-01 18:02 UTC, michaelcretzman commented on release-notes/continuous-delivery.md
> +- Added support to get GitHub webhook events through a CURL command if the client call fails. (CDS-58692)
how is this an Early Access feature? Is it behind a feature flag?

I don't know what the summary means so I've asked the dev in the ticket

2023-05-01 18:02 UTC, michaelcretzman commented on release-notes/continuous-delivery.md
> +  When you create or update a new service override, the environment reference was an identifier before. Now, Harness supports scoped environment references in metadata as well as YAML as part of the
Update: Rohan said to remove this one:
> the story is getting deployed but the epic and enhancement isnt done, no need to document it

2023-05-02 05:54 UTC, roshnisarangadharan commented on release-notes/continuous-delivery.md
> +  When you create or update a new service override, the environment reference was an identifier before. Now, Harness supports scoped environment references in metadata as well as YAML as part of the
ok

2023-05-02 05:55 UTC, roshnisarangadharan commented on release-notes/continuous-delivery.md
> +- Added support to get GitHub webhook events through a CURL command if the client call fails. (CDS-58692)
Moved to new features list

2023-05-03 12:38 UTC, charanya-j commented on release-notes/continuous-delivery.md
> +  Support has been added to hide the STO module from CE.
Added support to

2023-05-03 12:40 UTC, charanya-j submitted a review, later dismissed

2023-05-04 06:00 UTC, merged