Add new module - Internal Developer Portal (Beta)
harness/developer-hub pull request #1567
Opened 2023-05-02 08:27 UTC by OrkoHunter

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

Adds a new Harness module

2023-05-02 14:34 UTC, ravilach commented
We eventually will also need the Coveo Facet updated cc @wei-harness

2023-05-25 15:30 UTC, ravilach commented
@ orkohunter good for us to check this out?

2023-05-25 15:30 UTC, OrkoHunter commented
Hi @ravilach - added a one page overview of IDP with a note that this is available in closed beta to existing customers. We have a [long list of docs](https://harness.atlassian.net/wiki/spaces/IDP/pages/21275968000/Customer-facing+documentation+requirements) that are being written by the team. We will continuously add them here. Do you think we can merge this PR to lay the foundations of IDP so that it's easier for others in the team to add their respective docs/tutorials?

<img width="2560" alt="Screenshot 2023-05-25 at 8 55 34 PM" src="https://github.com/harness/developer-hub/assets/8065913/07acf8d2-8f65-4f71-9e31-b9324119a075">

2023-05-25 15:35 UTC, ravilach commented
@OrkoHunter since we a good set of changes in the docusarus.js and the sidebar.js, mind bringing those up to speed before we merge? CC @KimberlyFields this is ready for review.

2023-05-30 19:49 UTC, deepakbolangady requested changes
I need some inputs for the first two paragraphs (we can look at them before beta). I've entered my feedback on the other sections of the document. I'll continue to review this text as more commits are added. Thank you.

2023-05-30 19:49 UTC, deepakbolangady commented on docs/internal-developer-portal/intro.md
> +Harness IDP lets developers **create** new software components in seconds following the company’s best practices. It lets them **manage** their software by presenting a developer-centric view of all
I would like to ask a question or two here. I definitely have suggestions for this text.

2023-05-30 19:49 UTC, deepakbolangady commented on docs/internal-developer-portal/intro.md
> +Fully integrated into the Harness platform, IDP reduces the maintenance overhead and investment required from customers and is enterprise ready with our platform features.
Same as previous: I would like to ask a couple of questions here.

2023-05-30 19:49 UTC, deepakbolangady commented on src/components/Docs/data/internalDeveloperPortal.ts
> +    name: "Learn more",
```suggestion
    name: "Get started with IDP",
```

2023-05-30 19:49 UTC, deepakbolangady commented on src/components/Docs/data/internalDeveloperPortal.ts
> +          "Read this to know more about the use-cases and features of Harness IDP.",
```suggestion
          "Learn how Harness's developer-centric portal helps platform engineering and development teams improve productivity."
```

2023-05-30 19:49 UTC, deepakbolangady commented on docs/internal-developer-portal/intro.md
> +
# Overview of Harness IDP

2023-06-02 06:35 UTC, deepakbolangady approved these changes
Approving with a few comments. Thanks.

2023-06-02 06:35 UTC, deepakbolangady commented on docs/internal-developer-portal/intro.md
> +Harness IDP lets you **create** new software components in seconds adhering to your company’s best practices. It lets you **manage** the software you own by presenting a developer-centric view of all
```suggestion
Harness IDP enables you to create new software components quickly while adhering to your company’s best practices. It enables you to manage the software you own by presenting a developer-centric view of all relevant information such as service health, deployments, and alerts. It also enables you to explore the internal software ecosystem of the company, discover technical documentation, APIs, and services, all of which enable better collaboration.
```
* Can we back up the "in seconds" claim, or would the time taken depend on variables? I would prefer "Harness IDP enables rapid development of ...", but in the current sentence, "quickly" works too (still subjective but better than "in seconds").
* When someone says "lets you", our thoughts go to permission. "Enables you" is better. It means "gives you the ability to" or "empowers you" in a way. I hope these suggestions can be implemented. 
* Let's run with this description. In the next iteration, let's bring in the personas involved. The first part of this description is for the Platform Engineering team and the last part is for development teams, I think. Both user segments should be able to connect with this text. Thanks.

2023-06-02 06:35 UTC, deepakbolangady commented on docs/internal-developer-portal/intro.md
> +Fully integrated into the Harness platform, IDP reduces the maintenance overhead and investment required from the platform engineering and is enterprise ready.
```suggestion
Fully integrated into the Harness platform, IDP reduces the maintenance overhead and investment required from platform engineering teams and is enterprise ready.
```

2023-06-05 06:22 UTC, deepakbolangady approved these changes

2023-06-05 06:40 UTC, merged