add CI java http server tutorial
harness/developer-hub pull request #161
Opened 2022-12-01 21:16 UTC by jimsheldon

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-01 22:08 UTC, ravilach commented
Thanks for the PR! @jimsheldon mind adding those tiles to the 'AllTutorials.tsx' and 'ContinuousIntegration.tsx' like you have before [since you are pro! If not I can add]. 

@KimberlyFields adding you as a CI reviewer, feel free to re-assign if needed. 

Cheers!

-Ravi

2022-12-01 22:17 UTC, ravilach requested changes
Tiles if possible. Cheers!

2022-12-02 13:17 UTC, jimsheldon commented
No problem. What do you mean by "Tiles if possible"? Thanks

2022-12-02 13:32 UTC, ravilach approved these changes

2022-12-02 16:38 UTC, KimberlyFields requested changes
The content looks good, but I made several suggestions for style and formatting.

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +### Add Integration Tests Stage
```suggestion
### Add an integration tests stage
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +This separate pipeline stage will pull the Docker image published in the previous step, run it as a [Background step](../../docs/continuous-integration/ci-technical-reference/background-step-settings
```suggestion
This separate pipeline stage pulls the Docker image that was published in the previous step, runs it as a [Background step](../../docs/continuous-integration/ci-technical-reference/background-step-settings.md), and verifies that the container started successfully.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +1. In the **Pipeline Studio** click **Add Stage** and select **Build**.
```suggestion
1. In the **Pipeline Studio**, select **Add Stage**, and then select **Build**.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +   Enter `Run Connectivity Test` in the **Stage Name** field, then click **Set Up Stage**.
```suggestion
 2. In the **Stage Name** field, enter `Run Connectivity Test`, and then select **Set Up Stage**.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +2. In the **Infrastructure** tab, select **Propagate from an existing stage**, select the previous stage from the drop-down menu and click **Continue**.
```suggestion
3. On the **Infrastructure** tab, select **Propagate from an existing stage**, select the previous stage from the drop-down menu, and then select **Continue**.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +### Add Background Step
```suggestion
### Add a background step
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +This Background step runs the Docker image published in the previous stage.
```suggestion
This background step runs the Docker image that was published in the previous stage.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +1. Click **Add Step**, the **Step Library** dialogue window will appear. Select **Background** from the list.
```suggestion
1. Select **Add Step**. In the **Step Library** dialog, select **Background** from the list.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +2. Enter `Run Java HTTP Server` in the **Name** field.
```suggestion
2. In the **Name** field, enter `Run Java HTTP Server`.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +3. Expand the **Additional Configuration** section, click the **Container Registry** field and select your Docker Hub connector.
```suggestion
3. Expand the **Additional Configuration** section, select the **Container Registry** field, and then select your Docker Hub connector.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +4. Enter `your_user/jhttp:<+pipeline.sequenceId>` (replace `your_user` with your Docker Hub username) in the **Image** field.
```suggestion
4. In the **Image** field, etner `your_user/jhttp:<+pipeline.sequenceId>`. Replace `your_user` with your Docker Hub username.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +5. Click **+ Add** under **Port Bindings**, enter `8888` in the **Host Port** and **Container Port** fields.
```suggestion
5. Under **Port Bindings**, select **+ Add**, and then enter `8888` in the **Host Port** and **Container Port** fields.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +   This will expose port `8888` from the running container to the host operating system. This will allow the connection test step to reach the application at `localhost:8888`.
```suggestion
   This exposes port `8888` from the running container to the host operating system. This allows the connection test step to reach the application at `localhost:8888`.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +6. Click **Apply Changes**.
```suggestion
6. Select **Apply Changes**.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +### Add Connection Test Step
```suggestion
### Add a connection test step
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +This step runs a connection test from the host operating system, verifying the application started successfully.
```suggestion
This step runs a connection test from the host operating system to verify that the application started successfully.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +1. Click **Add Step**, the **Step Library** dialogue window will appear. Select **Run** from the list.
```suggestion
1. Select **Add Step**. On the **Step Library** dialog, select **Run** from the list.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +2. Enter `Test Connection to Java HTTP Server` in the **Name** field.
```suggestion
2. In the **Name** field, enter `Test Connection to Java HTTP Server` .
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +3. Enter this in the **Command** field:
```suggestion
3. In the **Command** field, enter the following command:
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +   This simple connectivity test will attempt to reach the service every two seconds, until successful.
```suggestion
   This simple connectivity test attempts to reach the service every two seconds until it is successful.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +4. Click **Apply Changes**, then click **Save**.
```suggestion
4. Select **Apply Changes**, and then select **Save**.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +   With the application up and running, many types of tests are possible: integration, security, performance, and more!
```suggestion
   With the application up and running, many types of tests are possible: integration, security, performance, and more.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +### Optional YAML Configuration
```suggestion
### Optional YAML configuration
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +## Run Your Pipeline
```suggestion
## Run your pipeline
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +1. In the **Pipeline Studio** click **Run**, the **Run Pipeline** dialogue window will open.
```suggestion
1. In the **Pipeline Studio**, select **Run**.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +2. Select **Git Branch** as the **Build Type**, and enter `main` in the **Branch Name** field.
```suggestion
2. Select **Git Branch** as the **Build Type**, and then enter `main` in the **Branch Name** field.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +3. Click **Run Pipeline**.
```suggestion
3. Select **Run Pipeline**.
```

2022-12-02 16:38 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +4. Observe each step of the pipeline execution. When the first stage completes, test results will appear in the **Tests** tab. When the second stage completes, you should see the successful `curl` co
```suggestion
4. Observe each step of the pipeline execution. When the first stage completes, test results appear in the **Tests** tab. When the second stage completes, you should see the successful `curl` command in the final step.
```

2022-12-02 18:57 UTC, ravilach commented
@jimsheldon let us know when you are happy with your version. Looks like a few commits have been included, then can get @KimberlyFields to re-approve. Cheers!

2022-12-02 19:16 UTC, ravilach submitted a review, later dismissed
Still good from my side for the tech changes. -Ravi

2022-12-02 19:37 UTC, jimsheldon commented
I think all of these suggestions look good, but it's a lot of clicking to accept them...

@KimberlyFields do you have the markdown file I can just bring into my branch?

2022-12-02 20:08 UTC, KimberlyFields commented
@jimsheldon I made the suggestions via GitHub comments. You can click **Add suggestions to batch** for each suggestion, and then commit all of the changes in one commit.

2022-12-02 21:11 UTC, jimsheldon commented
Thanks @KimberlyFields! I didn't know that was possible.

2022-12-03 15:10 UTC, ravilach submitted a review, later dismissed

2022-12-05 15:05 UTC, merged