Sto GitHub actions doc 2919
harness/developer-hub pull request #1616
Opened 2023-05-05 16:09 UTC by douglas-j-bothwell

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* https://harness.atlassian.net/browse/DOC-2919

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-05-19 12:06 UTC, williamwissemann submitted a review, later dismissed

2023-05-31 22:32 UTC, aimurphy requested changes
Some feedback based on my experience w CI plugins. Most is optional, but there is an important step missing from the Plugin step setup.

2023-05-31 22:32 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +* You can run scans using [GitHub Action steps](/docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step) and [Drone plugin steps](/docs/continuous-integration/use-ci/use-drone-plu
```suggestion
* You can run scans using [GitHub Action steps](/docs/continuous-integration/use-ci/use-drone-plugins/ci-github-action-step) and [Plugin steps](/docs/continuous-integration/use-ci/use-drone-plugins/run-a-git-hub-action-in-cie). 
```
A little nitpicky, but the step is just called "Plugin" step since you can also use it to run your own plugins.

2023-05-31 22:32 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +* The type of step to use depends on your build infrastructure. GitHub Action steps are supported on Harness Cloud infrastructures only. Drone Plugin steps are supported on Harness Cloud and Kubernet
```suggestion
* The type of step to use depends on your build infrastructure. GitHub Action steps are supported on Harness Cloud infrastructures only. Drone Plugin steps are supported on Harness Cloud and Kubernetes infrastructures.
```

I believe you can also use Plugin steps with VM and local runner build infras.

2023-05-31 22:32 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +* [GitHub](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#the-components-of-github-actions) and [Harness](/docs/getting-started/learn-harness-key-concepts) use s
Optional - This page compares GHA with Harness CI: https://64668af0b876e108972c0364--harness-developer.netlify.app/docs/continuous-integration/migration-guides/migrating-from-githubactions/ 

this might also be a good link for the bullet where you mention converting GHA yaml to Harness yaml.

2023-05-31 22:32 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +   :::
empty note here

2023-05-31 22:32 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +        <td>Optional. Specify a map of environment variables to pass to the Action. </td>
Not sure if you want to include this, but env is not optional for private repos.

2023-05-31 22:32 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +        <td>Required. Provide a map of key-value pairs representing settings required by the GitHub Action itself. This example configures the Action to output a data file in SARIF format. </td>
Technically settings are optional. In the UI, it is under optional config because the GHA might not have settings or it might have default values that the user doesn't want to change.

2023-05-31 22:32 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +3. Use **Settings** to specify the Github Action you want to use and to pass variables and attributes required by the Action.
There is a key step missing. The Plugin step needs a connector ref and to point to the plugin/github-actions image.

Also, I am not 100% sure, but in some cases they need to select "Privileged".

2023-06-01 00:05 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/use-sto/orchestrate-and-ingest/run-scans-using-github-actions.md
> +* The type of step to use depends on your build infrastructure. GitHub Action steps are supported on Harness Cloud infrastructures only. Drone Plugin steps are supported on Harness Cloud and Kubernet
The STO team has only tested security scans on Harness Cloud (Actions) and k8s (Actions and plugins). I've revised the language to make this more explicit.

2023-06-01 02:52 UTC, merged