DOC-3080 TAS connector
harness/developer-hub pull request #1633
Opened 2023-05-08 09:19 UTC by roshnisarangadharan

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-05-08 13:04 UTC, deepakbolangady requested changes
The preview environment did not open for me, so that part of my review is pending. I'll take a look again after you've incorporated the comments. Please reach out to me if you have any questions about my comments. Thank you.

2023-05-09 05:31 UTC, roshnisarangadharan commented on docs/platform/7_Connectors/Cloud-providers/add-tas-connector.md
> +4. Apply the profile to the delegate profile and check the logs.
we are applying the profile with cf cli commands to the delegate profile

2023-05-09 05:34 UTC, roshnisarangadharan commented on docs/platform/7_Connectors/Cloud-providers/add-tas-connector.md
> +<summary>Install a delegate by using the terminal</summary>
```suggestion
<summary>Use the terminal</summary>
```

2023-05-09 05:36 UTC, roshnisarangadharan commented on docs/platform/7_Connectors/Cloud-providers/add-tas-connector.md
> +<summary>Use the delegate installation wizard</summary>
I think its is understood if we say use the wizard. Also, I have mentioned, expand the sections to learn how to install delegates.

2023-05-09 06:00 UTC, merged