[DOC-1808] [DOC-1604] [DOC-2543] CI Docs - Format Test Reports
harness/developer-hub pull request #1659
Opened 2023-05-09 17:41 UTC by aimurphy

## DOC-1808, DOC-1604

- New topic about formatting test reports:
- https://646651542bf1342276580365--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref
- Related changes to link to the new page and some non-technical updates to "Enable Test Intelligence" and "Run Tests step settings"

## DOC-2543

- Use .ticonfig.yaml to ignore tests/files
- https://646651542bf1342276580365--harness-developer.netlify.app/docs/continuous-integration/use-ci/set-up-test-intelligence/#ignore-tests-or-files

2023-05-10 19:38 UTC, rustd commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +## Ignore tests or files
Why are we adding a yaml file for configuring TI? cc @dgarg-harness @bradrydzewski

2023-05-10 19:49 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +## Ignore tests or files
see https://harness.atlassian.net/browse/DOC-2543 and related tickets.

2023-05-11 06:54 UTC, hemanthmantri requested changes

2023-05-11 06:54 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +                                                - "**/*.xml"
Let's use `target/surefire-reports/*.xml` to make it clear what this is about. This will also ensure we aren't parsing unrelated XML files and wasting time and handling errors.

2023-05-11 06:54 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +                                                - "**/*.xml"
Same else where for mvn/java based YAML samples.

2023-05-11 06:54 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +The following YAML example is for a pipeline that runs Test Intelligence on the Dubbo open-source project. Note that this example uses the deprecated Service Dependency step, which has been replaced
Let's change this YAML in that case by not using deprecated steps. Let's use Apache Kafka YAML or RocketMQ project YAML (which we used in the CI training)

2023-05-11 06:54 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +## Ignore tests or files
The rationale for this is that pipeline YAMLs are maintained by devOps persona and the code/tests/annotations/tests to skip etc are maintained by developer persona and is closer to the codebase. This file can get long and also we plan to extend this with more code level data with this ticket:  https://harness.atlassian.net/browse/CI-7146 
I discussed with @bradrydzewski and we agreed to use the `.harness_ci_config.yml` file with only tests to start with.

2023-05-11 06:54 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +title: Format test reports
IMHO, we should show examples of usage instead of just links. Some CircleCI docs for reference:


https://circleci.com/docs/collect-test-data/#test-runner-examples-by-language

https://circleci.com/blog/how-to-output-junit-tests-through-circleci-2-0-for-expanded-insights/

2023-05-11 14:14 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +title: Format test reports
Those examples are specific to circleci's setup. I think i understand how the command and report path translates to harness yaml. If you're able to give me some in-house examples, that would help.

2023-05-11 16:45 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +title: Format test reports
@aimurphy : The examples are just shell commands. We just need to move them to a Run Step in Harness YAML.

Example:
```steps:
  - run:
      name: Install JUnit coverage reporter
      command: yarn add --dev jest-junit
  - run:
      name: Run tests with JUnit as reporter
      command: jest --ci --runInBand --reporters=default --reporters=jest-junit
      environment:
        JEST_JUNIT_OUTPUT_DIR: ./reports/
  - store_test_results:
      path: ./reports/

will be this in Harness:

```
      - step:
          type: Run
          name: Run Jest Tests
          identifier: run_jest_tests
          spec:
            shell: Sh
            command: |
              yarn add --dev jest-junit
              jest --ci --runInBand --reporters=default --reporters=jest-junit
          envVariables:
             JEST_JUNIT_OUTPUT_DIR: "/harness/reports"
          reports:
            type: JUnit
            spec:
              paths:
                - "/harness/reports/*.xml"

2023-05-11 17:20 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +title: Format test reports
ok thanks

2023-05-11 19:38 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +title: Format test reports
@hemanthmantri I've added examples for most of them, but TBH I have no idea if they are correct except the one you gave me and the Go one that I got from Jim.

2023-05-16 23:27 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +                          - /build/out.xml
Did you mean `/harness/build/out.xml` ?

2023-05-16 23:27 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +                    args: test -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -T 16C -fae
Let's remove flags like -T 16C and -fae

2023-05-16 23:27 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +         MOCHA_FILE: "/harness/junit/test-results.xml"
Is this the right env variable?

2023-05-16 23:30 UTC, hemanthmantri commented
One concern I have is about searchability inside the page. For example in the CircleCI page, I can go and search for my language/tool and I felt that was convenient. For example if I search for `jest` in the page I won't find any results because it is buried under `Java Script` tab.

2023-05-17 00:00 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +         MOCHA_FILE: "/harness/junit/test-results.xml"
I don't know.

2023-05-17 00:17 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/test-report-ref.md
> +         MOCHA_FILE: "/harness/junit/test-results.xml"
Looks correct: https://github.com/michaelleeallen/mocha-junit-reporter/blob/master/README.md#usage 
There's a way to also directly specify in the cmdline :

`mocha test --reporter mocha-junit-reporter --reporter-options mochaFile=./path_to_your/file.xml`

2023-05-18 17:43 UTC, douglas-j-bothwell submitted a review, later dismissed

2023-05-18 18:08 UTC, merged