CHAOS-1660: new topic HCE/SRM integration
harness/developer-hub pull request #1672
Opened 2023-05-10 16:08 UTC by StrawberryPad

[**Link to preview**](https://64623d3562fbce203ecd43c6--harness-developer.netlify.app/docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm)

Early access

2023-05-15 12:53 UTC, amityt requested changes
The changes look good to me @StrawberryPad ! 🚀 
Requested some minor changes 😅

2023-05-15 12:53 UTC, amityt commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +For example, let's say you use SRM to monitor services and to correlate change events to service health. Now you want to see how one or more chaos faults impacts your target environment. By adding th
Can we rephrase this to:
Now you want to see how one or more chaos faults impact your target environment -> Now you want to see how one or more chaos faults impact the services in the target environment

2023-05-15 12:53 UTC, amityt commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +1. In Harness, select **Chaos > Chaos Experiments**, and then find and select an experiment.
find and select an experiment -> create an experiment

2023-05-15 12:53 UTC, amityt commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +1. Go to **Chaos > Changes** to get another view of the data.
**Service Reliability > Changes**

2023-05-15 13:05 UTC, StrawberryPad commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +1. In Harness, select **Chaos > Chaos Experiments**, and then find and select an experiment.
@amityt Just checking: you can connect a fault to services within an existing experiment, OR create an experiment and connect a fault to services, right? (the above assumed you're going to add one to an existing experiment)

2023-05-16 04:22 UTC, amityt commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +1. In Harness, select **Chaos > Chaos Experiments**, and then find and select an experiment.
Yes, we can add services to existing experiments as well 👍🏼

2023-05-16 04:23 UTC, amityt submitted a review, later dismissed
LGTM 🚀

2023-05-16 11:00 UTC, SudheendraKatte commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +For more information on Harness SRM and monitored services, go to these topics to:
```suggestion
For more information on Harness SRM and monitored services, go to these topics:
```

2023-05-16 12:04 UTC, StrawberryPad commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +For example, let's say you use SRM to monitor services and to correlate change events to service health. Now you want to see how one or more chaos faults impacts services in your target environment.
Thanks, Sudhi. The original is correct as it relates to multiple services in the target env. :-)

2023-05-16 12:05 UTC, StrawberryPad commented on docs/chaos-engineering/configure-chaos-experiments/experiments/use-chaos-with-srm.md
> +	The top part of the [Changes dashboard](/docs/service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board) displays a Changes Timeline, including a separate line
nicely caught! should be "diamond"

2023-05-16 12:32 UTC, merged