CCM governance recommendations and overview page
harness/developer-hub pull request #1720
Opened 2023-05-15 14:10 UTC by charanya-j

Added two new markdown files to cover **Governance recommendations** and one for the **overview** page.
Updated **Set up cost visibility for AWS** with permissions for governance

2023-05-15 22:23 UTC, Rohit-Kaliki requested changes

2023-05-15 22:23 UTC, Rohit-Kaliki commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/gov-overview.md
> +    You can view a visual representation of your savings trends through the **Savings Trend** graph, which allows you to hover over individual data points to view the corresponding cost savings for a
This is purely offering savings from CAG, this line doesn't make sense? 

We should also add a section on how the cost savings are calculated, in what scenarios etc. 
If we delete a EBS volume on 3rd May, we show costs saved on 3rd is 40$ (This 40$ is cost of running an EBS Volume for the last 30 days which is collected as savings) 

This feature provides you with a granular level of insight into your cloud spending, enabling you to identify any trends or anomalies and make informed decisions to optimize your resource utilization and maximize cost savings.

2023-05-15 22:23 UTC, Rohit-Kaliki commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/1-ccm-recommendations/governance.md
> +- DynamoDB Tables
We don't have support for Dynamo, Lambda, ELB yet

2023-05-15 22:23 UTC, Rohit-Kaliki commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/1-ccm-recommendations/governance.md
> +4. Enter a name for the Rule enforcement.
We should also highlight the fact that on the first run, it essentially rightsizes/ decommisions active opp. but the enforcement will ensure savings are ongoing.

2023-05-15 23:42 UTC, nikunj-badjatya commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/gov-overview.md
> +  - **All time realized savings** — The cost savings realized in the last one month.
Yes confirmed.

2023-05-16 00:50 UTC, nikunj-badjatya commented on docs/cloud-cost-management/2-getting-started-ccm/4-set-up-cloud-cost-management/set-up-cost-visibility-for-aws.md
> +                "elasticbeanstalk:List*",
We will need to update these. https://github.com/harness/harness-core/pull/47851/files once this is merged we can take the permissions from here.

2023-05-16 10:52 UTC, charanya-j commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/gov-overview.md
> +    You can view a visual representation of your savings trends through the **Savings Trend** graph, which allows you to hover over individual data points to view the corresponding cost savings for a
realized cost savings
enforcement -2
ec2 old instance and ec2 low usage
the same VM (instance or resource) can show up in both rules
these rules are independent and the cost is calculated independently for each execution. We need to note that there might be an overlap.

2023-05-19 12:39 UTC, riyasyash approved these changes

2023-05-19 12:40 UTC, riyasyash commented
@charanya-j Reviewed for lambda code update section doc

2023-05-21 02:10 UTC, charanya-j commented
Updated comments and created another pull request and merged 
https://github.com/harness/developer-hub/pull/1815

2023-05-21 02:10 UTC, closed without merging