[DOC-3105] - remote debugging
harness/developer-hub pull request #1728
Opened 2023-05-15 18:52 UTC by aimurphy

Add instructions for debug mode.

2023-05-17 12:11 UTC, HenAmar requested changes

2023-05-17 12:11 UTC, HenAmar commented on docs/continuous-integration/use-ci/debug-mode.md
> +   * Replace `{harness pat}` with your own [Harness personal access token](/docs/platform/user-management/add-and-manage-api-keys/#create-personal-access-token).
We have to mention the the private access token must have "pipeline execution" permission

2023-05-17 12:11 UTC, HenAmar commented on docs/continuous-integration/use-ci/debug-mode.md
> +
Is it worth mentioning that the ssh session will be available for 1 hour or step timeout (what comes first) . after that it goes out.

2023-05-17 16:27 UTC, rustd commented on docs/continuous-integration/use-ci/debug-mode.md
> +title: Debug mode
Title should be "Debug with SSH"

2023-05-17 19:29 UTC, aimurphy commented on docs/continuous-integration/use-ci/debug-mode.md
> +title: Debug mode
changed

2023-05-18 16:07 UTC, aimurphy commented on docs/continuous-integration/use-ci/debug-mode.md
> +* The build infrastructure is remote. This includes Harness Cloud, Kubernetes clusters, or AWS VMs on remote hosts.
Hen confirmed it can be either AWS or GVP as long as it's Linux based.

2023-05-23 13:55 UTC, HenAmar submitted a review, later dismissed

2023-05-23 13:58 UTC, KimberlyFields approved these changes

2023-05-23 14:18 UTC, merged