updates to CI java http server tutorial
harness/developer-hub pull request #182
Opened 2022-12-07 15:09 UTC by jimsheldon

more yaml-based

use include for docker hub connector

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-07 15:11 UTC, ravilach approved these changes
Thanks for adding to shared fold and trying out the component capability. Looks good to me.

2022-12-07 23:53 UTC, ravilach commented
Was able to merge in 181.

2022-12-08 00:17 UTC, KimberlyFields requested changes

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +### Modify pipeline
```suggestion
### Modify the pipeline
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +Select **Pipelines** from the menu on the left, then select your **jhttp** pipeline from the list.
```suggestion
From the left pane, select **Pipelines**, and then select your **jhttp** pipeline from the list.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +This configuration expects the Docker Hub connector ID to be `Docker_Hub`. If your connector ID is different, replace `Docker_Hub` with the correct ID.
```suggestion
This configuration requires the Docker Hub connector ID to be `Docker_Hub`. If your connector ID is different, replace `Docker_Hub` with the correct ID.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +Click the **Save** button in the YAML editor.
```suggestion
Select **Save** in the YAML editor.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
>  2. Select **Git Branch** as the **Build Type**, and then enter `main` in the **Branch Name** field.
```suggestion
2. In the **Build Type** field, select **Git Branch**, and then enter **main** in the **Branch Name** field.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/build-code/ci-java-http-server.md
> +4. Observe each step of the pipeline execution. When the first stage completes, test results appear in the **Tests** tab.
```suggestion
4. Observe each step of the pipeline execution. When the first stage completes, test results appear on the **Tests** tab.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +1. Expand the **Project Setup** menu on the left, then select **Connectors**.
```suggestion
1. From the left pane, expand the **Project Setup**, and then select **Connectors**.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +2. Click **+ New Connector**, and then select **Docker Registry**.
```suggestion
2. Select **+ New Connector**, and then select **Docker Registry**.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +3. In the **Name** field, enter `Docker Hub`, and then select **Continue**.
```suggestion
3. In the **Name** field, enter **Docker Hub**, and then select **Continue**.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +4. In the **Docker Registry URL** field, enter `https://index.docker.io/v2/`.
```suggestion
4. In the **Docker Registry URL** field, enter **https://index.docker.io/v2/**.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +7. In the **Password** field, select **Create or Select a Secret**. Follow the prompts to add your Docker Hub access token, then click **Continue**.
```suggestion
7. In the **Password** field, select **Create or Select a Secret**. Follow the prompts to add your Docker Hub access token, and then click **Continue**.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +8. At the next screen, select **Connect through Harness Platform**, then select **Save and Continue**.
```suggestion
8. At the next screen, select **Connect through Harness Platform**, and then select **Save and Continue**.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +9. Harness will perform a validation test, then click **Finish**.
```suggestion
9. After Harness performs a validation test, select **Finish**.
```

2022-12-08 00:17 UTC, KimberlyFields commented on tutorials/shared/dockerhub-connector-includes.md
> +10. In your list of connectors, note the ID of the connector that you just created. If you named the connecotr `Docker Hub`, the ID should be `Docker_Hub`.
```suggestion
10. In your list of connectors, note the ID of the connector that you just created. If you named the connector `Docker Hub`, the ID should be `Docker_Hub`.
```

2022-12-08 13:54 UTC, jimsheldon commented
Ping for @KimberlyFields if this is ready to merge 🙏🏻

2022-12-08 16:14 UTC, KimberlyFields commented
LGTM. @ravilach you didn't approve the PR. Do you want to give it one more review before merging?

2022-12-08 16:14 UTC, merged