CCM test branch
harness/developer-hub pull request #189
Opened 2022-12-08 17:43 UTC by charanya-j

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

Migrating CCM files to the Developer hub.

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

https://harness.atlassian.net/browse/DOC-2263
Local Yarn build was successful 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-08 22:51 UTC, KimberlyFields requested changes

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-azure.md
> +		7. Click **Create**.
Add an extra blank line between the image and step 7. This step renders as 7, but it should render as g because it is a sub-list of the sub-list for step 4.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-azure.md
> +
The numbering restarts at 1-3 instead of continuing from the previous numbering. These steps should be 6-8.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-gcp.md
> +### Overview
This heading shows up in the middle of the procedure.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/1-add-connectors/k8s-connector-autostopping.md
> +11. See [Set up CCM for Kubernetes](/docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-kubernetes.md) for instructions on creatin
The numbering resets to 1. These steps should be number 5-11.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-autostopping-rules-aws.md
> +2. Toggle the **Health check** button to configure the health check. Health check status should be successful for the AutoStopping rules to come into effect.
These steps should be numbers 2 and 3.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-autostopping-rules-for-kubernetes.md
> +2. If you have not added your cloud account, click **Connect to your** ***Cloud Account*** drop-down list. The name of the drop-down list depends on the cloud account type selection. If you select AW
The numbering reset to 1. These steps should be numbers 3 and 4.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-autostopping-rules-for-kubernetes.md
> +2. In **Idle time**, enter the idle time in minutes. This is the time that the AutoStopping rule will wait before stopping the idle instances.
These should be steps 4 and 5.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/manage-access-control-for-ccm-dashboards.md
> +3. In **Shared Resources**, select **Dashboards**.
Add a blank line above this line to fix an issue with step 3 appearing on the same line as "This section uses...".

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/orphaned-ebs-volumes-and-snapshots-dashboard.md
> +  2. **Custom**: Custom allows you to select the date range.
Make these items bullets instead of numbers. At first, I thought it was an issue with the numbering being reset. But, I think this information is part of step 4. Having 1 and 2 follow 4 is confusing.

2022-12-08 22:51 UTC, KimberlyFields commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/view-aws-resource-breakdown-cost-dashboard.md
> +5. Once you have made all the selections, click **Update**.  The data is refreshed with the latest data from the database.
The numbering reset to 1. These steps should be 3-7.

2022-12-09 06:14 UTC, charanya-j commented on docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-azure.md
> +		7. Click **Create**.
Done

2022-12-09 06:14 UTC, charanya-j commented on docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-azure.md
> +
Done

2022-12-09 06:37 UTC, charanya-j commented on docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-gcp.md
> +### Overview
Done

2022-12-09 12:58 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/1-add-connectors/k8s-connector-autostopping.md
> +11. See [Set up CCM for Kubernetes](/docs/cloud-cost-management/1-onboard-with-cloud-cost-management/set-up-cloud-cost-management/set-up-cost-visibility-for-kubernetes.md) for instructions on creatin
Done

2022-12-09 13:01 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-autostopping-rules-aws.md
> +2. Toggle the **Health check** button to configure the health check. Health check status should be successful for the AutoStopping rules to come into effect.
Done

2022-12-09 13:03 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-autostopping-rules-for-kubernetes.md
> +2. If you have not added your cloud account, click **Connect to your** ***Cloud Account*** drop-down list. The name of the drop-down list depends on the cloud account type selection. If you select AW
Done

2022-12-09 13:10 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/access-control/manage-access-control-for-ccm-dashboards.md
> +3. In **Shared Resources**, select **Dashboards**.
Done

2022-12-09 13:25 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/orphaned-ebs-volumes-and-snapshots-dashboard.md
> +  2. **Custom**: Custom allows you to select the date range.
Done

2022-12-09 13:28 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/view-aws-resource-breakdown-cost-dashboard.md
> +5. Once you have made all the selections, click **Update**.  The data is refreshed with the latest data from the database.
Done

2022-12-09 16:34 UTC, KimberlyFields approved these changes

2022-12-12 04:46 UTC, charanya-j commented
Merging the CCM migration branch with the main branch to publish the CCM docs to the Developer hub.

2022-12-12 04:48 UTC, merged