update release-notes.md
harness/developer-hub pull request #192
Opened 2022-12-09 07:16 UTC by SmritiSatya

Rephrase sentences, changed to bullet points, sentence case
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

2023-01-10 17:57 UTC, douglas-j-bothwell approved these changes
All looks good! Approved.

2023-01-10 18:00 UTC, michaelcretzman requested changes
minor things

2023-01-10 18:00 UTC, michaelcretzman commented on docs/chaos-engineering/introduction/release-notes.md
> +* UI/UX issues were fixed
no ticket number?

2023-01-10 18:00 UTC, michaelcretzman commented on docs/chaos-engineering/introduction/release-notes.md
> +* Configuring chaos infrastructure doesnot provide support for Linux and Windows.
change to "does not"

2023-01-11 03:29 UTC, SmritiSatya commented on docs/chaos-engineering/introduction/release-notes.md
> +* UI/UX issues were fixed
No, Michael. There weren't ticket numbers for some of the fixes/what's new.

2023-01-11 08:13 UTC, merged