[DOC-3231] - CI debug assistant
harness/developer-hub pull request #2039
Opened 2023-06-07 18:49 UTC by aimurphy

Created a new topic about the debug assistant. It uses partials.
- Preview: https://6490e3148dad3b4002d61be5--harness-developer.netlify.app/docs/continuous-integration/troubleshoot-ci/aida

Reorged some topics related to troubleshooting and created a folder for them, since there are three now. Updated links and redirects accordingly: https://6490e3148dad3b4002d61be5--harness-developer.netlify.app/docs/category/troubleshoot-ci

Added references to the debug assistant from related pages:
- Debug with ssh (debug-mode.md)
- Troubleshoot Continuous Integration (troubleshooting-ci.md)
- View builds (viewing-builds.md)

2023-06-20 00:41 UTC, douglas-j-bothwell approved these changes
Approved. No edits/sugs.

2023-06-20 13:31 UTC, douglas-j-bothwell requested changes
There's a malformed URL that needs to be fixed.

2023-06-20 13:31 UTC, douglas-j-bothwell commented on docs/continuous-integration/shared/aida-intro.md
> +[AIDA, the Harness AI Development Assistant,](https://http://harness.io/products/aida) can analyze log files and correlate error messages with known issues. This feature enables developers to trouble
```suggestion
[AIDA, the Harness AI Development Assistant,](https://harness.io/products/aida) can analyze log files and correlate error messages with known issues. This feature enables developers to troubleshoot and resolve deployment failures quickly, saving them from sifting through millions of log lines. AIDA also suggests fixes and predicts potential errors in the code even before the build is initiated. This feature is designed to work across Harness's CI and CD offerings.
```
The URL is malformed. I've updated it to what I THINK it's supposed to point to but I'm not positive b/c it's protected....

2023-06-21 12:40 UTC, KimberlyFields approved these changes

2023-06-21 12:40 UTC, merged