[DOC-3124] Added details for secret expiry date
harness/developer-hub pull request #2049
Opened 2023-06-08 11:21 UTC by rashminandasahoo

Set expiry date for secrets managed by Azure Key Vault.

## What Type of PR is This?

- [ ] Issue
- [x ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-06-08 12:05 UTC, nishantsaini20 submitted a review, later dismissed

2023-06-09 10:32 UTC, StrawberryPad requested changes

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +6. In **Inline Secret** **Value**, enter a value for the encrypted text.
Combine steps 6 and 7 - something like: 
6. Select the type of secret, and then configure the related values:
     * **Inline Secret Value**: enter a val.....
     * **Reference Secret**: if you have an Azure Key Vault or Hashicorp Vault secrets managers, you can reference existing secrets.

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +8. A secret can have an expiry date if it is managed by Azure Key Vault. To set an expiry date, select a date in **Expires on**.
Is this only if they select **Reference Secret**?

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +9. Enter **Description** for your secret.
```suggestion
9. (Optional) Enter a **Description** and **Tags** for your secret.
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +10. Enter **Tags** for your secret.
```suggestion
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Use the Encrypted Text in Connectors
```suggestion
## Use the secret in connectors
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
>  All of the passwords and keys used in Harness Connectors are stored as Encrypted Text secrets in Harness.
```suggestion
All of the passwords and keys used in Harness connectors are stored as encrypted text secrets in Harness.
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
>  You can either create the Encrypted Text secret first and then select it in the Connector or you can create/select it from the Connector by clicking **Create or Select a Secret**:
```suggestion
You can either [create the secret](#add-a-text-secret) first and then select it in the connector. or you can create it from the connector by clicking **Create or Select a Secret**:
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
>  You can also edit it in the Connector.
```suggestion
You can also edit the secret in the connector.
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Reference the Encrypted Text by Identifier
```suggestion
## Reference the secret by identifier
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
>  :::important
```suggestion
:::info important
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
>  :::important
I think the above will make the note say "Important" but better test it.

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Invalid Characters in Secret Names
```suggestion
## Invalid characters in secret names
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Secrets in Outputs
```suggestion
## Secrets in outputs
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Secret Scope
```suggestion
## Secret scope
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Line breaks and Shell-Interpreted Characters
```suggestion
## Line breaks and shell-interpreted characters
```

2023-06-09 10:32 UTC, StrawberryPad commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Characters length limit in Secret Names
```suggestion
## Characters length limit in secret names
```

2023-06-09 11:59 UTC, rashminandasahoo commented on docs/platform/Secrets/2-add-use-text-secrets.md
> +## Add a text secret
As discussed, secrets can be added at any scope. Changing the heading would be misleading.

2023-06-12 11:37 UTC, rashminandasahoo commented
Addressed the comments. Merging this since this is urgent.

2023-06-12 11:37 UTC, merged