CET release notes for 5.23.0 and 5.23.1
harness/developer-hub pull request #2053
Opened 2023-06-08 15:44 UTC by SudheendraKatte

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-06-08 18:10 UTC, aimurphy requested changes
Please see my comments.

2023-06-08 18:10 UTC, aimurphy commented on release-notes/continuous-error-tracking.md
> +## Latest - June xx, 2023, versions et-service 5.23.0 and et-collector 5.23.0
```suggestion
## Latest - June 9, 2023, versions et-service 5.23.0 and et-collector 5.23.0
```

2023-06-08 18:10 UTC, aimurphy commented on release-notes/continuous-error-tracking.md
> +## Latest - June xx, 2023, versions et-service 5.23.0 and et-collector 5.23.0
Please update the metadata at the top of the file to reflect the release date also.

2023-06-08 18:10 UTC, aimurphy commented on release-notes/continuous-error-tracking.md
> +- You can now conveniently access a comprehensive list of all active agents running across your entire account directly from the subscription page. (CET-1225)
```suggestion
- You can now conveniently access a comprehensive list of all active agents running across your entire account directly from the Subscription page. (CET-1225)
```

Not sure if the page name should be capitalized?

2023-06-08 18:10 UTC, aimurphy commented on release-notes/continuous-error-tracking.md
> +Released June xx, 2023
Please add the date.

2023-06-08 18:10 UTC, aimurphy commented on release-notes/continuous-error-tracking.md
> +##### Fixed issues
I don't think this heading is necessary because, by their nature, hotfixes only contain bug fixes.

2023-06-08 18:10 UTC, aimurphy commented on release-notes/continuous-error-tracking.md
> +- CET Agents that were started without providing an agent token are not appearing on the list of running agents. This issue has been resolved. (CET-1411)
```suggestion
- CET Agents that were started without providing an agent token are not appearing on the list of running agents. This issue has been resolved. (CET-1411)  
```

The format here does not follow how you presented the other fixed issues on the Fixed issues tab. The statement "This issue has been resolved" is in a different place.

2023-06-09 01:08 UTC, SudheendraKatte commented on release-notes/continuous-error-tracking.md
> +## Latest - June xx, 2023, versions et-service 5.23.0 and et-collector 5.23.0
Will add once the release date is announced.

2023-06-09 01:08 UTC, SudheendraKatte commented on release-notes/continuous-error-tracking.md
> +- You can now conveniently access a comprehensive list of all active agents running across your entire account directly from the subscription page. (CET-1225)
Page names are not capitalized across the CET topics.

2023-06-09 01:08 UTC, SudheendraKatte commented on release-notes/continuous-error-tracking.md
> +Released June xx, 2023
Will add once the release date is announced.

2023-06-09 01:08 UTC, SudheendraKatte commented on release-notes/continuous-error-tracking.md
> +##### Fixed issues
Good point! Updated.

2023-06-09 01:09 UTC, SudheendraKatte commented on release-notes/continuous-error-tracking.md
> +- CET Agents that were started without providing an agent token are not appearing on the list of running agents. This issue has been resolved. (CET-1411)
That was an error! Thanks for pointing out!!

2023-06-10 02:40 UTC, SudheendraKatte commented
Peer and tech review complete. Updated the release date.

2023-06-10 02:40 UTC, merged