PL-38935-JIT-user-provisioning
harness/developer-hub pull request #2137
Opened 2023-06-15 06:08 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-06-19 10:52 UTC, VikasMaddukuriHarness submitted a review, later dismissed

2023-06-19 11:15 UTC, StrawberryPad requested changes
Requesting some changes for clarity.

2023-06-19 11:15 UTC, StrawberryPad commented on docs/platform/3_User-Management/provision-use-jit.md
> +You can automatically provision users added to your SAML applications configured in Harness and allow them to access Harness.
I can't tell if it's the users that are configured in Harness, or the SAML apps that are configured in Harness. Also "them" is unclear... though I'm guessing it's the users.

2023-06-19 11:15 UTC, StrawberryPad commented on docs/platform/3_User-Management/provision-use-jit.md
> +Harness supports Just-in-time provisioning only if a new user attempts to log in via IDP.
```suggestion
Harness supports JIT provisioning only if a new user attempts to log in via IDP.
```

2023-06-19 11:15 UTC, StrawberryPad commented on docs/platform/3_User-Management/provision-use-jit.md
> +     ![](./static/jit-user-provisioning.png)
I think our convention is to have the image you might be referring to before the instruction on what to do. So if following this, this image should be in step 5.

2023-06-19 11:15 UTC, StrawberryPad commented on docs/platform/3_User-Management/provision-use-jit.md
> +
This is probably not a good use of tabs. You can simply add the link to instructions to the bullet list above. This is easier for the user, and more importantly here reduces the cost of maintenance of this doc (having tabs unnecessarily adds to maintenance time... important to consider when we're very short on resources).

2023-06-19 11:15 UTC, StrawberryPad commented on docs/platform/3_User-Management/provision-use-jit.md
> +   - **JIT Validation Key**: To log in for the first time, the SAML assertion must contain the key.
```suggestion
   - **JIT Validation Key**: The SAML assertion must contain this key on first login.
```

2023-06-19 11:15 UTC, StrawberryPad commented on docs/platform/3_User-Management/provision-use-jit.md
> +   - **JIT Validation Value**: At the time of first login, enter the value for the validation key that must be present in the SAML assertion.
```suggestion
   - **JIT Validation Value**: The value for the validation key that must be present in the SAML assertion on first login.
```

2023-06-20 10:43 UTC, rashminandasahoo commented on docs/platform/3_User-Management/provision-use-jit.md
> +You can automatically provision users added to your SAML applications configured in Harness and allow them to access Harness.
Rephrased.

2023-06-20 10:45 UTC, rashminandasahoo commented on docs/platform/3_User-Management/provision-use-jit.md
> +     ![](./static/jit-user-provisioning.png)
Done.

2023-06-20 10:47 UTC, rashminandasahoo commented on docs/platform/3_User-Management/provision-use-jit.md
> +
Done.

2023-06-20 13:19 UTC, merged