Add tutorial to build and containerise go application
harness/developer-hub pull request #214
Opened 2022-12-14 08:47 UTC by kameshsampath

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

Adding CI tutorial on how to build and containerise go application using CI pipelines.

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [x] *Optional* Screen Shoot. 
-

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/947745/207669988-b7ff2aca-b05c-4a81-98bb-385d526abbb8.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/947745/207669794-50374929-8043-4f03-b551-39e35ee83102.png">

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/947745/207669838-9a343b41-19e8-4ca5-816e-be596df9fd6a.png">

2022-12-14 14:00 UTC, ravilach requested changes
Looks good. Could we drop "CI" from the Page Title and Sidebar Nav?  e.g just " Build Go App". Cheers!
<img width="658" alt="image" src="https://user-images.githubusercontent.com/42775804/207614574-c98b6d5d-c673-4f56-ab26-adb190a15485.png">

2022-12-14 17:51 UTC, kameshsampath commented
> Looks good. Could we drop "CI" from the Page Title and Sidebar Nav? e.g just " Build Go App". Cheers! CC @kameshsampath <img alt="image" width="658" src="https://user-images.githubusercontent.com/42775804/207614574-c98b6d5d-c673-4f56-ab26-adb190a15485.png">

done!

2022-12-14 17:52 UTC, kameshsampath commented
> One more comment @kameshsampath from my side, can you add your Tile one more spot, in the "All Tutorials" section under CI -> https://github.com/harness/developer-hub/blob/main/src/components/LandingPage/AllTutorials.tsx. Cheers!

done

2022-12-14 17:57 UTC, ravilach commented
Thanks @kameshsampath! With a review from @KimberlyFields we should be good!

2022-12-19 13:46 UTC, ravilach commented
@kameshsampath looking at the build, on index.tsx, can you make one change? Or can bring your PR up to date with the repo e.g re-base? Not sure why this change didn't proprgate. 

![image](https://user-images.githubusercontent.com/42775804/208439657-8d52c0e3-c6b1-433e-b567-d25480546c96.png)


```

Exhaustive list of all broken links found:

- On source page path = /:

   -> linking to /tutorials/get-started

```

File:
https://github.com/harness/developer-hub/blob/main/src/pages/index.tsx

Change:

```
     <div className={styles.btnContainer}>
        <Link href="/tutorials">
          <button className="button button--primary">All Tutorials</button>

```

Cheers,

-Ravi

CC: @KimberlyFields @wei-harness

2022-12-19 15:46 UTC, kameshsampath commented
@ravilach did a rebase and pushed it back. Hope it is good now

2022-12-19 16:03 UTC, ravilach commented
Thanks @kameshsampath, all up to date, PR build passes. Cheers!

2022-12-19 20:55 UTC, ravilach commented
Heads up any suggestions please bulk-commit/accept. Each commit to the PR is a build :-)

2022-12-22 16:20 UTC, KimberlyFields requested changes
Please use the "Add suggestion to batch" option to accept the suggestions so that all of the updates are made in one commit. If you use the "Commit suggestion" option on each suggestion, a new build kicks off after every commit and slows down the builds.

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Navigate to __Project Setup__ --> __Secrets__,
```suggestion
1. Navigate to __Project Setup__, and then select  __Secrets__.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Click __+ New Secret__ and select __Text__,
```suggestion
2. Select __+ New Secret__ , and then select __Text__.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Set the __Secret Name__ to be `cosign_password` and fill your cosign private key password i.e. `$COSIGN_PASSSWORD` as __Secret Value__,
```suggestion
3. Set the __Secret Name__ to be `cosign_password`, and then fill your cosign private key password `$COSIGN_PASSSWORD` as __Secret Value__.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Click __+ New Secret__ and select __File__,
```suggestion
4. Select __+ New Secret__, and then select __File__.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Fill the details for the secret `cosign_private_key` as shown,
```suggestion
5. Fill the details for the secret `cosign_private_key` as shown.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +For the __Select File__ browse and pick the `cosign.key` from the `$TUTORIAL_HOME`.
```suggestion
6. For the __Select File__, browse and pick the `cosign.key` from the `$TUTORIAL_HOME`.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Repeat the same process of creating another `__File__` secret to store the cosign public key, this time using the file `cosign.pub` from the `$TUTORIAL_HOME`.
```suggestion
7. Repeat the same process of creating another `__File__` secret to store the cosign public key, this time using the file `cosign.pub` from the `$TUTORIAL_HOME`.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Fill the details for the secret `cosign_public_key` as shown,
```suggestion
8. Fill the details for the secret `cosign_public_key` as shown.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +With this we now have four secrets on our project,
```suggestion
With this we now have four secrets in our project:
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +## Update Pipeline to Sign the Container Image
```suggestion
## Update the pipeline to sign the container Image
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +We now have all required resources __cosign_password__, __cosign_private_key__ and __cosign_public_key__ to sign the container image using _cosign_.
```suggestion
We now have all of the required resources: __cosign_password__, __cosign_private_key__ and __cosign_public_key__ to sign the container image using _cosign_.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Let us now update the existing __build and push__ step of our `Build Go` pipeline to sign the `fruits-api` container image.
```suggestion
Now, update the existing __build and push__ step of our `Build Go` pipeline to sign the `fruits-api` container image.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Navigate to the __Projects__ --> __Pipelines__,
```suggestion
1. Navigate to __Projects__, and then  __Pipelines__.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +And click __Build Go__ pipeline to open the pipeline editor,
```suggestion
2. Select __Build Go__ pipeline to open the pipeline editor.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Click the step __build and push__ and update the __Command__ to be as shown,
```suggestion
3. Select the step __build and push__ and update the __Command__ to be as shown:
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Update the __Environment Variables__ section with following values,
```suggestion
4. Update the __Environment Variables__ section with following values:
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +The step also exposes an [output variable](https://docs.harness.io/article/4dot4qo5l4-download-and-copy-artifacts-using-the-command-step#output_variables) called `IMAGE_REF` which could be used by ot
```suggestion
The step also exposes an [output variable](https://developer.harness.io/docs/continuous-delivery/cd-execution/cd-general-steps/download-and-copy-artifacts-using-the-command-step) called `IMAGE_REF` which could be used by other steps, for example to verify the signature by using pipeline expression `<+steps.build_and_push.output.outputVariables.IMAGE_REF>`.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +:::note Points to Ponder
```suggestion
:::note 
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +- As marked ensure the `DOCKER_HUB_PASSWORD`,`COSIGN_PRIVATE_KEY` and `COSIGN_PASSWORD` are of type __Expression__
```suggestion
- As marked, ensure the `DOCKER_HUB_PASSWORD`,`COSIGN_PRIVATE_KEY` and `COSIGN_PASSWORD` are of the __Expression__ type.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +- `secrets.getValue` is an expression that allows to get the value from the secret `docker_hub_password`, that was created earlier in the tutorial. Check the [docs](https://developer.harness.io/docs/
```suggestion
- `secrets.getValue` is an expression that allows you to get the value from the secret `docker_hub_password` that was created earlier in the tutorial. Check the [docs](https://developer.harness.io/docs/platform/security/add-use-text-secrets/#step-3-reference-the-encrypted-text-by-identifier) for more information. 
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +- All `$DOCKER_HUB_USERNAME` references should your Docker Hub Username
```suggestion
- All `$DOCKER_HUB_USERNAME` references should your Docker Hub Username.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Click __Apply Changes__ to save the step and click __Save__ to save the pipeline.
```suggestion
5. Select __Apply Changes__ to save the step, and then select __Save__ to save the pipeline.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +As did earlier click __Run__ from the pipeline editor window,
```suggestion
1. As you did earlier, select __Run__ from the pipeline editor window.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Leaving everything to defaults namely __Git Branch__ and __Branch Name__ to be _main_, click __Run Pipeline__ to start the pipeline run.
```suggestion
2. Leaving all the default entries in place, namely __Git Branch__ and __Branch Name__ to be _main_, select __Run Pipeline__ to start the pipeline run.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +## Verify Signed Image
```suggestion
## Verify the signed image
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +To verify the image signature we use the public key `$COSIGN_PUBLIC_KEY` against the image `sha256` digest.
```suggestion
To verify the image signature, use the public key `$COSIGN_PUBLIC_KEY` against the image `sha256` digest.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +The command should show an output as shown if the signature is valid, with `$DOCKER_USERNAME` and `$IMAGE_REF` replaced your docker hub username and image digest from previous step.
```suggestion
The command should show an output as shown if the signature is valid, with `$DOCKER_USERNAME` and `$IMAGE_REF` replacing your Docker Hub username and image digest from the previous step.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +In an ideal scenario the verification will be done by governance tools like [OPA](https://www.openpolicyagent.org/docs/latest/) or [kyverno](https://kyverno.io/). The integration with those tools can
```suggestion
In an ideal scenario the verification is done by governance tools like [OPA](https://www.openpolicyagent.org/docs/latest/) or [kyverno](https://kyverno.io/). The integration with those tools can be done using Harness Platform with Harness Continuous Delivery.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +Can you update the pipeline to a sign verification step ?
```suggestion
Can you update the pipeline to a sign verification step?
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +## Continuing on Your Continuous Integration Journey
```suggestion
## Continuing on your continuous integration journey
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +You can now execute your builds whenever you want in a consistent fashion. Can modify the trigger to watch for SCM events so upon commit, for example, the Pipeline gets kicked off automatically. All
```suggestion
You can now execute your builds whenever you want in a consistent fashion. You can modify the trigger to watch for SCM events so upon commit, for example, the pipeline is kicked off automatically. All of the objects you create are available for you to reuse. Lastly, you can even save your backing work / have it as part of your source code. Everything that you do in Harness is represented by YAML; feel free to store it as part of your project.
```

2022-12-22 16:20 UTC, KimberlyFields commented on tutorials/build-code/ci-tutorial-container-signing.md
> +After you have built your artifact, the next step is to deploy your artifact. This is where Continuous Delivery steps in and make sure to check out some other [CD Tutorials](/tutorials/deploy-service
```suggestion
After you have built your artifact, the next step is to deploy your artifact. This is where Continuous Delivery steps in. Make sure to check out some other [CD Tutorials](/tutorials/deploy-services#all-tutorials).
```

2023-01-06 12:35 UTC, ravilach approved these changes

2023-01-06 12:36 UTC, merged