Pre go-live cleanup of ff docs
harness/developer-hub pull request #215
Opened 2022-12-14 15:00 UTC by Clare-Wilkinson

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-22 15:59 UTC, KimberlyFields requested changes
I made several suggestions. Use the "Add suggestion to batch" option to select the changes and have them all be part of one commit. If you commit each suggestion individually, a new build kicks off after each commit and slows down the build process.

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/1-ff-onboarding/2-ff-getting-started/3-java-quickstart.md
> +	+ For more information about Targets, go to [Target Management](https://docs.harness.io/category/xw2hz815l8-ff-target-management).
This should go to a topic in the developer hub.

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/2-ff-using-flags/5-manage-featureflags-in-git-repos.md
> + If you select the checkbox Always commit to this branch and do not prompt for commit message, the Auto-commit to the selected branch option will be toggled on.
```suggestion
 If you select the checkbox Always commit to this branch and do not prompt for a commit message, the Auto-commit to the selected branch option will be toggled on.
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/2-ff-using-flags/5-manage-featureflags-in-git-repos.md
> + The Auto-commit to selected branch toggle will be the same status as before you turned off synching with Git. 
```suggestion
 The Auto-commit to the selected branch toggle will be the same status as before you turned off synching with Git. 
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/1-sdk-overview/1-client-side-and-server-side-sdks.md
> +| **Users** | Designed to be used in applications, your users run directly on their own devices, such as mobile, desktop, and web applications. Optimized to be used by a single user and low bandwidth
```suggestion
| **Users** | Designed to be used in applications, your users run directly on their own devices, such as mobile, desktop, and web applications. Optimized to be used by a single user and provide low bandwidth consumption. Examples: JavaScript, iOS, Android, React Native SDKs.  | Designed to be used in server-side applications, such as web servers and backend services. Optimized to be used in multi-user and secure environments. Examples, Java, Go, and, Python SDKs. |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/1-sdk-overview/1-client-side-and-server-side-sdks.md
> +| **Security** | The SDKs are embedded in your applications and run on the browser or on mobile devices. Because of which these SDKs can be compromised by users when unpacking a mobile app or using t
```suggestion
| **Security** | The SDKs are embedded in your applications and run on the browser or on mobile devices. Therefore, these SDKs can be compromised by users when unpacking a mobile app or using the browser's developer tools to inspect the page. You should not use a server-side SDK key in client-side applications. Client-side SDKs only perform an evaluation of a flag and receive the result. They don't store all data about a flag. | The SDKs are embedded in applications that run on your servers, such as web servers or backend servers. These environments are comparatively safe. Server-side SDKs download all the feature flags that you have defined in a project and store them in memory. |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/2-flutter-sdk-reference.md
> +To check you have installed the prerequisites, run the `flutter doctor` command.
```suggestion
To check if you have installed the prerequisites, run the `flutter doctor` command. 
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +## Before You Begin
```suggestion
## Before you begin
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +* [Communication Strategy Between SDKs and Harness Feature Flags](../1-sdk-overview/2-communication-sdks-harness-feature-flags.md)
Include a "Before you begin" section only if necessary.

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +* [Create a Feature Flag on the Harness Platform](../../2-ff-using-flags/1-ff-creating-flag/4-create-a-feature-flag.md). If you are following along with the SDK README sample code, make sure your fla
```suggestion
* [Created a Feature Flag on the Harness Platform](../../2-ff-using-flags/1-ff-creating-flag/4-create-a-feature-flag.md). If you are following along with the SDK README sample code, make sure your flag is called `harnessappdemodarkmode`.
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +* [Create an SDK key and make a copy of it](../../2-ff-using-flags/1-ff-creating-flag/4-create-a-feature-flag.md#step-3-create-an-sdk-key)
```suggestion
* [Created an SDK key and made a copy of it](../../2-ff-using-flags/1-ff-creating-flag/4-create-a-feature-flag.md#step-3-create-an-sdk-key)
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +```
This is a good place to use tabs to present information for different platforms.

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +5. Complete the initialization.
Remove unnecessary capitalization in terms like environment and evaluate.

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +Import `FFContextProvider`  from `@harnessio/ff-react-client-sdk` to wrap your application. This allows you to access the Feature Flags service. For example:
```suggestion
Import `FFContextProvider` from `@harnessio/ff-react-client-sdk` to wrap your application. This allows you to access the Feature Flags service. For example: 
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +### Add your Client SDK Key
```suggestion
### Add your Client SDK key
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +To connect to the correct Environment that you set up on the Harness Platform, you need to add the Client SDK Key from that Environment. Input the Client SDK Key into the `apiKey` parameter, for exam
```suggestion
To connect to the correct environment that you set up on the Harness Platform, you need to add the Client SDK key from that environment. Input the Client SDK key into the `apiKey` parameter, for example:
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +### Add a Target
```suggestion
### Add a target
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +<summary>What is a Target?</summary>
```suggestion
<summary>What is a target?</summary> 
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +Targets are used to control which users see which Variation of a Feature Flag, for example, if you want to do internal testing, you can enable the Flag for some users and not others. When creating a
```suggestion
Targets are used to control which users see which variation of a feature flag, for example, if you want to do internal testing, you can enable the flag for some users and not others. When creating a target, you give it a name and a unique identifier. Often, targets are users but you can create a target from anything that can be uniquely identified, such as an app or a machine.  
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +For more information about Targets, go to [Targeting Users With Flags](../../2-ff-using-flags/4-ff-target-management/3-targeting-users-with-flags.md).
```suggestion
For more information about targets, go to [Targeting Users With Flags](../../2-ff-using-flags/4-ff-target-management/3-targeting-users-with-flags.md).
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +To add a Target that you want to Evaluate, build it using `cfTarget` and pass in arguments for the following:
```suggestion
To add a target that you want to evaluate, build it using `cfTarget` and pass in arguments for the following:
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +| identifier | Unique ID for the Target. | Required | `identifier: 'HT_1',` |
```suggestion
| identifier | Unique ID for the target. | Required | `identifier: 'HT_1',` |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +| name | Name for this Target. This does not have to be unique. **Note**: If you don’t provide a value, the name will be the same as the identifier. Read Regex requirements for Target names and ident
```suggestion
| name | Name for this target. This does not have to be unique. **Note**: If you don’t provide a value, the name will be the same as the identifier. Read Regex requirements for target names and identifiers below for accepted characters. | Required | `name: 'Harness_Target_1'` |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +| attributes | Additional data you can store for a Target, such as email addresses or location. These are key/pair values. | Optional | `email: 'demo@harness.io’ location: 'EMEA'` |
```suggestion
| attributes | Additional data you can store for a target, such as email addresses or location. These are key/pair values. | Optional | `email: 'demo@harness.io’ location: 'EMEA'` |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +<summary> Regex requirements for Target names and identifiers </summary>
```suggestion
<summary> Regex requirements for target names and identifiers. </summary>
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +The characters can be lowercase or uppercase but cannot include accented letters, for example `Cafe_789`.
I don't see an accent on the example characters.

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +| baseUrl | The URL used to fetch Feature Flag Evaluations. When using the Relay Proxy, make sure the URL you provide is publicly available. | `https://config.ff.harness.io/api/1.0` |
```suggestion
| baseUrl | The URL used to fetch feature flag evaluations. When using the relay proxy, make sure the URL you provide is publicly available. | `https://config.ff.harness.io/api/1.0` |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +| eventUrl | The URL for posting metrics data to the Feature Flag service. When using the Relay Proxy, make sure the URL you provide is publicly available. | `https://events.ff.harness.io/api/1.0` |
```suggestion
| eventUrl | The URL for posting metrics data to the feature flag service. When using the relay proxy, make sure the URL you provide is publicly available. | `https://events.ff.harness.io/api/1.0` |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +## Evaluate a Flag
```suggestion
## Evaluate a flag
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +Evaluating a Flag is when the SDK processes all Flag rules and returns the correct Variation of that Flag for the Target you provide.
```suggestion
Evaluating a flag is when the SDK processes all flag rules and returns the correct variation of that flag for the target you provide. 
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +If a matching Flag can’t be found, or the SDK can’t remotely fetch Flags, the default value is returned. The default value is undefined, however you can optionally set the default value to something
```suggestion
If a matching flag can’t be found, or the SDK can’t remotely fetch flags, the default value is returned. The default value is undefined, however you can optionally set the default value to something else, which is particularly useful if you plan to use async mode on startup. For more information about async mode, go to [Use async mode](#use-async-mode).
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +With this SDK you can evaluate a single Flag or a multiple Flags. To do this, import and use one of the following hooks and pass in:
```suggestion
With this SDK you can evaluate a single flag or a multiple flags. To do this, import and use one of the following hooks and pass in:
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +* Identifier of the Flag you want to evaluate
```suggestion
* Identifier of the flag you want to evaluate
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +* (Optional) The default Variation
```suggestion
* (Optional) The default variation 
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +##### Render if the Flag is enabled
```suggestion
##### Render if the flag is enabled 
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +By default `ifFeatureFlag` will render the component if the named Flag evaluates as truthy. In the below example, you can use `MyConditionalComponent` as a normal component and it will render the `My
truthy?

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +By default the component will display if the Flag value is evaluated as truthy. This behavior can be overridden by passing the matchValue option in the options object. The Flag value will then be com
```suggestion
By default the component will display if the flag value is evaluated as truthy. This behavior can be overridden by passing the matchValue option in the options object. The flag value will then be compared with `matchValue` to determine whether it should display. For example:
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +By default the component will display if the Flag value is evaluated as truthy. This behavior can be overridden by passing the matchValue option in the options object. The Flag value will then be com
truthy?

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/3-server-sdks/1-apex-sdk-reference.md
> +<summary> Regex requirements for Target names and identifiers </summary>
```suggestion
<summary> Regex requirements for target names and identifiers </summary>
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/3-server-sdks/1-apex-sdk-reference.md
> +## Evaluating a Flag
```suggestion
## Evaluating a flag
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/3-server-sdks/3-integrate-feature-flag-with-java-sdk.md
> +Below are the dependencies for Maven and Gradle that uses Java SDK version 1.1.8.0 as an example:
```suggestion
Below are the dependencies for Maven and Gradle that use Java SDK version 1.1.8.0 as an example:
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/3-server-sdks/4-net-sdk-reference.md
> +In Version 1.1.3 of the .NET SDK, the package name for installing the SDK changed from **ff-netF48-server-sdk** to **ff-dotnet-server-sdk**. To use this version, make sure you remove the old package
```suggestion
In Version 1.1.3 of the .NET SDK, the package name for installing the SDK changed from **ff-netF48-server-sdk** to **ff-dotnet-server-sdk**. To use this version, make sure you remove the old package name and use the new one. You can do this by using the following commands:  
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/3-server-sdks/4-net-sdk-reference.md
> +In Version 1.1.3 of the .NET SDK, the package name for installing the SDK changed from **ff-netF48-server-sdk** to **ff-dotnet-server-sdk**. To use this version, make sure you remove the old package
```suggestion
In Version 1.1.3 of the .NET SDK, the package name for installing the SDK changed from **ff-netF48-server-sdk** to **ff-dotnet-server-sdk**. To use this version, make sure you remove the old package name and use the new one. You can do this by using the following commands:  
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/4-ff-sdks/3-server-sdks/8-ruby-sdk-reference.md
> +| `name` | Name for this Target. This does not have to be unique. **Note**: If you don’t provide a value, Harness generates the name based on the ID.Read **Regex requirements for Target names and ide
```suggestion
| `name` | Name for this target. This does not have to be unique. **Note**: If you don’t provide a value, Harness generates the name based on the ID. Read **Regex requirements for target names and identifiers** below for accepted characters. | Optional **Note**: If you don't want to send a name, don't send the parameter. Sending an empty argument causes an error. | `("Harness_Target_1")` |
```

2022-12-22 15:59 UTC, KimberlyFields commented on docs/feature-flags/5-subscribe-ff/1-subscriptions-overview.md
> +Currently online subscriptions are available only to self-serve Feature Flags customers. For enterprise buyers or for subscribing to other modules, contact our Sales team.
```suggestion
Currently online subscriptions are available only to self-serve customers. If you are an enterprise buyer or want to subscribe to other modules, contact the Harness Sales team.
```

2023-01-03 11:38 UTC, Clare-Wilkinson commented on docs/feature-flags/4-ff-sdks/2-client-sdks/7-react-client.md
> +```
Yes I think so too.

2023-01-03 12:04 UTC, Clare-Wilkinson commented
Changes made as per Kim's review. Merging branch.

2023-01-03 12:04 UTC, merged