feat: [CDS-70736]: Add OCI support, ECR AWS configuration
harness/developer-hub pull request #2179
Opened 2023-06-20 12:13 UTC by mteodor

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *[CDS-70736](https://harness.atlassian.net/browse/CDS-70736)*
*  *[CDS-71192](https://harness.atlassian.net/browse/CDS-71192)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-06-20 13:35 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +* Currently, only Git platforms and HTTP Helm servers are supported in a GitOps Repository. Also OCI Helm repository is supported.
```suggestion
* Currently, only Git platforms, HTTP Helm servers, and OCI Helm repositories are supported in a GitOps Repository. 
```

2023-06-20 13:37 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/add-harness-git-ops-repository-credentials-template.md
> +* Currently, only Git platforms and HTTP Helm servers are supported in a GitOps Repository. Not supported for OCI Helm repositories.
Should you have to mention this explicitly? I mean the first sentence is enough to understand that OCI is not supported.

2023-06-20 20:07 UTC, mteodor commented on docs/continuous-delivery/gitops/add-harness-git-ops-repository-credentials-template.md
> +* Currently, only Git platforms and HTTP Helm servers are supported in a GitOps Repository. Not supported for OCI Helm repositories.
ok, removed

2023-06-20 20:23 UTC, lasdox submitted a review, later dismissed

2023-06-20 20:38 UTC, shivagowda commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +5. Clieck on **Enable OCI**
typo: Click

2023-06-20 20:43 UTC, shivagowda approved these changes
lgtm

2023-06-20 21:09 UTC, meenaravichandran1 commented
nit: Can you remove "." from the heading?
![image](https://github.com/harness/developer-hub/assets/111807454/c33a6892-856b-468b-b1b3-070be618e88c)

2023-06-20 21:11 UTC, mteodor commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +helpdocs_topic_id: lf6a27usso
how is this populated? @roshnisarangadharan

2023-06-21 05:00 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +helpdocs_topic_id: lf6a27usso
You only need the first 3 items. Ignore the rest. They're part of old topics.

2023-06-21 10:40 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +   - To add a private repository, select the authentication option with username and password.
```suggestion
   - To add a private repository, select the authentication option with username and password, and enter the access token.
```

2023-06-21 11:09 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +There is an additional CRD, `ECRAuthorizationToken` that generates the token. We will use this token instead of `ClusterSecretStore` in this setup.
```suggestion
There is an additional CRD, `ECRAuthorizationToken` that generates the token. We will use this CRD instead of `ClusterSecretStore` in this setup.
```

2023-06-21 11:49 UTC, roshnisarangadharan submitted a review, later dismissed

2023-06-21 11:55 UTC, roshnisarangadharan commented
@mteodor Let me know when you're planning to make this feature live. Will merge once it is in PROD.

2023-06-21 15:15 UTC, shivagowda submitted a review, later dismissed
lgtm

2023-06-22 08:52 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +The credentials used below are samples only. Use your actual credentials.
```suggestion
The credentials used above are samples only. Use your actual credentials.
```

2023-06-22 08:56 UTC, StrawberryPad requested changes

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +8. Select **Save & Continue**. Harness validates the connection.
This step (save and continue) is missing from the other two tabs. Should it be the last step in those tabs too?

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/harness-cd-git-ops-quickstart.md
> +15. In **Path**, select **helm-guestbook**. This is the location of this app in the repo: `https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook`. For Git and Helm repos prepopul
"For Git and Helm repos prepopulated path or chart dropbox will be shown as well as branch or tag for Git and version for Helm chart and , for OCI Helm repository chart."

This sentence is really hard to understand (also ungrammatical, but I can't tell what it should be instead). Suggest a sub-bullet list to clarify what's being said here, like what is shown for each one (Git, Helm, etc).

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +This topic assumes that you have already created as [OCI Helm repository](/docs/continuous-delivery/gitops/add-a-harness-git-ops-repository#add-a-repository).
```suggestion
This topic assumes that you have already created an [OCI Helm repository](/docs/continuous-delivery/gitops/add-a-harness-git-ops-repository#add-a-repository).
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +GitOps repositories are stored in Kubernetes secrets. For GitOps to be able to pull these repositories from Amazon ECR, you have to rotate the credentials stored in the secret. You can use [External
"GitOps repositories are stored in Kubernetes secrets." 
This doesn't seem correct. Should it be "GitOps repository credentials are stored in Kubernetes secrets"? Please double check with dev.

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +When storing an OCI Helm repository in Amazon Elastic Container Registry (Amazon ECR), you must obtain a token. The Amazon ECR tokens are short-lived, hence need rotation.
```suggestion
When storing an OCI Helm repository in Amazon Elastic Container Registry (ECR), you must obtain a token. The Amazon ECR tokens are short-lived, hence need rotation. 
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +The above commands installs the external secret operator with necessary Custom Resource Definitions (CRDs).
```suggestion
The above commands install the external secret operator with necessary Custom Resource Definitions (CRDs). 
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +The above commands installs the external secret operator with necessary Custom Resource Definitions (CRDs).
It's best practice to explain what the commands do before presenting them, so this sentence should be above the code snippet.

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +
It would be good to have a summary of (numbered) steps here to link to the sections below it.

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +In this topic, we will walk you through how to use the external secrets operator.
```suggestion
In this topic, we will walk you through how to use the External Secrets Operator.
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +In this topic, we will walk you through how to use the external secrets operator.
Since you're talking about a third party product, you should capitalize External Secrets Operator throughout the topic.

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +Use the following command to create AWS credentials in Kubernetes secret:
```suggestion
Use the following commands to create AWS credentials in Kubernetes secret: 
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +The credentials used below are samples only. Use your actual credentials.
```suggestion
The credentials used above are samples only. Use your actual credentials.
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +The credentials used below are samples only. Use your actual credentials.
ideally, this sentence should be above the code snippet, and in that case, it would point to "below".

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +The credentials created in the previous step `awssm-secret` is referenced here.
```suggestion
The secret created in the previous step, `awssm-secret`, is referenced below.
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +## Create Generator YAML
```suggestion
## Create generator YAML
```

2023-06-22 08:56 UTC, StrawberryPad commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +## Apply Generator YAML
```suggestion
## Apply generator YAML
```

2023-06-22 09:02 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/harness-cd-git-ops-quickstart.md
> +15. In **Path**, select **helm-guestbook**. This is the location of this app in the repo: `https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook`. For Git and Helm repos prepopul
I'm noticing this sentence addition now. Let me check with Dev what they mean by this.

2023-06-22 09:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/gitops/helm-oci-repository-aws-ecr.md
> +GitOps repositories are stored in Kubernetes secrets. For GitOps to be able to pull these repositories from Amazon ECR, you have to rotate the credentials stored in the secret. You can use [External
```suggestion
GitOps repository credentials are stored in Kubernetes secrets. For GitOps to be able to pull these repositories from Amazon ECR, you have to rotate the credentials stored in the secret. You can use [External Secrets Operator](https://external-secrets.io) and [ArgoCD ECR Updater](https://artifacthub.io/packages/helm/argocd-aws-ecr-updater/argocd-ecr-updater) to achieve this.
```

2023-06-22 10:53 UTC, StrawberryPad approved these changes

2023-06-22 20:24 UTC, shivagowda approved these changes
lgtm

2023-06-22 20:29 UTC, merged

2023-06-22 20:36 UTC, michaelcretzman commented
merged at the request of @shivagowda