CHAOS-1928: adds chaos 0.14.x release notes
harness/developer-hub pull request #2236
Opened 2023-06-23 14:41 UTC by StrawberryPad

2023-06-26 12:33 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +* Upgraded the database to update the index in the linuxInfrastructures collection. (CHAOS-1836)
We can remove this one!

2023-06-26 12:35 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +* Added a feature that removes chaos entities when there's a delete event for a project, org or account. Also subscribed to entity-crud redis stream to listen for deletion events. (CHAOS-1143)
```suggestion
* Enhanced the chaos entities deletion functionality to delete all chaos entities associated to a project, org or account when there's a delete event for a project, org or account respectively. (CHAOS-1143)
```

2023-06-26 12:37 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +* The **Discard** button is now disabled if there are no changes in an experiment. (CHAOS-1878)
Enhanced the Discard button on Chaos Studio to be disabled if there are no changes in an experiment.

2023-06-26 12:42 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +* Added logic to handle parallel experiments in the experiment manifest. (CHAOS-1208)
Fixed the issue when CD step was not showing parallel faults even when the selected experiment was having multiple parallel experiments

2023-06-26 12:44 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +* The **Chaos** Continuous Delivery (CD) step has been updated to handle new experiment and pipeline statuses. (CHAOS-733)
Fixed the issue when aborting an experiment running as part of a Pipeline, pipeline step used to show `All your faults executed without an issue`. Now it shows correct details based on experiment execution.

2023-06-26 12:56 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +* (CHAOS-1917) _XXX ISSUE IN PROGRESS XXX_
The issue has been fixed when generating chaos infrastructures manifest with NodeSelectors/Tolerations was resulting into having first letter of key/value pairs in capital.

2023-06-26 16:55 UTC, douglas-j-bothwell requested changes
One comment and a few remaining to-do's:
1. The date in the frontmatter needs updating **date: 2023-06-05T10:00**
2. The What's New page needs to updated with the new CE  features

2023-06-26 16:55 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
> +* Added support for new experiment run statuses in the **Chaos** Continuous Delivery (CD) step. (CHAOS-1210)
Why is this a Fixed Issue? Sounds more like a feature to me.

2023-06-27 08:37 UTC, StrawberryPad commented on release-notes/chaos-engineering.md
> +* Added support for new experiment run statuses in the **Chaos** Continuous Delivery (CD) step. (CHAOS-1210)
Chaos is not part of the core release so it doesn't get space in "What's New". Fixed the rest.

2023-06-27 14:38 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +## Latest - June 27, 2023, version 0.14.1
```suggestion
## Latest - June 28, 2023, version 0.14.1
```

2023-06-27 14:39 UTC, Jonsy13 submitted a review, later dismissed
Minor comment, looks good apart from that! Thanks @StrawberryPad 🚀

2023-06-28 09:42 UTC, Jonsy13 approved these changes

2023-06-28 09:58 UTC, merged