CDS-57634 - AWS SAM and Containerized Step Group topics
harness/developer-hub pull request #2249
Opened 2023-06-23 22:57 UTC by michaelcretzman

https://harness.atlassian.net/browse/CDS-57634

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* https://harness.atlassian.net/browse/CDS-57634

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-06-26 07:15 UTC, hextechpal requested changes

2023-06-26 07:15 UTC, hextechpal commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +To provide greater control over the resources used for CD steps, Harness also lets you use your own Kubernetes cluster as the runtime infrastructure for CD steps.
Not all cd steps are supported right now. We may need to rephrase this better

2023-06-26 07:15 UTC, hextechpal commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +You can use a CD step group that points to your cluster as the runtime infrastructure. Next, in the step group, a Docker in Docker (DinD) environment is set up for the steps. Each step in the group i
Dind is not setup by default if user needs didd they can set it up themselves, by adding a background step. We can link CI documentation to explain this more

2023-06-26 07:15 UTC, hextechpal commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +## Supported deployment types
I think this section doesn't belong in this doc. This doc should just explain that harness cd stages (deployment, custom) have the ability so spin up containers. I think this section belong to the sam documentation

2023-06-26 07:18 UTC, sahilhindwani-harness requested changes

2023-06-26 07:18 UTC, sahilhindwani-harness commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +You can use a CD step group that points to your cluster as the runtime infrastructure. Next, in the step group, a Docker in Docker (DinD) environment is set up for the steps. Each step in the group i
I think this statement is wrong. 
There is no dind requirement for the step group to run, we just need the kubernetes server and delegate should have permissions to create a pod inside that cluster. 

Only if one your plugin requires docker, then we should use dind step. It is not mandatory to add dind step always. Maybe it is required for sam plugin but overall it may or may not be required, depends on the use-case.

2023-06-26 07:18 UTC, sahilhindwani-harness commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +Think of each CD step as a container run inside the DinD environment, just like running `docker run` for the DinD environment and `docker exec` for each container:
I think it should be `each step is running inside kubernetes pod as containers`
Step group will create a pod and then create containers as per the step defined in step group.  Post that it will start executing those containers inside pods, one by one. 
If your step requires/assumes the docker to be present, we should create a dind step else it is not required.

2023-06-26 07:18 UTC, sahilhindwani-harness commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +You can use the same cluster to run the Harness delegate and the containerized step group(s), but it is not required.
We should add a limitation that your delegate should have permission to create a pod and secret inside that cluster else your executions might fail.

2023-06-26 07:18 UTC, sahilhindwani-harness commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +This option is disabled for deployment types that do not support containerized step groups.
As per our discussion in this thread, I think we are not disabling it. cc - @thisrohangupta 
https://harness.slack.com/archives/C04JTFQL0HK/p1687719066686259?thread_ts=1687465789.444989&cid=C04JTFQL0HK

2023-06-26 17:29 UTC, thisrohangupta commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +This option is disabled for deployment types that do not support containerized step groups.
We are not disabling it

2023-06-26 17:30 UTC, thisrohangupta commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/containerized-step-groups.md
> +You can use the same cluster to run the Harness delegate and the containerized step group(s), but it is not required.
Agreed, do we have a sample of the permissions needed @sahilhindwani-harness ?

2023-07-06 21:42 UTC, thisrohangupta approved these changes
Nice work Michael, this is what we discussed.

2023-07-07 17:42 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +Harness supports AWS SAM (Serverless Application Model) deployments. SAM is an open-source framework provided by Amazon Web Services (AWS) that simplifies the deployment and management of serverless
AWS Serverless Application Model (SAM)

2023-07-07 17:45 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +For SAM deployments in Harness, you simply add your SAM template to Harness, select the target region, and Harness will perform the SAM build and deploy.
```
For SAM deployments in Harness, add your SAM template to Harness, and then select the target region. Harness will perform the SAM build and deploy.
```

2023-07-07 17:46 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +For SAM deployments in Harness, you simply add your SAM template to Harness, select the target region, and Harness will perform the SAM build and deploy.
```suggestion
For SAM deployments in Harness, add your SAM template to Harness and select the target region. Harness will perform the SAM build and deploy.
```

2023-07-07 17:49 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +When you set up the Harness environment for your deployment, you will add a Harness AWS connector to the Harness environment Infrastructure Definition. Typically, the AWS connector uses the access an
```suggestion
When you set up the Harness environment for your deployment, you must add a Harness AWS connector to the Harness environment Infrastructure Definition. Typically, the AWS connector uses the access and secret keys for an AWS IAM user (there are other options). The permissions added to the IAM user account must permit whatever AWS service changes you are performing in your SAM template.
```

2023-07-07 17:51 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +- **CloudFormation permissions:** The IAM role should have permissions to create, update, and delete CloudFormation stacks. This includes permissions for creating and managing CloudFormation template
```suggestion
- **CloudFormation permissions:** The IAM role should have permissions to create, update, and delete CloudFormation stacks. This include permissions for creating and managing CloudFormation templates, stack resources, and stack policy.
```

2023-07-07 17:53 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +- **S3 bucket permissions:** If your SAM application requires storing artifacts or deployment packages in Amazon S3, the IAM role should have permissions to read and write to the specific S3 buckets
..used for storing the deployment artifacts.

2023-07-07 17:54 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +- **Other service-specific permissions:** Depending on the services your SAM application interacts with (e.g., DynamoDB, SNS, SQS, etc.), you may need to include additional permissions specific to th
```suggestion
- **Other service-specific permissions:** Depending on the services your SAM application interacts with (for example, DynamoDB, SNS, SQS, etc.), you may need to include additional permissions specific to those services.
```

2023-07-07 17:55 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +You add your SAM template in the Harness SAM service. Harness supports standard SAM templates.
```suggestion
Harness supports standard SAM templates. You can add your SAM template in the Harness SAM service. 
```

2023-07-07 17:55 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +3. Name the service an select **Save**.
```suggestion
3. Name the service and select **Save**.
```

2023-07-07 17:56 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +6. In **Specify Manifest Type**, select **AWS SAM Directory**, and select **Continue**.
```suggestion
6. In **Specify Manifest Type**, select **AWS SAM Directory**, and then select **Continue**.
```

2023-07-07 17:57 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +8. Select or create a new Harness Git connector to your Git provider, and then select **Continue**.
add a link for Git connector?

2023-07-07 17:57 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +   1.  **Manifest Identifier:** enter a name for the template.
```suggestion
   1.  **Manifest Identifier:** Enter a name for the template.
```

2023-07-07 17:57 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +   2.  **Git Fetch Type:** select how you want to fetch the template.
```suggestion
   2.  **Git Fetch Type:** Select how you want to fetch the template.
```

2023-07-07 17:57 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +   3.  **Branch**/**Commit Id:** enter the branch name or commit Id.
```suggestion
   3.  **Branch**/**Commit Id:** Enter the branch name or commit Id.
```

2023-07-07 17:58 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +You can also add a values.yaml file to use Go templating in your SAM template. Go templating allows you to select different values.yaml files for different environments, etc.
etc. in the end is confusing. 
Go templating allows you to select different values.yaml files for different environments.

2023-07-07 17:59 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +And then your template references the values.yaml file using the format `{{.Values.KEY}}`. Here's an example using `{{.Values.runtime}}`:
```suggestion
Your template references the values.yaml file using the format `{{.Values.KEY}}`. Here's an example using `{{.Values.runtime}}`:
```

2023-07-07 17:59 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +You can create service variables and then use them in the values.yaml file you added.
```suggestion
You can create service variables, and then use them in the values.yaml file you added.
```

2023-07-07 18:00 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +For information on how to override service variables at the environment level, go to [Services and environments basics](http://localhost:3000/docs/continuous-delivery/get-started/services-and-environ
```suggestion
For information on how to override service variables at the environment level, go to [Services and environments basics](/docs/continuous-delivery/get-started/services-and-environments-overview).
```

2023-07-07 18:00 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +For information on general environment settings, go to [Services and environments basics](http://localhost:3000/docs/continuous-delivery/get-started/services-and-environments-overview).
```suggestion
For information on general environment settings, go to [Services and environments basics](/docs/continuous-delivery/get-started/services-and-environments-overview).
```

2023-07-07 18:00 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +For information on general service settings, go to [Services and environments basics](http://localhost:3000/docs/continuous-delivery/get-started/services-and-environments-overview).
```suggestion
For information on general service settings, go to [Services and environments basics](/docs/continuous-delivery/get-started/services-and-environments-overview).
```

2023-07-07 18:02 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +2. Select **Infrastructure Definitions**.
```suggestion
```

2023-07-07 18:03 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +2. Select **Infrastructure Definitions**.
Deleting step 2 as selecting infra def is mentioned in step 1. Continue numbering the procedure.

2023-07-07 18:03 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +4. In **Connector**, select or create a Harness AWS connector. Ensure the IAM account uses the required permissions for the operations your SAM template requires.
may be a link to how to create the AWS connector?

2023-07-07 18:04 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +4. In **Connector**, select or create a Harness AWS connector. Ensure the IAM account uses the required permissions for the operations your SAM template requires.
Ensure that the IAM account..

2023-07-07 18:04 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +5. In **Service**, select the SAM service to use, and select **Continue**.
```suggestion
5. In **Service**, select the SAM service to use, and then select **Continue**.
```

2023-07-07 18:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +6. In **Environment**, select the SAM environment and infrastructure definition to use, and select **Continue**.
```suggestion
6. In **Environment**, select the SAM environment and infrastructure definition to use, and then select **Continue**.
```

2023-07-07 18:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +- **SAM step group:** uses your Kubernetes cluster as a step runtime infrastructure.
```suggestion
- **SAM step group:** Uses your Kubernetes cluster as a step runtime infrastructure.
```

2023-07-07 18:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +  - **DinD Background step:** creates a Docker in Docker container for the each step's execution resources.
```suggestion
  - **DinD Background step:** Creates a Docker in Docker container for the each step's execution resources.
```

2023-07-07 18:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +  - **Download Manifests step:** fetches your SAM template.
```suggestion
  - **Download Manifests step:** Fetches your SAM template.
```

2023-07-07 18:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +  - **SAM Build step:** runs a [sam build](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html).
```suggestion
  - **SAM Build step:** Runs a [sam build](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html).
```

2023-07-07 18:06 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +  - **SAM Deploy step:** runs a [sam deploy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html).
```suggestion
  - **SAM Deploy step:** Runs a [sam deploy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html).
```

2023-07-07 18:07 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +When the step group setting **Enable container based execution** is enabled, the step group is containerized. When it is disabled, the Harness delegate performs all tasks on its host system.
```suggestion
When the step group setting **Enable container based execution** is enabled, the step group is containerized. When it is disabled, the Harness Delegate performs all tasks on its host system.
```

2023-07-07 18:07 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +- **Kubernetes Cluster:** add a Harness [Kubernetes Cluster connector](https://developer.harness.io/docs/platform/connectors/cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-
```suggestion
- **Kubernetes Cluster:** Add a Harness [Kubernetes Cluster connector](https://developer.harness.io/docs/platform/connectors/cloud-providers/ref-cloud-providers/kubernetes-cluster-connector-settings-reference/) to connect to the cluster that will be used as the runtime step infrastructure.
```

2023-07-07 18:07 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +- **Namespace:** enter the name of the cluster namespace to use.
```suggestion
- **Namespace:** Enter the name of the cluster namespace to use.
```

2023-07-07 18:13 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +You can add/select a different container registry connector and image for each step, but the image should support the SAM template operations you are deploying.
add or select

2023-07-07 18:14 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +2. In **Container Registry**, the Harness container registry connector is already set up. You can add/select your own container registry connector if you like.
Container Registry connector...
add or select

2023-07-07 18:14 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +The Download manifests step fetches the SAM template in the Harness service you selected for this stage. The step does not require configuration.
```suggestion
The Download Manifests step fetches the SAM template in the Harness service you selected for this stage. The step does not require configuration. 
```

2023-07-07 18:15 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +1. **Git initialization:** the command `git init` is executed to initialize a new Git repository.
```suggestion
1. **Git initialization:** The command `git init` is executed to initialize a new Git repository.
```

2023-07-07 18:15 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +2. **Setting remote origin:** the command `git remote add origin <repository-url>` is executed to set the remote origin for the Git repository.
```suggestion
2. **Setting remote origin:** The command `git remote add origin <repository-url>` is executed to set the remote origin for the Git repository.
```

2023-07-07 18:15 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +3. **Fetching remote branches:** the command `git fetch --depth=50 origin +refs/heads/main:` is executed to fetch the remote branches from the origin.
```suggestion
3. **Fetching remote branches:** The command `git fetch --depth=50 origin +refs/heads/main:` is executed to fetch the remote branches from the origin.
```

2023-07-07 18:15 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +4. **Checking out main branch:** the command `git checkout -b main origin/main` is executed to create and switch to a new branch named `main` based on the remote branch `origin/main`.
```suggestion
4. **Checking out main branch:** The command `git checkout -b main origin/main` is executed to create and switch to a new branch named `main` based on the remote branch `origin/main`.
```

2023-07-07 18:16 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +The SAM Build step performs a standard [sam build](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) as well as setting up the c
```suggestion
The SAM Build step performs a standard [SAM build](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) as well as setting up the container environment, resolving expressions in the SAM template, and building the SAM application using the specified dependencies and Docker container image.
```

2023-07-07 18:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +The [--use-container](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) option is set up by Harness automatically. This command
```suggestion
The [--use-container](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) option is set up by Harness automatically. This command ensures that AWS SAM packages and builds the application code inside a Docker container that is configured with the necessary dependencies and runtime environment specified in the AWS SAM template.
```

2023-07-07 18:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +In SAM Build Docker Container Registry, you can use the same Harness Docker Registry connector automatically set up in the **Container Registry** setting or add/select your own connector.
registry

2023-07-07 18:18 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +   1. Several environment variables are set using the export command, including `PLUGIN_SAM_TEMPLATE_FILE_PATH`, `PLUGIN_VALUES_YAML_FILE_PATH`, and `PLUGIN_VALUES_YAML_CONTENT`. These variables are
```suggestion
   1. Several environment variables are set using the `export` command, including `PLUGIN_SAM_TEMPLATE_FILE_PATH`, `PLUGIN_VALUES_YAML_FILE_PATH`, and `PLUGIN_VALUES_YAML_CONTENT`. These variables are exported to be used in subsequent commands.
```

2023-07-07 18:19 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +The SAM Deploy step performs a standard [sam deploy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html).
```suggestion
The SAM Deploy step performs a standard [SAM deploy](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html).
```

2023-07-07 18:20 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +1. Open the SAM Deploy step.
What do you mean by open here? Selecting the step?

2023-07-07 18:20 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +1. Open the SAM Build step.
What do you mean by open here?

2023-07-07 18:21 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +6.  Information about the managed S3 bucket is displayed.
```suggestion
6. Information about the managed S3 bucket is displayed.
```

2023-07-07 18:21 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +7.  Details of the deployment are displayed, including stack name, region, and other parameters.
```suggestion
7. Details of the deployment are displayed, including stack name, region, and other parameters.
```

2023-07-07 18:21 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +8.  The deployment is initiated.
```suggestion
8. The deployment is initiated.
```

2023-07-07 18:22 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +9.  The SAM deployment is successful.
```suggestion
9. The SAM deployment is successful.
```

2023-07-07 18:23 UTC, roshnisarangadharan approved these changes
Approved with some suggestions and comments. Implement as you see fit.

2023-07-07 21:16 UTC, michaelcretzman commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/aws-sam-deployments.md
> +2. Select **Infrastructure Definitions**.
actually, our UI requires you select the Infra Def tab, and then the Infra Def button to create the Infra Def.

2023-07-07 21:44 UTC, merged