permission note for copy template
harness/developer-hub pull request #230
Opened 2022-12-19 05:24 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-19 05:28 UTC, utkarshchoubey-harness requested changes
name of permission is - core_template_copy

2022-12-20 10:58 UTC, deepakbolangady commented on docs/platform/13_Templates/use-a-template.md
>  Once you've made all the changes, click **Run** and then click **Run Pipeline**. The Template is deployed.
1) Good to use a comma before "and then" in instructions. 
2) Also, good to replace "once" with "after".
3) Use lowercase in "template".

2022-12-20 10:58 UTC, deepakbolangady commented on docs/platform/13_Templates/use-a-template.md
>  ### Option: Copy to Pipeline
1) "Copy to the pipeline"? (use of "the" and lowercase pipeline)
2) Global comment: per our style guide, "Begin with the most meaningful words. Do not include “Step”, “Review”, “Option” at the beginning of headings."

2022-12-20 10:58 UTC, deepakbolangady commented on docs/platform/13_Templates/use-a-template.md
> +To copy a template, make sure you have the **core_template_copy** permission. The option to copy templates is disabled if you do not have this permission.
The second sentence in this note is implied by the first. It is not necessary. Also, should this be in a prereqs section?

2022-12-20 11:34 UTC, deepakbolangady commented on docs/platform/13_Templates/use-a-template.md
> +### Step: Use a template
We still need to fix how we begin our titles. Again, quoting from our style guide: "Begin with the most meaningful words. Do not include “Step”, “Review”, “Option” at the beginning of headings."

Please make this change as soon as you can across your doc set. Thanks.

2022-12-20 11:36 UTC, deepakbolangady approved these changes
One comment was missed: from our style guide, "Begin with the most meaningful words. Do not include “Step”, “Review”, “Option” at the beginning of headings."

I'll approve for now, but please create a follow-up PR for this change. Thanks.

2022-12-20 11:37 UTC, merged