[DOC-3338] Multilayer caching topic
harness/developer-hub pull request #2318
Opened 2023-06-30 18:41 UTC by aimurphy

2023-06-30 19:13 UTC, jamie-harness commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +                      echo <+execution.steps.L1_Caching.status>
let's remove this echo. It was for my debug purpose

2023-06-30 19:16 UTC, jamie-harness requested changes

2023-06-30 19:16 UTC, jamie-harness commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +* All **Restore Cache** steps except the last (`n-1`) have a [failure strategy](/docs/platform/pipelines/w_pipeline-steps-reference/step-failure-strategy-settings/) that causes the step to fail if th
All **Restore Cache** steps except the last (`n-1`) have a [failIfKeyNotFound] set to true, so that the step is marked as failure

It also need a failure strategy to ignore the same failure, putting the step to fail ignored or similar state so that it failed, but does not fail the whole pipeline

2023-06-30 19:52 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +* All **Restore Cache** steps except the last (`n-1`) have a [failure strategy](/docs/platform/pipelines/w_pipeline-steps-reference/step-failure-strategy-settings/) that causes the step to fail if th
Fixed, thank you for the clarification.

2023-06-30 19:53 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +                      echo <+execution.steps.L1_Caching.status>
Removed it.

2023-06-30 20:07 UTC, jamie-harness requested changes

2023-06-30 20:07 UTC, jamie-harness commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +* All **Restore Cache** steps except the last (`n-1`) have a [failure strategy](/docs/platform/pipelines/w_pipeline-steps-reference/step-failure-strategy-settings/) that causes the step to fail if th
This is not a failure strategy. failIfKeyNotFound is a checkbox you can find only in the cache plugin step

2023-06-30 20:14 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +* All **Restore Cache** steps except the last (`n-1`) have a [failure strategy](/docs/platform/pipelines/w_pipeline-steps-reference/step-failure-strategy-settings/) that causes the step to fail if th
Okay

2023-06-30 20:15 UTC, jamie-harness approved these changes

2023-07-05 16:28 UTC, StrawberryPad approved these changes

2023-07-05 16:28 UTC, StrawberryPad commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +## Pattern overview
```suggestion
## Pattern for CI pipelines with multilayer caching
```

2023-07-05 16:28 UTC, StrawberryPad commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +## Pattern overview
Or something similarly specific to make the heading more scannable.

2023-07-05 16:28 UTC, StrawberryPad commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +The following steps demonstrate how to configure multilayer caching in one stage of a CI pipeline.
```suggestion
Follow these steps to configure multilayer caching in one stage of a CI pipeline.
```

2023-07-05 16:28 UTC, StrawberryPad commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +   The following YAML example would add two **Restore Cache from GCS** steps to a pipeline:
```suggestion
   The following YAML adds two **Restore Cache from GCS** steps to a pipeline:
```

2023-07-05 16:28 UTC, StrawberryPad commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +2. On each **Restore Cache** step *except the last*, enable **Fail if Key Doesn't Exist** and add a [failure strategy](/docs/platform/pipelines/w_pipeline-steps-reference/step-failure-strategy-settin
```suggestion
2. On each **Restore Cache** step *except the last*, enable **Fail if Key Doesn't Exist**, and add a [failure strategy](/docs/platform/pipelines/w_pipeline-steps-reference/step-failure-strategy-settings/) where the step fails on **All Errors** and executes the **Ignore** action in response. For example:
```

2023-07-05 16:28 UTC, StrawberryPad commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +   Set the conditional execution to **Execute this step if the stage execution is successful thus far** (`stageStatus: Success`) and include the JEXL condition `<+execution.steps.L1_Caching.status> =
```suggestion
   Set the conditional execution to **Execute this step if the stage execution is successful thus far** (`stageStatus: Success`) and include the JEXL condition `<+execution.steps.L1_Caching.status> == "IGNORE_FAILED"`. For example:
```

2023-07-05 16:28 UTC, StrawberryPad commented on docs/continuous-integration/use-ci/caching-ci-data/multilayer-caching.md
> +   Set the conditional execution to **Execute this step if the stage execution is successful thus far** (`stageStatus: Success`) and include the JEXL condition `<+execution.steps.L1_Caching.status> =
I do this if the sentence is really long.

2023-07-05 17:04 UTC, merged