added Harness CI/CD tutorial
harness/developer-hub pull request #236
Opened 2022-12-20 06:25 UTC by pavanbelagatti

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-20 14:18 UTC, ravilach requested changes

2022-12-20 14:18 UTC, ravilach commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +# Harness Continuous Integration and Continuous Delivery
Can we change the title e.g the H1 Tag here to `# Build and Deploy a NodJS App to Kubernetes`

2022-12-20 14:18 UTC, ravilach commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +- Free [Harness](https://app.harness.io/auth/#/signup/?utm_source=internal&utm_medium=social&utm_campaign=community&utm_content=pavan_cicd_article&utm_term=get-started) account to do CI/CD (on-premis
Can we change the UTM links to `https://app.harness.io/auth/#/signup/?module=cd&?utm_source=website&utm_medium=harness-developer-hub&utm_campaign=cd-plg&utm_content=get-started`

2022-12-20 14:19 UTC, ravilach commented
@pavanbelagatti thanks for the contribution. You can just re-commit to your branch for the changes. Tagging in @michaelcretzman as the CD reviewer. Cheers!

2022-12-22 07:25 UTC, pavanbelagatti commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +# Harness Continuous Integration and Continuous Delivery
Updated the Header Title

2022-12-22 07:25 UTC, pavanbelagatti commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +- Free [Harness](https://app.harness.io/auth/#/signup/?utm_source=internal&utm_medium=social&utm_campaign=community&utm_content=pavan_cicd_article&utm_term=get-started) account to do CI/CD (on-premis
Changed the link! Thanks for the quick feedback @ravilach

2022-12-27 04:52 UTC, pavanbelagatti commented
@michaelcretzman can you please take a look

2022-12-27 17:58 UTC, KimberlyFields requested changes
Be sure to use the **Add suggestion to batch** option to accept the suggestions instead of committing each suggestion individually. The batch option combines all the changes into a single commit. The preview build is rebuilt every time there's a new commit, so doing a batch prevents the preview build from rebuilding multiple times.

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Add the required connectors, GitHub repo, Docker Hub and secrets, if any. Delegate in Harness is a service/software you need to install/run on the target cluster [Kubernetes cluster in our case] to c
```suggestion
4. Add the required connectors, GitHub repo, Docker Hub and secrets, if any. The Harness Delegate is a lightweight worker process that you need to install on the target cluster to connect your artifacts, infrastructure, collaboration, verification, and other providers with the Harness Manager. When you set up Harness for the first time, you install a Harness Delegate.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Select the Continuous Integration module and add the necessary stages and steps, as shown below.
```suggestion
5. Select the Continuous Integration module, and then add the necessary stages and steps, as shown below.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Select the Continuous Integration module and add the necessary stages and steps, as shown below.
```suggestion
5. Select the Continuous Integration module, and then add the necessary stages and steps, as shown below.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +‘Test’ step set-up is done as below,
```suggestion
6. Set up the Test step as shown below.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +The “‘Push to Docker Registry” step is as below,
```suggestion
7. Set up the Push to Docker Registry step as shown below.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Next, set up a deployment pipeline.
```suggestion
8. Next, set up a deployment pipeline.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Add the required details in the “Service” tab.
```suggestion
9. Add the required details on the **Service** tab.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Define the environment type in the “Environment” tab.
```suggestion
10. Define the environment type in the **Environment** tab.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Strategise the execution by selecting which deployment you prefer.
```suggestion
11. Strategize the execution by selecting the deployment you prefer.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +Save everything and run the pipeline.
```suggestion
12. Save everything, and then run the pipeline.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +You can see both CI and CD getting executed one by one with all the steps specified.
```suggestion
You can see both CI and CD being executed one by one with all the steps specified.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +**Congratulations!** We successfully built, and tested the application code and deployed it onto our Kubernetes cluster using the Harness platform.
```suggestion
**Congratulations!** You successfully built and tested the application code and deployed it onto the Kubernetes cluster.
```

2022-12-27 17:58 UTC, KimberlyFields commented on tutorials/deploy-services/harness-cicd-tutorial.md
> +You can see two replicas running as per our specifications on the `deployment.yaml` file. Also, confirm the same by going to your Kubernetes dashboard. Since I am using Google cloud (GCP), I can see
```suggestion
You can see two replicas running as per the specifications on the `deployment.yaml` file. Also, confirm the same by going to your Kubernetes dashboard. The following image shows two pods running on Google cloud (GCP).
```

2022-12-29 15:26 UTC, KimberlyFields approved these changes

2022-12-29 15:27 UTC, KimberlyFields commented
@ravilach you requested some changes on this PR and it looks like they were addressed. Are you ok with this PR being merged?

2023-01-03 18:44 UTC, michaelcretzman commented
PR gives me a 404. 
All links to the MD file here are outdated.
Removing myself as reviewer.

2023-01-03 19:06 UTC, ravilach commented
Sorry I missed this convo. @KimberlyFields looks good to me. @pavanbelagatti we will need to get your tile added to https://developer.harness.io/tutorials/deploy-services, can create a separate PR for that.

2023-01-03 19:06 UTC, merged