Update virtual-machine-on-prem-backup-and-recovery.md
harness/developer-hub pull request #239
Opened 2022-12-21 00:45 UTC by kat-enos

Small changes per the guidelines. Fixed some format issues. (All changes are previewed, even if not formally tested locally.)

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-12 10:37 UTC, deepakbolangady requested changes
LGTM with a few updates. Thanks!

2023-01-12 10:37 UTC, deepakbolangady commented on docs/first-gen/fg-sme/k8s/kubernetes-cluster-on-prem-add-ingress-controller-service-annotations.md
> +Annotations are done in the KOTS admin tool's Nginx Ingress Controller Service Annotations settings.
Is there any way to change this to the active voice? For example, "You add annotations by ..."

2023-01-12 10:37 UTC, deepakbolangady commented on docs/first-gen/fg-sme/k8s/kubernetes-cluster-on-prem-add-ingress-controller-service-annotations.md
> +In **Nginx Ingress Controller Service Annotations**, enter your annotations. See [NGINX Ingress Controller Annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annot
```suggestion
In **Nginx Ingress Controller Service Annotations**, enter your annotations. For examples from Kubernetes, see [NGINX Ingress Controller Annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/) and [Ingress Controllers](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/).
```

2023-01-12 10:37 UTC, deepakbolangady commented on docs/self-managed-enterprise-edition/self-managed-enterprise-edition-guide/virtual-machine-on-prem-backup-and-recovery.md
> +   For **Amazon S3** and **Other S3-Compatible Storage**, enter in the location and credentials.
```suggestion
   In **Amazon S3** and **Other S3-Compatible Storage**, enter the location and credentials.  
```

2023-01-12 10:37 UTC, deepakbolangady commented on docs/self-managed-enterprise-edition/self-managed-enterprise-edition-guide/virtual-machine-on-prem-backup-and-recovery.md
> +2. Click **Start a snapshot**. The snapshot begins. You can see its progress:
```suggestion
2. Click **Start a snapshot**. The snapshot process begins. You can see its progress:
```

2023-01-12 17:19 UTC, kat-enos commented on docs/first-gen/fg-sme/k8s/existing-cluster-kubernetes-on-prem-infrastructure-requirements.md
> +The outbound access is required for a **connected install only**. If you use [Airgap mode](https://kots.io/kotsadm/installing/airgap-packages/), this is not required.
I didn't catch this one but based on looking at Wikipedia and some security sources, decided to standardize on "air gap" or, when the hyphenate is appropriate, "air-gapped [environment]". I try to clarify by using "disconnected environment" on first reference and then putting "(air gap)" after that. But air gap is well accepted jargon in the security world so I don't believe there's an issue. I'm not sure that the Airgap company would be able to register "airgap" as a tradename. Terminology aside, in this case it's possible to write around the issue by labeling the link with the title of the target, which is not "Airgap mode". 

I have a developmental edit of all of this KOTS stuff but haven't had a chance to spend the time on it and we will be deprecating KOTS installation for Self-Managed Enterprise Edition this year and doing it with Helm.

2023-01-12 17:20 UTC, kat-enos commented on docs/first-gen/fg-sme/k8s/existing-cluster-kubernetes-on-prem-infrastructure-requirements.md
> +The outbound access is required for a **connected install only**. If you use [Airgap mode](https://kots.io/kotsadm/installing/airgap-packages/), this is not required.
Thanks, Deepak, for helping me out with these reviews. I need to get these changes to minimize the problems that might develop with the larger PRs slated for the next few days.

2023-01-12 17:30 UTC, kat-enos commented on docs/first-gen/fg-sme/k8s/existing-cluster-kubernetes-on-prem-infrastructure-requirements.md
> +For secure connections from any integration into the Harness Manager (Github Webhooks, for example), including **Harness Delegate**, you must use a publicly trusted certificate.
Because I haven't had the chance to implement my developmental edit of the KOTS install material, which includes much rewriting, I haven't smoothed out some of these issues.

Re "secure connections," I agree that it should be "to Harness Manager." I will also strike "the" before Harness Manager" since tech docs style is generally to drop the article before product names. I don't like classing Harness Delegate as an integration since it's not third party so will restate the sentence and probably get ride of the parenthetical "for example" statement in the middle of the sentence. 

I would use bold text for Harness Delegate if it was the label/name for a UI screen or, depending on company style, if it was spelled out like a programming element, for example, **harnessDelegate**. 

I agree that ambiguity is an issue. Sometimes it's necessary to avoid cleaning up unclear language until you can clarify its meaning.

2023-01-12 17:36 UTC, kat-enos commented on docs/first-gen/fg-sme/k8s/existing-cluster-kubernetes-on-prem-infrastructure-requirements.md
> +For connections from Harness Manager outbound to an integration, you can use a self-signed certificate. In this case, you must import the self-signed certificate into the delegate's JRE keystore manu
- Agree that "outbound" can be seen as redundant here.
- I like the addition of "by" for readability.
- Re the last, I will drop the "Harness" since that should be well established at this point, and change the link to the actual title of the document, which has been put in sentence caps, and use that as a "For more information." People should know where they're jumping to before they go.

2023-01-12 17:41 UTC, kat-enos commented on docs/first-gen/fg-sme/k8s/kubernetes-cluster-on-prem-add-ingress-controller-service-annotations.md
> +Annotations are done in the KOTS admin tool's Nginx Ingress Controller Service Annotations settings.
Anyway, I'll put in a fix for the construction.

2023-01-12 17:43 UTC, kat-enos commented on docs/first-gen/fg-sme/k8s/kubernetes-cluster-on-prem-add-ingress-controller-service-annotations.md
> +In **Nginx Ingress Controller Service Annotations**, enter your annotations. See [NGINX Ingress Controller Annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annot
Yeah, there are a lot of link references that don't conform to the guidelines.  I'll fix this one.

2023-01-13 06:10 UTC, deepakbolangady commented on docs/first-gen/fg-sme/k8s/existing-cluster-kubernetes-on-prem-infrastructure-requirements.md
> +The outbound access is required for a **connected install only**. If you use [Airgap mode](https://kots.io/kotsadm/installing/airgap-packages/), this is not required.
I think you made the right choice with "air gap" and "air-gapped [environment]". Thanks, Katherine.

2023-01-13 06:14 UTC, deepakbolangady approved these changes
Thanks for putting a lot of thought into this feedback, Katherine. LGTM.

2023-01-13 06:14 UTC, merged