IaCM beta docs
harness/developer-hub pull request #2393
Opened 2023-07-07 20:54 UTC by KimberlyFields

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-07-13 23:57 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +Infrastructure as Code (IaC) is the ability to define cloud resources as code definitions. It allows for repeatable infrastructure configuration. Examples of IaC tools are HashiCorp Terraform and Ama
it's not just cloud resources, it can be any resources that the provider has. I can work with you on a better definition

2023-07-13 23:59 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +Harness Infrastructure as Code Management (IaCM) provides a way to avoid the following common issues:
With should also add "Lack of collaboration - users and small teams face challenges when it comes to collaborating on shared resources and may end up with conflicts when it comes to resource changes

2023-07-14 00:01 UTC, urischeiner commented on docs/infra-as-code-management/iacm-cd-pipeline.md
> +You may want to have a single pipeline that provisions or updates resources used during deployment. To do this, you need to create a pipeline with the following stages:
would it make sense to provide links to the CD documentations?

2023-07-14 00:04 UTC, urischeiner commented on docs/infra-as-code-management/iacm-cd-pipeline.md
> +If you select a pipeline and select the **Apply** step, you will see that all the Terraform outputs are available as output parameters. You can paste the path and use it in any additional stage that
I think ti would make sense to provide a link to the documentation of variables. We are using the standard practice of variables of Harness, so it should be straightforward for Harness users. 
Another thing we should say here is that users can either copy the value of the variable, or the path to the variable itself

2023-07-14 00:05 UTC, urischeiner commented on docs/infra-as-code-management/iacm-cd-pipeline.md
> +Here’s an example of how to pass a variable from an IaCM stage to an another stage:
I would elaborate a little bit more here - we can say something like - if you are interested in using the "bucket_name" as an input, you either copy the current value, or the path to the variables, meaning that the value will be fetched at runtime

2023-07-14 00:11 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Cloud provider
we should provide link to the cloud connectors doc - it's the same thing

2023-07-14 00:12 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +The process of taking the code definition and running it against a cloud provider to create cloud resources. For example, “terraform apply” against a main.tf file.
might make sense to change it a little bit to
The process of taking the infrastructure configuration and applying it against a cloud provider to create cloud resources. For example, “terraform apply” against a main.tf file.

2023-07-14 00:13 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Resource stack
We change the name to be "Workspace"
Here's the doc from Terraform Cloud - should be something similar https://developer.hashicorp.com/terraform/cloud-docs/workspaces

2023-07-14 00:14 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Resource stack template
you can remove it for now as we don't have it yet...

2023-07-14 00:14 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Teardown
We should change it to "Destrory"

2023-07-14 00:17 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Variables
we should explain that there are environment and Terraform variables
here's an example of a doc from a different vendor - https://docs.env0.com/docs/variables#manage-variables

2023-07-14 00:17 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Workflow
we don't have it, so you can remove this bit..

2023-07-14 19:22 UTC, urischeiner commented on docs/infra-as-code-management/use-delegates-with-iacm.md
> +Set up your build infrastructure just as you would for Harness CI. For details, go to [Set up build infrastructure](https://developer.harness.io/docs/category/set-up-build-infrastructure).
we support the following options - cloud (where a delegate is not needed), k8s, and docker

2023-07-14 19:23 UTC, urischeiner commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +A workspace is a named environment that stores Terraform configurations, variables, states, and other resources necessary to manage infrastructure. Each workspace is mapped to a single state.
we can add a link to the term we have on the terminology page

2023-07-14 19:25 UTC, urischeiner commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +Users can assign Terraform configuration with multiple workspaces to enforce the same desired configuration. Each workspace creates a different state from the configuration and independent lifecycle.
I think the example is not very clear.. maybe we can say that we can have a single configuration of k8s cluster, but we can create multiple Workspaces out of it, leading to different clusters

2023-07-14 19:37 UTC, urischeiner commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +4. On the **Workspace** tab, select an existing workspace or select **+ Create New Workspace** to create a new workspace.
we need to replace the image.. it's dated. let me know if you want my help in this

2023-07-14 19:38 UTC, urischeiner commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +5. Select the **Execution** tab, and then add the **IACM Terraform steps** for adding Terraform plugins. Five operations are supported: init/plan/apply/destroy/plan-destroy.
This has changed now- we provide out of the box flows. I can provide newer images if you need

2023-07-14 20:34 UTC, urischeiner commented on docs/infra-as-code-management/workspaces/review-workspace.md
> +    ![Execution history](./static/execution-history.png)
We change the layout of this page so we should update the image

2023-07-14 20:34 UTC, urischeiner requested changes
Hey Kim, some feedback enclosed, happy to work with you on embedding the changes

2023-07-24 19:40 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Variables
The other vendor's doc that you referenced contains details about how to use the variables. This "terms and concepts" section is just a high-level overview for right now. When we have more detailed information about each term, we can link to that section.

2023-07-24 19:49 UTC, KimberlyFields commented on docs/infra-as-code-management/use-delegates-with-iacm.md
> +Once you have both a delegate and Drone runner running, you can modify the **runtime** section of your pipeline to set the **type** to be **Docker** instead of **Cloud**.
Yes

2023-07-24 20:08 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Cloud provider
Done

2023-07-24 20:09 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +Infrastructure as Code (IaC) is the ability to define cloud resources as code definitions. It allows for repeatable infrastructure configuration. Examples of IaC tools are HashiCorp Terraform and Ama
Sure, feel free to make a suggestion.

2023-07-24 20:11 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +Harness Infrastructure as Code Management (IaCM) provides a way to avoid the following common issues:
Done

2023-07-24 20:11 UTC, KimberlyFields commented on docs/infra-as-code-management/iacm-cd-pipeline.md
> +You may want to have a single pipeline that provisions or updates resources used during deployment. To do this, you need to create a pipeline with the following stages:
Added links below.

2023-07-24 20:12 UTC, KimberlyFields commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +A workspace is a named environment that stores Terraform configurations, variables, states, and other resources necessary to manage infrastructure. Each workspace is mapped to a single state.
Not needed because it will only repeat the definition.

2023-07-24 20:12 UTC, KimberlyFields commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +4. On the **Workspace** tab, select an existing workspace or select **+ Create New Workspace** to create a new workspace.
Let's wait until the product is a bit more settled before adding more screenshots to avoid rework.

2023-07-24 20:13 UTC, KimberlyFields commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +5. Select the **Execution** tab, and then add the **IACM Terraform steps** for adding Terraform plugins. Five operations are supported: init/plan/apply/destroy/plan-destroy.
Can you provide details about the new workflow? It looks the same in the environment that I can access.

2023-07-24 20:26 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +The process of taking the code definition and running it against a cloud provider to create cloud resources. For example, “terraform apply” against a main.tf file.
Done

2023-07-24 20:26 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Resource stack
Done

2023-07-24 20:26 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Resource stack template
Done

2023-07-24 20:26 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Teardown
Done

2023-07-24 20:26 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Workflow
Done

2023-07-24 20:27 UTC, KimberlyFields commented on docs/infra-as-code-management/use-delegates-with-iacm.md
> +Set up your build infrastructure just as you would for Harness CI. For details, go to [Set up build infrastructure](https://developer.harness.io/docs/category/set-up-build-infrastructure).
Done

2023-07-24 20:27 UTC, KimberlyFields commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +Users can assign Terraform configuration with multiple workspaces to enforce the same desired configuration. Each workspace creates a different state from the configuration and independent lifecycle.
Done

2023-07-24 21:52 UTC, urischeiner approved these changes
looks good

2023-07-24 21:53 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +Infrastructure as Code (IaC) is the ability to define cloud resources as code definitions. It allows for repeatable infrastructure configuration. Examples of IaC tools are HashiCorp Terraform and Ama
you can remove the word "cloud" and we should be good

2023-07-24 21:54 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +## Variables
ok, we would need a doc that explain the functionality of these variables

2023-07-24 21:56 UTC, urischeiner commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +5. Select the **Execution** tab, and then add the **IACM Terraform steps** for adding Terraform plugins. Five operations are supported: init/plan/apply/destroy/plan-destroy.
If you will create a pipeline with Infra stage here - https://app.harness.io/ng/account/l7HREAyVTnyfUsfUtPZUow/iacm/overview

You will see in the Execution tab that we have out of the box workflow for Terraform - Provision, and Destroy. and we also provide "free canvas"

2023-07-25 19:14 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +Infrastructure as Code (IaC) is the ability to define cloud resources as code definitions. It allows for repeatable infrastructure configuration. Examples of IaC tools are HashiCorp Terraform and Ama
Done

2023-07-25 19:38 UTC, KimberlyFields commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +5. Select the **Execution** tab, and then add the **IACM Terraform steps** for adding Terraform plugins. Five operations are supported: init/plan/apply/destroy/plan-destroy.
Thanks. I updated the steps.

2023-07-25 23:07 UTC, michaelcretzman approved these changes
Approved with suggestions.

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +title: Overview of Infrastructure as Code Management
it would be nice to define IaC and IaCM in the same topic so people know what our IaCM does specifically.

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +    You can also define a trigger to the pipeline to be executed when there is a change in the Terraform configuration.
how?

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +You can use the Harness Visual Editor or YAML to destroy, or tear down, a workspace. To destroy a pipeline, add the “init” , “plan-destroy”,  “destroy” step.
```suggestion
You can use the Harness Visual Editor or YAML to destroy, or tear down, a workspace. To destroy a workspace in your pipeline stage, add the “init” , “plan-destroy”,  and “destroy” steps.
```

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +* Steps required for teardown are init, plan, and destroy, or init, plan-destroy.
```suggestion
* The steps required for teardown are init, plan, and destroy, or init, plan-destroy.
```

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +* The plan-destroy step generates a Terraform plan. This Terraform plan is accessible to all the steps after the IaCM Terraform plan, and is accessible on “<+pipeline.stages.{nameofthestage}.spec.exe
```suggestion
* The plan-destroy step generates a Terraform plan. This Terraform plan is accessible to all the steps after the IaCM Terraform plan, and can be referenced using the expression `<+pipeline.stages.STAGE_ID.spec.execution.steps.STEP_ID.output.outputVariables.parsedPlan>`.
```

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +* The plan-destroy step generates a Terraform plan. This Terraform plan is accessible to all the steps after the IaCM Terraform plan, and is accessible on “<+pipeline.stages.{nameofthestage}.spec.exe
Pretty sure we use step Id and not name since that's how every other expression in Harness works. You might want to confirm this.

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/provision-workspace.md
> +3. Provide the Name and Timeout, and select the command `init`.
```suggestion
3. Provide the name and timeout, and select the command `init`.
```

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/review-workspace.md
> +    * All the resources. Selecting each resource shows you the attributes of the resources.
```suggestion
    * All the resources. Selecting each resource shows you the attributes of that resource. 
```

2023-07-25 23:07 UTC, michaelcretzman commented on docs/infra-as-code-management/workspaces/review-workspace.md
> +    ![Resources](./static/resources-tab.png)
very hard to read the image. consider a lightbox or crop it.

2023-07-26 17:43 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +---
It's the first iteration of beta docs for a product that's still in development. This topic will evolve along with the product.

2023-07-26 17:49 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm.md
> +
Updated to match Google style.

2023-07-27 16:08 UTC, urischeiner commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +A company offering the ability to run cloud resources on your behalf, for example AWS, Azure, GCP, and others.
Can we reorder the terms this way:
- Cloud provider
- Cloud resource
- Workspace - please change the word "stack" to Workspace
- Variables
- Provision
- Destroy
- Drift
- Drift detection
- Harness state tracking
- Terraform state backend

2023-07-27 18:51 UTC, KimberlyFields commented on docs/infra-as-code-management/get-started-with-iacm/iacm-terms-and-concepts.md
> +A company offering the ability to run cloud resources on your behalf, for example AWS, Azure, GCP, and others.
Done

2023-07-27 19:19 UTC, merged