[PL-38164] Add delegate selector details
harness/developer-hub pull request #2395
Opened 2023-07-07 21:20 UTC by brian-f-harness

Add delegate selector details

For reviewers, previews are available:

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-07-10 22:34 UTC, pratmit approved these changes
LGTM

2023-07-11 20:56 UTC, jennyjames21 submitted a review, later dismissed

2023-07-11 21:41 UTC, michaelcretzman submitted a review, later dismissed
aside from the broken partials, the rest of the PR looks fine.
I will approve and you can just fix the partials before merging.

2023-07-11 21:47 UTC, aimurphy requested changes
CI doesn't support step/step group selectors.

2023-07-11 21:47 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
> +Although you must select a specific delegate when you create the Kubernetes Cluster connector, you can choose to use a different delegate for executions and cleanups in individual pipelines, steps, o
Please revert the changes to this file. CI doesn't support step-level selectors - See info box here: https://64adbe6a3e41d140467a9407--harness-developer.netlify.app/docs/platform/Delegates/manage-delegates/select-delegates-with-selectors#step-and-step-group-delegate-selector

2023-07-11 21:47 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
> +This means that if delegate selectors are present at the pipeline, step, or stage levels, then these selections override the delegate selected in the Kubernetes cluster connector's configuration. If
```suggestion
This means that if delegate selectors are present at the pipeline and stage levels, then these selections override the delegate selected in the Kubernetes cluster connector's configuration. If a stage has a stage-level delegate selector, then it uses that delegate. Stages that don't have stage-level delegate selectors use the pipeline-level selector, if present, or the connector's delegate.
```

2023-07-11 21:47 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
> +Delegate selectors override service infrastructure connectors when present at the pipeline, step, or stage levels.
```suggestion
Delegate selectors override service infrastructure connectors when present at the pipeline or stage levels.
```

I don't know what a service infrastructure connector is. Do you mean the delegate in the build infrastructure connector (i.e. k8s cluster connector)? I believe I already described that in the section/example above this, but if not, could you put a link here to more info of what a "service infra connector" is?

2023-07-11 21:47 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
> +Although you must install a delegate to use the local runner build infrastructure, you can choose to use a different delegate for executions and cleanups in individual pipelines, steps, or stages. To
Pls revert - CI doesn't support step-level selectors. See info box here: https://64adbe6a3e41d140467a9407--harness-developer.netlify.app/docs/platform/Delegates/manage-delegates/select-delegates-with-selectors#step-and-step-group-delegate-selector

2023-07-11 21:47 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
> +1. Step
Pls revert.

2023-07-11 21:47 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
> +Delegate selectors do not override service infrastructure connectors. Delegate selectors only determine the delegate that executes the operations of your pipeline.
```suggestion
Delegate selectors do not override service infrastructure connectors. Delegate selectors only determine the delegate that executes the operations of your pipeline.
```

Confused why this statement is different than the one on the K8s build infra page. Also, same comment as on the k8s page - Idk what a "service infrastructure connector" is.

2023-07-11 22:31 UTC, brian-f-harness commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
> +Delegate selectors do not override service infrastructure connectors. Delegate selectors only determine the delegate that executes the operations of your pipeline.
removed

2023-07-11 22:31 UTC, brian-f-harness commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
> +1. Step
reverted

2023-07-11 22:32 UTC, brian-f-harness commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/define-a-docker-build-infrastructure.md
> +Although you must install a delegate to use the local runner build infrastructure, you can choose to use a different delegate for executions and cleanups in individual pipelines, steps, or stages. To
reverted. only left updated cross reference change (broken in prod) - updated to remove option from both xrefs

2023-07-11 22:34 UTC, brian-f-harness commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
> +This means that if delegate selectors are present at the pipeline, step, or stage levels, then these selections override the delegate selected in the Kubernetes cluster connector's configuration. If
reverted

2023-07-11 22:38 UTC, aimurphy approved these changes

2023-07-11 22:41 UTC, brian-f-harness commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/set-up-a-kubernetes-cluster-build-infrastructure.md
> +Although you must select a specific delegate when you create the Kubernetes Cluster connector, you can choose to use a different delegate for executions and cleanups in individual pipelines, steps, o
only update I left in place was to correct the xref (removed "option")

2023-07-11 22:42 UTC, merged