PL Release Notes Dec21
harness/developer-hub pull request #242
Opened 2022-12-21 10:46 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-21 12:58 UTC, deepakbolangady requested changes
I see a number of improvements from earlier release notes! Great work!

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +-   The Create Resource Group API returns an HTTP 500 response code when the included scopes is blank. (PL-30195, ZD-37663)
"scope is blank" or "scopes are blank", depending on which one is accurate.

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +    This is fixed by adding a null check and throwing a null pointer exception when the included scopes is left blank.
"This is fixed by adding" could leave the developer thinking that they need to perform the described action to fix the issue. "This has been fixed by adding" clarifies that they don't have to do anything because the fix is in the past. Let me know if you need to talk about this nuance. Thanks.

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +-   Entering an invalid `tenant_id` does not throw any error and allows selection of previously loaded vaults in Azure Key Vault secret manager. (PL-28136)
"Entering an invalid value for `tenant_id`
Also, some descriptions are in the simple present while others are in the past tense. Can we use the past tense for all, given that that is the tense we've been using all along? Thanks.

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +    Displaying appropriate error message and setting the vault value to empty when there is an error in fetching vaults has fixed this issue.
"an appropriate"

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +-   The date format in pipeline studio is incorrect. (PIE-7040)
Pipeline Studio (use uppercase)

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +    Changing the date format to `DD/MM/YYYY` has fixed this issue.
(optional) what was it earlier? do we need to mention that?

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +    Resetting the input set form with values from formik has fixed this issue.
Formik should probably be in uppercase. Please check. It's a third-party library, right? Just ran a quick Google search and took a glance at the results.

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +-   If the environment details are blank in the deploy stage settings, clicking the Service tab throws an error. (PIE-6240)
Do we know what the message was? Showing that message in the description might help. Users tend to search with text copied from the message they see. Or they associate the description with their issue better when they see the exact message or part thereof. Thanks.

2022-12-21 12:58 UTC, deepakbolangady commented on release-notes/harness-platform-release-notes.md
> +-   You can now get the service provider configuration, schema, and a list of all the supported resource types corresponding to SCIM applications through API. (PL-29069)
Can we have a summary-like opening to this description? For example, "API support for discovery of SCIM service provider features and schema (PL-29069)" (This summary is only a suggestion based on what I saw in the Jira ticket. Reword as you wish.) The current summary can go unchanged into the description. How does this look (dropped repetitive text):

API support for discovery of SCIM service provider features and schema (PL-29069)
Harness now supports the following three HTTP GET API endpoints to facilitate the discovery of SCIM service provider features and schema. These endpoints are defined in SCIM 2.0:
(add list here)

2022-12-21 13:54 UTC, rashminandasahoo commented on release-notes/harness-platform-release-notes.md
> +-   The Create Resource Group API returns an HTTP 500 response code when the included scopes is blank. (PL-30195, ZD-37663)
I already changed this and committed the changes. Not sure why it still says "scopes is blank". Will check.

2022-12-21 14:01 UTC, rashminandasahoo commented on release-notes/harness-platform-release-notes.md
> +    Changing the date format to `DD/MM/YYYY` has fixed this issue.
The date format is DD/MM/YYYY everywhere in Harness. Let us stick to "incorrect" here since it applies only to one case where the date format was not DD/MM/YYYY. Mentioning the wrong date format might confuse customers.

2022-12-21 14:03 UTC, rashminandasahoo commented on release-notes/harness-platform-release-notes.md
> +-   If the environment details are blank in the deploy stage settings, clicking the Service tab throws an error. (PIE-6240)
It used to highlight the Environment field indicating it as a required field.

2022-12-22 09:47 UTC, deepakbolangady submitted a review, later dismissed
Updated the build number before merging.

2022-12-22 10:24 UTC, deepakbolangady approved these changes

2022-12-22 10:29 UTC, merged