CDS-73133-limitation for service overrides on multi env set up
harness/developer-hub pull request #2463
Opened 2023-07-14 10:13 UTC by roshnisarangadharan

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-07-18 16:57 UTC, tchaurasiya requested changes

2023-07-18 16:57 UTC, tchaurasiya commented on docs/continuous-delivery/get-started/services-and-environments-overview.md
> +Runtime inputs are not supported if you are trying to override services in a multi environment set up.
Runtime inputs are not supported in both multi service or multi environment case

2023-07-18 17:08 UTC, roshnisarangadharan commented on docs/continuous-delivery/get-started/services-and-environments-overview.md
> +Runtime inputs are not supported if you are trying to override services in a multi environment set up.
```suggestion
Runtime inputs are not supported if you are trying to override services in a multi service and multi environment set up.
```

2023-07-19 06:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/get-started/services-and-environments-overview.md
> +Runtime inputs are not supported if you are trying to override services in a multi service and multi environment set up.
```suggestion
Runtime inputs are not supported if you are trying to override services in a multi-service and multi-environment set up.
```

2023-07-19 06:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/environments/service-overrides.md
> +* Runtime inputs are not supported if you are trying to override services in a multi service and multi environment set up.
```suggestion
* Runtime inputs are not supported if you are trying to override services in multi-service and multi-environment set ups.
```

2023-07-19 06:47 UTC, tchaurasiya approved these changes

2023-07-19 08:58 UTC, merged