Adding best practices tutorial
harness/developer-hub pull request #2478
Opened 2023-07-14 20:16 UTC by ethangj

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-07-18 13:50 UTC, ravilach commented
@KimberlyFields @ethangj this might not be a tutorial more of a best practices. Better place for this is in the docs?

2023-07-19 18:22 UTC, KimberlyFields commented
@StrawberryPad please work with Ethan on finding the best place for this content.

2023-07-21 22:30 UTC, ethangj commented
@KimberlyFields @ravilach Given that we just lack content right now, would it be possible to get it up there so to pad things out and as we get more content over q3 we can move it later?

2023-07-21 22:56 UTC, ravilach commented
IMO it's not a tutorial but a great best practices guide. @StrawberryPad any guidance to put in FF docs? CC @KimberlyFields

2023-07-24 10:16 UTC, StrawberryPad requested changes

2023-07-24 10:16 UTC, StrawberryPad commented on tutorials/feature-flags/best-practices.md
> +The downside is, with many new features and anyone having access to implement feature flags, you will find that your application code can have feature flags all over the place. In addition to having
```suggestion
The downside is, with many new features and anyone having access to implement feature flags, you will find that your application code can have feature flags all over the place. In addition to having feature flags spread across the code base, the feature flag management system will also grow as each one of these new feature flags is established in the code. In other words, as use of feature flags grows within the organization, these are two places where hygiene needs to be maintained.
```

2023-07-24 10:16 UTC, StrawberryPad commented on tutorials/feature-flags/best-practices.md
> +If you’re looking for a way to implement these best practices and ensure that you have a solution that supports your ability to do so, and maybe even have some baked in, it’s well worth your time to
```suggestion
If you’re looking for a way to implement these best practices and ensure that you have a solution that supports your ability to do so, and even have some best practices baked in, it’s well worth your time to check out Harness Feature Flags. When you’re ready, you’re welcome to sign up for a demo or a free trial! Happy coding.
```

2023-07-24 10:19 UTC, StrawberryPad commented
@ethangj - added suggestions mostly to comply with our heading style, but also some for clarification. I'm happy to put this within tutorials to pad the content. It doesn't really fit into the docs as written, since it's more like a blog. We do have a best practices section in docs, which is appropriately short. I can point from that section to this article/"tutorial" for more info, once we merge this.

2023-07-25 10:50 UTC, merged