New CI Tutorial: Build and Push to AWS ECR
harness/developer-hub pull request #250
Opened 2022-12-22 07:16 UTC by pavanbelagatti

Signed-off-by: Pavan Belagatti <pavan@shippable.com>

## Summary

This new CI tutorial helps the user to build and push container images to AWS ECR.

## What Type of PR is This?

- [x] Tutorial

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## HouseKeeping
Some items to keep track of. Screenshots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally

2022-12-22 09:28 UTC, pavanbelagatti commented
@ravilach - Troy told me to add it. Please take a look

2022-12-22 09:51 UTC, ravilach commented
@pavanbelagatti can you change the sign up UTM to https://app.harness.io/auth/#/signup/?module=ci&?utm_source=website&utm_medium=harness-developer-hub&utm_campaign=ci-plg&utm_content=get-started and create a tile per our Slack?

2022-12-27 04:51 UTC, pavanbelagatti commented
@KimberlyFields can you please take a look

2023-01-06 18:53 UTC, KimberlyFields requested changes
Remember to use the Add suggestion to batch option to enable a single commit of all suggestions.

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +Select AWS from the list and add the required details.
```suggestion
9. Select AWS from the list and add the required details. 
```

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +There are three ways to connect your AWS account. We will use ‘AWS Access Key’ method to authenticate and connect.
```suggestion
10. There are three ways to connect your AWS account. We will use **AWS Access Key** method to authenticate and connect.
```

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +Once you click ‘Save and Continue’, you should see a successful connection message.
```suggestion
After you select **Save and Continue**, you should see a successful connection message.
```

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +It is time we need to add our last step in the CI pipeline, i,e pushing the image to Amazon ECR.
```suggestion
It is time to add our last step in the CI pipeline; pushing the image to Amazon ECR.
```

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +Go back to your pipeline and add a step under the ‘Build and Test’ stage (under execution).
```suggestion
12. Go back to your pipeline and add a step under the **Build and Test** stage (under execution). 
```

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +Select ‘Build and Push to ECR’
```suggestion
13. Select **Build and Push to ECR**.
```

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +Make sure to correctly add the Region, Account ID and Image Name. Add the ‘Tags’ [I have added ‘testing’ as a Tag]. Apply changes and save the pipeline settings.
```suggestion
14. Make sure to correctly add the Region, Account ID, and Image Name. Add the Tags [I have added **testing** as a Tag]. Apply the changes and save the pipeline settings.
```

2023-01-06 18:53 UTC, KimberlyFields commented on tutorials/build-code/ci-build-push-to-ecr.md
> +Save and run the pipeline:)
```suggestion
Save and run the pipeline.
```

2023-01-09 05:09 UTC, pavanbelagatti commented
Done, suggestions successfully applied.  
cc @ravilach & @KimberlyFields

2023-01-09 14:13 UTC, ravilach requested changes
@pavanbelagatti can you un-commit the `yarn.lock` file you have committed please? https://stackoverflow.com/questions/12481639/remove-file-from-latest-commit

2023-01-09 14:14 UTC, ravilach commented
One more item if you don't mind @pavanbelagatti, can you add the tile to the All-Tutorials section please? Thanks!

2023-01-09 18:46 UTC, KimberlyFields approved these changes

2023-01-09 18:47 UTC, KimberlyFields commented
@ravilach my changes were incorporated so I approved the PR. Please merge this PR when your suggested changes are implemented.

2023-01-10 06:20 UTC, pavanbelagatti commented
@ravilach I removed the yarn file and added the tile to the All-Tutorials section.

2023-01-10 14:39 UTC, ravilach approved these changes

2023-01-10 14:43 UTC, merged