Secret and secret manager Tutorial
harness/developer-hub pull request #2510
Opened 2023-07-18 13:35 UTC by harnesspravin

# Harness Developer Pull Request
Secret and secret manager Tutorial

## What Type of PR is This?

New tutorial
- [ ] Tested Locally

2023-07-18 17:30 UTC, harnesspravin commented
I need more work on the secret flow diagram, changing it to a draft.

2023-07-28 18:43 UTC, brian-f-harness reviewed
Looks good. I added minor suggestions for HDH docs standards.

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +-  For the secret value, paste the access token for your AWS user account. The Harness delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```suggestion
-  For the secret value, paste the access token for your AWS user account. The Harness Delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +-  For the secret value, paste the ARN for your AWS user account. The Harness delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```suggestion
-  For the secret value, paste the ARN for your AWS user account. The Harness Delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +**More information [To find the Access key ID and ARN](https://docs.aws.amazon.com/kms/latest/developerguide/find-cmk-id-arn.html)**
```suggestion
For more information, go to [find the Access key ID and ARN](https://docs.aws.amazon.com/kms/latest/developerguide/find-cmk-id-arn.html) in the AWS documentation.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Connectors in Harness enable integration with 3rd party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetchin
```suggestion
Connectors in Harness enable integration with third-party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetching files from a GitHub repository within pipeline stages. For more details, go to [Connectors](https://developer.harness.io/docs/category/connectors).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +- Copy the contents of [aws-kms-connector.yml](https://github.com/harness-community/harnesscd-example-apps/blob/master/harness-platform/secrets/aws-kms-connector.yaml).
```suggestion
- Copy the contents of [aws-kms-connector.yaml] file (https://github.com/harness-community/harnesscd-example-apps/blob/master/harness-platform/secrets/aws-kms-connector.yaml).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +If you are NOT using default organisation and project, make sure to change the `orgIdentifier` and `projectIdentifier` in aws-kms-connector.yaml file.
```suggestion
If you are NOT using the default organization and project, make sure to change the `orgIdentifier` and `projectIdentifier` in the `aws-kms-connector.yaml` file.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Now you use this secret manager in your pipeline.
```suggestion
You can now use this secret manager in your pipeline.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +    - For more information on forking a GitHub repository, go to [GitHub docs](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository).
```suggestion
    - For more information on forking a GitHub repository, go to [forking a repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) in the GitHub documentation.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +3. **Docker**. For this tutorial ensure that you have the Docker runtime installed on your Harness delegate host. If not, use one of the following options to install Docker:
```suggestion
3. **Docker**. For this tutorial, ensure that you have the Docker runtime installed on your Harness Delegate host. If you do not have the Docker runtime, use one of the following installation options:
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +1. Login to Harness.
```suggestion
1. Sign in to Harness.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +## Getting Started with GCP KMS
```suggestion
## Getting started with GCP KMS
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +<summary>What is the Harness delegate?</summary>
```suggestion
<summary>What is the Harness Delegate?</summary>
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +The Harness delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers such as artifacts registries, cloud platforms, etc.
```suggestion
The Harness Delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers, such as artifacts registries, cloud platforms, etc. The delegate is installed in the target infrastructure, for example, a Kubernetes cluster, and performs operations including deployment and integration. Learn more about the delegate in the [Delegate overview](https://developer.harness.io/docs/platform/delegates/delegate-concepts/delegate-overview/).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +**Make sure delegate is installed and its connected. For more details, you can refer [tutorial](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate)**
```suggestion
**Make sure the delegate is installed and it is connected. For more details, go to the [Google Cloud Functions](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate) tutorial.**
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +### GCP - Secret Key
```suggestion
### GCP - Secret key 
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Connectors in Harness enable integration with 3rd party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetchin
```suggestion
Connectors in Harness enable integration with third-party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetching files from a GitHub repository within pipeline stages. For more details, go to [Connectors](https://developer.harness.io/docs/category/connectors).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +You can refer [Obtain Google Cloud Symmertic Key](https://developer.harness.io/docs/platform/Secrets/Secrets-Management/add-google-kms-secrets-manager#obtain-google-cloud-symmetric-key) to get more i
```suggestion
You can refer [Obtain Google Cloud Symmertic Key](https://developer.harness.io/docs/platform/Secrets/Secrets-Management/add-google-kms-secrets-manager#obtain-google-cloud-symmetric-key) to get more information on the above parameters.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +- Select **Save Changes** and verify that the new connector named **gcp-kms-connector** is successfully created.
```suggestion
- Select **Save Changes**, and verify that the new connector named **gcp-kms-connector** is successfully created.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +If you are NOT using default organisation and project, make sure to change the `orgIdentifier` and `projectIdentifier` in gcp-kms-connector.yaml file.
```suggestion
If you are NOT using the default organization and project, make sure to change the `orgIdentifier` and `projectIdentifier` in the `gcp-kms-connector.yaml` file.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Now you use this secret manager in your pipeline.
```suggestion
You can now use this secret manager in your pipeline.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +2. Obtain the **Admin Token** from Hashicorp Public vault URL.
```suggestion
2. Obtain the **Admin Token** from the Hashicorp Public vault URL.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +    - For more information on forking a GitHub repository, go to [GitHub docs](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository).
```suggestion
    - For more information on forking a GitHub repository, go to [forking a repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) in the GitHub documentation.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +4. **Docker**. For this tutorial ensure that you have the Docker runtime installed on your Harness delegate host. If not, use one of the following options to install Docker:
```suggestion
4. **Docker**. For this tutorial, ensure that you have the Docker runtime installed on your Harness Delegate host. If you do not have the Docker runtime, use one of the following installation options:
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +## Getting Started with Hashicorp
```suggestion
## Getting started with Hashicorp
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +1. Login to Harness.
```suggestion
1. Sign in to Harness.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +<summary>What is the Harness delegate?</summary>
```suggestion
<summary>What is the Harness Delegate?</summary>
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +The Harness delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers such as artifacts registries, cloud platforms, etc.
```suggestion
The Harness Delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers, such as artifacts registries, cloud platforms, etc. The delegate is installed in the target infrastructure, for example, a Kubernetes cluster, and performs operations, including deployment and integration. Learn more about the delegate in the [Delegate overview](https://developer.harness.io/docs/platform/delegates/delegate-concepts/delegate-overview/).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +**Make sure delegate is installed and its connected. For more details, you can refer [tutorial](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate)**
```suggestion
**Make sure the delegate is installed and it is connected. For more details, go to the [Google Cloud Functions](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate) tutorial.**
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +-  For the secret value, paste the admin token from Hashicorp Public vault URL. The Harness delegate uses this credential to authenticate Harness with Hashicorp at deployment runtime.
```suggestion
-  For the secret value, paste the admin token from the Hashicorp Public vault URL. The Harness delegate uses this credential to authenticate Harness with Hashicorp at deployment runtime.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Connectors in Harness enable integration with 3rd party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetchin
```suggestion
Connectors in Harness enable integration with third-party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetching files from a GitHub repository within pipeline stages. For more details, go to [Connectors](https://developer.harness.io/docs/category/connectors).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +- Replace `Public Vault URL` with your public vault url from Hashicopr Vault.
```suggestion
- Replace `Public Vault URL` with your public vault URL from Hashicorp Vault.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +If you are NOT using default organisation and project, make sure to change the `orgIdentifier` and `projectIdentifier` in hashicorp_vault_connector.yaml file.
```suggestion
If you are NOT using the default organization and project, make sure to change the `orgIdentifier` and `projectIdentifier` in the `hashicorp_vault_connector.yaml` file.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Now you use this secret manager in your pipeline.
```suggestion
You can now use this secret manager in your pipeline.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +1. Obtain the **AWS - Access Key ID** from AWS
```suggestion
1. The **AWS - Access Key ID** from AWS
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +2. Obtain the **AWS - Secret Key ID** from AWS
```suggestion
2. The **AWS - Secret Key ID** from AWS
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +    - For more information on forking a GitHub repository, go to [GitHub docs](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository).
```suggestion
    - For more information on forking a GitHub repository, go to [forking a repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) in the GitHub documentation.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +4. **Docker**. For this tutorial ensure that you have the Docker runtime installed on your Harness delegate host. If not, use one of the following options to install Docker:
```suggestion
4. **Docker**. For this tutorial, ensure that you have the Docker runtime installed on your Harness Delegate host. If you do not have the Docker runtime, use one of the following installation options:
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +## Getting Started with AWS KMS
```suggestion
## Getting started with AWS KMS
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +1. Login to Harness.
```suggestion
1. Sign in to Harness.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +<summary>What is the Harness delegate?</summary>
```suggestion
<summary>What is the Harness Delegate?</summary>
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +The Harness delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers such as artifacts registries, cloud platforms, etc.
```suggestion
The Harness Delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers, such as artifacts registries, cloud platforms, etc. The delegate is installed in the target infrastructure, for example, a Kubernetes cluster, and performs operations, including deployment and integration. Learn more about the delegate in the [Delegate overview](https://developer.harness.io/docs/platform/delegates/delegate-concepts/delegate-overview/).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +**Make sure delegate is installed and its connected. For more details, you can refer [tutorial](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate)**
```suggestion
**Make sure the delegate is installed and it is connected. For more details, go to the [Google Cloud Functions](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate) tutorial.**
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +### AWS - Access Key ID
```suggestion
### AWS - Access key ID
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +-  For the secret value, paste the access token for your AWS user account. The Harness delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```suggestion
-  For the secret value, paste the access token for your AWS user account. The Harness Delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +### AWS - Secret Key ID
```suggestion
### AWS - Secret key ID
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +-  For the secret value, paste the access token for your AWS user account. The Harness delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```suggestion
-  For the secret value, paste the access token for your AWS user account. The Harness Delegate uses this credential to authenticate Harness with AWS at deployment runtime.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Connectors in Harness enable integration with 3rd party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetchin
```suggestion
Connectors in Harness enable integration with third-party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetching files from a GitHub repository within pipeline stages. For more details, go to [Connectors](https://developer.harness.io/docs/category/connectors).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +If you are NOT using default organisation and project, make sure to change the `orgIdentifier` and `projectIdentifier` in aws-secret-manager-connector.yaml file.
```suggestion
If you are NOT using the default organization and project, make sure to change the `orgIdentifier` and `projectIdentifier` in the `aws-secret-manager-connector.yaml` file.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Now you use this secret manager in your pipeline.
```suggestion
You can now use this secret manager in your pipeline.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +1. Login to Harness.
```suggestion
1. Sign in to Harness.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +    - For more information on forking a GitHub repository, go to [GitHub docs](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository).
```suggestion
    - For more information on forking a GitHub repository, go to [forking a repository](https://docs.github.com/en/get-started/quickstart/fork-a-repo#forking-a-repository) in the GitHub documentation.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +2. **Docker**. For this tutorial ensure that you have the Docker runtime installed on your Harness delegate host. If not, use one of the following options to install Docker:
```suggestion
2. **Docker**. For this tutorial, ensure that you have the Docker runtime installed on your Harness Delegate host. If you do not have the Docker runtime, use one of the following installation options:
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +<summary>What is the Harness delegate?</summary>
```suggestion
<summary>What is the Harness Delegate?</summary>
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +The Harness delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers such as artifacts registries, cloud platforms, etc.
```suggestion
The Harness Delegate is a service that runs in your local network or VPC to establish connections between the Harness Manager and various providers, such as artifacts registries, cloud platforms, etc. The delegate is installed in the target infrastructure, for example, a Kubernetes cluster, and performs operations, including deployment and integration. To learn more about delegates, go to the [Delegate overview](https://developer.harness.io/docs/platform/delegates/delegate-concepts/delegate-overview/).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +**Make sure delegate is installed and its connected. For more details, you can refer [tutorial](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate)**
```suggestion
**Make sure the delegate is installed and it is connected. For more details, go to the [Google Cloud Functions](https://developer.harness.io/tutorials/cd-pipelines/serverless/gcp-cloud-func#delegate) tutorial.**
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +### GCP - Secret Key
```suggestion
### GCP - Secret key 
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Connectors in Harness enable integration with 3rd party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetchin
```suggestion
Connectors in Harness enable integration with third-party tools, providing authentication for operations during pipeline runtime. For instance, a GitHub connector facilitates authentication and fetching files from a GitHub repository within pipeline stages. For more details, go to [Connectors](https://developer.harness.io/docs/category/connectors).
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +If you are NOT using default organisation and project, make sure to change the `orgIdentifier` and `projectIdentifier` in gcp-secret-manager-connector.yaml file.
```suggestion
If you are NOT using the default organization and project, make sure to change the `orgIdentifier` and `projectIdentifier` in the `gcp-secret-manager-connector.yaml` file.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Now you use this secret manager in your pipeline.
```suggestion
You can now use this secret manager in your pipeline.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +Lets create pipeline which will print logs on the console to see how Harness sanitization logs.
```suggestion
Let's create a pipeline that will print logs on the console to see how Harness sanitization logs.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +### Create a New Secret.
```suggestion
### Create a new secret. 
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +-  For the secret value, add string `docsecret`
```suggestion
-  For the secret value, add the string `docsecret`.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +    - Select **Edit YAML** to enable edit mode. Copy the contents of [secret-sanitization.yaml](https://github.com/harness-community/harnesscd-example-apps/blob/master/harness-platform/secrets/secret
```suggestion
    - Select **Edit YAML** to enable edit mode. Copy the contents of [secret-sanitization.yaml](https://github.com/harness-community/harnesscd-example-apps/blob/master/harness-platform/secrets/secret-sanitization.yaml) and paste it.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +    - Select Save to save the pipeline.
```suggestion
    - Select **Save** to save the pipeline.
```

2023-07-28 18:43 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +When a text secret is displayed in a deployment log, Harness substitutes the text secret value with asterisks (*) so that the secret value is never displayed.​ Please go through the [secrets and log-
```suggestion
When a text secret is displayed in a deployment log, Harness substitutes the text secret value with asterisks (*) so that the secret value is never displayed.​ For more information, go to [secrets and log-sanitization](https://developer.harness.io/docs/platform/Secrets/Secrets-Management/secrets-and-log-sanitization). 
```

2023-07-28 18:44 UTC, brian-f-harness reviewed
Looks good. I added minor suggestions for HDH docs standards.

2023-07-30 17:42 UTC, harnesspravin commented
Thanks look good to me. Can we merge this?

2023-07-31 20:19 UTC, aimurphy requested changes
Is the tutorial supposed to be under CD? It seems more like a Platform tutorial. 

It hasn't been added to the landing page: https://64c7bc7d66879f006eaf5761--harness-developer.netlify.app/tutorials/cd-pipelines

I left some comments but there are issues with the architecture, particularly the heading levels.

I think the overall title could be differentiated from the directory title. Perhaps something like "Use secrets managers", since the tutorial is more about setting up different secret managers than explaining what secrets are.

2023-07-31 20:19 UTC, aimurphy commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +In this tutorial, we'll walk you through the process of safely storing and accessing sensitive information like API keys and credentials. You'll learn best practices, gain hands-on experience, and ho
```
You'll learn best practices, gain hands-on experience, and understand how to ensure your secrets remain protected.
```

Missing a word or needs rephrasing. "You'll learn...", "You'll gain", and "You'll how to" doesn't make sense.

2023-07-31 20:19 UTC, aimurphy commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
>  <details open>
I don't think the accordion is necessary for this small amount of information if it is going to be set to default open.

2023-07-31 20:19 UTC, aimurphy commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
>  # Harness secrets management overview
All headings need to be level 2 or lower.

2023-07-31 20:19 UTC, aimurphy commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +## Getting started with AWS KMS
```
Get started with AWS KMS
```

2023-07-31 20:19 UTC, aimurphy commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
>  <details open>
Same comment as before. I think this is too little content to put in an accordion if it's default set to open.

2023-07-31 20:19 UTC, aimurphy commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +## Getting started with Hashicorp
Get started with Hashicorp

I don't know if "get started" is the best title for these. That sounds like we're going to tell them how to use Hashicorp for the first time. Maybe "Use Hashicorp to manage secrets" or something like that would be better?

2023-08-08 05:07 UTC, harnesspravin commented
Brian already modified it as per the comments. are we good to merge?

2023-08-08 13:28 UTC, brian-f-harness commented on tutorials/cd-pipelines/secret-and-secret-managers/secret-secretmanager.md
> +This feature is behind a Feature Flag and is available only to our paid customers.
@harnesspravin Do we have the FF name?

2023-08-08 13:30 UTC, brian-f-harness commented
> Brian already modified it as per the comments. are we good to merge?

@harnesspravin I'm working through some suggested changes from peer review and trying to finalize. 

> Is the tutorial supposed to be under CD? It seems more like a Platform tutorial.
> 
> It hasn't been added to the landing page: https://64c7bc7d66879f006eaf5761--harness-developer.netlify.app/tutorials/cd-pipelines
> 
> I left some comments but there are issues with the architecture, particularly the heading levels.
> 
> I think the overall title could be differentiated from the directory title. Perhaps something like "Use secrets managers", since the tutorial is more about setting up different secret managers than explaining what secrets are.

@harnesspravin I still need to add this to the landing page before we publish.

2023-08-10 05:44 UTC, harnesspravin commented
> > Thanks look good to me. Can we merge this?
> 
> @harnesspravin What is the secrets feature flag name? I'll add it before merging.

We don't need to add the feature flag name in the tutorial. We have to say contact support to enable these features. So that support team can help with this.

2023-08-11 14:31 UTC, aimurphy submitted a review, later dismissed
overall LGTM, just a few comments

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +4. Enter the secret name `SECRET_NAME`.
```suggestion
4. Enter  **Name** for the secret.
```

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +5. For the **Secret Value**, paste the personal access token (PAT) from GitHub with the repo scope. For more information, go to [creating a personal access token](https://help.github.com/en/github/au
```suggestion
5. For the **Secret Value**, enter a GitHub personal access token (PAT) with the repo scope. For more information, go to [creating a personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) in the GitHub documentation. 
```

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +3. In console logs, you can see that the secret is masked with ***** as per below screenshot.
```suggestion
3. In console logs, the secret is masked with asterisks (`*`), as shown in the following image.
```

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +When a text secret is displayed in a deployment log, Harness substitutes the text secret value with asterisks (*) so that the secret value is never displayed.​ For more information, go to [secrets an
```suggestion
When a text secret is displayed in a deployment log, Harness substitutes the text secret value with asterisks (`*`) so that the secret value is never displayed.​ For more information, go to [secrets and log-sanitization](https://developer.harness.io/docs/platform/Secrets/Secrets-Management/secrets-and-log-sanitization).
```

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +When a text secret is displayed in a deployment log, Harness substitutes the text secret value with asterisks (*) so that the secret value is never displayed.​ For more information, go to [secrets an
FYI there is an exception that secrets exported in Output Variables are visible in build logs. https://developer.harness.io/docs/continuous-integration/use-ci/run-ci-scripts/run-step-settings#output-variables

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +## Connectors
```suggestion
### Connectors
```

should this be level 3?

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +---------------------------------------------------
This line is only used on one of the tabs

2023-08-11 14:31 UTC, aimurphy commented on tutorials/platform/secrets-management.md
> +### Use AWS KMS to manage secrets
```suggestion
## Use AWS KMS to manage secrets 
```

should this heading be different? It's the same as on the AWS KMS tab.

2023-08-11 15:07 UTC, merged