DOC-2391: Add FG SMP 12/21/22 v77622 relnotes
harness/developer-hub pull request #255
Opened 2022-12-23 06:28 UTC by kat-enos

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)* 
DOC-2391

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-28 14:52 UTC, deepakbolangady requested changes
Hi, Katherine. I started giving feedback and learned about half the way through that I should focus on the DEL release notes. I should have known earlier. I have added comments to other entries too. If you can incorporate them, great! Otherwise, please look at the DEL ones only. 

The guidelines for enhancements and new features recommend a summary with Jira ticket details and then a description of the benefits. If updated documentation is available, we should include a reference. I understand that a number of tickets here are not DEL, so that might be a challenge. We should look to resolve this, one way or another, before the next SMP release. 

I also noticed that release notes from Oct 31 and earlier have empty table headers. It's not a priority, but I thought I'll add a note here.

2022-12-28 14:52 UTC, deepakbolangady commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5073 | Updated the Core Protocol Buffers library `protobuf-java/protobuf-javalite` to version 3.21.7. This update fixes CVE-2022-3171, a vulnerability affecting some earlier versions. The vulne
Hyphenate "denial of service."

2022-12-28 14:52 UTC, deepakbolangady commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5100, ZD-35558 | Fixed a regression issue that allowed delegate tasks to continue to run when delegates were not able to research external resources. |
"delegates were not able to research external resources." Would that be anthropomorphism? Can we fix this with rewording?

2022-12-28 20:14 UTC, kat-enos commented
Hi Deepak.

Thanks for having a look. I'll have a look at and respond to your comments
later. Because the notes were already published to HelpDocs with PM
approval, because there is always great interest in getting the release
notes out ASAP, and because the SMP notes include notes written by others,
I didn't expect an overall editorial review. Also, some of the items. you
mention, like the format issues in the older notes, are because the tables
broke when others migrated the content. I hoped to get the new notes out
there in the correct format quickly, to push down the older formatting and
other migration issues until I had a chance to clean them up.

The way the SMP notes have been done, since they are voluminous and come
from varying modules, has been to see if any particular summary has already
been written/edited/used in other notes, and to copy that into the SMP
notes. It makes sense that we might want to leave the responsibility for
the note with the writer for the subject area, in part to ensure that the
notes published in different sets of notes match. I hoped we would automate
the generation of the notes to the portal in a useful, searchable
format, and that would allow for a note to be edited one time and placed
automatically and ensure consistency. It would eliminate a lot of the
issues we're having.

Re the last issue, it looks like an auto-correct issue that I'll
definitely fix. "Research" should be "reach." I don't think it would be
anthropomorphic if it were not a typo since machines do search and research
is akin to that.

I'll look at the other comments.

Thanks.
k.

On Wed, Dec 28, 2022 at 6:52 AM Deepak Bolangady ***@***.***>
wrote:

> *EXTERNAL EMAIL* - Use caution when opening attachments, clicking links,
> or responding.
>
> ***@***.**** requested changes on this pull request.
>
> Hi, Katherine. I started giving feedback and learned about half the way
> through that I should focus on the DEL release notes. I should have known
> earlier. I have added comments to other entries too. If you can incorporate
> them, great! Otherwise, please look at the DEL ones only.
>
> The guidelines for enhancements and new features recommend a summary with
> Jira ticket details and then a description of the benefits. If updated
> documentation is available, we should include a reference. I understand
> that a number of tickets here are not DEL, so that might be a challenge. We
> should look to resolve this, one way or another, before the next SMP
> release.
>
> I also noticed that release notes from Oct 31 and earlier have empty table
> headers. It's not a priority, but I thought I'll add a note here.
> ------------------------------
>
> In docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> <https://github.com/harness/developer-hub/pull/255#discussion_r1058091760>
> :
>
> > @@ -12,6 +12,73 @@ This document contains release notes for Harness Self-Managed Enterprise Edition
>
>
>
>  For Harness SaaS release notes, see [Harness SaaS Release Notes](https://docs.harness.io/article/xacpxeyioo-harness-saa-s-release-notes).Release notes are displayed with the most recent release first.
>
>
>
> +### December 21, 2022, version 77622
>
> +
>
> +Delegate: 77621
>
> +
>
> +**Important information about KOTS admin console**
>
>
> Hi, Katherine. "KOTS admin console" needs an article before it because we
> are describing a specific admin console by using "KOTS" as a determiner. I
> spent some time online to determine whether "a" and "c" needed uppercase
> treatment and, by consequence, whether that was the reason we were not
> using an article. Looks like we should use lowercase and that make me think
> we need "the." Thanks.
> ------------------------------
>
> In docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> <https://github.com/harness/developer-hub/pull/255#discussion_r1058098824>
> :
>
> > @@ -12,6 +12,73 @@ This document contains release notes for Harness Self-Managed Enterprise Edition
>
>
>
>  For Harness SaaS release notes, see [Harness SaaS Release Notes](https://docs.harness.io/article/xacpxeyioo-harness-saa-s-release-notes).Release notes are displayed with the most recent release first.
>
>
>
> +### December 21, 2022, version 77622
>
> +
>
> +Delegate: 77621
>
> +
>
> +**Important information about KOTS admin console**
>
>
> Can we replace this title with a Markdown admonition type--one of the
> types described here?
> https://docusaurus.io/docs/markdown-features/admonitions
> <https://docusaurus.io/docs/markdown-features/admonitions>
> Reason: it's good to standardize how we call a user's attention to
> important text.
>
> We can still insert an appropriate title in your choice of admonition
> (note or info), if you feel one is necessary. The article I referenced here
> has the info you need. Thanks.
> ------------------------------
>
> In docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> <https://github.com/harness/developer-hub/pull/255#discussion_r1058136757>
> :
>
> > +**Important information about KOTS admin console**
>
> +
>
> +This release of Harness Self-Managed Enterprise Edition requires KOTS admin console 1.88.0. You must upgrade KOTS before you deploy this Harness release. Use the following commands:
>
> +
>
> +```
>
> +curl https://kots.io/install/1.88.0 <https://kots.io/install/1.88.0> | bash
>
> +kubectl kots admin-console upgrade -n <namespace>
>
> +```
>
> +
>
> +#### New features and enhancements
>
> +
>
> +This release introduces the following features and enhancements.
>
> +
>
> +| **Feature or enhancement** | **Description** |
>
> +| --- | --- |
>
> +| CDS-40179 | Added reconciliation for `looker` entities to ensure data synchronization between mongoDB and timescaleDB. |
>
>
>
>    - If "looker" here refers to Looker, the data analytics platform,
>    should we init-cap the name? Regardless, is there a reason for marking it
>    up as code in Markdown?
>    - Can we reword the description so that it describes how the
>    enhancement benefits the user?
>
> ------------------------------
>
> In docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> <https://github.com/harness/developer-hub/pull/255#discussion_r1058193344>
> :
>
> > +
>
> +This release of Harness Self-Managed Enterprise Edition requires KOTS admin console 1.88.0. You must upgrade KOTS before you deploy this Harness release. Use the following commands:
>
> +
>
> +```
>
> +curl https://kots.io/install/1.88.0 <https://kots.io/install/1.88.0> | bash
>
> +kubectl kots admin-console upgrade -n <namespace>
>
> +```
>
> +
>
> +#### New features and enhancements
>
> +
>
> +This release introduces the following features and enhancements.
>
> +
>
> +| **Feature or enhancement** | **Description** |
>
> +| --- | --- |
>
> +| CDS-40179 | Added reconciliation for `looker` entities to ensure data synchronization between mongoDB and timescaleDB. |
>
> +| CDS-45694 | **Coverage for Stage and Step level deployment details task**. Added unit tests. |
>
>
> The description in Jira is different: "Longer retention for deployment in
> custom dashboards was failing due to a missing null check which has been
> added." Can we check with the engineering team about how this issue impacts
> users and reword accordingly?
> ------------------------------
>
> In docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> <https://github.com/harness/developer-hub/pull/255#discussion_r1058241899>
> :
>
> > +This release of Harness Self-Managed Enterprise Edition requires KOTS admin console 1.88.0. You must upgrade KOTS before you deploy this Harness release. Use the following commands:
>
> +
>
> +```
>
> +curl https://kots.io/install/1.88.0 <https://kots.io/install/1.88.0> | bash
>
> +kubectl kots admin-console upgrade -n <namespace>
>
> +```
>
> +
>
> +#### New features and enhancements
>
> +
>
> +This release introduces the following features and enhancements.
>
> +
>
> +| **Feature or enhance [...]

2022-12-29 01:12 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +**Important information about KOTS admin console**
Typically "the" is not used before product names. "KOTS admin console" is the product name, more or less, and it's often just referred to as "kotsadm."  I've been moving toward just defining it on first reference and standardizing to something consistent in the docs that use it, which is the general editorial standard. More information follows: KOTS just means "Kubernetes-off-the-shelf," so its name is fairly generic. Anyway, I checked their site since typically I defer to them but found they were pretty inconsistent ("kotsadm Admin Console," "the Admin Console," "the admin console," and so on, which sometimes happens with the documentation for open-source products. It's an add-on that is incorporated into others products so it's often referred to by its component name. The Replica reference was more consistent and just called it, generically, "the admin console" or "kotsadm," which is the component itself (https://docs.replicated.com/enterprise/installing-overview).

2022-12-29 01:16 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +**Important information about KOTS admin console**
I'll be going over all the notes and fixing things that did not come forward in the migration as well as incorporating the recommended formatting for things like formerly folded code snippets and notes. It was late in the evening when I was updating the DevHub content and since migration cleanup continues across the board, I was focusing on getting the notes out there to customers.

2022-12-29 01:31 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| CDS-40179 | Added reconciliation for `looker` entities to ensure data synchronization between mongoDB and timescaleDB. |
This CDS issue was written by someone else. I did note the reference to "looker entities" and believe I added the markdown to fix what might read like a mistake to ensure it was clear that it was a reference to code, like the use in this Looker SDK: LookerEmbedSDK.init('looker.example.com', '/auth'). LookerEmbedSDK is a class, and they are title caps. But the reference in text was "looker entity," more like the "looker.example.com" reference on the first parameter there. But since it's a CDS note, I would typically defer to the writer whose subject area includes the term. I just tried to make the existing reference to an "entity" make more sense.

2022-12-29 01:43 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| CDS-45694 | **Coverage for Stage and Step level deployment details task**. Added unit tests. |
Not sure which CDS issue you refer to though when the summary on the Confluence page is not grammatical or informative, I often do some research in the Jira ticket and the PM is always requested to approve publication of the notes as a whole. I typically want to see "null check" changed to something less vague.

2022-12-29 01:53 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| CDS-47016 | Changed how search functionality on the deployments page works. Instead of using regex, search operations now use mongo stemming algorithms. |
Most of the writers are using the sentence fragments that title the tickets to describe the issue. That's where these come from. FYI, before I took a job as a writer, I was a developmental editor at Microsoft on the DDK and SDK so I'm very familiar with applying style guides like MSTP, but I do try to conform to team style. I generally think it's stronger to begin the first sentence with an action verb to describe the change or improvement and then to leave the information about what was broken for a second sentence.

2022-12-29 01:56 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| CDS-47016 | Changed how search functionality on the deployments page works. Instead of using regex, search operations now use mongo stemming algorithms. |
Also FYI, after thinking about it, I concluded that it made the most sentence to maintain relnotes from other modules as they were written by the writer for the subject area. I try to only fix glaring things like grammar, spelling, code style, or incomprehensibility, so that the relnote remains recognizable.

2022-12-29 02:25 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-4888 | Adopted the use of an immutable image for the delegate that is installed by default in newly created accounts. For more information on new delegate features including auto-update, see De
I think "For more information," which is a standard way of writing a reference, is fine since the first sentence says that we "adopted" the use of an immutable image. That means it's recently added or "new." Re a comma before "including," the phrase is restrictive so the comma should not be included. See https://medium.com/@Ediket/when-do-you-use-a-comma-before-including-or-such-as-9b3e1b4f7af3 or a style guide.

2022-12-29 02:27 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5073 | Updated the Core Protocol Buffers library `protobuf-java/protobuf-javalite` to version 3.21.7. This update fixes CVE-2022-3171, a vulnerability affecting some earlier versions. The vulne
Thanks for catching that. I was so intent on clarifying that the CVE was related to DoS that I forgot the hyphenation.

2022-12-29 02:42 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5153 | Changed the base image for the non-legacy delegate to `redhat/ubi8-minimal:latest`. This ensures that each release includes fixes for all operating system-level fixes. |
The first issue is a boondoggle. We're moving away form the term "immutable," and non-legacy delegates are not guaranteed to be immutable. The terminology is confusing and confusing to customers. We've also been changing instances of "immutable delegate" to "delegate" in the docs. I err on the side of caution and when something is described in a release note summary as "non-legacy," I assume there's a reason for it.

For the second, I think you could argue that "each" is preferable to "every" for reasons of concision and because the described condition is true for each *individual* release. But if you can find in MSTP or another technical writing style guide a rule that trumps precision, I'd accept it. I was taught as an editor, that I should be able to cite a source for every change I suggest.

On the third issue, redhat/ubi8-minimal:latest is how our image is referenced in and retrieved from the repository. If I changed the reference, I would be introducing an inaccuracy. The reference is in code font, so can be understood as a code reference.

2022-12-29 03:13 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5308 | Removed the delegate dependency on Java driver component `mongo-java-driver`. This eliminates vulnerability CVE-2021-20328 affecting client-side field level encryption (CSFLE). |
Thanks for the suggestions. You don't need the "the" before "vulnerability" when it comes before the identifier. I added "vulnerability" to try to make the note less opaque for those who don't handle CVEs and didn't want to spell it out as a "Common Vulnerabilities and Exposures (CVE)." I can omit "vulnerability" but then the reader must click the link to find out what a CVE is. 

The delegate terminology isn't up to me. We are standardizing on "Harness Delegate" as the product name or "the delegate"/"delegates" in text for the delegate that will become the one and only. Changing the English language reference for this component can end up making something technically inaccurate. FYI, we're no longer initial-capping "Delegate" in the docs, unless we're making a reference to the "Harness Delegate" product name. Nouns don't always require capitalization and too much capitalization has a negative impact on text readability per usability studies.

2022-12-29 03:24 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5386 | Changed the base image that the non-legacy delegate uses to `redhat/ubi8-minimal:latest`. This ensures that each release includes all OS-level security updates. |
I wouldn't feel comfortable doing that since both tickets were ID'd for relnotes and not together. Putting them together would treat them as though they're the same. I'd have to research the Jira and make sure I had buy-in. But  a good thought. Thanks.

2022-12-29 03:27 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| PL-26799 | Removed feature flag `LDAP_GROUP_SYNC_JOB_ITERATOR`. This makes it possible for all accounts for which LDAP is configured to set up a periodic group sync schedule by using a `cron` expre
Since PL isn't my area, I would have tried to make minimal changes that don't require technical review and help to get the notes out quickly if the note was already written/edited.

2022-12-29 03:39 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +|          | Additionally, LDAP user group sync will not use a quartz job. Instead, the `cron`-based scheduler will use the user-configured `cron` expression. The default value remains set to a 15-mi
Looks like this is for the same PL note so I would have tried to be consistent with the writer while trying to get the SMP notes out as quickly as possible. But I usually look up uses of words like "quartz" if I have questions or put code elements in code font to avoid the appearance of grammar/spelling issues. I would typically change "will not use" to "does not use" or something similar since present tense is preferred in technical writing. I don't object to "is set to" since I think it clarifies that there's a value that might optionally be changed.

2022-12-29 03:41 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| PL-29603 | Upgraded `org.mongodb:mongo-java-driver` to version 3.12.11 to fix vulnerabilities. |
Another PL issue so perhaps something that should be addressed earlier in the food chain. Engineers should cite the CVE or vulnerability name in their summaries, IMO. Writers would need confirmation of the technical information to include.

2022-12-29 03:44 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| CDS-36784 | **NPE when trying to click a version of a linked Shell Script step from Template Library** |
I'm going to revert my notes, which were done in tables to make them more scannable and sortable (this is how they did them for a Cisco team I worked with), to the bulleted form that others continue to use since we won't be able to do much with the notes unless we get better CSS.

2022-12-29 03:46 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +|           | Fixed a bug where the linked template in the pre-deployment step in the canary workflow did not show the correct version |
I agree. I typically would not use "where" in this manner. I also tend to avoid characterizing a problem as a "bug" since it's not terribly useful. But this is probably from a module whose notes I don't write/edit.

2022-12-29 03:47 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5100, ZD-35558 | Fixed a regression issue that allowed delegate tasks to continue to run when delegates were not able to research external resources. |
Typo. Thanks for noting. "Research" should have been "reach," which makes a lot more sense.

2022-12-29 04:10 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +**Important information about KOTS admin console**
I went ahead and decided to go with KOTS Admin Console (kotsadm) for these notes to do the headline some justice.

2022-12-29 04:20 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +**Important information about KOTS admin console**
Re your introduction up top, given the quick turnaround asked for on release notes, as well as the fact that most of them were written/edited upstream, I didn't think we were doing editorial passes over them so wouldn't have thought to tell you that the DEL notes are my area. Sorry about that. I think that all the release notes would go more easily if we moved to the use of a release notes tool--for example, a Jira add-on--which would allow each note to be written one time for all modules. Then they could be built onto pages or into a web portal depending on the filters for the particular release note set. This would be a less error-prone process that would save time and perhaps make it easier for writers to spend more time ensuring the notes were written well enough to be understood by the different audiences who might be looking at them.

2022-12-29 04:23 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +**Important information about KOTS admin console**
Thanks for including the link. I looked it up and inserted the syntax for a note. I have to say though, that I noticed one marked DANGER somewhere in some file and thought that might not be the kind of label we'd want to use. I can't say I've seen it used in other docs I've worked with.

2022-12-29 04:32 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5308 | Removed the delegate dependency on Java driver component `mongo-java-driver`. This eliminates vulnerability CVE-2021-20328 affecting client-side field level encryption (CSFLE). |
I changed the wording slightly to phrasing you might prefer: "This eliminates the CVE-2021-20328 vulnerability that affects...." It's not as terse.

2022-12-29 04:33 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| PL-26799 | Removed feature flag `LDAP_GROUP_SYNC_JOB_ITERATOR`. This makes it possible for all accounts for which LDAP is configured to set up a periodic group sync schedule by using a `cron` expre
Re the use of "Cron" instead of "cron", they can be different things.

2022-12-29 04:34 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| CDS-36784 | **NPE when trying to click a version of a linked Shell Script step from Template Library** |
FYI, I intend to do a separate pass to revert the notes to the bulleted format the other writers are using. I find it better hygiene in case I have to back out any changes.

2022-12-29 04:35 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5073 | Updated the Core Protocol Buffers library `protobuf-java/protobuf-javalite` to version 3.21.7. This update fixes CVE-2022-3171, a vulnerability affecting some earlier versions. The vulne
Fixed.

2022-12-29 20:38 UTC, KimberlyFields requested changes

2022-12-29 20:38 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5153 | Changed the base image for the non-legacy delegate to `redhat/ubi8-minimal:latest`. This ensures that each release includes fixes for all operating system-level fixes. |
This is the incorrect description for[ ](https://harness.atlassian.net/browse/DEL-5153). The Public Release Notes Summary field for DEL-5153 is "Upgrade org.apache.commons:commons-text to 1.10.0 to fix a critical vulnerability in delegate."

2022-12-29 20:55 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-4888 | Adopted the use of an immutable image for the delegate that is installed by default in newly created accounts. For more information on new delegate features including auto-update, see De
Please provide the issue ID you're writing about.

2022-12-29 20:57 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-on-prem-release-notes.md
> +| DEL-5153 | Changed the base image for the non-legacy delegate to `redhat/ubi8-minimal:latest`. This ensures that each release includes fixes for all operating system-level fixes. |
I will doublecheck and see if there is a mismatch.

2022-12-30 01:53 UTC, KimberlyFields approved these changes

2022-12-30 05:31 UTC, merged