New SDK Tutorial for FF
harness/developer-hub pull request #2552
Opened 2023-07-20 14:09 UTC by HarnessTheChaos

We are adding a new SDK tutorial for FF to help a couple customers leverage our new method for refreshing browsers brought to the foreground. I also updated the other tutorials to have some SEO keywords. I need to create another PR to add the tile box for this tutorial and a prior one yet but I can't find where that is located so submitting this to get the content out there so we can use it today.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ x] Tested Locally
- [ x] *Optional* Screen Shoot. 

![image](https://github.com/harness/developer-hub/assets/115592784/c94e3a08-9480-45b5-9afd-160f26a18e42)

2023-07-20 14:19 UTC, HarnessTheChaos commented
@StrawberryPad I'm open to any feedback - thank you for reviewing.

2023-07-20 14:24 UTC, ravilach commented
Reminder if you are able to add the Tutorial Card @HarnessTheChaos on https://developer.harness.io/tutorials/feature-flags. 

* https://harness.atlassian.net/wiki/spaces/PD/pages/21254144997/Harness+HDH+Contributors+Guide+-+Technical+Internal#Adding-Tutorials
* Add Card Here: https://github.com/harness/developer-hub/blob/main/src/components/LandingPage/data/featureFlagsData.tsx

2023-07-24 10:25 UTC, StrawberryPad commented
@HarnessTheChaos - silly question, but who are you :-D

2023-07-24 10:51 UTC, StrawberryPad requested changes

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +# Making Flags Resilient During A Mobile Web Browser Refresh
```suggestion
# Making flags resilient during a mobile web browser refresh
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +## Integrating refreshEvaluations() WebView On Mobile Devices
```suggestion
## Integrating refreshEvaluations() WebView on mobile devices
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +### toForeground() JS Function
```suggestion
### toForeground() JS function
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +### Mobile Web Browsers
```suggestion
### Mobile web browsers
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +The SDK provides a function on the client instance called `refreshEvaluations()`. Calling this allows you to soft poll the servers for the latest evaluations. Note to avoid overloading the backend se
```suggestion
The SDK provides a function on the client instance called `refreshEvaluations()`. Calling this allows you to soft poll the servers for the latest evaluations. To avoid overloading the backend servers, this function will only call out to the network after enough time has elapsed.
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +Once you have a client instance (as shown on the previous page) add a function that can be easily invoked from the device's native language
```suggestion
Once you have a client instance (as shown on the previous page), add a function that can be easily invoked from the device's native language.
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +On iOS add an observer to wait for [willEnterForegroundNotification](https://developer.apple.com/documentation/uikit/uiapplication/1622944-willenterforegroundnotification) on the [WKWebView](https://
```suggestion
On iOS, add an observer to wait for [willEnterForegroundNotification](https://developer.apple.com/documentation/uikit/uiapplication/1622944-willenterforegroundnotification) on the [WKWebView](https://developer.apple.com/documentation/webkit/wkwebview) to call [evaluateJavaScript()](https://developer.apple.com/documentation/webkit/wkwebview/1415017-evaluatejavascript).
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +On Android register an [ActivityLifecycleCallbacks](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks) listener and override [onActivityStarted](https://devel
```suggestion
On Android, register an [ActivityLifecycleCallbacks](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks) listener and override [onActivityStarted](https://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks#onActivityStarted(android.app.Activity)) (API level 29). Then once a foreground event arrives, you can call [evaluateJavascript()](https://developer.android.com/reference/android/webkit/WebView#evaluateJavascript(java.lang.String,%20android.webkit.ValueCallback%3Cjava.lang.String%3E)) on the [WebView](https://developer.android.com/reference/android/webkit/WebView).
```

2023-07-24 10:51 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +When not embedded inside a WebView and using a mobile browser you can detect when the browser app comes to the foreground by listening for the 'visibilitychange' event as described here [Page Lifecyc
```suggestion
When not embedded inside a WebView and using a mobile browser, you can detect when the browser app comes to the foreground by listening for the 'visibilitychange' event as described here [Page Lifecycle API](https://developer.chrome.com/blog/page-lifecycle-api/).
```

2023-07-24 12:25 UTC, ravilach commented
> 

@StrawberryPad that is Matt S e.g @HarnessTheChaos.

@HarnessTheChaos when you go through the comments, can you commit them as a batch? Each commit
in a PR will kick off a build.

![image](https://github.com/harness/developer-hub/assets/42775804/b2100cbb-a53b-4caf-8186-8b55dd9f6ced)

2023-07-24 15:54 UTC, HarnessTheChaos commented on tutorials/feature-flags/mobile-browser-refresh.md
> +Once you have a client instance (as shown on the previous page) add a function that can be easily invoked from the device's native language
Apologies, that can be deleted. What's the best way to delete @StrawberryPad with this process?

2023-07-24 16:03 UTC, HarnessTheChaos commented
> 

I'll submit this and also add another missing tutorial that doesn't have a tile.

2023-07-24 16:33 UTC, StrawberryPad commented on tutorials/feature-flags/mobile-browser-refresh.md
> +Once you have a client instance (as shown on the previous page) add a function that can be easily invoked from the device's native language
Hey @HarnessTheChaos - I'm not sure how a fork works as opposed to a branch in terms of edits. If it were a branch, I would say you could make new commits in your branch (edits, deletions) and push into the PR. Would a fork work the same way?

2023-07-24 17:19 UTC, HarnessTheChaos commented
@StrawberryPad here's the PR for the two tile cards associated with this tutorial and a tutorial from the other week. https://github.com/harness/developer-hub/pull/2608

2023-07-25 09:40 UTC, merged