DOC-2391: Add NG SMP relnotes for 12/23/22
harness/developer-hub pull request #256
Opened 2022-12-23 08:16 UTC by kat-enos

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*
DOC-2391

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-27 20:33 UTC, KimberlyFields requested changes

2022-12-27 20:33 UTC, KimberlyFields commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDS-38870 | Users can copy the fqns for service and environment variables now . The service variables will be by the default name of <+serviceVariables.variableName> and environment by the name of
I don't think putting just the Jira ticket number in the Feature or enhancement column is best for presenting new features and enhancements to customers. The Jira ticket numbers won't mean anything to most customers. I would like to see a brief summary of the new feature or enhancement in the Feature or enhancement column and additional details about the feature in the Description column. 

Please revise the format, and then resubmit the PR for me to review.

2022-12-27 20:33 UTC, KimberlyFields commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDB-415 | Users previously were only able to clone Dashboards either from the "Out Of The Box" Dashboards or from folders where they had an EDIT permission assigned. Now, if the user has any folder
Similar comment as above. Add a brief description of the issue in the Issue column.

2022-12-27 22:22 UTC, kat-enos commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDS-38870 | Users can copy the fqns for service and environment variables now . The service variables will be by the default name of <+serviceVariables.variableName> and environment by the name of
I'm unclear what you're asking for here. If you object to the use of tables, let me know. Some companies prefer the use of tables ordered by ticket no. because it makes issues more scannable. 

As for the descriptions, most of the items that are included in SMP have already been written and I was told to use the rewrites that other writers had in place. That makes sense for the sake of time as well as to ensure that customers aren't confused by different descriptions of the same issue. I tried to use a scannable format that could contribute to sortability without changing the write-ups other writers used.

If you don't like the tables, I will change everything back to bulleted lists to be wholly consistent with others.

2022-12-27 22:23 UTC, kat-enos commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDB-415 | Users previously were only able to clone Dashboards either from the "Out Of The Box" Dashboards or from folders where they had an EDIT permission assigned. Now, if the user has any folder
Same response as above.

Please advise and I will revert to bullets.

2022-12-27 22:57 UTC, kat-enos commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDS-38870 | Users can copy the fqns for service and environment variables now . The service variables will be by the default name of <+serviceVariables.variableName> and environment by the name of
Another approach might be to approve the PR so that the information is available to customers now and consider changes format changes later on.

Please advise.

2022-12-28 00:43 UTC, KimberlyFields commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDS-38870 | Users can copy the fqns for service and environment variables now . The service variables will be by the default name of <+serviceVariables.variableName> and environment by the name of
@kat-enos I'm asking you to update the table so that the "Feature or enhancement" column contains a brief summary of each new feature/enhancement followed by the Jira ticket number, and the description column provides more details. 

For example: 

Feature or enhancement column: 

API support for discovery of SCIM service provider features and schema. (PL-29069)

Description column: 

Harness now supports the following three HTTP GET API endpoints to facilitate the discovery of SCIM service provider features and schema. These endpoints are defined in SCIM 2.0:

- ServiceProviderConfig

- ResourceType

- Schemas

Since these release notes are already past due, you can go ahead and publish them now and then prioritize creating a new PR with an improved table and cleaned up content. Please send the new PR for me to review.

2022-12-28 03:06 UTC, kat-enos commented
To clarify, I completed the preparation of these notes for publication to
DevHub on 12/23, before I shut down my machine for the holiday after
11:00pm at night. They duplicate the notes published on 12/21 to HelpDocs
after their publication was approved by Prateek.

I will revert my document to using the same form that the other writers are
using. SMP incorporates tickets from numerous modules so I'll assume that
those meet with the standards outlined at
https://harness.atlassian.net/wiki/spaces/DOCS/pages/1689845830/Release+notes+process+and+guidelines


On Tue, Dec 27, 2022 at 4:43 PM KimberlyFields ***@***.***>
wrote:

> *EXTERNAL EMAIL* - Use caution when opening attachments, clicking links,
> or responding.
>
> ***@***.**** commented on this pull request.
> ------------------------------
>
> In release-notes/self-managed-enterprise-edition-release-notes.md
> <https://github.com/harness/developer-hub/pull/256#discussion_r1057995253>
> :
>
> > @@ -8,6 +8,143 @@ sidebar_position: 11
>
>  Harness Self-Managed Enterprise Edition is updated regularly. Review the notes below for details about recent changes.
>
> +## December 21, 2022, version 77622
> +
> +### New features and enhancements
> +
> +This release introduces the following features and enhancements.
> +
> +| **Feature or enhancement** | **Description** |
> +| --- | --- |
> +| CDS-38870 | Users can copy the fqns for service and environment variables now . The service variables will be by the default name of <+serviceVariables.variableName> and environment by the name of <env.variables.variableName> |
>
> @kat-enos <https://github.com/kat-enos> I'm asking you to update the
> table so that the "Feature or enhancement" column contains a brief summary
> of each new feature/enhancement followed by the Jira ticket number, and the
> description column provides more details.
>
> For example:
>
> Feature or enhancement column:
>
> API support for discovery of SCIM service provider features and schema.
> (PL-29069)
>
> Description column:
>
> Harness now supports the following three HTTP GET API endpoints to
> facilitate the discovery of SCIM service provider features and schema.
> These endpoints are defined in SCIM 2.0:
>
>    -
>
>    ServiceProviderConfig
>    -
>
>    ResourceType
>    -
>
>    Schemas
>
> Since these release notes are already past due, you can go ahead and
> publish them now and then prioritize creating a new PR with an improved
> table and cleaned up content. Please send the new PR for me to review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/harness/developer-hub/pull/256#discussion_r1057995253>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTVUT2M46RJR65JRY46PVTWPOELBANCNFSM6AAAAAATHQDTCI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>
>

2022-12-28 03:19 UTC, kat-enos commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDS-38870 | Users can copy the fqns for service and environment variables now . The service variables will be by the default name of <+serviceVariables.variableName> and environment by the name of
@KimberlyFields, To clarify, I completed the preparation of these notes for publication to DevHub on 12/23, before I shut down my machine for the holiday after 11:00pm at night. They duplicate the notes published on 12/21 to HelpDocs after their publication was approved by Prateek.

I will revert my document to using the same form that the other writers are using. SMP incorporates tickets from numerous modules so I will assume that those meet with the standards outlined at https://harness.atlassian.net/wiki/spaces/DOCS/pages/1689845830/Release+notes+process+and+guidelines.

2022-12-28 09:00 UTC, ravilach commented
@kat-enos as a heads up, with items that look like HTML e.g `<+serviceVariables.variableName> and environment by the name of <env.variables.variableName>`, Docusouras can think this is an HTML [e.g translate to JSX] tag and complains. Running `yarn build` locally will produce:

```
 release-notes/self-managed-enterprise-edition-release-notes.md: Expected corresponding JSX closing tag for <env.variables.variableName>. (22:257)

  20 | <tr parentName="tbody">

  21 | <td parentName="tr" {...{"align":null}}>{`CDS-38870`}</td>

> 22 | <td parentName="tr" {...{"align":null}}>{`Users can copy the fqns for service and environment variables now . The service variables will be by the default name of <+serviceVariables.variableName> and environment by the name of `}<env.variables.variableName></td>

     |                                                                                                                                                                                                                                                                  ^

  23 | </tr>

  24 | <tr parentName="tbody">

  25 | <td parentName="tr" {...{"align":null}}>{`CDS-39012`}</td>
```

Basically, just wrap or escape those phrases that looks like HTML tags with `code` comments e.g `<+serviceVariables.variableName>` and `<env.variables.variableName>` and any other occurance.

2022-12-28 15:27 UTC, ravilach commented
> @kat-enos as a heads up, with items that look like HTML e.g `<+serviceVariables.variableName> and environment by the name of <env.variables.variableName>`, Docusouras can think this is an HTML [e.g translate to JSX] tag and complains. Running `yarn build` locally will produce:

Also would show up locally in the `yarn start` preview. 

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/42775804/209834510-bab19c75-f40d-4bef-b224-3d8d81b78b45.png">

2022-12-29 06:37 UTC, kat-enos commented
@ravilach Hi Ravi. I've checked the linters and it looks like the PR is making it through now. Let me know if you think otherwise. Thanks.

2022-12-29 14:33 UTC, ravilach commented
@kat-enos looks like there is one more tag that has not been escaped. Running locally `yarn start`

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/42775804/209967368-06704c6a-2e5e-4a45-8987-3b7a48be31a7.png">

```
<artifact.metadata.url>. (198:314)

  196 | <tr parentName="tbody">
  197 | <td parentName="tr" {...{"align":null}}>{`CDS-43863`}</td>
> 198 | <td parentName="tr" {...{"align":null}}><strong parentName="td">{`The `}<inlineCode parentName="strong">{`<artifact.metadata.url>`}</inlineCode>{` is null for the Nexus3 artifact Docker repository format.`}</strong>{` The URL was added to the metadata so it can now be accessed using `}<artifact.metadata.url>{`.`}</td>
```

Located at: 

<img width="718" alt="image" src="https://user-images.githubusercontent.com/42775804/209968028-56d8ad2f-b4a2-47dc-b330-a479fda750c3.png">

Once that is escaped, local build worked for me. 

-Rvi

2022-12-29 19:03 UTC, KimberlyFields commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDB-415 | Users previously were only able to clone Dashboards either from the "Out Of The Box" Dashboards or from folders where they had an EDIT permission assigned. Now, if the user has any folder
For now, merge the PR as is so that customers can have access to the release notes. Then, create a new PR to follow the style of the release notes for the other modules.

2022-12-29 19:04 UTC, KimberlyFields commented on release-notes/self-managed-enterprise-edition-release-notes.md
> +| CDB-415 | Users previously were only able to clone Dashboards either from the "Out Of The Box" Dashboards or from folders where they had an EDIT permission assigned. Now, if the user has any folder
For now, merge the PR as is so that customers can have the release notes. Then, create a new PR to either fix the tables as I requested in my previous comments or replace the tables with bulleted lists.

2022-12-29 19:05 UTC, KimberlyFields approved these changes
Approving this PR to enable customers to have access to the release notes, with the understanding that Katherine will submit a new PR to fix the formatting issues.

2022-12-29 20:08 UTC, kat-enos commented
Merged release notes to get out the latest set to customers. I will continue dealing with post-migration fixes in a separate pass.

2022-12-29 20:08 UTC, merged