Caching with GitEx
harness/developer-hub pull request #259
Opened 2022-12-28 08:57 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-28 09:50 UTC, mohitg0795 commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Entity caching reduces delays in loading your remote entities on the Harness UI. Caching is especially useful when there are multiple-level nestings like pipeline templates, stage templates, and step
Shouldn't we write "multi-level" instead of "multiple-level"?

2022-12-28 09:51 UTC, mohitg0795 commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness maintains a local cache of the remote entities there by improving their load time on the UI similar to the inline entities.
It should be "thereby" instead of "there by". Please CMIIW.

2022-12-28 09:54 UTC, mohitg0795 commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +3.  Harness clears the cache for any entity that hasn't been loaded on the Harness UI in the previous 72 hours. The entity is loaded from Git after cleanup, and Harness updates its cache.
I think we should put it like this:

- Harness clears the cache for any entity that hasn't been referred to or loaded in the last 72 hours. On any subsequent access (be it from API or UI), Harness will fetch from GIT, update the cache and return the response.

2022-12-28 09:57 UTC, mohitg0795 commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +2. Harness indicates an active cache with a green tick if an entity's cache has been updated in the last two hours.
We should clearly mention that whatever cache status we see on UI only refers to cache status of the direct entity being fetched. Nested entities may have different statuses.

eg: If a pipeline has 3 nested templates, then on loading pipeline:
- If its VALID cache, it may be possible that state of nested templates may be VALID or STALE.
- If its STALE cache, it may be possible that state of nested templates may be VALID or STALE.
- The status being shown on UI only represents cache status of the pipeline being loaded.

2022-12-28 18:57 UTC, deepakbolangady requested changes
A few questions popped up around how the caches were organized (per entity?). Giving those details in the intro would help. Thanks for the review request!

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Entity caching reduces delays in loading your remote entities on the Harness UI. Caching is especially useful when there are multiple-level nestings like pipeline templates, stage templates, and step
* "to the Harness UI." (think of loading as an action that moves something from one point _to_ another.)
* Replace "like" with "such as."
* What you might have meant is "multiple levels of nesting." How about "multiple levels of nesting, such as those involving pipeline templates, stage templates, and step templates. Loading such nested entities can be time consuming and involves numerous ..."
* thereby (one word)

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness maintains a local cache of the remote entities there by improving their load time on the UI similar to the inline entities.
This sentence/paragraph doesn't contribute much beyond what the first paragraph did. Can we combine this sentence with the first sentence of the first paragraph, as follows?
The Harness UI maintains a local cache to reduce delays in loading your remote entities. Caching is especially useful ..." 
(Then we won't need this paragraph.)

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness uses cache to save and load the following entities:
"uses a cache" or "uses caching." Better still, "caches." Also, given that a cache is used to save and load content, using "cache" and "save and load" is a little excessive.
"Harness caches the following remote entities:
  - Templates
  - Pipelines"
 Does that read okay?

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +The Git cache is only used to render entities faster on the Harness UI, not to improve pipeline execution. Harness always fetches entities from Git during pipeline executions to avoid using the stale
* Write "in the Harness UI" when you use "render". When you use "load," write "to the Harness UI."
* So far, when we wrote "Harness UI caches," did we mean Git cache? If so, we should say so in the intro. "Harness uses the Git cache ..."
* Maybe begin the last sentence with "For pipeline execution, Harness always fetches entities from Git to ..." (Or, "When executing a pipeline, Harness always ..."

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +You can reload the entities from Git and update cache any time.
* "update the cache"
* "at any time"
Also, are those two actions distinct? Or would it suffice to write "You can update the cache at any time"?

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +## Entity cache lifecycle
Global: "life cycle" (two words)

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness UI uses the following cache lifecycle to render any remote entity:
replace "any" with "a"?

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +1. The first time you load a remote entity on Harness, it fetches it from Git, renders it on the UI, and updates the cache. Harness loads this entity from the cache after this.
* Referring to "it fetches it from Git," what fetches what from Git? There are two possible subjects here: the remote entity and Harness. While it's not plausible that the entity is the "it" that you refer to, we must leave no room for ambiguity. How about "The first time you load a remote entity to the Harness UI, the Harness UI fetches the entity from Git, renders it in the UI, and then updates the cache." (note also the prepositions I've changed.)
* Overuse of "this". To work around having to write "this" multiple times, consider "Subsequently, the Harness UI loads the entity from the cache."

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +2. Harness indicates an active cache with a green tick if an entity's cache has been updated in the last two hours.
This paragraph is confusing. A cache usually consists of multiple cached items, and those items could have a status of their own (active, expired, etc.). When you say "active cache", do we mean the cache itself has a status here? And when you write "entity's cache," I would ask if there is a cache per entity. Do we mean "Harness uses a green tick mark against an entity in the UI to indicate that the entity was updated in the last two hours and is therefore active in the cache?" (something like that?) Happy to discuss this comment. If you don't have an opportunity to talk before you have to publish this documentation, go ahead and publish. We can discuss later. Thanks.

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +   When any entity's cache was last updated more than 2 hours ago, Harness displays an orange tick against it indicating a stale cache.
"to indicate"

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +3.  Harness clears the cache for any entity that hasn't been loaded on the Harness UI in the previous 72 hours. The entity is loaded from Git after cleanup, and Harness updates its cache.
Who initiates the cleanup? Manual? Automatic?

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +2. Harness indicates an active cache with a green tick if an entity's cache has been updated in the last two hours.
Reading ahead, I see that there is one cache per entity (for example, pipeline). Can we state that ahead of time so the questions I had in my comment don't pop up in our users' minds?

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +To ensure isolation between caches for different pipelines for different branches, cache for each entity is maintained separately for each branch.
"the cache for each"

2022-12-28 18:57 UTC, deepakbolangady commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +- Discard your changes done on the UI and reload the configurations from Git.
"in the UI"

2022-12-29 05:37 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +description: This topic explains entity caching with Git experience.
There is explicit mention of "Harness UI" to rule out any confusion that caching also improves the pipeline execution.

2022-12-29 05:41 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Entity caching reduces delays in loading your remote entities on the Harness UI. Caching is especially useful when there are multiple-level nestings like pipeline templates, stage templates, and step
Done

2022-12-29 05:43 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness maintains a local cache of the remote entities there by improving their load time on the UI similar to the inline entities.
Done.

2022-12-29 05:44 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness uses cache to save and load the following entities:
Done

2022-12-29 05:46 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +The Git cache is only used to render entities faster on the Harness UI, not to improve pipeline execution. Harness always fetches entities from Git during pipeline executions to avoid using the stale
Done.
For the 2nd point, we did not mean Git cache.

2022-12-29 05:47 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +2. Harness indicates an active cache with a green tick if an entity's cache has been updated in the last two hours.
Let's discuss this.

2022-12-29 05:48 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +   When any entity's cache was last updated more than 2 hours ago, Harness displays an orange tick against it indicating a stale cache.
Done

2022-12-29 05:49 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +To ensure isolation between caches for different pipelines for different branches, cache for each entity is maintained separately for each branch.
Done

2022-12-29 05:50 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Entity caching reduces delays in loading your remote entities on the Harness UI. Caching is especially useful when there are multiple-level nestings like pipeline templates, stage templates, and step
We should write "multiple-level".

2022-12-29 05:50 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness maintains a local cache of the remote entities there by improving their load time on the UI similar to the inline entities.
Done

2022-12-29 05:55 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +3.  Harness clears the cache for any entity that hasn't been loaded on the Harness UI in the previous 72 hours. The entity is loaded from Git after cleanup, and Harness updates its cache.
Harness clears the cache for any entity that hasn't been referred to or loaded on the Harness UI in the previous 72 hours. Any subsequent access (whether through API or UI) will fetch the entity from GIT, update the cache, and return the response.

2022-12-29 05:56 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +You can reload the entities from Git and update cache any time.
These are 2 things happening in parallel.

2022-12-29 05:56 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +## Entity cache lifecycle
Done

2022-12-29 05:57 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +Harness UI uses the following cache lifecycle to render any remote entity:
Done

2022-12-29 05:59 UTC, rashminandasahoo commented on docs/platform/10_Git-Experience/harness-git-cache.md
> +1. The first time you load a remote entity on Harness, it fetches it from Git, renders it on the UI, and updates the cache. Harness loads this entity from the cache after this.
Done

2022-12-29 06:29 UTC, merged