scim-jwt-token-auth
harness/developer-hub pull request #260
Opened 2022-12-29 12:30 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-03 07:26 UTC, pbarapatre10 commented on docs/platform/16_APIs/jwt-token-auth.md
> +- Make sure you have the **Manage** permission for users and user groups.
'managge' & 'view' permissions as well.

2023-01-03 07:27 UTC, pbarapatre10 approved these changes

2023-01-03 17:24 UTC, deepakbolangady requested changes
I have a few questions. Please get back to me with any questions you might have. I'm always happy to discuss my comments on a call and hear your thoughts. Let me know. Thanks.

2023-01-03 17:24 UTC, deepakbolangady commented on docs/platform/16_APIs/jwt-token-auth.md
> +   Harness checks the following to complete the authentication:
The first condition says that Harness validates the authenticity of the JWT token. The second item begins with "validate the token." Is the validation of the authenticity of the JWT token different from the validation of the token itself? Or should the second condition be only about matching claims?
Also, both the conditions have to do with validation. Can we modify the lead-in sentence as follows?

====
Harness validates the following to complete the authentication:
- Authenticity of the issued JWT token. For this validation, Harness uses the public JWT Keys URL.
- Claims in the JWT token. Harness matches the claims in the token to those defined in the account settings.

====
I would also like us to take a look at the term "public JWT Keys URL." That much capitalization made look for the term online. I found no results when I used quotation marks in my Google search, for both "public JWT Keys URL" and "JWT Keys URL." I found "JWT Keys" in some results, but the context was probably different. Thanks.

2023-01-03 17:24 UTC, deepakbolangady commented on docs/platform/16_APIs/jwt-token-auth.md
> +2. Use the following curl command to fetch all the users using a JWT token:
"all the users using a JWT token" > it is highly likely that we mean "all the users by using a JWT token." The former means that the users use a token, and we need find those that do. The latter means that we must use a token to find users. If the written instruction is accurate, please ignore my comment, but I needed to be sure. Thanks.

2023-01-04 04:46 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +title: Use the Harness SCIM APIs through JWT Token
How about "Use JWT token for Harness SCIM API authentication"?

2023-01-04 04:54 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +Currently, this feature is behind the feature flags `NG_SETTINGS` and `PL_SUPPORT_JWT_TOKEN_SCIM_API`. Contact Harness Support to enable the feature.
I see most of the other topics written by other writers have the same template for notifying about a feature flag. 
It would be better to do this change globally to maintain consistency. Incorporating it just for this topic will create inconsistencies. Please let me know if I should still change it.

2023-01-04 04:59 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +Harness SCIM APIs are accessible via JWT token. You can use your email addresses other than the ones you have registered in Harness, for identity provider authentication. After successful authenticat
Done

2023-01-04 05:12 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +To be able to do this, you must enable the **SCIM JWT Token** in default settings through the Settings API.
To do this, you must enable the **SCIM JWT Token** through the [Setting API](https://apidocs.harness.io/tag/Setting).

2023-01-04 05:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +    - `keyField`: this is the distinguished field to match the JWT claims map.
Done

2023-01-04 05:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +    - `valueField`: this is the value that matches to the above keyField.
Updated to "Value corresponding to the keyField."

2023-01-04 05:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +    - `ServiceAccountId`: the identifier string of a service account which is assigned to roles in Harness.
Done

2023-01-04 05:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +  For more information, see Use Settings API.
Done

2023-01-04 05:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +## Invoke SCIM API through JWT token
Done

2023-01-04 05:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +1. Enter your JWT Token in the Bearer header.
Done

2023-01-04 05:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +2. Use the following curl command to fetch all the users using a JWT token:
Done

2023-01-04 08:48 UTC, deepakbolangady commented on docs/platform/16_APIs/jwt-token-auth.md
> +title: Use the Harness SCIM APIs through JWT Token
> How about "Use JWT token for Harness SCIM API authentication"?

Insert "a" before "JWT." Otherwise OK. Thanks.

2023-01-04 08:50 UTC, deepakbolangady commented on docs/platform/16_APIs/jwt-token-auth.md
> +Currently, this feature is behind the feature flags `NG_SETTINGS` and `PL_SUPPORT_JWT_TOKEN_SCIM_API`. Contact Harness Support to enable the feature.
OK.

2023-01-04 08:55 UTC, deepakbolangady commented on docs/platform/16_APIs/jwt-token-auth.md
> +To be able to do this, you must enable the **SCIM JWT Token** in default settings through the Settings API.
> To do this, you must enable the **SCIM JWT Token** through the [Setting API](https://apidocs.harness.io/tag/Setting).

LGTM, and thanks for changing "Settings" to "Setting." (Since you've used "the" before the name of the setting, please insert something after the name of the setting. For example, "To do this, you must enable the **SCIM JWT Token** setting through the [Setting API](https://apidocs.harness.io/tag/Setting).

2023-01-04 09:00 UTC, deepakbolangady commented on docs/platform/16_APIs/jwt-token-auth.md
> +Once you have configured the default settings, SCIM updates pick up the new settings after 120 secs.
We don't nee both "after" and "later." Maybe we can use the general statement I added at the end of my comment?

2023-01-04 09:11 UTC, deepakbolangady requested changes

2023-01-04 09:11 UTC, deepakbolangady commented on docs/platform/16_APIs/jwt-token-auth.md
> +   Harness checks the following to complete the authentication:
"JWT keys URL" should be OK, although I don't see it used anywhere. However, "keys URL" (lowercase) is used, and prefixing "JWT" to it should do no harm. It's the all-uppercase that caught my attention.

2023-01-04 10:13 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +title: Use the Harness SCIM APIs through JWT Token
Done

2023-01-04 10:16 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +To be able to do this, you must enable the **SCIM JWT Token** in default settings through the Settings API.
Done

2023-01-04 10:17 UTC, rashminandasahoo commented on docs/platform/16_APIs/jwt-token-auth.md
> +Once you have configured the default settings, SCIM updates pick up the new settings after 120 secs.
Done

2023-01-04 11:55 UTC, deepakbolangady approved these changes

2023-01-04 11:55 UTC, merged