[SMP-1656] SMP external Redis 0.8.0
harness/developer-hub pull request #2612
Opened 2023-07-24 19:47 UTC by brian-f-harness

SMP external Redis 0.8.0

For reviewers, a preview is available:

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-07-25 01:41 UTC, kapilgarg1996 commented on docs/self-managed-enterprise-edition/advanced-configurations/use-an-external-redis-database.md
> +## Software requirements
```suggestion
- 1GB/s minimum network bandwidth

## Software requirements
```

2023-07-25 01:41 UTC, kapilgarg1996 commented on docs/self-managed-enterprise-edition/advanced-configurations/use-an-external-redis-database.md
> +
```suggestion
- Supported OS (Ubuntu 20.04 LTS)
- [Redis enterprise download URL](https://redis.com/redis-enterprise-software/download-center/software/)

```

2023-07-25 01:41 UTC, kapilgarg1996 commented on docs/self-managed-enterprise-edition/advanced-configurations/use-an-external-redis-database.md
> +
```suggestion
   4. Add the DNS record subdomain in the **FQDN** field which we used in NS record, for example `redis.harness-redis.com`.

```

2023-07-25 01:41 UTC, kapilgarg1996 commented on docs/self-managed-enterprise-edition/advanced-configurations/use-an-external-redis-database.md
> +     :::
```suggestion
     :::info
     You can skip the cluster key if the page opens for now. (you can procure a license key independently from redislabs)
     :::
```

2023-07-25 01:41 UTC, kapilgarg1996 commented on docs/self-managed-enterprise-edition/advanced-configurations/use-an-external-redis-database.md
> +   ```
```suggestion
1. Run the following command.

   ```shell
   redis-cli -h <YOUR_INTERNAL_ENDPOINT> -p <port>
   ```
2. Run the following.
  
   ```shell
   ping
   ```

  The expected response is `pong`.

3. Run the following.
   
   ```shell
   set foo bar
   ```

4. Run the following.

   ```shell
   get foo
   ```
```

2023-07-25 01:41 UTC, kapilgarg1996 commented on docs/self-managed-enterprise-edition/advanced-configurations/use-an-external-redis-database.md
> +   ```
```suggestion
To configure your Harness environment and Helm chart, do the following:

1. Add the following override entries to your newly-installed Harness Redis instance.

   ```yaml
   global:
     database:
       redis:
         installed: false
         hosts:
         - <YOUR_INTERNAL_ENDPOINT_AND_PORT>
         secretName: ""
         userKey: ""
         passwordKey: ""
   ```
```

2023-07-28 17:38 UTC, pratmit submitted a review, later dismissed
LGTM, based on the technical details provided

2023-07-31 14:23 UTC, kapilgarg1996 commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +After you configure your firewall rules, you must install Redis. To install Redis, you must create three VMs, create a public zone, configure your Redis cluster, configure your Redis database, and te
```suggestion
After you configure your firewall rules, you must install Redis. To install Redis, you must create three VMs, create DNS records, configure your Redis cluster, configure your Redis database, and test your connectivity.
```

2023-07-31 14:23 UTC, kapilgarg1996 commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +
```suggestion
- Redis Enterprise. To download Redis for Ubuntu 20.04, go to [Redis enterprise](https://redis.com/redis-enterprise-software/download-center/software/).

- Public or Internal domain name. eg harness-redis-abc.com
```

2023-07-31 14:23 UTC, kapilgarg1996 commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +To create a public zone, do the following:
```suggestion
To create DNS records, do the following:
```

2023-07-31 14:23 UTC, kapilgarg1996 commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +
```suggestion
1. Go to the DNS portal of your domain registrar.

2. Create three type A records with subdomains for the public domain name, for example, `node1.harness-redis-abc.com`, `node2.harness-redis-abc.com`, and `node3.harness-redis-abc.com`.

3. Add the internal IP and external IP for each VM in their respective A records.

4. Create one NS record with a different subdomain, for example `redis.harness-redis.com`.

5. Add the subdomains of all your nodes, for example `node1.harness-redis.com`, `node2.harness-redis.com`, and `node3.harness-redis.com`.

```

2023-07-31 20:40 UTC, aimurphy requested changes

2023-07-31 20:40 UTC, aimurphy commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +3. Open https://<EXTERNAL_IP_OF_NODE2>:8443 in your browser, and then complete the following on the node setup page.
```suggestion
3. Open `https://<EXTERNAL_IP_OF_NODE2>:8443` in your browser, and then complete the following on the node setup page. 
```

2023-07-31 20:40 UTC, aimurphy commented on src/components/LandingPage/data/smpData.tsx
> +    newDoc: false,
```suggestion
    newDoc: true,
```

2023-07-31 20:40 UTC, aimurphy commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +sidebar_label: Configure an external self-managed Redis database
```suggestion
sidebar_label: External self-managed Redis
```

2023-07-31 20:40 UTC, aimurphy commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +3. Open https://<EXTERNAL_IP_OF_NODE3>:8443 in your browser, and then complete the following on the node setup page.
```suggestion
3. Open `https://<EXTERNAL_IP_OF_NODE3>:8443` in your browser, and then complete the following on the node setup page. 
```

2023-07-31 20:40 UTC, aimurphy commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +1. Open https://<YOUR_NODE1_EXTERNAL_IP>:8443 in your browser.
```suggestion
1. Open `https://<YOUR_NODE1_EXTERNAL_IP>:8443` in your browser.
```

2023-07-31 20:40 UTC, aimurphy commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +         passwordKey: ""
It looks like the closing is missing for this code block.

Also I would just double-check the spacing and code blocks in the whole tutorial. On GH, it looks like something is up with the format but I don't see any issue on the preview.

2023-07-31 20:40 UTC, aimurphy commented on tutorials/self-managed-enterprise-edition/use-an-external-redis-database.md
> +1. Open https://<YOUR_NODE1_EXTERNAL_IP>:8443 in your browser.
One of these sections is duplicated.

2023-07-31 20:57 UTC, aimurphy approved these changes
approved just one suggestion to change the time

2023-07-31 20:57 UTC, aimurphy commented on src/components/LandingPage/data/smpData.tsx
> +    time: "5 min",
```suggestion
    time: "15 min",
```

2023-07-31 21:23 UTC, merged