updates for doc-2335
harness/developer-hub pull request #262
Opened 2022-12-29 18:28 UTC by SudheendraKatte

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

Updates for the issue DOC-2335.

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2022-12-29 18:55 UTC, KimberlyFields requested changes
I noticed that the yarn.lock file is included in this PR. I'm not sure if you intended for that to be included.

2022-12-29 18:55 UTC, KimberlyFields commented on docs/continuous-delivery/cd-execution/cv-category/verify-deployment-with-prometheus.md
> +Harness automatically creates a Monitored Service using a concatenation of the Service and Environment names. For example, a Service named `todolist` and an Environment named `dev` will result in a m
```suggestion
Harness automatically creates a monitored service using a concatenation of the service and environment names. For example, a service named `todolist` and an environment named `dev` results in a monitored service with the name `todolist_dev`.
```

2022-12-29 18:55 UTC, KimberlyFields commented on docs/continuous-delivery/cd-execution/cv-category/verify-deployment-with-prometheus.md
> +The option to auto-create a monitored service is not available if you have configured either service or environment or both as runtime values. When you run the pipeline, Harness concatenates the serv
```suggestion
The option to auto-create a monitored service is not available if you have configured a service, an environment, or both as runtime values. When you run the pipeline, Harness concatenates the service and environment values you enter in the runtime inputs screen and generates a monitored service name. If an existing monitored service with the same name exists, Harness assigns it to the pipeline. If no monitored service that matches the generated monitored service name exists, Harness skips the verification step. 
```

2022-12-29 18:55 UTC, KimberlyFields commented on docs/continuous-delivery/cd-execution/cv-category/verify-deployment-with-prometheus.md
> +For example, suppose you enter service as `todolist` and environment as `dev`. In that case, Harness generates the monitored service name `todolist_dev`, checks whether a monitored service with the n
```suggestion
For example, suppose you enter the service as `todolist` and the environment as `dev`. In that case, Harness generates the monitored service name `todolist_dev`, checks whether a monitored service with the name `todolist_dev` is available, and assigns it to the pipeline. If no monitored service is available with the name `todolist_dev`, Harness skips the verification step.
```

2022-12-29 18:55 UTC, KimberlyFields commented on docs/continuous-delivery/cd-execution/cv-category/verify-deployments-with-app-dynamics.md
> +Harness automatically creates a Monitored Service using a concatenation of the Service and Environment names. For example, a Service named `todolist` and an Environment named `dev` will result in a m
It looks like the same content is repeated in each file. Apply the same suggestions I added to the previous file to all of the files.

2022-12-30 11:23 UTC, closed without merging

2022-12-30 11:24 UTC, SudheendraKatte commented
Created a new branch jira-doc-2335 to address the merge conflict in this PR.