[DOC-3497] WIP Delegate 801xx release notes
harness/developer-hub pull request #2703
Opened 2023-07-28 16:22 UTC by brian-f-harness

Delegate 801xx release notes

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-08-02 21:44 UTC, pratmit approved these changes
LGTM

2023-08-03 15:08 UTC, SudheendraKatte approved these changes
Approved with a minor suggestion.

2023-08-04 13:24 UTC, deepakbolangady requested changes

2023-08-04 13:27 UTC, deepakbolangady approved these changes

2023-08-04 13:44 UTC, merged