CHAOS-2192: Add docs to provide the steps for creating secrets in GCP
harness/developer-hub pull request #2739
Opened 2023-08-01 11:38 UTC by uditgaurav

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-08-01 13:53 UTC, StrawberryPad requested changes
Just need some context and clarification at the top 2/3 lines. See review comments.

2023-08-01 13:53 UTC, StrawberryPad commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +
We should state here in once sentence the purpose of this secret.

2023-08-01 13:53 UTC, StrawberryPad commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +**Derive SA from GCP**
What is SA?

2023-08-02 11:43 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +    private_key: "<private-key>"
```suggestion
    private_key: <private-key>
```
Private key contains `\n` characters which need to be preserved. If we use double quotes then they will be lost.

2023-08-02 11:43 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +1. Create a new service account. Replace &lt;service-account-name&gt; with the name you want to give to the service account:
```suggestion
2. Create a new service account. Replace &lt;service-account-name&gt; with the name you want to give to the service account:
```

2023-08-02 11:43 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +1. After the service account is created, you can generate a new JSON key file. Replace &lt;service-account-name&gt; with the name of your service account and &lt;key-file&gt; with the path where you
```suggestion
3. After the service account is created, you can generate a new JSON key file. Replace &lt;service-account-name&gt; with the name of your service account and &lt;key-file&gt; with the path where you want to save the key file:
```

2023-08-02 11:43 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +    private_key: "<private-key>"
We can emphasize this in the doc so that users don't do this mistake.

2023-08-02 11:43 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +1. Prepare the secret YAML based on this JSON:
```suggestion
4. Prepare the secret YAML based on this JSON:
```

2023-08-02 11:43 UTC, neelanjan00 commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +1. Create the secret YAML file in the chaos infra namespace using the command:
```suggestion
5. Create the secret YAML file in the chaos infra namespace using the command:
```

2023-08-02 12:25 UTC, neelanjan00 approved these changes

2023-08-02 12:26 UTC, uditgaurav commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +    private_key: "<private-key>"
Sure

2023-08-02 12:56 UTC, StrawberryPad commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +1. Create a new service account. Replace &lt;service-account-name&gt; with the name you want to give to the service account:
@neelanjan00 @uditgaurav - FYI, you don't need to manually number steps in markdown. You can begin all of them with "1. " and they will automatically number themselves (as long as you don't have more than one line between steps). This helps to keep steps correct if you re-arrange or delete steps.

2023-08-02 14:09 UTC, uditgaurav commented on docs/chaos-engineering/technical-reference/chaos-faults/gcp/security-configurations/prepare-secret-for-gcp.md
> +1. Create a new service account. Replace &lt;service-account-name&gt; with the name you want to give to the service account:
Didn't knew about that. Thanks!

2023-08-04 13:33 UTC, merged