feat: [CDS-73703]: Add ESO OCI Helm repository docs.
harness/developer-hub pull request #2748
Opened 2023-08-01 18:53 UTC by mteodor

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-08-02 14:51 UTC, manavjot-harness submitted a review, later dismissed

2023-08-02 15:12 UTC, meenaravichandran1 submitted a review, later dismissed

2023-08-03 17:54 UTC, deepakbolangady requested changes
Hi, Mirko. I've added feedback. Please let me know if you have any questions. Thank you.

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +      - for AWS you must put `AWS`, and for Google you put `oauth2accesstoken` for username.
```suggestion
      - In the user name field, if you are authenticating to AWS, enter `AWS`. If you are authenticating to Google, enter `oauth2accesstoken`.
```
Is "username" the name of the field. Typically, we would begin the instruction with "In **User name**, enter the ..." Since I cannot see the UI now, I cannot tell whether the name of the field is "User name" or "Username" or something else. Please check and change my generic "In the user name field" to the typical wording I described above.

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +      - for password you put your shortlived token. If you have [External Secrets Operator](https://docs.harness.io/article/3xqjzq2q2q-external-secrets-operator) **Refresh token** checkbox will appea
```suggestion
      - In **Password** enter your short-lived token. If you have an [External Secrets Operator](https://docs.harness.io/article/3xqjzq2q2q-external-secrets-operator), a **Refresh token** checkbox appears. Enable the checkbox.
```
Same as my previous comment, but I cannot think a password field would ever be called anything else. If I'm wrong, please check and correct.

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +    - If you checked  **Refresh Token**, fill in  **Refresh Interval** (e.g. 1m, 1h, 12h, 1d). This is the interval at which the token will be refreshed.
```suggestion
    - If you checked  **Refresh Token**, specify a  **Refresh Interval** (for example, 1m, 1h, 12h, or 1d). This is the interval with which you want the token to be refreshed.
```

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +          - If you select **Google Service Account**, you must upload the service [account key file](https://cloud.google.com/iam/docs/keys-create-delete). Paste the contents of file in the **Account
```suggestion
          - If you select **Google Service Account**, you must upload the service [account key file](https://cloud.google.com/iam/docs/keys-create-delete). Paste the contents of the file in the **Account Key** field. Contents of the file must be on a single line. For example:
```

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +          - If you select **Google Workload Identity**, you must enter the GCP Workload parameters. [Google Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
```suggestion
          - If you select **Google Workload Identity**, you must enter the GCP Workload parameters. For more information, go to [Google Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity).
```

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +          - Project ID is project where registry is located.
```suggestion
          - Project ID is the project in which the registry is located.
```

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +          - If you select **AWS Access Credentials**, you must enter the AWS access key id and AWS secret access key, and optionally AWS session token. [AWS Credentials](https://docs.aws.amazon.com/g
```suggestion
          - If you select **AWS Access Credentials**, enter the AWS access key ID, the AWS secret access key, and, optionally, the AWS session token. For more information, go to [AWS Credentials](https://docs.aws.amazon.com/general/latest/gr/aws-sec-cred-types.html#access-keys-and-secret-access-keys).
```

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +          - If you select **AWS Service Account**, you must enter the service account.
```suggestion
          - If you select **AWS Service Account**, enter the service account.
```

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +          - **Region** is the region where registry is located.
```suggestion
          - **Region** is the region in which the registry is located.
```

2023-08-03 17:54 UTC, deepakbolangady commented on docs/continuous-delivery/gitops/add-a-harness-git-ops-repository.md
> +          - **Role** is the role arn that will be assumed with given credentials.
```suggestion
          - **Role** is the role ARN that will be assumed with given credentials.
```

2023-08-07 19:36 UTC, michaelcretzman approved these changes

2023-08-07 19:37 UTC, michaelcretzman commented
@deepakbolangady I approved this. Once you have PM approval you are good to merge.

2023-08-08 21:00 UTC, merged