Update settings for JWT token auth
harness/developer-hub pull request #277
Opened 2023-01-04 09:07 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-05 21:23 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +4. Enter a name and email address for this account.
Whose name and email address should be used here? Unless the user already has an understanding of what service accounts are and how they are used, this may not be clear.

2023-01-05 21:25 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +6. Your service account now appears in **Service Account**. Click ** Manage Roles** against the service account you just created to assign role bindings to the service account you just created.
```suggestion
6. Your service account now appears in the **Service Account** list. Select ** Manage Roles** next to the service account you just created to assign role bindings.
```

2023-01-05 21:32 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +   Use the following curl command to update the settings corresponding to the JWT Token authentication:
```suggestion
   Use the following curl command to update the settings corresponding to the JWT authentication:
```

2023-01-05 21:42 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +6. Your service account now appears in **Service Account**. Click ** Manage Roles** against the service account you just created to assign role bindings to the service account you just created.
I think it would be helpful to tell the user to write down the service account ID that is automatically created. The user will need this ID in the next section.

2023-01-05 21:46 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +## Create a service account in Harness
Do you have to create a new service account to do this or can you use an existing account that has the correct settings? It's not clear.

2023-01-05 21:47 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +   For more information, see Create a [service account](../4_Role-Based-Access-Control/6-add-and-manage-service-account.md).
The instructions in the linked topic do not match the instructions here. It looks like the linked content is outdated.

2023-01-06 04:35 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +title: Use the Setting API
Use the Setting API to enable SCIM API authentication through JWT

2023-01-06 04:36 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +You can use JWT Tokens to access Harness SCIM APIs. To do this, you must first configure the settings corresponding to JWT token using the [Setting API](https://apidocs.harness.io/tag/Setting#operati
Done

2023-01-06 05:05 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +1. In Harness, click **Account Settings**.
All the topics refer to the product as "Harness". Are we changing it to app.harness.io now?

2023-01-06 05:11 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +7. Assign the following permissions to the service account:
Users need to select a role and a resource group in the Manage Roles step. This is where the role assignment is done or the permissions are assigned. I have put links to the topics which explain how to do that. However, this is for a specific customer who already knows about RBAC in Harness.

2023-01-06 05:12 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +4. Enter a name and email address for this account.
The user needs to enter a specific name and email address that would correspond to this service account. It could be any valid email address.

2023-01-06 05:17 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +## Create a service account in Harness
A Service account is under the access control module. The steps mentioned here are to create a new service account to enable JWT authentication.

2023-01-06 05:18 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +   For more information, see Create a [service account](../4_Role-Based-Access-Control/6-add-and-manage-service-account.md).
I will create a separate JIRA ticket to update the content.

2023-01-06 17:34 UTC, KimberlyFields requested changes

2023-01-06 17:34 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +## Create a service account in Harness
My point was that it's not clear if a new service account is required to enable JWT authentication. Please add some context around why the user needs to create a service account and indicate if they can use an existing service account.

2023-01-06 17:34 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +1. In Harness, click **Account Settings**.
"Harness" is vague. I think it's best to be specific. Yes, I would like to change it for any new or updated content. You don't have to go back and change every existing instance.

2023-01-06 17:34 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +4. Enter a name and email address for this account.
Since it's not clear why the user needs to create this service account, it's not clear whose name and email should be entered here. Please clarify.

2023-01-06 17:34 UTC, KimberlyFields commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +7. Assign the following permissions to the service account:
Are you sure that the person who would be doing this already knows about RBAC in Harness? If that's the assumption, why include some of the steps for creating a service account? Why not just say you need a service account with specific permissions and provide a link to the existing instructions for creating a service account?

2023-01-09 12:36 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +4. Enter a name and email address for this account.
I checked with @pbarapatre10 on this. Users can enter any email address. It does not matter what they enter. The main focus here is on the service account ID.
This enhancement is only for JPMC.

2023-01-09 12:39 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +7. Assign the following permissions to the service account:
Checked with @pbarapatre10.
This is only for JPMC and they are aware of RBAC.
The steps also talk about assigning specific permissions to the service account which is important for this feature.

2023-01-09 12:42 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +- Make sure you have the **View** and **Edit** permissions for the **Default Settings** at the account scope.
Done

2023-01-09 12:45 UTC, rashminandasahoo commented on docs/platform/16_APIs/default-settings-for-jwt-token.md
> +4. Enter a name and email address for this account.
For clarity, I have rephrased it to "Enter your name and email address".

2023-01-10 05:32 UTC, merged