Added a note for the email address update ff
harness/developer-hub pull request #284
Opened 2023-01-05 13:28 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-05 13:48 UTC, pbarapatre10 submitted a review, later dismissed

2023-01-05 22:29 UTC, KimberlyFields requested changes

2023-01-05 22:29 UTC, KimberlyFields commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +#### Features supported
```suggestion
#### Supported features
```

2023-01-05 22:29 UTC, KimberlyFields commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +#### Group push to Harness
```suggestion
#### Push assigned groups to Harness
```

2023-01-05 22:29 UTC, KimberlyFields commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +If an error prevents adding, deleting, or updating an individual user to Harness, you must retry provisioning the user in Okta later, after resolving the issues. For more information, see [Troublesho
You have to reprovision a user in Okta to delete a user in Harness? That's how I read that sentence. Is that correct?

2023-01-05 22:29 UTC, KimberlyFields commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +Only the five fields listed at the top of this section will be synced to Harness users. You can update values in other fields, but those values will be saved for this user only in Okta. They won't be
```suggestion
Only the five fields listed at the top of this section are synced to Harness users. You can update values in other fields, but those values are saved for this user in Okta only and are not updated in Harness.
```

2023-01-05 22:29 UTC, KimberlyFields commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +If you have created users prior to adding the mapping rule, click Reapply Mappings in your Harness application User settings.
```suggestion
If you have created users prior to adding the mapping rule, select **Reapply Mappings** in the **User** settings section of your Harness application.
```

2023-01-05 22:29 UTC, KimberlyFields commented on docs/platform/3_Authentication/8-provision-users-and-groups-using-azure-ad-scim.md
> +#### Features supported
```suggestion
#### Supported features
```

2023-01-06 03:49 UTC, rashminandasahoo commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +If an error prevents adding, deleting, or updating an individual user to Harness, you must retry provisioning the user in Okta later, after resolving the issues. For more information, see [Troublesho
Updated to "If an error prevents adding, deleting, or updating an individual user to Harness, you must retry provisioning the user later, after resolving the issues. For more information, see [Troubleshooting Group Push](https://help.okta.com/en-us/Content/Topics/users-groups-profiles/usgp-group-push-troubleshoot.htm)."

2023-01-06 04:00 UTC, rashminandasahoo commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +#### Features supported
Done

2023-01-06 04:00 UTC, rashminandasahoo commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +#### Group push to Harness
Done

2023-01-06 04:00 UTC, rashminandasahoo commented on docs/platform/3_Authentication/6-provision-users-with-okta-scim.md
> +Only the five fields listed at the top of this section will be synced to Harness users. You can update values in other fields, but those values will be saved for this user only in Okta. They won't be
Done

2023-01-06 04:00 UTC, rashminandasahoo commented on docs/platform/3_Authentication/7provision-users-and-groups-with-one-login-scim.md
> +If you have created users prior to adding the mapping rule, click Reapply Mappings in your Harness application User settings.
Done

2023-01-06 04:00 UTC, rashminandasahoo commented on docs/platform/3_Authentication/8-provision-users-and-groups-using-azure-ad-scim.md
> +#### Features supported
Done

2023-01-06 04:17 UTC, SudheendraKatte approved these changes
Approving the PR to unblock Rashmi.

2023-01-06 04:19 UTC, merged