Changed the upper case to lower for provisioning tutorial
harness/developer-hub pull request #2848
Opened 2023-08-09 13:31 UTC by Debanitrkl

# Harness Developer Pull Request

## What Type of PR is This?

- [x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-08-09 17:32 UTC, schoudhury requested changes

2023-08-09 17:32 UTC, schoudhury commented on tutorials/ provisioning/clouformation.md
>  title: CloudFormation
should be "AWS CloudFormation"

2023-08-09 17:32 UTC, schoudhury commented on tutorials/ provisioning/clouformation.md
there seems be a space in the file name before provisioning in the form of " provisioning" instead of "provisioning". can you pls check? also the right name is "infra-provisioning" and not just "provisioning"

2023-08-10 14:35 UTC, aimurphy requested changes

2023-08-10 14:35 UTC, aimurphy commented on src/components/Tutorials/ProvisioningCDData.ts
> +            "Provisiong deployment infrastructre using CF",
```suggestion
            "Provision deployment infrastructure using CF",
```

2023-08-10 14:35 UTC, aimurphy commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/lottie-react/-/lottie-react-2.4.0.tgz#f7249eee2b1deee70457a2d142194fdf2456e4bd"
Please revert/uncommit changes to yarn.lock. If you need the true/latest version, please check `main`.

2023-08-10 14:47 UTC, schoudhury commented on yarn.lock
> +  resolved "https://registry.yarnpkg.com/lottie-react/-/lottie-react-2.4.0.tgz#f7249eee2b1deee70457a2d142194fdf2456e4bd"
@Debanitrkl ravi added yarn.lock to .gitignore couple days back. can you pls rebase so that you can get that change and then this yarn.lock change will become local to you. cc @ravilach

2023-08-10 16:15 UTC, aimurphy approved these changes

2023-08-10 23:01 UTC, schoudhury approved these changes

2023-08-10 23:01 UTC, merged