{GitLab; GitHub Actions} to Harness CI Migration Guides
harness/developer-hub pull request #285
Opened 2023-01-05 14:15 UTC by Ompragash

Signed-off-by: Ompragash Viswanathan <ompragash@proton.me>

## Summary

This PR contains a **Migrating from {GitLab; GitHub Actions}** guides that help the user to migrate their existing {GitLab; GitHub Actions} pipelines to Harness CI.

- Added two files: `migrating-from-githubactions.md` and `migrating-from-gitlab.md`

### Attention Needed

File: {`migrating-from-gitlab.md`; `migrating-from-githubactions.md`}
> Need to check/add the values of the below parameters
- `sidebar_position`
- `helpdocs_topic_id`
- `helpdocs_category_id`

## What Type of PR is This?

- [x] Documentation

## Credits❤️
- @codewdhruv & @krishi0408 for all their hard work and efforts in migrating other* CI pipelines to Harness CI!

## Mandate PR checks
- [x] Tested Locally
- [x] *Optional* Screen Shoot.
<img width="1785" alt="Screenshot 2023-01-05 at 7 29 59 PM" src="https://user-images.githubusercontent.com/21008429/210800119-b92794b6-0394-4583-bf3f-8295d99f3e10.png">
<img width="1785" alt="Screenshot 2023-01-05 at 7 30 12 PM" src="https://user-images.githubusercontent.com/21008429/210800164-cfb735b5-65ce-401f-8c9a-04e1d59b822c.png">
<img width="1785" alt="Screenshot 2023-01-05 at 7 30 33 PM" src="https://user-images.githubusercontent.com/21008429/210800191-00c5fd9f-2cc3-406a-b25b-b341f802defd.png">

2023-01-06 20:51 UTC, KimberlyFields requested changes
Use the Add suggestion to batch option to accept the suggestions instead of using the Commit suggestion option on each suggestion. That way, you'll only have one commit with all of the suggestions instead of multiple commits.

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +There are a few differences, and this guide will show you the important differences so that you can quickly migrate your existing Gitlab workflows to Harness CI.
```suggestion
There are a few differences, and this guide will show you the important differences so that you can quickly migrate your existing GitLab workflows to Harness CI.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- Gitlab configurations are stored in the .gitlab-ci.yml file in the root directory of your repository while Harness provides inline pipeline storage or importing [pipeline YAML (Pipeline-as-Code)](h
```suggestion
- GitLab configurations are stored in the .gitlab-ci.yml file in the root directory of your repository while Harness provides inline pipeline storage or importing [pipeline YAML (Pipeline-as-Code)](https://developer.harness.io/docs/platform/git-experience/import-a-pipeline/) from Git option.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- Harness CI provides proprietary technologies like Cache Intelligence and Test Intelligence™ enabling [four times faster](https://harness.io/blog/fastest-ci-tool) than other leading CI tools
```suggestion
- Harness CI provides proprietary technologies like Cache Intelligence and Test Intelligence™ which enables Harness CI to be [four times faster](https://harness.io/blog/fastest-ci-tool) than other leading CI tools.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- Harness CI allows executing Github Actions plugins, Drone Plugins, and Bitrise Plugins using the [Plugin steps](https://docs.harness.io/category/ei5fgqxb0j-use-drone-plugins)
```suggestion
- Harness CI allows executing GitHub Actions plugins, Drone Plugins, and Bitrise Plugins using the [Plugin steps](https://developer.harness.io/docs/category/use-drone-plugins/)
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- **Testing and Verification:** GitLab CI comes with a set of test suites which apply to any language. Harness CI goes beyond that. Test Intelligence is one of Harness CI's most advanced features whi
```suggestion
- **Testing and Verification:** GitLab CI comes with a set of test suites that apply to any language. Harness CI goes beyond that. Test Intelligence is one of Harness CI's most advanced features that dramatically reduces build times. It does so by running incremental builds that allow Harness to run relevant tests and bypass unnecessary tests.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- **Secrets Management:** GitLab does not offer native secrets management capabilities. They have selected Vault by HashiCorp as their first supported secrets management partner which means you must
```suggestion
- **Secrets Management:** GitLab does not offer native secrets management capabilities. They have selected Vault by HashiCorp as their first supported secrets management partner, which means you must first configure your Vault server. Harness includes a built-in secrets management feature that enables you to store encrypted secrets, such as access keys, and use them in your Harness applications.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +
It might be easier for customers to understand the differences if you put them in a table.

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Harness Cache Intelligence is another proprietary technology that reduces pipeline execution time by automatically caching well-known directories for Java and Node.js support as of now with more lang
```suggestion
Harness Cache Intelligence is another proprietary technology that reduces pipeline execution time by automatically caching well-known directories for Java and Node.js support as of now ,with more languages support coming in the future. It manages and flushes the cache in the Harness user interface.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +In GitLab jobs are a fundamental element in the configuration file. Jobs in GitLab CI/CD are very similar to steps in Harness CI. In both systems it has the following characteristics:
```suggestion
In GitLab, jobs are a fundamental element in the configuration file. Jobs in GitLab CI/CD are very similar to steps in Harness CI. Jobs have the following characteristics in both products: 
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- Jobs in Gitlab contain a series of steps or scripts that run sequentially similar to the steps in Harness CI
```suggestion
- Jobs in GitLab contain a series of steps or scripts that run sequentially similar to the steps in Harness CI.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- Jobs run in parallel by default in Gitlab, but can be configured to run sequentially.
```suggestion
- Jobs run in parallel by default in GitLab, but can be configured to run sequentially.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- A Stage in Harness CI is a subset of the Pipeline that contains the logic to perform one major segment of the Pipeline process.
```suggestion
- A Stage in Harness CI is a subset of the pipeline that contains the logic to perform one major segment of the pipeline process. 
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +- Stages are based on the different milestones of the Pipeline, such as building, approving etc
```suggestion
- Stages are based on the different milestones of the pipeline, such as building, approving, etc.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +You can run a script or a shell command in a job. In GitLab CI/CD script steps are specified using the script key.
```suggestion
You can run a script or a shell command in a job. In GitLab, CI/CD script steps are specified using the script key.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +In Harness CI all scripts are specified using the command key for the steps inside the stage configuration.
```suggestion
In Harness CI, all scripts are specified using the command key for the steps inside the stage configuration.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +In Harness CI you add a docker image by connecting to your repository using an Harness Docker Connector. You can configure different types of artifact source connectors in Harness.
```suggestion
In Harness CI you add a docker image by connecting to your repository using a Harness Docker connector. You can configure different types of artifact source connectors in Harness. 
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Gitlab CI defines images at the job level and allows or supports setting this to be used by all jobs globally that don’t have a docker image defined.
```suggestion
GitLab CI defines images at the job level and allows or supports setting this to be used by all jobs globally that don’t have a Docker image defined.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +In Harness CI Stages are executed in order of occurrence in the YAML config. Stages defined under the “- parallel” tag execute in a parallel fashion.
```suggestion
In Harness CI, stages are executed in order of occurrence in the YAML configuration. Stages defined under the “- parallel” tag execute in a parallel fashion.
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +## Environment Variables
```suggestion
## Environment variables
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Environment Variables defines in Gitlab can used to:
```suggestion
Environment variables in GitLab can used to:
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Harness CI supports users to add Variables on Project, Organization, and Account levels and allows them to be referenced using the following expression: `<+variable.[scope].[variable_id]>`
```suggestion
Harness CI supports users to add variables on project, organization, and account levels, and allows them to be referenced using the following expression: `<+variable.[scope].[variable_id]>`
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Find more information on Account, project, and Org level Variables [here](https://docs.harness.io/article/f3450ye0ul-add-a-variable)
```suggestion
Find more information on account, project, and org-level variables [here](https://developer.harness.io/docs/platform/variables-and-expressions/add-a-variable/)
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Parallel matrix jobs in Harness CI allows you to create jobs at runtime based on specified variables. Here to run multiple instances of a job with different variables values for each instance can be
```suggestion
Parallel matrix jobs in Harness CI allow you to create jobs at runtime based on specified variables. Running multiple instances of a job with different variables values for each instance can be accomplished with a combination of `parallel:` and `matrix:`
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +To learn more about Matrix check out the [documentation here](https://docs.harness.io/article/eh4azj73m4#matrix)
```suggestion
To learn more about matrix, go to the [documentation here](https://developer.harness.io/docs/platform/pipelines/looping-strategies-matrix-repeat-and-parallelism/#matrix)
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Gitlab CI Trigger: Through API
This seems like an incomplete thought. What are you trying to communicate here?

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +Harness CI Harness supports Webhooks triggers, Artifacts triggers, Manifest triggers, and scheduled triggers. The two most commonly used triggers are webhook triggers based on Git events and Schedule
```suggestion
Harness CI supports webhook triggers, artifact triggers, manifest triggers, and scheduled triggers. The two most commonly used triggers are webhook triggers based on Git events and scheduled triggers based on cron expressions. 
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +To know more about creating a trigger visit [Harness Triggers](https://developer.harness.io/docs/category/triggers)
```suggestion
To learn more about creating a trigger, go to [Harness Triggers](https://developer.harness.io/docs/category/triggers).
```

2023-01-06 20:51 UTC, KimberlyFields commented on docs/continuous-integration/migration-guides/migrating-from-gitlab.md
> +## Complete Example
```suggestion
## Complete example
```

2023-01-09 18:02 UTC, Ompragash commented
> Use the Add suggestion to batch option to accept the suggestions instead of using the Commit suggestion option on each suggestion. That way, you'll only have one commit with all of the suggestions instead of multiple commits.

I mostly use git CLI to commit changes and those commits are directories and files

2023-01-23 13:59 UTC, jimsheldon commented
I'm not sure if it makes sense to add to this doc, but we have two big differentiators over GHA right now:

1. Apple silicon support (currently not available on the free tier unfortunately)
2. Linux arm64 support (available on the free tier)

Let me know if I can help.

2023-01-27 20:43 UTC, KimberlyFields commented
@Ompragash have you had the chance to review my comments?

2023-01-28 07:55 UTC, Ompragash commented
hey @KimberlyFields, as we were doing more migrations we were trying to find out if we can add more details. I think by this week we can get it out and I'll satisfy the ask accordingly and comment if required.

2023-02-23 19:21 UTC, aimurphy commented
@Ompragash Just checking if you have any updates or if you've been able to review Kim's comments?

2023-04-20 18:39 UTC, aimurphy commented
This PR has fallen far behind main. I am transferring these draft topics to a new feature branch and I will pick up revisions from there.

2023-04-20 18:39 UTC, closed without merging