Update automate-delegate-installation.md
harness/developer-hub pull request #288
Opened 2023-01-05 19:09 UTC by kat-enos

Small edits for migration cleanup and language.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-06 00:06 UTC, kat-enos commented
Small editorial pass with post-migration cleanup.

2023-01-06 16:41 UTC, KimberlyFields requested changes

2023-01-06 16:41 UTC, KimberlyFields commented on docs/platform/2_Delegates/delegate-guide/automate-delegate-installation.md
> +If you want to install Kubernetes delegates in separate clusters, do not use the same harness-kubernetes.yaml and name for both delegates. Download a new Kubernetes YAML `spec` from Harness for each
```suggestion
If you want to install Kubernetes delegates in separate clusters, do not use the same harness-kubernetes.yaml and name for both delegates. Download a new Kubernetes YAML `spec` from Harness for each delegate you want to install. This prevents name conflicts. 
```

2023-01-06 16:41 UTC, KimberlyFields commented on docs/platform/2_Delegates/delegate-guide/automate-delegate-installation.md
> +The delegate configuration file contains environment variables for account, Organization, and Project. The account variable is always set with your Harness account ID.
```suggestion
The delegate configuration file contains environment variables for account, organization, and project. The account variable is always set with your Harness account ID.
```

2023-01-12 20:23 UTC, kat-enos commented
I believe all changes were made in the file.

2023-01-12 23:05 UTC, michaelcretzman approved these changes

2023-01-20 20:24 UTC, KimberlyFields approved these changes

2023-02-16 05:58 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +A Kubernetes cluster requires only one delegate. To create high availability in the cluster, you can increase the number of delegate replica pods. Do not add another delegate to the cluster.
```suggestion
A Kubernetes cluster requires only one delegate. To create high availability in the cluster, you can increase the number of delegate replica pods. Do not add another delegate to the cluster. 

If you want to install Kubernetes delegates in separate clusters, do not use the same harness-kubernetes.yaml and name for both delegates. Download a new Kubernetes YAML `spec` from Harness for each delegate you want to install. This prevents name conflicts. 

In every case, the delegates must be identical in terms of permissions, keys, connectivity, and so on. With two or more delegates running in the same target environment, high availability is provided by default. The failure of a single delegate does not stop Harness from performing deployments. For greater availability, increase the number of replica pods to run three delegates in case you lose two, and so on.

```

2023-02-16 13:01 UTC, deepakbolangady approved these changes
LGTM but for some minor comments, Katherine. Approving with the assumption that you'll consider the feedback before you merge. Thanks.

2023-02-16 16:21 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +* Two delegates in different locations with different connectivity do not support high availability. For example, if you have one delegate in a development environment and another in a production env
I'm not sure what the writer's intention was on "different connectivity" but I tend to think that "physically separated connectivity" would be more confusing. If I was going to change that description, I would want to have it technically reviewed and in doing edits like this the point is to avoid changing technical meaning. Delegates don't talk to each other and any network connection could be said to be a "different connection" or to be "physically separated" by virtue of how sockets are connected. I think the point is that you have two delegates running in different environments. I can cut out "with different connectivity" and think that might make things more clear.

2023-02-16 16:24 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +The delegate configuration file contains environment variables for account, organization, and project. The account variable is always set with your Harness account ID.
I'll accept this change. I agree that the original "with" is vague.

2023-02-16 16:26 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +Before you duplicate the file, review the list of environment variables in the delegate `spec` to ensure they are appropriate for the second delegate. For further information, see [Delegate environme
I think the word on that was to implement it as we write new content.

2023-02-16 16:31 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +For the Kubernetes delegate, the name is referenced in multiple fields:
I thought I wrote around this since the "For the Kubernetes delegate" structure adds extra words. I think your rewrite is confusing. The point of this section in this document that precedes me, is that you need to change the name of a Kubernetes document in multiple fields in the YAML. I'll open up the file and try to simplify it.

2023-02-16 16:33 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +The process you use to rename a delegate depends on its type. For Docker delegates, you change the name in one environment variable in the Docker compose file. For the Kubernetes delegate, you change
I thought I had a simplification for this, that writes around the "you use" form, one that I usually try to avoid. I'll try to address it by opening the file and making further changes though it will slow finally getting out the changes that were made.

2023-02-16 16:47 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +#### Rename the Docker delegate
The "Harness Delegate" convention comes from Microsoft style for dealing with product names -- that is, the product names that belong to the company. We were initial-capitalizing Docker Delegate from the viewpoint that we consider it a delegate "type." It is not a product name and we don't own Docker, so the term does not need to, and should not, conform to the standards for Harness product names. Style sheets with usage examples of product, module and tradenames would help with the confusion. Product name style is also not used when you want to refer to multiple instances of the component, in other words, it would be incorrect to use pluralization and say "Harness Delegates"; instead, I use "Harness delegates" if necessary but there's usually no reason not to simplify and just say "delegates." Generally, if the context is clear, you can just use the shortened form. This is all based on how I learned to treat product names in accord with legal standards (including the bugging of tradenames internal and external) at Microsoft. The PM is trying to simplify things for customers and we agreed that, in the long run, it should just be "delegate." So the use is consistent within the different guidelines that exist.

2023-02-21 20:39 UTC, michaelcretzman approved these changes
approved with the assumption that you will consider my suggestions.

2023-02-21 20:39 UTC, michaelcretzman commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +The delegate configuration file contains environment variables for account, organization, and project. The account variable is set to your Harness account ID.
```suggestion
The delegate configuration file contains environment variables for account, organization, and project. The account variable is set to your Harness account Id.
```

2023-02-21 20:39 UTC, michaelcretzman commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +The delegate configuration file contains environment variables for account, organization, and project. The account variable is set to your Harness account ID.
ID should be Id or Identifier.

2023-02-21 20:39 UTC, michaelcretzman commented on docs/platform/2_Delegates/advanced-installation/automate-delegate-installation.md
> +Before you duplicate the file, review the list of environment variables in the delegate `spec` to ensure they are appropriate for the second delegate. For further information, see [Delegate environme
not sure why spec is formatted as code. 

Also if we are talking about K8s delegates, you can just say manifest or spec.

2023-02-21 21:53 UTC, merged