added new topic
harness/developer-hub pull request #290
Opened 2023-01-05 22:28 UTC by michaelcretzman

AWS ECS support summary

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* https://harness.atlassian.net/browse/CDS-49725

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-05 23:30 UTC, thisrohangupta approved these changes
Thanks Michael for the docs update on this. It looks good.

2023-01-06 16:31 UTC, KimberlyFields requested changes

2023-01-06 16:31 UTC, KimberlyFields commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +- Harness has made Infrastructure Definitions a lighter configuration you can reuse for other ECS Services.
We are no longer capitalizing terms like infrastructure definitions, pipeline, delegate, etc. They are common terms and should not be capitalized unless they are trademarked by Harness. Please update the capitalization of the terms in this PR.

2023-01-06 16:31 UTC, KimberlyFields commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +For users coming from Harness FirstGen, this is a significant change and requires time to upgrade previous pipelines.
Since this information affects FirstGen users, please add a link to this from the FirstGen ECS docs.

2023-01-06 19:50 UTC, michaelcretzman commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +description: Harness ECS support.
changed it to:

title: AWS ECS support changes from Harness FirstGen to NextGen
description: Review ECS support changes from FirstGen to NextGen.

2023-01-06 19:53 UTC, michaelcretzman commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +For users coming from Harness FirstGen, this is a significant change and requires time to upgrade previous pipelines.
done

2023-01-06 20:02 UTC, michaelcretzman commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +- [ECS deployment tutorial](../../onboard-cd/cd-quickstarts/ecs-deployment-tutorial.md)
done

2023-01-06 20:02 UTC, michaelcretzman commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +- Basic ECS Workflow type.
done

2023-01-06 20:04 UTC, michaelcretzman commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +
done

2023-01-06 20:59 UTC, michaelcretzman commented on docs/continuous-delivery/cd-advanced/AWS ECS/ecs-v2-summary.md
> +- Harness has made Infrastructure Definitions a lighter configuration you can reuse for other ECS Services.
done

2023-01-06 21:23 UTC, thisrohangupta approved these changes

2023-01-06 21:24 UTC, thisrohangupta commented
The changes look good to me, I read the readme earlier, sorry for the delay Michael

2023-01-06 22:19 UTC, KimberlyFields approved these changes

2023-01-06 22:20 UTC, merged