Update harness-saa-s-release-notes.md
harness/developer-hub pull request #293
Opened 2023-01-06 00:07 UTC by michaelcretzman

added FG SaaS RN for CD

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-06 16:52 UTC, KimberlyFields requested changes

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +### Jan 5th, 2023, version 78100
This is not the final version number.

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +  Fixed a bug where approvals executed after a stage with runtime inputs were not being expired.
Shouldn't this be in the Fixed issues section instead of the What's new section?

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +  You can retrieve the value of the collectionEnabled field for an Artifact Source using GraphQL Apis, like in the example below:
```suggestion
  You can retrieve the value of the collectionEnabled field for an Artifact Source using GraphQL APIs, like in the example below:
```

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +- Support AWS S3 as script source for Terraform Provisioners (CDS-2970
```suggestion
- Support AWS S3 as a script source for Terraform Provisioners (CDS-2970)
```

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +  - Now you can use AWS S3 option for your remote Terraform script files.
```suggestion
  - Now you can use the AWS S3 option for your remote Terraform script files.
```

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +  - Now you can use AWS S3 option for your remote Terraform script files.
Add a link to the docs for this. Also, be sure to add this to the early access topic.

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +  - Fixed an issue using multiselect fields with new metadata endpoint. While using new metadata endpoint, we received an empty string where null was expected. Now we check for both.
```suggestion
  - Fixed an issue using multiselect fields with a new metadata endpoint. While using a new metadata endpoint, we received an empty string where null was expected. Now we check for both.
```

2023-01-06 16:52 UTC, KimberlyFields commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +- Custom Remote Manifest error message needs to be improved when Chart.yaml is given instead of directory (CDS-48038)
```suggestion
- Custom Remote Manifest error message needs to be improved when Chart.yaml is given instead of a directory (CDS-48038)
```

2023-01-09 23:18 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +- Delegate tasks are now limited based on account. (DEL-5371)
If you're indicating DEL-5371, there are no corresponding docs at this time.

2023-01-09 23:47 UTC, michaelcretzman commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +- Add the status of the collection in the artifactsource response in GraphQL API (CDS-44426)
there isn't a doc. Our GraphQL UI exposes the compiled comments as docs. I can show you if you want.

2023-01-09 23:47 UTC, michaelcretzman commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +  - Now you can use AWS S3 option for your remote Terraform script files.
no doc yet. backlog

2023-01-09 23:52 UTC, michaelcretzman commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +  Fixed a bug where approvals executed after a stage with runtime inputs were not being expired.
done.

2023-01-09 23:53 UTC, michaelcretzman commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +### Jan 5th, 2023, version 78100
will add it when it's available and before merge

2023-01-11 00:12 UTC, michaelcretzman commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +- The libraries of the Apache CXF open-source services framework (`org.apache.cxf`) were upgraded to fix vulnerabilities. (DEL-5591)
the vulnerabilities were in the Apache libraries not Harness. Harness upgraded the libraries to safe ones is more of a upgrade to the product. It's debatable but I think it's something customers would see as an enhancement.

2023-01-11 00:13 UTC, michaelcretzman commented on docs/first-gen/firstgen-release-notes/harness-saa-s-release-notes.md
> +- The  libraries of the `io.netty:netty*` client/server framework have been updated to fix vulnerabilities. (DEL-5632)
the vulnerabilities were in the netty libraries not Harness. Harness upgraded the libraries to safe ones is more of a upgrade to the product. It's debatable but I think it's something customers would see as an enhancement.

2023-01-11 01:21 UTC, merged