Cd ng release saas january 5th 2023 for 781xx
harness/developer-hub pull request #299
Opened 2023-01-06 19:37 UTC by michaelcretzman

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* RN for January 5th, 2023, version 78100

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-10 20:34 UTC, KimberlyFields requested changes
Remember to use the Add suggestion to batch option instead of the Commit suggestion option to enable a single commit with all of the accepted suggestions instead of individual commits for each accepted suggestion.

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  Earlier we were creating expired times for new freeze windows that will never get active. Due to this, manual freeze was getting marked as expired after creation, but global freeze was getting enab
This is confusing and I'm not sure how to make it better. Please revise for clarity.

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +- The template input screen is blank when we try changing the template version (CDS-47641) A black template input screen is shown when version of a linked template is changed from **stable** to **alw
```suggestion
- The template input screen is blank when changing the template version. (CDS-47641) 

A black template input screen is shown when the version of a linked template is changed from **stable** to **always use stable version**. This happens only for pipeline templates. This issue has been fixed.
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +- The template input screen is blank when we try changing the template version (CDS-47641) A black template input screen is shown when version of a linked template is changed from **stable** to **alw
Should "black" be "blank"?

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  We don't support propagate service from previous stage in case of multi-service deployments.
Please revise for clarify. This sounds like something that isn't supported rather than something that was fixed.

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +- shading color when adding a connector is off (CDS-47282)
```suggestion
- When adding a connector, the **Details** dialog is unclear. (CDS-47282)
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  Added delegate selector title and icon with details for Kubernetes8s Connector.
```suggestion
  The UI was improved so that it now includes a delegate selector title and an icon with details for the Kubernetes Connector.
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +- ServiceNow import sets logging issues (CDS-43958)
```suggestion
- ServiceNow import sets logging issues. (CDS-43958)
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  Descriptive console logs have been added in the ServiceNow Import Set step for various scenarios. This will further help in debugging or monitoring the step from console tab itself.
```suggestion
  Descriptive console logs have been added in the ServiceNow Import Set step for various scenarios. This will further help in debugging or monitoring the step from the console tab.
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +- Getting "Connector Not Found Error" when checked from the pipeline (CDS-43812)
When what is checked?

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  Fixed test connection for Physical DataCenter connector.
```suggestion
  Fixed the test connection for the Physical DataCenter connector.
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +- Secret value is not masked in the exception (CDS-43267)
```suggestion
- Secret value is not masked in the exception. (CDS-43267)
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  Issue: secrets were not masked in exceptions due to invalid JSON input data containing secrets in ServiceNow Import Sets. Solution: proper sanitization is added to ensure secrets are masked in exce
```suggestion
  Secrets were not masked in exceptions due to invalid JSON input data containing secrets in ServiceNow Import Sets. 
  
Proper sanitization was added to ensure secrets are masked in exceptions resulting in this scenario in logs as well as in the UI.
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +- Approval slack notification sending names instead of identifier in the approval notification (CDS-29134)
```suggestion
- Approval Slack notification sending names instead of identifier in the approval notification. (CDS-29134)
```

2023-01-10 20:34 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  Harness approval notifications via slack and email currently send identifiers instead of readable names. For example, for details regarding organization, project, and triggered by metadata, identif
```suggestion
  Harness approval notifications via Slack and email currently send identifiers instead of readable names. For example, for details regarding organization and project, and triggered by metadata, identifiers are sent instead of names. This issue has been resolved. The notification now contains names, emails, etc., instead of identifiers. For users triggering the approval step, email is displayed. For organization and projects, names are displayed.
```

2023-01-10 21:36 UTC, michaelcretzman commented on release-notes/continuous-delivery.md
> +  Earlier we were creating expired times for new freeze windows that will never get active. Due to this, manual freeze was getting marked as expired after creation, but global freeze was getting enab
updated with:

> - [Deployment freeze](../docs/continuous-delivery/cd-deployments-category/deployment-freeze.md): When the freeze window schedule time frame is prior to the current time, the API returns success but the UI is still disabled. (CDS-47760)
>   
> When users created freeze window schedule time frames that are in the past, the freeze window was marked as expired right after creation, which is correct, but the global freeze (`Freeze disabled on all deployments for this [Account/Organization/Project]`) was getting enabled. Now we throw an exception when the new freeze window created is already expired.

2023-01-10 21:41 UTC, michaelcretzman commented on release-notes/continuous-delivery.md
> +  We don't support propagate service from previous stage in case of multi-service deployments.
changed to:

> - The [Deployment Template](../docs/continuous-delivery/onboard-cd/cd-quickstarts/custom-deployment-tutorial.md) **Details** screen goes blank when changing the template version in **Version Label**. (CDS-47641) 

>  A blank template **Details** screen is shown when the version of a linked template is changed from **stable** to **Always use stable version**. This happens only for pipeline templates. This issue has been fixed. Now you can change the **Version Label** and there is no issue.

2023-01-10 22:04 UTC, michaelcretzman commented on release-notes/continuous-delivery.md
> +- Getting "Connector Not Found Error" when checked from the pipeline (CDS-43812)
if the connector referenced in the pipeline exists.

changed to:

- Getting "Connector Not Found Error" when you save a pipeline using the Physical DataCenter connector even when the connector exists. (CDS-43812)
  
  Fixed the check for the Physical DataCenter connector.

2023-01-10 22:19 UTC, KimberlyFields requested changes

2023-01-10 22:19 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  We don't support propagate service from previous stage in case of multi-service deployments.
@michaelcretzman my comment was regarding CDS-47626, not CDS-47641.

2023-01-10 22:19 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +  Earlier we were creating expired times for new freeze windows that will never get active. Due to this, manual freeze was getting marked as expired after creation, but global freeze was getting enab
Some additional revisions:
When users created freeze window schedule time frames that were in the past, the freeze window was marked as expired right after creation, which is correct, but the global freeze (Freeze disabled on all deployments for this [Account/Organization/Project]) was enabled. Now, we throw an exception when the newly created freeze window is already expired.

2023-01-10 22:19 UTC, KimberlyFields commented on release-notes/whats-new.md
> +### Continuous Delivery
Apply the same edits that I made in the What's new section in continuous-delivery.md to the text in this file.

2023-01-10 23:29 UTC, KimberlyFields approved these changes
I'm approving this in anticipation of the additional comments being addressed before the PR is merged.

2023-01-10 23:29 UTC, KimberlyFields commented on release-notes/continuous-delivery.md
> +## January 5th, 2023, version 78100
Make sure you update the date and version number.

2023-01-10 23:29 UTC, KimberlyFields commented on release-notes/whats-new.md
> +## January 5th, 2023, version 78100
Make sure you update the date and version number.

2023-01-10 23:49 UTC, michaelcretzman commented
@KimberlyFields 
- incorp'd your review
- added clarifications
- added images and links
- did another pass on the text
Please review

2023-01-11 03:34 UTC, KimberlyFields approved these changes

2023-01-11 03:34 UTC, merged