added release notes content for the  release 77908-xxxx
harness/developer-hub pull request #304
Opened 2023-01-09 06:42 UTC by SudheendraKatte

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

Added contents for release notes 77908

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-09 08:11 UTC, rashminandasahoo requested changes

2023-01-09 08:11 UTC, rashminandasahoo commented on release-notes/service-reliability-management.md
> +Now, the Service Health screen displays the service status as NO_DATA if there is no metric data available from the health source for a time period.
Please see if this looks correct in the context "When there are no metrics available from the health source, the Service Health screen now shows the service state as `NO DATA`."

2023-01-09 08:11 UTC, rashminandasahoo commented on release-notes/service-reliability-management.md
> +Saving the **Verify** step in a Stage template throws the `Invalid YAML. Can't find pipeline.` error if the YAML file does not contain a pipeline key. (SRM-13320)
Saving the **Verify** step in a stage template throws an error if the pipeline key is missing in the YAML.

2023-01-09 08:11 UTC, rashminandasahoo commented on release-notes/service-reliability-management.md
> +You can now save the **Verfy** step in a Stage template even if the YAML file does not contain a pipeline key.
Typo in Verify.

2023-01-10 04:38 UTC, SudheendraKatte commented on release-notes/service-reliability-management.md
> +Now, the Service Health screen displays the service status as NO_DATA if there is no metric data available from the health source for a time period.
Thanks for the suggestion. I prefer to keep the existing text as the suggested text makes the information technically not complete.

2023-01-10 04:42 UTC, SudheendraKatte commented on release-notes/service-reliability-management.md
> +You can now save the **Verfy** step in a Stage template even if the YAML file does not contain a pipeline key.
The fix contains backend information which is not exposed to the end user.

2023-01-10 07:24 UTC, SudheendraKatte commented on release-notes/service-reliability-management.md
> +Service Health screen displays service status as Healthy even if there is no metric data available from the health source for a time period. (SRM–13336)
Here is the updated text:

- Even though metric data is not available from the health source for a time period, the Overall Health Score timeline displays green bars and shows the service score as 100.
  
  Now, on the Service Health page, the Overall Health Score timeline displays grey bars if metric data is unavailable from the health source for a specific time period. It does not show the health score.

2023-01-11 05:07 UTC, rashminandasahoo approved these changes

2023-01-11 05:35 UTC, merged