CCM BI dashboard
harness/developer-hub pull request #315
Opened 2023-01-10 12:59 UTC by charanya-j

Created a new topic to document the steps to access CCM dashboards.
Local build successful.

2023-01-10 17:57 UTC, michaelcretzman requested changes
just a few minor nits. Looks good.

2023-01-10 17:57 UTC, michaelcretzman commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/access-ccm-dashboards.md
> +For information on core Dashboard functionality, see [Create Dashboards](https://docs.harness.io/article/ardf4nbvcy-create-dashboards).
I think we use "go to" instead of "see".
check our style guide: https://harness.atlassian.net/wiki/spaces/DOCS/pages/21130772574/Documentation+style+guide

2023-01-10 17:57 UTC, michaelcretzman commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/access-ccm-dashboards.md
> +Harness provides pre-loaded **By Harness** (pre-defined) and **Custom** (user-defined) Dashboards to visualize cloud cost data across clusters and the Cloud accounts.
remove "the" before "Cloud accounts".
use "cloud" instead of "Cloud".

2023-01-10 17:57 UTC, michaelcretzman commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/access-ccm-dashboards.md
> +1. In the **Harness** application, click **Dashboards**.
this could probably all be one list of numbers and not reset to 1 here.

2023-01-11 03:09 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/access-ccm-dashboards.md
> +For information on core Dashboard functionality, see [Create Dashboards](https://docs.harness.io/article/ardf4nbvcy-create-dashboards).
Thank you, Michael. Fixed it.

2023-01-11 03:09 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/access-ccm-dashboards.md
> +Harness provides pre-loaded **By Harness** (pre-defined) and **Custom** (user-defined) Dashboards to visualize cloud cost data across clusters and the Cloud accounts.
Done.

2023-01-11 03:10 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/8-ccm-dashboards-and-access-control/ccm-dashboards-by-harness/access-ccm-dashboards.md
> +1. In the **Harness** application, click **Dashboards**.
This s actually a new ordered list.

2023-01-11 04:06 UTC, charanya-j commented
Hi @michaelcretzman,
Thanks for reviewing the PR. I've incorporated your comments. Could you please approve?

2023-01-11 17:30 UTC, michaelcretzman approved these changes

2023-01-11 17:31 UTC, merged