CCM-11324-added new markdown files for commitment orchestrator
harness/developer-hub pull request #3358
Opened 2023-09-18 12:36 UTC by charanya-j

2023-09-20 10:48 UTC, sandyydk requested changes
Looks good to me. Added a small comment to remove a typo. 

@navaneeth Do we want to retain the image used in docs for Setup Screen where projected savings look a bit less or is it fine as it's only a sample screen?

2023-09-20 10:48 UTC, sandyydk commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch.md
> +For more information about Reserved Instances, go to [Reserved Instances. \
nit: Additional backslash here. This is visible in the docs.

2023-09-20 10:48 UTC, sandyydk commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch.md
> +For more information about Reserved Instances, go to [Reserved Instances. \
![Uploading Screenshot 2023-09-20 at 4.15.19 PM.png…]()

2023-09-20 11:08 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch.md
> +For more information about Reserved Instances, go to [Reserved Instances. \
Noted.

2023-09-21 11:44 UTC, jyotiarora-harness approved these changes

2023-09-28 00:03 UTC, Additi requested changes
PTAL

2023-09-28 00:03 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/use-commitment-orch.md
> +   - The Commitment Orchestrator continuously looks for opportunities to acquire or convert Reserved Instances (RIs)
Can we also add we do daily staggered purchases and not in bulk.

2023-10-11 05:40 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/_category_.json
> +       "title":"Optimize cloud costs by using Commitment Orchestrator"
Done

2023-10-11 05:41 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch-summary.md
> +* Viewing the total Compute spend, Compute coverage, Savings, and the Commitment utilization data.
Done

2023-10-11 05:43 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch-summary.md
> +* **Compute spend**: The total amount spent on all compute instances that include Savings Plans, RIs, and On-Demand instances.
Done

2023-10-11 05:46 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch-summary.md
> +* **Compute Coverage**: This visualization illustrates the percentage of coverage attributed to specific commitment types. Within the bar graph, the X-axis denotes dates, while the Y-axis represents
Done

2023-10-11 05:48 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch-summary.md
> +* **Savings**: The total cost savings achieved by setting up the Commitment Orchestrator. Within the bar graph, the X-axis denotes dates, while the Y-axis represents the corresponding saved costs. Be
Done

2023-10-11 05:50 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch-summary.md
> +After setting up the Commitment Orchestrator, some automated actions are taken in order to optimize utilization of the RIs and Savings Plans. The details of these events are recorded and displayed in
Done

2023-10-11 05:54 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch.md
> +The Harness Cloud Cost Management (CCM) platform provides powerful cost-saving mechanisms through its AutoStopping and Cluster Orchestrator features, which can automatically shut down non-production
Done

2023-10-11 05:57 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/use-commitment-orch.md
> +   - The Commitment Orchestrator continuously looks for opportunities to acquire or convert Reserved Instances (RIs)
Done

2023-10-11 06:00 UTC, charanya-j commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/commitment-orch.md
> +In such cases, you can still optimize your resource utilization and save costs by making the most of your existing Reserved Instances (RI) before purchasing new ones. By carefully managing your RIs a
Added this here: # How does Commitment Orchestrator optimize utilization?

2023-12-19 19:46 UTC, bot2-harness commented
This PR has been automatically closed due to inactivity.

2023-12-19 19:46 UTC, closed without merging