new topic
harness/developer-hub pull request #336
Opened 2023-01-11 20:13 UTC by michaelcretzman

added Rohan's and Umesh's doc.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* https://harness.atlassian.net/browse/CDS-49945

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-11 20:41 UTC, thisrohangupta approved these changes
This looks good thanks Michael

2023-01-12 23:31 UTC, douglas-j-bothwell requested changes
A few typos, otherwise looks good!

2023-01-12 23:31 UTC, douglas-j-bothwell commented on docs/continuous-delivery/onboard-cd/upgrading/_category_.json
> +        "position": "300",
You need to move the "position" field up one  level, out of "customProps", otherwise it will have no effect. I usually place it right after "label".

2023-01-12 23:31 UTC, douglas-j-bothwell commented on docs/continuous-delivery/onboard-cd/upgrading/upgrade-nextgen-cd.md
> +Harness provides out of the box Canary, Blue Green, and Rolling Deployment capabilities for any tech stack.
Suggest "Harness provides out-of-the-box Canary, Blue/Green, and Rolling deployment capabilities for any tech stack."

2023-01-12 23:31 UTC, douglas-j-bothwell commented on docs/continuous-delivery/onboard-cd/upgrading/upgrade-nextgen-cd.md
> +- We now support pipelines as templates you can share across various projects.
"templates that you can share"

2023-01-12 23:31 UTC, douglas-j-bothwell commented on docs/continuous-delivery/onboard-cd/upgrading/upgrade-nextgen-cd.md
> +- Harness GitOps delivers a fully managed GitOps experience to allows teams to scale implementations quickly and spend less time managing environments.
that allows teams

2023-01-12 23:31 UTC, douglas-j-bothwell commented on docs/continuous-delivery/onboard-cd/upgrading/upgrade-nextgen-cd.md
> +- Enforce policies at when pipelines are saved or run.
Enforce policies when pipelines....

2023-01-13 01:30 UTC, michaelcretzman commented
incorporated Doug's suggestions. We're good to merge.

2023-01-13 01:30 UTC, merged