SRM dashboards'
harness/developer-hub pull request #3399
Opened 2023-09-20 18:39 UTC by SudheendraKatte

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-09-20 18:58 UTC, SudheendraKatte commented
@shankaranandh @deepak-harness , please review and provide comments.

2023-09-20 19:58 UTC, brian-f-harness approved these changes
LGTM. Left a few minor suggestions.

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-intro.md
> +   The dashboard list is displayed, that includes the following pre-configured Service Reliability dashboards:
```suggestion
   The dashboard list is displayed, which includes the following pre-configured Service Reliability dashboards:
```

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-intro.md
> +For a complete guide to Harness dashboards, go to [Dashboards](https://developer.harness.io/docs/category/dashboards-1).
```suggestion
For a complete guide to Harness dashboards, go to [Dashboards](/docs/category/dashboards-1).
```

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-intro.md
> +1.	In the dashboard list, locate the dashboard you wish to explore and select it. The selected dashboard opens, displaying the relevant metrics and data. For example, if you want to view the SLO Heal
```suggestion
- In the dashboard list, locate the dashboard you wish to explore and select it. The selected dashboard opens, displaying the relevant metrics and data. For example, if you want to view the SLO Health dashboard, simply select it in the list.
```

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-intro.md
> +To view the SRM dashboards, follow these steps:
```suggestion
To view the SRM dashboards, do the following:
```

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-intro.md
> +1.	In the dashboard list, locate the dashboard you wish to explore and select it. The selected dashboard opens, displaying the relevant metrics and data. For example, if you want to view the SLO Heal
I think when there's only one item in a list/steps, we use a bullet

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-health.md
> +   The dashboard list is displayed, that includes the default SLO Health and SLO History dashboards.
```suggestion
   The dashboard list is displayed, which includes the default SLO Health and SLO History dashboards.
```

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-intro.md
> +<docimage path={require('./static/srm-dashboards.png')} />
```suggestion
   <docimage path={require('./static/srm-dashboards.png')} />
```

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-health.md
> +[Health Status Summary tile](#health-status-summary-tile)
```suggestion
- [Health Status Summary tile](#health-status-summary-tile)
```

2023-09-20 19:58 UTC, brian-f-harness commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-health.md
> +- **Environment name**: The environment where the SLO is applied. For Example, production, Terraform, and so on.
```suggestion
- **Environment name**: The environment where the SLO is applied. For example, production, Terraform, and so on.
```

2023-09-21 06:51 UTC, SudheendraKatte commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-intro.md
> +1.	In the dashboard list, locate the dashboard you wish to explore and select it. The selected dashboard opens, displaying the relevant metrics and data. For example, if you want to view the SLO Heal
Thanks for pointing out!

2023-09-21 09:05 UTC, Varsha-lalwani requested changes

2023-09-21 09:05 UTC, Varsha-lalwani commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-health.md
> +
You can add that you can also hover over the  graph and get the count.

2023-09-21 09:05 UTC, Varsha-lalwani commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-health.md
> +- **SLO percentage**: This shows how close you are to achieving your SLO. It's a measure of how well you're meeting your target.
This is SLI percentage.
There is one more field SLO Target, which is basically SLO target percentage what user defined.

2023-09-21 09:05 UTC, Varsha-lalwani commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-history.md
> +- **SLO percentage**: Measure of how well you're meeting your target. This shows how close you are to achieving your SLO.
Rename it to SLO Target

2023-09-21 09:05 UTC, Varsha-lalwani commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-history.md
> +
there is no health status summary tile in history

2023-09-21 10:40 UTC, SudheendraKatte commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-health.md
> +- **SLO percentage**: This shows how close you are to achieving your SLO. It's a measure of how well you're meeting your target.
@Varsha-lalwani , the SLO Health dashboard doesn't have the SLO Target and SLI Percentage fields. They are part of the SLO History dashboard.

2023-09-21 11:53 UTC, SudheendraKatte commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-history.md
> +- **SLO percentage**: Measure of how well you're meeting your target. This shows how close you are to achieving your SLO.
Addressed

2023-09-21 11:53 UTC, SudheendraKatte commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-health.md
> +
Not documented as the functionality is intuitive.

2023-09-21 11:53 UTC, SudheendraKatte commented on docs/service-reliability-management/srm-dashboard/srm-dashboard-slo-history.md
> +
Removed

2023-09-21 13:58 UTC, Varsha-lalwani approved these changes

2023-09-21 19:23 UTC, merged