Update install-a-docker-delegate.md
harness/developer-hub pull request #347
Opened 2023-01-13 01:03 UTC by kat-enos

Post-migration cleanup + small editing changes -- a few image corrections to be made

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*.  Small changes/housekeeping -- post-migration with edits thrown in

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-13 12:39 UTC, deepakbolangady requested changes

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +You can install Docker Delegate while setting up a connector or independent of another process.
I'm not sure that the clauses joined by the "or" are similar (or parallel) in nature. Also, "as part of" might have been better than "while"? The "while" does not suggest that installing Docker Delegate is part of the connector configuration workflow (or the workflow for any entity). They might still be independent of each other; just performed in parallel. How about "Various workflows for configuring Harness entities, such as those for configuring connectors, include a step for installing Docker Delegate. However, you can also install Docker Delegate beforehand and then reference them in those workflows." (I'm going wild here but please consider this sample text. Also, I felt this is a classic case of what the product provides vs. what the user can do, so I modified the wording accordingly.)

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +You can install Docker Delegate while setting up a connector or independent of another process.
Subsequent text suggests that the connector workflow is the only workflow that includes this installation option. If my recommendation is good, please modify it as needed. Thanks.

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +After you select **New Delegate** on the Delegate page or while setting up a connector, the delegate selection page appears.
```suggestion
After you select **New Delegate** on the Delegate page, or when you are setting up a connector, the delegate selection page appears.
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +**Do not run delegates with the same name in different clusters.** See [Troubleshooting](../../../troubleshooting/troubleshooting-nextgen.md).Add Tags to the Delegate. By default, Harness adds a tag
```suggestion
**Do not run delegates with the same name in different clusters.** See [Troubleshooting](../../../troubleshooting/troubleshooting-nextgen.md). Add tags to the delegate. By default, Harness adds a tag that uses the name you enter. To add more, type them in and press **Enter**.
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +**Do not run delegates with the same name in different clusters.** See [Troubleshooting](../../../troubleshooting/troubleshooting-nextgen.md).Add Tags to the Delegate. By default, Harness adds a tag
* "Type them in" > "type them in <some box>" (just thinking why we wrote "in". Might be colloquial too, in which case you don't need to enter a box name or something else. 
*  **Do not run delegates with the same name in different clusters.** > Do we need bold text for emphasis? Or can we use a note instead? Also, does that mean we can run delegates with the same name on the same cluster? Or should we not have delegates with the same name at all?

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +If you system already has a delegate image, Harness doesn't pull the latest image when you run `docker-compose`. Simply run `docker pull harness/delegate` to pull the latest. Now you can see the YAML
"If your"

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +The delegate installs. Type `docker ps` to see the container:
"is installed"?

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +In the delegate wizard, click **Verify** and Harness will verify that it is receiving heartbeats from the delegate.
"for Harness to verify"
Alternatively "click Verify to verify that Harness is receiving ..." (since the user will want to verify, not Harness itself)

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +That's it. The delegate is installed and registered and connected.
```suggestion
That's it. The delegate is installed, registered, and connected.
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `ACCOUNT_ID` | The Harness account ID for the account where this Delegate will attempt to register. | ```- ACCOUNT_ID=H5W8i2828282828Xg```|
```suggestion
| `ACCOUNT_ID` | The ID of the Harness account with which the Delegate attempts to register. | ```- ACCOUNT_ID=H5W8i2828282828Xg```|
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `DELEGATE_STORAGE_URL` | The URL where published delegate jars are stored. | ```- name: DELEGATE_STORAGE_URL  value: https://app.harness.io```|
```suggestion
| `DELEGATE_STORAGE_URL` | The URL at which published delegate jars are stored. | ```- name: DELEGATE_STORAGE_URL  value: https://app.harness.io```|
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `DELEGATE_NAME` | The name of the delegate. This is the name that appears in Harness when the delegate is registered. You can automate delegate creation by omitting the name, and then have a script
The "you can automate" sentence is long. Can we split it?

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `NEXT_GEN` | Indicates that this delegate will register in Harness NextGen(`true`) or FirstGen(`false`). | ```- name: NEXT_GEN  value: "true"```|
```suggestion
| `NEXT_GEN` | If `true, the delegate registers with Harness NextGen. If `false`, the delegate registers with Harness FirstGen. | ```- name: NEXT_GEN  value: "true"```|
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `DELEGATE_TASK_LIMIT` | The maximum number of tasks the delegate can perform at once. All of the operations performed by the delegate are categorized as different types of tasks. | ```- name: DELEG
at once > concurrently?

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `DELEGATE_PROJECT_IDENTIFIER` | The Harness project [identifier](../../20_References/entity-identifier-reference.md) where the delegate will register. Delegates at the account or Org-level do not h
```suggestion
| `DELEGATE_PROJECT_IDENTIFIER` | The Harness project [identifier](../../20_References/entity-identifier-reference.md) with which the delegate registers. Delegates at the account or org level do not have a value for this variable. | ```-name: DELEGATE_PROJECT_IDENTIFIER  value: "myproject"```|
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `DELEGATE_PROJECT_IDENTIFIER` | The Harness project [identifier](../../20_References/entity-identifier-reference.md) where the delegate will register. Delegates at the account or Org-level do not h
Also, prefer "organization" to "org".

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `INIT_SCRIPT` | You can run scripts on the delegate using `INIT_SCRIPT`. For example, if you wanted to install software on the delegate pod, you can enter the script in `INIT_SCRIPT` and then apply
```suggestion
| `INIT_SCRIPT` | You can run scripts on the delegate by using `INIT_SCRIPT`. For example, if you want to install software on the delegate pod, you can enter the script in `INIT_SCRIPT` and then apply the delegate YAML. A multiline script must follow the YAML `spec` for [literal scalar style](https://yaml.org/spec/1.2-old/spec.html#id2795688). See [Run Scripts on Delegates](../delegate-guide/run-scripts-on-delegates.md). | ```- INIT_SCRIPT=  echo hello world!```|
```

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `INIT_SCRIPT` | You can run scripts on the delegate using `INIT_SCRIPT`. For example, if you wanted to install software on the delegate pod, you can enter the script in `INIT_SCRIPT` and then apply
* Good to expand on what `INIT_SCRIPT` is. For example, "the `INIT_SCRIPT` environment variable" (for example)
* "you can enter the script" > should that be "you can enter the path to the script"? (ignore if my question is invalid)

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `DELEGATE_DESCRIPTION` | The description added to the delegate in Harness Manager or YAML before registering. It appears in the delegate details page in the Harness Manager. | ```- name: DELEGATE_D
"or in the delegate YAML"?

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `USE_CDN` | Makes the delegate use a CDN for new versions. | ```- name: USE_CDN  value: "true"```|
Should we expand CDN?

2023-01-13 12:39 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +| `VERSION_CHECK_DISABLED` | By default, the delegate always checks for new versions (via the Watcher). | ```- name: VERSION_CHECK_DISABLED  value: "false"```|
via > through?

2023-01-16 20:39 UTC, kat-enos commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +Harness Delegate is a worker process you run in your deployment target environment, such as your local network, VPC, or cluster. The delegate connects artifact, infrastructure, collaboration, verific
Can't add a comma there. It wouldn't be grammatical since it separates "verification" from "and other providers".

2023-01-16 20:54 UTC, kat-enos commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +* Default 768MB RAM. There is a cap of 768MB per delegate, but when the delegate is updating there might be two delegates running. Hence, the minimum is 1.5 GB. Ensure that you provide the minimum me
There are a lot of editorial changes I would like to make to the document but the main goal of the changes was to fix problems that occurred in the migration so I make only limited copy edits.

Typically I avoid the use of "its" and I would write around some of the problems you've noticed but wouldn't be comfortable assuming that when two delegates are running, one of which is being updates, that the tasks of the first delegate are performed by the second and that we consider the second temporary. It may be implied. But that's the kind of thing that I'd probably want to have reviewed.

2023-01-16 21:01 UTC, kat-enos commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +Docker Delegate can be installed at the Harness account, Organization, or Project level.
The word "scope" doesn't match the current preposition "at". Programming elements are scoped or given a specific scope. I think the writer was talking about account permissions in a hierarchy of user permissions. Scope is often associated with namespace. I think it's fine as written and must assume that it was technically reviewed when it was written.

2023-01-23 20:26 UTC, kat-enos commented on docs/platform/2_Delegates/delegate-install-docker/install-a-docker-delegate.md
> +* Default 768MB RAM. There is a cap of 768MB per delegate, but when the delegate is updating there might be two delegates running. Hence, the minimum is 1.5 GB. Ensure that you provide the minimum me
FYI, I avoid the use of the "its" because it can be vague.

2023-01-24 23:25 UTC, kat-enos commented
Closed this PR to see if closing and reopening will fix the conflicts that exist with a file version that was moved after this PR was originally opened.

2023-02-16 22:25 UTC, closed without merging