feat: [CDS-76188]: Shell scripts do not use the same delegate as the deployment
harness/developer-hub pull request #3471
Opened 2023-09-26 07:03 UTC by sarthakkasat

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-09-26 07:25 UTC, yogesh-chauhan requested changes

2023-09-26 07:25 UTC, yogesh-chauhan commented on docs/first-gen/continuous-delivery/kubernetes-deployments/connect-to-your-target-kubernetes-platform.md
> +If you use a Delegate installed outside of the target cluster, any scripts in your Pipeline need to use the `${HARNESS_KUBE_CONFIG_PATH}` expression to reference the path to a Harness-generated kubec
1. typo:
the a checkbox -> the checkbox

2. Lets quote "Include Infrastructure Selectors"
3. to use a Delegate installed outside of the target cluster: outside -> inside. 
4. Infact, lets say that this will force the shell script to run on a delegate with the selectors defined by the k8s connector defined in the infrastructure definition

2023-09-26 08:33 UTC, sarthakkasat commented on docs/first-gen/continuous-delivery/kubernetes-deployments/connect-to-your-target-kubernetes-platform.md
> +If you use a Delegate installed outside of the target cluster, any scripts in your Pipeline need to use the `${HARNESS_KUBE_CONFIG_PATH}` expression to reference the path to a Harness-generated kubec
Done, also added these changes in shell script step

2023-09-27 13:19 UTC, yogesh-chauhan approved these changes

2023-09-27 16:15 UTC, deepakbolangady approved these changes
Made some style/language edits and corrected a typo in the vicinity of this commit.

2023-09-27 17:20 UTC, merged