v1 draft regex support for Artifactory tags CDS-77239
harness/developer-hub pull request #3581
Opened 2023-09-29 22:27 UTC by douglas-j-bothwell

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-10-03 19:26 UTC, puthrayaharness requested changes

2023-10-03 19:26 UTC, puthrayaharness commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +1. In **Repository**, enter the repo name. If the full path is `docker-remote/library/mongo/3.6.2`, you would enter `docker-remote`.
Please use a non-docker/generic repository & file with a full path for an example. It is misleading otherwise

2023-10-03 19:26 UTC, puthrayaharness commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +  This option is behind the feature flag `CD_NG_DOCKER_ARTIFACT_DIGEST`. Contact [Harness Support](mailto:support@harness.io) to enable the feature.
This FF is not present anymore; please feel free to remove it from here.

2023-10-03 19:26 UTC, puthrayaharness commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +6. To specify an image digest, use **Digest** and the unique identifier for the image you want to use.  Specifying an image by tag and digest (rather than tag alone) is useful when you want to deploy
It's not relevant for generic. It is valid for Docker only

2023-10-04 03:16 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
>  5. In **Service Definition**, select **Kubernetes**.
Kubernetes doesn't support 'Generic' format. Deployment types like WinRm, SSH etc support it.

2023-10-04 03:20 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +8. In **Artifactory Repository**, select of create an Artifactory Connector that connects to the Artifactory account where the repo is located. Click **Continue**. The **Artifact Details** settings a
I think point 8 is about connector but it is labelled as 'Artifact Repository'

2023-10-04 03:21 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +8. In **Artifactory Repository**, select of create an Artifactory Connector that connects to the Artifactory account where the repo is located. Click **Continue**. The **Artifact Details** settings a
Also spelling is incorrect. I think it should be 'select or create' in place of 'select of create'

2023-10-04 03:23 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
'Repository URL' appear after 'Artifact Path'

2023-10-04 03:24 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
We have not documented 'Tag Regex'

2023-10-04 03:27 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +  This option is behind the feature flag `CD_NG_DOCKER_ARTIFACT_DIGEST`. Contact [Harness Support](mailto:support@harness.io) to enable the feature.
@puthrayaharness This FF is GA but not deleted yet

2023-10-04 03:32 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +
Details are incorrectly matched in image.
iis-website- Repository
todolist-v3.0.zip - Artifact Path
Directory is root directory ('/') as Artifact is directly present in Repository.

2023-10-04 03:34 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +
Can we remove 'Artifact Path Filter' mark from image? As it would mislead between 'Artifact Filter' and 'Artifact Path Filter'.
We may document example in field description.

2023-10-04 03:36 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +
Can we have a different example image where Artifact is present in a directory inside Repository? It would bring more clarity.

2023-10-04 03:38 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +3. Select the method for specifying the artifacts you want to deploy:
Description of 'Artifact Directory' is mentioned in 'If specifying via directory' section below

2023-10-04 03:41 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - **Artifact Filter** Use an expression to specify the path. Useful if you want to fetch multiple artifacts in different paths.
Can we use 'Useful if you want to fetch artifacts from different paths' ? as we ultimately select one artifact from dropdown

2023-10-04 03:48 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +        You can use an expression to specify multiple artifacts. For example, suppose your service has a front end and a back end, and you store the latest artifacts in a `/latest` subfolder, like th
I think this description belongs only to 'Artifact Path Filter'. Can we make this more clear by labelling name of field?

2023-10-04 03:50 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - If specifying via directory:
In place of directory can we use field name 'Artifact Directory' for clear distinction?

2023-10-04 03:51 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - If specifying via filter, enter an expression that matches the tag of the artifacts you want to fetch. The following expressions are supported:
In place of 'filter' can we use field name 'Artifact Filter' for clear distinction?

2023-10-04 03:53 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - If specifying via filter, enter an expression that matches the tag of the artifacts you want to fetch. The following expressions are supported:
Concept of tag is not present for Generic format. This expression is to match the artifact path following directory.

2023-10-04 03:55 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - If specifying via filter, enter an expression that matches the tag of the artifacts you want to fetch. The following expressions are supported:
Below expressions are examples to help user construct them. They may construct different combinations and not restricted to these.
Can we update 'The following expressions are supported' to imply the same?

2023-10-04 14:19 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +1. In **Repository**, enter the repo name. If the full path is `docker-remote/library/mongo/3.6.2`, you would enter `docker-remote`.
Updated in local branch:

1. In **Repository**, enter the repo name. If the full path is `my-apps/myticketservice/1.0/ticket-service-1.0.jar`, you would enter `my-apps`.
2. In **Artifact Directory**, enter the path to the artifacts. If the full path is `my-apps/myticketservice/1.0/ticket-service-1.0.jar`, you would enter `/myticketservice/1.0`.

2023-10-04 14:20 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +  This option is behind the feature flag `CD_NG_DOCKER_ARTIFACT_DIGEST`. Contact [Harness Support](mailto:support@harness.io) to enable the feature.
Sounds like I should keep the FF for now....

2023-10-04 14:22 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +6. To specify an image digest, use **Digest** and the unique identifier for the image you want to use.  Specifying an image by tag and digest (rather than tag alone) is useful when you want to deploy
Removed this step in the local branch.

2023-10-04 14:26 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
>  5. In **Service Definition**, select **Kubernetes**.
Updated in local branch:

In **Service Definition**, select the deployment type.

2023-10-04 14:31 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +8. In **Artifactory Repository**, select of create an Artifactory Connector that connects to the Artifactory account where the repo is located. Click **Continue**. The **Artifact Details** settings a
Updated in local branch:

8. In **Artifactory Connector**, select or create an Artifactory connector that connects to the Artifactory account where the repo is located. Click **Continue**. The **Artifact Details** settings appear.

2023-10-04 15:05 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
Updated in local branch:

1. In **Repository**, enter the repo name. If the full path is `docker-remote/library/mongo/3.6.2`, you would enter `docker-remote`.
2. In **Artifact/Image Path**, enter the path to the artifact. If the full path is `docker-remote/library/mongo/3.6.2`, you would enter `library/mongo`.
3. In **Repository URL**, enter the URL from the `docker login` command in Artifactory's **Set Me Up** settings.

2023-10-04 15:18 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +3. Select the method for specifying the artifacts you want to deploy:
Removed this step in local branch

2023-10-04 15:20 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - **Artifact Filter** Use an expression to specify the path. Useful if you want to fetch multiple artifacts in different paths.
Updated in local branch.

2023-10-04 15:21 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - If specifying via directory:
Updated in local branch: 

- If you selected **Artifact Directory**:
     1. In **Artifact Directory**, enter the path to the artifacts. If the full path is `my-apps/myticketservice/1.0/ticket-service-1.0.jar`, you would enter `/myticketservice/1.0`.

2023-10-04 18:50 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +
Updated graphic...used `cf-tutorial` as the example repo...might not be a "real-world" example but this repo seems safe to include in a screenshot.

2023-10-04 18:51 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +        You can use an expression to specify multiple artifacts. For example, suppose your service has a front end and a back end, and you store the latest artifacts in a `/latest` subfolder, like th
Now reads:

Specify the the value or the regex for the artifacts.

If you selected Regex, enter the Artifact Path Filter for the artifacts you want to fetch. For example, suppose your service has a front end and a back end, and you store the latest artifacts in a /latest subfolder, like this: /myService/latest/front-service.zip /myService/latest/back-service.zip To fetch both artifacts, you can specify /myService for the artifact directory and latest/*.zip for the artifact path filter.

2023-10-04 18:53 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +   - If specifying via filter, enter an expression that matches the tag of the artifacts you want to fetch. The following expressions are supported:
@Abhishek-CDC Included these edits, plus a note about the artifact-filter limitations.

- `folder/*/*` : Fetch all artifacts from sub-directories under folder.

- `folder/*/*.zip` : Fetch all .zip artifacts from sub-directories under folder.

- `folder*/*` : Fetch all artifacts from subdirectories under folder*.

NOTE
You cannot apply a filter that finds BOTH artifacts in a folder AND all subdirectories under that folder. Thus `folder/*` finds artifacts in `folder` but no subdirectories, and `folder/*/*` finds artifacts in all subdirectories but not in `folder`.

2023-10-05 04:33 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +    You can use a regex to select the most recent image. Suppose you have a set of images with tags `3.1.1`, `3.1.2`, `3.1.3.1`, `3.1.3.2`, and `3.1.3.4`. Select **Regex**, then set **Tag Regex** `3.
In place of "You can use a regex to select the most recent image" we may use "You can use a regex to select image based on pattern"
AND
In place of "to select the most recent image" we may use "to select the most recent image with prefix 3.1"

2023-10-05 04:34 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +    You can use a regex to select the most recent image. Suppose you have a set of images with tags `3.1.1`, `3.1.2`, `3.1.3.1`, `3.1.3.2`, and `3.1.3.4`. Select **Regex**, then set **Tag Regex** `3.
Because in case of most recent image they can have '*' which means consider all. If a pattern is specified than recent among those images which matches pattern

2023-10-05 04:36 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +
in place of '/org/springframework/boot/spring-boot-hello/1.0/' we can use 'org/springframework/boot/spring-boot-hello/1.0'
'/' is not required in prefix and suffix

2023-10-05 04:39 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +     3. Specify the the value or the regex for the artifacts.
This 3 point is already implied in 2 point.
Also 'the' is appearing 2 times consecutively

2023-10-05 04:41 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +     2. Set **Artifact Details** to **Value** or **Regex** (useful if you want to fetch multiple artifacts).
can we remove 'useful if you want to fetch multiple artifacts'? as it will be fetching one artifact based on pattern.
This can be similar to docker like 'You can use a regex to select the most recent image.'

2023-10-05 04:46 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +      - `folder*/*` : Fetch all artifacts from subdirectories under folders with names that match `folder*`.
folder*/* description is incorrect.
It will fetch artifacts from all directories/sub-directories matching folder*
Example:
folder
folder123
folder/x/y/z

2023-10-05 04:53 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +      - `folder*/*` : Fetch all artifacts from subdirectories under folders with names that match `folder*`.
Similarly examples for 'folder/*/*':
folder/folder1
folder/folder1/folder2
folder/folder1/folder2/folder3

2023-10-05 04:54 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +     1. In **Artifact Directory**, enter the path to the artifacts. If the full path is `my-apps/myticketservice/1.0/ticket-service-1.0.jar`, you would enter `/myticketservice/1.0`.
we may use 'myticketservice/1.0' in place of '/myticketservice/1.0'

2023-10-05 12:42 UTC, douglas-j-bothwell commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +     3. Specify the the value or the regex for the artifacts.
Removed the extra "the" but leaving in step 3. Step 3 might be implied in step 2, but they're technically two separate steps.

2023-10-05 14:45 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +      - `folder/*/*` : Fetch all artifacts from all directories/sub-directories matching `folder`, for example `folder/folder1`, `folder/folder1/folder2`, `folder/folder1/folder2/folder3`, etc.
It should be "Fetch all artifacts from all directories/sub-directories under `folder`"

2023-10-05 14:46 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +      - `folder/*/*.zip` : Fetch all `.zip` artifacts from sub-directories under `folder`.
It should be "Fetch all `.zip` artifacts from all directories/sub-directories under folder"

2023-10-05 14:48 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +      - `folder*/*` : Fetch all artifacts from subdirectories under `folder` with names that match `folder*`, for example `folder`, `folder123`, `folder/x/y/z`, etc.
It should be "Fetch all artifacts from directories/sub-directories that matches `folder*`"

2023-10-05 14:51 UTC, Abhishek-CDC commented on docs/continuous-delivery/x-platform-cd-features/services/artifact-sources.md
> +      - `folder*/*` : Fetch all artifacts from subdirectories under `folder` with names that match `folder*`, for example `folder`, `folder123`, `folder/x/y/z`, etc.
As directories/sub-directories need not to be under 'folder'

2023-10-05 16:33 UTC, Abhishek-CDC submitted a review, later dismissed

2023-10-05 16:40 UTC, Abhishek-CDC approved these changes

2023-10-05 17:41 UTC, merged