feat: Added the enable scorecard docs for IDP
harness/developer-hub pull request #3620
Opened 2023-10-04 13:28 UTC by Debanitrkl

# Harness Developer Pull Request
Added the docs for scorecards in IDP

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +description: Measure software maturity and best practices
```suggestion
description: Measure software maturity and enforce best practices
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +Few steps like `add proxy` for plugin configuration will be obsolete in the upcoming release and you will be required to add scorecards under the `Scorecard` tab under `Admin` with adequate checks.
```suggestion
Few steps like `add proxy` for plugin configuration and layout update will be obsolete in the upcoming releases. They will be handled automatically.
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +1. #### Enable Sccorecards
```suggestion
1. #### Enable Scorecards
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +    - **Add Proxy to Harness ci-cd plugin** as mentioned below by navigating to the `Plugin` tab under `Admin` section in the left nav bar.
CI, CD, IDP, API, JSON, YAML, etc. are all acronyms. They'll always be all caps when used in a sentence. :)

```suggestion
    - **Add Proxy to Harness CI/CD plugin** as mentioned below by navigating to the `Plugin` tab under `Admin` section in the left nav bar. 
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +    - Harness-Account
```suggestion
    allowedHeaders:
      - authorization
      - Harness-Account
```

There should be an indentation here, right? @jenil-harness @sandeepa-kv-jois ?

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +Scorecard is available in IDP as an independent entity as well as in overview tab as illustrated below. The entity tab contains detailed comprehensive information as shown in the image under [overvie
```suggestion
Scorecard has two main UI components which are developer facing and lives in the Catalog - 1. A small "Card" for the Overview page with the scores and, 2. A "Tab" view with details of the checks and how the score got computed. This is illustrated below. The Tab view contains detailed comprehensive information as shown in the image under [overview](/docs/internal-developer-portal/features/scorecard#overview)
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +    - Go to the `Layout` section in IDP `Admin`, and select the **entity kind** for which you want to add scorecards.
```suggestion
    - Go to the `Layout` section in IDP `Admin`, and select "Service" or any other kind of catalog entity for which you want to add scorecards.
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +5. #### Removing/Disabling Scorecards
```suggestion
### Removing/Disabling Scorecards
```

This isn't really a step of the enable flow right? :)

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +    - Comment out the lines added under `Layout` tab to remove the scorecard.
```suggestion
    - Comment out the Scorecard related lines added under `Layout` tab as mentioned above to remove the scorecard components from the Catalog pages. 
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +    - Another way to **disable** the scorecard is to convert the same into draft post publishing and it will be disabled as illustrated below.
```suggestion
    - Another way to **disable** the scorecards feature is to change the status of all the scorecards you have to "draft". This will ensure that the computation will not run, and will not be shown to the developer.
```

2023-10-04 18:51 UTC, OrkoHunter commented on docs/internal-developer-portal/features/scorecard.md
> +<docimage width="1750vw" path={require('../../internal-developer-portal/features/static/remove-scorecard.png')}/>
```suggestion
<docimage width="100vw" path={require('../../internal-developer-portal/features/static/remove-scorecard.png')}/>
```

The `vw` and `vh` units are 0-100. 50vw means, half of available window width. 50vh means half of the loaded page height. https://www.w3schools.com/cssref/css_units.php

2023-10-05 04:37 UTC, Debanitrkl commented on docs/internal-developer-portal/features/scorecard.md
> +    - Harness-Account
I have used the example as mentioned in the Layout for CI/CD plugin and I don't think there's any indentation

2023-10-05 04:41 UTC, sandeepa-kv-jois commented on docs/internal-developer-portal/features/scorecard.md
> +    - **Add Proxy to Harness ci-cd plugin** as mentioned below by navigating to the `Plugin` tab under `Admin` section in the left nav bar.
We do not have to mention this info. Proxy config will be autopopulated in the next week's release. Currently, CI-CD plugin configs are non-editable in customer accounts unless we turn ON FF to edit.

2023-10-05 04:44 UTC, Debanitrkl commented on docs/internal-developer-portal/features/scorecard.md
> +    - **Add Proxy to Harness ci-cd plugin** as mentioned below by navigating to the `Plugin` tab under `Admin` section in the left nav bar.
We are adding the same info as `Few steps like add proxy for plugin configuration will be obsolete in the upcoming release` and asking the users to enable this FF as well `IDP_ENABLE_EDIT_HARNESS_CI_CD_PLUGIN`.

2023-10-05 04:44 UTC, sandeepa-kv-jois requested changes
We do not have to mention Proxy info. Proxy config will be autopopulated in the next week's release. Currently, CI-CD plugin configs are non-editable in customer accounts unless we turn ON FF to edit.

2023-10-05 16:05 UTC, merged