FAQ of the week
harness/developer-hub pull request #3737
Opened 2023-10-15 20:09 UTC by AnjaliSiwach

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-10-16 07:51 UTC, adiyaar24 requested changes

2023-10-16 07:51 UTC, adiyaar24 commented on kb/platform/harness-platform-faqs.md
> +You can look at the Delegate Service section of this documentation, [here](https://harness.atlassian.net/wiki/spaces/HCE/pages/21076181398/Local+Development+Setup+for+Harness+Chaos?atlOrigin=eyJpIjoi
This is an Internal question and there is no point of putting this to customer , please remove this

2023-10-16 07:51 UTC, adiyaar24 commented on kb/platform/harness-platform-faqs.md
> +The user can directly login using deep link [here](https://app.harness.io/ng/account/y3fpQpCfRQC8uakPcpfp2Q/main-dashboard)
We can't provide this , this is customer account ID , make it generic by replacing the accountID

`https://app.harness.io/ng/account/<AccountID>/main-dashboard`

2023-10-16 07:53 UTC, adiyaar24 requested changes

2023-10-16 07:53 UTC, adiyaar24 commented on kb/platform/harness-platform-faqs.md
> +We support workload identify for Google SM.
It should be Google Secret Manager not just `SM`

2023-10-16 07:53 UTC, adiyaar24 commented on kb/platform/harness-platform-faqs.md
> +They can use alphanumeric but it should not start or end with number.
`Yes you can use alphanumerics , but it should not start or end with a number`

2023-10-16 07:53 UTC, adiyaar24 commented on kb/platform/harness-platform-faqs.md
> +This could happen when manager iterator is not running, there is a limit of 5000 delegate tasks at a time per account, but if iterator is not running, it will get deleted automatically and this error
it will `not` get deleted automatically and this error arises.

2023-10-16 08:02 UTC, AbhinandanParashar commented on kb/platform/harness-platform-faqs.md
> +They can use alphanumeric but it should not start or end with number.
Instead of _They can use alphanumeric but it should not start or end with number_. use You can use alphanumeric but it should not start or end with number.

2023-10-16 08:05 UTC, AbhinandanParashar commented on kb/platform/harness-platform-faqs.md
> +This feature is currently available in CG, the customer can use `Restrict users to email domains` feature and only and set their email domain only. Also, there is a FF `LIMITED_ACCESS_FOR_HARNESS_USE
instead _the customer can use_ use  _you can use_

2023-10-17 09:10 UTC, deepanshuHarness approved these changes

2023-10-17 09:11 UTC, merged