Cretzman multiple bugs 01 17 2023
harness/developer-hub pull request #379
Opened 2023-01-17 20:07 UTC by michaelcretzman

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issues
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

- CDS-50596	Reference expressions for output from Jenkins vs Shell Script
- Bug	CDS-48449	Update Docs for ServiceV2 and Env Runtime Input Support
- Bug	CDS-48459	Update Terraform version on docs
- Bug	CDS-47102	Update the docs with the Cloudformation Tags syntax - user made an error when configuring cloudformation with tags

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-17 20:19 UTC, thisrohangupta approved these changes
The Changes for Cloudformation looks good.

2023-01-18 03:11 UTC, Debanitrkl approved these changes

2023-01-18 17:25 UTC, douglas-j-bothwell submitted a review, later dismissed
A few typos but otherwise looks good!

2023-01-18 17:25 UTC, douglas-j-bothwell commented on docs/continuous-delivery/cd-execution/cd-general-steps/run-jenkins-jobs-in-cd-pipelines.md
>  For Harness to capture Jenkins environment variables, your Jenkins configuration requires the [EnvInject Plugin](https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin). The plugin does not provide
```suggestion
For Harness to capture Jenkins environment variables, your Jenkins configuration requires the [EnvInject Plugin](https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin). The plugin does not provide full compatibility with the Pipeline plugin. See [Known Incompatibilities](https://wiki.jenkins.io/display/JENKINS/EnvInject+Plugin#EnvInjectPlugin-Knownincompatibilities) from Jenkins. Harness captures certain environment variables from the Jenkins build.
```

2023-01-18 17:25 UTC, douglas-j-bothwell commented on docs/continuous-delivery/cd-execution/cd-general-steps/run-jenkins-jobs-in-cd-pipelines.md
> +You can reference this Job information is subsequent steps in your pipeline or another Pipeline.
```suggestion
You can reference this Job information in subsequent steps in your pipeline or in another pipeline.
```

2023-01-18 17:25 UTC, douglas-j-bothwell commented on docs/continuous-delivery/cd-execution/cd-general-steps/run-jenkins-jobs-in-cd-pipelines.md
> +To reference it in another pipeline, you would use the full pipeline path to the build information. For example, `<+pipeline.stages.[stage_Id].spec.execution.steps.[step_Id].build.executionStatus>`.
```suggestion
To reference the Job information in another pipeline, use the full pipeline path to the build information. For example, `<+pipeline.stages.[stage_Id].spec.execution.steps.[step_Id].build.executionStatus>`.
```

2023-01-18 17:25 UTC, douglas-j-bothwell commented on docs/continuous-delivery/cd-execution/cd-general-steps/using-shell-scripts.md
>  At deployment runtime, Harness will evaluate the expression and the variable will contain its output.
```suggestion
At deployment runtime, Harness evaluates the expression and the variable contains its output.
```

2023-01-20 17:24 UTC, brettzu requested changes

2023-01-20 17:24 UTC, brettzu commented on docs/continuous-delivery/cd-execution/cd-general-steps/run-jenkins-jobs-in-cd-pipelines.md
> +To reference the Job information in another pipeline, use the full pipeline path to the build information. For example, `<+pipeline.stages.[stage_Id].spec.execution.steps.[step_Id].build.executionSta
This is to reference in another stage of the same pipeline, not in another pipeline.

2023-01-20 17:24 UTC, brettzu commented on docs/continuous-delivery/cd-execution/cd-general-steps/using-shell-scripts.md
> +Enter a name for the step. An Id is generated. This Id identifies the step and is used in variable expressions. For example, if the Id is **Shell Script**, the expression might be `<+execution.steps.
It works either way. The "execution." part seems to be optional.

2023-01-20 17:24 UTC, brettzu commented on docs/continuous-delivery/cd-execution/cd-general-steps/using-shell-scripts.md
> +	+ `<+execution.steps.[step_id].output.outputVariables.[output_variable_name]>`
The "execution." is optional, so either way works. Do we want to mention both or only one form?

2023-01-20 17:24 UTC, brettzu commented on docs/continuous-delivery/cd-execution/cd-general-steps/using-shell-scripts.md
> +echo "my secret: " <+execution.steps.CreateScript.output.outputVariables.myvar>
execution optional

2023-01-20 17:29 UTC, michaelcretzman commented on docs/continuous-delivery/cd-execution/cd-general-steps/using-shell-scripts.md
> +	+ `<+execution.steps.[step_id].output.outputVariables.[output_variable_name]>`
we should mention only execution. it helps them understand where the variable is evaluated.

2023-01-25 19:05 UTC, michaelcretzman commented
Prasad said I can merge this.

2023-01-25 19:05 UTC, merged