new topic per DOC-2446
harness/developer-hub pull request #387
Opened 2023-01-18 14:36 UTC by douglas-j-bothwell

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ *] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* https://harness.atlassian.net/browse/DOC-2446

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-18 20:39 UTC, r0610205 commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +This topic describes how to override the default behavior and use a private repo instead. You can download the scan images you need, perform your own security checks on the images, upload them to a p
I'd call it private registry instead of private repo

2023-01-18 22:48 UTC, aimurphy requested changes

2023-01-18 22:48 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   Harness maintains a Container Image Registry that is dedicated exclusively to hosting Harness-supported images. You can download your scan images from this registry instead of Docker Hub. To view
```suggestion
   Harness maintains a Container Image Registry that is dedicated exclusively to hosting Harness-supported images. You can download your scan images from this registry instead of Docker Hub. To view the list of images in this registry, enter the following command:
```

2023-01-18 22:48 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   * `runner_registry_image_prefix` = `harness`
If this parameter must be set to `harness`, to avoid confusion with the = character, would it be better to supply the entire code snippet w proper formatting, such as:

`runner_registry_image_prefix: harness`

I see that = is used in other topics, so this is probably something we should discuss WRT future changes to the documentation. There seems to be a mix of colon, equal, and em dash.

2023-01-18 22:48 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +     The supported format is <_domain_>/<_directory_> – for example, `app.harness.io/registry`.
```suggestion
     The supported format is `<_domain_>/<_directory_>` (such as, `app.harness.io/registry`). 
```

I am suggesting code formatting for the format example because you are describing how to format code.
I am suggesting parenthesis and 'such as' to match the structure of the following line.

2023-01-18 22:48 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   * `https_proxy`  —  The hostname and port to use for proxied HTTPS requests
There is inconsistency with use of periods to end lines in this list.

2023-01-18 22:48 UTC, aimurphy commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   If you need to use a proxy server, you can also specify the following:
```suggestion
   If you need to use a proxy server, you must also specify the following: 
```

I'm not clear if these settings are required or optional. 'You can' feels optional and incongruous with your use of 'if you need to' at the beginning of the line. I suggest 'also specify the following' or 'you must also specify the following'.

2023-01-18 22:54 UTC, douglas-j-bothwell reviewed
implement April's edits

2023-01-18 22:54 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   * `http_proxy`	 —  The hostname and port to use for proxied HTTP requests.
```suggestion
   * `http_proxy`	 —  The hostname and port to use for proxied HTTP requests
```

2023-01-18 22:54 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   * `no_proxy`  — A comma -separated list of hosts to bypass the proxy.
```suggestion
   * `no_proxy`  — A comma-separated list of hosts to bypass the proxy
```

2023-01-18 22:58 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   * `runner_registry_image_prefix` = `harness`
This is a good idea @aimurphy. I'll implement this change here and in the rest of the STO docs. 

I'm not sure if this is an issue in other docs outside of STO....

2023-01-18 22:59 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   * `runner_registry_image_prefix` = `harness`
```suggestion
   * `runner_registry_image_prefix : harness`
```

2023-01-18 22:59 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/use-sto/download-images-from-private-registry.md
> +   * `http_proxy`	 —  The hostname and port to use for proxied HTTP requests
```suggestion
   * `http_proxy`  —  The hostname and port to use for proxied HTTP requests
```

2023-01-19 17:44 UTC, aimurphy approved these changes

2023-01-19 17:47 UTC, merged