Update whats-supported.md
harness/developer-hub pull request #3902
Opened 2023-10-27 12:28 UTC by suryanarayanan-venkatesan

Added CCM feature flags in the what's supported doc

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-10-27 15:10 UTC, Additi requested changes

2023-10-27 15:10 UTC, Additi commented on docs/cloud-cost-management/whats-supported.md
> +        <td>Enables the commitment orchestrator in the UI side nav and also enables the feature card in the AWS connector.</td>
@suryanarayanan-venkatesan What does the second half implies? Enables feature card in AWS connector?

2023-10-30 05:29 UTC, suryanarayanan-venkatesan commented on docs/cloud-cost-management/whats-supported.md
> +        <td>Enables the commitment orchestrator in the UI side nav and also enables the feature card in the AWS connector.</td>
This is the feature card shown while creating the connector. However, as per discussion, will remove the FF from this PR

2023-10-31 16:18 UTC, rdsoze approved these changes

2023-10-31 16:18 UTC, merged