[SMP-2246] Add ccm to smp helm install
harness/developer-hub pull request #3931
Opened 2023-10-30 18:38 UTC by brian-f-harness

Add ccm to smp helm install

For reviewers, a preview is available.

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-10-30 21:29 UTC, pratmit approved these changes
LGTM

2023-10-31 04:51 UTC, arya-harness requested changes

2023-10-31 04:51 UTC, arya-harness commented on docs/self-managed-enterprise-edition/self-managed-helm-based-install/install-harness-self-managed-enterprise-edition-using-helm-ga.md
> +* For Harness Continuous Error Tracking, go to the [CET tutorials](/tutorials/error-tracking/).
I see two mentions of CET tutorials, it might be accidental here

2023-10-31 05:16 UTC, arya-harness approved these changes
LGTM

2023-11-01 22:45 UTC, merged