[fix]: [CCM-15018]: Introducing some more FAQ's for recommendations
harness/developer-hub pull request #4067
Opened 2023-11-07 13:40 UTC by shashwat-harness

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-11-07 16:11 UTC, trunapushpa approved these changes

2023-11-08 06:09 UTC, iamanmolm requested changes

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### Do we provide the facility to add custom policies to get Asset Optimization Recommendation ?
We can change get to generate. And also change Asset Optimization Recommendation to Asset Governance Recommendation.

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +Yes we do provide the facility to add custom policies to get Asset Optimization Recommendation. You can connect with our team and let us know the policies, we will hook those policies into our backen
Even in the answer change the Asset Optimization Recommendation to Asset Governance Recommendation.

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +Yes we do provide the facility to add custom policies to get Asset Optimization Recommendation. You can connect with our team and let us know the policies, we will hook those policies into our backen
Even in answer recommendations spell is incorrect.

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +If this is for nodepool reccomnedations, you need to add preferred instance families to the x86 families that you would actually use.
Here recommendation spell is incorrect.

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +If this is for nodepool reccomnedations, you need to add preferred instance families to the x86 families that you would actually use.
Confirm this answer with @abhinavsingh-ccm

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### When I create a JIRA ticket from a recommendation, will that recommendations automatically come in the applied recommendations tab once the JIRA status of the ticket is set to done ?
Change "will that recommendations" to "will that recommendation".

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +Yes, as soon as you change the JIRA status of a ticket created for a partiucular recommnedation and change it's status to done, that particular recommendation will automatically start appearing in ap
particular spell is incorrect.

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +Yes, as soon as you change the JIRA status of a ticket created for a partiucular recommnedation and change it's status to done, that particular recommendation will automatically start appearing in ap
recommendation spell is incorrect.

2023-11-08 06:09 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +Yes, as soon as you change the JIRA status of a ticket created for a partiucular recommnedation and change it's status to done, that particular recommendation will automatically start appearing in ap
Confirm this with @trunapushpa, I think it would be done via batch job not instantly.

2023-11-08 06:28 UTC, shashwat-harness commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### Do we support showing GCP reccomendations ?
Ohh sorry, I created these FAQs in a text editor and as a result, the word 'recommendation' may have been auto-corrected to this throughout the FAQs

2023-11-08 06:42 UTC, shashwat-harness commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### Can I generate recommendation related to some resources based on expected demands in the future to rightsize up/down effectively ?
This was a question asked by one of the customer. It makes sense considering customer wants to rightsize his resources up/down based on the future demands.

2023-11-08 06:56 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### Can I generate recommendation related to some resources based on expected demands in the future to rightsize up/down effectively ?
It is not very clear what cloud provider or resource type we are talking about?

2023-11-08 07:01 UTC, iamanmolm requested changes

2023-11-08 07:01 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +No, we do not provide asset governance recommendations at the perspective level."
Remove quotes from the end.

2023-11-08 07:04 UTC, shashwat-harness commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### Can I generate recommendation related to some resources based on expected demands in the future to rightsize up/down effectively ?
I think the customer was asking about rightsizing the CPU and Memory limits based on expected demands. For instance, if we have Black Friday coming up next week, the customer is now interested in determining the ideal CPU and memory limits to configure, taking into account the expected surge in demand during that event.

2023-11-08 07:20 UTC, iamanmolm commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### Can I generate recommendation related to some resources based on expected demands in the future to rightsize up/down effectively ?
We can also add, "In all supported recommendation we look at past data to generate recommendation."

2023-11-08 07:37 UTC, shashwat-harness commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +#### Can I generate recommendation related to some resources based on expected demands in the future to rightsize up/down effectively ?
Done

2023-11-08 09:46 UTC, iamanmolm submitted a review, later dismissed

2023-11-09 05:19 UTC, shashwat-harness commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +If this is for nodepool reccomnedations, you need to add preferred instance families to the x86 families that you would actually use.
Done

2023-11-09 05:25 UTC, iamanmolm approved these changes

2023-11-09 06:00 UTC, merged