Update cloud-cost-management.md
harness/developer-hub pull request #4198
Opened 2023-11-17 09:40 UTC by suryanarayanan-venkatesan

Updated Release notes

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-11-17 09:44 UTC, rajarshee-harness commented on release-notes/cloud-cost-management.md
> +* Previously, the incorrect error message was displayed when Delegate validation failed. (CCM-14963)
```suggestion
* Previously, the incorrect error message was displayed when Delegate validation failed in Kubernetes Quick Create. (CCM-14963)
```

2023-11-17 09:50 UTC, rishik30 commented on release-notes/cloud-cost-management.md
> +  Now, each page is paginated, with a maximum of 20 perspectives displayed, effectively resolving the issue.
```suggestion
The problem has been fixed, the perspective list is now paginated, with a limit of 20 perspectives shown per page.
```

2023-11-17 11:09 UTC, Additi requested changes
Please update the details.

2023-11-17 11:09 UTC, Additi commented on release-notes/cloud-cost-management.md
> +  Now, we have added a new feature that enables users to export Recommendations as comma-separated values (CSV) files.
This works for all the recommendations. Only for asset governance recommendations details are not exposed, just the list view is exported. The support for the same will be added soon.

2023-11-17 11:18 UTC, suryanarayanan-venkatesan commented on release-notes/cloud-cost-management.md
> +  Now, we have added a new feature that enables users to export Recommendations as comma-separated values (CSV) files.
Should i add this under `Note: ` section below the same line?

2023-11-22 16:17 UTC, aimurphy commented
@suryanarayanan-venkatesan Could you please update the CCM release notes to use the [new format](https://harness.atlassian.net/wiki/spaces/DOCS/pages/21534966104/Release+Notes+Format+New+for+Oct+2023#Individual-release-note-pages-(aka-%E2%80%9Cmodule-pages%E2%80%9D))? You can also look at the [CI page](https://developer.harness.io/release-notes/continuous-integration) as an example.

Please also update the `date` in the metadata when you publish release notes. This date is what triggers the RSS feed updates.

2024-02-28 16:00 UTC, aimurphy commented
@jyotiarora-harness @rdsoze Another one that has been open since last year. Please take action to merge or close.

2024-03-26 22:54 UTC, aimurphy commented
Closing this PR. The release notes for these releases were published.

2024-03-26 22:54 UTC, closed without merging