Delegate-reorg-changes
harness/developer-hub pull request #425
Opened 2023-01-23 04:31 UTC by kat-enos

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

Further changes for the re-org including those specified in https://harness.atlassian.net/browse/DOC-2421 that were overlooked because Prateek and I noted their destinations in different places. Further changes, including developmental, line edits and copy edits to follow in different PRs, to minimize the complexity.

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-23 14:18 UTC, ravilach approved these changes
From a HDH standpoint, looks good. -Ravi

2023-01-24 14:50 UTC, deepakbolangady requested changes

2023-01-24 14:50 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
> +    value: ""
Is this valid YAML? Looks like there's additional indentation here. A YAML linter will likely complain.

2023-01-24 14:50 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
> +Makes the delegate use a CDN for new versions.
What happens if the value is false?

2023-01-24 14:50 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
> +By default, the delegate always checks for new versions (via the Watcher).
```suggestion
By default, the delegate always checks for new versions (through the Watcher). 
```
(always or periodically? What's the frequency, if we have that info? Also, this double negative made me read it multiple times: "if the variable is named "disabled" and the value is false, then it has to mean "enabled". Is there a reason the engineer did not choose to go with VERSION_CHECK_ENABLED and a default value of "true"?)

2023-01-24 14:50 UTC, deepakbolangady commented on docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
> +The URL for the Watcher versions. See [Delegate Installation Overview](/docs/platform/2_Delegates/get-started-with-delegates/delegate-installation-overview.md).
"The URL at which Watcher versions are available." (?)

2023-01-24 14:50 UTC, deepakbolangady commented on docs/platform/2_Delegates/install-delegates/kubernetes-delegates/install-harness-delegate-on-kubernetes.md
> +For an introduction to delegates, see [Delegate Overview](/docs/platform/2_Delegates/get-started-with-delegates/delegates-overview.md). For more information about the delegate automatic update proces
```suggestion
For an introduction to delegates, see [Delegate Overview](/docs/platform/2_Delegates/get-started-with-delegates/delegates-overview.md). For more information about the automatic update process for a delegate, see [Delegate Auto-Update](/docs/platform/2_Delegates/configure-delegates/delegate-auto-update.md).
```

2023-01-24 14:50 UTC, deepakbolangady commented on docs/platform/7_Connectors/ref-cloud-providers/kubernetes-cluster-connector-settings-reference.md
>  * Install a Harness Kubernetes Delegate in your EKS cluster.You must be logged in as an admin user when you run the `kubectl apply -f harness-delegate.yaml` command.
```suggestion
* Install a Harness Kubernetes Delegate in your EKS cluster. You must be logged in as an admin user when you run the `kubectl apply -f harness-delegate.yaml` command.
```

2023-01-24 20:10 UTC, kat-enos commented on docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-a-kubernetes-sidecar-container.md
> +* [Install a Kubernetes Delegate](../../../platform/2_Delegates/advanced-installation/install-a-kubernetes-delegate.md): you must have a Harness Kubernetes Delegate running in your target Kubernetes
@deepakbolangady , as noted on the PR form: 
Further changes, including developmental, line edits and copy edits to follow in different PRs, to minimize the complexity.

2023-01-24 20:20 UTC, kat-enos commented on docs/continuous-delivery/cd-advanced/cd-kubernetes-category/add-a-kubernetes-sidecar-container.md
> +* [Install a Kubernetes Delegate](../../../platform/2_Delegates/advanced-installation/install-a-kubernetes-delegate.md): you must have a Harness Kubernetes Delegate running in your target Kubernetes
I have accepted some changes that weren't within the scope for this PR. This PR was intended to effect part of a re-organization and to minimize the complexity and risk of the changes.

2023-01-24 20:27 UTC, kat-enos commented on docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
> +Makes the delegate use a CDN for new versions.
Typically I'd prefer to see the effect of both "true" and "false" documented for boolean values. For an environment variable, we'd also want to know if it was optionally inserted and set and if there was a default value. But these items would require a technical review pass, which is out of scope for the changes in this PR. I have told the PR that the docs should probably have a technical review pass to identify inaccurate or obsolete information since most of the delegate docs are older.

2023-01-24 20:39 UTC, kat-enos commented on docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
> +By default, the delegate always checks for new versions (via the Watcher).
I didn't mean to resolve this comment and will change "through the Watcher" to "using the Watcher". I did comment that the clarifying information requested is out of scope for this PR but that it's possible that version checking is enabled by default and the customer is given the option, at the customer's own risk, of disabling version checking. I don't think the semantics of the programming element are confusing for engineers are accustomed to evaluating complex expressions including logical NOT operators and so on.

2023-01-24 20:41 UTC, kat-enos commented on docs/platform/2_Delegates/delegate-reference/delegate-environment-variables.md
> +The URL for the Watcher versions. See [Delegate Installation Overview](/docs/platform/2_Delegates/get-started-with-delegates/delegate-installation-overview.md).
I usually change these to "The URL location..." and may have done so in another edit coming down the pike.

2023-01-24 20:44 UTC, pratmit reviewed
PR approved as the organization of docs looks like what has been suggested in the doc - https://docs.google.com/document/d/1zgFum5poEPEBIf-spMllhXxJmHR5szb1hOQphNw30w4/edit#

2023-01-24 20:46 UTC, kat-enos commented on docs/platform/2_Delegates/install-delegates/kubernetes-delegates/install-harness-delegate-on-kubernetes.md
> +For an introduction to delegates, see [Delegate Overview](/docs/platform/2_Delegates/get-started-with-delegates/delegates-overview.md). For more information about the delegate automatic update proces
I think it's okay as is though I might change it to  something like "For more information about delegate updates...", since it makes for a quicker read to the link.

2023-01-24 20:51 UTC, pratmit submitted a review, later dismissed

2023-01-24 22:11 UTC, douglas-j-bothwell submitted a review, later dismissed

2023-01-25 23:00 UTC, kat-enos commented
Closing to assess state.

2023-01-25 23:00 UTC, closed without merging