Recreate pr 408
harness/developer-hub pull request #435
Opened 2023-01-23 21:04 UTC by aimurphy

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* DOC-2491

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-23 21:24 UTC, douglas-j-bothwell submitted a review, later dismissed

2023-01-23 21:24 UTC, douglas-j-bothwell commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +With Harness Cloud you can run builds in isolation on machines hosted and maintained by Harness. You can run builds at scale on Linux, Windows and macOS machines that are preinstalled with software c
```suggestion
With Harness Cloud you can run builds in isolation on machines hosted and maintained by Harness. You can run builds at scale on Linux, Windows, and macOS machines that are preinstalled with software commonly used in CI pipelines.
```

2023-01-23 21:30 UTC, douglas-j-bothwell approved these changes

2023-01-24 16:24 UTC, KimberlyFields requested changes

2023-01-24 16:24 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +With Harness Cloud you can run builds in isolation on machines hosted and maintained by Harness. You can run builds at scale on Linux, Windows, and macOS machines that are preinstalled with software
Avoid passive voice.

2023-01-24 16:24 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +
Add text between headings.

2023-01-24 16:24 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +## Local
Suggest making "Local" and "Kubernetes cluster" tabs instead of headings.

2023-01-24 16:24 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +With the Local runner (also known as the Docker runner) you can run builds on a local machine. You can execute build steps in Docker containers or directly on the host machine.
```suggestion
With the local runner, which is also known as the Docker runner, you can run builds on a local machine. You can execute build steps in Docker containers or directly on the host machine.
```

2023-01-24 16:24 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +With the Local runner (also known as the Docker runner) you can run builds on a local machine. You can execute build steps in Docker containers or directly on the host machine.
Avoid parentheses. Readers often skip text in parentheses.

2023-01-24 16:24 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +The following table shows which operating systems and architectures are supported by each build infrastructure option.
```suggestion
The following table shows which operating systems and architectures that each build infrastructure option supports.
```

2023-01-24 16:24 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +
@aimurphy I know you are editing content that Nofar wrote. I don't think this topic clearly describes the pros and cons of each infrastructure. Please work with Nofar on additional details about each infrastructure.

2023-01-24 17:54 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +
addressed in subsequent change

2023-01-24 17:54 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +
I will address this with her for future updates to the topic.

2023-01-24 17:55 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +## Local
addressed in subsequent change

2023-01-24 21:43 UTC, KimberlyFields submitted a review, later dismissed
I made one suggestion, but I'm approving the PR in anticipation of that suggestion being implemented.

2023-01-24 21:43 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/which-build-infrastructure-is-right-for-me.md
> +Available only with paid CI plans.
```suggestion
This option is available only with paid CI plans.
```

2023-01-25 19:11 UTC, KimberlyFields approved these changes

2023-01-26 00:17 UTC, merged