feat: [SSCA-847]: SBOM generation and Ingestion for Snyk and Trivy
harness/developer-hub pull request #4366
Opened 2023-11-29 22:27 UTC by williamwissemann

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-11-30 18:36 UTC, aimurphy requested changes
Most suggestions are optional, but there were a couple of broken links and issues with the headings on the Snyk page that must be addressed before this can be published.

2023-11-30 18:36 UTC, aimurphy commented on docs/software-supply-chain-assurance/sbom/generate-sbom-snyk.md
> +:::info
I understand why you included this note, but I don't think it is necessary here. The page is already clear that it is for Snyk. The presence of this note makes me think Snyk isn't supported in any capacity, when in reality you are saying that Synk Container doesn't have built-in support.

I suggest removing the note from this Snyk page. However, the original note on the [Ingest SBOM into SSCA page](https://6567bce976ceac23c8beb33a--harness-developer.netlify.app/docs/software-supply-chain-assurance/sbom/ingest-sbom-data) needs to be edited since there is no longer a generic "Generate SBOM from any scan step" topic (it is now the Blackduck topic).

```
:::info

Use this configuration for scanners that don't have built-in support in SSCA. For scanners with built-in support you can:

* [Use the SSCA Orchestration step to generate SBOM.](./generate-sbom.md)
* [Ingest results from a Blackduck STO scan step.](./generate-sbom-blackduck.md).
* [Ingest results from an Aqua Trivy STO scan step.](./generate-sbom-aqua-trivy.md)

For a list of all SSCA-supported scanners, go to [What's supported for STO](/docs/security-testing-orchestration/whats-supported).

:::

2023-11-30 18:36 UTC, aimurphy commented on docs/software-supply-chain-assurance/sbom/generate-sbom-snyk.md
> +sidebar_label: Ingest SBOM from Snyk Open Source & Container
```suggestion
sidebar_label: Ingest SBOM from Snyk
```

2023-11-30 18:36 UTC, aimurphy commented on docs/software-supply-chain-assurance/sbom/generate-sbom-snyk.md
> +   ```
The codeblock loses context when it's after the image.

~~~suggestion
   For example, you could use the following command in a **Run** step to generate a Snyk SBOM.
   
   ```
   snyk container sbom --format=spdx2.3+json \
    ubuntu:22.04 > /shared/customer_artifacts/result.spdx.json
   ```

   ![](../static/ingesting-sbom-from-other-scanners-03.png)
~~~

2023-11-30 18:36 UTC, aimurphy commented on docs/software-supply-chain-assurance/sbom/generate-sbom-snyk.md
> +4. If your SBOM tool can't output directly to your **Shared Path**, then add commands or a **Run** step to copy the SBOM into the directory specified in **Shared Paths**.
```suggestion
4. If your SBOM tool can't output directly to your **Shared Path**, then add commands or a **Run** step to copy the SBOM into the directory specified in **Shared Paths**.
```

I would modify this step to explain how it would apply to Snyk Container. Can Snyk Container output directly to the Shared Path?

2023-11-30 18:36 UTC, aimurphy commented on docs/software-supply-chain-assurance/sbom/generate-sbom-snyk.md
> +   * For **SBOM File Path**, enter the path to the SBOM file generated by your SBOM tool.
```suggestion
   * For **SBOM File Path**, enter the path to the SBOM file generated by Snyk Container.
```

2023-11-30 18:36 UTC, aimurphy commented on docs/software-supply-chain-assurance/sbom/generate-sbom-snyk.md
> +# Generating an  Snyk Open Source SBOM via an STO Snyk Step
```suggestion
## Generate and ingest a Snyk Open Source SBOM
```

2023-11-30 18:36 UTC, aimurphy commented on docs/software-supply-chain-assurance/sbom/generate-sbom-snyk.md
> +Configure an STO scanner step, such as the [Snyk STO step](/docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scans#snyk-repository-orchestration-example, and make sure you select **
```suggestion
Configure the [Snyk STO scanner step](/docs/security-testing-orchestration/sto-techref-category/snyk/snyk-scans#snyk-repository-orchestration-example), and make sure you select **Generate SBOM** and the **SBOM Format**.
```

2023-12-01 17:24 UTC, williamwissemann commented
@aimurphy Thanks, I think I have made all the changes to reflect the feedback.

2023-12-01 17:45 UTC, aimurphy commented
@williamwissemann The heading levels on the Snyk topic still need to be incremented. Headings must start with level 2 (`##`). I also suggested moving some text around for flow. Please see the comments here: https://github.com/harness/developer-hub/pull/4366/files#diff-b4497922206925d6218a7e5464f9f121d6abc43823b4a84bc593d2e2416af593

2023-12-01 19:23 UTC, aimurphy approved these changes

2023-12-01 19:32 UTC, williamwissemann commented
@aimurphy Okay, that should be all the changes. It doesn't look like I have permission to merge.

2023-12-01 19:38 UTC, merged