New topic for pipeline chaining
harness/developer-hub pull request #450
Opened 2023-01-24 12:23 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-25 08:53 UTC, prashantsharma04 commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +- Fast rollback: It makes it easy to roll back to previous stages in case of any issues.
Rollback is not supported in prod as of now. Not it has been supported in pipeline chaining

2023-01-25 09:01 UTC, Eric761 submitted a review, later dismissed

2023-01-25 09:01 UTC, prashantsharma04 submitted a review, later dismissed

2023-01-25 11:50 UTC, deepakbolangady requested changes
Thanks for looking into this urgent requirement, Rashmi. I have added some feedback. Please let me know if you want to discuss. If this needs to go out immediately, prioritize what you can incorporate and leave anything that is more involved to a later time, after you've published. I'll approve after you've incorporated the comments that you can address in the time you have. Thanks.

2023-01-25 11:50 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +- Better compliance: By automating the deployment process, pipeline chaining can help to ensure compliance with regulatory requirements and industry best practices.
Can we have a lead-in sentence and remove redundancies from the list? For example:
~~
With pipeline chaining, you can do the following:
- Automate the deployment process and make sure that the application is tested properly before deploying to production.
- Create complex workflows that involve multiple stages of deployment, testing, and verification.
- Handle errors and roll back to previous stages if issues occur.
(and so on)

~~
("Roll back" is two words when used as a verb.)
I would also question some of the items in the list. The first one, for example: isn't automation something we could do even before chained pipelines? It does not seem to say anything about chained pipelines. If automation is truly something introduced by this feature, we should elaborate.
The error handling one looks more like a useful feature we added and less like a direct benefit of being able to chain pipelines, which is what the title tells me to expect. 
I'm certain better collaboration and better compliance are direct benefits (as are the visibility and enhanced efficiency onces) but the statements will definitely benefit from your rewording, if you can look into it after sending it out the door (given you don't have time now).

2023-01-25 11:50 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +   This is your parent pipeline.
```suggestion
1. Create your parent [pipeline](../8_Pipelines/add-a-stage.md#step-1-create-a-pipeline) and configure it with the desired settings, such as triggers, environment variables, and deployment steps.
```
Until I reached the next line, I did not know which pipeline I was creating first... the parent or a child. Good to set context early.

2023-01-25 11:50 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +   For example, you can use the build image in the subsequent deployment stage.
```suggestion
   For example, you can use the build image in a subsequent deployment stage.
```

2023-01-25 11:50 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +5. You can use outputs from child pipelines in other stages in parent pipelines by clicking **Outputs**.
This sentence states a fact and needs a rewrite. Can we convert this to a step? Something like, "to do this, click **Outputs**.
Also, using the singular whenever appropriate makes for a clearer idea. Multiple plurals can lead to confusion and questions such as "can I use the output of one child pipeline in multiple other stages in the parent?" or "can I use the output of multiple child pipelines in a subsequent stage?" Consider this example: "To use the output of the child pipeline in subsequent stages of the parent pipeline, click ..." (Then you are referring to this specific child pipeline you are documenting and using the singular.)

2023-01-25 11:50 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +7. In the final pipeline, you can add a **Deploy** step to deploy the application to the desired environment.
final child pipeline?

2023-01-25 11:50 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +   You can also add "Rollback" step in case of any failure.
```suggestion
   You can also add a "Rollback" step if your deployment fails.
```
(Is my correction accurate?)

2023-01-25 11:50 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +   Once you have completed chaining the pipelines, you can run the parent pipeline to start the process.
```suggestion
   After you have chained the pipelines, you can run the parent pipeline.
```

2023-01-25 14:47 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +## Important
This is the list of permissions required and the limitations this feature has. Putting them as a note or info would not be right in this context.

2023-01-25 14:55 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +   This is your parent pipeline.
Done

2023-01-25 14:57 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +   You can also add "Rollback" step in case of any failure.
This statement needs to be removed. Rollback is not supported yet.

2023-01-27 05:06 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +- Better compliance: By automating the deployment process, pipeline chaining can help to ensure compliance with regulatory requirements and industry best practices.
Done

2023-01-27 05:07 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +7. In the final pipeline, you can add a **Deploy** step to deploy the application to the desired environment.
Rephrased to "final chained pipeline".

2023-01-27 05:14 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +5. You can use outputs from child pipelines in other stages in parent pipelines by clicking **Outputs**.
Done.

2023-01-27 06:46 UTC, deepakbolangady approved these changes
Approving so you can merge and send this out the door. Do take a look at any pending comments when you can, though. Thanks.

2023-01-27 06:46 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +For example, you could have a pipeline that deploys an application to a test environment. This is followed by another pipeline that runs a set of integration tests, and finally another pipeline that
```suggestion
For example, you could have a pipeline that deploys an application to a test environment. This could be followed by a pipeline that runs a set of integration tests and, finally, a pipeline that deploys the application to production. Each pipeline in the chain is triggered by the completion of the previous pipeline. The output of each pipeline is passed to the next pipeline in the chain. This way, you can automate the whole process and make sure that the application is tested properly before deploying to production.
```
"Deployed and tested properly before deploying to production" reads odd because we say we deploy before we deploy. Is the current suggestion okay?)

2023-01-27 06:46 UTC, deepakbolangady commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +## Important
Okay, I agree.

2023-01-27 06:58 UTC, rashminandasahoo commented on docs/platform/8_Pipelines/pipeline-chaining.md
> +In Harness, you can create a pipeline chain by linking pipelines together using a pipeline trigger. A pipeline trigger is a specific event or condition that triggers the next pipeline in the chain.
Removed this line because the mention of pipeline trigger is not correct and might confuse customers.

2023-01-27 07:18 UTC, deepakbolangady approved these changes

2023-01-27 07:42 UTC, merged