[CDB-1392] Manage dashboard RBAC
harness/developer-hub pull request #4683
Opened 2023-12-20 21:52 UTC by brian-f-harness

Manage dashboard RBAC

For reviewers, a preview is available.

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-12-20 22:16 UTC, Rohit-Kaliki commented
@brian-f-harness the netlify link is broken/ not working for me? 😅

2023-12-20 22:18 UTC, brian-f-harness commented
@Rohit-Kaliki The preview link in the conversation tab doesn't open for you?

https://658365d3e78d196952c17f86--harness-developer.netlify.app/docs/platform/role-based-access-control/manage-dashboards

2023-12-20 22:21 UTC, Rohit-Kaliki requested changes

2023-12-20 22:21 UTC, Rohit-Kaliki commented on docs/platform/role-based-access-control/manage-dashboards.md
> +* **Dashboard - Static Editor**: To add, edit, and delete dashboards
@brian-f-harness we have OOTB ACL Roles

https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/settings/access-control/roles/_dashboard_admin
https://app.harness.io/ng/account/6_vVHzo9Qeu9fXvj-AcbCQ/settings/access-control/roles/_dashboard_viewer

2023-12-20 22:21 UTC, Rohit-Kaliki commented on docs/platform/role-based-access-control/manage-dashboards.md
> +4. In **Name**, enter **Dashboard - Static Editor** and select **Save**.
We should reuse the OOTB roles for this section

2023-12-20 22:21 UTC, Rohit-Kaliki commented on docs/platform/role-based-access-control/manage-dashboards.md
> +4. In **Name**, enter **Dashboard - All View** and select **Save**.
Same as above, let's leverage OOTB Roles

2023-12-20 22:21 UTC, Rohit-Kaliki commented on docs/platform/role-based-access-control/manage-dashboards.md
> +By default, RBAC for STO custom dashboards is restricted to entities exclusively. When you grant folder access to a user, they can view all entity information on the dashboard. Therefore, the **Proje
By default, RBAC for STO custom dashboards is restricted to + Dashboard + entities exclusively.

2023-12-20 22:21 UTC, Rohit-Kaliki commented on docs/platform/role-based-access-control/static/manage-access-control-for-dashboards-06.png
Let's the the OOTB Roles here, sorry should have mentioned this in our call.

2023-12-20 23:38 UTC, Rohit-Kaliki approved these changes

2023-12-20 23:39 UTC, Rohit-Kaliki commented on docs/platform/role-based-access-control/manage-dashboards.md
> +The following roles are required for dashboards:
Nit: We can also add the fact that the Account Admin/ Account Viewer Roles have this access baked in

2023-12-20 23:39 UTC, Rohit-Kaliki approved these changes

2023-12-21 00:10 UTC, brian-f-harness commented on docs/platform/role-based-access-control/manage-dashboards.md
> +The following roles are required for dashboards:
added a note

2023-12-21 00:40 UTC, merged