secret cache update
harness/developer-hub pull request #471
Opened 2023-01-25 11:39 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-27 10:16 UTC, nishantsaini20 requested changes

2023-01-27 10:16 UTC, nishantsaini20 commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +- The secret manager is KMS (GCP KMS, AWS KMS): **EncryptedRecordData** contains encrypted secret values and encryption keys. When this gets cached, the cached values are always decrypted, resulting
IMO we should not be exposing too much internals. For this point just mentioning the type of KMS should be enough.

2023-01-27 10:16 UTC, nishantsaini20 commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +- The secret manager is GCP Secret Manager: In this case, **EncryptedRecordData** contains version information. Every time the inline secret is edited, the incremented version is updated in the datab
In this case, version is part of metadata. Every time the inline secret is edited, the version value also gets updated. However, because metadata is cached, and it has older version information, the older value keeps getting retrieved.

2023-01-27 10:41 UTC, rashminandasahoo commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +- The secret manager is KMS (GCP KMS, AWS KMS): **EncryptedRecordData** contains encrypted secret values and encryption keys. When this gets cached, the cached values are always decrypted, resulting
Done for all the bullets.

2023-01-28 15:00 UTC, manish-manchanda commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +The same does not happen for secret managers who do not use KMS. The secrets for non-KMS secret managers are inline, and no meta-data is used to retrieve the value.
"The same does not happen for secret managers who do not use KMS" I believe caching and retrieving stale value can happen for GCP Secret Manager as well when referenced secret is used and reference is changed.
@nishantsaini20 can confirm.
cc: @meenakshi-harness

2023-01-30 05:01 UTC, nishantsaini20 commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +The same does not happen for secret managers who do not use KMS. The secrets for non-KMS secret managers are inline, and no meta-data is used to retrieve the value.
@manish-manchanda  This gets covered in point **The secret manager is GCP Secret Manager** and **Secret is of reference type**

2023-01-30 05:01 UTC, nishantsaini20 approved these changes

2023-01-30 11:38 UTC, deepakbolangady requested changes

2023-01-30 11:38 UTC, deepakbolangady commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +Decrypting a secret sometimes requires its meta-data. When such meta-data changes on editing a secret, a cached stale value is retrieved.
```suggestion
Decrypting a secret sometimes requires its metadata. When you edit a secret, its metadata changes and a stale value is retrieved from the cache.
```
Is that accurate?

2023-01-30 11:38 UTC, deepakbolangady commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +This happens in the following cases:
Lead-in begins with "this happens". Good to add this lead-in to the previous paragraph.

2023-01-30 11:38 UTC, deepakbolangady commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +- The secret manager is KMS (GCP KMS, AWS KMS).
```suggestion
- The secrets manager is a KMS (GCP KMS or AWS KMS).
```
* "Secrets" for consistency. I see "secrets manager" and "secret manager". Is there a difference? (Run global check)
* Does the text in parentheses represent a set of examples? Or are they the exact set? The comma between those two names makes it unclear. If they represent an exact set, we can write "The secrets manager is Google Cloud KMS or AWS KMS." It looks like that's how those companies refer to those features, but please check. I took only a cursory glance. TBH, Google just writes "Cloud KMS", but because we aren't Google, we must prefix the company name.

2023-01-30 11:38 UTC, deepakbolangady commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +- The secret manager is GCP Secret Manager: It contains version information in its metadata. Every time the inline secret is edited, the incremented version is updated in the database. However, the o
```suggestion
- The secret manager is Google Cloud Secret Manager: It contains version information in its metadata. Every time you edit the inline secret, its version is incremented and updated in the database. However, on subsequent access, the older value is retrieved because cached metadata contains information about older versions.
```
Referring to "It contains version information in its metadata" - Please clarify what "it" is here.

2023-01-30 11:38 UTC, deepakbolangady commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +- Secret is of reference type: If a secret's reference path is changed during editing, it will update in the database, but the cache value still holds the older path, so it will fetch the secret from
```suggestion
- The secret is of the reference type: If a secret's reference path is edited, the path is updated in the database. However, the cached value continues to store the older path and fetches the stale secret.
```

2023-01-30 11:38 UTC, deepakbolangady commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +The same does not happen for secret managers who do not use KMS. The secrets for non-KMS secret managers are inline, and no meta-data is used to retrieve the value.
```suggestion
This issue does not occur with secrets managers that do not use a KMS. In such secrets managers. secrets are inline, and no metadata is used to retrieve the value. 
```
(Avoid using terms such as non-KMS. Also, I did not know what "secrets for non-KMS secret managers" meant, so I could not suggest an effective rewrite. A good way to write this is "In such secrets managers". Does that work?

2023-01-30 12:09 UTC, rashminandasahoo commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +Any secret manager requires a running Harness Delegate to encrypt and decrypt secrets. Any Delegate that references a secret requires direct access to the Secrets Manager.
@deepakbolangady The review request was only for a specific section corresponding to secret cache. We should review the whole topic as part of a separate ticket. This topic is 2 years old and our writing style has changed since then.

2023-01-31 06:25 UTC, rashminandasahoo commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +All Harness secrets managers require a running Harness Delegate to encrypt and decrypt secrets.
Removed this sentence.

2023-01-31 06:34 UTC, rashminandasahoo commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +In the secret manager, Harness maintains a cache of the encrypted data, except for those stored in the Hashicorp vault. The cache also contains meta-data associated with the secret like paths for the
Done

2023-01-31 06:35 UTC, rashminandasahoo commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +This happens in the following cases:
Done

2023-01-31 06:43 UTC, rashminandasahoo commented on docs/platform/6_Security/1-harness-secret-manager-overview.md
> +- The secret manager is KMS (GCP KMS, AWS KMS).
I checked on the usage of secrets vs secret.
AWS refers to it as AWS Secrets Manager. Google refers to it as Google Cloud Secret Manager.
I will change to "secret manager" throughout for consistency.

2023-01-31 07:11 UTC, deepakbolangady approved these changes
LGTM. Thanks.

2023-01-31 07:50 UTC, merged