[CDB-1267] Dashboard intelligence by AIDA
harness/developer-hub pull request #4722
Opened 2023-12-26 23:28 UTC by brian-f-harness

Dashboard intelligence by AIDA

For reviewers, a preview is available:

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-12-27 17:02 UTC, Rohit-Kaliki approved these changes

2023-12-27 17:02 UTC, Rohit-Kaliki commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +   - What are my total AWS costs for project `qa-stage`? Filter for the past 45 days.
Nit: We can keep the markdown & punctuation  consistent across all three points here.

2023-12-27 17:02 UTC, Rohit-Kaliki commented
LGTM

2023-12-27 21:12 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
I feel the visualization types should all be grouped under the same header. A single value type is technically not a table. And only having Table under a Table header seems superfluous.

2023-12-27 21:13 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
I feel the visualization types should all be grouped under the same header. A single value type is technically not a table. And only having Table under a Table header seems superfluous.

2023-12-27 21:14 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
Creating a dashboard does not necessitate saving in an explicit folder. I would note this is an optional step. Otherwise, the dashboard will save in the Custom Dashboards root folder.

2023-12-27 21:20 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
Under step 8, you technically do not select the module; you select the explore within a module you want to generate a visualization. An explore is a curated UI experience with modeled data points in Looker. See here for more reference: https://cloud.google.com/looker/docs/creating-and-editing-explores.

2023-12-27 21:24 UTC, josephdlopez requested changes
Please see my comments

2023-12-27 21:26 UTC, brian-f-harness commented
> Please see my comments

Thanks @josephdlopez. I added commits to address your changes. A new preview is building now.

2023-12-27 21:27 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
The tweaks are good! However, I am referring to line 77, that says `To create a Dashboard you first need to first create a Folder.`

2023-12-27 21:41 UTC, josephdlopez commented on docs/platform/dashboards/static/create-a-widget-AIDA-01.png
under step 11, i would recommend removing the mention to refining. currently, we do not have the ability for AIDA to take second or third passes on existing widgets. it is a simple creation and addition.

2023-12-27 21:47 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
Line 50 should have us-west1 wrapped in double quotes, not back-ticks. thank you!

2023-12-27 22:16 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +If you have trouble with a particular data point, pass both the view name and the field name in the prompt.
i fear view might be too BI technical. lets change it to table and provide an example.

example: segments environment instead of just environment. table name is segments.

example prompt: What are my total feature flags? Pivot by segments environment.

example image in UI showing table name field name under information "i" next to the field:
<img width="350" alt="image" src="https://github.com/harness/developer-hub/assets/118556620/4f82d2fa-4321-48e4-82ec-28f332a426dd">

2023-12-27 22:17 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +If you have trouble with a particular data point, pass both the view name and the field name in the prompt.
we should move this to one of the last recommendations, as this presupposes the other best practices

2023-12-27 22:23 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +   - How many of my feature flags are active?
Please change to What count of my feature flags are active?

2023-12-27 22:25 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +   - What are my total AWS costs for project qa-stage? Filter for the last 45 days.
Please change to What are my total AWS costs? Filter for the last 45 days.

2023-12-27 22:28 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +   - What is my monthly build count by project? Filter for the last 90 days.
Please change to What is my monthly build count? Filter for the last 90 days.

2023-12-27 22:31 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +   - What are my total costs by region? Filter for the last 30 days. Include a table calculation returning yes if region is `us-west1`, else no.
Please change to What are my AWS total costs? Pivot by region. Filter for the last 30 days. Include a table calculation returning yes if region is "us-west1", else no. Make this a table.

2023-12-27 22:37 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +- For number filters, use operators instead of words (for example, use “>” instead of “greater than”).
it would be good to also add recommending playing around with the order of each statement. for example, sometimes switching the table calculation instruction with filter instruction helps with generation:

example before: Show me total costs. Pivot by region. Include a table calculation returning yes if region is "us-west1" else no. Filter for the last 30 days.

example after: Show me total costs. Pivot by region. Filter for the last 30 days. Include a table calculation returning yes if region is "us-west1" else no.

2023-12-27 23:40 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +- If you have trouble with a particular data point, pass both the table name and the field name in the prompt. For example, if you want to view your feature flags by environment, you could enter the
please change to if you want to view your feature flags by segment environment

2023-12-28 00:07 UTC, brian-f-harness commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +- If you have trouble with a particular data point, pass both the table name and the field name in the prompt. For example, if you want to view your feature flags by environment, you could enter the
```suggestion
- If you have trouble with a particular data point, pass both the table name and the field name in the prompt. For example, if you want to view your feature flags by segment environment, you could enter the following prompt: 
```

2023-12-29 05:37 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +Harness currently supports the following visualization types:
Please change to Dashboard Intelligence by AIDA currently supports […]

2023-12-29 05:39 UTC, josephdlopez commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +- When constructing a query, it's important to avoid unnecessary information. The more concise and direct the query is, the better it will be. Avoid using irrelevant details and focus on the essentia
don’t we need a comma between details and focus to be grammatically correct? 😅😅😅

2023-12-29 05:45 UTC, brian-f-harness commented on docs/platform/dashboards/use-dashboard-intelligence-by-aida.md
> +- When constructing a query, it's important to avoid unnecessary information. The more concise and direct the query is, the better it will be. Avoid using irrelevant details and focus on the essentia
True, thanks. Updated.

2023-12-29 05:52 UTC, josephdlopez approved these changes

2023-12-29 17:37 UTC, merged