Knowledge Base Article to use Linear.app with Custom Approval
harness/developer-hub pull request #4774
Opened 2024-01-03 06:47 UTC by apoorv-arora-harness

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?
Knowledge Base Article to use Linear.app with Custom Approval
- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-01-03 13:56 UTC, puthrayaharness submitted a review, later dismissed

2024-01-04 18:18 UTC, aimurphy requested changes
Heading levels must be fixed for proper rendering.

I also added suggestions for the indentation which will help with alignment and layout.

I added some optional suggestions for wording changes.

2024-01-04 18:18 UTC, aimurphy commented on kb/continuous-delivery/articles/Linear.app-with-Custom Approval.md
> +Authorization should be kept secret to prevent unauthorized access. Revealing it exposes sensitive information, risking data breaches and compromising system security, making it a critical element to
```suggestion
4. **Headers:** Configure necessary headers for proper communication with Linear's API.
   * Content-Type: application/json
   * Authorization: `<+secrets.getValue("authorization")>`

   Authorization should be kept secret to prevent unauthorized access. Revealing it exposes sensitive information, risking data breaches and compromising system security, making it a critical element to safeguard. 
```

2024-01-04 18:18 UTC, aimurphy commented on kb/continuous-delivery/articles/Linear.app-with-Custom Approval.md
> +* Assertion: `<+httpResponseCode>==200`
```suggestion
   * Assertion: `<+httpResponseCode>==200`
```

2024-01-04 18:18 UTC, aimurphy commented on kb/continuous-delivery/articles/Linear.app-with-Custom Approval.md
> +* issueId = `<+json.select("data.issueCreate.issue.id", httpResponseBody)>`
```suggestion
   * issueId = `<+json.select("data.issueCreate.issue.id", httpResponseBody)>`
```

2024-01-04 18:18 UTC, aimurphy commented on kb/continuous-delivery/articles/Linear.app-with-Custom Approval.md
> +```
~~~suggestion
1.  **Script:** Create a Bash script to:
   * Install necessary packages.
   * Execute a curl command to query the Linear API for the issue status.
   * Extract and export the issue status as the variable status.
   * Print the status for visibility purpose.

   For example:

   ```
   #!/bin/bash
   # Update and install necessary packages
   sudo yum install -y microdnf
   microdnf update
   microdnf install jq

   # Make the curl request
    response=$(curl --location 'https://api.linear.app/graphql' \
   --header 'Content-Type: application/json' \
   --header "Authorization: $authorization" \
   --data "{ \"query\": \"query Issue { issue(id: \\\"$issue_id\\\") { id number priority priorityLabel identifier url description descriptionData title state { name } } }\" }")

   export status=$(echo "$response" | jq -r '.data.issue.state.name')
   echo "Status: $status"
   ```
~~~

2024-01-04 18:18 UTC, aimurphy commented on kb/continuous-delivery/articles/Linear.app-with-Custom Approval.md
> +Rejection criteria is optional field either you can define or not. If you do not define the rejection criteria pipeline will retry until the timeout is achieved. After the timeout reached the pipelin
```suggestion
2. **Custom Approval Parameters:**
   * Timeout: How long you want Harness to try to complete the step before failing (and initiating the stage or step Failure Strategy) [1d].
   * Script Type: Choose Bash as the script type.
   * Retry Interval: Set how long the step should wait to run the script again if the Approval or Rejection criteria evaluate to false.The number of times a script executes depends on the Retry Interval, Script Timeout, and how fast the script executes [30s].
   * Script Timeout: Set how long the step should wait for the script to complete before timing out [5m].

3. **Approval Criteria:** Define approval criteria based on the extracted status variable, or you can establish criteria using any other variable.

   ![](../static/approval-criteria.png)

4. **Rejection Criteria:** Rejection criteria is optional field either you can define or not. If you do not define the rejection criteria pipeline will retry until the timeout is achieved. After the timeout reached the pipeline will expire.
```

2024-01-04 18:18 UTC, aimurphy commented on kb/continuous-delivery/articles/Linear.app-with-Custom Approval.md
> +This script queries the Linear API to retrieve the current status of the created issue. The obtained status is stored in a variable (status) for subsequent use in approval or rejection criteria.
```suggestion
   ![](../static/rejection-criteria.png)

   This script queries the Linear API to retrieve the current status of the created issue. The obtained status is stored in a variable (status) for subsequent use in approval or rejection criteria.
```

2024-01-04 18:18 UTC, aimurphy commented on kb/continuous-delivery/articles/Linear.app-with-Custom Approval.md
> +![](../static/script-input-variable.png)
```suggestion
5. **Script Input Variable:** While you can simply declare a variable in your script using a Harness expression or string for its value, using Input Variables provides some additional benefits:
   * You can easily identify and manage the Harness expressions used in your script.
   * You can template your script.

   You can declare the variable using Name and Value in Script Input Variables and then reference the variable in the script just as you would any other variable: `$var_name`.

   ![](../static/script-input-variable.png)
```

2024-01-05 14:58 UTC, aimurphy approved these changes

2024-01-05 14:58 UTC, merged