Create deploy-delegate-to-ECS
harness/developer-hub pull request #484
Opened 2023-01-26 05:05 UTC by kat-enos

Quick step-by-step on how to install an immutable delegate on Amazon ECS and AWS Fargate.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [x ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*: To be noted later on

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-26 05:44 UTC, pratmit requested changes

2023-01-26 05:44 UTC, pratmit commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +title: Deploy a NextGen delegate to Amazon ECS
There is no NextGen Delegate. Rephrase this to " Deploy a Delegate to Amazon ECS in Harness Nextgen".

2023-01-26 05:44 UTC, pratmit commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +# Deploy a NextGen delegate to Amazon ECS
Same as above, NextGen delegate is not the right name.

2023-01-26 05:44 UTC, pratmit commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +## Deploy a delegate to Amazon Fargate
Deploy a delegate to Amazon Fargate in Harness NextGen.

2023-01-26 05:47 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +title: Deploy a NextGen delegate to Amazon ECS
I thought that was awkward ("to Amazon ECS in Harness NextGen") so tried to create a simpler title. Could also try "Use Harness NextGen to deploy a delegate to Amazon ECS".

2023-01-26 05:49 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +# Deploy a NextGen delegate to Amazon ECS
Once the context is set, it's not necessary to repeat it anyway. We could just talk about deploying a delegate and say that the process requires NextGen too. You don't usually get or want to say everything in the title -- makes it too long. Usually you set the context/requirements in the first paragraph.

2023-01-26 05:49 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +# Deploy a NextGen delegate to Amazon ECS
But I'll integrate whatever changes, including these, tomorrow.

2023-01-26 05:55 UTC, pratmit commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +# Deploy a NextGen delegate to Amazon ECS
That works for me but we can't say NextGen Delegate.

2023-01-26 20:01 UTC, pratmit commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +# Deploy a delegate to Amazon ECS or AWS Fargate
Deploy a docker delegate

2023-01-27 00:59 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +# Deploy a NextGen delegate to Amazon ECS
Fixed.

2023-01-27 01:05 UTC, pratmit submitted a review, later dismissed

2023-01-27 05:18 UTC, bharatgoelharness commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +
For image also we can add a description
IMAGE: Check the newer version of delegate image from https://hub.docker.com/r/harness/delegate/tags

2023-01-27 06:12 UTC, bharatgoelharness commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +
Here also we should add for image

2023-01-27 06:14 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +
Yes. Trying to fix that now.  :]
But I don't see an IMAGE env var in the YAML. Does IMAGE refer to the "image" field?

2023-01-27 06:20 UTC, kat-enos commented on docs/platform/2_Delegates/advanced-installation/deploy-delegate-to-ECS
> +
Now it's in both tables Bharat. Is that what you want? But there is no env var with the same IMAGE -- just the "image" field. Is that okay?

2023-01-27 06:39 UTC, pratmit approved these changes
LGTM

2023-01-27 22:00 UTC, merged

2023-01-27 22:00 UTC, kat-enos commented
Banzai!