feat [IDP-1959] : Added the release notes for the IDP v0.18.0
harness/developer-hub pull request #4886
Opened 2024-01-11 06:07 UTC by Debanitrkl

# Harness Developer Pull Request
Added the release notes for the IDP v0.18.0

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-01-11 06:43 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +Since it's the first release of the year, we've wrapped up some interesting features for you, including a new Devtools Plugin and revamped RBAC roles.
```suggestion
Since it's the first release of the year, we've wrapped up some interesting features for you, including a new Devtools Plugin and revamped access control permissions.
```

2024-01-11 06:43 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +- RBAC is revamped with new roles (IDP Admin and IDP Platform Engineering) and permissions.
```suggestion
- Access Control is revamped with new roles (IDP Admin and IDP Platform Engineering) and permissions. 
```

2024-01-11 09:23 UTC, sandeepa-kv-jois requested changes

2024-01-11 09:23 UTC, sandeepa-kv-jois commented on release-notes/internal-developer-portal.md
> +
We can also mention about project picker enhancement to not limit the number of projects to 50

2024-01-11 09:24 UTC, sandeepa-kv-jois requested changes

2024-01-11 09:24 UTC, sandeepa-kv-jois commented on release-notes/internal-developer-portal.md
> +
Also, the platform favorites support

2024-01-11 09:27 UTC, sandeepa-kv-jois requested changes

2024-01-11 09:27 UTC, sandeepa-kv-jois commented on release-notes/internal-developer-portal.md
> +
+ [Regex support for filename](https://harness.atlassian.net/browse/IDP-1825) cc: @vigneswara-propelo

2024-01-12 04:25 UTC, sandeepa-kv-jois requested changes

2024-01-12 04:25 UTC, sandeepa-kv-jois commented on release-notes/internal-developer-portal.md
> +![](./static/checks-idp.png)
We can mention plugin page revamp as well!

2024-01-12 05:14 UTC, sandeepa-kv-jois approved these changes

2024-01-12 05:15 UTC, merged