[FEAT] CCM 15393: Adding information about CAG for GCP
harness/developer-hub pull request #5062
Opened 2024-01-23 03:11 UTC by joeyouss

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [x] Issue
- [ ] Feature
- [] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-01-30 11:06 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +Currently, Harness supports GCP, AWS and Azure cloud governance.
Keep it sorted: AWS, Azure, GCP.

2024-01-30 11:06 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-azure.md
> +| **Cloud Governance** (Optional)              | This feature allows you to optimize your cloud spend and avoid unnecessary costs by rightsizing resources and decommissioning unused instances. For mo
Add example like ec2, ebs, azure.vm, gcp.instance.

2024-01-30 11:42 UTC, rajarshee-harness commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/filter-evalaution-rules.png
@iamanmolm This and another screenshot has the GCP Project Name. Should it be removed or it's fine?

2024-01-30 14:06 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/filter-evalaution-rules.png
Yeah we should hide any internal account information to be shown on docs.

2024-01-31 09:50 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/static/filter-evalaution-rules.png
Thank you for the heads up!

2024-01-31 10:41 UTC, iamanmolm requested changes

2024-01-31 10:41 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-aws.md
> +| **Cloud Governance** (Optional)              | This feature allows you to optimize your cloud spend and avoid unnecessary costs by rightsizing resources and decommissioning unused instances. For mo
Change the resources you had earlier seems correct only EC2, EBS, RDS, S3.

2024-01-31 10:41 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-azure.md
> +<<<<<<< Updated upstream
You also have this unresolved conflict, kindly fix this.

2024-01-31 10:41 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-azure.md
> +| **Cloud Governance** (Optional)              | This feature allows you to optimize your cloud spend and avoid unnecessary costs by rightsizing resources and decommissioning unused instances. For mo
For this change resources to vm, disk, sqlserver, loadbalancer

2024-01-31 10:41 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-azure.md
> +>>>>>>> Stashed changes
Also I can see your stashed changes here in the PR.

2024-01-31 10:41 UTC, iamanmolm commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/commitment-orchestrator/overview.md
How come CO came in this PR?

2024-01-31 10:41 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-gcp.md
> +| **Cloud Governance** (Optional)              | This feature allows you to optimize your cloud spend and avoid unnecessary costs by rightsizing resources and decommissioning unused instances. For mo
For this change resources to instance, disk, sql-instance, image

2024-01-31 11:26 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +Currently, Harness supports GCP, AWS and Azure cloud governance.
Added

2024-01-31 11:26 UTC, joeyouss commented on docs/cloud-cost-management/get-started/onboarding-guide/set-up-cost-visibility-for-azure.md
> +| **Cloud Governance** (Optional)              | This feature allows you to optimize your cloud spend and avoid unnecessary costs by rightsizing resources and decommissioning unused instances. For mo
Added

2024-02-01 06:55 UTC, iamanmolm approved these changes

2024-02-01 16:07 UTC, Rohit-Kaliki commented
https://65ba3651cb39f5caad497b78--harness-developer.netlify.app/docs/cloud-cost-management/use-ccm-cost-governance/asset-governance/asset-governance#cloud-asset-governance-for-aws We should also add Azure and GCP permissions in this page. Other aspects look good to me.

2024-02-01 16:08 UTC, Rohit-Kaliki commented
@joeyouss Going forward can we keep PRs separate for each unique change as much as possible, I see we have multiple changes factored into this PR>

2024-02-01 16:09 UTC, merged