[PL-44116] PL 1.22.x release notes
harness/developer-hub pull request #5141
Opened 2024-01-27 16:44 UTC by saifeemustafaqharness

[PL-46590](https://harness.atlassian.net/browse/PL-46590) PL 1.22.x SaaS release notes

https://harness.atlassian.net/wiki/spaces/PD/pages/21618098251/NG+Release+SAAS+January+22nd+2024+for+1.22.x-+Build

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-01-29 19:01 UTC, brian-f-harness commented on release-notes/platform.md
> +### Version 1.22.x <!--  January 29, 2024 -->
```suggestion
### Version 1.22.3 <!--  January 29, 2024 -->
```

2024-01-29 21:12 UTC, brian-f-harness commented
@saifeemustafaqharness remember to add Zendesk ticket number references when they are included.

2024-01-29 21:31 UTC, brian-f-harness requested changes

2024-01-29 21:31 UTC, brian-f-harness commented on release-notes/platform.md
> +
Added missing Zendesk ticket numbers. Please add them in and consider the additional comments I left for formatting and structure.

2024-01-30 01:25 UTC, pratmit commented
Is there a preview link for this?

2024-01-30 13:20 UTC, brian-f-harness approved these changes
@saifeemustafaqharness Just one version number placeholder update. Otherwise, looks good. You may want to update the preview based on the new commits. The current preview has placeholder version numbers.

2024-01-30 16:25 UTC, pratmit approved these changes
LGTM

2024-01-30 16:35 UTC, merged