GitEx support for Overrrides V2
harness/developer-hub pull request #5192
Opened 2024-01-30 18:01 UTC by krishi0408

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-02-07 13:02 UTC, shylajasun reviewed
Could this be also covered , on the status of the sync with bidirectional sync
Mention overrides also supports bidirectional sync
<img width="1088" alt="image" src="https://github.com/harness/developer-hub/assets/104134358/dd76c22d-59eb-4978-a206-925c19aaa4dd">

2024-02-07 13:02 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +7. In **Git Branch**, select your branch. If your branch isn't listed, enter its name. Create the branch in your repository before entering it in **Git Branch**. Harness does not create the branch fo
Currently only default branch of the repo is supported for overrides

2024-02-15 06:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5192) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5192) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5192) it.</sub>

2024-02-16 00:41 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Inline: Harness stores overrides in its platform.
Rephrase as Overrides are stored in the platform

2024-02-16 00:42 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Remote: Harness overrides is stored in Git.
Overrides are stored in a repository based on users choice

2024-02-16 00:52 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +You can set the overrides as Inline or Remote when you create an override.
Overrides can be stored remote or inline based on users choice

2024-02-16 00:52 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +8. Harness Git Experience auto-populates the **YAML Path** based on the scope oveerides are configured. For example, if you are creating overrides at Project level the YAML path will be ``org/default
Rephrase - based on the scope where overrides are configured

2024-02-16 00:52 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +8. Harness Git Experience auto-populates the **YAML Path** based on the scope oveerides are configured. For example, if you are creating overrides at Project level the YAML path will be ``org/default
in the path examples make it place holders instead of examples

2024-02-16 00:52 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Similar approach can be followed to move other Overrides method to Git.
check if this line is relevant

2024-02-16 00:52 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Oveerides also support [Biderectional Sync](/docs/platform/git-experience/gitexp-bidir-sync-setup.md).
Correct spelling mistakes

2024-02-21 00:04 UTC, SushrutHarness requested changes
Typos mostly

2024-02-21 00:04 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +:::info note
I think our standard is to put the feature flag note at the start of the relevant section. Maybe consider moving this note to the start of this section?

2024-02-23 06:29 UTC, krishi0408 commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +7. Select **Git Branch** , currently only default branch of the repository is supported for overrides.
Yup it can be master or main. Yes for now only default branch is supported.

2024-02-23 07:03 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Currently, Git Experience support for overrides is behind the feature flag `CDS_OVERRIDES_GITX` . Contact [Harness Support](mailto:support@harness.io) to enable the feature.
```suggestion
Currently, Git Experience support for overrides is behind the feature flag `CDS_OVERRIDES_GITX`. Contact [Harness Support](mailto:support@harness.io) to enable the feature.
```

2024-02-23 07:04 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +**Inline**: Overrides are stored in the Harness Platform.
```suggestion
* **Inline**: Overrides are stored in the Harness Platform.
```

2024-02-23 07:04 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +**Remote**: Overrides are stored in a repository based on users choice.
```suggestion
* **Remote**: Overrides are stored in a repository based on users choice.
```

2024-02-23 07:04 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +**Remote**: Overrides are stored in a repository based on users choice.
added bullets

2024-02-23 07:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +When you create overrides, you can store the overrides in one of the following ways:
```suggestion
When you create overrides, you can store them remotely or inline.
```

2024-02-23 07:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Overrides can be stored remotely or inline based on your choice.
```suggestion

```

2024-02-23 07:05 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Overrides can be stored remotely or inline based on your choice.
Deleting this line as we have covered it in the beginning itself, making it minimal.

2024-02-23 07:08 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +This topic explains how to use the Remote option to store your overrides in a repository. We've covered storing overrides in GitHub, you can choose a source code repository based on your preferences.
You can store overrides remotely in a repository. The steps below explains how to store overrides in GitHub. You can choose a source code repository of your choice.

2024-02-23 07:09 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +2. You will have an option to select **Inline** and **Remote** under every override method.
```suggestion
   You will have an option to select **Inline** and **Remote** under every override method.
```

2024-02-23 07:10 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +2. You will have an option to select **Inline** and **Remote** under every override method.
This is an outcome of a step. Marking it as as info below step 1.

2024-02-23 07:10 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +![](./static/overrides_gitex.png)
```suggestion
   ![](./static/overrides_gitex.png)
```

2024-02-23 07:10 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +![](./static/remote_overrides.png)
```suggestion
   ![](./static/remote_overrides.png)
```

2024-02-23 07:11 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +7. Select **Git Branch** , currently only default branch of the repository is supported for overrides.
```suggestion
7. Select **Git Branch**. Currently, only default branch of the repository is supported for overrides.
```

2024-02-23 07:11 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +9. Click **Save**.
```suggestion
9. Select **Save**.
```

2024-02-23 07:12 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +9. Click **Save**.
Use select instead of click to support accessibility users.

2024-02-23 07:12 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +Currently, Git Experience support for overrides is behind the feature flag `CDS_OVERRIDES_GITX` . Contact [Harness Support](mailto:support@harness.io) to enable the feature.
```suggestion
Currently, Git Experience support for overrides is behind the feature flag `CDS_OVERRIDES_GITX`. Contact [Harness Support](mailto:support@harness.io) to enable the feature.
```

2024-02-23 07:14 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +2. You will have an option to select **Inline** and **Remote** under every override method.
You can delete this step.

2024-02-23 07:16 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +2. You will have an option to select **Inline** and **Remote** under every override method.
```suggestion

```

2024-02-23 07:19 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +3. Select your **Environment** in case of **Global Environment** override method.
```suggestion
3. Under the **Global Environment** tab, select your **Environment**. 
    You have the option to select **Inline** or **Remote** code source under all override methods.
```

2024-02-23 07:19 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +5. In **Git Connector**, select or create a Git connector to the repo for your environment.​ For more information, go to [Code Repo Connectors](/docs/category/code-repo-connectors).
```suggestion
5. In **Git Connector**, select or create a Git connector to the repository for your environment.​ For more information, go to [Code Repo Connectors](/docs/category/code-repo-connectors).
```

2024-02-23 07:19 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +6. In **Repository**, select your repository. If your repository isn't listed, enter its name. Create the repository in Github before entering it in **Repository**. Harness does not create the reposi
```suggestion
6. In **Repository**, select your repository. If your repository isn't listed, enter its name. 
    Create the repository in Github before entering it in **Repository**. Harness does not create the repository for you.
```

2024-02-23 07:20 UTC, roshnisarangadharan reviewed
Added a few comments.

2024-02-23 10:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +This topic explains how to use the Remote option to store your overrides in a repository. We've covered storing overrides in GitHub, you can choose a source code repository based on your preferences.
```suggestion
You can store overrides remotely in a repository. The steps below explains how to store overrides in GitHub. You can choose a source code repository of your choice.
```

2024-02-23 10:47 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +    You have the option to select **Inline** or **Remote** code source under all override methods.
```suggestion
   You have the option to select **Inline** or **Remote** code source under all override methods.
```

2024-02-23 10:48 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/overrides-v2.md
> +    Create the repository in Github before entering it in **Repository**. Harness does not create the repository for you.
```suggestion
   Create the repository in Github before entering it in **Repository**. Harness does not create the repository for you.
```

2024-02-23 10:52 UTC, roshnisarangadharan approved these changes
Approved with minor format changes. LGTM.

2024-02-26 08:45 UTC, merged