first draft of the docs
harness/developer-hub pull request #5228
Opened 2024-02-01 09:49 UTC by joeyouss

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-02-06 15:54 UTC, Additi requested changes
@joeyouss Please review the changes and ensure consistency on terms across in the whole page.

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Reserved Instances are a pricing model offered by cloud service providers that allows customers to reserve and commit to a specific amount of computing capacity in advance for a term of one or three
@joeyouss Please add the definition of SP as well and also mention what they are called in each cloud provider's context.

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +However, it's essential for organizations to carefully analyze their usage patterns before making commitments to ensure they choose the most suitable Reserved Instances for their needs.
Everywhere please add Saving plan along with RIs. @joeyouss

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +In recent years, organizations leveraging cloud services have witnessed a concerning trend - the steady rise in cloud costs. As businesses increasingly migrate their operations to the cloud, the expe
We should not call it as a concerning trend but rather a growing business implying to huge cloud costs as most organisations are either moving from on-prem or increasing their business in cloud front.

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Some commitments, such as rigid long-term contracts, may lack flexibility to adapt to changing circumstances or unexpected events
What is referred to as rigid long term contracts here?

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +At Harness, we are committed to bring in the power of **AI and ML** to manage the commitments. Harness CCM helps you to track everything about your cloud spends so that you have an optimized cloud sp
"mitigating the problems associated with automated management of commitments."  This should be manual management of commitments not automated. @joeyouss

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +In the context of cloud spend or cloud bills breakdown,, over-commitment and under-commitment typically refer to the utilization of resources compared to the commitments made through mechanisms like
commitments made through discount plans (not mechanism)

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +For example, an organization may have purchased a significant number of Reserved Instances based on an initial estimation of their workload. If the actual usage turns out to be lower than expected, t
@joeyouss  orgnaisation is not considered to be over-committed, but the resources they have deployed are over committed leading to wastage and under utlisaition .

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Commitment Orchestrator can be found on our dashboard under Cloud Costs. Commitment Orchestrator can be easily setup from the dashboard itself by following these steps:
@joeyouss under cloud costs meaning?

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Commitment Orchestrator provides you with an option to choose the instances you would like to exclude when orchestrating instances for Compute Usage.
@joeyouss Note:  The purchases will happen only at master account level and thus will be in turn applicable for child accounts as well. The exclusion list will only be considered for the compute spend calulations and actual RI/SP may be used against the instances if they are part of child accounts.

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Coverage Percentage: The Coverage percentage is the percentage that you want to be covered by Savings Plans or Reserved Instances. The remaining amount will continue to run as on-demand.
you want to cover your compute spend by SP/RIs. The remaining coverage will continue...

2024-02-06 15:54 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +SP/RI split: Out of the totally compute spend, you have the option to split it between Convertible Reserved Instances and Compute Savings Plan
Out of total coverage, the system automatically calculates the maximum guardrail for purchasing the Savings Plans given the past compute spend data to ensure limiting any over purchase of saving plans. You can reduce the percentage by increasing share of Reserved Instances. However, you can't increase the coverage via Savings Plan beyond the max limit.

2024-02-08 09:48 UTC, joeyouss commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Reserved Instances are a pricing model offered by cloud service providers that allows customers to reserve and commit to a specific amount of computing capacity in advance for a term of one or three
done

2024-02-08 09:56 UTC, joeyouss commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Some commitments, such as rigid long-term contracts, may lack flexibility to adapt to changing circumstances or unexpected events
commitments made with cloud service providers for a fixed duration - by rigid I mean that once they sign contract, the organisation Is locked into using the agreed-upon resources

2024-02-08 09:58 UTC, joeyouss commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +At Harness, we are committed to bring in the power of **AI and ML** to manage the commitments. Harness CCM helps you to track everything about your cloud spends so that you have an optimized cloud sp
Amm, in one comment on the doc, it was mentioned "The things that we do: 
Automated commitment purchasing and management"

so we do automated purchasing only?

2024-02-08 10:01 UTC, joeyouss commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +In the context of cloud spend or cloud bills breakdown,, over-commitment and under-commitment typically refer to the utilization of resources compared to the commitments made through mechanisms like
done

2024-02-08 10:06 UTC, joeyouss commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +For example, an organization may have purchased a significant number of Reserved Instances based on an initial estimation of their workload. If the actual usage turns out to be lower than expected, t
done

2024-02-08 10:12 UTC, joeyouss commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +Commitment Orchestrator can be found on our dashboard under Cloud Costs. Commitment Orchestrator can be easily setup from the dashboard itself by following these steps:
https://app.harness.io/ - added backlink for this

2024-02-19 10:06 UTC, Additi approved these changes

2024-02-19 11:07 UTC, merged