add remote varfile doc
harness/developer-hub pull request #5240
Opened 2024-02-02 01:38 UTC by urischeiner

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-02-02 09:05 UTC, RickCraig requested changes
Only one's we _need_ to change would be the JXEL -> JEXL, others are suggestions.

2024-02-02 09:05 UTC, RickCraig commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +Users can define a Terraform configuration with multiple workspaces to enforce the same desired configuration. Each Workspace creates a different state from the configuration and independent lifecycl
```suggestion
Users can define a Terraform configuration with multiple workspaces to enforce the same desired configuration. Each Workspace creates a different state with it's own independent lifecycle.
```

Just a suggestion

2024-02-02 09:05 UTC, RickCraig commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +   * **Environment Variables** can be either String, [Secret](/docs/category/secrets), or a reference to another variable using [JXEL expression](https://developer.harness.io/docs/platform/variables-
```suggestion
   * **Environment Variables** can be either String, [Secret](/docs/category/secrets), or a reference to another variable using [JEXL expression](https://developer.harness.io/docs/platform/variables-and-expressions/harness-variables/) (it can be in the same or a different workspace or from the pipeline). 
```

2024-02-02 09:05 UTC, RickCraig commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +     * **Inline** Users can define Terraform variables within the Workspace. Variables can be either String, [hcl](https://developer.hashicorp.com/terraform/language/syntax/configuration), [Secret](/
```suggestion
     * **Inline** Users can define Terraform variables within the Workspace. Variables can be either String, [hcl](https://developer.hashicorp.com/terraform/language/syntax/configuration), [Secret](/docs/category/secrets), or a reference to another variable, using [JEXL expression](https://developer.harness.io/docs/platform/variables-and-expressions/harness-variables/) (can be in the same or a different workspace, or from the pipeline). 
```

2024-02-02 09:05 UTC, RickCraig commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +
```suggestion
```

2024-02-02 09:05 UTC, RickCraig commented on docs/infra-as-code-management/workspaces/create-workspace.md
> +
This suggestion is just to remove an extra line

2024-03-21 19:16 UTC, aimurphy commented
This PR is getting stale. How can #docs-council help to move it forward?

2024-03-21 19:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5240) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5240) it.</sub>

2024-03-21 19:48 UTC, urischeiner commented
@RickCraig can you please review and merge

2024-03-21 19:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5240) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: aimurphy<br/>:x: urischeiner<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5240) it.</sub>

2024-03-25 14:48 UTC, RickCraig approved these changes

2024-03-25 14:48 UTC, merged