Release notes for 1.23.x
harness/developer-hub pull request #5249
Opened 2024-02-02 18:33 UTC by krishi0408

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2024-02-02 18:56 UTC, SushrutHarness commented
@krishi0408 I made some changes, please review them!

2024-02-02 18:56 UTC, SushrutHarness approved these changes
LGTM

2024-02-02 21:08 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- Application logs used to get printed in TAS deployment logs, the issue is fixed by introducing a new environment variable `DISABLE_CF_APP_LOG_STREAMING` and when it’s set to true it will redact all
```suggestion
- Application logs used to get printed in TAS deployment logs, the issue is fixed by introducing a new environment variable `DISABLE_CF_APP_LOG_STREAMING` and when it’s set to true it will redact all application logs, providing users with more flexibility in managing log visibility. (CDS-89172, ZD-56849)
```

2024-02-02 21:09 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- Parent pipeline has a chained pipeline stage and both the parent and child pipelines are in different organizations. While running the parent pipeline, the user group selection for the child approv
```suggestion
- Parent pipeline has a chained pipeline stage and both the parent and child pipelines are in different organizations. While running the parent pipeline, the user group selection for the child approver user group displays parent pipeline organizations. The issue has now been fixed, and users should be able to select the correct user group(s) of the child pipeline that belong to a different or the same organization. (CDS-89001, ZD-55502)
```

2024-02-02 21:11 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- Approval message offset was not set properly, the issue is fixed now. (CDS-88839)
This one may have moved out of the release?  Not on the current list.

2024-02-02 21:11 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- When service was selected from **Projects** > **Service** > **Select Service** it used to open the configuration tab and when service was selected from **Deployments** > **Services** > **Select Ser
```suggestion
- When service was selected from **Projects** > **Service** > **Select Service** it used to open the configuration tab and when service was selected from **Deployments** > **Services** > **Select Service** it used to open the summary tab. The issue for this different behavior is now fixed and now via both ways, users will be taken to the service's summary tab. (CDS-88692, ZD-56528)
```

2024-02-02 21:12 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- Jenkins `jobParameter` was getting added to the pipeline even if it was not a runtime input in the template. The issue is fixed now and `jobParameter` will not be added automatically. (CDS-88380)
```suggestion
- Jenkins `jobParameter` was getting added to the pipeline even if it was not a runtime input in the template. The issue is fixed now and `jobParameter` will not be added automatically. (CDS-88380, ZD-55212)
```

2024-02-02 21:14 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- Wrong target groups were getting attached when multiple load balancers were used with the same load balancer name. The issue is fixed now. (CDS-89615,ZD-55701)
Is this CDS-88229, not CDS-89615?

2024-02-02 21:14 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- When service is marked as runtime in a child pipeline and then configured from the chained pipeline inputs tab, the service input fields are left as runtime. The Trigger Input panel and Input-set f
```suggestion
- When the service is marked as runtime in a child pipeline and then configured from the chained pipeline inputs tab, the service input fields are left as runtime. The Trigger Input panel and Input-set form do not properly prompt for service input. This issue has been resolved. (CDS-87983, ZD-55917)
```

2024-02-02 21:16 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- There was a duplicate key error on stage execution info collection. The issue is fixed now. (CDS-85208)
Is this item still on the list?

2024-02-02 21:17 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +### Version 1.23.0
Suggest adding new heading for February and moving items under it.

2024-02-02 21:19 UTC, brian-f-harness commented
@krishi0408 I added some suggestions to add Zendesk ticket reference numbers. We want to be sure we include these for all applicable RNs. Customers search release notes to see if their items are resolved in the release. Also, there were some items included that were not on the RN list for 1.23.x. Let me know if you have questions.

2024-02-02 21:20 UTC, brian-f-harness requested changes
Suggest adding Zendesk ticket numbers for customer reference.

2024-02-02 21:22 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- Issue while selecting VPC if name is empty. VPC name is optional in AWS console but id is always there, but if the name is empty it is not getting selected. The issue is fixed now and instead of `v
```suggestion
- Issue while selecting VPC if the name is empty. VPC name is optional in the AWS console but the id is always there, but if the name is empty it is not getting selected. The issue is fixed now and instead of `vpc.name` it will get displayed as `vpc.id:vpc.name`. (CDS-89297)
```

2024-02-02 21:42 UTC, SushrutHarness commented on release-notes/continuous-delivery.md
> +- Approval message offset was not set properly, the issue is fixed now. (CDS-88839)
The NG_UI_SAAS version is listed as 1.6.0 which means it should be in the 1.23.xx release. Where are you seeing the current list of issues?

2024-02-02 21:45 UTC, SushrutHarness commented on release-notes/continuous-delivery.md
> +- Wrong target groups were getting attached when multiple load balancers were used with the same load balancer name. The issue is fixed now. (CDS-89615,ZD-55701)
Looks like thats the case, seems that CDS-89615 is a hotfix ticket for CDS-88229 that was marked invalid.

2024-02-02 21:45 UTC, brian-f-harness commented on release-notes/continuous-delivery.md
> +- Approval message offset was not set properly, the issue is fixed now. (CDS-88839)
> The NG_UI_SAAS version is listed as 1.6.0 which means it should be in the 1.23.xx release. Where are you seeing the current list of issues?

https://harness.atlassian.net/wiki/spaces/PD/pages/21628289360/NG+Release+SAAS+January+29th+2024+for+1.23.x-+Build#Release-Notes-Eligible-Tickets

This is the page Akhil provides each release based on the Release Note Candidate set to Yes in Jiras. 

Here's the top level page: https://harness.atlassian.net/wiki/spaces/PD/pages/21596897283/Release+Notes+2024

2024-02-02 21:59 UTC, SushrutHarness commented on release-notes/continuous-delivery.md
> +- WinRm connector was missing the back button. The issue is fixed now. (CDS-86773)
It was marked as not a release notes candidate, but this seems useful to put on this list.

2024-02-02 22:13 UTC, brian-f-harness approved these changes
Spoke to @SushrutHarness about recommended changes.

2024-02-04 16:56 UTC, krishi0408 commented
> @krishi0408 I added some suggestions to add Zendesk ticket reference numbers. We want to be sure we include these for all applicable RNs. Customers search release notes to see if their items are resolved in the release. Also, there were some items included that were not on the RN list for 1.23.x. Let me know if you have questions.

Thanks @brian-f-harness , I guess they might have changed to No after I made the PR. Thanks for headsup

2024-02-05 11:20 UTC, merged