Cache intelligence doc 2506
harness/developer-hub pull request #528
Opened 2023-01-30 23:09 UTC by douglas-j-bothwell

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-01-30 23:23 UTC, jamie-harness requested changes

2023-01-30 23:23 UTC, jamie-harness commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +curl --location --request GET 'https://app.harness.io:7171/cache/info?accountIdentifier=$HARNESS_ACCOUNT_ID' \
should be app.harness.io/gateway/ci/cache/info?accountIdentifier=$HARNESS_ACCOUNT_ID

let's not use port number in qa or prod. The #3,4,5 requests in the collections are from QA. Let's use the similar for official doc

2023-01-30 23:23 UTC, jamie-harness commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +curl --location --request DELETE 'https://app.harness.io:7171/cache/info?accountIdentifier=$HARNESS_ACCOUNT_ID' \
ditto

2023-01-30 23:27 UTC, jamie-harness submitted a review, later dismissed

2023-01-30 23:28 UTC, jamie-harness commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +curl --location --request DELETE 'https://app.harness.io/gateway/ci/cache/info?accountIdentifier=$HARNESS_ACCOUNT_ID' \
also an optional parameter &path here. You can delete a sub-folder

2023-01-30 23:48 UTC, michaelcretzman approved these changes
approved with assumption that you'll consider my suggestions.

2023-01-30 23:48 UTC, michaelcretzman commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +  - Basel, Maven, Gradle, Yarn, and Node frameworks
```suggestion
  - Harness Cloud build infrastructures.
  - Basel, Maven, Gradle, Yarn, and Node frameworks.
```

2023-01-30 23:48 UTC, michaelcretzman commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +  - Basel, Maven, Gradle, Yarn, and Node frameworks
I think periods are required. I think it's for sentences, mainly, but seeing a mix looks weird. Your call.

2023-01-30 23:48 UTC, michaelcretzman commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +### Cache and Reuse Data for Your Fetch Operations
```suggestion
### Cache and reuse data for your fetch operations
```

2023-01-30 23:48 UTC, michaelcretzman commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +#### Automatic Caching
```suggestion
#### Automatic caching
```

2023-01-30 23:48 UTC, michaelcretzman commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +#### Manual Caching
```suggestion
#### Manual caching
```

2023-01-30 23:51 UTC, jamie-harness commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +
Maybe we should mention the user (that the auth token is generated for) need to have account edit privilege rbac

2023-01-31 00:42 UTC, douglas-j-bothwell commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +
@jamie-harness So download and delete cache data, a user needs an API key with the [core_account_edit](https://developer.harness.io/docs/platform/Role-Based-Access-Control/ref-access-management/api-permissions-reference) permission specifically?

2023-01-31 00:45 UTC, jamie-harness commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +
Download no. Download is through pipelines, we don't have a public API for that. 
This get call only gets the stored cache information, like size, which path is cached etc.

I just saw line 89: it should get cache metadata or something like that.

And yes, core_account_edit is needed for both APIs

2023-01-31 06:22 UTC, jamie-harness commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +Get metadata about the cache, such as size and location.
location is a little ambiguous here I think. It should be either directories cached or paths being cached. It's the directory path that the cache is stored in. For example, if you do a maven build, there will be cache populated in /root/.m2 and we save that cached folder to the bucket storage we are hosting. and that /root/.m2 will be returned in this API. Indicating that this is the folder where the cache originally came from, and is also where the cache will be restored when a restore step (in pipeline) is used. 

Location sometimes means bucket location, which can be bucket region (i.e. us-east-2) or location cache is stored to (bucket name, IP address, etc), and this information we are hiding. 

However, I don't have a strong opinion on this one. It's usually not ambiguous, mentioning just in case.

2023-02-06 20:37 UTC, hemanthmantri reviewed
I think Cache Intelligence deserves a documentation page of its own.

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +  - Basel, Maven, Gradle, Yarn, and Node frameworks
Bazel

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +  - Harness Cloud build infrastructures
infrastructure

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +[manual caching](#manual-caching)
What's with reference to manual caching here?

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +To enable automatic caching on a CI Build stage, add the following lines to  the stage YAML definition:
We are marketing this as "Cache Intelligence" so wonder if we should call it so instead of "Automatic Caching"

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +This feature includes the following API calls.
Cache management API

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +You must have an API Key with [core_account_edit](/docs/platform/Role-Based-Access-Control/ref-access-management/api-permissions-reference#harness-api-permissions) permissions to use these commands.
"invoke these APIs." instead of "use these commands."

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +#### Delete cache for pipeline
The cache is at the account level.

2023-02-06 20:37 UTC, hemanthmantri commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +[automatical caching](#manual-caching)
Says "automatical" in manual section.

2023-02-08 19:46 UTC, closed without merging