CHAOS-4002 Resilience probes create, use, edit
harness/developer-hub pull request #5317
Opened 2024-02-08 05:11 UTC by SmritiSatya

Resilience probe introduction, usage

2024-02-12 04:46 UTC, S-ayanide requested changes
Left some comments

2024-02-12 04:46 UTC, S-ayanide commented on docs/chaos-engineering/technical-reference/resilience-probes/introduction.md
> +It is a tedious task to predict or test exhaustively for how and when failures will occur in a production environment. Resilience probes will help simulate various failures, thereby testing how your
This paragraph explains a chaos fault, rather than a resilience probe. Since a fault helps simulate various failures in an experiment, a probe however, is just a pluggable check to run validation on top of your hypothesis. Please refer: https://youtu.be/bocVdb7mjO4?si=ItITJ-5Gz2icOUb3&t=1379

2024-02-12 04:46 UTC, S-ayanide commented on docs/chaos-engineering/technical-reference/resilience-probes/introduction.md
> +This feature creates a global instance of probes, that is, a shared entity that can be used across multiple faults. This feature also brings reusability since you create the validation instance first
In the last line, instead of `avoids repeated creation of same faults for similar requirements.` is should be `avoids repeated creation of same probes for similar requirements.`

2024-02-12 04:46 UTC, S-ayanide commented on docs/chaos-engineering/technical-reference/resilience-probes/introduction.md
> +## Generic runProperties for all probes
Should we use camel casing here? Since `runProperties` is a backend terminology and something we write in the manifest!

2024-02-12 04:46 UTC, S-ayanide commented on docs/chaos-engineering/technical-reference/resilience-probes/probe-acceptance-criteria.md
> +You can [create a probe](/docs/chaos-engineering/technical-reference/resilience-probes/use-probe#create-a-resilience-probe) from within an experiment or from the **Resilience Probes** tab.
If a first time user is wanting to create a resilience probe directly from chaos studio drawer (from within an experiment) they would see an option to add a system probe (which is a health check system probe) as a one click button. This would go away if they have atleast one resilience probe configured.

This information can be added as a note or in another section whichever you find better.

2024-02-12 04:46 UTC, S-ayanide commented on docs/chaos-engineering/technical-reference/resilience-probes/probe-acceptance-criteria.md
> +Command probes in the **Source** mode is only available for Linux on the self-managed platform (SMP).
Source in cmd is available for k8s for both saas and smp. In SMP source is available only for k8s but not for linux. Wanted to reiterate this statement since got a bit confused reading the above.

2024-03-08 09:24 UTC, closed without merging

2024-03-08 09:24 UTC, SmritiSatya commented
https://github.com/harness/developer-hub/pull/5784 new PR since the structure of docs was changed