CHAOS-3328 Update connect-chaos-infrastructures.md
harness/developer-hub pull request #5375
Opened 2024-02-12 09:55 UTC by SmritiSatya

Specify Helm chart support for chaos infra installations

2024-02-29 11:39 UTC, SarthakJain26 requested changes

2024-02-29 11:39 UTC, SarthakJain26 commented on docs/chaos-engineering/chaos-infrastructure/connect-chaos-infrastructures.md
> +1. Download the helm repository. This repository contains all the chaos resources required for chaos infrastructure management. The repository also contains resources necessary for namespace and scop
@SmritiSatya the changes are already in stress, and will be available in QA. You can attach screen shots if needed.

2024-02-29 11:39 UTC, SarthakJain26 commented on docs/chaos-engineering/chaos-infrastructure/connect-chaos-infrastructures.md
> +
Can you please also add a point that "the flags in the command are based on the input provided by users, whereas to override other values, they can do it by changing it in values.yaml file"

2024-03-06 13:06 UTC, SmritiSatya commented
https://github.com/harness/developer-hub/pull/5739 Created a new PR since revamp changed the structure of the docs

2024-03-06 13:06 UTC, closed without merging