Traffic Routing Step Reference done
harness/developer-hub pull request #5416
Opened 2024-02-13 23:31 UTC by SushrutHarness

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ x] Tested Locally
- [ ] *Optional* Screenshot.

2024-02-13 23:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5416) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5416) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5416) it.</sub>

2024-02-14 05:36 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/canary-deployment-step.md
> +Configure traffic routing for canary deployment pipelines. For more information, see the [Traffic Routing Step Reference page](/docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-re
```suggestion
For information on how to configure traffic routing for Canary deployments, see the [Traffic Routing Step Reference page](/docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md).
```

2024-02-14 05:57 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +title: Kubernetes Traffic Shifting Step
```suggestion
title: Kubernetes Traffic Routing Step
```

2024-02-14 09:48 UTC, roshnisarangadharan approved these changes
@SushrutHarness Approved after making some structural changes to the doc and other minor edits.

2024-02-14 10:03 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +    * **Resource Name:** Name of your resource.
Resource name - will be used in generating kubernetes name for traffic routing resources (name need to be kubernetes resource name compliant)

2024-02-14 10:08 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +        * **Match Type**: Specifies the way you want to match incoming requests to filter them.
it can have one of 3 values (exact, prefix, regex). match type value defines how the rule value is being matched against incoming request.

2024-02-14 10:12 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +    * **Host**: Specify the name of one of your destination hosts here.
host should be the name of the kubernetes service

2024-02-14 10:13 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +    * **Resource Name:** Name of your resource.
Resource name - will be used in generating kubernetes name for traffic routing resources (name need to be kubernetes resource name compliant)

2024-02-14 10:14 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +    * **Host**: Specify the name of one of your destination hosts here.
host should be the name of the kubernetes service resource

2024-02-14 10:17 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +    * **Host**: Specify the name of one of your destination hosts here.
Important note (only applicable for BlueGreen and Canary deploy steps): 
instead of using specific kubernetes service resource names we have provided placeholders which you can use for host names.

`stable` and  `stage` - for BG

`stable` and  `canary` - for Canary

these placeholders will be replaced by the actual kubernetes service resource names which were generated during the BG/Canary deployment.

2024-02-14 10:21 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +### Config Type
what about inherit type?

2024-02-14 10:23 UTC, markoharness requested changes
I don't see the link to Traffic Routing config in the BG deploy step page.

2024-02-14 23:02 UTC, SushrutHarness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +### Config Type
I talk about it on line 24, a few lines down. What is an improvement that can be made here?

2024-02-15 21:52 UTC, thisrohangupta approved these changes
This looks good.

2024-02-15 21:53 UTC, thisrohangupta approved these changes

2024-02-15 21:58 UTC, SushrutHarness commented
Need to bypass requested changes. Changes are made but Marko is OOO

2024-02-15 21:58 UTC, closed without merging

2024-02-16 12:04 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +    * **header**:
nit: headers

2024-02-16 12:04 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +    * **header**:
nit: headers

2024-02-16 12:04 UTC, markoharness commented on docs/continuous-delivery/deploy-srv-diff-platforms/kubernetes/cd-k8s-ref/traffic-shifting-step.md
> +Currently, we only support specs.smi-spec.io/v1alpha3 and specs.smi-spec.io/v1alpha4 resources.
maybe we can give better explanation. 

We currently only support specs.smi-spec.io/v1alpha3 and specs.smi-spec.io/v1alpha4 versions of TrafficSplit resource having in mind that only these versions support having rules (like uri, method, headers as described later)