[PL-47565] PL SMP 0.14.0 Release Notes
harness/developer-hub pull request #5437
Opened 2024-02-15 14:42 UTC by saifeemustafaqharness

[PL-47565](https://harness.atlassian.net/browse/PL-47565)

0.14.0 - https://harness.atlassian.net/wiki/spaces/PD/pages/21654175763/Release+Notes+tickets+for+0.14.0+release

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screenshot.

2024-02-15 14:58 UTC, brian-f-harness requested changes
@saifeemustafaqharness Added suggestions to update the Air Gap alternative download method vernos.

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +| Helm Chart | [0.14.x](https://github.com/harness/helm-charts/releases/tag/harness-0.14.x) |
```suggestion
| Helm Chart | [0.14.0](https://github.com/harness/helm-charts/releases/tag/harness-0.14.0) |
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +| Air Gap Bundle | [0.14.x](https://console.cloud.google.com/storage/browser/smp-airgap-bundles/harness-0.14.x) |
```suggestion
| Air Gap Bundle | [0.14.0](https://console.cloud.google.com/storage/browser/smp-airgap-bundles/harness-0.14.0) |
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/ccm_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/ccm_images.tgz" \
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/cdng_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/cdng_images.tgz" \
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/ce_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/ce_images.tgz" \
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/cet_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/cet_images.tgz" \
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/ci_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/ci_images.tgz" \
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/ff_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/ff_images.tgz" \
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/platform_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/platform_images.tgz" \
```

2024-02-15 14:58 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +  "gs://smp-airgap-bundles/harness-0.13.4/sto_images.tgz" \
```suggestion
  "gs://smp-airgap-bundles/harness-0.14.0/sto_images.tgz" \
```

2024-03-01 05:54 UTC, brian-f-harness submitted a review, later dismissed
Looks good from a docs perspective.

Added a few minor suggestions to fix some spacing issues, mostly for CD tickets. 

Also, please update line five to date: `2024-03-01T10:00` before merging for the RSS feed.
Verify the microservice version numbers with the SMP team via tech review.

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +## February xx, 2024, version 1.22.6
```suggestion
## March 1, 2024, version 1.22.6
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- You can now see AccountID in Switch Account screen(CDS-88728)
```suggestion
- You can now see AccountID in Switch Account screen (CDS-88728)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Grouping and Collapsible are now supported for Overrides(CDS-82376)
```suggestion
- Grouping and Collapsible are now supported for Overrides (CDS-82376)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Option to select secrets in script output variables has been removed.(CDS-86690)
```suggestion
- Option to select secrets in script output variables has been removed. (CDS-86690)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Making edits to more than one variable simultaneously only applied the changes to the last variable in the list(CDS-88198, ZD-56156)
```suggestion
- Making edits to more than one variable simultaneously only applied the changes to the last variable in the list. (CDS-88198, ZD-56156)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Github release trigger were not working as expected because UI didn't show the Conditions(CDS-87647, ZD-55832)
```suggestion
- Github release trigger were not working as expected because UI didn't show the Conditions (CDS-87647, ZD-55832)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Http step with mtls not working due to exception caused during delegate capability check for the step(CDS-87547,ZD-55531)
```suggestion
- Http step with mtls not working due to exception caused during delegate capability check for the step (CDS-87547, ZD-55531)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Pipeline was failing with delegate error to fetch JSON format(CDS-87440,ZD-55387)
```suggestion
- Pipeline was failing with delegate error to fetch JSON format. (CDS-87440, ZD-55387)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Harness bidirectional sync webhook feature not working(CDS-85694,ZD-54338)
```suggestion
- Harness bidirectional sync webhook feature not working. (CDS-85694, ZD-54338)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Template inputs were not showing up in Pipeline editor (CDS-84490)
```suggestion
- Template inputs were not showing up in Pipeline editor. (CDS-84490)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- FF validation used to work for name and ID fields but not any other field (CDS-87581)
```suggestion
- FF validation used to work for name and ID fields but not any other field. (CDS-87581)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- When only one manifest is created in OCT Helm, runtime inputs were not being displayed.(CDS-87941)
```suggestion
- When only one manifest is created in OCT Helm, runtime inputs were not being displayed. (CDS-87941)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +   The issue is fixed by updating the condition in code to select default behaviour if only 1 manifest is available
```suggestion
   The issue is fixed by updating the condition in code to select default behaviour if only 1 manifest is available.
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Pipeline template using a stage template was not honoring ``gitBranch`` field for service selection.(CDS-88378)
```suggestion
- Pipeline template using a stage template was not honoring ``gitBranch`` field for service selection. (CDS-88378)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- The ExecutionList page overflowed the page when not needed.(CDS-88388)
```suggestion
- The ExecutionList page overflowed the page when not needed. (CDS-88388)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Icon for trigger was missing in new nav.(CDS-88529)
```suggestion
- Icon for trigger was missing in new nav. (CDS-88529)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- When attempting to save Stage Templates of Azure Webapp Deployment Type, the screen repeatedly asked to save.(CDS-88930)
```suggestion
- When attempting to save Stage Templates of Azure Webapp Deployment Type, the screen repeatedly asked to save. (CDS-88930)
```

2024-03-01 05:54 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Pipeline invocation failed when searching for the YAML in the wrong branch.(CDS-91080)
```suggestion
- Pipeline invocation failed when searching for the YAML in the wrong branch. (CDS-91080)
```

2024-03-04 14:03 UTC, brian-f-harness submitted a review, later dismissed

2024-03-04 14:03 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +date: 2024-03-01T10:00
```suggestion
date: 2024-03-04T10:00
```

2024-03-04 14:03 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +## March xx, 2024, version 1.22.6
```suggestion
## March 4, 2024, version 1.22.6
```

2024-03-04 17:45 UTC, saifeemustafaqharness commented
@brian-f-harness @pratmit @nataraja2018 @gn-harness 
I have updated all the versions with respect to the newly released 0.14.1, which was previously with respect to 0.14.0

Can you please review it and approve the changes? I believe SMP 0.14.1 has already been released. Thanks

2024-03-04 17:48 UTC, brian-f-harness approved these changes

2024-03-04 18:02 UTC, merged