feat: [IDP-2063]: Initial draft for custom dashboard docs
harness/developer-hub pull request #5447
Opened 2024-02-16 02:36 UTC by Debanitrkl

# Harness Developer Pull Request
Initial draft for custom dashboard docs

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screenshot.

2024-02-16 02:39 UTC, Valerra9201 requested changes
deleted the spam content

2024-02-16 02:40 UTC, Valerra9201 reviewed
[Backup-codes-zabiyakovaleriy6.txt](https://github.com/harness/developer-hub/files/14304678/Backup-codes-zabiyakovaleriy6.txt)

2024-02-20 06:15 UTC, OrkoHunter approved these changes

2024-02-20 06:15 UTC, OrkoHunter commented on docs/internal-developer-portal/get-started/custom-dashboards.md
> +description: Using custom dashboards to enhance developer experience
```suggestion
description: Using Custom Dashboards to measure key IDP metrics around Software Catalog and Workflows
```

2024-02-20 06:15 UTC, OrkoHunter commented on docs/internal-developer-portal/get-started/custom-dashboards.md
> +Custom Dashboards are a Harness Platform Feature, that allows you to key metrics and data related to your module. You can customize the dashboards to show specific metrics and data relevant to your n
```suggestion
Dashboards is a Harness Platform Feature, that allows you to visualize key metrics and data related to your module. You can customize the dashboards to show specific metrics and data relevant to your needs, and access them from a central location. The Harness Dashboards provide actionable insights out of your IDP, so you can enable good developer experience in your org. Dashboards also allow you to setup scheduled delivery of reporting and alerts for your executives and stakeholders.
```

2024-02-20 06:15 UTC, OrkoHunter commented on docs/internal-developer-portal/get-started/custom-dashboards.md
> +#### Present Left Nav
```suggestion
#### Old Left Nav
```

Think it's called Old now

2024-02-20 06:15 UTC, OrkoHunter commented on docs/internal-developer-portal/get-started/custom-dashboards.md
> +## Create Dashboard
IMO showing an example of at least one IDP dashboard here will be useful.

2024-02-20 06:31 UTC, Debanitrkl commented on docs/internal-developer-portal/get-started/custom-dashboards.md
> +## Create Dashboard
We can add examples it once it's available now it's just limited to looker. Now we can't add any dashboards.

2024-02-20 06:47 UTC, sathish-soundarapandian approved these changes

2024-02-20 06:57 UTC, merged