[DOC-3983]
harness/developer-hub pull request #5495
Opened 2024-02-20 17:32 UTC by joeyouss

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [X] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-02-20 17:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5495) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5495) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5495) it.</sub>

2024-02-21 00:14 UTC, SushrutHarness requested changes
typos

2024-02-21 00:14 UTC, SushrutHarness commented on docs/faqs/cloud-cost-management-faqs.md
> +#### Why user traffic is not getting detected when custom exclusion/inclusion is enabled?
```suggestion
#### Why is user traffic not getting detected when custom exclusion/inclusion is enabled?
```

2024-02-21 00:14 UTC, SushrutHarness commented on docs/faqs/cloud-cost-management-faqs.md
> +1. Please make sure the Access logs are enabled in the ALB
What is the ALB?

2024-02-21 00:14 UTC, SushrutHarness commented on docs/faqs/cloud-cost-management-faqs.md
> +```s3:ListBucket
move `s3:ListBucket` onto a new line maybe?

2024-02-21 00:14 UTC, SushrutHarness commented on docs/faqs/cloud-cost-management-faqs.md
> +3. OR Use the RDS Autostopping rule as a dependancy to another Autostopping rule(For example, Autostopping rule for an EC2). As long as the parent resource(EC2) is running, Harness makes sure that de
```suggestion
3. OR Use the RDS Autostopping rule as a dependency to another Autostopping rule (For example, Autostopping rule for an EC2). As long as the parent resource (EC2) is running, Harness makes sure that dependent resource (RDS) is running too.
```

2024-02-21 17:05 UTC, krishi0408 submitted a review, later dismissed

2024-04-30 22:49 UTC, aimurphy commented on docs/faqs/cloud-cost-management-faqs.md
> +```s3:ListBucket
~~~suggestion
```
s3:ListBucket
~~~

2024-04-30 22:57 UTC, aimurphy commented on docs/faqs/cloud-cost-management-faqs.md
> +1. Please make sure the Access logs are enabled in the ALB
It stands for Application Load Balancer.

2024-04-30 23:12 UTC, merged