Update release notes 0.7
harness/developer-hub pull request #560
Opened 2023-02-01 17:59 UTC by SmritiSatya

Release notes 0.7
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

2023-02-02 03:56 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +    * This release adds support for deploying your project on existing chaos infrastructure (also known as the greenfield method of deployment). You can specify the name of the delegate and other det
```suggestion
    * This release adds support for deploying your chaos infrastructures on cluster via existing deployed Harness delegates (also known as the brownfield method of deployment). You can select the connector pointing to the required delegate and other details like installation mode, service account name, and namespace, after which the YAML manifest is generated and sent over to the cluster rather than being downloaded on your system. Once the delegate receives the manifest, It deploys your chaos infrastructure on the selected cluster. Currently, you can only deploy chaos infrastructure using account-level delegates.
```

2023-02-02 03:57 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +    * When you try to connect to a chaoshub that is disconnected, you will not see any faults or experiments in the chaoshub. This release adds a feature such that when you click on a disconnected ch
```suggestion
    * When you try to open a chaoshub that is disconnected, you will not see any faults or experiments in the chaoshub. This release adds a feature such that when you click on a disconnected chaoshub, it tries to synchronize and connect to the chaoshub at least once. 
```

2023-02-02 03:57 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +    * In the **Deployment** tab, when you click on **Pipeline** and select a chaos experiment, you can filter experiments based on their names. This release adds another filter so that you can view e
```suggestion
    * In the **Deployment** tab, when you click on **Pipeline** and select a chaos experiment, you can filter experiments based on their names. This release adds another filter so that you can view experiments based on the target chaos infrastructure.
```

2023-02-02 03:58 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +    * In the **Chaos Experiments** tab, you can see the detailed execution of an experiment's runs by clicking on **View run**. This release makes every run of an experiment clickable so that you can
```suggestion
    * In the **Chaos Experiments** tab, you can see the detailed execution of an experiment's runs by clicking on **View run**. This release makes every run of an experiment clickable so that you can view the detailed execution of an experiment run by just clicking on the experiment run row.
```

2023-02-02 04:00 UTC, Jonsy13 commented on release-notes/chaos-engineering.md
> +* When you hovered over a probe, the name of the probe would not be displayed fully if it was long. Now it has been fixed. (Chaos-990)
```suggestion
* When you hovered over a probe, the details of the probe would overflow if it was long. Now it has been fixed. (Chaos-990)
```

2023-02-02 04:01 UTC, Jonsy13 requested changes
Looks good, PTAL on minor comments!

2023-02-02 05:33 UTC, Jonsy13 submitted a review, later dismissed

2023-02-02 12:53 UTC, deepakbolangady requested changes
Please reach out for a discussion if you need one.

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +    * This release categorizes and displays all the chaos experiments based on the average resilience score. It also displays the number of experiments in each category. It shows three categories, i.
```suggestion
    * This release categorizes and displays all the chaos experiments on the basis of average resilience score. It also displays the number of experiments in each category. It shows three categories, which are for experiments with an average resilience score between 0 and 40, 40 to 80, and 80 to 100. This provides better insights about the chaos experiments and their resilience scores. Previously, the overview page showed only the number of experiments that passed and the number of experiments that failed. 
```
* Check whether I use the right words to replace "i.e.". 
* The first category was described as "between 0 and 40. That wording excludes the values at the extremes (0 and 40). So does the resilience score begin with 1? Or is zero included? If it is included, try "from 0 through 40". However, in that case, 40 lies in two categories. If the extremes are to be included in all categories, even 80 falls in two categories. If an experiment has a resilience score of exactly 80, in which category is it shown? Should we write "from 0 through 39, 40 through 79, and 80 through 100"? That's an example. We will have to find out from engineering.
* Also, global comment: in some descriptions, we describe previous behavior first. Here (and I noticed it elsewhere), we describe the previous behavior at the end. This is not a critical issue, but it helps to be consistent in how we organize our information for easy parsing.

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +    * In the **Chaos Experiments** tab, you can see the detailed execution of an experiment's runs by clicking on **View run**. This release makes every run of an experiment clickable so that you can
```suggestion
    * In the **Chaos Experiments** tab, you can see the detailed execution of an experiment's runs by clicking on **View run**. This release makes every run of an experiment clickable so that you can view the detailed execution of an experiment run.
```
Here's my interpretation of this description: both releases (previous and new) showed detailed information about every run. The previous release did that by providing a button named **View run** next to every run (or maybe a single button that expanded all runs at once). The current release does that by removing the button and making the run (I take "run" here to mean whatever text is used to show a run) itself clickable. Is my interpretation correct? If yes, maybe we can be a little more precise. I re-read this description multiple times before I reached this conclusion. If this change is merely about the removal of a button and addition of equivalent functionality, we should say so. Let me know whether I'm right. Then we can discuss rewording if necessary.

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* Searching for chaos experiments in the search bar only showed experiments that had been run at least once. Now it has been fixed such that when you search for an experiment, the search results incl
```suggestion
* Searching for chaos experiments by using the search bar showed only those experiments that had been run at least once. Now, when you search for an experiment, the search results include those experiments that were aborted and experiments that were saved but not run. (Chaos 916)
```
(Deleted text that would have made it necessary to be clear on what "it" refers to (namely, the search functionality))

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* If some of the parameters were left as empty strings when specifying the target application parameters through a YAML manifest, the user interface for the target application page would crash. This
```suggestion
* When specifying the target application parameters through a YAML manifest, if you left some parameters empty, the user interface of the target application page would stop responding. This has been fixed so that, irrespective of the values that you enter in the YAML manifest, you can change the values of the target application on the user interface. (Chaos-970)
```

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* In a chaos experiment, the fault library would incorrectly show fault categories and fault labels even when the hub had been disconnected. It would persist data from the previously selected chaos h
```suggestion
* In a chaos experiment, the fault library would incorrectly show fault categories and fault labels even when the hub had been disconnected. The fault library would persist data from the previously selected chaos hub. This has now been fixed. A disconnected chaos hub now displays the message “No faults found in the selected hub.” (Chaos-971)
```

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* On the chaos hub screen, you could not scroll over the list of hubs from all places on the screen. Now the scroll bar has been shifted to the extreme right so that you can scroll through from anywh
```suggestion
* On the chaos hub screen, you could not scroll through the list of hubs from any location on the screen. This issue has been fixed by moving the scroll bar to the extreme right of the screen. (Chaos-964)
```
(reworded the second sentence to avoid repeating a number of words)

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* If you hovered over a probe, its details would overflow if it was long. Now it has been fixed. (Chaos-990)
```suggestion
* If you hovered over a probe, its details would overflow if they were too long. Now, it has been fixed. (Chaos-990)
```

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* In the chaos hub, when the number of chaos faults that you wished to view on a page was altered (or increased), it would result in a blank page. Now it has been fixed. (Chaos-984)
Who altered the list? The user? Good to write in the active voice if you know who the actor is (or can explicitly name them). 
```suggestion
* In a chaos hub, if you altered the number of chaos faults that you wished to view on a page, it would result in a blank page. Now it has been fixed. (Chaos-984)
```
Again, we should try to avoid the weak (or empty) "it" as far as possible. How about "Any alteration to the number of chaos faults that you wished to view on a single page in a chaos hub would result in a blank page." (Please reword if necessary.)
Also, is it any alteration or only an increase? Be specific. Don't write both.

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* When a chaos experiment was imported into the chaos hub, it would not be logged as an audit event and would not be displayed on the user interface. It has been fixed. (Chaos-779)
What would not be displayed on the UI? The chaos experiment itself or the audit event entry? Currently, the wording suggests that it could be either. 
Also, optional to reword: "The issue is now fixed" is better than "It has been fixed." (The latter is not wrong at all; it just makes us look like we are in a hurry to finish the description.)

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* If no chaos infrastructure is connected with your project, it previously showed a blank screen. Now it displays the message, "There are no chaos infrastructure in your project." (Chaos-1009)
The empty "it" resurfaces. What showed a blank screen? Again in the second sentence. Also, the message needs a grammatical correction. Please let engineering know. Thanks.

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* In CRON experiments, the scheduled run time would always be shown in GMT. Now it has been fixed to show the run time in your browser’s time zone. (Chaos-1035)
```suggestion
* In CRON experiments, the scheduled run time would always be shown in GMT. Now, it has been fixed to show the run time in your browser’s time zone. (Chaos-1035)
```

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* The parameters in the YAML manifest of different runs of the same chaos experiment were inconsistent with the changes made (if any) in their respective runs. Now it has been fixed.
```suggestion
* The parameters in the YAML manifest of different runs of the same chaos experiment were inconsistent with the changes made (if any) in their respective runs. Now, it has been fixed.
```

2023-02-02 12:53 UTC, deepakbolangady commented on release-notes/chaos-engineering.md
> +* When a component on the user interface was missing due to incompatibilities, the page would crash. Now it has been fixed so that instead of the page crashing, the component field shows as empty. (C
Determine whether you can use "stops responding" instead of "crash" wherever you have to use the latter. It's less jarring on the imagination. Some style guides prohibit its usage. See https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/c/crash. (Might need to search and replace with appropriate text globally.)

2023-02-02 12:59 UTC, SmritiSatya commented on release-notes/chaos-engineering.md
> +    * This release adds support for X-API-KEY authentication for user facing chaos APIs. This way, you can avoid using the JWT token which gives more control over the module and set your own custom e
No, the JWT token gives more access.

2023-02-02 13:03 UTC, SmritiSatya commented on release-notes/chaos-engineering.md
> +* Supports deployment on existing chaos infrastructure
Sure, got it, Deepak.

2023-02-03 14:29 UTC, douglas-j-bothwell approved these changes

2023-02-03 14:29 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
> +    * This release categorizes and displays all the chaos experiments on the basis of average resilience score. It also displays the number of experiments in each category. It shows three categories,
```suggestion
    * This release categorizes and displays all the chaos experiments on the basis of average resilience score. It also displays the number of experiments in each category. It shows three categories based on the average resilience scores of the experiments: 0 through 39, 40 through 79, and 80 through 100. This provides better insights about the chaos experiments and their resilience scores. Previously, the overview page showed only the number of experiments that passed and the number of experiments that failed. 
```

2023-02-03 14:29 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
> +* The parameters in the YAML manifest of different runs of the same chaos experiment were inconsistent with the changes made (if any) in their respective runs. Now, it has been fixed.
Missing the Jira ticket number.

2023-02-03 14:29 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
> +* Enable save and run buttons on the experiment builder (CHAOS-913)
**Save** and **Run**? Capitalized and bolded?

2023-02-03 14:29 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
>      * This release enables the save and run buttons after you tune the application by specifying the parameters on the user interface. As a consequence, the default weight is set to 10 since the user
Same as previous.

2023-02-03 14:29 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
>      * This release divides the edit experiment action into two actions: edit experiment and clone experiment. The edit experiment action helps you make changes to the current (or selected) experiment
```suggestion
    * This release divides the edit experiment action into two actions: Edit Experiment and Clone Experiment. The Edit Experiment action helps you make changes to the current (or selected) experiment. The Clone Experiment action helps you create a new experiment from an already existing experiment. The cloned experiment retains the same configuration as the original experiment with the ability to tune the configurations if required.
```

2023-02-03 14:29 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
> +* When a chaos experiment was deleted, the fault running within the experiment was not stopped). Now it has been fixed such that, when an experiment is deleted, the chaos fault running on the Kuberne
```suggestion
* When a chaos experiment was deleted, the fault running within the experiment was not stopped. Now it has been fixed such that, when an experiment is deleted, the chaos fault running on the Kubernetes cluster is halted, the fault is deleted, and the experiment as a whole is deleted. (CHAOS-782)
```

2023-02-03 14:29 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
> +* When you search for a specific chaos fault and the chaos manager cannot map this chaos fault to a chaos fault icon, the user interface used to display an error. Now, instead of showing the error, i
```suggestion
* When you search for a specific chaos fault and the chaos manager cannot map this chaos fault to a chaos fault icon, the user interface previously displayed an error. Now, instead of showing the error, it silently skips the error logs. (CHAOS-814)
```

2023-02-04 16:12 UTC, merged

2023-02-05 15:43 UTC, douglas-j-bothwell reviewed
One comment to double-check  but otherwise looks good!

2023-02-05 15:43 UTC, douglas-j-bothwell commented on release-notes/chaos-engineering.md
> +* If no chaos infrastructure is connected with your project, a blank screen would be displayed. Now, the message "There are no chaos infrastructure in your project." is displayed. (CHAOS-1009)
"There are no chaos infrastructure in your project." Is this literally what the UI says? Seems to me it should say "There is no chaos infrastructure" (single) or "There are no chaose infrastructures" (plural).

2023-02-05 15:45 UTC, douglas-j-bothwell reviewed
One new comment but otherwise looks good!

2023-02-05 17:25 UTC, SmritiSatya commented on release-notes/chaos-engineering.md
> +* If no chaos infrastructure is connected with your project, a blank screen would be displayed. Now, the message "There are no chaos infrastructure in your project." is displayed. (CHAOS-1009)
Oh yes, the statement is grammatically incorrect. I will change it here. I have already raised a ticket for this with the engg team.

2023-02-05 17:33 UTC, SmritiSatya commented
https://github.com/harness/developer-hub/pull/603 PR to fix the grammar