built-in scanners v0 draft STO-6935
harness/developer-hub pull request #5602
Opened 2024-02-27 23:24 UTC by douglas-j-bothwell

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-02-28 16:32 UTC, priteshchandaliya commented
@douglas-j-bothwell can we say `and/or` instead of just `or` in the following sections

```[SCA](https://65de775f016f6a5cd175337e--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/built-in/sca) Add an OWASP Dependency Check and/or OSV scan to detect vulnerabilities in your open-source libraries and packages.```

```[Container](https://65de775f016f6a5cd175337e--harness-developer.netlify.app/docs/security-testing-orchestration/sto-techref-category/built-in/containers) Add an Aqua Trivy and/or Anchor Grype scan to detect vulnerabilities in your container images.```

2024-03-21 14:08 UTC, jsentongo requested changes

2024-03-21 14:53 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/sto-techref-category/built-in/containers.md
> +- You don't need to add a [Docker-in-Docker background service](/docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference#docker-in-docker-requirements-for-sto) manua
@jsentongo I removed "if it's needed" from the end of this sentence but then added it back. When adding a non-built-in container scan step, you need to add the DinD background step in a k8s or Docker build environment but not in Harness Cloud.

2024-03-21 19:52 UTC, priteshchandaliya commented
@douglas-j-bothwell please change the screenshot to the latest one 
![Screenshot 2024-03-21 at 12 45 26 PM](https://github.com/harness/developer-hub/assets/12145343/fa3ec518-b42b-4411-8c6b-b4c007c864e7)

Typo mistake in Aqua Trivy spelling
![Screenshot 2024-03-21 at 12 51 18 PM](https://github.com/harness/developer-hub/assets/12145343/82e1e356-551f-4b0e-94b7-9d1bfabc996f)

Rest all looks good

2024-03-21 20:59 UTC, merged