feat:[CDS-92800]: fix snow create/update doc
harness/developer-hub pull request #5622
Opened 2024-02-28 18:58 UTC by naman-goenka

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-02-28 23:59 UTC, SushrutHarness submitted a review, later dismissed
LGTM

2024-02-29 05:10 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +In **Template Name**, you can either enter the name of an existing template, select from the list of existing templates that is displayed when you click the field, or provide an expression. You can a
```suggestion
In **Template Name**, you can enter the name of an existing template and a list of existing template names appear. You can either select an existing template from the list, or provide an expression. You can also search for the templates you need.
```

2024-02-29 05:11 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +The searching of form templates requires:
```suggestion
Make sure you have met the following requirements for form templates:
```

2024-02-29 05:11 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +- This feature requires Harness Delegate version 82400 or later.
```suggestion
- Harness Delegate version 82400 or later.
```

2024-02-29 05:12 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +- Atleast `1.0.2` version of the Integration for Harness Software Delivery Platform app
```suggestion
- Integration for Harness Software Delivery Platform app version 1.0.2 or later.
```

2024-02-29 05:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +In **Template Name**, you can either enter the name of an existing template, select from the list of existing templates that is displayed when you click the field, or provide an expression. You can a
```suggestion
In **Template Name**, you can enter the name of an existing template, select from the list of existing templates displayed when you click the field, or provide an expression. You can also search templates you need.
```

2024-02-29 05:17 UTC, naman-goenka commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +In **Template Name**, you can either enter the name of an existing template, select from the list of existing templates that is displayed when you click the field, or provide an expression. You can a
@roshnisarangadharan here it is written this way because manual inputs are also allowed

2024-02-29 05:18 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +Your ServiceNow ticket is now added to your pipeline. After standard template is loaded, fields are marked editable based on `Standard Change Properties` if `change_manager` role is present with the
```suggestion
Your ServiceNow ticket is now added to your pipeline. After standard template is loaded, fields are marked editable based on `Standard Change Properties` if `change_manager` role is present with the integration user. Else, the properties can't be fetched and fields are made read-only as per default settings in the ServiceNow documentation. 
```

2024-02-29 05:19 UTC, roshnisarangadharan submitted a review, later dismissed

2024-02-29 05:19 UTC, roshnisarangadharan commented
@naman-goenka Let me know when to merge.

2024-02-29 05:25 UTC, naman-goenka commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +Make sure you have met the following requirements for form templates:
Only `search` requires delegate version, rest the listing and manual entry works without them as well. Please consider reverting

2024-02-29 05:26 UTC, naman-goenka commented
> @naman-goenka Let me know when to merge.

Waiting for @shylajas to review

2024-02-29 09:28 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +Make sure you have met the following requirements for form templates:
```suggestion
Make sure you have met the following requirements for searching form templates:
```

2024-02-29 09:29 UTC, roshnisarangadharan approved these changes

2024-03-08 10:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +In **Template Name**, you can enter the name of an existing template, select from the list of existing templates displayed when you click the field, or provide an expression. You can also search temp
```suggestion
In **Template Name**, you can enter the name of an existing template, select from the list of existing templates displayed when you select the field, or provide an expression. You can also search the templates you need.
```

2024-03-08 10:18 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +In **Template Name**, you can enter the name of an existing template, select from the list of existing templates displayed when you click the field, or provide an expression. You can also search temp
```suggestion
In **Template Name**, you can enter the name of an existing template, select from the list of existing templates displayed when you select the field, or provide an expression. You can also search the templates you need.
```

2024-03-08 10:18 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/ticketing-systems/create-service-now-tickets-in-cd-stages.md
> +Your ServiceNow ticket is now added to your pipeline. After standard template is loaded, fields are marked editable based on `Standard Change Properties` if `change_manager` role is present with the
Please add a link to the ServiceNow documentation.

2024-03-08 10:21 UTC, roshnisarangadharan requested changes
Please add the ServiceNow doc link as mentioned in the comment. Let me know when ready, I'll approve and merge.

2024-03-08 11:16 UTC, naman-goenka commented
> Please add the ServiceNow doc link as mentioned in the comment. Let me know when ready, I'll approve and merge.

done

2024-03-08 11:42 UTC, roshnisarangadharan approved these changes

2024-03-08 11:42 UTC, merged