Create pipeline-faq.md
harness/developer-hub pull request #5661
Opened 2024-03-01 07:26 UTC by thisrohangupta

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-01 07:50 UTC, ankittiwari-harness approved these changes

2024-03-01 18:49 UTC, SushrutHarness requested changes
Try these changes? Might fix the build issue

2024-03-01 18:49 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: You can use any status value in a JEXL condition. For example, <+pipeline.stages.cond.spec.execution.steps.echo.status> == "FAILED"
```suggestion
A: You can use any status value in a JEXL condition. For example, `<+pipeline.stages.cond.spec.execution.steps.echo.status> == "FAILED"`
```

2024-03-01 18:49 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +The expression <+execution.steps.[step Id].status> resolves to the status of a step. For example, <+execution.steps.mystep.status>.
```suggestion
The expression `<+execution.steps.[step Id].status>` resolves to the status of a step. For example, `<+execution.steps.mystep.status>`.
```

2024-03-01 20:29 UTC, SushrutHarness requested changes
Typos, and visuals

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: Charatcer limit is 128 characters.
```suggestion
A: Character limit is 128 characters.
```

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: You can use any status value in a JEXL condition. For example, `<+pipeline.stages.cond.spec.execution.steps.echo.status> == "FAILED"`
Yea the problem was that the `<` character is reserved in docusaurus essentially. Please take a look at the published netifly link to see if you like how this looks

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: We do not have a trigger, but, we do have a stage called Pipeline Chainging which lets you start a pipeline based on a pipeline completing.
```suggestion
A: We do not have a trigger, but, we do have a stage called Pipeline Chaining which lets you start a pipeline based on a pipeline completing.
```

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +#### Q: How can I specify my pipeline to pick the right delegate my my environment?
```suggestion
#### Q: How can I specify my pipeline to pick the right delegate for my environment?
```

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +#### Q: How long are harness deployment logs visible in the UI?
Repeated question

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: You will not be able to see all pipeline execution under one view as we have 3 level of scoping in Harness Next Gen and based on the organistaion and Project pipeline executions can be seen as pra
```suggestion
A: You will not be able to see all pipeline execution under one view as we have 3 level of scoping in Harness Next Gen and based on the organization and Project pipeline executions can be seen as part of the execution history tab.
```

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: In CIE If you have set a environment variables in stage level it will be available for all steps. In CD you can make use os stage variables or pipeline variables to achieve your usecase of using s
```suggestion
A: In CI If you have set a environment variables in stage level it will be available for all steps. In CD you can make use of stage variables or pipeline variables to achieve your use-case of using the same variables anywhere in pipeline and stages.
```

2024-03-01 20:29 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: In CIE If you have set a environment variables in stage level it will be available for all steps. In CD you can make use os stage variables or pipeline variables to achieve your usecase of using s
Did you mean CI, not CIE?

2024-03-02 00:10 UTC, thisrohangupta commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +A: In CIE If you have set a environment variables in stage level it will be available for all steps. In CD you can make use os stage variables or pipeline variables to achieve your usecase of using s
CIE is the official product name

2024-03-04 21:52 UTC, SushrutHarness approved these changes
Typos again, but approved.

2024-03-04 21:52 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +#### Q: is there a limit to the number of pipelines a project can have?
```suggestion
#### Q: Is there a limit to the number of pipelines a project can have?
```

2024-03-04 21:52 UTC, SushrutHarness commented on docs/platform/pipelines/w_pipeline-steps-reference/pipeline-faq.md
> +#### Q: What has happened to the pause button?
```suggestion
#### Q: What happened to the pause button?
```

2024-03-04 21:52 UTC, SushrutHarness approved these changes
LGTM

2024-03-05 22:45 UTC, merged