Added docs on AWS with OIDC.
harness/developer-hub pull request #5702
Opened 2024-03-05 00:06 UTC by SushrutHarness

# Harness Developer Pull Request
REMEMBER TO ADD FEATURE FLAG TO FEATURE FLAG LIST

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [X] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-05 00:07 UTC, SushrutHarness commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
> +   If you would like to use AWS with OIDC, select **Use OIDC** here and ignore step 3 below.
Two questions:

Is this correct?
Does this bloat the docs?

2024-03-05 00:14 UTC, SushrutHarness commented on docs/continuous-delivery/cd-integrations.md
> +        <td>Enables the option to connect to AWS with OIDC. Only currently supported for Kubernetes, Helm, Terraform, and Cloudformation. <b>This feature is in Beta.</b> </td>
i've listed this feature as in Beta. Is that correct @thisrohangupta ?

2024-03-05 04:30 UTC, roshnisarangadharan commented on docs/platform/connectors/cloud-providers/add-aws-connector.md
> +   The `Use OIDC` credential option is currently behind a feature flag. Contact [Harness Support](mailto:support@harness.io) to enable the feature.
@SushrutHarness please mention the feature flag here.

2024-03-05 04:30 UTC, roshnisarangadharan commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> +The `Use OIDC` credential option is currently behind a feature flag. Contact [Harness Support](mailto:support@harness.io) to enable the feature.
mention the feature flag

2024-03-05 04:31 UTC, roshnisarangadharan commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> +This option is only currently supported for Kubernetes, Helm, Terraform, and CloudFormation deployment types.
```suggestion
Currently, this option is supported only for Kubernetes, Helm, Terraform, and CloudFormation deployment types. 
```

2024-03-05 04:32 UTC, roshnisarangadharan commented on docs/continuous-delivery/cd-integrations.md
> +        <td>Enables the option to connect to AWS with OIDC. Only currently supported for Kubernetes, Helm, Terraform, and Cloudformation. <b>This feature is in Beta.</b> </td>
```suggestion
        <td>Enables the option to connect to AWS with OIDC. Currently, this option is supported only for Kubernetes, Helm, Terraform, and CloudFormation deployment types. <b>This is a Beta feature.</b> </td>
```

2024-03-05 04:33 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
> +If you are using the OIDC credential type for your AWS connector, also add a trust relationship between this IAM role and your identity provider. For information on using OIDC with AWS at Harness see
```suggestion
If you are using the OIDC credential type for your AWS connector, also add a trust relationship between this IAM role and your identity provider. For information on using OIDC with AWS at Harness, go to [AWS Connector -- Credentials](/docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md#credentials)
```

2024-03-05 04:36 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/spot-deployment.md
> +Currently, Harness does not support using Spot Elastigroup with an OIDC-enabled AWS connector.
This info is covered in line 21 already right? You can remove this note.

2024-03-05 04:37 UTC, roshnisarangadharan requested changes
@SushrutHarness added few editorial comments, amend as you see fit. Please mention the feature flag names.

2024-03-06 20:25 UTC, thisrohangupta commented on docs/continuous-delivery/cd-integrations.md
> +        <td>Enables the option to connect to AWS with OIDC. Only currently supported for Kubernetes, Helm, Terraform, and Cloudformation. <b>This feature is in Beta.</b> </td>
Yes this feature is in Beta. You need to add ECS to the list.

2024-03-06 20:27 UTC, thisrohangupta commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
> +   If you would like to use AWS with OIDC, select **Use OIDC** here and ignore step 3 below.
Use OIDC is another option this doesn't bloat the docs

2024-03-06 20:51 UTC, SushrutHarness commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> +Currently, this option is only supported for Kubernetes, Helm, Terraform, and CloudFormation deployment types.
```suggestion
Currently, this option is only supported for Kubernetes, Helm, Terraform, ECS, and CloudFormation deployment types. 
```

2024-03-06 20:51 UTC, SushrutHarness commented on docs/continuous-delivery/cd-integrations.md
> +        <td>Enables the option to connect to AWS with OIDC. Currently, this option is only supported for Kubernetes, Helm, Terraform, and Cloudformation. <b>This is a Beta feature.</b> </td>
```suggestion
        <td>Enables the option to connect to AWS with OIDC. Currently, this option is only supported for Kubernetes, Helm, Terraform, ECS, and Cloudformation. <b>This is a Beta feature.</b> </td>
```

2024-03-07 05:47 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
> +If you are using the OIDC credential type for your AWS connector, also add a trust relationship between this IAM role and your identity provider. For information on using OIDC with AWS at Harness, go
```suggestion
If you are using the OIDC credential type for your AWS connector, add a trust relationship between the IAM role and your identity provider. For information on using OIDC with AWS at Harness, go to [AWS Connector -- Credentials](/docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md#credentials).
```

2024-03-07 05:47 UTC, roshnisarangadharan commented on docs/continuous-delivery/deploy-srv-diff-platforms/aws/ecs/ecs-deployment-tutorial.md
> +   If you would like to use AWS with OIDC, select **Use OIDC** here and ignore step 3 below.
```suggestion
   If you would like to use AWS with OIDC, select **Use OIDC** here and ignore Step 3 below. 
```

2024-03-07 05:48 UTC, roshnisarangadharan approved these changes

2024-03-07 06:05 UTC, merged