Chore(Exp-docs): Add Locust Loadgen Chaos Experiment Docs
harness/developer-hub pull request #572
Opened 2023-02-02 14:38 UTC by uditgaurav

# Harness Developer Pull Request
## What Type of PR is This?

- This PR adds Locust Loadgen ChaosExperiment Docs. This will help to know about the experiment details like - the flow of experiment, different tunables used, pre-requisites and other details

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-02 18:59 UTC, avaakash requested changes

2023-02-05 17:53 UTC, uditgaurav commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen-chaos.md
> +![Locust Loadgen Chaos](./static/images/locust-loadgen-chaos.png)
It is not a aws chaos

2023-02-21 09:47 UTC, roshnisarangadharan commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
> +            <td> Duration that you specify, through which chaos is injected into the target resource (in seconds). </td>
Can this be rewritten to "Time taken to inject chaos into a target resource (in seconds)."

2023-02-21 09:52 UTC, roshnisarangadharan commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
> +            <td> Rate to spawn users at (users per second).</td>
"Numbers of users spawned per second."

2023-02-21 09:54 UTC, roshnisarangadharan commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
> +            <td> Period to wait before and after injecting chaos (in seconds). </td>
Can we say "The wait period before and after injecting chaos (in seconds)."

2023-02-21 09:55 UTC, roshnisarangadharan commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
> +Use the following example to tune it:
Use the following example to tune the target host.

2023-02-21 09:55 UTC, roshnisarangadharan commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
> +Use the following example to tune it:
Use the following example to tune the number of users.

2023-02-21 09:56 UTC, roshnisarangadharan commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
> +Use the following example to tune it:
Use the following example to tune the custom load image.

2023-02-21 09:56 UTC, roshnisarangadharan commented on docs/chaos-engineering/chaos-faults/load/locust-loadgen.md
> +It specifies the rate at which users are spawned (users spawned per second). Tune it by using the `LOAD_IMAGE` environment variable.
...users are spawned per second.

2023-02-21 09:59 UTC, roshnisarangadharan approved these changes
Reviewed the changed sections only. Approved with some suggestions. Implement or ignore as needed.

2023-02-21 10:30 UTC, roshnisarangadharan approved these changes

2023-02-23 14:48 UTC, SudheendraKatte submitted a review, later dismissed
LGTM

2023-02-23 17:02 UTC, roshnisarangadharan approved these changes

2023-02-24 02:20 UTC, merged