feat: [CDS-91915]: Add Knowledge base how bidirectional sync prevent github api limit
harness/developer-hub pull request #5730
Opened 2024-03-06 06:57 UTC by krishi0408

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-06 06:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5730) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5730) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5730) it.</sub>

2024-03-06 07:25 UTC, roshnisarangadharan commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +Read more on how to enable [Biderectional Sync](/docs/platform/git-experience/gitexp-bidir-sync-setup.md).
```suggestion
Read more on how to enable [Biderectional Sync](/docs/platform/git-experience/gitexp-bidir-sync-setup/).
```

2024-03-06 07:25 UTC, roshnisarangadharan commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +This knowledge base article discusses how Bidirectional Sync can help prevent reaching the GitHub API limit issue.
```suggestion
This knowledge base article discusses how bidirectional sync can help prevent reaching the GitHub API limit issue.
```

2024-03-06 07:26 UTC, roshnisarangadharan commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +Github limits the number of REST API requests that you can make within a specific amout of time. Sometimes, the number is extrememly high and stops remote entitites from working.
```suggestion
GitHub limits the number of REST API requests that you can make within a specific amount of time. Sometimes, the number is high and stops remote entities from working. 
```

2024-03-06 07:28 UTC, roshnisarangadharan commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +In bidirectioal sync, changes made on either the Git repository or Harness are automatically synchronized. Updates to the entity on the platform are determined by the received event payload.Therefore
```suggestion
In bidirectional sync, changes made on either the Git repository or Harness are automatically synchronized. Updates to the entity on the platform are determined by the received event payload. Therefore, it is required to enable bidirectional sync configuration before the remote entities are created. 
```

2024-03-06 07:29 UTC, roshnisarangadharan approved these changes
Fixed typos and links. Approved.

2024-04-02 07:14 UTC, adivishy1 commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +This knowledge base article discusses how bidirectional sync can help prevent reaching the GitHub API limit issue.
We dont need to specify a git provider, we can just tell Git rate limit issue

2024-04-02 07:14 UTC, adivishy1 commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +This knowledge base article discusses how bidirectional sync can help prevent reaching the GitHub API limit issue.
you can change this everywhere GitHub is mentioned

2024-04-02 21:18 UTC, SushrutHarness requested changes
I know you've done the work already, but I'm wondering if this should just be added to the bidirectional sync documentation as opposed to being its own KB article.

2024-04-02 21:18 UTC, SushrutHarness commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +In bidirectional sync, the source of truth is Harness's cached data. Therefore, instead of making API calls to Git every time, bidirectional sync fetches the data from Harness Cache, thus limiting th
You've said the same thing twice in line 15 and 17, I think one of these might be leftovers from an edit.

2024-04-03 05:07 UTC, krishi0408 commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +In bidirectional sync, the source of truth is Harness's cached data. Therefore, instead of making API calls to Git every time, bidirectional sync fetches the data from Harness Cache, thus limiting th
Yup didn't noticed, thanks for pointing @SushrutHarness. I have removed the second para

2024-04-03 05:09 UTC, krishi0408 commented
> I know you've done the work already, but I'm wondering if this should just be added to the bidirectional sync documentation as opposed to being its own KB article.

Hey @SushrutHarness yes we thought about that initially but then PMs and dev decided to have a separate KB on how bidirectional sync prevent hitting API rate limits and attach the doc there.

2024-04-03 05:09 UTC, krishi0408 commented on kb/continuous-delivery/articles/biderectional-sync-prevent-github-api-limit.md
> +This knowledge base article discusses how bidirectional sync can help prevent reaching the Git API limit issue.
Yup added rate, thanks for noticing. Appreciate it.

2024-04-04 06:11 UTC, merged