[PL-48012] PL 1.28.x Release Notes
harness/developer-hub pull request #5736
Opened 2024-03-06 10:25 UTC by saifeemustafaqharness

[PL-48012](https://harness.atlassian.net/browse/PL-48012)

https://harness.atlassian.net/wiki/spaces/PD/pages/21684125729/NG+Release+SAAS+March+4th+2024+for+1.28.x-+Build

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [x] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +- The delegate list page now shows the latest delegate version beside the New Delegate button. This will help you compare your delegate version with the latest supported delegate version. (PL-47049)
```suggestion
- The delegate list page now shows the latest delegate version beside the **New Delegate** button. This will help you compare your delegate version with the latest supported delegate version. (PL-47049)
```

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +- Upgraded org.eclipse.jetty.* from v9.4.53.v20231009 to 9.4.54.v20240208. (PL-47854)
```suggestion
- Upgraded `org.eclipse.jetty.*` from v9.4.53.v20231009 to 9.4.54.v20240208. (PL-47854)
```

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +- The UI has been updated to include an HEC (HTTP Event Collector) Auth Token option in the Splunk Connector, allowing users to select HEC type authentication. (PL-46977)
```suggestion
- The UI has been updated to include an HTTP Event Collector (HEC) Auth Token option in the Splunk Connector, allowing users to select HEC-type authentication. (PL-46977)
```

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +- In the recent update to ng-manager version 1.28.0, we have implemented enhancements to the validation mechanism for secret identifiers. With the introduction of the EntityValidator annotation and t
```suggestion
- In the recent update to `ng-manager` version 1.28.0, we have implemented enhancements to the validation mechanism for secret identifiers. With the introduction of the `EntityValidator` annotation and the `EntityValidator` class, we now provide more flexibility and precision in validating secret identifiers, particularly regarding the use of hyphens. (PL-46959)
```

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +   - Introduction of EntityValidator Annotation and Class: We have introduced the EntityValidator annotation along with the EntityValidator class.
```suggestion
   - We have introduced the `EntityValidator` annotation and class.
```

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +   Restriction on Starting with a Hyphen: Secret identifiers cannot start with a hyphen, following best practices.
```suggestion
      - Restriction on starting with a hyphen: Secret identifiers cannot start with a hyphen, following best practices. 
```

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +- Customers were unable to view delegate logs due to the system not automatically switching to app.harness.io as the remote logging service when GCP is blocked by a firewall. (PL-46958, ZD-57844)
```suggestion
- Delegate logs were unavailable due to the system not automatically switching to app.harness.io as the remote logging service when GCP was blocked by a firewall. (PL-46958, ZD-57844)
```

2024-03-11 14:15 UTC, brian-f-harness commented on release-notes/platform.md
> +- Fixed the issue that is allowing the creation of user PATs (Personal Access Tokens) at the organization and project scope via API, ensuring consistent listing and management in the UI. PATs can onl
```suggestion
- Fixed the issue that allowed the creation of user Personal Access Tokens (PATs) at the organization and project scope via API, ensuring consistent listing and management in the UI. PATs can only be created at the account scope. (PL-47558)
```

2024-03-11 14:48 UTC, brian-f-harness requested changes
The delegate-dependent items are missing. Please add items from the [delegate-dependent changes](https://harness.atlassian.net/wiki/spaces/PD/pages/21684125729/NG+Release+SAAS+March+4th+2024+for+1.28.x-+Build#NG-Delegate-dependent-changes--) with the standard dependency verbiage:

   This item requires Harness Delegate version 24.03.82510. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate).

2024-03-11 20:08 UTC, brian-f-harness commented on release-notes/platform.md
> +### Version 1.28.9<!--  March 11, 2024 -->
```suggestion
### Version 1.28.10<!--  March 12, 2024 -->
```

2024-03-11 20:08 UTC, brian-f-harness requested changes

2024-03-11 20:08 UTC, brian-f-harness commented on release-notes/platform.md
> +date: 2024-03-11:T10:00:30
```suggestion
date: 2024-03-12:T10:00:30
```

2024-03-12 06:25 UTC, nataraja2018 submitted a review, later dismissed

2024-03-12 13:04 UTC, brian-f-harness requested changes
Please add the items in the delegate-dependent section of the release notes page and include the standard verbiage.
https://harness.atlassian.net/wiki/spaces/PD/pages/21684125729/NG+Release+SAAS+March+4th+2024+for+1.28.x-+Build#NG-Delegate-dependent-changes--

2024-03-12 13:04 UTC, brian-f-harness commented on release-notes/platform.md
>     This item is available with Harness Platform version 1.28.9 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, g
```suggestion
   This item is available with Harness Platform version 1.28.10 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate).
```

2024-03-12 13:04 UTC, brian-f-harness commented on release-notes/platform.md
>     This item is available with Harness Platform version 1.28.9 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, g
```suggestion
   This item is available with Harness Platform version 1.28.10 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate).
```

2024-03-12 13:04 UTC, brian-f-harness commented on release-notes/platform.md
>     This item is available with Harness Platform version 1.28.9 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, g
```suggestion
   This item is available with Harness Platform version 1.28.10 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate).
```

2024-03-12 21:54 UTC, brian-f-harness commented on release-notes/platform.md
> +date: 2024-03-12:T10:00:30
```suggestion
date: 2024-03-13:T10:00:30
```

2024-03-12 21:55 UTC, brian-f-harness commented on release-notes/platform.md
> +### Version 1.28.10<!--  March 12, 2024 -->
```suggestion
### Version 1.28.10<!--  March 13, 2024 -->
```

2024-03-13 10:17 UTC, brian-f-harness approved these changes

2024-03-13 13:13 UTC, brian-f-harness requested changes
The deployed version is 1.28.11

https://monitoring.harness.io/d/ZJD3rKZIz/microservice-version-dashboard?orgId=1&refresh=5m&from=now-5m&to=now

https://harness.slack.com/archives/C04R4UDE1FT/p1710307241653819?thread_ts=1710211576.561939&cid=C04R4UDE1FT

2024-03-13 13:13 UTC, brian-f-harness commented on release-notes/platform.md
> +### Version 1.28.10<!--  March 13, 2024 -->
```suggestion
### Version 1.28.11<!--  March 13, 2024 -->
```

2024-03-13 13:13 UTC, brian-f-harness commented on release-notes/platform.md
> +   This item is available with Harness Platform version 1.28.10 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version,
```suggestion
   This item is available with Harness Platform version 1.28.11 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate).
```

2024-03-13 13:13 UTC, brian-f-harness commented on release-notes/platform.md
> +   This item is available with Harness Platform version 1.28.10 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version,
```suggestion
   This item is available with Harness Platform version 1.28.11 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate).
```

2024-03-13 13:13 UTC, brian-f-harness commented on release-notes/platform.md
> +   This item is available with Harness Platform version 1.28.10 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version,
```suggestion
   This item is available with Harness Platform version 1.28.11 and does not require a new delegate version. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate).
```

2024-03-13 15:37 UTC, brian-f-harness approved these changes

2024-03-13 16:52 UTC, pratmit submitted a review, later dismissed
LGTM

2024-03-13 18:09 UTC, brian-f-harness approved these changes

2024-03-13 18:25 UTC, merged