[PL-48049] DEL 82500 Release Notes
harness/developer-hub pull request #5761
Opened 2024-03-07 10:36 UTC by saifeemustafaqharness

[PL-48049](https://harness.atlassian.net/browse/PL-48049)

https://harness.atlassian.net/wiki/spaces/PD/pages/21684125729/NG+Release+SAAS+March+4th+2024+for+1.28.x-+Build#NG-Delegate-dependent-changes--

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-11 05:52 UTC, saifeemustafaqharness commented
@pratmit @brian-f-harness Ready for review

2024-03-11 14:20 UTC, brian-f-harness commented on release-notes/delegate.md
> +### Harness version 1.28.9, Harness Delegate version 24.02.82501 <!--  February 27, 2024 -->
```suggestion
### Harness version 1.28.9, Harness Delegate version 24.02.82501 <!--  March xx, 2024 -->
```

2024-03-11 14:20 UTC, brian-f-harness commented on release-notes/delegate.md
> +   - Use CPU_USAGE_THRESHOLD for CPU control (default: no limit)
```suggestion
   - Use `CPU_USAGE_THRESHOLD` for CPU control (default: no limit)
```

2024-03-11 14:20 UTC, brian-f-harness commented on release-notes/delegate.md
> +   - Use MEMORY_USAGE_THRESHOLD for memory control (default: 80%)
```suggestion
   - Use `MEMORY_USAGE_THRESHOLD` for memory control (default: 80%)
```

2024-03-11 14:20 UTC, brian-f-harness commented on release-notes/delegate.md
> +   If you are using RESOURCE_USAGE_THRESHOLD (deprecated), it exclusively controls the memory threshold.
```suggestion
   If you are using `RESOURCE_USAGE_THRESHOLD` (deprecated), it exclusively controls the memory threshold.
```

2024-03-11 14:20 UTC, brian-f-harness commented on release-notes/delegate.md
> +- OPA policy enforcement has been introduced to three new entities, namely Service Accounts, API Keys, and Tokens. For Service Accounts and API Keys, naming conventions policies are enforced, while f
```suggestion
- OPA policy enforcement has been introduced to three new entities: Service Accounts, API Keys, and Tokens. For Service Accounts and API Keys, naming convention policies are enforced, while for Tokens, Time-To-Live (TTL) policies are enforced. These enforcement mechanisms are seamlessly integrated into both create and update operations, ensuring adherence to predefined standards during the `onSave` action. (PL-46778)
```

2024-03-11 14:20 UTC, brian-f-harness commented on release-notes/delegate.md
> +- Support added to enable OPA policy for naming convention enforcement while creating or updating a Service Account. (PL-46777)
```suggestion
- Support added to enable OPA policy for naming convention enforcement while creating or updating a service account. (PL-46777)
```

2024-03-11 14:20 UTC, brian-f-harness commented on release-notes/delegate.md
> +- Attempts to use the `harness_platform_user` resource to create or delete users results in an error. The message "Request failed as you have an older version of entity, please reload the page and tr
```suggestion
- Attempts to use the `harness_platform_user` resource to create or delete users resulted in an error. The message "Request failed as you have an older version of an entity, please reload the page and try again" was displayed and the Terraform state went out of sync with Harness. (PL-39870, ZD-47107)
```

2024-03-11 14:49 UTC, brian-f-harness requested changes

2024-03-11 14:49 UTC, brian-f-harness commented on release-notes/delegate.md
> +
Please verify the delegate verno. I see 24.03.82502 in QA.

2024-03-12 13:13 UTC, brian-f-harness approved these changes

2024-03-12 21:55 UTC, brian-f-harness commented on release-notes/delegate.md
> +date: 2024-03-12T10:00
```suggestion
date: 2024-03-13T10:00
```

2024-03-12 21:55 UTC, brian-f-harness commented on release-notes/delegate.md
> +### Harness version 1.28.10, Harness Delegate version 24.03.82502 <!--  March 12, 2024 -->
```suggestion
### Harness version 1.28.10, Harness Delegate version 24.03.82502 <!--  March 13, 2024 -->
```

2024-03-12 22:44 UTC, brian-f-harness approved these changes
LGTM

2024-03-13 13:14 UTC, brian-f-harness requested changes
The deployed version is 1.28.11

https://harness.slack.com/archives/C04R4UDE1FT/p1710307241653819?thread_ts=1710211576.561939&cid=C04R4UDE1FT

2024-03-13 13:14 UTC, brian-f-harness commented on release-notes/delegate.md
> +### Harness version 1.28.10, Harness Delegate version 24.03.82502 <!--  March 13, 2024 -->
```suggestion
### Harness version 1.28.11, Harness Delegate version 24.03.82502 <!--  March 13, 2024 -->
```

2024-03-13 15:29 UTC, brian-f-harness approved these changes

2024-03-13 16:52 UTC, pratmit approved these changes
LGTM

2024-03-13 18:25 UTC, merged