[feat]: [CDS-91474]: Add Ignore status code for HTTP connections settings in the doc
harness/developer-hub pull request #5763
Opened 2024-03-07 12:18 UTC by krishi0408

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-07 12:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5763) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5763) it.</sub>

2024-03-07 16:16 UTC, roshnisarangadharan commented on docs/continuous-delivery/cd-integrations.md
> +        <td> When enabled Harness only requires a valid response from the target HTTP server and does not verify the response code. </td>
```suggestion
        <td> When enabled, Harness only requires a valid response from the target HTTP server and does not verify the response code. </td>
```

2024-03-07 16:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> +You can enable **Ignore status code for HTTP connections**, when enabled Harness only requires a valid response from the target HTTP server and does not verify the response code. This is particularly
```suggestion
You can enable **Ignore status code for HTTP connections**. When enabled, Harness only requires a valid response from the target HTTP server and does not verify the response code. This is particularly useful when the Harness Delegate is configured with a proxy because socket connection tests conducted by Harness from the delegate do not account for proxy details.
```

2024-03-07 16:17 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> +You can enable the setting by following below steps:-
```suggestion
You can enable the setting by following below steps:
```

2024-03-07 16:20 UTC, roshnisarangadharan commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> +This setting can be enbaled using feature flag ``CDS_USE_HTTP_CHECK_IGNORE_RESPONSE_INSTEAD_OF_SOCKET_NG``.
```suggestion
This setting is behind the feature flag, ``CDS_USE_HTTP_CHECK_IGNORE_RESPONSE_INSTEAD_OF_SOCKET_NG``. To enable a feature flag in your Harness account, contact [Harness Support](mailto:support@harness.io).
```

2024-03-07 16:21 UTC, roshnisarangadharan submitted a review, later dismissed
Approved with editorial updates. Check for technical accuracy with Dev before merge. Thanks!

2024-03-07 19:43 UTC, SushrutHarness submitted a review, later dismissed
LGTM

2024-03-11 05:39 UTC, abhinavsingh1196 requested changes

2024-03-11 05:39 UTC, abhinavsingh1196 commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> +1. Enable the setting by navigating to **Project Settings**.
setting is available on ORG and ACCOUNT level as well

2024-03-11 05:39 UTC, abhinavsingh1196 commented on docs/continuous-delivery/cd-integrations.md
> +        <td>CDS_USE_HTTP_CHECK_IGNORE_RESPONSE_INSTEAD_OF_SOCKET_NG</td>
should we even add this here? we are going to remove this FF in next few weeks.

2024-03-11 05:39 UTC, abhinavsingh1196 commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> +This setting is behind the feature flag, ``CDS_USE_HTTP_CHECK_IGNORE_RESPONSE_INSTEAD_OF_SOCKET_NG``. To enable this feature flag in your Harness account, contact [Harness Support](mailto:support@har
setting is independent of the feature flag, it will always be available. To use this feature currently, we need EITHER of the FF or setting to be enabled. 
We should mention that we are going to remove the FF and this feature should only be controlled by the setting going forward.

2024-03-11 13:28 UTC, krishi0408 commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> +This setting is behind the feature flag, ``CDS_USE_HTTP_CHECK_IGNORE_RESPONSE_INSTEAD_OF_SOCKET_NG``. To enable this feature flag in your Harness account, contact [Harness Support](mailto:support@har
Sure I will add that as a note as well

2024-03-11 13:29 UTC, krishi0408 commented on docs/continuous-delivery/cd-integrations.md
> +        <td>CDS_USE_HTTP_CHECK_IGNORE_RESPONSE_INSTEAD_OF_SOCKET_NG</td>
oh okay sure @abhinavsingh1196 if it's gonna get removed I will remove the FF from here.

2024-03-11 13:30 UTC, krishi0408 commented on docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/http-step.md
> +1. Enable the setting by navigating to **Project Settings**.
Okay I will add that as well

2024-03-11 17:32 UTC, SushrutHarness commented on docs/continuous-delivery/cd-integrations.md
> +        <td>CDS_USE_HTTP_CHECK_IGNORE_RESPONSE_INSTEAD_OF_SOCKET_NG</td>
If this is going to be merged before the FF is removed, it still needs to go here. We don't want customers looking for a feature that is still behind a flag.

2024-03-12 07:40 UTC, abhinavsingh1196 approved these changes

2024-03-12 07:43 UTC, merged