Azure governance docs
harness/developer-hub pull request #5764
Opened 2024-03-07 12:56 UTC by joeyouss

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [X] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-07 12:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=5764) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=5764) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=5764) it.</sub>

2024-03-08 03:28 UTC, iamanmolm commented
I think this was the not the expected structure. The structure was expected like what we have specs. @Rohit-Kaliki ?

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +EC2 instances
We should make this as a list.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +Virtual Machines (VMs)
We should make this as a list.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +Compute Engine instances
We should make this as a list.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +Cloud Custodian, while a widely used open-source cloud management tool, presents several challenges, including lack of a graphical interface, scalability issues, limited reporting and security featur
This comparison can be framed in a better way. Paragraphs are not that intuitive.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +1. **Recommendation: delete-low-utilised-cosmodb**
Point 1 looks bigger than Point 2. Also sub point is going into same line as Point 1.
<img width="979" alt="Screenshot 2024-03-08 at 9 04 19 AM" src="https://github.com/harness/developer-hub/assets/105212590/a3ac5255-7ad2-410f-9ac2-af1d0480d175">

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +2. **Recommendation:**
It is missing recommendation name. Also point and sub points are coming in the same line.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +
Remove extra space from here.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +
Also remove extra space from here.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +3. **Recommendation:delete-low-utilised-load-balancers**
Point and sub points are coming in the same line.

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +3. **Recommendation:delete-low-utilised-load-balancers**
Also how come sub points are going outside the points:
<img width="1123" alt="Screenshot 2024-03-08 at 9 07 58 AM" src="https://github.com/harness/developer-hub/assets/105212590/e4b99846-e812-4d1a-988f-d583e0754719">

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +4. **Recommendation:delete-orphaned-network-interface**
Point and sub points are coming in the same line. Policy seems to be outside the code blocks and further subheading went inside the code blocks.
<img width="1028" alt="Screenshot 2024-03-08 at 9 09 53 AM" src="https://github.com/harness/developer-hub/assets/105212590/13e43d6a-acaf-497a-82e0-257c3d42e13d">

2024-03-08 03:43 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/1-asset-governance.md
> +5. **Recommendation:stop-underutilized-vms**
Everything below this is completely messed up. Points are within code blocks and policies are outside code blocks.
<img width="1031" alt="Screenshot 2024-03-08 at 9 12 09 AM" src="https://github.com/harness/developer-hub/assets/105212590/c24157a9-cf64-4660-b991-169e76690c72">

2024-03-08 03:44 UTC, iamanmolm requested changes
Kindly change the structure and also address all the comments above.

2024-03-13 04:41 UTC, closed without merging

2024-03-13 04:41 UTC, joeyouss commented
Closing this PR since azure docs will be updated over 4 PRs