CI-11652 update go split test example
harness/developer-hub pull request #5870
Opened 2024-03-13 22:52 UTC by aimurphy

2024-03-15 06:52 UTC, hemanthmantri requested changes

2024-03-15 06:52 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/run-tests/speed-up-ci-test-pipelines-using-parallelism.md
> +                      FILES=`/addon/bin/split_tests --file-path "SUITES.txt" --split-by testsuite_timing \
Where is SUITES.txt coming from?
@anurag-harness please provide a working example YAML.

2024-03-15 14:52 UTC, aimurphy commented on docs/continuous-integration/use-ci/run-tests/speed-up-ci-test-pipelines-using-parallelism.md
> +                      FILES=`/addon/bin/split_tests --file-path "SUITES.txt" --split-by testsuite_timing \
it was a guess because I don't know what the yaml should be.

2024-03-22 17:23 UTC, aimurphy commented
@hemanthmantri Can you review it again?

2024-03-26 22:23 UTC, merged