first part of azure docs
harness/developer-hub pull request #5887
Opened 2024-03-14 14:59 UTC by joeyouss

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [x] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-15 03:40 UTC, Rohit-Kaliki reviewed
Flow looks good, let's work on the language and other house keeping stuff.

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +11. Set the frequency from **Hourly**, **Daily**, or **Weekly **options. In case you select Daily or Weekly, specify the day, time, and time zone to run the rule on schedule.
Weekly is not properly formatted. "**Weekly** options"

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +After setting up the schedule, you can view the enforcement on the **Rule Enforcements** page.
"on the **Enforcements** page."

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +    <DocImage path={require('./static/set-up-schedule.png')} width="60%" height="60%" title="Click to view full size image" />
Screenshot is wrong. It should be of Enforcement List Page.

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Furthermore, you can disable the enforcement at any time using the toggle button in the **Status** column. If you want to turn off the dry-run mode, select **Edit** from the vertical ellipsis menu (⋮
and then go to "Target And Schedule", use slider to turn off "Enforce Rule(s) in Dry Run mode" and click on Finish.

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +You can view any Enforcements on Rule Enforcements page. Expand the enforcement to view the rules, target accounts, and regions included in the enforcement. For updating, you can use the “Edit” optio
Remove "Expand the enforcement to view the rules, target accounts, and regions included in the enforcement." as this is incorrect. You cant expand the rule enforcement.

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +You can view any Enforcements on Rule Enforcements page. Expand the enforcement to view the rules, target accounts, and regions included in the enforcement. For updating, you can use the “Edit” optio
"you can use the "Edit" button from the vertical ellipsis menu (⋮) to update the enforcements as per your convenience."

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +To delete an enforcement, simply click on “Delete”
"To delete an enforcement, simply click on “Delete” from the vertical ellipsis menu (⋮)"

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Evaluations include all the data about enforcements run (both, directly and from the test terminal). The Evaluations window also shows you the total cost impact with each enforcement i.e. the costs o
"run (both RUN ONCE from rule editor and from Enforcement)"

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +## Use filters in rule evaluation
Make it subheading under Evaluations heading.

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Evaluations include all the data about enforcements run (both, directly and from the test terminal). The Evaluations window also shows you the total cost impact with each enforcement i.e. the costs o
"you can view and audit all the enforcements that ran in the past."

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +## Use filters in rule evaluation
Filters in Evaluations List Page.

2024-03-15 06:34 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +    * Azure Filters
GCP Filters can also be added.

2024-03-15 07:14 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Currently, GCP support for Asset Governance is behind the feature flag **CCM_ENABLE_GCP_CLOUD_ASSET_GOVERNANCE_UI** Contact [Harness Support](mailto:support@harness.io) to enable the feature.
done

2024-03-15 07:15 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Rules help you set up asset governance for your cloud provider. A rule is essentially a small file with a set of logic that you can run on your cloud infrastructure. For example, there might be a sce
done

2024-03-15 07:23 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Ideally, rules include policy, resource filters, and actions.
done

2024-03-15 07:23 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +- A **policy** is defined in YAML format and consists of filters and actions that are applied to a specific type of cloud resource set up by you.
ok

2024-03-15 07:25 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +- A **resource** is the type of cloud resource or service on which the rule will be run or to which the actions and filters will be applied, such as AWS EC2, AWS S3, GCP SQL, or Azure VMs.
done

2024-03-15 09:04 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Evaluations include all the data about enforcements run (both, directly and from the test terminal). The Evaluations window also shows you the total cost impact with each enforcement i.e. the costs o
done

2024-03-15 09:05 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +- **Actions** are operations that have to be performed on the resource and are applied to the output of the filters specified in the policy when the rule is run. Actions can include things like termi
done

2024-03-15 09:05 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +So essentially, a rule is a file that includes logic defined by a policy that performs certain actions on the resource based on the filters provided by the user. Rules can include multiple policies,
done

2024-03-15 09:08 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Harness provides some out-of-the-box policies for EC2, RDS, EBS, ELB, and S3 that can be enforced. These policies cannot be edited but can be cloned.
done

2024-03-15 09:10 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +As mentioned previously, a Rule can have multiple policies. However, when there are multiple rules with multiple policies, it can become hard to manage them all together. This is where **Rule Sets**
done

2024-03-15 09:11 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +4. Select the **Rule sets** tab.
done

2024-03-15 09:15 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +9. Select the rules that you want to enforce.
done

2024-03-15 09:16 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Enforcements enable you to enforce a certain set of rules or rule sets (also known as governance guardrails) against a specific set of targets (accounts, subscriptions, and projects) to run periodica
this was added by Rohit, change it?

2024-03-15 09:21 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Enforcements enable you to enforce a certain set of rules or rule sets (also known as governance guardrails) against a specific set of targets (accounts, subscriptions, and projects) to run periodica
done

2024-03-15 09:22 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Enforcements enable you to enforce a certain set of rules or rule sets (also known as governance guardrails) against a specific set of targets (accounts, subscriptions, and projects) to run periodica
done

2024-03-15 09:23 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Rule Sets: You can select the Rule Sets that your Enforcement will consist of.
done

2024-03-15 09:24 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Rule Sets: You can select the Rule Sets that your Enforcement will consist of.
done

2024-03-15 09:25 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +11. Set the frequency from **Hourly**, **Daily**, or **Weekly **options. In case you select Daily or Weekly, specify the day, time, and time zone to run the rule on schedule.
done

2024-03-15 09:26 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +After setting up the schedule, you can view the enforcement on the **Rule Enforcements** page.
done

2024-03-18 05:43 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +### Create a new rule
done

2024-03-18 05:44 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +  <DocImage path={require('./static/rule_set.png')} width="90%" height="90%" title="Click to view full size image" />
don e

2024-03-18 05:50 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +You can view the Rule Set on the Asset Governance Rules page. Expand the rule set to view the individual rules in the rule set. You can click on individual rules to update them and/or use the “Edit”
done

2024-03-18 05:51 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Furthermore, you can disable the enforcement at any time using the toggle button in the **Status** column. If you want to turn off the dry-run mode, select **Edit** from the vertical ellipsis menu (⋮
done

2024-03-18 05:52 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +You can view any Enforcements on Rule Enforcements page. Expand the enforcement to view the rules, target accounts, and regions included in the enforcement. For updating, you can use the “Edit” optio
done

2024-03-18 05:54 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +You can view any Enforcements on Rule Enforcements page. Expand the enforcement to view the rules, target accounts, and regions included in the enforcement. For updating, you can use the “Edit” optio
done

2024-03-18 05:54 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +To delete an enforcement, simply click on “Delete”
done

2024-03-18 05:55 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +Evaluations include all the data about enforcements run (both, directly and from the test terminal). The Evaluations window also shows you the total cost impact with each enforcement i.e. the costs o
done

2024-03-18 05:55 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +## Use filters in rule evaluation
done

2024-03-18 05:56 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/2-Harness-Concepts.md
> +## Use filters in rule evaluation
done

2024-03-18 09:31 UTC, iamanmolm requested changes
Dummy

2024-03-18 09:53 UTC, iamanmolm approved these changes

2024-03-18 09:55 UTC, merged