Update overview.md
harness/developer-hub pull request #6084
Opened 2024-03-28 02:47 UTC by joeyouss

added native user approval draft

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-28 02:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6084) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6084) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6084) it.</sub>

2024-03-28 02:47 UTC, joeyouss commented
- Need to add screenshots
- Need to add the type of recommendatons like "initiating seed..."

2024-03-28 16:49 UTC, aimurphy reviewed
Some syntax/style suggestions also here.

2024-03-28 16:49 UTC, aimurphy commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +:::important note
```suggestion
:::info
```

Important is not a valid note type for docusaurus. It used to be, but it was deprecated. Please use "info" instead. You do not need to include the word "note".

2024-03-28 16:49 UTC, aimurphy commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +**Supported actions:**
```suggestion
### Supported actions
```

Please use headings for content labels like this instead of bold styling. Bold has no importance in the DOM. Bold is more appropriate for optional styling, like you have done in the list below.

2024-03-28 16:49 UTC, aimurphy commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +6. **COMPLETED**: The approved recommendation has been successfully completed.
```suggestion
* **APPROVED**: Authorized user approves the recommendation, allowing the action to proceed.
* **REJECTED**: Authorized user rejects the recommendation, preventing the action from taking place.
* **APPROVAL_PENDING**: The action is pending approval from the authorized user. By default, pending actions expire in 24 hours.
* **EXPIRED**: The recommended action has expired.
* **ERROR**: Approval process encounters an error.
* **COMPLETED**: The approved recommendation has been successfully completed.
```

Please use numbered lists only when the order of the items on the list matters (such as a series of steps). Otherwise, use bullets.

2024-03-28 16:49 UTC, aimurphy commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +**UI Walkthrough**
```suggestion
### Action Center UI
```

2024-04-01 12:26 UTC, Additi requested changes

2024-04-01 12:26 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +3. **APPROVAL_PENDING**: The action is pending approval from the authorized user. By default, pending actions expire in 24 hours.
For approval_pending, mention the recommendation is pending approval and this is the default state where all the recommendations will come.

2024-04-01 12:26 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +- **SP Purchase Plan**: We send out monthly recommendations for purchasing SP (Savings Plans), provided there isn't an existing SP in place already. Upon receipt, you will have 24 hours to approve th
Compute saving plans

2024-04-01 12:26 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +- **RI Purchase Plan**: Our system generates recommendations for purchasing RI (Reserved Instances) multiple times throughout the month. Just like with SP purchases, you'll have a 24-hour window to a
Convertible RIs and also mention of purchasing seed RI (t3.nano) and how it will be purchased if there are no t3.nano, if it already exists we will use it. If any other RI exists, we will use that to get a t3.nano to ensure that the t3.nano also expires along with the original RI

2024-04-01 12:26 UTC, Additi commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +You can select automatic approval or manual approval during the setup of commitment orchestrator.
You can change and select the mode during the setup flow

2024-04-01 14:36 UTC, joeyouss commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +:::important note
thank you! i think I used it recently and it still works?

2024-04-01 15:07 UTC, aimurphy commented on docs/cloud-cost-management/4-use-ccm-cost-optimization/Commitment-orchestrator/overview.md
> +:::important note
It converts it to info for now, but as a best practice, we shouldn't use deprecated elements. It will most likely be removed in a future docusaurus release.

2024-04-03 08:44 UTC, merged