AWS recommendations
harness/developer-hub pull request #6086
Opened 2024-03-28 03:22 UTC by joeyouss

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-28 03:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6086) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6086) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6086) it.</sub>

2024-03-28 16:38 UTC, aimurphy reviewed
Added some suggestions for syntax/style for your consideration.

2024-04-02 12:01 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/4-AWS-recommendations
> +### **1. Recommendation: delete-unattached-volumes**
Actually, this was a part of template that we used for gov docs

2024-04-02 15:13 UTC, aimurphy commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/4-AWS-recommendations
> +      - State: available
```suggestion
**Policy Used:**
```yaml
policies:
  - name: delete-unattached-volumes
    resource: ebs
    filters:
      - Attachments: []
      - State: available
```

2024-04-04 12:35 UTC, iamanmolm requested changes

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +Recommendations help kickstart your journey with governance. Essentially, Harness run certain policies behind the scenes to generate recommendations for your governance-enabled AWS subscriptions. The
"governance-enabled AWS accounts."

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +### Recommendation: delete-unattached-volumes
name for this recommendation is now changed to "delete-unattached-ebs"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Description:** Delete unattached volumes
The description is changed to "Delete all ebs volumes which are unattached".

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Policy Used:**
Move it to next line.

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +  - name: delete-unattached-volumes
Update the name to "delete-unattached-ebs"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Policy Used:**
Move it to next line.

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Policy Used:**
Move it to next line.

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Policy Used:**
Move it to next line.

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +### Recommendation: rds-delete-unuseds
The policy name is now changed to "stop-unused-rds"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Description:** Delete unused RDS database
The description is changed to "Stop unused RDS database"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +  - name: rds-delete-unused
Change the name to "stop-unused-rds"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +    description: Delete unused RDS database
Changed the description to "Stop unused RDS database"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +      - delete
Change "delete" to "stop"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +    - ```rds:DeleteDBInstance```
Change this to "rds:StopDBInstance"

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +---
Move this page below Harness Concepts as we did in case of Azure.

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/Harness-Concepts.md
> +Rules help you set up Asset Governance for your cloud provider. A Rule is essentially a small file with a set of logic that you can run on your cloud infrastructure. For example, there might be a sce
Remove 1 dot after "us.."

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/Harness-Concepts.md
> +- A **resource** is the type of cloud resource or service on which the rule will be run with the actions and filters, such as Azure VMs, AKS, Cosmos DB, etc.
"such as ec2, s3, elb etc."

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/Harness-Concepts.md
> +<DocImage path={require('../static/rule_example_AWS.png')} width="80%" height="80%" title="Click to view full size image" />
Filters applied is covering the action part of policy as well. Kindly fix it.
<img width="842" alt="Screenshot 2024-04-04 at 6 00 25 PM" src="https://github.com/harness/developer-hub/assets/105212590/a9b0c964-2685-4c93-8a87-822d9921d8f1">

2024-04-04 12:35 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/Harness-Concepts.md
> +    * Azure Filters
"AWS Filters"

2024-04-05 16:16 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +Recommendations help kickstart your journey with governance. Essentially, Harness run certain policies behind the scenes to generate recommendations for your governance-enabled AWS subscriptions. The
done

2024-04-05 16:16 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/Harness-Concepts.md
> +    * Azure Filters
done

2024-04-05 16:20 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/Harness-Concepts.md
> +- A **resource** is the type of cloud resource or service on which the rule will be run with the actions and filters, such as Azure VMs, AKS, Cosmos DB, etc.
done

2024-04-05 16:24 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/Harness-Concepts.md
> +Rules help you set up Asset Governance for your cloud provider. A Rule is essentially a small file with a set of logic that you can run on your cloud infrastructure. For example, there might be a sce
done

2024-04-05 16:34 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +  - name: rds-delete-unused
done

2024-04-05 16:34 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +    description: Delete unused RDS database
done

2024-04-05 16:34 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +      - delete
done

2024-04-05 16:34 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +    - ```rds:DeleteDBInstance```
done

2024-04-05 16:36 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +### Recommendation: delete-unattached-volumes
done

2024-04-05 16:36 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Description:** Delete unattached volumes
done

2024-04-05 16:37 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +  - name: delete-unattached-volumes
done

2024-04-06 00:56 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +Recommendations help kickstart your journey with governance. Essentially, Harness run certain policies behind the scenes to generate recommendations for your governance-enabled AWS subscriptions. The
@joeyouss this is still not addressed.

2024-04-06 00:57 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Description:** Delete unused RDS database
@joeyouss this is not yet addressed.

2024-04-06 10:14 UTC, iamanmolm approved these changes

2024-04-06 15:50 UTC, merged