CD FAQs
harness/developer-hub pull request #6101
Opened 2024-03-28 18:44 UTC by austinthao5

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the CODEOWNERS. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screenshot.

2024-03-28 18:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6101) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6101) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6101) it.</sub>

2024-03-28 19:47 UTC, SushrutHarness requested changes
Great FAQ writing! I left a few nitpicks and few suggestions, take a look and check if they're still right technically.

2024-03-28 19:47 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +If you've recently migrated your Pipeline and Input Set(s) from Inline to Remote, you may encounter this error. To fix this, the Trigger needs to reference a Remote Input Set. If using Remote Input S
```suggestion
If you've recently migrated your Pipeline and Input Set(s) from Inline to Remote, you may encounter this error. To fix this, the Trigger needs to reference a Remote Input Set.  It is required for Triggers to reference a Remote Input Set when using Remote Input Sets and Remote Pipelines.
```

2024-03-28 19:47 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +If you've recently migrated your Pipeline and Input Set(s) from Inline to Remote, you may encounter this error. To fix this, the Trigger needs to reference a Remote Input Set. If using Remote Input S
```suggestion
If you've recently migrated your Pipeline and Input Set(s) from Inline to Remote, you may encounter this error. To fix this, the Trigger needs to reference a Remote Input Set. It is required for Triggers to reference a Remote Input Set when using Remote Input Sets and Remote Pipelines.
```

2024-03-28 19:47 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Any - Deploy to environments matching any of the tags.
Fantastic explanation

2024-03-28 19:47 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +If your pipeline is timing out before your step has a chance to hit the timeout threshold, it's likely that the pipeline itself has a timeout that has already been reached.
Can you quickly tell me (the customer) where to find this timeout setting for the pipeline?

2024-03-29 17:48 UTC, austinthao5 commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +If your pipeline is timing out before your step has a chance to hit the timeout threshold, it's likely that the pipeline itself has a timeout that has already been reached.
Sure, it's in Advanced Settings > Pipeline Timeout Settings

2024-03-29 19:35 UTC, SushrutHarness submitted a review, later dismissed
Consider adding the setting instructions to FAQ. OTherwise looks good

2024-03-29 19:42 UTC, SushrutHarness approved these changes

2024-03-29 21:02 UTC, merged