New PR and Issue templates
harness/developer-hub pull request #6169
Opened 2024-04-02 20:28 UTC by aimurphy

Thanks for contributing to the Harness Developer Hub! Our code owners will review your PR.

## Purpose

Update the PR template to reflect our current practices.

Also updated the issue template.

## Merge requirements

- [ ] Successful preview build.
- [ ] No merge conflicts.
- [ ] Up to date with main.
- [ ] SME/Product review.
- [ ] Editorial/peer review.
- [ ] No open change requests from reviewers.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

## PR lifecycle

We aim to merge PRs within one week or less. However, sometimes delays happen.

If your PR has been open longer than two weeks without any human activity, please add a comment tagging one of the [code owners](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS).

2024-04-02 20:49 UTC, SushrutHarness approved these changes
LGTM

2024-04-02 21:33 UTC, brian-f-harness submitted a review, later dismissed
LGTM

2024-04-03 00:08 UTC, douglas-j-bothwell submitted a review, later dismissed
LGTM. I like the checklist!

2024-04-03 00:11 UTC, ravilach submitted a review, later dismissed

2024-04-03 00:12 UTC, ravilach commented
I would say to limit the checklist for folks in the public who might not know who a SME is. Can separate Harness vs Non-Harness.

2024-04-03 02:35 UTC, aimurphy commented
> I would say to limit the checklist for folks in the public who might not know who a SME is. Can separate Harness vs Non-Harness.

good point. changed it to be shorter and just say generic "code owner review"

2024-04-03 05:20 UTC, krishi0408 commented
LGTM

2024-04-03 05:20 UTC, krishi0408 approved these changes

2024-04-03 07:00 UTC, roshnisarangadharan approved these changes

2024-04-03 07:04 UTC, SmritiSatya requested changes

2024-04-03 07:04 UTC, SmritiSatya commented on .github/pull_request_template.md
> +Thanks for contributing to the Harness Developer Hub! Our code owners will review your PR.
Thank you for contributing to the Harness Developer Hub! Our code owners will review your pull request (PR).

2024-04-03 07:04 UTC, SmritiSatya commented on .github/pull_request_template.md
If the PR is related to a specific JIRA or a GitHub issue, include the issue ID in the PR title.

2024-04-03 12:54 UTC, jenniferopal approved these changes
lgtm!

2024-04-03 15:04 UTC, merged