Cache intelligence v2
harness/developer-hub pull request #618
Opened 2023-02-07 02:41 UTC by douglas-j-bothwell

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-07 05:29 UTC, jamie-harness requested changes

2023-02-07 05:29 UTC, jamie-harness commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +  - Basel, Maven, Gradle, Yarn, and Node frameworks
Bazel, not basel

2023-02-07 05:29 UTC, jamie-harness commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +  - Basel, Maven, Gradle, Yarn, and Node frameworks
Build tools is more accurate then frameworks here, but it should be ok

2023-02-07 15:32 UTC, aimurphy commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
>  ### Cache and Reuse the Data for Your Fetch Operations
```suggestion
### Cache and reuse the data for your fetch operations
```

2023-02-07 15:35 UTC, aimurphy commented on docs/continuous-integration/troubleshoot/optimizing-ci-build-times.md
> +Caching and reusing can be useful for data that your builds need to fetch, but that you cannot include in an optimized image as described above. Caching ensures faster job execution by reusing the ex
```suggestion
Caching and reusing is useful for data that your builds need to fetch, but that you can't include in an optimized image as described above. Caching expedites job execution by reusing expensive fetch operation data from previous jobs. 
```

2023-02-07 15:38 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +description: You can set up your pipeline to cache your build artifacts automatically.
```suggestion
description: Set up your pipelines to automatically cache build artifacts.
```

2023-02-07 15:38 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +You can set up your pipeline to cache your build artifacts automatically. Note the following:
```suggestion
You can set up your pipelines to automatically cache build artifacts. Note the following:  
```

2023-02-07 15:39 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +* Cache Intelligence is currently supported for the following.
```suggestion
* Cache Intelligence is currently supported for the following:
```

2023-02-07 15:39 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +description: You can set up your pipeline to cache your build artifacts automatically.
build dependencies

2023-02-07 15:39 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +            path:             # optional paths to support specific frameworks
I think we should show one YAML sample with only caching.enabled=true. The paths can be mentioned in a separate YAML example indicating that the field can be used for frameworks where automatic caching is not supported.

2023-02-07 15:39 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +Delete the cache. You can include an optional `path` parameter to delete a specific subfolder in the cache.
sub-directory?

2023-02-07 15:39 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +curl --location --request DELETE 'https://app.harness.io/gateway/ci/cache/info?accountIdentifier=$HARNESS_ACCOUNT_ID&path=/path/to/deleted/folder' \
/path/to/delete
@jamie-harness : Can we specify multiple directories to delete?

2023-02-07 15:40 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +* Harness Cloud can cache up to 2GB of data per account. All pipelines in the account can use the same cache.
```suggestion
* Harness Cloud can cache up to 2GB of data per account. All pipelines in the account use the same cache. 
```
"can use" kind of implies that it is configurable. If a pipeline uses cache intelligence, then it's using the account's cache.

2023-02-07 15:41 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +To enable Cache Intelligence on a CI Build stage, add the following lines to  the stage YAML definition:
```suggestion
To enable Cache Intelligence on a CI Build stage, add the following lines to the stage YAML definition: 
```

2023-02-07 15:45 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +
```suggestion
###Cache Intelligence API

Use the Cache Intelligence API to get information about the cache or delete the cache.

```

Suggested breaking with a heading since the API calls aren't triggering a cache event (so not really related to the above heading, "Automated caching"). I also suggested rewriting the first sentence since there is a note between the sentence and the first call subsection.

2023-02-07 15:47 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +#### Delete cache for pipeline
The subsection heading is "delete cache for pipeline", but I think it's deleting the entire account's cache.

2023-02-07 15:49 UTC, aimurphy submitted a review, later dismissed

2023-02-07 15:53 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +curl --location --request DELETE 'https://app.harness.io/gateway/ci/cache/info?accountIdentifier=$HARNESS_ACCOUNT_ID&path=/path/to/deleted/folder' \
Editorial comment: I would probably format the last part as `&path=<path to directory to delete>` or something. I completely overlooked it in the current format assuming it was a standard file path.

2023-02-07 16:14 UTC, douglas-j-bothwell commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +            path:             # optional paths to support specific frameworks
@hemanthmantri Removing the `path:` field from this example. The Save and Restore Cache docs for [S3 ](https://ci.pr.harness.io/pr-624/docs/continuous-integration/use-ci/caching-ci-data/saving-cache) and [GCS](https://ci.pr.harness.io/pr-624/docs/continuous-integration/use-ci/caching-ci-data/save-cache-in-gcs) include YAML samples. If these need updating, we can do this in a separate ticket.

2023-02-08 21:02 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +```
We should have another YAML example for unsupported build tools and mention the `paths` key to be used to specify the list of paths that can be cached.

2023-02-08 21:31 UTC, douglas-j-bothwell reviewed
implemented edits

2023-02-08 21:43 UTC, douglas-j-bothwell commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +```
Will implement this in a future PR: https://harness.atlassian.net/browse/DOC-2583

2023-02-08 22:10 UTC, aimurphy commented on docs/continuous-integration/use-ci/caching-ci-data/cache-intelligence.md
> +  - The build tool must store cache data in the default location for that tool.
Should this bullet be indented more or outdented?

2023-02-08 22:11 UTC, aimurphy approved these changes
approved, just one question left as a comment.

2023-02-08 22:59 UTC, merged