[PL-38188] Update delegate YAML samples - add comments
harness/developer-hub pull request #6194
Opened 2024-04-03 21:27 UTC by brian-f-harness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Purpose

Update delegate YAML samples - add comments

Internal Harness contributors - Please edit this summary to include preview links after the preview build finishes.

## Merge requirements

- [x] Successful preview build.
- [ ] Code owner review.
- [x] No merge conflicts.

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

2024-04-04 10:29 UTC, mdmilic requested changes

2024-04-04 10:29 UTC, mdmilic commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +       harness.io/name: kubernetes-delegate
`PUT_YOUR_DELEGATE_NAME` instead of `kubernetes-delegate`.
Just an FYI, the names as such are actually not that important to match, what's important are labels and selectors, but to keep the things sane we name all the related resources with the same prefix (i.e. delegate name)

2024-04-04 10:29 UTC, mdmilic commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +    name: kubernetes-delegate
`PUT_YOUR_DELEGATE_NAME`

2024-04-04 14:17 UTC, brian-f-harness commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +       harness.io/name: kubernetes-delegate
```suggestion
       harness.io/name: PUT_YOUR_DELEGATE_NAME
```

2024-04-04 14:17 UTC, brian-f-harness commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +    name: kubernetes-delegate
```suggestion
    name: PUT_YOUR_DELEGATE_NAME
```

2024-04-04 14:45 UTC, mdmilic commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +   name: kubernetes-delegate-hpa
Sorry found one more place that I missed previously. I'll approve since this name is allowed to be anything, but you might want it to be consistent.

2024-04-04 14:45 UTC, mdmilic submitted a review, later dismissed

2024-04-04 16:05 UTC, brian-f-harness commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +   name: kubernetes-delegate-hpa
```suggestion
   name: PUT_YOUR_DELEGATE_NAME
```

2024-04-04 16:06 UTC, brian-f-harness commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +   name: kubernetes-delegate-hpa
Thanks @mdmilic!

2024-04-05 20:45 UTC, douglas-j-bothwell approved these changes
A few optional tweaks otherwise LGTM

2024-04-05 20:45 UTC, douglas-j-bothwell commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
>  Go to the following for an example of a Kubernetes manifest you can use to configure Harness Delegate and the Helm chart default `values.yaml` file.
```suggestion
Go to the following for an example of a Kubernetes manifest that you can use to configure Harness Delegate and the Helm chart default `values.yaml` file.
```

2024-04-05 20:45 UTC, douglas-j-bothwell commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +  # Use an existing Secret which stores the UPGRADER_TOKEN key instead of creating a new one. The value should be set with the `UPGRADER_TOKEN` key inside the secret.
```suggestion
  # Use an existing Secret that stores the UPGRADER_TOKEN key instead of creating a new one. The value should be set with the `UPGRADER_TOKEN` key inside the secret.
```

2024-04-05 20:45 UTC, douglas-j-bothwell commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +# Below are the required fields, no default values are populated for these.
```suggestion
# Below are the required fields. No default values are populated for these.
```

2024-04-05 20:45 UTC, douglas-j-bothwell commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +  # CI Mount targets are the locations that the secrets should be mounted in the CI Images. This will share any CA chain defined in the certs_path key to any CI image
```suggestion
  # CI Mount targets are the locations where the secrets should be mounted in the CI Images. This will share any CA chain defined in the certs_path key to any CI image
```

2024-04-05 20:45 UTC, douglas-j-bothwell commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +# This is the recommended way of using custom certs with CI.
```suggestion
# This is the recommended way to use custom certs with CI.
```

2024-04-05 20:45 UTC, douglas-j-bothwell commented on docs/platform/delegates/delegate-reference/YAML/example-kubernetes-manifest-harness-delegate.md
> +# Refer to: https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates/
```suggestion
# For more information, go to https://developer.harness.io/docs/continuous-integration/use-ci/set-up-build-infrastructure/k8s-build-infrastructure/configure-a-kubernetes-build-farm-to-use-self-signed-certificates/
```

2024-04-05 20:47 UTC, merged