Fixed yaml to be accurate (hopefully)
harness/developer-hub pull request #6220
Opened 2024-04-05 00:00 UTC by SushrutHarness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Purpose

What is the motivation for this PR? What changes does it include? Include as much or as little detail as needed.

Correct incorrect yaml in google functions file.

If this submission relates to a Jira or GitHub issue, include the issue ID in the title.

Internal Harness contributors - Please edit this summary to include preview links after the preview build finishes.

## Merge requirements

- [X] Successful preview build.
- [ ] Code owner review.
- [X] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

2024-04-05 00:08 UTC, guilhermezanini-harness requested changes

2024-04-05 00:08 UTC, guilhermezanini-harness commented on docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
> +    environmentVariables:
According to [Google Docs](https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v2#buildconfig), this one should be in snake case: `environment_variables`

2024-04-05 00:09 UTC, guilhermezanini-harness requested changes

2024-04-05 00:09 UTC, guilhermezanini-harness commented on docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
> +    environmentVariables:
Also in snake case the `buildConfig` attribute.

2024-04-05 00:11 UTC, guilhermezanini-harness requested changes

2024-04-05 00:11 UTC, guilhermezanini-harness commented on docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
> +    environmentVariables:
According to [Google Docs](https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v2#buildconfig), this one should be in snake case: environment_variables

The same applies to `buildConfig` and `entryPoint`.

2024-04-05 01:27 UTC, anshul-harness commented on docs/continuous-delivery/deploy-srv-diff-platforms/google-functions.md
> +  entry_point: myFunction
This looks incorrect to me. Please verify. This does not match the schema https://cloud.google.com/functions/docs/reference/rpc/google.cloud.functions.v2#function

2024-04-09 13:49 UTC, guilhermezanini-harness approved these changes
Everything looks good.

2024-04-09 14:08 UTC, roshnisarangadharan approved these changes

2024-04-09 14:15 UTC, merged