draft for split permissions
harness/developer-hub pull request #6227
Opened 2024-04-05 14:52 UTC by jenniferopal

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Purpose

Adding informations on split permissions. 

## Merge requirements

- [X] Successful preview build.
- [X] Code owner review.
- [X] No merge conflicts.
- [X] New features docs

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
> + 4. If you're sure you want to archive the flag, type the name or ID of the flag in the field provided, and then select **Archive**. Be aware you can restore the archived flag within 30 days.
user only needs to type in the ID of the flag, name's not required 👍

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
> + 2.
should this 2. be beside `A list of archived flags is displayed` ?

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
>  1. Next to the flag you want to restore, select **more options** (**︙**), and then select **Restore**.
should these be step 3 and 4?

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
>  1. On the confirmation screen, select **Delete**.
should this be step 2?

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +## Creating & Managing Roles
should the default be and ampersand or `and`, it seems to be a mix of both

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +The **Feature Flag Admin Role** is a default Role available specifically for Feature Flags. The administrator roles gives you the ability to grant and revoke  permissions at an environment level. Thi
```suggestion
The **Feature Flag Admin Role** is a default Role available specifically for Feature Flags. The administrator roles gives you the ability to grant and revoke permissions at an environment level. This includes:
```

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +The **Feature Flag Admin Role** is a default Role available specifically for Feature Flags. The administrator roles gives you the ability to grant and revoke  permissions at an environment level. Thi
just want to double check - are we referring to one or more administrator role here?

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +* Creating, Editing and deleting **Roles**, and
```suggestion
* Creating, editing and deleting **Roles**, and
```

2024-04-25 13:12 UTC, crystal-fong commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> + Resource groups within your Harness Account.
does this need a new line? same on line 79

2024-04-25 13:40 UTC, jenniferopal commented on docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
> + 2.
Yes, I missed that typo!

2024-04-25 13:45 UTC, jenniferopal commented on docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
>  1. Next to the flag you want to restore, select **more options** (**︙**), and then select **Restore**.
I split it into three steps instead. Hopefully this is better!

2024-04-25 14:15 UTC, jenniferopal commented on docs/feature-flags/ff-creating-flag/edit-and-delete-a-feature-flag.md
>  1. On the confirmation screen, select **Delete**.
Yes, it should! Thanks for spotting that!

2024-04-25 14:26 UTC, jenniferopal commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +The **Feature Flag Admin Role** is a default Role available specifically for Feature Flags. The administrator roles gives you the ability to grant and revoke  permissions at an environment level. Thi
This is just the one. I thought this was the only default role and the admin creates the additional roles? 
Is that correct?

2024-04-25 14:29 UTC, crystal-fong commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +The **Feature Flag Admin Role** is a default Role available specifically for Feature Flags. The administrator roles gives you the ability to grant and revoke  permissions at an environment level. Thi
ya that's right!

2024-04-25 15:17 UTC, Kira-Jennings commented on docs/feature-flags/ff-security-compliance/roles-and-permissions.md
> +Harness Feature Flags includes built-in roles for you to manage RBAC within the module. To examine the permissions assigned to these roles, to view them:
```suggestion
Harness Feature Flags includes built-in roles for you to manage RBAC within the module. To examine the permissions assigned to these roles:
```

2024-04-25 15:18 UTC, Kira-Jennings commented on docs/feature-flags/ff-security-compliance/roles-and-permissions.md
> +Harness Feature Flags includes built-in roles for you to manage RBAC within the module. To examine the permissions assigned to these roles, to view them:
The last sentence here didn't quite make sense

2024-04-25 15:19 UTC, Kira-Jennings commented on docs/feature-flags/ff-security-compliance/roles-and-permissions.md
> + 1. Select **Account Settings**, and then select **Access Control** along the top of the page, or by scrolling down.
Should we add that this is at the account level/scope only, the same as 2 & 3 mention scope?

2024-04-26 13:12 UTC, jenniferopal commented on docs/feature-flags/ff-security-compliance/roles-and-permissions.md
> + 1. Select **Account Settings**, and then select **Access Control** along the top of the page, or by scrolling down.
Yes, of course. I'll clarify that further. Thanks for pointing that out. :)

2024-04-26 14:56 UTC, HarnessTheChaos requested changes

2024-04-26 14:56 UTC, HarnessTheChaos commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +
Can these be bulleted out on their own line so it's easier to read?

![image](https://github.com/harness/developer-hub/assets/115592784/74ed2901-c300-400e-a661-e4e9329bffe4)

2024-04-26 14:56 UTC, HarnessTheChaos commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> +
Same type of bullets and single lines for ease of reading

2024-04-26 14:56 UTC, HarnessTheChaos commented on docs/feature-flags/ff-security-compliance/manage-access-control.md
> + 4. Within the Resources, select **Feature Flags**, Proxy Keys**, or both if that's what you require.
Proxy Keys needs the front **

2024-04-26 16:18 UTC, HarnessTheChaos approved these changes

2024-04-26 16:21 UTC, merged