Document SSCA Policy Violation Update
harness/developer-hub pull request #6244
Opened 2024-04-08 12:31 UTC by tejakummarikuntla

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Purpose

What is the motivation for this PR? What changes does it include? Include as much or as little detail as needed.

If this submission relates to a Jira or GitHub issue, include the issue ID in the title.

Internal Harness contributors - Please edit this summary to include preview links after the preview build finishes.

## Merge requirements

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

2024-04-08 16:27 UTC, humanshu2002 submitted a review, later dismissed

2024-04-09 06:47 UTC, pranay-harness approved these changes
LGTM

2024-04-16 05:46 UTC, sunilgupta-harness requested changes

2024-04-16 05:46 UTC, sunilgupta-harness commented on docs/software-supply-chain-assurance/ssca-policies/create-ssca-policies.md
> +- **Error and exit**: The step throws and error and terminates the pipeline execution.
It should be " The step throws an error" and further pipeline execution happens depending on the failure strategy of the step

2024-04-16 05:46 UTC, sunilgupta-harness commented on docs/software-supply-chain-assurance/ssca-policies/enforce-ssca-policies.md
> +* In a **Build** stage, add the step after the artifact (image) has been pushed to an artifact repository.
Step should be added after SBOM generation step

2024-04-16 05:46 UTC, sunilgupta-harness commented on docs/software-supply-chain-assurance/ssca-policies/overview.md
> +* Finally, a report is generated, highlighting the identified policy violations.
where report gets generate ?

2024-04-17 12:14 UTC, tejakummarikuntla commented on docs/software-supply-chain-assurance/ssca-policies/overview.md
> +* Finally, a report is generated, highlighting the identified policy violations.
@sunilgupta-harness, I agree that it would be beneficial to include information on the report's accessibility. However, these points give a conclusion of the overall process. The details of the report are linked at the beginning of the document itself.

2024-04-23 20:12 UTC, pranay-harness submitted a review, later dismissed

2024-05-02 08:45 UTC, tejakummarikuntla reviewed
Remove the usage of word "Report" in overview

2024-05-03 11:55 UTC, sunilgupta-harness approved these changes

2024-05-03 11:55 UTC, merged