Step group template
harness/developer-hub pull request #625
Opened 2023-02-07 11:46 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-07 14:38 UTC, thisrohangupta requested changes
We can create step group templates via API and Terraform Provider. 

Based of the YAML Body, Harness can detect for the Step Group object and automatically create the Step Group Template. There are no additional fields that need to be defined in the API or Terraform provider.

Create Templates API:
https://apidocs.harness.io/tag/Templates#operation/createTemplate 

Terraform Provider:
https://registry.terraform.io/providers/harness/harness/latest/docs/resources/platform_template

2023-02-07 14:58 UTC, yogesh-chauhan requested changes

2023-02-07 14:58 UTC, yogesh-chauhan commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +A step group in Harness is a collection of deployment steps that are executed together as a single unit. This allows you to organize and manage complex deployment processes by dividing them into smal
any type of deployment step -> we should say any type of Harness Pipeline Step. deployment is specific to CD. CI has different terminology

2023-02-07 14:58 UTC, yogesh-chauhan commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +By creating a step group template, you can standardize and simplify your deployment processes, and reduce the time and effort required to create new deployments. You can parameterize certain aspects
to create new deployments -> to create new pipelines and templates

2023-02-07 14:58 UTC, yogesh-chauhan commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +You can share your step group template at the project, organization, and account levels.
You can share your -> You can create your

2023-02-07 14:58 UTC, yogesh-chauhan commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +First, we'll create a project-level template in the **Deployments** module. You can do this in any project.
project-level -> project level

2023-02-07 14:58 UTC, yogesh-chauhan commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +1. Select **Deploy**. The deploy stage type is a CD Stage that enables you to deploy any service to your target environment.
can we mention that this deploy type decided where this step group template can be used ?
if type if deploy, it can used be used in "deploy" stage or stage templates
if type if build, it can used be used in "build" stage or stage templates

2023-02-08 04:52 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +A step group in Harness is a collection of deployment steps that are executed together as a single unit. This allows you to organize and manage complex deployment processes by dividing them into smal
Done

2023-02-08 04:53 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +By creating a step group template, you can standardize and simplify your deployment processes, and reduce the time and effort required to create new deployments. You can parameterize certain aspects
Done

2023-02-08 04:54 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +You can share your step group template at the project, organization, and account levels.
Done

2023-02-08 04:57 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +First, we'll create a project-level template in the **Deployments** module. You can do this in any project.
Rephrased to "Let us start by creating a template in the project scope within the **Deployments** module. "

2023-02-08 05:09 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +1. Select **Deploy**. The deploy stage type is a CD Stage that enables you to deploy any service to your target environment.
"The stage type you choose determines where you can reference the step group template in the pipeline. If you select Deploy as the stage type, you can reference the template in any pipeline's Deploy stage. If you select Build as the stage type, you can reference the template in any pipeline's Build stage."

2023-02-08 07:04 UTC, thisrohangupta approved these changes
Great work Rashmi!

2023-02-08 07:53 UTC, yogesh-chauhan approved these changes

2023-02-08 16:12 UTC, utkarshchoubey-harness submitted a review, later dismissed
LGTM!

2023-02-09 06:09 UTC, SudheendraKatte requested changes

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +If you do not use step group Conditional Execution settings, then the stage's conditional execution settings are used.
```suggestion
If you do not use step group Conditional Execution settings, then the stage's conditional execution settings are applied.
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +For more information, see [Step Failure Strategy Settings](../8_Pipelines/w_pipeline-steps-reference/step-failure-strategy-settings.md)
```suggestion
For more information, go to [Step Failure Strategy Settings](../8_Pipelines/w_pipeline-steps-reference/step-failure-strategy-settings.md)
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +If you do not use a step group Failure Strategy, then the Stage's Failure Strategy is used.
```suggestion
If you do not use a step group Failure Strategy, then the Stage's Failure Strategy is applied.
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +Select one of the following **Looping Strategy** to run your step multiple times with different inputs:
```suggestion
Select one of the following **Looping Strategy** options to run a step multiple times with different inputs: 
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +For more information, see [Looping Strategies Overview](../8_Pipelines/looping-strategies-matrix-repeat-and-parallelism.md)
```suggestion
For more information, go to [Looping Strategies Overview](../8_Pipelines/looping-strategies-matrix-repeat-and-parallelism.md)
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +Click **Save**. Enter a comment for you changes and click **Save**.
```suggestion
Click **Save**. Enter a comment for the changes and click **Save**.
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +Click **Save**. Enter a comment for you changes and click **Save**.
This is confusing. Do I need to click Save and then a screen appears where I enter the comments, and then click Save once again?

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +You can use the step group template in any pipeline in your project now that you have it.
You can use the step group template in any pipeline within your project.

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +4. Select your step group template from the list of templates.
```suggestion
4. Select step group template from the list of templates.
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +6. Enter a name for your template and click **Apply Changes**.
```suggestion
6. Enter a name for the template and click **Apply Changes**.
```

2023-02-09 06:09 UTC, SudheendraKatte commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +   The template is now referenced in your pipeline.
Your pipeline now includes a reference to the template.

2023-02-09 07:01 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +A step group in Harness is a collection of deployment steps that are executed together as a single unit. This allows you to organize and manage complex deployment processes by dividing them into smal
These are two words; the standard way to include them is without hyphens.

2023-02-09 07:04 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +Click **Save**. Enter a comment for you changes and click **Save**.
Yes.

2023-02-09 07:06 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +You can use the step group template in any pipeline in your project now that you have it.
Done

2023-02-09 07:07 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +4. Select your step group template from the list of templates.
This is specific to the template that was created in the previous step.

2023-02-09 07:09 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +   The template is now referenced in your pipeline.
Done

2023-02-09 07:10 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +7. Select the scope at which you want to save this template in **Save To**.
Done

2023-02-09 08:25 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +  2. In **Repository**, select your repository.​ If your repository isn't listed, enter its name since only a select few repositories are filled here.​Create the repository in Git before entering it
It is "Repository".

2023-02-09 08:33 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +   The stage type you choose determines where you can reference the step group template in the pipeline. If you select **Deploy** as the stage type, you can reference the template in any pipeline's d
Rephrased a bit differently.

2023-02-09 08:41 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +   You can add more steps to form a step group.
The intention here is to tell the users that they can add more steps if they want. Step group in itself is a group of multiple steps.

2023-02-09 08:52 UTC, rashminandasahoo commented on docs/platform/13_Templates/create-a-stepgroup-template.md
> +For more information, see [Step Failure Strategy Settings](../8_Pipelines/w_pipeline-steps-reference/step-failure-strategy-settings.md)
This is a cross-reference from another topic. "See" would be appropriate here.

2023-02-09 09:53 UTC, SudheendraKatte approved these changes
LGTM @rashminandasahoo

2023-02-09 10:19 UTC, merged