Security section
harness/developer-hub pull request #627
Opened 2023-02-07 15:59 UTC by SmritiSatya

Add security documentation
Signed-off-by: Smriti S <smriti.satyanarayana@harness.io>

2023-02-08 05:50 UTC, ksatchit commented
The google doc references should be avoided and this content needs to be brought into the HDH too.  We also need to add our recommended PSPs/policy specs into HDH as YAMLs embedded in markdown. Adding @uditgaurav for your help on this.

2023-02-09 05:32 UTC, deepakbolangady requested changes
This document from Engineering/PM needs some cleanup. Some of the changes I recommend making require a tech review. Please share the changes with the original author before incorporating. Thanks.

2023-02-09 05:32 UTC, deepakbolangady commented on docs/chaos-engineering/overview/harness-chaos-security.md
> +Depending upon (a) the infrastructure where chaos experiments are executed, and (b) desired list of chaos experiments, the permissions used can be modified (reduced) to create a lower blast radius an
```suggestion
Depending on the infrastructure on which chaos experiments are executed and the desired list of chaos experiments, the permissions used can be modified (reduced) to create a lower blast radius and impact from a security perspective. This applies to both Kubernetes-based and non-Kubernetes chaos. 
```
There is some ambiguity in the first sentence. Does it imply that the infrastructures and experiments in use determine whether or not users can modify permissions (for some infrastructures and experiments, they can; for others, they cannot)? The "depending upon" is making it a little unclear, and even if users understand it correctly, it won't be on the first pass. 

I think what is meant is this: You can fine-tune permissions to suit specific infrastructures and experiments if you want to reduce the blast radius and impact from a security perspective. 

Does that simplify the statement somewhat? When we use "depending on", we need to be clear.

2023-02-09 05:32 UTC, deepakbolangady commented on docs/chaos-engineering/overview/harness-chaos-security.md
> +In the case of the Kubernetes chaos, it is achieved through [service accounts](https://docs.google.com/document/d/1uB7BVFDdD8NfaT97MTj0qrF0eE3rnQOmpOOi4AqCzWE/edit#heading=h.p793kkfaj1zi) mapped to c
Does "default ones" refer to "default service accounts" or "default roles"? Replace "ones" accordingly.

```suggestion
In the case of the Kubernetes chaos, it is achieved through [service accounts](https://docs.google.com/document/d/1uB7BVFDdD8NfaT97MTj0qrF0eE3rnQOmpOOi4AqCzWE/edit#heading=h.p793kkfaj1zi) mapped to custom roles instead of the default ones mentioned in [Kubernetes roles for chaos infrastructure](#kubernetes-roles-for-chaos-infrastructure). For non-Kubernetes chaos, it is achieved through cloud-specific role definitions (for example, IAM) mapped to the user account.  
```
Also, please clarify what "it" refers to in both statements. Thanks.

2023-02-09 05:32 UTC, deepakbolangady commented on docs/chaos-engineering/overview/harness-chaos-security.md
> +Each fault in the enterprise ChaosHub publishes the permissions needed in order to execute it and users are free to tune their roles accordingly. Also available are common permission templates that w
```suggestion
Every fault in the Enterprise ChaosHub publishes the permissions that users need to execute the fault. Users can tune their roles. Also available are common permission templates that work as subsets/supersets for a specific category of experiments. For example, for information about recommended roles for AWS resource faults, go to [AWS resource faults](https://developer.harness.io/docs/chaos-engineering/chaos-faults/aws/policy-for-all-aws-faults). 
```
(Modified the statement that includes the reference to AWS resource faults because the link was not applied to the word "here", and that made me look below this paragraph for the roles.)

2023-02-09 05:32 UTC, deepakbolangady commented on docs/chaos-engineering/overview/harness-chaos-security.md
> +The deployments that comprise of the chaos infrastructure and the transient experiment pods launched to inject faults use the [in-cluster config](https://kubernetes.io/docs/tasks/run-application/acce
```suggestion
The deployments that comprise the chaos infrastructure and the transient experiment pods launched to inject faults use the [in-cluster configuration](https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/) to make Kubernetes API calls and thereby auto-mount service token secrets. The execution happens through non-root users with containers running secure base images. 
```

2023-02-09 05:32 UTC, deepakbolangady commented on docs/chaos-engineering/overview/harness-chaos-security.md
> +Some faults (mainly, the pod network and stress faults) necessitate container-runtime specific operations which necessitate privilege escalation, such as entering the network and pid namespaces, mani
```suggestion
Some faults (mainly, the pod network and stress faults) necessitate container-runtime—specific operations such as entering the network and pid namespaces. These operations in turn necessitate privilege escalation, manipulating the cgroup, and so on. In these cases, some of the pods are designed to run with privileged containers and root users. These pods also mount the runtime-specific socket files from the underlying host. However, it is important to note that such pods are short-lived (they exist for the duration of chaos) and can be run only if the users equip the serviceaccounts with access to the right security policy. 
```

2023-02-09 05:32 UTC, deepakbolangady commented on docs/chaos-engineering/overview/harness-chaos-security.md
> +Harness recommends security policy templates ([PSP](https://kubernetes.io/docs/concepts/security/pod-security-policy/), [OpenShift SCC](https://docs.openshift.com/container-platform/3.11/admin_guide/
```suggestion
To enable the execution of such experiments, Harness recommends the security policy templates ([PSP](https://kubernetes.io/docs/concepts/security/pod-security-policy/), [OpenShift SCC](https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html), and [Kyverno](https://kyverno.io/policies/)). 
```

2023-02-20 10:03 UTC, merged