Faq cd
harness/developer-hub pull request #6306
Opened 2024-04-11 22:54 UTC by austinthao5

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-04-11 22:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6306) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6306) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6306) it.</sub>

2024-04-12 20:18 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Git Triggers use Webhooks and where there's a webhook there's usually a payload you can utilize. The action used to trigger the Webhook should also be included in the Git Payload so you can reference
```suggestion
#### How do I get the index of a looping strategy?
You can use the `<+strategy.identifierPostFix>` expression to get the index of a strategy. For more information, go to the [identifierPostFix expressions](https://developer.harness.io/docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism/#identifierpostfix-expressions) documentation.

#### How do I use maps in Harness expressions?
You can convert map to JSON and use the `<+json.select()>` function to achieve this. For more information, go to [JSON and XML Functors](https://developer.harness.io/docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/json-and-xml-functors/) documentation.

#### How do I get the action of my Git trigger in an expression?
Git triggers use webhooks, and webhooks usually have a payload that you can utilize. The action used to trigger the webhook should also be included in the Git oayload so that you can reference the action using the `<+trigger.payload.action>` expression.
```

2024-04-12 20:18 UTC, SushrutHarness requested changes
Changing documentation reference lines to align with style guide.

2024-04-12 20:18 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +You can use the `<+strategy.identifierPostFix>` expression to get the index of a strategy. More information can be found in the [identifierPostFix expressions](https://developer.harness.io/docs/platf
```suggestion
You can use the `<+strategy.identifierPostFix>` expression to get the index of a strategy. More information, go to [identifierPostFix expressions](https://developer.harness.io/docs/platform/pipelines/looping-strategies/looping-strategies-matrix-repeat-and-parallelism/#identifierpostfix-expressions).
```

2024-04-12 20:18 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +You can convert the Map to JSON and use the `<+json.select()>` function in order to achieve this. More information can be found in the [JSON and XML Functors](https://developer.harness.io/docs/contin
```suggestion
You can convert the Map to JSON and use the `<+json.select()>` function in order to achieve this. For more information, go to [JSON and XML Functors](https://developer.harness.io/docs/continuous-delivery/x-platform-cd-features/cd-steps/utilities/json-and-xml-functors/).
```

2024-04-12 20:18 UTC, roshnisarangadharan approved these changes

2024-04-12 20:20 UTC, roshnisarangadharan submitted a review, later dismissed

2024-04-12 20:20 UTC, SushrutHarness submitted a review, later dismissed

2024-04-12 20:21 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Git triggers use webhooks, and webhooks usually have a payload that you can utilize. The action used to trigger the webhook should also be included in the Git oayload so that you can reference the ac
```suggestion
Git triggers use webhooks, and webhooks usually have a payload that you can utilize. The action used to trigger the webhook must be included in the Git payload so that you can reference the action using the `<+trigger.payload.action>` expression.
```

2024-04-12 20:21 UTC, roshnisarangadharan approved these changes

2024-04-12 20:34 UTC, merged