CI-5155 - revise set up test intelligence
harness/developer-hub pull request #631
Opened 2023-02-07 20:34 UTC by aimurphy

Clarified the calculation of **Duration** in the report.
General revisions throughout based on UI changes, additional languages supported, etc.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ x] Issue
- [ ] Feature
- [x ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ x] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-07 20:37 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +**Duration** reflects the sum of all test durations collected as-is from the JUnit report. These values corresponds with the CPU time, and it is possible that the sum of these times may exceed the to
@hemanthmantri This is the specific change for CI-5155/CI-5131. The rest of the changes are editorial or based on UI changes. Although you may also want to review the YAML at the end.

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   1. **Packages**: Leave blank or provide a comma-separated list of source code package prefixes, such as `com.company., io.company.migrations`. If blank, Harness auto-detects the package.
packages.

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   3. **Namespaces**: For .NET C# only, supply a comma-separated list of namespaces prefixes that you want to test.
namespace prefixes

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   4. **Image**: The name of the Docker image to use for running the build commands. Enter a Fully Qualified Image Name (FQIN) when using a private container registry.
Can we somehow mention that steps 3 and 4 are optional when "Harness Cloud" infrastructure is used?

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   Make sure the PR will trigger all tests, such as pom.xml, non-Java, and so on.
Ensure the build triggered due to this PR runs all the tests.

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +2. After the build succeeds, on the build details page, select **Tests**. **Tests** shows the test report for the test you configured for the **Run Tests** step. Harness publishes test results in JUn
Harness parses test reports only if they are in JUnit format. Please make sure the XML reports being generated in your tests are in JUnit format. Otherwise, the **Tests** tab will not show any tests.

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +**Duration** reflects the sum of all test durations collected as-is from the JUnit report. These values corresponds with the CPU time, and it is possible that the sum of these times may exceed the to
The test duration indicates the CPU time taken for all the tests to complete. 
Should we mention that the pipeline execution time is wall clock time?

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +Test Intelligence makes decisions about which tests to run by assessing changes to the pipeline's codebase or the individual tests.
... by assessing changes to the code base (source files or test files).

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +You can filter the list to only show failed tests; sort the list by failure rate, duration, and total tests; and expand test suites to see details about individual tests in that suite.
The default view only shows failed tests. Users can toggle the "Show all Tests" switch to see all the tests.

2023-02-10 05:18 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +    projectIdentifier: CD_Examples
CI_Examples

2023-02-10 16:33 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +You can enable Test Intelligence for builds in CI pipeline stages that use the **Run Tests** step. This topic explains how to set up Test Intelligence in a Harness CI pipeline stage.
Changed to "You can enable Test Intelligence by including a **Run Tests** step in your CI pipeline **Build** stages.

2023-02-10 16:36 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   4. **Image**: The name of the Docker image to use for running the build commands. Enter a Fully Qualified Image Name (FQIN) when using a private container registry.
Yes, I'll add that.

2023-02-10 16:39 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   Make sure the PR will trigger all tests, such as pom.xml, non-Java, and so on.
Changed to: Make sure that the build triggered by this PR runs all tests, such as pom.xml, non-Java, and so on.

2023-02-10 16:44 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +2. After the build succeeds, on the build details page, select **Tests**. **Tests** shows the test report for the test you configured for the **Run Tests** step. Harness publishes test results in JUn
Changed to: In order for the **Tests** tab to show tests, your test reports must be in JUnit XML format. Harness parses test reports that are in JUnit XML format only.

2023-02-10 16:48 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +**Duration** reflects the sum of all test durations collected as-is from the JUnit report. These values corresponds with the CPU time, and it is possible that the sum of these times may exceed the to
Revised as: **Duration** reflects the sum of CPU time taken for all tests to complete. The values are collected as-is from the JUnit report, and they don't correspond with wall clock time. In contrast, the pipeline execution time is a measure of wall clock time. Therefore, it is possible that the **Duration** may exceed the pipeline execution time.

2023-02-10 21:13 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   Make sure the PR will trigger all tests, such as pom.xml, non-Java, and so on.
Remove "such as pom.xml, non-java and son on.". Those are not tests. 

"Make sure that the build triggered by this PR runs all the tests."

2023-02-10 21:14 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   Make sure that the build triggered by this PR runs all tests, such as pom.xml, non-Java, and so on.
Remove    ", such as pom.xml, non-Java, and so on."

2023-02-10 21:20 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   Make sure that the build triggered by this PR runs all tests, such as pom.xml, non-Java, and so on.
removed

2023-02-10 22:30 UTC, KimberlyFields requested changes

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> -#### Visualization
Use tabs instead of headings to present the various parts of the sections of the test report/

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +### Reference: Test Intelligence pipeline configuration as code
Remove "Reference:". Think you should add "example" to the end of the title since this shows an example yaml template.

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +### See also
Remove this section. There's already a link to the overview at the beginning of the topic and there's no reason to link to view test reports here.

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +Bootstrapping generates the initial call graph for TI. Once the call graph is generated, TI can perform Test Selection.
Think more info is needed here. Do you need to do this once or every time you set up TI for a different build stage? Also, use lower case on Test Selection.

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +### Create the Build stage
I don't think this heading is accurate since you might already have a build stage where you want to add test intelligence. I think we can really simplify this topic by putting all the steps from Create the build stage through Configure the Run Tests step into a single procedure for setting up test intelligence.

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +**Duration** reflects the sum of CPU time taken for all tests to complete. The values are collected as-is from the JUnit report, and they don't correspond with wall clock time. In contrast, the pipel
"wall clock time"? Might not work for non-native English speakers.

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +Test Intelligence makes decisions about which tests to run by assessing changes to source files and test files in the codebase.
"makes decisions" - anthropomorphism

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +- **Updated Tests**: The number of tests that Test Intelligence ran because the tests themselves were changed
Add periods at the end of each sentence.

2023-02-10 22:30 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +Select **Expand graph** to display the Test Intelligence Visualization. Visualization shows why a specific test was selected and the reason behind every test selection. Purple nodes represent tests.
```suggestion
Select **Expand graph** to display the Test Intelligence Visualization, which shows why a specific test was selected and the reason behind every test selection. Purple nodes represent tests. Select any test (purple node) to see all the classes and methods covered by that test. Blue nodes represent changed classes and methods that caused Test Intelligence to select that test.
```

2023-02-11 07:29 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +**Duration** reflects the sum of CPU time taken for all tests to complete. The values are collected as-is from the JUnit report, and they don't correspond with wall clock time. In contrast, the pipel
What would be a good term to use to distinguish between total CPU "run time" (As an aggregate of time taken for all tests, even if they were running simultaneously) and "real world" time (How long you would wait for the tests to finish)?

2023-02-11 08:08 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +**Duration** reflects the sum of CPU time taken for all tests to complete. The values are collected as-is from the JUnit report, and they don't correspond with wall clock time. In contrast, the pipel
`wall clock time` is a well-understood term in computer science and some test runners also print wall clock time in the output. Another term is `elapsed time` (https://www.ibm.com/docs/en/zos/2.2.0?topic=indicators-elapsed-time) but I have seen `wall clock time` or `wall time` used more often.

2023-02-13 21:18 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +* If the pipeline already has as **Build** stage, select **Codebase** to configure the pipeline's codebase settings.
I'm going to condense this into a requirements section with tabs. The procedure needs the build stage, but users enabling TI probably already have a pipeline with a build stage. Experienced users will care more about which languages are supported than how to add a build stage.

2023-02-13 21:18 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +### Create the Build stage
Will fix.

2023-02-13 21:21 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +Bootstrapping generates the initial call graph for TI. Once the call graph is generated, TI can perform Test Selection.
@hemanthmantri Could you help me clarify when the bootstrap is needed? Do you only need to this this the first time you enable TI on the pipeline, or every time you add it to any stage in a pipeline?

2023-02-13 21:28 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
>  ![](./static/set-up-test-intelligence-02.png)
It was probably there because this topic originally didn't describe how to complete each field, it just said to look at the screenshot.

2023-02-13 23:50 UTC, hemanthmantri commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +Bootstrapping generates the initial call graph for TI. Once the call graph is generated, TI can perform Test Selection.
Bootstrap is per repository. Every time a new repository is being built for the first time in a RunTests step, we need to follow the above process. From the user's perspective, nothing actually changes. They raise a PR, let the tests run and if they pass, they merge the PR. They don't have to know there's something called Bootstrap behind the scenes. The only reason we mention this is - only after the first PR has been merged, the subsequent PRs can take advantage of the Callgraph to select a subset of tests instead of all tests.

2023-02-14 00:06 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +Bootstrapping generates the initial call graph for TI. Once the call graph is generated, TI can perform Test Selection.
@hemanthmantri Thank you! I revised it to: 
```
When you first enable Test Intelligence on a repo, you must run all tests to generate an initial call graph. This creates a baseline for test selection in future builds. To generate the initial call graph:

1. [Add a webhook trigger](../../../platform/11_Triggers/triggering-pipelines.md) to the pipeline that listens for PR merge events.
2. Open a PR against the pipeline's codebase. Make sure the build triggered by this PR runs all tests.
3. Merge the PR.
4. Wait while the pipeline executes. To monitor the build's progress, go to **Builds** and select the build that was started by the PR.
```

To clarify, the CI pipeline webhook trigger should listen for a PR to be *opened*, not *merged*? 
Should the steps be this instead?

```
1. [Add a webhook trigger](../../../platform/11_Triggers/triggering-pipelines.md) to the pipeline that listens for PRs to be opened against the pipeline's codebase.
2. Open a PR against the pipeline's codebase. Make sure the build triggered by this PR runs all tests.
3. Wait while the pipeline executes. To monitor the build's progress, go to **Builds** and select the build that was started by the PR.
4. If the tests pass and the build succeeds, merge the PR.
```

2023-02-16 02:12 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   8. **Test Report Paths**: Input one or more test report paths.
Consider putting these items in an expandable section.

2023-02-16 02:12 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   3. **Namespaces**: For .NET C# only, supply a comma-separated list of namespace prefixes that you want to test.
Consider putting these items in an expandable section.

2023-02-16 02:12 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +  * Blue nodes represent changes to classes and methods that caused Test Intelligence to select that test.
Consider putting this info in a table or some other format. I looked at the rendered content in the preview build and the number of bullets is a little overwhelming and hard to parse.

2023-02-16 02:12 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +```mdx-code-block
I looked at the rendered content in the preview build and I'm not about the use of tabs for these three requirements. I think of tabs as more useful in situations where there are many choices and the user only needs to pick the one they need. For example, for lists of parameters for different languages. The user many only use Go, so they know they just have to pick the Go tab for their instructions. Consider adding a sentence to guide the user to select each tab for details about each requirement or consider an alternate presentation.

2023-02-16 02:36 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +```mdx-code-block
What about accordions?

I'm operating on the assumption that users will already have some kind of pipeline set up before they get to setting up test intelligence, so I don't want these prerequisite steps to overwhelm the topic's actual purpose.

2023-02-16 03:33 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   8. **Test Report Paths**: Input one or more test report paths.
I moved the details over to the Run Tests step settings reference topic where it makes more sense for that info to be (at least for now). If I decide to elimiate the reference topics later, I will probably change this into a series of more detailed top-level steps, rather than a single top-level step with a bunch of substeps.

2023-02-16 03:37 UTC, KimberlyFields commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +```mdx-code-block
Accordions should work.

2023-02-16 03:38 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +   3. **Namespaces**: For .NET C# only, supply a comma-separated list of namespace prefixes that you want to test.
This is an important part of the initial setup and I am concerned that putting it in an accordion makes it seem optional.

2023-02-16 03:41 UTC, aimurphy commented on docs/continuous-integration/use-ci/set-up-test-intelligence/set-up-test-intelligence.md
> +  * Blue nodes represent changes to classes and methods that caused Test Intelligence to select that test.
I will put them in accordions.

2023-02-16 04:38 UTC, aimurphy commented
- Moved each setting's details to a more appropriate location, in the Run Tests step settings reference topic. General clean up of Run Tests step settings topic.
- Moved the YAML code up into an accordion under the step settings. The YAML can only be used to configure the step, so they still need to generate the initial call graph. If they skip to the end (where the YAML originally was), they have a higher chance of missing the call graph step.
- Not sure what to do about the roman numerals for the call graph. I will undoubtedly be back in this topic in the future, so I will revisit it then.
- Use accordions for the requirements and test report sections.
- Noticed an unnecessarily repeated sentence - reduced it into one location in the intro.

2023-02-16 04:41 UTC, aimurphy commented
Rebased to resolve a merge conflict

2023-02-16 15:01 UTC, KimberlyFields approved these changes
I left several new comments and suggestions, but I'm going to approve this PR with the understanding that you will address the comments.

2023-02-16 15:01 UTC, KimberlyFields commented on docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
> +* **Never:** The kubelet assumes that the image exists locally and doesn't try to pull the image.
A kubelet can't assume anything. Suggest revising the sentence to "The image is not pulled."

2023-02-16 15:01 UTC, KimberlyFields commented on docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
> +Set the value to specify the user Id for all processes in the pod, running in containers. For more information, go to [Set the security context for a pod](https://kubernetes.io/docs/tasks/configure-p
```suggestion
Set the value to specify the user ID for all processes in the pod, running in containers. For more information, go to [Set the security context for a pod](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).
```

2023-02-16 15:01 UTC, KimberlyFields commented on docs/continuous-integration/ci-technical-reference/configure-run-tests-step-settings.md
> +Set the value to specify the user Id for all processes in the pod, running in containers. For more information, go to [Set the security context for a pod](https://kubernetes.io/docs/tasks/configure-p
Not sure why you have a comma after "pod"

2023-02-16 15:02 UTC, KimberlyFields commented
@aimurphy the preview build didn't show your most recent changes. Not sure why. I assume that you tested the updated format locally and that the new expandables and tabs work as intended.

2023-02-16 16:01 UTC, merged