added gcp governance docs
harness/developer-hub pull request #6338
Opened 2024-04-16 10:44 UTC by joeyouss

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: Added documentation for GCP governance 
* Jira/GitHub Issue numbers (if any): CCM-17310
* Preview links/images (Internal contributors only): 

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-04-16 10:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6338) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6338) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6338) it.</sub>

2024-04-17 04:32 UTC, iamanmolm requested changes

2024-04-17 04:32 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/GCP/2-Harness-Concepts.md
> +- **Target Accounts and Regions**: The target accounts and regions that you will be running the Enforcements on.
GCP doesn't have regions.

2024-04-17 04:32 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/GCP/2-Harness-Concepts.md
> +You can view any Enforcements on Rule Enforcements page. Click on the enforcement to view details such as the rules, target accounts, and regions included in the enforcement. For updating, you can us
GCP doesn't have regions.

2024-04-17 04:32 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/GCP/gcp-recommendations.md
> +title: GCP Recommendations
Kindly update this with the recommendation policies shared over slack.

2024-04-18 00:50 UTC, iamanmolm requested changes

2024-04-18 00:50 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/GCP/gcp-recommendations.md
> +Recommendations help kickstart your journey with governance. Essentially, Harness runs certain policies behind the scenes to generate recommendations for your governance-enabled Azure subscriptions.
"governance-enabled GCP projects."

2024-04-18 00:50 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/GCP/gcp-recommendations.md
> +**Savings Computed:** Savings are determined as 35% of the total cost. Implementing this recommendation would result in a 35% reduction in the maintenance cost of that disk, bringing it down to 92%.
"Savings are considered as 35% of the total cost. Implementing this recommendation would result in 35% to 92% reduction in the maintenance cost of that disk. Thus, we considered the minimum savings achievable, which is 35%. Ref: https://cloud.google.com/compute/docs/viewing-and-applying-idle-resources-recommendations"

2024-04-18 04:56 UTC, iamanmolm submitted a review, later dismissed

2024-04-18 12:21 UTC, SmritiSatya submitted a review, later dismissed

2024-04-18 14:13 UTC, merged