[PL-49108] PL 1.34.x Release Notes
harness/developer-hub pull request #6366
Opened 2024-04-18 09:31 UTC by saifeemustafaqharness

[PL-49108](https://harness.atlassian.net/browse/PL-49108)

https://harness.atlassian.net/wiki/spaces/PD/pages/21749825690/NG+Release+SAAS+April+15th+2024+for+1.34.x-+Build

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-04-22 13:40 UTC, brian-f-harness requested changes

2024-04-22 13:40 UTC, brian-f-harness commented on release-notes/platform.md
> +   ```
```suggestion
- We've added an optional registry mirror configuration for delegate `upgrader`. If you use Docker pull through registry cache (`https://docs.docker.com/docker-hub/mirror/`), you can configure `upgrader` to use an optional registry mirror for your delegate images. For more information, go to [Configure an optional registry mirror for delegate images](/docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration#configure-an-optional-registry-mirror-for-delegate-images). (PL-47920, ZD-59005)
```

2024-04-22 13:40 UTC, brian-f-harness commented on release-notes/platform.md
> +- 2FA reset emails were failing to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR
```suggestion
- 2FA reset emails failed to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR codes are now correctly included in 2FA reset emails. (PL-48980, ZD-61314, ZD-61420, ZD-61486)
```

2024-04-22 13:40 UTC, brian-f-harness commented on release-notes/platform.md
> +- 2FA reset emails were failing to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR
@saifeemustafaqharness please add the Zendesk ticket ID references.

2024-04-22 13:40 UTC, brian-f-harness commented on release-notes/platform.md
> +- The link to Slack on the UI Help section was not functioning. The community link has been updated to ensure it works correctly. (PL-48948)
```suggestion
- The link to Slack on the UI Help section was not functioning. The community link has been updated to ensure it works correctly. (PL-48948, ZD-61203)
```

2024-04-22 13:40 UTC, brian-f-harness commented on release-notes/platform.md
> +- When a new pipeline for approval was created, but the approval email was not being sent, preventing testing of the link within the approval email. Resolved this issue that prevented notifications f
```suggestion
- When a new pipeline for approval was created, but the approval email was not being sent, preventing testing of the link within the approval email. Resolved this issue that prevented notifications from being sent to multiple emails configured in a user group for email notifications. (PL-48854, ZD-60366, ZD-61333)
```

2024-04-22 13:40 UTC, brian-f-harness commented on release-notes/platform.md
> +- 2FA reset emails were failing to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR
```suggestion
- 2FA reset emails failed to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR codes are now correctly included in 2FA reset emails. This item requires Harness Delegate version 24.03.82709. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate) (PL-48980, ZD-61314, ZD-61420, ZD-61486)
```

2024-04-22 18:42 UTC, brian-f-harness commented on release-notes/platform.md
> +date: 2024-04-22:T10:00:30
```suggestion
date: 2024-04-23:T10:00:30
```

2024-04-22 18:42 UTC, brian-f-harness commented on release-notes/platform.md
> +### Version 1.34.x<!--  April 22, 2024 -->
```suggestion
### Version 1.34.x<!--  April 23, 2024 -->
```

2024-04-22 19:44 UTC, brian-f-harness commented on release-notes/platform.md
> +   ```
@saifeemustafaqharness suggest a more concise RN here and link to the docs that are already in place. Also, please remember to add all applicable Zendesk ticket IDs for all applicable RN.

2024-04-23 12:48 UTC, brian-f-harness requested changes
Some suggested changes

2024-04-23 13:38 UTC, brian-f-harness commented on release-notes/platform.md
> +- The delegate task rejection metric was designed to reflect tasks rejected by a delegate due to system-related reasons (such as lack of resources or exceeding the limit of parallel tasks) but did no
```suggestion
- The delegate task rejection metric was designed to reflect tasks rejected by a delegate due to system-related reasons (such as lack of resources or exceeding the limit of parallel tasks) but did not include specific details like task type or task ID. Enhanced the task rejection metrics by adding `taskType` and `taskId` labels. This item requires Harness Delegate version 24.04.82804. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate) (PL-48488)
```

2024-04-23 13:39 UTC, brian-f-harness commented on release-notes/platform.md
>  - Users were being logged out when testing a Git connector with invalid credentials due to the Git client's 401 response being propagated to the UI. Implemented error handling to convert a 401 respon
```suggestion
- Users were being logged out when testing a Git connector with invalid credentials due to the Git client's 401 response being propagated to the UI. Implemented error handling to convert a 401 response from the test connection step to a 400, while preserving the original error message, preventing unintended user logouts. This item requires Harness Delegate version 24.04.82804. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate). (PL-47753, ZD-58629)
```

2024-04-23 13:40 UTC, brian-f-harness commented on release-notes/platform.md
> +- 2FA reset emails failed to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR codes
```suggestion
- 2FA reset emails failed to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR codes are now correctly included in 2FA reset emails. This item requires Harness Delegate version 24.04.82804. For information about Harness Delegate features that require a specific delegate version, go to the [Delegate release notes](/release-notes/delegate). (PL-48980, ZD-61314, ZD-61420, ZD-61486)
```

2024-04-23 19:46 UTC, pratmit approved these changes
LGTM

2024-04-23 19:49 UTC, merged