[PL-49109] DEL 82800 Release Notes
harness/developer-hub pull request #6367
Opened 2024-04-18 09:40 UTC by saifeemustafaqharness

[PL-49109](https://harness.atlassian.net/browse/PL-49109)

https://harness.atlassian.net/wiki/spaces/PD/pages/21749825690/NG+Release+SAAS+April+15th+2024+for+1.34.x-+Build#NG-Delegate-dependent-changes--

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-04-22 13:44 UTC, brian-f-harness commented on release-notes/delegate.md
> +- 2FA reset emails were failing to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR
```suggestion
- 2FA reset emails failed to display the QR code properly due to the recent deprecation of Google APIs. The method for generating QR codes has been updated, resolving the issue and ensuring QR codes are now correctly included in 2FA reset emails. (PL-48980, ZD-61314, ZD-61420, ZD-61486)
```

2024-04-22 13:44 UTC, brian-f-harness commented on release-notes/delegate.md
> +- The delegate task rejection metric was designed to reflect tasks rejected by a delegate due to system-related reasons (such as lack of resources or exceeding the limit of parallel tasks) but did no
Is there an update required to the delegate metrics topic for this? If so, do we have a docs ticket?

2024-04-22 18:41 UTC, brian-f-harness commented on release-notes/delegate.md
Update the date field in the frontmatter before merging

2024-04-23 12:28 UTC, brian-f-harness requested changes

2024-04-23 12:28 UTC, brian-f-harness commented on release-notes/platform.md
> +- The delegate task rejection metric was designed to reflect tasks rejected by a delegate due to system-related reasons (such as lack of resources or exceeding the limit of parallel tasks) but did no
@saifeemustafaqharness I think the changes to the platform.md file should be in the PL RN PR, not here.

2024-04-23 13:22 UTC, saifeemustafaqharness commented on release-notes/platform.md
> +- The delegate task rejection metric was designed to reflect tasks rejected by a delegate due to system-related reasons (such as lack of resources or exceeding the limit of parallel tasks) but did no
actually this was an addition about the release version. But you are absolutely right, I agree. It should have been with PL release, rather than DEL RN

2024-04-23 13:24 UTC, saifeemustafaqharness commented on release-notes/delegate.md
Yes, will do

2024-04-23 13:25 UTC, saifeemustafaqharness commented on release-notes/delegate.md
Thanks Brian!!

2024-04-23 13:33 UTC, saifeemustafaqharness commented on release-notes/delegate.md
> +- The delegate task rejection metric was designed to reflect tasks rejected by a delegate due to system-related reasons (such as lack of resources or exceeding the limit of parallel tasks) but did no
I don't think we have a docs ticket for this.

2024-04-23 13:36 UTC, brian-f-harness commented on release-notes/delegate.md
> +date: 2024-04-24T10:00
```suggestion
date: 2024-04-23T10:00
```

2024-04-23 14:10 UTC, brian-f-harness submitted a review, later dismissed

2024-04-23 21:58 UTC, brian-f-harness commented on release-notes/delegate.md
> +date: 2024-04-23T10:00
```suggestion
date: 2024-04-24T10:00
```

2024-04-23 21:58 UTC, brian-f-harness commented on release-notes/delegate.md
> +### Harness version 1.34.2, Harness Delegate version 24.04.82804 <!--  April 23, 2024 -->
```suggestion
### Harness version 1.34.2, Harness Delegate version 24.04.82804 <!--  April 24, 2024 -->
```

2024-04-24 13:25 UTC, brian-f-harness approved these changes

2024-04-24 17:42 UTC, pratmit approved these changes
LGTM

2024-04-24 17:49 UTC, merged