Update FAQ
harness/developer-hub pull request #6388
Opened 2024-04-18 21:45 UTC by brijeshjagani

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \ Pushing New FAQ

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [X] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-04-18 21:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6388) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6388) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6388) it.</sub>

2024-04-18 23:56 UTC, SushrutHarness requested changes
Some typos, and formatting changes!

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Save the cloned rule.
Can you make these steps a numbered list?

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +To switch back to the old UI in Harness, adjust the user preference settings in your Account Settings.
Can we get more detail on how to navigate here in a "**Account Settings** > **User Preferences** > **Old UI**" style format?

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### How to Install Powershell on harness delegate?
```suggestion
#### How to Install Powershell on the Harness Delegate?
```

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +https://developer.harness.io/docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile/
```suggestion
go to [Custom Images Delegate Dockerfile](]https://developer.harness.io/docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile/)
```

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Would like to know what are the account using older delegate version?
```suggestion
#### What accounts are using the older delegate version?
```

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +You can determine if an account is using an older delegate version by checking the Delegate release notes. The release notes provide information about features that require a specific delegate versio
```suggestion
You can determine if an account is using an older delegate version by checking the delegate release notes. The release notes provide information about features that require a specific delegate version. If the account is using a version older than the required version for a specific feature, then they are using an older delegate version.
```

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +You can also use check article here to verify which is the supported version for your account and check delegate version which you are using. https://developer.harness.io/docs/platform/delegates/inst
```suggestion
To verify what version is supported for your account, and to check which delegate version you are using, go to [Delegate Upgrades and Expiration]9https://developer.harness.io/docs/platform/delegates/install-delegates/delegate-upgrades-and-expiration/#use-automatic-upgrade-with-custom-delegate-images)
```

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Apply the changes.
Can you make these steps a numbered list.

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Click "Save" and select permissions for the role.
Use **<example text>** to make a word bold to indicate an in interface option to select.

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Yes, you can create a policy to block deployments when all tests are not successful. Here's an example policy that can be applied using the On Run event for a pipeline:
```suggestion
Yes, you can create a policy to block deployments when all tests are not successful. Here's an example policy that can be applied using the **On Run** event for a pipeline:
```

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +https://developer.harness.io/docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile/
```suggestion
To learn more, go to [Build Custom Image Delegates](https://developer.harness.io/docs/platform/delegates/manage-delegates/build-custom-images-delegate-dockerfile/)
```

2024-04-18 23:56 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +I recommend reviewing the document available at:
```suggestion
```

2024-04-19 17:52 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +<+infra.tags.endpoint> is not available as a Harness Variable. Refer to the Supported Infra Harness Variable documentation for more details.
```suggestion
`<+infra.tags.endpoint>` is not available as a Harness Variable. Refer to the Supported Infra Harness Variable documentation for more details.
```

2024-04-19 17:53 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +####  What is <+infra.tags.endpoint>?
```suggestion
####  What is `<+infra.tags.endpoint>`?
```

2024-05-01 16:20 UTC, aimurphy commented
These questions are duplicated/moved to PR 6531. Closing here to avoid MC/unnecessary duplication.

2024-05-01 16:20 UTC, closed without merging