[PL-49125] Add Harness OIDC provider endpoint and OIDC audience settings
harness/developer-hub pull request #6408
Opened 2024-04-19 23:23 UTC by brian-f-harness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: Add Harness OIDC provider endpoint and OIDC audience settings
* Jira/GitHub Issue numbers (if any): PL-49125
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-04-23 18:28 UTC, Raghav-Murali commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> -* **Use OIDC**: Connect to AWS with OIDC. In order to do this you will need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
Do we have a reference of the FF `CDS_AWS_OIDC_AUTHENTICATION` in this doc ? This flag has to be enabled for AWS OIDC feature.

2024-04-23 18:30 UTC, Raghav-Murali commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> +* **Use OIDC**: Connect to AWS with OIDC. To do this you will need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html) in AWS a
Include the parent link of the doc - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_oidc.html

2024-04-23 18:39 UTC, Raghav-Murali commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
> +To connect to GCP with OIDC, you must configure an [OIDC identity provider](https://cloud.google.com/identity-platform/docs/web/oidc#configuring_the_provider) in GCP and add it in a trust relationshi
Include this link instead - https://cloud.google.com/iam/docs/workload-identity-federation-with-other-providers.

There is no trust relationship in GCP. We need to connect the Service Account with relevant permissions to the Workload Identity Federation. So rewrite this line as -

To connect to GCP with OIDC, you must configure an [OIDC identity provider](https://cloud.google.com/identity-platform/docs/web/oidc#configuring_the_provider) in GCP and connect the service account with relevant permissions that Harness will use to operate in GCP.

2024-04-23 18:39 UTC, Raghav-Murali commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
> +   * OIDC audience: `sts.amazonaws.com](https://iam.googleapis.com/projects/<YOUR_GCP_PROJECT_ID>/locations/global/workloadIdentityPools/<YOUR_WORKLOAD_POOL_ID>/providers/<YOUR_PROVIDER_ID>`
No `sts.amazonaws.com` here.

2024-04-23 18:40 UTC, Raghav-Murali requested changes
Please address the comments.

2024-04-23 23:46 UTC, brian-f-harness commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> -* **Use OIDC**: Connect to AWS with OIDC. In order to do this you will need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
@Raghav-Murali Yes. I removed it with a commit. It was on line 434.

2024-04-23 23:50 UTC, brian-f-harness commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference.md
> +   * OIDC audience: `sts.amazonaws.com](https://iam.googleapis.com/projects/<YOUR_GCP_PROJECT_ID>/locations/global/workloadIdentityPools/<YOUR_WORKLOAD_POOL_ID>/providers/<YOUR_PROVIDER_ID>`
copy-paste error. Thanks for catching it.

2024-04-24 00:02 UTC, brian-f-harness commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> -* **Use OIDC**: Connect to AWS with OIDC. In order to do this you will need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
@Raghav-Murali I also removed the other instances of the FF we had in docs.
cc @roshnisarangadharan @SushrutHarness @krishi0408

2024-04-26 00:26 UTC, Raghav-Murali commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> -* **Use OIDC**: Connect to AWS with OIDC. In order to do this you will need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
@brian-f-harness This should not be removed. I was just asking whether a reference for this FF was provided earlier.

2024-04-26 00:30 UTC, brian-f-harness commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> -* **Use OIDC**: Connect to AWS with OIDC. In order to do this you will need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_oidc.html)
Thanks @Raghav-Murali I misread your comment.

2024-04-29 18:11 UTC, Raghav-Murali approved these changes

2024-04-29 19:26 UTC, douglas-j-bothwell submitted a review, later dismissed
A few sugs otherwise LGTM

2024-04-29 19:26 UTC, douglas-j-bothwell commented on docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference.md
> +* **Use OIDC**: Connect to AWS with OIDC. To do this you will need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_oidc.html) in AWS and add
```suggestion
* **Use OIDC**: Connect to AWS with OIDC. To do this, you need to create an [OIDC identity provider](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_oidc.html) in AWS. Then you need to add it in a trust relationship with an IAM role you create that Harness will use to operate in AWS. Use the following Harness OIDC provider endpoint and OIDC audience settings to create your OIDC identity provider.
```

2024-04-29 19:26 UTC, douglas-j-bothwell commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +This only leverages the account ID parameter when we send the token payload to the AWS STS service. For more information, go to [Harness AWS connector settings](https://developer.harness.io/docs/plat
```suggestion
This only leverages the account ID parameter when Harness sends the token payload to the AWS STS service. For more information, go to [Harness AWS connector settings](https://developer.harness.io/docs/platform/connectors/cloud-providers/ref-cloud-providers/aws-connector-settings-reference/#harness-aws-connector-settings).
```

2024-04-29 19:42 UTC, merged