[CCM- 17412]: revamped the overview page for AG
harness/developer-hub pull request #6412
Opened 2024-04-22 11:19 UTC by joeyouss

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-04-22 11:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6412) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6412) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6412) it.</sub>

2024-04-22 12:08 UTC, iamanmolm requested changes

2024-04-22 12:08 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +  - **Recommendations** - Harness displays a list of ten recommendations that can help optimize the cloud assets and minimize cloud costs. Harness highlights the total potential savings that can be a
"**Recommendations** - Governance Overview displays a list of all recommendations that can help optimize the cloud assets and minimize cloud costs. Governance Overview highlights the total potential savings that can be achieved if all recommendations are applied."

2024-04-22 12:08 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +    Additional to this, for each recommendation, Harness shows:
"Additional to this, for each recommendation, Harness shows more details like:"

2024-04-22 12:08 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +    - **Potential Monthly Spend**: Potential Monthly Spend is the monthly spend for all the resources that surfaced out as part of recommendations. Why potential? Because the resource might be newly
"which might not be present for all the days for newly created resources."

2024-04-22 12:08 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### What’s supported
Multi Policy is cost co-relation is now supported for all cloud providers.

2024-04-22 12:08 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### What’s supported
Recommendation for GCP is also added.

2024-04-22 12:15 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  The **Overview** page offers a consolidated summary of your organization's governance rules, enforcements, and cost savings resulting from rule executions. This provides a quick and easy way to monit
done

2024-04-22 12:16 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +  - **Total Savings** — The total cost savings achieved from the day you began utilizing CCM Asset Governance up to the present date.
done

2024-04-22 12:16 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +    - **By Cloud Provider**: This shows savings data for each cloud provider.
done

2024-04-22 12:18 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +  - **Recommendations** - Harness displays a list of ten recommendations that can help optimize the cloud assets and minimize cloud costs. Harness highlights the total potential savings that can be a
done

2024-04-22 12:18 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +    Additional to this, for each recommendation, Harness shows:
done

2024-04-22 12:19 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### What’s supported
done

2024-04-23 03:58 UTC, iamanmolm requested changes

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +    - **Potential Monthly Spend**: Potential Monthly Spend is the monthly spend for all the resources that surfaced out as part of recommendations which might not be present for all the days for newl
"**Potential Monthly Spend**: Potential Monthly Spend is the monthly spend for all the resources that surfaced out as part of recommendations. Why potential? Because the resource might be newly added and Harness looks at the last 30 days of cost data which might not be present for all the days for newly created resources."

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  To apply a recommendation, select the row. The recommendation opens on the **Recommendations** page. To learn how to enforce this recommendation, go to [Governance recommendations](/docs/cloud-cost-m
This page seems to be outdated. We can fix this up and make it more generalised.

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### What’s supported
Subheading seems to be mis-aligned:
<img width="342" alt="Screenshot 2024-04-23 at 9 21 08 AM" src="https://github.com/harness/developer-hub/assets/105212590/1f01c36d-71fd-4770-8d6c-f793959c1f28">

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +| AWS   | aws.ec2, aws.ebs, aws.rds, aws.ebs-snapshot | Yes ✅ | Yes ✅ | Yes ✅ | Yes ✅ |
For aws we support for cost co-relation for 2 more resources: aws.elastic-ip, aws.elb. Also for gcp we added support for cost co-relation: gcp.instance, gcp.disk, gcp.snapshot, gcp.sql-instance, gcp.image.

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +| Azure | Every Resource in Billing Report | Yes ✅ | Yes ✅ | Yes ✅ | No ❌ |
Add a note below stating "Cost co-relation for GCP would work only if we have detailed billing export setup."

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  Cost Correlation Refresh API: This API is used to refresh or update the cost of all resources in the evaluation. It is exposed to resolve cases where the cost for any resource is not yet part of CUR,
On this page below AIDA line seems unrelatable.

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### How is Cost Correlation Computed
Change heading to "Cost Correlation Refresh API".

2024-04-23 03:58 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +- [Asset Governance recommendations for AWS](https://developer.harness.io/docs/cloud-cost-management/use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations)
Also in AWS recommendations we have added few more recommendations and I see we did not did not added Savings Computed section in AWS.

2024-04-23 05:02 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### What’s supported
done

2024-04-23 05:02 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +    - **Potential Monthly Spend**: Potential Monthly Spend is the monthly spend for all the resources that surfaced out as part of recommendations which might not be present for all the days for newl
done

2024-04-23 05:02 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +| AWS   | aws.ec2, aws.ebs, aws.rds, aws.ebs-snapshot | Yes ✅ | Yes ✅ | Yes ✅ | Yes ✅ |
done

2024-04-23 05:05 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +| Azure | Every Resource in Billing Report | Yes ✅ | Yes ✅ | Yes ✅ | No ❌ |
done

2024-04-23 05:06 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### How is Cost Correlation Computed
done

2024-04-23 05:06 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  Cost Correlation Refresh API: This API is used to refresh or update the cost of all resources in the evaluation. It is exposed to resolve cases where the cost for any resource is not yet part of CUR,
done

2024-04-23 05:07 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +- [Asset Governance recommendations for AWS](https://developer.harness.io/docs/cloud-cost-management/use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations)
I will update that in another PR for recommendations changes

2024-04-23 05:10 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  To apply a recommendation, select the row. The recommendation opens on the **Recommendations** page. To learn how to enforce this recommendation, go to [Governance recommendations](/docs/cloud-cost-m
ok, for now should I remove it? I can add it when I update recomendations page. We are revamping recommendations docs to make it better in this and next sprint

2024-04-23 05:44 UTC, iamanmolm requested changes

2024-04-23 05:44 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +    - **Potential Monthly Spend**: PPotential Monthly Spend is the monthly spend for all the resources that surfaced out as part of recommendations. Why potential? Because the resource might be newly
PP in Potential is wrong.

2024-04-23 05:44 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  To apply a recommendation, select the row. The recommendation opens on the **Recommendations** page. To learn how to enforce this recommendation, go to [Governance recommendations](/docs/cloud-cost-m
Keep it for now.

2024-04-23 05:44 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +## Cost Correlation Refresh API
Wrong heading modified.

2024-04-23 05:44 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
>  ### How is Cost Correlation Computed
Change this heading to "Cost Correlation Refresh API"

2024-04-23 05:45 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/3-gov-overview.md
> +- [Asset Governance recommendations for AWS](https://developer.harness.io/docs/cloud-cost-management/use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations)
Okay

2024-04-23 08:31 UTC, merged