added 30 FAQs
harness/developer-hub pull request #6528
Opened 2024-04-30 18:54 UTC by ank1064

tested locally

2024-04-30 19:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6528) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6528) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6528) it.</sub>

2024-04-30 19:30 UTC, SushrutHarness requested changes
Requesting changes, there is an FAQ here that needs to be rewritten! Please take a look

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### How to reference multiple values of dropdown in the pipeline?
```suggestion
#### How do I reference multiple values of a dropdown in the pipeline?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +You can reference using the same output expression and the value will come up as a string, you can use split() to get the separate value from the array.
```suggestion
You can reference using the same output expression and the value will come up as a string. Then, you can use split() to get each separate value from the array.
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Backend config not getting picked up in terraform deployment even if it's defined in the terraform plan step?
```suggestion
#### Why is my backend config not getting picked up in the terraform deployment even if it's defined in the terraform plan step?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Does harness support formatting of code from single line to multi-line?
```suggestion
#### Does Harness support formatting of code from single line to multi-line?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +No, the harness does not support code formatting. You will have to format the code manually and add it to the harness. Harness will preserve the format
```suggestion
No, Harness does not support code formatting. You will have to format the code manually and add it to Harness. Harness will preserve the format
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Getting the message "Invalid transition to status" on running the Jira update step?
```suggestion
#### Why am I getting the error "Invalid transition to status" when running the Jira update step?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Secret Value Beginning with "*" Returns Error when assigned to a value in K8s manifest?
```suggestion
#### Why does the secret value beginning with "*" return an error when assigned to a value in K8s manifest?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +The error is due to K8s behavior. Anything without quotes and and starts with * is treated as an anchor. To preserve the value as it is, we need to pass it in quotes. regarding the password being unm
```suggestion
The error is due to K8s behavior. Anything without quotes and starts with * is treated as an anchor. To preserve the value as it is, we need to pass it in quotes.
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Harness expression not resolving on execution, when variable name as hyphen in its name?
```suggestion
#### Why is my Harness expression not resolving on execution when the variable name has a hyphen?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +"Hyphens" are not allowed for variable names. Due to this validation check expression resolution fails.
```suggestion
"Hyphens" are not allowed for variable names. Due to this, the expression's validation check fails.
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### How do I preserve some original values of pipeline run such as triggerType even in case of re-running the pipeline?
```suggestion
#### How do I preserve some original values of a pipeline run (such as triggerType) even when I rerun the pipeline?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +One way, where you store the triggertype value in a project-level variable and check the condition on that variable.
```suggestion
You can store the triggerType value in a project-level variable and check the condition on that variable.
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +i.e you can create a project-level variable and add a shell script at the beginning of the pipeline to store the value of the trigger type using an API. So whenever the pipeline is run by webhook the
```suggestion
In other words, you can create a project-level variable and add a shell script at the beginning of the pipeline to store the value of the trigger type using an API. Then, whenever the pipeline is run by webhook the value is updated to type webhook and once the pipeline is completely run, you can add another API call to clear out the status.
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +i.e you can create a project-level variable and add a shell script at the beginning of the pipeline to store the value of the trigger type using an API. So whenever the pipeline is run by webhook the
Can someone else take a look at this and figure out a clearer way to state this?

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Cannot rename the Project level service in Harness when updated on the Git side?
```suggestion
#### Why can I not rename the Project level service in Harness when it is updated on the Git side?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made git side, we were able to fetch the YAML but metadata DB did not get updated. To res
```suggestion
By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made on the git side, we are able to fetch the YAML but the metadata DB does not get updated. To resolve this please rename the service from UI save the pipeline. it will sync the db as well as git YAML.
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made git side, we were able to fetch the YAML but metadata DB did not get updated. To res
What does, `To resolve this please rename the service from UI save the pipeline.` mean? Are we renaming the pipeline to `save the pipeline` ? Also how does the DB affect the ability to rename the pipeline? I'm unclear what the question is, and what its answer means

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Service name not showing in the Select Service when launching the pipeline in case of multiservice?
```suggestion
#### Why is my service name not showing up in `Select Service` when launching the pipeline with `Deploy multiple services` enabled?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Custom approval step does not acknowledge the updated value in YAML on retry?
```suggestion
#### Why does the custom approval step not acknowledge the updated value in YAML on a retry?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Why commit is created with a bot connector and not a user account when a pipeline is saved?
```suggestion
#### Why is a commit created with a bot connector and not a user account when a pipeline is saved?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Why PR is created with a bot connector and not a user account when a pipeline is saved and OAuth integrated with git exp?
```suggestion
#### Why is a PR created with a bot connector and not a user account when a pipeline is saved and OAuth integrated with git exp?
```

2024-04-30 19:30 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +We support only OAuth for commits, not PR.
```suggestion
We support OAuth only for commits, not PRs.
```

2024-05-01 19:50 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made git side, we were able to fetch the YAML but metadata DB did not get updated. To res
This is still confusing to me so I am unresolving the comment.

2024-05-01 19:51 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made git side, we were able to fetch the YAML but metadata DB did not get updated. To res
@brian-f-harness you resolved this comment, does this line make sense to you? what does it mean?

2024-05-01 20:01 UTC, brian-f-harness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made git side, we were able to fetch the YAML but metadata DB did not get updated. To res
@SushrutHarness Here's my suggestion:
By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made on the Git side, Harness fetches the YAML, but the metadata DB is not updated. To resolve this, rename the service in the UI and then save the pipeline. This syncs the DB and Git YAML.

2024-05-01 21:09 UTC, SushrutHarness commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made on the git side, we are able to fetch the YAML but the metadata DB does not get upda
```suggestion
By default, Harness Git Experience syncs unidirectionally, from Harness to your Git repos. Since changes were made on the Git side, Harness fetches the YAML, but the metadata DB is not updated. To resolve this, rename the service in the UI and then save the pipeline. This syncs the DB and Git YAML.
```

2024-05-01 21:10 UTC, SushrutHarness approved these changes

2024-05-02 05:53 UTC, roshnisarangadharan commented on kb/cloud-cost-management/cloud-cost-management-faqs.md
> +To pinpoint account-level discounts in AWS CUR, utilize the line item type column within the report. This column segregates various charges, including discounts, refunds, and more, at the account lev
```suggestion
To pinpoint account-level discounts in AWS CUR, utilize the line item type column within the report. This column segregates various charges, including discounts, refunds, and more at the account level.
```

2024-05-02 05:54 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Can I add barriers in the pipeline?
```suggestion
#### Can I add barriers in a pipeline?
```

2024-05-02 05:54 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +No, Barriers are only supported in parallel stages and step groups to make them synchronized.
```suggestion
You cannot add barriers in pipelines. Barriers are only supported in parallel stages and step groups to make them synchronized.
```

2024-05-02 05:55 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +To confirm if the cloud_pricing_export data is being used in calculations, you can check the cost data in Harness CCM and compare it with the cost data in your GCP billing reports. If the data matche
This should be in CCM FAQ section.

2024-05-02 05:56 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### How do I reference multiple values of a dropdown in the pipeline?
```suggestion
#### How do I reference multiple values of a drop-down in the pipeline?
```

2024-05-02 05:56 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Why is my backend config not getting picked up in the terraform deployment even if it's defined in the terraform plan step?
```suggestion
#### Why is my backend config not getting picked up in Terraform deployments even if it's defined in the Terraform Plan step?
```

2024-05-02 05:57 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +To acknowledge the backend configs, make sure your terraform code does not have the backend defined as local in the below config set -
```suggestion
To acknowledge backend configs, make sure your Terraform code does not have the backend defined as local in the below config set -
```

2024-05-02 05:57 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Please change the value to the correct type of backend location.
```suggestion
Change the value to the correct type of backend location.
```

2024-05-02 05:57 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +No, Harness does not support code formatting. You will have to format the code manually and add it to Harness. Harness will preserve the format
```suggestion
No, Harness does not support code formatting. You will have to format the code manually and add it to Harness. Harness will preserve the format.
```

2024-05-02 05:57 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Why am I getting the error "Invalid transition to status" when running the Jira update step?
```suggestion
#### Why am I getting the error, "Invalid transition to status" when running the Jira Update step?
```

2024-05-02 05:58 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### How do I retrieve Template YAML Contents?
```suggestion
#### How do I retrieve Template YAML contents?
```

2024-05-02 05:58 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +We have an API to get template details - https://apidocs.harness.io/tag/Templates#operation/getTemplate
```suggestion
We have an API to get template details. For more details, go to [API documentation](https://apidocs.harness.io/tag/Templates#operation/getTemplate).
```

2024-05-02 05:59 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Why does the secret value beginning with "*" return an error when assigned to a value in K8s manifest?
```suggestion
#### Why does the secret value beginning with "*" return an error when assigned to a value in the K8s manifest?
```

2024-05-02 06:00 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +i.e you can create a project-level variable and add a shell script at the beginning of the pipeline to store the value of the trigger type using an API. So whenever the pipeline is run by webhook the
```suggestion
You can store the triggerType value in a project-level variable and check the condition on that variable. You can create a project-level variable and add a shell script at the beginning of the pipeline to store the value of the trigger type using an API. So whenever the pipeline is run by webhook the value is updated to type webhook and once the pipeline is completely run, you can add another API call to clear out the status.
```

2024-05-02 06:01 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +Currently, by design if "Deploy multiple services" is enabled, we display the count of services during the run, and if you hover over the services window, it will display the services that are select
```suggestion
Currently, by design, if "Deploy multiple services" is enabled, we display the count of services during the run. If you hover over the services window, it will display the services that are selected.
```

2024-05-02 06:02 UTC, roshnisarangadharan commented on kb/continuous-delivery/continuous-delivery-faqs.md
> +#### Why is a PR created with a bot connector and not a user account when a pipeline is saved and OAuth integrated with git exp?
```suggestion
#### Why is a PR created with a bot connector and not a user account when a pipeline is saved and OAuth integrated with Git Experience?
```

2024-05-02 06:04 UTC, roshnisarangadharan approved these changes
Approving with the assumption that you will consider my suggestion, https://github.com/harness/developer-hub/pull/6528/files#r1587098656.

2024-05-02 09:55 UTC, jenniferopal approved these changes
From Feature Flags, LGTM!

2024-05-10 10:22 UTC, closed without merging