[PL-50653] SMP 0.15.2 patch RN
harness/developer-hub pull request #6540
Opened 2024-05-01 21:16 UTC by brian-f-harness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: SMP 0.15.2 patch RN
* Jira/GitHub Issue numbers (if any): PL-50653
* Preview links/images (Internal contributors only): pending

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [x] Successful preview build.
- [x] Code owner review.
- [x] No merge conflicts.
- [x] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-05-01 21:23 UTC, nikunj-badjatya requested changes

2024-05-01 21:23 UTC, nikunj-badjatya commented on release-notes/self-managed-enterprise-edition.md
> +- Added support for Kubernetes true-up fees when using amortized costs with AWS. (CCM-15397)
Added support for Kubernetes cost true-up with AWS amortized costs. (CCM-15397)

2024-05-01 21:24 UTC, brian-f-harness commented on release-notes/self-managed-enterprise-edition.md
> +- Added support for Kubernetes true-up fees when using amortized costs with AWS. (CCM-15397)
```suggestion
- Added support for Kubernetes cost true-up with AWS amortized costs. (CCM-15397)
```

2024-05-01 21:27 UTC, nikunj-badjatya approved these changes

2024-05-01 21:38 UTC, aimurphy submitted a review, later dismissed

2024-05-02 05:07 UTC, swapnil-harness submitted a review, later dismissed

2024-05-02 12:42 UTC, merged