CHAOS-5239 GameDay V2
harness/developer-hub pull request #6545
Opened 2024-05-02 11:17 UTC by SmritiSatya

GameDay V2

2024-05-08 13:59 UTC, brian-f-harness approved these changes

2024-05-08 13:59 UTC, brian-f-harness commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +This section describes how to create and execute [GameDay](/docs/chaos-engineering/features/gameday/introduction-to-gameday.md) V2.
```suggestion
This topic describes how to create and execute [GameDay](/docs/chaos-engineering/features/gameday/introduction-to-gameday.md) V2.
```

2024-05-08 13:59 UTC, brian-f-harness commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +You can create prerequisites for your GameDay that would:
```suggestion
You can create prerequisites for your GameDay that:
```

2024-05-08 13:59 UTC, brian-f-harness commented on docs/chaos-engineering/features/gameday/run-gameday.md
> +This section describes how to create and execute a [GameDay](/docs/chaos-engineering/features/gameday/introduction-to-gameday.md).
```suggestion
This topic describes how to create and execute a [GameDay](/docs/chaos-engineering/features/gameday/introduction-to-gameday.md).
```

2024-05-08 13:59 UTC, brian-f-harness commented on docs/chaos-engineering/features/gameday/run-gameday.md
> +If you are new to HCE, head to [GameDay V2](/docs/chaos-engineering/features/gameday/gameday-v2.md) and follow the steps to create and run a GameDay
```suggestion
If you are new to HCE, head to [GameDay V2](/docs/chaos-engineering/features/gameday/gameday-v2.md) and follow the steps to create and run a GameDay.
```

2024-05-08 13:59 UTC, brian-f-harness commented on docs/chaos-engineering/features/gameday/run-gameday.md
> +11. Clicking GameDay leads you to the page that contains the experiments associated with the GameDay.
```suggestion
11. Clicking **GameDay** opens the page that contains the experiments associated with the GameDay.
```

2024-05-22 06:48 UTC, Saranya-jena requested changes

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +2. Add stakeholder names, their roles, and whether they are allowed to approve a GameDay run. Only a stakeholder can approve or reject a GameDay run. Select **Next: Select Prerequisites**.
allowed -> required (as anyone can approve/reject the run on the behalf of selected stakeholder).
Only a stakeholder can approve or reject a GameDay run -> As mentioned above anyone can approve/reject on others' behalf.

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +4. Enter a name and a description (optional). Select **Save**.
Instead of name, we can rephrase it to something like - title for the prerequisite.

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +8. Once the stakeholder approves the GameDay run, you can proceed.
stakeholder approves -> stakeholders approve (as there can be multiple stakeholders)

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +* Select the experiment to view the details of the selected experiment.
This is not available currently, but should be available in the upcoming releases

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +10. HCE checks if the prerequisites are fulfilled. If one of them is not fulfilled, you will not be able to execute the experiments.
HCE doesn't check, users have to mark the prerequisites as done to move forward

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +- Select **Add/View Notes** to note your findings about the GameDay.
This notes is on experiment level, users can add notes related to those particular experiments. gameday run level notes can be added in the post mortem step

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +14. Select **Download Run Report** to download the report.
Not available yet

2024-05-22 06:48 UTC, Saranya-jena commented on docs/chaos-engineering/features/gameday/gameday-v2.md
> +- Select the experiment in the GameDay to view manifest details. Select **View Execution** to see more.
not available yet

2024-05-22 10:46 UTC, merged