new changes
harness/developer-hub pull request #6568
Opened 2024-05-03 13:38 UTC by joeyouss

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-05-03 13:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6568) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6568) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6568) it.</sub>

2024-05-06 06:59 UTC, abhijeet-harness approved these changes

2024-05-06 07:07 UTC, iamanmolm requested changes
1. Kindly make "Handling Kubernetes secrets" part AWS, GCP similar to Azure:
<img width="1287" alt="Screenshot 2024-05-06 at 12 34 30 PM" src="https://github.com/harness/developer-hub/assets/105212590/cb8afeb7-c3cf-4e41-a073-6a14ec6d2c2e">
<img width="1317" alt="Screenshot 2024-05-06 at 12 34 42 PM" src="https://github.com/harness/developer-hub/assets/105212590/0e87bfe2-5153-4863-903c-0b260959df08">.

2. Also increase the architecture diagram size in both AWS, GCP as we did in Azure.

2024-05-06 07:08 UTC, sdsingh07 commented on docs/cloud-cost-management/get-started/ccm-smp/1-smp-ccm-roadmap.md
> +|Perspectives | ✅  | ❌  | ❌  | ✅ |
We are now supporting GCP and Azure as well.

2024-05-06 07:08 UTC, sdsingh07 commented on docs/cloud-cost-management/shared/ccm-supported-platforms.md
> +|Perspectives | ✅  | ❌  | ❌  | ✅ |
We are now supporting GCP and Azure as well.

2024-05-06 07:26 UTC, abhijeet-harness commented on docs/cloud-cost-management/shared/ccm-supported-platforms.md
> +|Perspectives | ✅  | ❌  | ❌  | ✅ |
This section is for supported feats. in AirGapped mode.

2024-05-06 07:26 UTC, abhijeet-harness commented on docs/cloud-cost-management/get-started/ccm-smp/1-smp-ccm-roadmap.md
> +|Perspectives | ✅  | ❌  | ❌  | ✅ |
This section is for supported feats. in AirGapped mode.

2024-05-06 09:59 UTC, merged