GitLab triggers (new topic) STO-7459
harness/developer-hub pull request #6668
Opened 2024-05-13 01:19 UTC by douglas-j-bothwell

### Preview links

- [GitLab triggers to block merge requests](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers) - 
   - Intro -- switched steps (create trigger 1, failure critiera 2)
   - [Before you begin](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers/#before-you-begin) Updated GitLab connector link
   - [Create the Harness trigger](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers/#create-the-harness-trigger) Fixed links to subsections, removed bold in links
   - [Set up the failure criteria](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers/#set-up-the-failure-criteria) "filter" => "set of failure criteria"

- [GitHub triggers to block pull requests](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/github-triggers)
   - Intro -- switched steps (create trigger 1, failure critiera 2)
   -  [Before you begin](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/github-triggers/#before-you-begin)Updated GitLab connector link
   - [Create the Harness trigger](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/github-triggers/#create-the-harness-trigger) Fixed links to subsections, removed bold in links
   - [Set up the failure criteria](https://6658ef7337abf67927ca1d3b--harness-developer.netlify.app/docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/github-triggers/#set-up-the-failure-criteria) "filter" => "set of failure criteria"

### Merge requirements

PRs must meet these requirements to be merged:

- [x] Successful preview build.
- [x] PM review.
- [x] No merge conflicts.
- [x ] Editorial review.

2024-05-17 22:35 UTC, priteshchandaliya requested changes

2024-05-17 22:35 UTC, priteshchandaliya commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +1. [Set up the failure criteria](#set-up-the-failure-criteria) for your STO pipeline.
The order should be 2, 1 and 3

2024-05-17 22:35 UTC, priteshchandaliya commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +- A [**Harness connector**](/docs/category/code-repo-connectors/) to your GitLab account.
Point the link to GitLab Connector rather than generic connector

2024-05-17 22:35 UTC, priteshchandaliya commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +- The [Codebase](/docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase/) in your pipeline should point to the Git repo that you want to scan.
Point the link to GitLab code base Connector rather than generic connector

2024-05-17 22:35 UTC, priteshchandaliya commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +
```suggestion
You can configure your Harness pipeline to fail if the scan finds vulnerabilities that match a specified criteria. You can use one of two methods:
```

2024-05-17 22:35 UTC, priteshchandaliya commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +- [Trigger on a review comment](#trigger-on-a-pr-review-comment)
The link should go to correct sub section

2024-05-17 22:35 UTC, priteshchandaliya commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +#### [Configuration](/docs/platform/triggers/triggering-pipelines#configure-the-trigger)
All the sub topic should not be bold font

2024-05-30 20:32 UTC, brian-f-harness submitted a review, later dismissed
Optional suggestion to remove (top right), otherwise LGTM

2024-05-30 20:32 UTC, brian-f-harness commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +1. Go to your STO pipeline, select **Triggers** (top right), and add a new trigger.
```suggestion
1. Go to your STO pipeline, select **Triggers**, and add a new trigger.
```

2024-05-30 20:32 UTC, brian-f-harness commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +1. Go to your STO pipeline, select **Triggers** (top right), and add a new trigger.
[](url)
```suggestion
1. Go to your STO pipeline, select **Triggers**, and add a new trigger.
```

2024-06-11 14:25 UTC, douglas-j-bothwell commented on docs/security-testing-orchestration/use-sto/stop-builds-based-on-scan-results/gitlab-triggers.md
> +- The [Codebase](/docs/continuous-integration/use-ci/codebase-configuration/create-and-configure-a-codebase/) in your pipeline should point to the Git repo that you want to scan.
@priteshchandaliya There is only one type of Codebase object. This is different from code repo connectors, which are provider-specific: GitHub, GitLab, BitBucket, etc.

2024-06-18 20:59 UTC, priteshchandaliya approved these changes

2024-06-19 13:03 UTC, merged