[PL-46871] Account Admin documentation for user
harness/developer-hub pull request #6689
Opened 2024-05-14 08:42 UTC by saifeemustafaqharness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-05-14 11:56 UTC, saifeemustafaqharness commented
@brian-f-harness Do you think this would require screenshots as well in the steps?

2024-05-14 14:08 UTC, brian-f-harness commented
> @brian-f-harness Do you think this would require screenshots as well in the steps?

@saifeemustafaqharness I don't personally use a lot of screenshots. Our developer audience is comfortable using a UI. Here's guidance from our style guide.
https://harness.atlassian.net/wiki/spaces/DOCS/pages/21544468526/Harness+documentation+style+guide#Screenshots

I do have some other suggestions for this PR to update the steps to align with our style guide. I'm still working through the review.

2024-05-14 19:09 UTC, Jimit09Gandhi commented on docs/platform/role-based-access-control/add-manage-roles.md
> +To add an existing user to a custom Resource Group and do Role bindings:
Here its about providing role binding to Principal and selecting role and Resource Group. Its not about adding user to Resource Group.

2024-05-14 19:10 UTC, Jimit09Gandhi commented on docs/platform/role-based-access-control/add-manage-roles.md
> +1. Go to **Account Settings**, select **Access Control**, and then choose **Resource Group**.
Do we need this 2 sections. Seems repetitive.

2024-05-14 19:29 UTC, brian-f-harness requested changes
@saifeemustafaqharness Recommend following existing patterns for processes that can be completed at multiple scopes. Made some comments and will re-review after changes are implemented.

I recommend that you walk through the steps in the UI and be sure to refer to all UI elements by their exact name.

2024-05-14 19:29 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +
We can do this at the account/org/project scope. Recommend following existing patterns for processes we can do at any scope.

2024-05-15 07:04 UTC, saifeemustafaqharness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +## Adding Account Admin permissions to users in a Custom Resource Group
@brian-f-harness Can we write in this format:
Adding all permissions access to specific resources selected via Custom Resource Group

??

2024-05-15 07:06 UTC, saifeemustafaqharness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +To add an existing user to a custom Resource Group and do Role bindings:
Will change the verbiage to mention this

2024-05-15 07:13 UTC, saifeemustafaqharness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +1. Go to **Account Settings**, select **Access Control**, and then choose **Resource Group**.
Two sections are required because one scenario is for a new user and another one is for an existing user; merging both will look like a very long process.

2024-05-15 16:34 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +## Adding Account Admin permissions to users in a Custom Resource Group
We want to avoid using gerunds in headings.
https://harness.atlassian.net/wiki/spaces/DOCS/pages/21544468526/Harness+documentation+style+guide#Headings%2C-titles

2024-05-21 13:40 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +8. Click **All Resources Including** under **Resource Groups** and select your respective **Resource Group** from the drop down.
```suggestion
9. Under **Resource Groups**, select **All Resources Including**,  and then select your **Resource Group**.
```

2024-05-21 13:42 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +10. The user can now login through their account and access only those resources that are allowed in the resource groups with their **Account Admin** permissions.
```suggestion
   The user can now sign in to their account and access only those resources allowed in the resource groups with their **Account Admin** permissions.
```

2024-05-21 13:42 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +3. Create a new **Resource Group**, select the desired resource types, and click **Save**.
```suggestion
3. Create a new **Resource Group**, select the desired resource types, and then select **Save**.
```

2024-05-21 13:42 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +2. Select **Access Control**, and then choose **Resource Group**.
```suggestion
2. Select **Access Control**, and then select **Resource Group**.
```

2024-05-21 13:43 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +4. Return to **Account Settings**, select **Access Control**, then choose **Users**.
```suggestion
4. Return to **Account Settings**, select **Access Control**, then select **Users**.
```

2024-05-21 13:44 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +7. Click **Add** under **Role Bindings**. Click **Select a role** under **Roles** and choose **Account Admin** from the drop down.
```suggestion
7. Under **Role Bindings**, select **Add** . 
8. Under **Roles**, click **Select a role**, and then select **Account Admin**.
```

2024-05-21 14:19 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +10. The user can now sign in to their account and access only those resources allowed in the resource groups with their **Account Admin** permissions.
```suggestion
   The user can now sign in to their account and access only those resources allowed in the resource groups with their **Account Admin** permissions.
```

2024-05-21 14:19 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +10. The user can now sign in to their account and access only those resources allowed in the resource groups with their **Account Admin** permissions.
Suggest removing numbered step since this is a result of the previous action and not a new action. (Similar to line 175.)

2024-05-21 14:33 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +5. Click **New User**, enter the user's email, and click **Add** under **Role Bindings**.
```suggestion
5. Click **New User**, enter the user's email, then, under **Role Bindings**, select **Add**.
```

2024-05-21 14:33 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +6. Click **Select a role** under **Roles** and choose **Account Admin** from the drop down.
```suggestion
6. Under **Roles**, click **Select a role**, then choose **Account Admin** from the dropdown.
```

2024-05-21 14:33 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +7. Click **All Resources Including** under **Resource Groups** and select your respective **Resource Group**.
```suggestion
7.  Under **Resource Groups**, click **All Resources Including** and select your **Resource Group**.
```

2024-05-21 14:45 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +You can do role bindings to a user and attach the user to a specific resource group at the Account, Project, or Organization scope. To add new users to a custom Resource Group with role bindings, do
```suggestion
You can do role bindings to a user and attach the user to a specific resource group at the Account, Project, or Organization scope.

To add new users to a custom Resource Group with role bindings, do the following:
```

2024-05-21 15:16 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +8. Click **Apply** to send an invitation to the user's email. After the user accepts the invite, the role binding process is complete.
```suggestion
8. Click **Apply** to send an invitation to the user's email. After the user accepts the invite, the role-binding process is complete.
```

2024-05-21 20:16 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +1. In Harness, go to **Account Settings**, **Organization Settings**, or **Project Settings**, depending on the [scope](https://developer.harness.io/docs/platform/role-based-access-control/rbac-in-ha
```suggestion
1. In Harness, go to **Account Settings**, **Organization Settings**, or **Project Settings**, depending on the [scope](https://developer.harness.io/docs/platform/role-based-access-control/rbac-in-harness/#permissions-hierarchy-scopes) at which you want to add new users to a custom Resource Group and do role bindings.
```

2024-05-21 20:16 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +1. In Harness, go to **Account Settings**, **Organization Settings**, or **Project Settings**, depending on the [scope](https://developer.harness.io/docs/platform/role-based-access-control/rbac-in-ha
```suggestion
1. In Harness, go to **Account Settings**, **Organization Settings**, or **Project Settings**, depending on the [scope](https://developer.harness.io/docs/platform/role-based-access-control/rbac-in-harness/#permissions-hierarchy-scopes) at which you want to add new users to a custom Resource Group and do role bindings.
```

2024-05-21 20:17 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +2. Select **Access Control**, and then choose **Resource Group**.
```suggestion
2. Under **Access Control**, select **Resource Groups**.
```

2024-05-21 20:18 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +4. Return to **Account Settings**, select **Access Control**, then choose **Users**.
```suggestion
4. Return to **Account Settings**. Under **Access Control**, select **Users**.
```

2024-05-21 20:19 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +2. Select **Access Control**, and then select **Resource Group**.
```suggestion
2. Under **Access Control**, select **Resource Groups**.
```

2024-05-21 20:19 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +4. Return to **Account Settings**, select **Access Control**, then select **Users**.
```suggestion
4. Return to **Account Settings**. Under **Access Control**, select **Users**.
```

2024-05-21 20:23 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +9. Under **Resource Groups**, select **All Resources Including**,  and then select your **Resource Group**.
```suggestion
9. Under **Resource Groups**, select **All Resources Including**, and then select your **Resource Group**.
```

2024-05-21 20:23 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +7. Under **Role Bindings**, select **Add** .
```suggestion
7. Under **Role Bindings**, select **Add**. 
```

2024-05-21 20:24 UTC, brian-f-harness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +
Recommend verifying the steps and UI element names in the QA or prod UI to ensure accuracy.

2024-05-27 07:31 UTC, Jimit09Gandhi requested changes

2024-05-27 07:31 UTC, Jimit09Gandhi commented on docs/platform/role-based-access-control/add-manage-roles.md
> +5. Search for the user to whom you want to assign the **Account Admin** role, and then select the user.
Instead of Account Admin we can mention Account Admin/Any custom role with all permissions selected as for resource selected in resource group. You can re-word it.

2024-05-27 07:31 UTC, Jimit09Gandhi commented on docs/platform/role-based-access-control/add-manage-roles.md
> +6. Under **Roles**, click **Select a role**, then choose **Account Admin** from the dropdown.
Instead of Account Admin we can mention Account Admin/Any custom role with all permissions selected as for resource selected in resource group. You can re-word it.

2024-05-27 15:14 UTC, saifeemustafaqharness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +5. Search for the user to whom you want to assign the **Account Admin** role, and then select the user.
Done

2024-05-27 15:14 UTC, saifeemustafaqharness commented on docs/platform/role-based-access-control/add-manage-roles.md
> +6. Under **Roles**, click **Select a role**, then choose **Account Admin** from the dropdown.
Done

2024-05-27 15:23 UTC, Jimit09Gandhi approved these changes

2024-05-27 15:32 UTC, saifeemustafaqharness commented
@brian-f-harness Are we good to merge this? Jimit has approved.

2024-05-27 16:29 UTC, brian-f-harness approved these changes

2024-05-27 16:33 UTC, merged