docs: [IAC-1862]: IaCM Onboarding guide
harness/developer-hub pull request #6727
Opened 2024-05-16 13:44 UTC by richardblack-Harness

## Description

* Add IaCM onboarding doc 
   * Interactive walkthrough to follow alongside step-by-step sections in a later PR
* [JIRA](https://harness.atlassian.net/browse/IAC-1862)

PRs must meet these requirements to be merged:

- [x] Successful preview build.
- [x] Code owner review.
- [x] No merge conflicts.
- [x] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-05-16 14:28 UTC, brian-f-harness approved these changes
Some minor suggestions and style recommendations to adhere to the style guide, otherwise LGTM

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +Welcome to the Harness Infrastructure as Code Management (IaCM) onboarding guide. This document introduces you to the powerful capabilities of IaCM using Harness and guides you through key functional
```suggestion
Welcome to the Harness Infrastructure as Code Management (IaCM) onboarding guide. This topic introduces you to the powerful capabilities of IaCM using Harness and guides you through key functionalities that streamline and secure your infrastructure management tasks.
```

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +Infrastructure as Code Management (IaCM) refers to managing and provisioning computing infrastructure through machine-readable definition files rather than physical hardware configuration or interact
```suggestion
Infrastructure as Code Management (IaCM) refers to managing and provisioning computing infrastructure through machine-readable definition files rather than physical hardware configuration or interactive configuration tools. By using IaCM, teams can ensure consistency, accountability, and repeatability within their environments. Harness enhances IaCM with features like real-time cost estimation, automated policy enforcement, and drift detection, ensuring that your infrastructure is provisioned efficiently and complies with organizational standards and budget constraints.
```

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +- A [configured Connect to your Git repository](https://developer.harness.io/docs/platform/connectors/code-repositories/connect-to-code-repo)
```suggestion
- A [configured Connector to your Git repository](https://developer.harness.io/docs/platform/connectors/code-repositories/connect-to-code-repo)
```

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +Tags: To facilitate easy identification and management within AWS resources, a tag name with the value' my_first_ec2_instance' is applied.
```suggestion
Tags: To facilitate easy identification and management within AWS resources, a tag name with the value `my_first_ec2_instance` is applied.
```

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +Users can define a Terraform configuration with multiple workspaces to enforce the same desired configuration. Each Workspace creates a different state with its own independent lifecycle.
```suggestion
You can define a Terraform configuration with multiple workspaces to enforce the same desired configuration. Each Workspace creates a different state with an independent lifecycle.
```

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +- **Add workspace details**
```suggestion
5. Select **Add workspace details**.
```

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +- **Connector** - Select the Harness connector to use during provisioning. You can select
might be missing content after "You can select"

2024-05-16 14:28 UTC, brian-f-harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +- **Repository** - Specify the Git configuration for the Terraform configuration files. You should specify the Harness Git connector, repository branch, and file path to the configuration files in th
```suggestion
- **Repository**: Specify the Git configuration for the Terraform configuration files. You should specify the Harness Git connector, repository branch, and file path to the configuration files in the repository.
```

2024-05-16 15:03 UTC, brian-f-harness submitted a review, later dismissed

2024-05-16 16:02 UTC, RickCraig requested changes
Excellent work! I have a few comments and a couple of fixes. Some of my comments are suggestions, so you don't have to implement them, if you disagree with me. Also educate me in any place I'm clearly uninformed!

2024-05-16 16:14 UTC, richardblack-Harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +- Instance Type: Configures the instance to use a t2.micro, offering cost-effective performance suitable for low to moderate demand. Go to the [AWS t2 instances list](https://aws.amazon.com/ec2/insta
Done

2024-05-16 16:14 UTC, richardblack-Harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +```
It'll do no harm for context regardless.

2024-05-16 16:18 UTC, richardblack-Harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +Go to [Terraform Documentation](https://developer.hashicorp.com/terraform/intro) for more information on Terraform.
Added a quick reference.

2024-05-16 16:31 UTC, richardblack-Harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +Infrastructure as Code Management (IaCM) refers to managing and provisioning computing infrastructure through machine-readable definition files rather than physical hardware configuration or interact
Updated

2024-05-16 16:39 UTC, richardblack-Harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +2. In the module pane, select **Infrastructures**.
It doesn't Infrastructure singular is correct. good spot

2024-05-16 16:39 UTC, richardblack-Harness commented on docs/infra-as-code-management/get-started/onboarding-guide.md
> +4. Select **Create new Workspace**.
updated

2024-05-20 12:36 UTC, RickCraig approved these changes

2024-05-20 12:39 UTC, merged