784xx Release Notes - CI
harness/developer-hub pull request #677
Opened 2023-02-10 22:39 UTC by aimurphy

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-13 16:51 UTC, rustd commented on release-notes/continuous-integration.md
> +* Harness CI now supports remote debugging of remote builds in Harness Cloud, Kubernetes, and VMs in AWS, Azure, and other cloud platforms. If a build fails at a Run step, you can rerun the build in
@aimurphy you remove Remote Debugging from this list.

2023-02-13 16:53 UTC, aimurphy commented on release-notes/continuous-integration.md
> +* Harness CI now supports remote debugging of remote builds in Harness Cloud, Kubernetes, and VMs in AWS, Azure, and other cloud platforms. If a build fails at a Run step, you can rerun the build in
Remove the whole bullet?

2023-02-13 17:50 UTC, KimberlyFields requested changes

2023-02-13 17:50 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +  * Replace Configure Service Dependency steps with Background steps to take advantage of the more robust control and configuration option. (CI-5580)
@aimurphy I know this is your first release notes PR at Harness, so please review [ ](https://harness.atlassian.net/wiki/spaces/DOCS/pages/1689845830/Release+notes+process+and+guidelines#What%E2%80%99s-new) and update these entries for new features to make them more descriptive and include the benefits. You may need to work with Pranav on some of these. Make sure there's a link to associated docs. 

Also, every entry in a module's "What's new" section must also be added to the overall What's new topic [ ](https://developer.harness.io/release-notes/whats-new). Michael made some change to the overall What's new in [ ](https://github.com/harness/developer-hub/pull/678/files) so make sure to coordinate on updating that file to avoid merge conflicts.

2023-02-13 17:50 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* With the NEW_LEFT_NAV_BAR feature flag enabled, you can view builds details at the project level without drilling down into individual modules. We fixed an issue where the **Commits** tab produced
```suggestion
* With the NEW_LEFT_NAV_BAR feature flag enabled, you can view build details at the project level without drilling down into individual modules. We fixed an issue where the **Commits** tab produced a `404` error when viewing build details from the project level. (CI-6817)
```

2023-02-13 17:50 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* With the NEW_LEFT_NAV_BAR feature flag enabled, you can view builds details at the project level without drilling down into individual modules. We fixed an issue where the **Commits** tab produced
Are these two different issues in the same issue? Not sure why the first sentence is part of the fixed issue description. Also, avoid "we" per MSTP [ ](https://learn.microsoft.com/en-us/style-guide/grammar/person#avoid-plural-first-person-we-us)

2023-02-13 17:50 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* We fixed an issue where expressions used in a pipeline's codebase properties resolved to `null` rather than their expected values. (CI-6679, ZD-38122, ZD-38241, ZD-38698, ZD-39088)
Same comment as above about "we".

2023-02-13 17:50 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +No early access features added in this release.
The original is correct.

2023-02-13 17:50 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +No early access features added in this release.
The original is correct. Undo all changes to this sentence in this file.

2023-02-13 17:54 UTC, aimurphy commented on release-notes/continuous-integration.md
> +No early access features added in this release.
fixed

2023-02-13 17:55 UTC, aimurphy commented on release-notes/continuous-integration.md
> +* With the NEW_LEFT_NAV_BAR feature flag enabled, you can view builds details at the project level without drilling down into individual modules. We fixed an issue where the **Commits** tab produced
The issue was only happening with that FF enabled, because you had to go through the "Projects" tab that is part of that FF.

2023-02-13 17:59 UTC, aimurphy commented on release-notes/continuous-integration.md
> +No early access features added in this release.
fixed it back.

2023-02-13 18:10 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +  * Replace Configure Service Dependency steps with Background steps to take advantage of the more robust control and configuration option. (CI-5580)
https://harness.atlassian.net/wiki/spaces/DOCS/pages/1689845830/Release+notes+process+and+guidelines

I just realized the above link was not included in my original comment.

2023-02-13 19:35 UTC, aimurphy commented on release-notes/continuous-integration.md
> +  * Replace Configure Service Dependency steps with Background steps to take advantage of the more robust control and configuration option. (CI-5580)
Discussed w/ PM & got approval

2023-02-13 21:53 UTC, KimberlyFields reviewed
A few more changes are needed.

2023-02-13 21:53 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* With the feature flag `NEW_LEFT_NAV_BAR` enabled, you can view build details at the project level without drilling down into individual modules. When viewing build details from project level, the *
```suggestion
* With the feature flag `NEW_LEFT_NAV_BAR` enabled, you can view build details at the project level without drilling down into individual modules. When viewing build details from the project level, the **Commits** tab produced a `404` error. This is fixed. (CI-6817)
```

2023-02-13 21:53 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* The CI Getting Started workflow leads you through creating an SCM connector and a pipeline. We fixed an issue where exiting the Getting Started workflow before creating a pipeline resulted in incom
Avoid "We"

2023-02-13 21:53 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* Added **Python** as a built-in **Shell** option for [Run steps](../docs/continuous-integration/ci-technical-reference/run-step-settings.md). (CI-6692)
```suggestion
* **Python** is now available as a built-in **Shell** option for [Run steps](../docs/continuous-integration/ci-technical-reference/run-step-settings.md). (CI-6692)
```

2023-02-13 21:53 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +  * GCP connectors are authenticated through either a GCP service account key or by inheriting credentials from the Harness delegate running in GCP. This change improves how you can use GCP connector
```suggestion
  * GCP connectors are now authenticated through either a GCP service account key or by inheriting credentials from the Harness delegate running in GCP. This change improves how you can use GCP connectors with inherited credentials in your pipelines.
```

2023-02-13 21:53 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* Use [Background steps](../docs/continuous-integration/ci-technical-reference/background-step-settings.md) to configure service dependencies.
```suggestion
* [Background steps](../docs/continuous-integration/ci-technical-reference/background-step-settings.md) can now be used to configure service dependencies.
```

2023-02-13 21:53 UTC, KimberlyFields commented on release-notes/continuous-integration.md
> +* Improved handling of Azure repo URLs in [Git webhook pipeline triggers](../docs/platform/11_Triggers/triggering-pipelines.md). (CI-5720)
Can you provide some details on what was improved? And is this a fix or a new item? Seems like it might be a fix.

2023-02-13 22:37 UTC, aimurphy commented on release-notes/continuous-integration.md
> +  * GCP connectors are authenticated through either a GCP service account key or by inheriting credentials from the Harness delegate running in GCP. This change improves how you can use GCP connector
They already were authenticated by both methods, but Run steps couldn't reference images in GCR if the GCP connector had inherited credentials. It would fail with an error that "Inherit FromDelegate" was not supported.

2023-02-13 22:38 UTC, aimurphy commented on release-notes/continuous-integration.md
> +  * Previously, if you wanted a Run step to call an image in GRC, the GCP connector attached to your Run step had to use service account key authentication. Now, the GCP connector can use either auth
They are sub-bullets under line 22

2023-02-13 22:40 UTC, aimurphy commented on release-notes/continuous-integration.md
> +* Use [Background steps](../docs/continuous-integration/ci-technical-reference/background-step-settings.md) to configure service dependencies.
Technically this was introduced in November. This is kind of a re-announcement... The actual change this time is that they've removed Configure Service Dependency from the visual editor for new pipelines.

2023-02-13 22:44 UTC, aimurphy commented on release-notes/continuous-integration.md
> +* Improved handling of Azure repo URLs in [Git webhook pipeline triggers](../docs/platform/11_Triggers/triggering-pipelines.md). (CI-5720)
It's an enhancement. I have asked multiple times and I haven't gotten any specifics. I think this is because the changes are about how the API handles these URLs on the backend than something that would usually be exposed to the user.

There is an old and new URL format for Azure repos. The ticket was originally created due to an auth issue with webhook triggers that received old format URLs. Instead of fix that one issue, my understanding is that multiple changes were made to improve handling of these old format URLs in webhook triggers.

2023-02-13 22:50 UTC, aimurphy commented on release-notes/continuous-integration.md
> +  * Previously, if you wanted a Run step to call an image in GRC, the GCP connector attached to your Run step had to use service account key authentication. Now, the GCP connector can use either auth
I moved the ids to be on the first level bullet.

2023-02-13 23:17 UTC, KimberlyFields approved these changes

2023-02-15 08:31 UTC, deepakbolangady approved these changes
Approving after updating the date and version number. @aimurphy, if you still need to incorporate feedback, feel free to do so after this is published.

2023-02-15 08:51 UTC, deepakbolangady submitted a review, later dismissed
Approving after updating the date field in the metadata in both files.

2023-02-15 10:26 UTC, deepakbolangady submitted a review, later dismissed
Resolved a merge conflict with PL release notes. Looks like I need another approval!

2023-02-15 12:49 UTC, deepakbolangady approved these changes

2023-02-15 13:08 UTC, merged