Update iacmData.ts
harness/developer-hub pull request #6770
Opened 2024-05-20 18:18 UTC by urischeiner

Update IaCM Roadmap

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-05-20 18:52 UTC, RickCraig requested changes

2024-05-20 18:52 UTC, RickCraig commented on src/components/Roadmap/data/iacmData.ts
> +        description: "Using Infracost, IaCM provides cost estimation on resource changes, allowing users to understand how cloud bill will be changed, based on resource changes",
```suggestion
        description: "By utilizing Infracost, IaCM offers cost predictions for resource modifications, enabling users to foresee adjustments to their cloud expenses ahead of time.",
```

Just a suggestion, but it needs to change as the original doesn't make sense.

2024-05-20 18:52 UTC, RickCraig commented on src/components/Roadmap/data/iacmData.ts
> +        description: "IaCM supports hosted backend, allowing users to store state securely",
```suggestion
        description: "IaCM supports hosted remote backends, enabling users to securely store state.",
```

2024-05-20 18:52 UTC, RickCraig commented on src/components/Roadmap/data/iacmData.ts
> +        description: "IaCM support PR Automation that populates plan and cost data to the PR process, helping users to reduce testing time on Terraform changes",
```suggestion
        description: "IaCM supports PR Automation that populates plan and cost data as a pull request comment, helping users to reduce testing time on Terraform changes",
```

Just a suggestion, needs the s after support though

2024-05-21 13:21 UTC, richardblack-Harness requested changes
Couple of very minor suggestions. Otherwise LGTM!

2024-05-21 13:21 UTC, richardblack-Harness commented on src/components/Roadmap/data/iacmData.ts
> +        description: "Plugins for tfsec, tflint, and checkov that can be added to the IaCM pipeline to find security vulnerabilities and misconfiguration",
```suggestion
        description: "Add Plugins for tfsec, tflint, and checkov to your IaCM pipeline to find security vulnerabilities and misconfiguration.",
```

2024-05-21 13:21 UTC, richardblack-Harness commented on src/components/Roadmap/data/iacmData.ts
> +        description: "Integration with CCM allows IaCM users to have full visibility of costs associated with the resources being managed by IaCM",
```suggestion
        description: "Integrate with CCM to grant IaCM users full visibility of costs associated with resources managed by IaCM.",
```

2024-05-21 13:21 UTC, richardblack-Harness commented on src/components/Roadmap/data/iacmData.ts
> +        description: "IaCM supports highly customized pipelines that allow users to create advanced workflow, add 3rd party plugins, run steps in parallel, and more.",
```suggestion
        description: "IaCM supports highly customized pipelines that allow users to create advanced workflows, add 3rd party plugins, run steps in parallel, and more.",
```

2024-05-21 13:21 UTC, richardblack-Harness commented on src/components/Roadmap/data/iacmData.ts
> +        description: "IaCM supports hosted remote backends, enabling users to securely store state.",
```suggestion
        description: "IaCM supports hosted remote backends, enabling users to store their infrastructure state securely.",
```

2024-08-09 13:12 UTC, ravilach commented
@richardblack-Harness do you still need this one?

2024-08-09 13:17 UTC, closed without merging

2024-08-09 13:17 UTC, richardblack-Harness commented
> @richardblack-Harness do you still need this one?

@ravilach Our roadmap items are in place for Q3 and beyond, I will close this.