add new aws recommendations
harness/developer-hub pull request #6820
Opened 2024-05-23 14:47 UTC by joeyouss

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-05-23 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6820) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6820) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6820) it.</sub>

2024-05-23 18:18 UTC, nikunj-badjatya submitted a review, later dismissed

2024-06-04 06:51 UTC, iamanmolm requested changes

2024-06-04 06:51 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Savings Computed:**
Missing Savings Computed.

2024-06-04 06:51 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Savings Computed**:
Missing Savings Computed.

2024-06-05 14:08 UTC, iamanmolm approved these changes

2024-06-05 14:11 UTC, iamanmolm requested changes

2024-06-05 14:11 UTC, iamanmolm commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Without Lifecycle Policy**
Can we keep it side by side maybe in a table comparison?

2024-06-06 10:02 UTC, joeyouss commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Without Lifecycle Policy**
done

2024-06-06 12:30 UTC, brian-f-harness submitted a review, later dismissed
Added a few minor suggestions, otherwise LGTM

2024-06-06 12:30 UTC, brian-f-harness commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Description:** Delete underutilised cache cluster with CPU utilisation less than 5% in last 7 days.
```suggestion
**Description:** Delete underutilized cache cluster with CPU utilization less than 5% in the last 7 days.
```

2024-06-06 12:30 UTC, brian-f-harness commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Savings Computed:** The policy identifies a list of resources on which potential savings are calculated by summing up cost of each resource for last 30 days.
```suggestion
**Savings Computed:** The policy identifies a list of resources on which potential savings are calculated by summing up the cost of each resource for the last 30 days.
```

2024-06-06 12:30 UTC, brian-f-harness commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +---
```suggestion
```

2024-06-06 12:30 UTC, brian-f-harness commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +---
```suggestion
```

2024-06-06 12:52 UTC, brian-f-harness commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Description:** Configure lifecycle for s3 buckets wherever it is absent which would help to reduce storage spend
```suggestion
**Description:** Configure lifecycle for S3 buckets wherever it is absent which would help to reduce storage spend
```

2024-06-06 12:52 UTC, brian-f-harness commented on docs/cloud-cost-management/5-use-ccm-cost-governance/asset-governance/AWS/AWS-recommendations.md
> +**Description:** Configure intelligent tiering for s3 buckets wherever it is disabled which would help to reduce storage spend.
```suggestion
**Description:** Configure intelligent tiering for S3 buckets wherever it is disabled which would help to reduce storage spend.
```

2024-06-18 14:52 UTC, merged