added new info
harness/developer-hub pull request #6928
Opened 2024-06-04 14:33 UTC by joeyouss

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-06-04 14:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=6928) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=6928) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=6928) it.</sub>

2024-06-04 15:48 UTC, tuffacton commented
Usually we get a nice netlify link for the draft, can we see that?

2024-06-05 04:20 UTC, iamanmolm requested changes

2024-06-05 04:20 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
> +### Troubleshooting
Lets move it at the bottom of the doc.

2024-06-05 04:20 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/ccm-smp/aws-smp.md
> +If in case the keys expire, the secrets will have to be set again. We recommend to `kubectl delete`` the following pods:
Once the secret is updated you don't need to delete the pod right away. First you would have to update the secrets in respective secret.yaml and then delete the pod.

2024-06-05 04:20 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/ccm-smp/azure-smp.md
> +### Troubleshooting
Lets move it at the bottom of the doc.

2024-06-05 04:20 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/ccm-smp/azure-smp.md
> +If in case the K8s secrets expire, the secrets will have to be set again. We recommend to `kubectl delete`` the following pods:
Once the secret is updated you don't need to delete the pod right away. First you would have to update the secrets in respective secret.yaml and then delete the pod.

2024-06-05 04:20 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/ccm-smp/gcp-smp.md
> +### Troubleshooting
Lets move it at the bottom of the doc.

2024-06-05 04:20 UTC, iamanmolm commented on docs/cloud-cost-management/get-started/ccm-smp/gcp-smp.md
> +If in case the K8s secrets expire, the secrets will have to be set again. We recommend to `kubectl delete` the following pods:
Once the secret is updated you don't need to delete the pod right away. First you would have to update the secrets in respective secret.yaml and then delete the pod.

2024-06-17 17:00 UTC, nikunj-badjatya approved these changes

2024-06-18 05:18 UTC, merged