Topic for Harness UI
harness/developer-hub pull request #701
Opened 2023-02-14 10:43 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-14 11:15 UTC, abhinavrastogi-harness approved these changes
LGTM apart from the one small spelling issue!

2023-02-14 11:15 UTC, abhinavrastogi-harness commented on docs/getting-started/harness-ui-overview.md
> +description: Exploare the Harness UI and navigate to the desired modules.
spelling of `Explore` is wrong

2023-02-15 10:03 UTC, abhinavrastogi-harness approved these changes

2023-02-15 15:28 UTC, deepakbolangady requested changes
Added a first set of comments. Please take a look and reach out if you have any questions. I'm happy to meet and discuss.

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +## Projects
Just referring to the four modules described here (considering Projects to be a module for the purposes of this discussion): are we describing these modules because they are shown in the module selector by default (until the user chooses to change the order or selection)? I think it should be enough to just say that the module selector shows a certain number of modules by default and that the user can change the order and hide modules that they do not use. We should not have to name and describe the modules here. This topic is only about how the UI might behave in specific situations (first login, for example) and how the users can customize the UI.

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +1. Click **Select Modules** in your Harness account, in the left navigation.
Good idea to begin with the location the user should look at first. For example:
```suggestion
1. In the left navigation, click **Select Modules**.
```
(Can skip "in your Harness account", given that that is implicit.)

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +   The modules appear in the following categories:
Good that you listed all the categories and modules verbatim, but just dropping a note that you could simply say "the modules are listed in various functional categories." The UI will corroborate that every time and you won't have to make changes (or have to be informed to make changes) if the categories are renamed or changed in any way. Just a trick that you can ignore for now.

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +2. Select **Customize your navigation** to configure your left navigation.
```suggestion
2. To configure your left navigation, select **Customize your navigation**.
```
(global: good to begin with the objective of the step.)

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +3. To re-order the modules and set the priority, drag and drop the modules.
```suggestion
3. To reorder the modules, drag each module to its desired position. 
```
(by priority, do you mean the order in the list? If yes, then we've already written "reorder". Also, https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/drag-and-drop recommends using move or drag. I rewrote to suggest a change.)

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +4. Click the modules you want to see in the left navigation. Harness automatically saves your selection, and you can see the selected modules in your left navigation.
```suggestion
4. Select the modules you want to see in the left navigation. Harness automatically saves your selection, and you can see the selected modules in your left navigation.
```
(Select, since it's a check box. I clicked a module, outside the checkbox, and nothing happened.)
Also, the user has to close the nav configuration screen by clicking the cross at the top-right corner before they see the selected modules in the left nav. Should we state that as a separate step?)

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +Account Overview has your Harness Account Details.
```suggestion
Account Overview shows your Harness account details.
```

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +To view your Harness Account Details, go to Account Settings and click Overview.
```suggestion
To view your Harness account details, go to **Account Settings** and click **Overview**.
```

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +Your Account Overview details are shown.
```suggestion
Your account overview details are shown.
```

2023-02-15 15:28 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +This section provides options for you to set up Authentication for users, enforce Password policies and restrict email domain.
```suggestion
This section provides options for you to set up authentication for users, enforce Password policies and restrict email domain.
```
This comment applies to the rest of the article from this point onward: these pages are all described in PL docs. Do we need to describe them here, even briefly? It should be sufficient to say that Account Settings aggregates a number of administrative configurations and settings (I leave the wording to you; I'm rambling) that are described in the platform documentation. Simplifying the description insulates this topic from frequent changes in order and name and additions and deletions. Just a thought you should consider.

2023-02-16 04:52 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +![](./static/new-nav-left.png)
Done.

2023-02-16 04:55 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +## Projects
I agree with you. However, I tried to keep the descriptions very short. The point is to give the user an idea so they don't have to go back and forth on multiple topics. It would be their choice to then follow the cross-referenced topics only if they wish to dig deeper.

2023-02-16 04:58 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +## Module selection
The customers would select modules, reorder them and ultimately customize the left navigation.

2023-02-16 04:59 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +   The modules appear in the following categories:
Done

2023-02-16 11:13 UTC, deepakbolangady approved these changes
Approving so that we don't delay the release, but please incorporate the comments whose state I changed to "unresolved". 

I also added a fresh set of comments on the section I had not reviewed yesterday because I deemed them unnecessary in this topic (that section describes each item in Account Settings). However, since you chose not to reword it, I added comments today. Also, that section is missing some items. On app.harness.io, I can see other pages that are not described here. For example:
* Freeze Windows
* Billing
Finally, I don't see MY PROFILE in the account settings nav, in my account. 
So maybe the contents of the left nav depend on one's role? Wouldn't users find the list here confusing then? If it's role-based, we should use the solution I offered in the final comment in my previous review.

2023-02-16 11:29 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +4. Click the modules you want to see in the left navigation. Harness automatically saves your selection, and you can see the selected modules in your left navigation.
Harness saves the settings automatically as and when the user checks or unchecks any module. I have specified this in the doc. We need not have a separate step for this.

2023-02-16 12:14 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +To view your profile information go to MY PROFILE.
Bottom left

2023-02-16 12:18 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +- Basic Information
These are sections on the **My Profile** page.

2023-02-16 12:37 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +## Projects
Ok

2023-02-16 13:07 UTC, deepakbolangady approved these changes
Approved with a final comment about an empty line discrepancy between the two lists in the "My Profile" section. After fixing that, let's merge.

2023-02-16 13:07 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +
The lead-in sentence and list items are separated by a line here. I don't see this separation in the next list. One or the other, for consistency.

2023-02-16 13:07 UTC, deepakbolangady commented on docs/getting-started/harness-ui-overview.md
> +### Subscriptions
Are we missing the trial subscription?

2023-02-16 13:41 UTC, rashminandasahoo commented on docs/getting-started/harness-ui-overview.md
> +### Subscriptions
I picked the details from here https://app.harness.io/ng/#/account/H5W8iol5TNWc4G9h5A2MXg/settings/subscriptions?moduleCard=cd&&tab=PLANS
These are the 3 subscriptions we show on the product.

2023-02-16 13:41 UTC, merged