adding Browser Testing section with BrowserStack doc
harness/developer-hub pull request #7020
Opened 2024-06-11 16:58 UTC by jimsheldon

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: adding Browser Testing section with BrowserStack doc
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-06-11 19:56 UTC, rustd requested changes
Can you please include a yaml sample similar to 

 https://66688cec4268510e84bdad1b--harness-developer.netlify.app/docs/continuous-integration/use-ci/manage-dependencies/ci-localstack-background-step 

or

https://66688cec4268510e84bdad1b--harness-developer.netlify.app/docs/continuous-integration/use-ci/manage-dependencies/ci-saucelabs-background-step

2024-06-13 15:49 UTC, jimsheldon commented
@rustd I have added a yaml example https://666b0b2d3e80c4530b9fc660--harness-developer.netlify.app/docs/continuous-integration/development-guides/browser/browserstack

2024-06-13 20:16 UTC, nofarblue approved these changes
looks good, thanks

2024-06-13 20:20 UTC, rustd approved these changes

2024-06-14 00:42 UTC, merged