Draft PR for Updation of Documentation
harness/developer-hub pull request #7100
Opened 2024-06-18 09:07 UTC by adiyaar24

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-06-18 09:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=7100) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=7100) it.</sub>

2024-06-18 09:08 UTC, adiyaar24 commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
> +distribution
Please ask the Engineering team to provide a sample user data for Windows Distribution as well

As of now if you don't specify the user data it works flawlessly

2024-06-18 13:59 UTC, jimsheldon requested changes

2024-06-18 13:59 UTC, jimsheldon commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/vm-build-infrastructure/set-up-an-aws-vm-build-infrastructure.md
> +      ami: ami-xxx  ## Linux Amd64 AMI should be passed
In the "Launch the EC2 instance" section we say the VM must be Ubuntu. Can we specify Ubuntu here?

```suggestion
      ami: ami-xxx  ## Ubuntu Amd64 AMI must be passed
```

2024-07-04 19:00 UTC, nofarb approved these changes
approved

2024-08-13 18:17 UTC, dewan-ahmed commented
Hi @adiyaar24 please update this PR to resolve conflicts and remove "draft" from title if it's good to get merged. thanks.

2024-10-25 01:07 UTC, closed without merging

2024-10-25 01:07 UTC, bot2-harness commented
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!