Updating docs in case of nested expressions
harness/developer-hub pull request #7152
Opened 2024-06-21 07:46 UTC by vtxorxwitty

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-06-21 08:22 UTC, sahilhindwani-harness commented on docs/platform/variables-and-expressions/harness-variables.md
> +If nested expressions are unable to resolve at some point during resolution, we return the concatenated string value of the partially resolved expression till that point as opposed to null in case of
Can we be more clear here? I think this is not completely clear. 
What are nested expressions and unnested expressions? Can we give some examples?

2024-06-21 08:28 UTC, vtxorxwitty commented on docs/platform/variables-and-expressions/harness-variables.md
> +If nested expressions are unable to resolve at some point during resolution, we return the concatenated string value of the partially resolved expression till that point as opposed to null in case of
Done

2024-06-21 08:30 UTC, sahilhindwani-harness requested changes

2024-06-21 08:30 UTC, sahilhindwani-harness commented on docs/platform/variables-and-expressions/harness-variables.md
> +Unnested Expression: <+pipeline.variables.prod>         --> null
This is not true, right? It depends on executionMode that the step is passing.

2024-06-21 08:34 UTC, vtxorxwitty commented on docs/platform/variables-and-expressions/harness-variables.md
> +Unnested Expression: <+pipeline.variables.prod>         --> null
Yes @sahilhindwani-harness , how would you want us to document this? Should we mention this is only is case of Shellscript. Or Should we document the executionMode corresponding to every step.

2024-08-19 01:09 UTC, closed without merging

2024-08-19 01:10 UTC, bot2-harness commented
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!