[PL-42276] Active PL Feature Flags
harness/developer-hub pull request #7170
Opened 2024-06-24 12:24 UTC by saifeemustafaqharness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): https://harness.atlassian.net/browse/PL-42276
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-06-25 13:32 UTC, brian-f-harness requested changes
@saifeemustafaqharness I suggest moving this content to the What's supported topic to mirror how CD presents the FF list. This was Sid's original request.

2024-06-25 13:32 UTC, brian-f-harness commented on docs/platform/references/active-platform-feature-flags.md
> +helpdocs_is_published: true
```suggestion
```

2024-06-25 13:32 UTC, brian-f-harness commented on docs/platform/references/active-platform-feature-flags.md
> +helpdocs_is_published: true
@saifeemustafaqharness These are legacy fields you find in topics that were converted from the old docs system. They aren't necessary for new topics.

2024-06-25 13:32 UTC, brian-f-harness commented on docs/platform/references/active-platform-feature-flags.md
> +Feature flags are a way that developers can conditionally turn certain sections of their code (or code paths) on or off. You can think of feature flags as an extension or a way to put changes into pr
```suggestion
```

2024-06-25 13:32 UTC, brian-f-harness commented on docs/platform/references/active-platform-feature-flags.md
> +Feature flags are a way that developers can conditionally turn certain sections of their code (or code paths) on or off. You can think of feature flags as an extension or a way to put changes into pr
You can use the verbiage CD uses in the What's supported topic.

https://developer.harness.io/docs/continuous-delivery/cd-integrations#active-cd-feature-flags

2024-06-25 13:39 UTC, brian-f-harness commented on docs/platform/references/active-platform-feature-flags.md
> +| PL_CENTRAL_NOTIFICATIONS                    |             |
```suggestion
| `PL_UPDATE_EMAILS_VIA_SCIM`                |             |
| `PL_NO_EMAIL_FOR_SAML_ACCOUNT_INVITES`        |             |
| `PL_LDAP_PARALLEL_GROUP_SYNC`                 |             |
| `PL_NEW_SCIM_STANDARDS`                     |             |
| `PL_USE_CREDENTIALS_FROM_DELEGATE_FOR_GCP_SM` |             |
| `PL_DELEGATE_TASK_CAPACITY_CHECK`             |             |
| `PL_FAVORITES`                               |             |
| `PL_ALLOW_TO_SET_PUBLIC_ACCESS`               |             |
| `PL_GCP_OIDC_AUTHENTICATION`                  |             |
| `PL_CENTRAL_NOTIFICATION`                    |             |
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +Some Harness Platform features are released behind feature flags to get feedback from specific customers before releasing the features to the general audience.
```suggestion
Some Harness Platform features are released behind feature flags to get feedback from specific customers before releasing the features to the general audience. Feature development statuses are categorized as [Beta, GA, or Limited GA](/docs/platform/get-started/release-status).
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +## Active Platform Feature flags
```suggestion
## Active Platform feature flags
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +| `PL_NEW_SCIM_STANDARDS`                       | Enabling the `PL_NEW_SCIM_STANDARDS` feature flag ensures compliance with SCIM 2.0 standards by including the meta fields `createdAt`, `lastUpdated`,
```suggestion
| `PL_NEW_SCIM_STANDARDS`                       | Enabling the `PL_NEW_SCIM_STANDARDS` feature flag ensures compliance with SCIM 2.0 standards by including the meta fields `createdAt`, `lastUpdated`, `version`, and `resourceType` in CRUD operation responses on users or user groups. |
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +| `PL_DELEGATE_TASK_CAPACITY_CHECK`             | When enabled, tasks of the accounts will be broadcasted until task timeout other wise the default behavior is that tasks will be broadcasted up to 3
```suggestion
| `PL_DELEGATE_TASK_CAPACITY_CHECK`             | When enabled, account tasks will be broadcasted until timeout. The default behavior is to broadcast tasks up to 3 times to delegates. |
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +| `PL_CENTRAL_NOTIFICATION`                     | Enable/disable Centralized Notifications Management. |
```suggestion
| `PL_CENTRAL_NOTIFICATION`                     | Enable/disable Centralized Notifications Management. For more information, go to [Manage delegate notifications](/docs/platform/notifications/manage-notifications). |
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +| `PL_ALLOW_TO_SET_PUBLIC_ACCESS`               | Allows pipeline executions marked for public view to be accessed without authentication. You can share execution URLs, including console logs, withou
```suggestion
| `PL_ALLOW_TO_SET_PUBLIC_ACCESS`               | Allows pipeline executions marked for access to public view without authentication. You can share execution URLs, including console logs, without requiring users to sign in. For more information, go to [Allow public access to pipeline executions](/docs/platform/pipelines/executions-and-logs/allow-public-access-to-executions/).|
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +| `PL_FAVORITES`                                | Allows you to set the frequently accessed projects and connectors as favorites. |
```suggestion
| `PL_FAVORITES`                                | Allows you to set the frequently accessed projects and connectors as favorites. For more information, go to [Set favorites](/docs/platform/favorites/set-favorites/). |
```

2024-07-11 21:25 UTC, brian-f-harness commented on docs/platform/platform-whats-supported.md
> +| `PL_GCP_OIDC_AUTHENTICATION`                  | Enabling this feature flag allows GCP connectors using OpenID Connect (OIDC) to let Harness communicate directly with GCP through OIDC. |
```suggestion
| `PL_GCP_OIDC_AUTHENTICATION`                  | Enabling this feature flag allows GCP connectors using OpenID Connect (OIDC) to let Harness communicate directly with GCP through OIDC. For more information, go to [Google Cloud Platform (GCP) connector settings reference](/docs/platform/connectors/cloud-providers/ref-cloud-providers/gcs-connector-settings-reference/). |
```

2024-07-11 21:43 UTC, batraprashant approved these changes

2024-07-11 21:44 UTC, merged