feat: [PIPE-20191]: Add new file convention for environment
harness/developer-hub pull request #7255
Opened 2024-07-02 07:52 UTC by krishi0408

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-07-02 07:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7255) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=7255) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=7255) it.</sub>

2024-07-02 09:48 UTC, mohitg0795 commented on docs/platform/git-experience/autocreation-of-entities.md
> +- Folder name should be `envs` followed by the type of environment `production` or `pre-production`.
production and pre-production are just examples of type of env

2024-07-03 09:05 UTC, hingerabhinav requested changes

2024-07-03 11:16 UTC, hingerabhinav commented
<img width="299" alt="image" src="https://github.com/harness/developer-hub/assets/67260975/b35dcdc1-6818-4ffa-8697-c462d6832afe">
Plural for env and infras.

2024-07-04 06:45 UTC, hingerabhinav commented on docs/platform/git-experience/autocreation-of-entities.md
> +- Folder name should be `envs` followed by the type of environment `production` and `pre_production`.
production 'or' pre_production

2024-07-04 09:59 UTC, merged