CDS-52164
harness/developer-hub pull request #730
Opened 2023-02-16 11:52 UTC by roshnisarangadharan

Added a use case for triggering a pipeline from a thrid-party CI system using custom webhook trigger

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-20 05:06 UTC, roshnisarangadharan commented
unsuccessful pipeline check

2023-02-27 16:48 UTC, thisrohangupta submitted a review, later dismissed
this looks good thank you!

2023-02-28 15:31 UTC, KimberlyFields requested changes

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +3. In **Artifact Location** > **Artifact Details**, select **Runtime input** for **Image Path** and **Tag** fields.
You have to select **Continue** twice to get to the Artifact Location dialog, but that information is missing. Please revise this step to make it clear. 

Also, add "the" before **Image Path**.

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +4. Click **Submit**.
```suggestion
4. Select **Submit**.
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +1. In your Harness pipeline, click **Triggers**.
```suggestion
1. In your pipeline, select **Triggers** at the top right portion of the dialog.
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +1. In your Harness pipeline, click **Triggers**.
A screenshot with the Triggers option circled would be helpful here because if you've never created a Trigger, the location of the Trigger option is not obvious.

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +4. Name the new trigger and click **Continue**.
```suggestion
4. Name the new trigger, and then select **Continue**.
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +5. Specify the **Conditions** for running the pipeline and click **Continue**.
```suggestion
5. Specify the **Conditions** for running the pipeline, and then select **Continue**. 
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +5. Specify the **Conditions** for running the pipeline and click **Continue**.
"Specify the conditions" is vague. Can you provide some details to guide the user?

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +    For example, execute pipeline if the source/target branch name matches a pattern.
```suggestion
    For example, execute the pipeline if the source or target branch name matches a pattern.
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +6. In **Pipeline Input**, define payload fields so that Harness can map them to the **Image Path** and **Tag** fields.
You have to select **Continue** to get to the Pipeline Input. Please add that missing step.

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +6. In **Pipeline Input**, define payload fields so that Harness can map them to the **Image Path** and **Tag** fields.
"define payload fields" is vague. Can you provide details?

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +7. Click **Create Trigger**.
```suggestion
7. Select **Create Trigger**. 
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +## Trigger the pipeline from an thrid-party CI system.
```suggestion
## Trigger the pipeline from a third-party CI system
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +1. Copy and paste the webhook trigger payload as a cURL command on an editor and edit the body fields.
```suggestion
1. Locate the trigger you created, select the link in the **Webhook** column, and then select **Copy as cURL Command*. 
2. Paste the command in an editor. Edit the body fields.
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +1. Copy and paste the webhook trigger payload as a cURL command on an editor and edit the body fields.
"edit the body fields" is vague. What does the user need to edit and why?

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +    The `-H 'X-Api-Key: sample_api_key'` parameter is used to authorize custom triggers. You can use [Harness API keys](../4_Role-Based-Access-Control/7-add-and-manage-api-keys.md) with this paramete
The third sentence says "This is described below in...". Don't user directional indicates, such as below, per the Microsoft Style Guide.[ ](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/below)

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +    We recommend that you use VS Code or Sublime Text to edit payload information to avoid format issues.
This information should be in the step where you tell them to paste the command into an editor. It's too late at this point.

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +2. Run the updated cURL command on Terminal.
If you made the suggestions I made above, then this should be step 3. 

Also, replace "on Terminal" with "in a Terminal".

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +3. Go to Harness **Deployments** to see the pipeline triggered by your custom webhook trigger.
```suggestion
3. Go to **Deployments** to see the pipeline triggered by your custom webhook trigger.
```

2023-02-28 15:31 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +3. Go to Harness **Deployments** to see the pipeline triggered by your custom webhook trigger.
If you made the edits I suggested above, this should be step 4.

2023-03-01 05:49 UTC, roshnisarangadharan commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +You can use a custom webhook trigger when passing an image from a non-Harness CI system.
Run pipleines from any third-party CI system using custom webhook trigger cURL command.

2023-03-01 06:29 UTC, roshnisarangadharan commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +5. Specify the **Conditions** for running the pipeline and click **Continue**.
Conditions are not mandarory. Have given an example below for better understanding.

2023-03-01 06:37 UTC, roshnisarangadharan commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +6. In **Pipeline Input**, define payload fields so that Harness can map them to the **Image Path** and **Tag** fields.
mentioned select continue in the previous step

2023-03-01 21:54 UTC, michaelcretzman submitted a review, later dismissed
approving with the assumption that you will consider my suggestions.

2023-03-01 21:54 UTC, michaelcretzman commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +6. In the **Pipeline Input** tab, define payloads for the **Image Path** and **Tag** fields so that Harness can map them later when running the trigger.
```suggestion
6. In **Pipeline Input**, define payloads for **Image Path** and **Tag** so that Harness can map them later when running the trigger.
```

2023-03-01 21:54 UTC, michaelcretzman commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +1. Locate the trigger you created, select the link in the **Webhook** column and select **Copy as cURL Command**.
```suggestion
1. In your pipeline **Triggers**, locate the trigger you created, select the link in the **Webhook** column, and select **Copy as cURL Command**.
```

2023-03-01 21:54 UTC, michaelcretzman commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +4. Go to **Deployments** to see the pipeline triggered by your custom webhook trigger.
```suggestion
4. In Harness, go to **Deployments** or the pipeline's **Execution History** to see the pipeline triggered by your custom webhook trigger.
```

2023-03-01 22:21 UTC, KimberlyFields commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +3. On the **Edit Service** dialog, scroll down to the **Artifacts** section and select the pencil icon.
In general, it's best to avoid naming UI elements in instructions, if possible. However, as I was following along as a newbie to the CD UI, I found the UI to be overwhelming with so many pieces and parts that change every time you select something. The UI is quite busy. I suggested that Roshni add the names of UI elements in some cases to act as guides for newer users. For example, it took me a few minutes to realize that "Service" is a tab that I had to select. I also recommended that Roshni add "dialog" after "Edit Service" to provide affirmation to the user that they are in the right place because a new dialog pops up after you select the pencil icon in step 3. Perhaps this is a difference of viewpoint between myself as someone who does not use CD regularly vs Michael who knows everything about the UI. If you are writing only for the most advanced user, then you are not writing to a large segment of your audience.

2023-03-02 05:57 UTC, roshnisarangadharan commented on docs/platform/11_Triggers/trigger-pipelines-from-a-third-party-ci-system.md
> +3. On the **Edit Service** dialog, scroll down to the **Artifacts** section and select the pencil icon.
I avoided naming UI elements because our audiences are developers. Also, it is consistent with the style and tone of the existing document. Now, should I or should I not mention ui elements like dialog and page?

2023-03-06 14:57 UTC, KimberlyFields submitted a review, later dismissed
Approving with one suggestion.

2023-03-07 07:45 UTC, SmritiSatya approved these changes

2023-03-07 07:46 UTC, merged