[DEL-5781] Delegate install doc for new workflow
harness/developer-hub pull request #738
Opened 2023-02-16 21:20 UTC by kat-enos

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ x] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here: [DEL-5781]

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-16 22:37 UTC, Vbhatia20 submitted a review, later dismissed
provided few comments, please let me know once incorporated.

2023-02-16 22:37 UTC, Vbhatia20 commented on docs/platform/2_Delegates/install-delegates/install-a-delegate
> +  --set delegateDockerImage=harness/delegate-test:23.02.78306 \
delegateDockerImage=harness/delegate-test:23.02.78306. should be
**delegateDockerImage=harness/delegate:23.02.78306**

2023-02-16 22:37 UTC, Vbhatia20 commented on docs/platform/2_Delegates/install-delegates/install-a-delegate
> +helm repo update
can be updated to : **helm repo update harness-delegate**

2023-02-16 22:37 UTC, Vbhatia20 commented on docs/platform/2_Delegates/install-delegates/install-a-delegate
> +docker run --cpus=1 --memory=2g \
this needs to be updated and log streaming url should be added for e.g.:
<img width="696" alt="Screenshot 2023-02-16 at 5 36 10 PM" src="https://user-images.githubusercontent.com/95602529/219502645-c408865f-398c-4b94-902a-165e92f40278.png">

2023-02-16 23:00 UTC, kat-enos commented
Hi Vishal.
I haven't forgotten the updates that were pointed out on the GoogleDoc --
still working on it but building on my desktop and dealing with images.
I'll get these items incorporated in the next hour, I hope.
Thanks.
k.

On Thu, Feb 16, 2023 at 2:37 PM Vishal Bhatia ***@***.***>
wrote:

> *EXTERNAL EMAIL* - Use caution when opening attachments, clicking links,
> or responding.
>
> ***@***.**** requested changes on this pull request.
>
> provided few comments, please let me know once incorporated.
> ------------------------------
>
> In docs/platform/2_Delegates/install-delegates/install-a-delegate
> <https://github.com/harness/developer-hub/pull/738#discussion_r1109073475>
> :
>
> > +```
>
> +helm repo update
>
> +```
>
> +
>
> +#### Install the delegate
>
> +
>
> +Copy and paste the following instructions into your CLI. These instructions are modified based on your account settings and the configuration options selected above.
>
> +
>
> +```
>
> +helm upgrade -i helm-delegate --namespace harness-delegate-ng --create-namespace \
>
> +  harness-delegate/harness-delegate-ng \
>
> +  --set delegateName=helm-delegate \
>
> +  --set accountId=yOGUkZC9THWFWgVA6tSj-g \
>
> +  --set delegateToken=NTg4YzNjZDc1NzAyMTE2MzBhMTJlYTI1MDkyYjRjMzg= \
>
> +  --set managerEndpoint=https://stress.harness.io \
>
> +  --set delegateDockerImage=harness/delegate-test:23.02.78306 \
>
>
> delegateDockerImage=harness/delegate-test:23.02.78306. should be
> *delegateDockerImage=harness/delegate:23.02.78306*
> ------------------------------
>
> In docs/platform/2_Delegates/install-delegates/install-a-delegate
> <https://github.com/harness/developer-hub/pull/738#discussion_r1109091591>
> :
>
> > +Delegates are identified by their names. Delegate names must be unique within a namespace and should be unique in your cluster. A valid name includes only lowercase letters and does not start or end with a number. The dash character (“-”) can be used as a separator between letters.
>
> +
>
> +#### Add the repository
>
> +
>
> +Add the Harness Helm chart repository to your local Helm registry. Use the following command:
>
> +
>
> +```
>
> +helm repo add harness-delegate https://app.harness.io/storage/harness-download/delegate-helm-chart/
>
> +```
>
> +
>
> +#### Update the repository
>
> +
>
> +Use the following command to ensure you retrieve the latest version of the Harness Helm chart:
>
> +
>
> +```
>
> +helm repo update
>
>
> can be updated to : *helm repo update harness-delegate*
> ------------------------------
>
> In docs/platform/2_Delegates/install-delegates/install-a-delegate
> <https://github.com/harness/developer-hub/pull/738#discussion_r1109093267>
> :
>
> > +
>
> +#### Name the delegate
>
> +
>
> +Accept or change the default delegate name of `docker-delegate`.
>
> +
>
> +![](./static/install-a-delegate-21.png)
>
> +
>
> +Delegates are identified by their names. Delegate names must be unique within a namespace and should be unique in your cluster. A valid name includes only lowercase letters and does not start or end with a number. The dash character (“-”) can be used as a separator between letters.
>
> +
>
> +
>
> +#### Install the delegate
>
> +
>
> +Use the `docker run` command to install the delegate with the specified parameters:
>
> +
>
> +```
>
> +docker run --cpus=1 --memory=2g \
>
>
> this needs to be updated and log streaming url should be added for e.g.:
> [image: Screenshot 2023-02-16 at 5 36 10 PM]
> <https://user-images.githubusercontent.com/95602529/219502645-c408865f-398c-4b94-902a-165e92f40278.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/harness/developer-hub/pull/738#pullrequestreview-1302359698>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZTVUT7DNQUHXXAPSEGMZ7DWX2T37ANCNFSM6AAAAAAU6VVGSQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>
>

2023-02-21 23:36 UTC, xingchi-jin requested changes

2023-02-21 23:36 UTC, xingchi-jin commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +  -e MANAGER_HOST_AND_PORT=https://myserver.io harness/new-delegate:23.02.78306
we are showing different MANAGER_HOST_AND_PORT and image for different commands. eg. the 
MANAGER_HOST_AND_PORT is https://myserver.io while at line 128, it's  https://stress.harness.io
for image, here it's showing harness/new-delegate:23.02.78306, at line 129 it's harness/delegate:23.02.78306 

make sure they are the consistent

2023-02-21 23:37 UTC, xingchi-jin commented on docs/platform/2_Delegates/install-delegates/install-a-delegate
> +  --set delegateDockerImage=harness/delegate-test:23.02.78306 \
should it use a specific image tag here ? 

now 784 is already released

2023-02-23 03:54 UTC, xingchi-jin commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +| `managerEndpoint` | The endpoint of Harness Manager in your Harness cluster. |
the managerEndpoint description is same as the one at line 239, should we show the same suggestions here ?

2023-02-23 03:54 UTC, xingchi-jin commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +  -e MANAGER_HOST_AND_PORT=https://myserver.io harness/delegate:23.02.78306
the managerEndpoint description is same as the one at line 239, should we show the same suggestions here ?

2023-02-23 15:49 UTC, aimurphy approved these changes
Approved w some comments and the understanding that you will reformat more in the near future.

2023-02-23 15:49 UTC, aimurphy commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +description: This document explains how to install Harness delegates in NextGen environments on Kubernetes or Docker using Helm chart, Terraform Plan, Kubernetes manifest, or Docker.
This is too long for the card. You could copy the first sentence from your topic body and let it truncate (so that it appears to the user as if the card is previewing the first line on the page), or shorten to ~10 words so it will fit on the card.

2023-02-23 15:49 UTC, aimurphy commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +- Select the mode of installation: Helm chart, Terraform Plan, or Kubernetes manifest
suggest using OL since it is a series of steps.

2023-02-23 15:49 UTC, aimurphy commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +# Go to the New Delegate page
Start with heading level 2. The page title is rendered as H1 in the output, and accessibility best practices recommend only one `<h1>` per page. 

https://www.nomensa.com/blog/how-structure-headings-web-accessibility
https://webaim.org/techniques/semanticstructure/#headings

2023-02-23 17:24 UTC, kat-enos commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +description: This document explains how to install Harness delegates in NextGen environments on Kubernetes or Docker using Helm chart, Terraform Plan, Kubernetes manifest, or Docker.
Thanks April. I'm looking forward to the landing pages that allow for more customization and the inclusion of paths through the documentation. I accustomed to using full sentences for these descriptions based on their inclusion in meta information in searches. I'll have to take a pass over the descriptions.

2023-02-23 17:33 UTC, kat-enos commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +- Select the mode of installation: Helm chart, Terraform Plan, or Kubernetes manifest
It wasn't meant as an ordered procedure but to break down the longer series of steps into three parts and would misrepresent the longer series of steps that the install actually includes. Basically, I'm using the Microsoft way I was trained to do it in the developer content where programmed processes or higher-level processes are distinguished from procedures. These might also end up as links or tab headings in the end. But thanks.

2023-02-23 17:35 UTC, kat-enos commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +# Go to the New Delegate page
Thanks for pointing that out. Maybe starting with H2 won't kill me once things are moved around -- I needed the lower-level heads.

2023-02-23 18:11 UTC, pratmit approved these changes
Verified in the pr environment, the delegate install page is stale but can be removed as all the commands are included.

2023-02-23 20:02 UTC, kat-enos commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +
This was resolved yesterday. @pratmit was not looking at a Preview file.

2023-02-23 20:03 UTC, kat-enos commented on docs/platform/2_Delegates/install-delegates/install-a-delegate.md
> +---
This image does not exist in the doc and I explained the larger image that provides context. @pratmit was not looking at a Preview file.

2023-02-23 20:08 UTC, aimurphy commented
@kat-enos Please let me know why the CI topics were deleted before merging this.

2023-02-23 22:08 UTC, aimurphy commented
@ravilach all 4 worked so I'm gonna merge this.

2023-02-24 01:03 UTC, aimurphy approved these changes

2023-02-24 01:03 UTC, merged