Update continuous-integration-faqs.md
harness/developer-hub pull request #7389
Opened 2024-07-16 19:56 UTC by austinthao5

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-07-16 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7389) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=7389) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=7389) it.</sub>

2024-07-22 20:22 UTC, dewan-ahmed commented
Thanks for your contribution @austinthao5 
Could you please sign the [CLA](https://cla-assistant.io/harness/developer-hub?pullRequest=7389)? 

https://github.com/harness/developer-hub/pull/7389#issuecomment-2231723827

thanks.

2024-07-24 17:28 UTC, austinthao5 commented
CLA has been signed. Let me know if there's any other issues

2024-08-02 02:57 UTC, dewan-ahmed requested changes
![Screenshot 2024-08-01 at 11 53 13 PM](https://github.com/user-attachments/assets/c011d703-bac3-4e6e-9453-a13bd0f0557e)
Made some formatting changes due to how the backtick enclosed text was appearing.

2024-08-02 02:57 UTC, dewan-ahmed commented on kb/continuous-integration/continuous-integration-faqs.md
> +### What's the difference between `CI_MOUNT_VOLUMES`, `ADDITIONAL_CERTS_PATH`, and `DESTINATION_CA_PATH`?
```suggestion
### What's the difference between CI_MOUNT_VOLUMES, ADDITIONAL_CERTS_PATH, and DESTINATION_CA_PATH?
```

2024-08-02 02:57 UTC, dewan-ahmed commented on kb/continuous-integration/continuous-integration-faqs.md
> +`ADDTIONAL_CERTS_PATH` and `CI_MOUNT_VOLUMES` work in tandem to ensure certificates are mounted on the Kubernetes Build Infrastructure where as `DESTINATION_CA_PATH` does not require other environmen
```suggestion
`ADDTIONAL_CERTS_PATH` and `CI_MOUNT_VOLUMES` work in tandem to ensure certificates are mounted on the Kubernetes Build Infrastructure, whereas `DESTINATION_CA_PATH` does not require other environment variables to mount certificates. Instead, `DESTINATION_CA_PATH` relies on the certificate being mounted at `/opt/harness-delegate/ca-bundle` in order to copy the certificate to the provided comma-separated list of file paths.
```

2024-08-03 12:58 UTC, dewan-ahmed approved these changes
Changes done via https://github.com/harness/developer-hub/pull/7389/commits/ea2643ce57190d65fb2319116cbdf493d34571d1 and and https://github.com/harness/developer-hub/pull/7389/commits/9705f78949b098cef993953082cf217af62d6f00

2024-08-03 12:58 UTC, merged