DOCS-2514-Concatenate-pipeline-variables
harness/developer-hub pull request #745
Opened 2023-02-20 09:40 UTC by roshnisarangadharan

Added a new entry to show the correct concatenation syntax for pipeline variables. Made editorial updates to match current style guidelines.

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-20 09:41 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +### Variable concatenation
@naidu-harness @guilhermezanini-harness Added a new section to explain correct concatenation syntax. Please review.

2023-02-20 09:53 UTC, naidu-harness requested changes

2023-02-20 09:53 UTC, naidu-harness commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +For example, `<+pipeline.variable.var1>_suffix` will not work.
I would not use this. 
Lets say Harness always recommends to use `<+pipeline.variables.var1>.+("_suffix")` /  `<+pipeline.variables.var1>.concat("_suffix")` instead of `<+pipeline.variable.var1>_suffix`

2023-02-20 09:53 UTC, naidu-harness commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +For example, `<+pipeline.variable.var1>_suffix` will not work.
There are some places it might work without string interpolation and that causes confusion.

2023-02-20 09:53 UTC, naidu-harness commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +When using ternary conditional `?:` operators, do not use spaces between the operators and values.
can we give a sample explaining with spaces and without spaces to show the difference?

2023-02-20 10:46 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +For example, `condition ? <value_if_true> : <value_if_false> will not work. Use `condition?<value_if_true>:<value_if_false>` instead.
@naidu-harness Please check if this simple example is enough

2023-02-20 10:48 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +For example, `condition ? <value_if_true> : <value_if_false>` will not work. Use `condition?<value_if_true>:<value_if_false>` instead.
@naidu-harness Please check if this simple example is enough

2023-02-20 10:49 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +Harness recommends that you use Java string method for concatenating pipeline variables.
@naidu-harness How about this?

2023-02-20 10:54 UTC, naidu-harness approved these changes

2023-02-20 10:54 UTC, naidu-harness commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +For example, `condition ? <value_if_true> : <value_if_false>` will not work. Use `condition?<value_if_true>:<value_if_false>` instead.
LGTM

2023-02-20 10:54 UTC, naidu-harness commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +Harness recommends that you use Java string method for concatenating pipeline variables.
LGTM

2023-02-20 14:29 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
In this illustration, you can see how the information in each section of the stage is referenced.

2023-02-20 14:29 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Here is how you reference the information in each of these sections.

2023-02-20 14:32 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
You can use all Java string methods on Harness variable expressions.

2023-02-20 14:37 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
I did not understand this sentence. Can it be rephrased?
Does this give the same meaning? "You can also paste the expressions that don't appear, such as expressions that reference settings from previous stages."

2023-02-20 14:40 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
... it tries to resolve it ... -> can we rephrase? I understand it means Harness tries to resolve the expression, but 'it' and 'it' again may be a little confusing.

2023-02-20 14:41 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Variable names must be unique within the same stage. You can use the same variable names in different stages of the same pipeline or in other pipelines.

2023-02-20 14:43 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Number type variables are always treated as doubles (double-precision floating-point).

2023-02-20 14:43 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
For example, here is a pipeline variable of number type.

2023-02-20 14:44 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
If you enter 123 in a string field, such as a name, it is treated as a string. If you enter 123 in a count field, such as instance count, it is treated as a double.

2023-02-20 14:44 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Here is a ...

2023-02-20 14:45 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Here is ..

2023-02-20 14:45 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
For example, in the following execution URL, the UUID follows `executions` and is `kNHtmOaLTu66f_QNU-wdDw`.

2023-02-20 14:47 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Here is ...

2023-02-20 14:48 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Currently, there are two versions of services and environments, v1 and v2. Services and environments v1 are being replaced by services and environments v2.

2023-02-20 14:52 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
If the Docker image is added in the service definition **Artifacts** section, you can reference it as `dockercfg: <+artifact.imagePullSecret>`.

2023-02-20 14:53 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
For example, AMI tags. If you are deploying a Docker image named `nginx:stable-perl`, the tag would be `stable-perl`.

2023-02-20 14:54 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
... Docker Hub, ECR, or GCR.

2023-02-20 14:54 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
.. repository.

2023-02-20 14:54 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
In a Harness Shell script step ...

2023-02-20 14:55 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
The sidecar identifier is set when you add the sidecar artifact. You can see it in the artifact listing.

2023-02-20 14:58 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
These deployments can be done in physical data centers, on AWS, and on Azure.

2023-02-20 14:59 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
If you use this variable in a pipeline, ...

2023-02-20 15:01 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
When you add a new artifact trigger, you can select the artifact to listen on, and its **Tag** setting is automatically populated with `<+trigger.artifact.build>`.

2023-02-20 15:01 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Can this be rephrased?

2023-02-20 15:02 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
Adding a new tag to the artifact fires the trigger and executes the pipeline. Harness resolves `<+trigger.artifact.build>` to the tag that fired the trigger. This ensures that the new tag is used when pulling the artifact and that version is deployed.

2023-02-20 15:03 UTC, SmritiSatya commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
.. repositories used by the triggers.

2023-02-21 05:52 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
You can also paste the expressions that don't appear. For example, expressions that reference settings from previous stages.

2023-02-21 05:55 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
ignoring this comment. I think "on physical data centers, AWS, and Azure" is grammatically ok.

2023-02-21 05:57 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
The `<+trigger.artifact.build>` used for **Tag** makes sure that the new artifact version that executed the trigger is used for the deployment.

2023-02-21 05:57 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
"...and the new artifact version is deployed."

2023-02-21 05:59 UTC, roshnisarangadharan commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
You can select who can create and use these triggers within Harness. However, you must use your repository's RBAC to control who can add the artifacts or initiate the events that start the Harness trigger.

2023-02-21 06:25 UTC, SmritiSatya approved these changes

2023-02-21 06:26 UTC, merged