CI 1.36 and 1.37 RN for CI.
harness/developer-hub pull request #7464
Opened 2024-07-23 15:16 UTC by dewan-ahmed

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: CI 1.36 and 1.37 Release Notes
* Preview links/images (Internal contributors only): \__________________

## Merge Requirements

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-07-23 15:18 UTC, dewan-ahmed commented
These release notes are still being worked on. Please **do not merge**.

Once the PR is ready, I'll remove the **do not merge** label and this PR will go through PM review and editorial review.

2024-07-23 15:19 UTC, lkilpatrick-harness approved these changes
LGTM

2024-07-29 19:05 UTC, nofarblue requested changes

2024-07-29 19:05 UTC, nofarblue commented on release-notes/continuous-integration.md
> +#### Early Access feature
Can you take the git clone out of this release notes ?
it goes in in 1.39

2024-07-29 20:56 UTC, dewan-ahmed commented on release-notes/continuous-integration.md
> +#### Early Access feature
sure. resolved via https://github.com/harness/developer-hub/pull/7464/commits/b1457728b4c3c1b18734ec2b33c85f573afdcfd9

2024-07-29 21:44 UTC, dewan-ahmed commented
@nofarblue please review.

2024-07-29 22:17 UTC, nofarblue approved these changes

2024-07-29 22:18 UTC, merged