Faqs-Q2
harness/developer-hub pull request #7497
Opened 2024-07-25 23:01 UTC by kartikeya2609

Faqs-Q2

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: Added few FAQs

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [X] Successful preview build.

2024-07-27 02:12 UTC, dewan-ahmed commented
Hi @kartikeya2609 please check the build fail details and fix the issues. Then we can review. Thanks.

2024-07-29 11:32 UTC, krishi0408 commented on kb/security-testing-orchestration/security-testing-orchestration-faqs.md
> +Access Token (Orchestration scans): Use a Harness text secret for your encrypted token and reference it in the format <+secrets.getValue("myaccesstoken")>.
```suggestion
Access Token (Orchestration scans): Use a Harness text secret for your encrypted token and reference it in the format `<+secrets.getValue("myaccesstoken")>`.
```

2024-07-29 11:32 UTC, krishi0408 commented on kb/continuous-delivery/faqs.md
> +#### Can user use the \*.tgz file to do the helm template cli?
```suggestion
#### Can user use the `\*.tgz` file to do the helm template cli?
```

2024-07-29 11:48 UTC, krishi0408 commented on kb/continuous-delivery/faqs.md
> +#### Harness uses which encoding in the copy command step?
```suggestion
#### Which encoding in the copy command step in Harness?
```

2024-07-29 11:49 UTC, krishi0408 approved these changes

2024-07-29 11:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7497) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=7497) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: kartikeya2609<br/>:x: krishi0408<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=7497) it.</sub>

2024-08-14 03:08 UTC, nofarblue commented on kb/continuous-integration/continuous-integration-faqs.md
> +### Is user can filter which CI builds timed out during Initialize step?
I  think tis is very specific , and shouldn't be included in FAQ

2024-08-14 03:10 UTC, nofarblue commented on kb/continuous-integration/continuous-integration-faqs.md
> +### How can user Spin up a dynamic containers during testing after the build?
I understand the answer, but I don't think the question is clear. there are many use cases for background step. 
Maybe something like ' how can I spin up a service needed by my build steps?'

2024-08-14 03:12 UTC, nofarblue requested changes
I've made multiple comments on the CI FAQ updates. please review.

2024-10-25 01:07 UTC, closed without merging

2024-10-25 01:07 UTC, bot2-harness commented
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!