feat:[CDS-99739]: Sequential and parallel deployments
harness/developer-hub pull request #7613
Opened 2024-08-07 13:34 UTC by krishi0408

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-08-07 13:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7613) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=7613) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=7613) it.</sub>

2024-08-07 20:57 UTC, SushrutHarness requested changes
Please take a look at this page:
https://developer.harness.io/docs/continuous-delivery/x-platform-cd-features/advanced/multiserv-multienv/#deploying-in-parallel-or-serial
Are you repeating work? 

Also, please move the page into `Advanced CD Use cases`

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +When you click on **Deploy multiple Services** you see an option for **Deploy Services in Parallel?**. When you check that it will allow you to deploy your services parallelly.
```suggestion
When you click on **Deploy multiple Services** you see an option for **Deploy Services in Parallel?**. When you check that it will allow you to deploy your services in parallel.
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +When you click on **Deploy to multiple Environments or Infrastructures** you see an option for **Deploy to Environments or Infrastructures in parallel?**. When you check that it will allow you to dep
```suggestion
When you click on **Deploy to multiple Environments or Infrastructures** you see an option for **Deploy to Environments or Infrastructures in parallel?**. When you check that it will allow you to deploy your infrastructure and environment in parallel.
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +By default, the execution sequence is the parallel deployment for Services.
```suggestion
By default, the execution sequence is parallel deployment for services.
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +Pipelines can be executed with multiple Services and Environments. These Services and Environments are combined into a Service & Environment (infrastructure) in a stage for execution.
```suggestion
Pipelines can be executed with multiple services and environments. These services and environments are combined into a service & environment (infrastructure) in a stage for execution.
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +1. Sequential Deployment in Multi Services and Sequential Multi-Infrastructure
```suggestion
#### Sequential Deployment in Multi Services and Sequential Multi-Infrastructure
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +### Expected Scenario
```suggestion
### Expected Scenarios
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +Each service is sequentially deployed in collection of Infrastructure ordered in the YAML.
Should this be
```suggestion
Each service is sequentially deployed in a collection of Infrastructure instructed by the YAML.
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +Here, 1 and 2 will be deployed parallelly and 3 and 4 will be deployed parallelly i.e same services are deployed parallelly in the different infrastructure. 1 and 3 will deployed sequentially and 2 a
Please use in parallel over parallely. 
```suggestion
Here, 1 and 2 will be deployed in parallel and 3 and 4 will be deployed in parallel i.e the same services are deployed in parallel in each infrastructure. 1 and 3 will deployed sequentially and 2 and 4 will be deployed sequentially i.e different service in same infrastructure will deployed sequentially.
```

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +Here, 1 and 2 will be deployed parallelly and 3 and 4 will be deployed parallelly i.e same services are deployed parallelly in the different infrastructure. 1 and 3 will deployed sequentially and 2 a
Is the first sentence here about services and the second about environments?

2024-08-07 20:57 UTC, SushrutHarness commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +![](./static/service_parallel_infra_parallel.png)
Is this the right image? it looks like its depicting a sequential deployment.

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +When you click on **Deploy multiple Services** you see an option for **Deploy Services in Parallel?**. When you check that it will allow you to deploy your services in parallel.
Remove the question mark in this line

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +When you click on **Deploy to multiple Environments or Infrastructures** you see an option for **Deploy to Environments or Infrastructures in parallel?**. When you check that it will allow you to dep
This line seems repeating the same words

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +### Sequential Deployment in Multi Services and Sequential Multi-Infrastructure
Sequential Deployment in Multi Services and Multi-Infrastructure

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +For example:
Rename this as Sample configuration

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +### Parallel Deployment in Multi-Services and Sequential Multi-Infrastructure
Parallel Deployment in Multi-Services and Sequential in Multi-Infrastructure

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +Here, 1 and 2 will be deployed in parallel and 3 and 4 will be deployed in parallel i.e the same services are deployed in parallel in each infrastructure. 1 and 3 will deployed sequentially and 2 and
This is confusing

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +
Add the sample title here

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +Services are deployed in parallel, but the environments and infrastructures are deployed sequentially.
This line needs to be rephrased

2024-08-09 13:17 UTC, shylajasun commented on docs/continuous-delivery/x-platform-cd-features/sequential-and-parallel-deployments.md
> +Services are deployed in parallel, but the environments and infrastructures are deployed sequentially.
Services are deployed in parallel sequentially in the infrastructures

2024-08-12 06:52 UTC, SudarshanPurohit reviewed
It's a nice detailed explanation, but I think that more context in the beginning will help. For example, "Deployment and Concurrency" section could come right at the top, along with an explanation of the referenced keyword  "Max Concurrency", and that there are two different settings, one in Service tab, one in Env tab. And then we explain the possible use cases - Service tab setting selecte or not selected, Env tab setting selected or not selected, and both of them selected. Maybe a table?
The sections explaining combinations of flow will be easier to understand once this context is given.

2024-08-12 11:50 UTC, SudarshanPurohit approved these changes
Looks good to me; please get @shylajasun 's review as well.

2024-08-12 14:30 UTC, merged