Ci 13616 upload artifacts to j frog
harness/developer-hub pull request #7653
Opened 2024-08-09 18:49 UTC by lkilpatrick-harness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

https://harness.atlassian.net/browse/CI-13616

Added stage variable examples to https://developer.harness.io/docs/continuous-integration/use-ci/build-and-upload-artifacts/upload-artifacts/upload-artifacts-to-jfrog/

and

https://developer.harness.io/docs/continuous-integration/continuous-integration-faqs/#can-i-run-the-upload-artifacts-to-jfrog-artifactory-step-with-a-non-root-user

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-08-20 00:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7653) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=7653) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: lkilpatrick-harness<br/>:x: nofarblue<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=7653) it.</sub>

2024-08-20 02:46 UTC, nofarblue requested changes, later dismissed
hey, i've made a few changes directly to the source branch, also left a comment

2024-08-20 02:46 UTC, nofarblue commented on kb/continuous-integration/continuous-integration-faqs.md
> +In other cases with a docker compatible jfrog registry, this limitation is not present.
@lkilpatrick-harness  the limitation applies to all build and push steps, other than for 'build and push to docker registry " when configured with jfrog?
if so, why do we add this in the FAQ of 'Build and Push to JFrog Docker registries' page ?

2024-08-26 21:28 UTC, dewan-ahmed commented
Hi @lkilpatrick-harness pls address Nofar's comment(s) and the MC. thanks

2024-08-28 20:46 UTC, nofarb commented on docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md
> +* [Can I push and pull from two different docker registries that have same prefix for registry URL ?](/kb/continuous-integration/continuous-integration-faqs/#can-i-push-and-pull-from-two-different-do
another comment said this limitation doesn't apply in jfrog. should this be removed? @lkilpatrick-harness

2024-09-03 22:48 UTC, Aishwarya-Lad commented on docs/continuous-integration/use-ci/build-and-upload-artifacts/build-and-push/build-and-push-to-docker-jfrog.md
> +* [Can I push and pull from two different docker registries that have same prefix for registry URL ?](/kb/continuous-integration/continuous-integration-faqs/#can-i-push-and-pull-from-two-different-do
yea we can remove this from here, and also from FAQs of all the build and push steps(ACR, GCR, GHCR, ECR, GAR) except of docker.

2024-09-13 13:07 UTC, dewan-ahmed approved these changes
LGTM.

2024-09-13 13:13 UTC, merged