Ci resource classes
harness/developer-hub pull request #7671
Opened 2024-08-13 00:41 UTC by nofarblue

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: added info about available resource classes in Harness cloud and how to select resource class in a stage that uses. cloud 
* Jira/GitHub Issue numbers (if any): CI-8920
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-08-13 00:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7671) <br/>All committers have signed the CLA.

2024-08-13 14:41 UTC, rustd requested changes

2024-08-13 14:41 UTC, rustd commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +
We probably need 2 tables here. wdyt?
Here's what we had used for the internal field enablement for these 2 models.
<img width="1030" alt="image" src="https://github.com/user-attachments/assets/03ce4b2f-1af9-4bf6-a6e7-afdca9e54f18">

2024-08-13 14:41 UTC, rustd commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +When using **Flex** resource class Harness will allocate machines with higher CPU higher than 4 cores, based capacity available in Harness cloud. we recommend using **Flex** resource class , unless l
When using **Flex** resource class Harness will provide maximum resources based on available capacity in Harness cloud.

2024-08-13 14:41 UTC, rustd commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +Customers on paid plans can purchase credits via credit packages. These purchased credits can be rolled over from one month to the next, but generally expire one year from purchase, unless specified
Delete "via credit packages" -> We don't have it

2024-08-13 14:41 UTC, rustd commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> +Free plans get 2000 free build credits each month.
"build credits" is "cloud credits"

2024-08-13 14:41 UTC, rustd commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> +Harness can invoice in arrears for overages. For more information about Harness Cloud billing and build credit consumption, go to [Subscriptions and licenses](/docs/continuous-integration/get-started
"build credits" is "cloud credits"

2024-08-13 14:41 UTC, rustd commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> +You can use the yaml editor to change the cloud machine size, in case you would like to take advantage of larger machines.
delete ", in case you would like to take advantage of larger machines."

2024-08-17 04:12 UTC, nofarblue commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> +You can use the yaml editor to change the cloud machine size, in case you would like to take advantage of larger machines.
removed

2024-08-17 04:16 UTC, nofarblue commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> +Free plans get 2000 free build credits each month.
fixed

2024-08-17 04:16 UTC, nofarblue commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> -You can upgrade from the Free plan to either the Team or Enterprise plan through the Harness Platform.
we don't have 'Team' anymore , just startup and enterprise, so I though just saying 'paid' is better @rustd

2024-08-17 04:18 UTC, nofarblue commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +When using **Flex** resource class Harness will allocate machines with higher CPU higher than 4 cores, based capacity available in Harness cloud. we recommend using **Flex** resource class , unless l
changed

2024-08-17 04:19 UTC, nofarblue commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +Customers on paid plans can purchase credits via credit packages. These purchased credits can be rolled over from one month to the next, but generally expire one year from purchase, unless specified
fixed

2024-08-17 05:06 UTC, nofarblue commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +
changed

2024-08-19 16:04 UTC, rustd commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +Harness Cloud provides Harness-managed VMs for executing various tasks, such as builds, and security tests. This section explains billing and credit consumption for Harness Cloud.
infrastructure

2024-08-19 17:23 UTC, rustd commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +Each minute of execution on Harness Cloud consumes credits. The rate per Cloud minute, and the resulting credits consumption, depends on the target environment (such as OS type, machine resources, an
Each minute of execution on Harness Cloud consumes credits. The rate per minute, and the resulting credits consumption, depends on the target environment (such as OS type, machine resources, and so on) that you use for the Harness Cloud execution.

2024-08-19 17:32 UTC, rustd commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +Harness Cloud provides Harness-managed VMs for executing various tasks, such as builds, and security tests. This section explains billing and credit consumption for Harness Cloud.
Harness cloud will include compute, storage and networking credits so let's leave it more broader.

2024-08-20 03:17 UTC, nofarblue commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> -You can upgrade from the Free plan to either the Team or Enterprise plan through the Harness Platform.
fixed

2024-08-20 03:20 UTC, nofarblue commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +Each minute of execution on Harness Cloud consumes credits. The rate per Cloud minute, and the resulting credits consumption, depends on the target environment (such as OS type, machine resources, an
fixed

2024-08-20 03:22 UTC, nofarblue commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
don't follow, can you show the add comment to the line where a change is needed @neo413001

2024-08-28 22:27 UTC, rustd commented on docs/continuous-integration/get-started/ci-subscription-mgmt.md
> +**Custom Model**: Users can select specific resource classes tailored to their needs, with defined CPU allocations.
Use "Cores" instead of "CPU" everywhere

2024-08-28 22:29 UTC, rustd commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> +* Use Cloud credits to run builds on Harness-managed machines. No need to set up you own machines.
infrastructure instead of machines. No need to set-up and maintain infrastructure yourself

2024-08-28 23:01 UTC, nofarb commented on docs/continuous-integration/use-ci/set-up-build-infrastructure/use-harness-cloud-build-infrastructure.md
> +Harness can invoice in arrears for overages. For more information about Harness Cloud billing and build credit consumption, go to [Subscriptions and licenses](/docs/continuous-integration/get-started
this is just the file name, not what the user see

2024-09-16 20:35 UTC, dewan-ahmed commented
@nofarblue pls check the build fails and MC.

2024-10-23 14:28 UTC, rustd approved these changes

2024-10-23 14:46 UTC, merged