Ci release notes 1.42
harness/developer-hub pull request #7711
Opened 2024-08-17 00:05 UTC by lkilpatrick-harness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

### Version 1.42

#### Fixed issues

- The Intelligence Baseline popup was re-running the pipeline even when the close button was clicked. This has been fixed so that the close button now dismisses the popup as expected. (CI-13779, ZD-68120)

- On pipeline failure at init step entire pod yaml/object was being logged as error log for debugging as a result if any environment variables in a container referencing secrets present were also getting logged in delegate logs. Issue is resolved by changing the log type from error to debug type to remove visibility and added an extra log without logging entire object. (CI-13785)

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-08-17 05:22 UTC, nofarblue requested changes
see comment

2024-08-17 05:22 UTC, nofarblue commented on release-notes/continuous-integration.md
> +- The Intelligence Baseline popup was re-running the pipeline even when the close button was clicked. This has been fixed so that the close button now dismisses the popup as expected. (CI-13779, ZD-6
let's remove this please, this is beta FF

2024-08-19 19:05 UTC, dewan-ahmed commented
Please update the file front matter date.

2024-08-19 19:39 UTC, lkilpatrick-harness commented on release-notes/continuous-integration.md
> +- The Intelligence Baseline popup was re-running the pipeline even when the close button was clicked. This has been fixed so that the close button now dismisses the popup as expected. (CI-13779, ZD-6
I have removed it.

2024-08-20 03:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=7711) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=7711) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: lkilpatrick-harness<br/>:x: nofarblue<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=7711) it.</sub>

2024-08-20 03:00 UTC, nofarblue approved these changes

2024-08-20 16:10 UTC, merged