Change Impact Analysis Quickstart - Harness feature flag as change source.
harness/developer-hub pull request #788
Opened 2023-02-22 21:43 UTC by SudheendraKatte

Change Impact Analysis Quickstart
 -  add new topic - Harness feature flag as change source. 
 - rewrote and restructured the change impact analysis content
 
# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [X] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-22 21:48 UTC, SudheendraKatte commented
@shankarh7924 , I have made the following changes:

- created a new topic for adding ff as change source
- revamped the existing change impact analysis content
- restructured the topics
Please review and provide your comments

2023-02-28 03:42 UTC, SudheendraKatte commented
Please review and provide comments. Here are the major changes:

- New topic - change-impact-analysis-add-featureflag.md
- Content reorg and rewrite - change-impact-analysis-changes-dash-board.md, change-impact-analysis-quickstart.md, and change-impact-analysis-service-health-dashboard.md.

2023-02-28 05:54 UTC, deepak-harness commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +You can add Harness Feature Flag as a change source. This helps you monitor the impact of feature flag on service health. The following steps explain how to add feature flag as a change source.
Feature flag is by default added as a change source since it is an internal change source.
What need to explain is how changes of a "given" feature flag can be seen in SRM against the service health.

2023-02-28 06:30 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +You can add Harness Feature Flag as a change source. This helps you monitor the impact of feature flag on service health. The following steps explain how to add feature flag as a change source.
Thanks @deepak-harness . I have updated the topic. Please review and let me know.

2023-02-28 12:10 UTC, deepak-harness commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +The Changes dashboard provides a quick overview of change events from multiple change sources. A change source is a combination of a Harness Service and associated environment that monitors changes s
"change source is a combination"
Change source is a system which generate the change events when ever it records any change.

2023-02-28 12:10 UTC, deepak-harness commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +The Changes dashboard helps you understand when the change occurred, why it took place, and what kind of effect it had.
what kind of effect it had on the service health of the monitored service.

2023-02-28 12:10 UTC, deepak-harness commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +- Correlate recent changes in your service and their broader impact on your service.
on your service's health

2023-02-28 12:10 UTC, deepak-harness commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +1. Select **+ Add New Health Source**.
It should be seperate section. Just say add a new health source.
Now, Health source section(module) can talk about how to configure each type of health source

2023-02-28 12:10 UTC, deepak-harness commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +1. Select **+ Add New Health Source**.
same in health source. just say add a connection and divert the user to add connector which can have seperate doc for each type of connector.

2023-02-28 15:04 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +The Changes dashboard provides a quick overview of change events from multiple change sources. A change source is a combination of a Harness Service and associated environment that monitors changes s
Replaced with the following:
A change source is a system that generates change events whenever a change is recorded.

2023-02-28 15:08 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +- Correlate recent changes in your service and their broader impact on your service.
Updated

2023-02-28 15:09 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +1. Select **+ Add New Health Source**.
Noted. As discussed, these issues will be addressed while restructuring the documentation.

2023-02-28 17:07 UTC, sunilgupta-harness commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +Whenever the feature flag is turned off or on, a change event is recorded in the Health Source page of the monitored service.
Change event is recorded on health score page not health source page of monitored service

2023-03-01 10:43 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +Whenever the feature flag is turned off or on, a change event is recorded in the Health Source page of the monitored service.
Updates as
Whenever the feature flag is turned off or on, a change event is recorded in the Service Health page of the monitored service.

2023-03-01 12:10 UTC, deepak-harness submitted a review, later dismissed

2023-03-02 10:31 UTC, SmritiSatya submitted a review, later dismissed

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +sidebar_position: 30
Overview of all the change events.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
Outlined below is the step to navigate to the Changes dashboard.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
#### Changes timeline

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
It has the following details.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
You can modify the time slot using the handles.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
Harness Change Impact Analysis allows you to get a clear understanding of what has changed, when it changed, why it changed, and the effect it had on your monitored service. It helps you identify recent change events in your service around the time when there is a deterioration of performance. This real-time change event tracking aids in faster root cause analysis, allowing teams to make confident decisions.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +- Ensure that you have installed a Delegate and it can communicate with Harness, health source, and change source. To learn more about Delegates, go to [Get started with delegates](https://developer.
Ensure that you have installed a Delegate and that it can communicate with Harness, health source, and change source.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
To create a project:

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
A Harness Monitored Service is a combination of a Harness service and environment. A service represents a microservice or other workloads, which means it is a logical entity that can be monitored. Environments represent your deployment targets such as QA, prod, and so on.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
To create a new change source:

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
To add a new health source:

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +description: Observe and track health of monitored service.
Observe and track health of the monitored service.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +- Overall health score timeline
Change summary

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
Overall health score timeline

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
The graph displays the changes in deployment, infrastructure, feature flag and incidents.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
You can modify the timeline using the handles.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
The **Changes** list provides a detailed breakdown of all the changes that occurred in deployment, infrastructure, and feature flags during the selected time period. It also displays the incidents from the incident management tool during the selected time period. You can see the following information in the **Changes** list:

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
All metrics
Anomalous metrics

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
The **Metrics**, **Logs**, and **Errors** tabs display the metrics, logs, and error data collected at regular intervals, respectively.

2023-03-02 10:31 UTC, SmritiSatya commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
The **Service Dependency** section depicts the dependencies between applications, infrastructure, and data graphically. 

2023-03-02 18:50 UTC, deepakbolangady requested changes
Hi, Sudhi. I know much of the content in this PR is existing content that you had to bring into line somewhat. However, check if you can incorporate these comments. I've used suggestions as much as possible to make your task easier. Let me know how it goes. We should meet to discuss the format of the quickstart, though.

I did not reach the end of the PR in this round, but I'll take another look tomorrow. Thanks. 

I'm hoping Kim or someone else familiar with FF can look at the FF part of this PR.

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +8.   On the top right-hand corner select **Save**.
```suggestion
8. In the upper-right corner select **Save**.  
```
(per https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/u/upper-left-upper-right, though your wording is also used.)

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +description: Observe and track health of monitored service.
Or "observe and track the health of a monitored service."

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +- View metrics to analyze patterns, historic trends, performance changes, and correlate factors of your services over a period.
What are correlate factors? Or does the sentence require some rewording?

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +   A list of all the monitored services appears.
```suggestion
   A list of all monitored services appears.
```

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +2. Choose the monitored service for which you want to see the health data.
```suggestion
2. Select the monitored service for which you want to see health data.
```

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +Change summary displays the number of changes in deployments, infrastructure, and incidents for a specific time period. You can set the time period based on the period of length for which you want to
```suggestion
The change summary displays the number of changes in deployments, infrastructure, and incidents for a specific time period. You can specify the time period for which you want to see data. The available options are:
```
Not sure what "You can set the time period based on the period of length for which you want to see the data" means but we would have to ask the original author. We could hazard a guess. Not sure whether "specify" is the right word but feel free to replace.

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +The overall health score timeline provides a graphical representation of the high level overview of the service health for the time period that you have selected. The graph is divided into time slots
```suggestion
The overall health score timeline is a graphical overview of the health of a service over a specified time period. The graph is divided into time slots of equal length. The span of each division depends on the time period setting. The graph displays changes in deployment, infrastructure, and feature flag. It also displays incidents. This helps you correlate data over a time period and analyze the impact of change on the reliability of the service.
```
* Not sure what "graphical representation of the high level overview", but I proposed a change. Let me know whether it works. 
* Also not sure what "based on the time period setting" refers to, but I took a leap. 
* Either "displays changes in the deployment, infrastructure, and feature flag" or "displays changes in deployments, infrastructures, and feature flags". Which one?
* What does the "this" that begins the last sentence refer to? The incidents in the previous sentence or the timeline/graph overall?

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +The overall health score is computed based on the change events such as deployments, infrastructure changes, and incidents. The health score ranges between 0 and 100.
```suggestion
The overall health score is computed based on change events such as deployments, infrastructure changes, and incidents. The health score ranges between 0 and 100.
```
* Can we review this sentence from a technical standpoint? Are deployments considered change events here? Ignore if accurate. Also, "change events such as ... infrastructure changes" sounds odd. Would help to reword. 
* Also, when we use "between" with a numeric range, the end points are not included. Can a health score not be 0 or 100?

2023-03-02 18:50 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +The Overall Health Score timeline has a **Time Window** which displays granular details such as health score, incident count, metrics, and logs for a specific timeline on the graph. You can move the
```suggestion
The Overall Health Score timeline has a time window that displays granular details such as health score, incident count, metrics, and logs for a specific time period on the graph. You can move the time window along the graph to choose a specific time period. You can increase or decrease the time window by using the handles.
```

2023-03-02 19:13 UTC, SudheendraKatte commented
@deepakbolangady and @KimberlyFields , the scope of FF topic here is limited to selecting a monitored service from within the FF. From SRM context, the user is not expected to do anything more here.

2023-03-03 01:33 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +title: Connect Harness Feature Flag to a monitored service
We are not referring to the entire FF module here. It is just an FF within the module. In layman's terms, this topic describes how to tell a monitored service that it should display any changes that happen in a particular FF. So the term "connect' is valid in this context.

Also, it is not "Harness Feature Flags" but just "Harness Feature Flag" as we are talking about a single/one ff that exists within the FF module. To avoid the confusion, changing the title to "Attach a Harness feature flag to a monitored service".

2023-03-03 01:37 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +description: Learn how to connect Harness Feature Flag to a monitored service.
Changed to "...attach a feature flag..."

2023-03-03 01:42 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +You can connect Harness Feature Flag to a monitored service. This helps you monitor the impact of feature flag status change on the service health. The following steps explain how to connect a featur
Accepted

2023-03-03 01:43 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +1. In your Harness project, navigate to the **Feature Flag** module, and then select **Feature Flags**.
Accepted

2023-03-03 01:46 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +3. In the **Services** section, select the pencil icon next to the **Services**.
Accepted.

2023-03-03 01:49 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +Whenever the feature flag is turned off or on, a change event is recorded in the Service Health page of the monitored service.
Updated

2023-03-03 01:55 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +![FF event generated](./static/change-impact-view-ff-event-generated.png)
Thank you! I would be prefer keeping the original text. 

Reference - https://developers.google.com/style/notices#when-to-use-a-note-notice-type

2023-03-03 01:56 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +description: Get a quick overview of all the change events.
Updated the description.

2023-03-03 01:57 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +![Changes dashboard](./static/change-impact-changes-dashboard.png)
Thank you! I would prefer not use the Note tag.

2023-03-03 01:59 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +You can customize the Changes dashboard using the following filters:
Updated

2023-03-03 02:05 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +The Changes Timeline is a graphical representation of all the changes that occurred. The graph displays the information based on the filter settings.
The change that you suggested looks better. Thank you!

2023-03-03 02:26 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +These changes might include deployments, infrastructure changes, incidents, and feature flags. Harness Change Impact Analysis helps you:
Makes sense! Moved the "These changes might include deployments, infrastructure changes, incidents, and feature flags." part to the first paragraph and removed the list that starts with "Harness Change Impact Analysis helps you: ".

2023-03-03 02:32 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +- You must have created an Organization in Harness. To learn more about Organizations in Harness, go to [Create Organizations and Projects](https://developer.harness.io/docs/platform/organizations-an
Accepted the suggested change. For the remaining questions, I would prefer the user to go to the other page to learn more.

2023-03-03 02:43 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +## Create a project
I did consider that option before writing afresh in this topic. The problem is, the last step in the PL procedure has this step:

4. Pick a module and click Create New Pipeline to get started!

2023-03-03 02:50 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +A Harness Monitored Service is a combination of a Harness service and environment. Service represents a microservice or other workloads, which means it is a logical entity that can be monitored. Envi
Loved the suggestion! thank you!

2023-03-03 02:54 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +The Create new monitored service settings page appears.
Agree. Changed to "he Create new monitored service settings page appears."

2023-03-03 03:02 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +      To create a new service, perform the following steps:
Updated

2023-03-03 03:03 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +### Define monitored service
Updated.

2023-03-03 03:04 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +    * **Create or Select an Environment**: Choose an appropriate environment.
Absolutely :)

2023-03-03 03:13 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +2. In the **Provider Type** dropdown, select the change source. Following are the available options:
Updated all the instances.

2023-03-03 03:18 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +4. In the **Application** dropdown, select an application ID. This field is available only if you have selected **Harness CD** as the deployment option.
This looks straight forward - This field is available if you select Harness CD in **Provider Type**.

2023-03-03 03:22 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +### Add change source
My mistake, can't blame frontend :)

2023-03-03 03:28 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +A Health Source monitors the health trends of the Monitored Service using logs or metrics collected from an APM or logging tool.
- Corrected all instances of Health Source --> to health source
- Expanded APM

2023-03-03 03:30 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +   1. **Select Connector**: Select an existing connector. Connectors contain the information necessary to integrate and work with your health source.
Updated

2023-03-03 03:32 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +   2. **Select Feature**: Select the feature associated with the health source. The available features depend on the health source that you select. For example, if you select **SumoLogic** as the hea
Updated

2023-03-03 03:33 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +- **Services**: Select the monitored service for which you want to see the changes. You can select multiple monitored services.
Updated

2023-03-03 03:33 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +- **Sources**: Select the source for which you want to see the changes. For example, Harness CD NextGen, Harness CD, Kubernetes, PagerDuty, Feature Flags, and so on. You can select multiple change so
Updated

2023-03-03 03:33 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +To view the change details for a specific time slot, select the time slot on the Changes Timeline. A time window appears with the details of all the changes that occurred in that specific time slot.
Updated

2023-03-03 03:34 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +Harness Change Impact Analysis allows you to get a clear understanding of what has changed, when it changed, why it changed, and the effect it had on your monitored service. It helps you in identifyi
Updated

2023-03-03 03:34 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +2. In the About the Project page, do the following and then select **Save and Continue**:
Accepted

2023-03-03 03:34 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +   - **Organization**: Select an organization for the project. If you don't yet have an organization in Harness, go to [Create a Harness Org](https://developer.harness.io/docs/platform/organizations-
Accepted

2023-03-03 03:34 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +3. In the Invite Collaborators (Optional) page, add team members to the project in the **Invite People to Collaborate** field.
Accepted

2023-03-03 03:35 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +1. In your Harness project, navigate to the **Service Reliability** module and then select **Monitored Services** > **+ New Monitored Service**.
Updated

2023-03-03 03:35 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +    * **Create or select a Service**: Select a Harness service that you want to monitor.
Updated

2023-03-03 03:36 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +          *  **Name** : Enter a name for the service. For example, _sample_service_.
Updated

2023-03-03 03:36 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +      2. Enter the following information and then select **Save**:
Updated

2023-03-03 03:36 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +    Harness autopopulates the **Monitored Service Name** field by combining the **Service** and **Environment** names. This field is not editable.
Accepted

2023-03-03 03:36 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +A Change Source monitors change events related to deployments, infrastructure changes, and incidents.
Accepted

2023-03-03 03:36 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +In the **Change Sources** section, you can either edit the existing change source or create a new one.
Accepted

2023-03-03 03:37 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +    - **Incident**: Select the incident management tool which monitors your application.
Updated

2023-03-03 03:54 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +6. In the **Customize Health Source** tab, the settings are displayed based on the health source you have selected in the **Define Health Source** tab.
Changed to "On the **Customize Health Source** tab, configure the health source settings. The settings that are displayed depend on the health source that you select in the **Define Health Source** tab."

2023-03-03 03:56 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +   - **Find an AppDynamics application**: Displays the list of applications associated with AppDynamics. Select the appropriated application.
I would prefer "Select the application you want".

2023-03-03 03:58 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +8.   On the top right-hand corner select **Save**.
Noted, thank you!

2023-03-03 04:06 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +- View metrics to analyze patterns, historic trends, performance changes, and correlate factors of your services over a period.
Changed to "correlate the data over a period."

2023-03-03 04:07 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +2. Choose the monitored service for which you want to see the health data.
Updated

2023-03-03 04:10 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +Change summary displays the number of changes in deployments, infrastructure, and incidents for a specific time period. You can set the time period based on the period of length for which you want to
"You can specify the time period for which you want to see the data" is accurate.

2023-03-03 04:16 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +The overall health score timeline provides a graphical representation of the high level overview of the service health for the time period that you have selected. The graph is divided into time slots
Points taken. Here is the updated text:

The overall health score timeline is a graphical overview of the health of a service over a specified time period. The graph is divided into time slots of equal length. The span of each division depends on the time period setting. The graph displays change in deployments, infrastructures, and feature flags. It also displays incidents. The graph helps you correlate data over a time period and analyze the impact of change on the reliability of the service.

2023-03-03 04:26 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +The overall health score is computed based on the change events such as deployments, infrastructure changes, and incidents. The health score ranges between 0 and 100.
Updated text:

The total health score is calculated based on deployment and infrastructure modification change events, as well as incidents. The total health score is calculated based on deployment and infrastructure modification change events, as well as incidents. The health score ranges from 0 and 100.

2023-03-03 04:29 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +The Overall Health Score timeline has a **Time Window** which displays granular details such as health score, incident count, metrics, and logs for a specific timeline on the graph. You can move the
Updated

2023-03-03 04:43 UTC, SudheendraKatte commented on docs/getting-started/quickstarts.md
> +* [Change Impact Analysis Quickstart](../service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md) describes how you can correl
Done

2023-03-03 04:45 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +   ![Feature Flag list](./static/change-impact-view-ff-navigation.png)
Done

2023-03-03 04:45 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +   ![Select Monitored Service](./static/change-impact-view-ff-select-monitoredservice.png)
Removed

2023-03-03 04:52 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +sidebar_position: 30
Changed to "Get an overview of all change events"

2023-03-03 04:53 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
I would prefer the existing text :)

2023-03-03 04:54 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
Done

2023-03-03 04:56 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
Changed to "It displays the following details"

2023-03-03 04:58 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +
Good one! Re writing it as "You can change the time slot using the handles"

2023-03-03 04:59 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
Updated text:

Harness Change Impact Analysis enables you to understand what has changed, when it changed, why it changed, and the effect it had on your monitored service. It helps you identify recent change events in your service around the time performance deteriorated. These changes might include deployments, infrastructure changes, incidents, and feature flags. This real-time change event tracking aids in faster root cause analysis and allows teams to make confident decisions.

2023-03-03 05:00 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
Updated

2023-03-03 05:02 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
Updated text:

A monitored service is a logical entity that combines a Harness service and environment. The service could be a microservice or any other workload that can be monitored. Environments represent your deployment targets such as QA, prod, and so on.

2023-03-03 05:03 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
This looks correct but keeping the existing text based on comments from earlier reviews.

2023-03-03 05:03 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-quickstart.md
> +
This looks correct but keeping the existing text based on comments from earlier reviews.

2023-03-03 05:03 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +description: Observe and track health of monitored service.
Updated

2023-03-03 05:04 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +- Overall health score timeline
Corrected

2023-03-03 05:05 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
Corrected

2023-03-03 05:05 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
Updated text:

The overall health score timeline is a graphical overview of the health of a service over a specified time period. The graph is divided into time slots of equal length. The span of each division depends on the time period setting. The graph displays change in deployments, infrastructures, and feature flags. It also displays incidents. The graph helps you correlate data over a time period and analyze the impact of change on the reliability of the service.

2023-03-03 05:06 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
Updated text:

You can change the time period by using the handles.

2023-03-03 05:09 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
Updated

2023-03-03 05:09 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
They are UI elements.

2023-03-03 05:11 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
Correctec

2023-03-03 05:13 UTC, SudheendraKatte commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-service-health-dashboard.md
> +
Updated text:

The Service Dependence section graphically displays the dependencies between applications, infrastructure, and data.

2023-03-03 12:41 UTC, deepakbolangady submitted a review, later dismissed

2023-03-03 12:52 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-add-featureflag.md
> +![FF event generated](./static/change-impact-view-ff-event-generated.png)
My feedback was about retaining the image. I've complained about so many images that I thought I should let you know when we should keep one. My comment wasn't about converting it to a note but rather about me noting that we should retain the image.

2023-03-03 12:52 UTC, deepakbolangady commented on docs/service-reliability-management/howtos-service-reliability-management/change-impact-analysis/change-impact-analysis-changes-dash-board.md
> +![Changes dashboard](./static/change-impact-changes-dashboard.png)
Again, my comment wasn't about adding a note. It was about me noting explicitly that we should keep this image.

2023-03-03 17:54 UTC, aimurphy approved these changes
Approving line 9 in change-impact-analysis-add-featureflag.md per request in doc-team-reviews channel.

2023-03-03 17:55 UTC, merged