Update fg-delegate.md
harness/developer-hub pull request #790
Opened 2023-02-22 22:55 UTC by kat-enos

Relnotes for Harness Delegate in SaaS 785xx CG

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-22 23:34 UTC, pratmit requested changes

2023-02-22 23:34 UTC, pratmit commented on docs/first-gen/firstgen-release-notes/fg-delegate.md
> +- The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
The delegate hostname can be used for dynamic selection. You can select a delegate hostname from those in your delegate groups during pipeline runtime.

2023-02-23 01:28 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/fg-delegate.md
> +- The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
Same question as the other one.

If you want an alternate, how about:

You can dynamically select delegates by hostname during pipeline runs. To do so, select delegates by hostname from your delegate groups.

2023-02-23 03:21 UTC, pratmit commented on docs/first-gen/firstgen-release-notes/fg-delegate.md
> +- The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
This works !

2023-02-23 03:43 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/fg-delegate.md
> +- The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
I will implement.

2023-02-23 03:43 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/fg-delegate.md
> +- The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
Thanks.

2023-02-24 05:25 UTC, kat-enos commented on docs/first-gen/firstgen-release-notes/fg-delegate.md
> +- The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
Issue resolved. Resolving the conversation.

2023-02-24 16:00 UTC, aimurphy approved these changes
approved w 2 comments about the version number

2023-02-24 16:00 UTC, aimurphy commented on docs/first-gen/firstgen-release-notes/fg-delegate.md
> +Harness FirstGen release 785xx includes the following feature changes and fixes for Harness Delegate.
version number here too

2023-02-24 21:56 UTC, aimurphy approved these changes

2023-02-24 21:57 UTC, merged

2023-02-24 21:58 UTC, kat-enos commented
Thanks April.