Update delegate.md
harness/developer-hub pull request #791
Opened 2023-02-22 23:20 UTC by kat-enos

Release notes for 2/23 SaaS drop,

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ x] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-02-22 23:34 UTC, pratmit requested changes

2023-02-22 23:34 UTC, pratmit commented on release-notes/delegate.md
> +-  - The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
The delegate hostname can be used for dynamic selection. You can select a delegate hostname from those in your delegate groups during pipeline runtime.

2023-02-23 01:23 UTC, kat-enos commented on release-notes/delegate.md
> +-  - The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
@pratmit, they're selecting the hostname of one delegate from the delegates in the delegate groups, aren't they? Your suggestion means they can select a delegate hostname from the hostnames in their delegate groups. Do you mean that the delegates are listed by hostname? Please adviser.

2023-02-23 02:20 UTC, ravilach reviewed
@kat-enos don't forget to change the publish date in the front matter please :-)

2023-02-23 03:20 UTC, pratmit commented on release-notes/delegate.md
> +-  - The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
yes delegate is listed by hostname. Please refer the ticket if more clarification is needed.
This is the public release notes which is also fine by me - "User can provide delegate hostname as a dynamic selector to pick one individual delegate among the delegate groups"

2023-02-24 05:22 UTC, kat-enos commented on release-notes/delegate.md
> +-  - The delegate hostname can be used for dynamic selection. You can select a delegate from those in your delegate groups during pipeline runtime. (DEL-5052)
@pratmit This one took the same change as the CG one -- the change we agreed to. That was slipped in. yesterday, I believe. I am resolving this conversation.

2023-02-24 05:27 UTC, kat-enos commented
@ravilach Front matter corrected yesterday. Cheers.

2023-02-24 16:03 UTC, aimurphy submitted a review, later dismissed
lgtm with 1 comment

2023-02-24 16:03 UTC, aimurphy commented on release-notes/delegate.md
> +Harness NextGen release 785xx includes the following changes for Harness Delegate.
I think it needs the final version number - line 17 and 20?

2023-02-24 21:56 UTC, aimurphy approved these changes

2023-02-24 21:56 UTC, kat-enos commented on release-notes/delegate.md
> +Harness NextGen release 785xx includes the following changes for Harness Delegate.
Done.

2023-02-24 21:57 UTC, merged