[PL-57426]: SMP 0.21.0 Release Notes
harness/developer-hub pull request #8122
Opened 2024-09-25 08:08 UTC by GokulBansal0

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes:  SMP 0.21.0 Release Notes
* Jira/GitHub Issue numbers (if any): [PL-57426](https://harness.atlassian.net/browse/PL-57426)
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-09-30 13:37 UTC, SudarshanPurohit reviewed
This needs to include the following GitOps features: 
https://harness.atlassian.net/browse/CDS-96922
https://harness.atlassian.net/browse/CDS-97914

2024-10-01 05:09 UTC, SudarshanPurohit commented on release-notes/self-managed-enterprise-edition.md
> +
- Access Control to GitOps Applications can now be managed using Labels. This allows Applications to be automatically added to the required Access Control Resource Groups. See https://developer.harness.io/docs/continuous-delivery/gitops/use-gitops/manage-permissions/ for more details. (CDS-97914)
- When creating a GitOps Application, the cluster can now be specified by name instead of using the IP address, if required. This is helpful in cases where the Cluster IP may change in the backend. (CDS-96922)

2024-10-01 17:46 UTC, GokulBansal0 commented on release-notes/self-managed-enterprise-edition.md
> +
added to pr

2024-10-01 17:47 UTC, pratmit approved these changes
LGTM

2024-10-01 17:53 UTC, pratmit approved these changes

2024-10-04 16:22 UTC, wei-harness requested changes

2024-10-04 16:22 UTC, wei-harness commented on docs/self-managed-enterprise-edition/shared/smp-supported-platforms.md
> +| 1.30               | Yes       | Starting with EKS 1.30 (AWS), the support for default annotation on the storage class has been removed. For Harness to work, please update your overrides to include
@GokulBansal0  there is an error during build, please check it out:
 ```
 "message": "Expected a closing tag for `<br>` (11:340-11:344) before the end of `tableData`",
  "line": 11,
  "reason": "Expected a closing tag for `<br>` (11:340-11:344) before the end of `tableData`",
```

2024-10-04 16:23 UTC, wei-harness commented on docs/self-managed-enterprise-edition/shared/smp-supported-platforms.md
> +| 1.30               | Yes       | Starting with EKS 1.30 (AWS), the support for default annotation on the storage class has been removed. For Harness to work, please update your overrides to include
Please use <br /> instead of <br>

2024-10-07 06:38 UTC, GokulBansal0 commented on release-notes/self-managed-enterprise-edition.md
> +| Helm Chart | [0.21.0](https://github.com/harness/helm-charts/releases/tag/harness-0.21.0) |
yes. It will come after release

2024-10-08 09:18 UTC, avaakash submitted a review, later dismissed

2024-10-08 12:29 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +  `minAvailable` and `maxUnavailable` can be set to either percentage or absolute value, if both of them are set then K8s will throw an error.
```suggestion
  `minAvailable` and `maxUnavailable` can be set to either percentage or absolute value. If both of them are set then `minAvailable` will take precedence.
```

2024-10-08 17:12 UTC, wei-harness approved these changes

2024-10-09 08:16 UTC, avaakash approved these changes

2024-10-10 18:24 UTC, avaakash approved these changes

2024-10-10 20:25 UTC, pratmit approved these changes

2024-10-11 05:43 UTC, merged