docs: [IAC-2491]: Add TF Auth approaches
harness/developer-hub pull request #8211
Opened 2024-10-07 11:16 UTC by richardblack-Harness

## Description

* Add OpenTofu and Terraform authentication approaches depending on use case.
* [JIRA](https://harness.atlassian.net/browse/IAC-2491)

PRs must meet these requirements to be merged:

- [x] Successful preview build.
- [x] Code owner review.
- [x] No merge conflicts.
- [x] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-09 13:24 UTC, rssnyder requested changes
just validate new group, otherwise looks great

2024-10-09 13:24 UTC, rssnyder commented on .github/CODEOWNERS
> +/kb/reference-architectures/iacm/ @RickCraig @allofthesepeople @scottyw-harness @richardblack-Harness
i cant find the `allofthesepeople` group in this org, can you link it to me so i can ensure its valid?

2024-10-09 17:37 UTC, richardblack-Harness commented on .github/CODEOWNERS
> +/kb/reference-architectures/iacm/ @RickCraig @allofthesepeople @scottyw-harness @richardblack-Harness
Sure it Roger Simms: https://github.com/allofthesepeople

2024-10-10 09:20 UTC, wei-harness approved these changes

2024-10-14 13:09 UTC, rssnyder approved these changes

2024-10-14 13:34 UTC, merged