fix:[PIPE-22410]:Added details on GitLab repository search limitations
harness/developer-hub pull request #8251
Opened 2024-10-10 09:37 UTC by krishi0408

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-10 09:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=8251) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=8251) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=8251) it.</sub>

2024-10-10 10:29 UTC, senjucanon2 requested changes

2024-10-10 10:29 UTC, senjucanon2 commented on docs/platform/git-experience/oauth-integration.md
change it to "Customers"

2024-10-10 10:33 UTC, senjucanon2 submitted a review, later dismissed
LGTM

2024-10-10 10:43 UTC, mohitg0795 submitted a review, later dismissed

2024-10-14 04:43 UTC, senjucanon2 approved these changes
LGTM

2024-10-14 07:30 UTC, Debanitrkl approved these changes
LGTM

2024-10-14 07:30 UTC, merged