Update DinD docs and URL to override STO images in pipeline
harness/developer-hub pull request #8281
Opened 2024-10-14 12:10 UTC by tejakummarikuntla

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-14 14:19 UTC, williamwissemann commented on docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
> +            pem_files=$(find /harness-shared-certs-path/ -name "*.pem")
```suggestion
            pem_files=$(find $HARNESS_SHARED_CERTS_PATH -name "*.pem")
```

To make this a little bit more resilient we should probably change it to this ^

2024-10-14 16:58 UTC, priteshchandaliya submitted a review, later dismissed

2024-10-15 12:59 UTC, williamwissemann approved these changes

2024-10-15 14:26 UTC, priteshchandaliya submitted a review, later dismissed

2024-10-15 17:44 UTC, krishi0408 submitted a review, later dismissed

2024-10-15 19:03 UTC, wei-harness requested changes

2024-10-15 19:03 UTC, wei-harness commented on docs/security-testing-orchestration/sto-techref-category/wiz-scanner-reference.txt
@tejakummarikuntla what is the txt file for? if it's a markdown file, let's make it ends with .md or .mdx

2024-10-15 19:03 UTC, wei-harness commented on docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.BACKUP.txt
@tejakummarikuntla please don't commit any backup files.

2024-10-16 10:32 UTC, tejakummarikuntla commented on docs/security-testing-orchestration/sto-techref-category/wiz-scanner-reference.txt
This is an old markdown file; it is kept for reference in txt format.

2024-10-16 10:35 UTC, tejakummarikuntla commented on yarn.lock
Thanks for spotting this, @wei-harness.

2024-10-16 10:36 UTC, tejakummarikuntla commented on docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.BACKUP.txt
This seems to be an old file kept for reference. Kingly Ignore this file, it could be needed to refer any specific sections.

2024-10-16 19:39 UTC, wei-harness commented on docs/security-testing-orchestration/sto-techref-category/sonarqube-sonar-scanner-reference.BACKUP.txt
@tejakummarikuntla who would be the right person to verify if it's still being referenced?

2024-10-16 20:37 UTC, wei-harness approved these changes

2024-10-17 11:24 UTC, krishi0408 approved these changes

2024-10-17 13:14 UTC, williamwissemann commented on docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
> +## Scanning a Docker image with STO - DinD details
```suggestion
## Scanning a Docker image with STO
```

You should just remove `- DinD details`

2024-10-17 13:21 UTC, williamwissemann commented on docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
> +<DocVideo src="https://www.youtube.com/embed/x1NXBJaHF7U?si=gOrrOAE9p1DGEnLB" />
A couple of notes:
- Does it make sense to explicitly mention that you don't need the run step using Skopeo to pull the image? STO will automatically pull the tar when using the docker v2, aws ecr, etc. settings. It may be worth transitioning from "What does to native steps support?" to saying, "To simulate scanning an image built within the pipeline, we will use a run step using Skopeo..."
- The Custom scan step is called out as supporting the without docker in docker flow, but that is false; the Custom scan step still always requires docker in docker.

2024-10-17 18:02 UTC, tejakummarikuntla commented on docs/security-testing-orchestration/sto-techref-category/security-step-settings-reference.md
> +<DocVideo src="https://www.youtube.com/embed/x1NXBJaHF7U?si=gOrrOAE9p1DGEnLB" />
Thanks for the detailed feedback, @williamwissemann.
Removing the video for now.

2024-10-17 19:17 UTC, priteshchandaliya approved these changes

2024-10-19 07:37 UTC, merged