SCS: Document rule 2.3.9 for Harness pipelines and update release notes
harness/developer-hub pull request #8291
Opened 2024-10-15 11:33 UTC by tejakummarikuntla

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-17 05:28 UTC, pranaysap requested changes

2024-10-17 05:28 UTC, pranaysap commented on docs/software-supply-chain-assurance/manage-risk-and-compliance/standards-and-rule-definitions.md
> +| 1.2.16                    | Unrestricted usage of GitHub Actions allowed across the organization | GitHub   | pi Repository    | HIGH     |
pi Repository is wrong here

2024-10-17 05:29 UTC, pranay-harness requested changes

2024-10-17 05:29 UTC, pranay-harness commented on docs/software-supply-chain-assurance/manage-risk-and-compliance/standards-and-rule-definitions.md
> +| 1.2.16                    | Unrestricted usage of GitHub Actions allowed across the organization | GitHub   | pi Repository    | HIGH     |
pi repository is wrong here

2024-10-22 06:53 UTC, tejakummarikuntla commented on docs/software-supply-chain-assurance/manage-risk-and-compliance/standards-and-rule-definitions.md
> +| 1.2.16                    | Unrestricted usage of GitHub Actions allowed across the organization | GitHub   | pi Repository    | HIGH     |
Good catch, fixed it @pranay-harness

2024-10-22 17:14 UTC, pranay-harness approved these changes

2024-10-23 03:51 UTC, Debanitrkl approved these changes

2024-10-23 03:52 UTC, merged