feat: [IDP]: Added the release notes for v0.35
harness/developer-hub pull request #8311
Opened 2024-10-17 05:37 UTC by Debanitrkl

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-17 06:07 UTC, OrkoHunter requested changes

2024-10-17 06:07 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +- Added support for [configuring runtime inputs](https://developer.harness.io/docs/platform/variables-and-expressions/runtime-input-usage/#configure-execution-inputs) in the [IDP Stage](https://devel
I don't understand this. Can you give an example of what was not possible today and what users can do now?

For example, if had `<+input>` in my pipeline variable - now I can do `<+input>.something()`? We already had runtime input support in our stage, did we not?

2024-10-17 06:07 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +  - [Harness CCM Backstage Plugin](https://github.com/harness/backstage-plugins/tree/main/plugins/harness-ccm#harness-cloud-cost-management-plugin). [IDP-3758]
Pointing to external plugin docs doesn't work Deba - we need our own plugin docs. The GitHub README talks about API Key and Proxy - all of which is irrelevant today for let's say Intelliflo who wants to use this plugin today.

2024-10-17 06:07 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +  - [Simple Icons](https://github.com/dweber019/backstage-plugins/tree/main/plugins/simple-icons#simple-icons-plugin). [IDP-3763]
This is not a typical plugin. I think this deserves a more "Icons" page under Layout or "Links" page under Catalog where we talk about how to add icons to links using https://simpleicons.org/.

2024-10-17 06:07 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +- Fixed an issue where Harness Code URLs could not be properly parsed for the `// ` characters during the registration of a software component. [IDP-3820]
Account Level Repos had an issue. They are fixed now.

2024-10-17 06:07 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +- Fixed the issue with usage of `x-api-key` in [IDP APIs](https://developer.harness.io/docs/internal-developer-portal/api-refernces/public-api) headers. [IDP-3729]
@jenil-harness @sathish-soundarapandian @sandeepa-kv-jois So we had recommended users to use `x-api-token` for a while. Will there APIs break with this change? Do they need to move back to `x-api-key`?

https://harness.slack.com/archives/C066C0AH4DU/p1726540761125039?thread_ts=1726523192.334139&cid=C066C0AH4DU

2024-10-17 06:07 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +- Fixed the issue causing Timeout errors on Workflows execution page, even when the Pipeline execution was successful. [IDP-3580]
IMO this is the most important fix of all. Let's move to the top and add -

"We'll closely observe this but please report if you see this issue again."

2024-10-17 06:23 UTC, Debanitrkl commented on release-notes/internal-developer-portal.md
> +- Added support for [configuring runtime inputs](https://developer.harness.io/docs/platform/variables-and-expressions/runtime-input-usage/#configure-execution-inputs) in the [IDP Stage](https://devel
No this is different, it asks for input only when the stage is executed as part of the pipeline execution, not the whole pipeline. That means when click on Run it won't ask for any input. The details are given in the reference I have provided.

2024-10-17 06:26 UTC, sathish-soundarapandian commented on release-notes/internal-developer-portal.md
> +- Fixed the issue with usage of `x-api-key` in [IDP APIs](https://developer.harness.io/docs/internal-developer-portal/api-refernces/public-api) headers. [IDP-3729]
Yes. To whoever we have communicated this, we need to notify about this.
@jenil-harness I hope you have the list of customers who complained about this and we asked to use the work around.

2024-10-17 06:38 UTC, OrkoHunter commented on release-notes/internal-developer-portal.md
> +- Fixed the issue with usage of `x-api-key` in [IDP APIs](https://developer.harness.io/docs/internal-developer-portal/api-refernces/public-api) headers. [IDP-3729]
Okay, so it's a breaking change to a breaking change we made earlier to our Catalog APIs. Let's call it out as such. We'll have to notify Jeremy and a few customers who have reported this issue. It's linked from the JIRA.

2024-10-21 06:01 UTC, OrkoHunter approved these changes

2024-10-21 06:24 UTC, OrkoHunter approved these changes

2024-10-21 06:26 UTC, sandeepa-kv-jois requested changes

2024-10-21 06:26 UTC, sandeepa-kv-jois commented on release-notes/internal-developer-portal.md
> +
+ Scaffolder actions for Github is available now

2024-10-21 06:29 UTC, Debanitrkl commented on release-notes/internal-developer-portal.md
> +
Didn't add it on the release notes because our docs mentioned that the in-built scaffolder actions are always available as it was before the backstage upgrade. Should we add it under bug fixes.

2024-10-21 07:03 UTC, merged