[PL-58076]: SMP 0.22.0 RN
harness/developer-hub pull request #8350
Opened 2024-10-23 08:39 UTC by GokulBansal0

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: SMP 0.22.0 RN
* Jira/GitHub Issue numbers (if any): [PL-58076](https://harness.atlassian.net/browse/PL-58076)
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-27 17:38 UTC, pratmit submitted a review, later dismissed

2024-10-29 14:17 UTC, avaakash requested changes

2024-10-29 14:17 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +With MongoDB 5 reaching end-of-life (EOL), upgrading to MongoDB 6.x is recommended as an intermediate step for customers using an in-cluster MongoDB instance. This upgrade mitigates known CVEs and al
```suggestion
With MongoDB 5 reaching end-of-life (EOL), upgrading to MongoDB 6.x is recommended for customers using an in-cluster MongoDB instance. This upgrade mitigates known CVEs and aligns with MongoDB’s recommended upgrade path.
```

2024-10-29 14:17 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +1. Upgrade to at least SMP 0.17.0 or if you are running 0.16.0 or below version. This is required because Mongo doesn’t allow direct upgrade from Mongo 4.0 to Mongo 6.0
```suggestion
1. Upgrade to at least SMP 0.17.0 if you are running 0.16.0 or below version. This is required because Mongo doesn’t allow direct upgrade from Mongo 4.0 to Mongo 6.0
```

2024-10-29 14:17 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +  - The job is idempotent, meaning it will safely handle re-runs without unintended effects.
```suggestion
```

2024-10-29 14:17 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +  - For installations using helm, customers should avoid direct MongoDB upgrades from version 4.4 to 6.0 to ensure compatibility.
```suggestion
```

2024-10-29 14:17 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +To enable automatic FCV upgrade, include this job definition: (mongo-preupgradejob)[https://raw.githubusercontent.com/harness/helm-charts/refs/heads/main/src/harness/templates/mongo-preupgradejob.yam
```suggestion
To run FCV upgrade manually (required for ArgoCD users), include this job definition: (mongo-preupgradejob)[https://raw.githubusercontent.com/harness/helm-charts/refs/heads/main/src/harness/templates/mongo-preupgradejob.yaml]
```

2024-10-29 14:17 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +    enabled: true  # Set to false to disable
```suggestion
    enabled: false
```

2024-10-29 14:17 UTC, avaakash commented on release-notes/self-managed-enterprise-edition.md
> +
Add the Mongo upgrade to 6.0 ticket RN

2024-10-29 14:54 UTC, GokulBansal0 commented on release-notes/self-managed-enterprise-edition.md
> +
done

2024-10-29 17:36 UTC, avaakash approved these changes

2024-10-29 17:53 UTC, pratmit approved these changes
LGTM

2024-10-29 17:54 UTC, merged