Brijesh CI FAQ
harness/developer-hub pull request #8379
Opened 2024-10-24 21:50 UTC by brijeshjagani

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [X] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-24 21:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=8379) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=8379) before we can accept your contribution.<br/><hr/>**CX Engineering** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=8379) it.</sub>

2024-10-25 14:35 UTC, dewan-ahmed approved these changes
LGTM from CI. Will take 👍🏽 from PL.

2024-10-25 16:46 UTC, nofarblue requested changes

2024-10-25 16:46 UTC, nofarblue commented on kb/continuous-integration/continuous-integration-faqs.md
> +### How can we update the build status display name in Bitbucket to be more descriptive?
suggest creating a run step to execute API command, to update the status as they see fit

2024-10-25 16:46 UTC, nofarblue commented on kb/continuous-integration/continuous-integration-faqs.md
> +Yes, you can build multi-platform images using Harness CI/CD. The Build and Push to ECR plugin supports building multi-architecture images. However, when using the built-in build and push steps, you'
I think we shouldn't say it's supported with build and push - when customers are asking for multi-architecture they want to do it in one step execution.

2024-10-25 18:11 UTC, dewan-ahmed commented
@brijeshjagani pls address the MC under `kb/continuous-integration/continuous-integration-faqs.md` and Nofar's comments.

2024-11-25 01:04 UTC, closed without merging