Update cloud-cost-management-faqs.md
harness/developer-hub pull request #8473
Opened 2024-10-31 20:29 UTC by jmoon-harness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-10-31 20:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=8473) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=8473) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=8473) it.</sub>

2024-11-06 07:28 UTC, wei-harness requested changes

2024-11-06 07:28 UTC, wei-harness commented on docs/faqs/cloud-cost-management-faqs.md
> +You will need to set the correct timestamp "budgetMonthlyBreakdown": { "budgetBreakdown": "MONTHLY", "budgetMonthlyAmount": [ { "time": 1685577600000, "value": 20000.0, } , where time is set in Unix
@jmoon-harness it caused an error:

> Error: MDX compilation failed for file "/harness/docs/faqs/cloud-cost-management-faqs.md"
> Cause: Could not parse expression with acorn

---
The reason for this error is that the parser is expecting a JavaScript expression. 
If you just want braces instead of an expression, escape the opening: \\{. or use ` or `` to denote it as code.
If you do want an expression, make sure that it’s valid JavaScript and that it is an expression.

2024-11-06 15:53 UTC, jmoon-harness reviewed
Updated format

2024-11-06 15:53 UTC, jmoon-harness commented on docs/faqs/cloud-cost-management-faqs.md
> +You will need to set the correct timestamp "budgetMonthlyBreakdown": { "budgetBreakdown": "MONTHLY", "budgetMonthlyAmount": [ { "time": 1685577600000, "value": 20000.0, } , where time is set in Unix
Updated the format

2024-11-06 20:33 UTC, wei-harness requested changes

2024-11-06 20:33 UTC, wei-harness commented on kb/platform/harness-platform-faqs.md
> +There is the variable delegateSelectors that is set in each pipeline when a delegate is set. Outside of the pipeline itself there are not any other mention to call what delegate was being used other
@jmoon-harness 
there are still errors,
did you also see those errors during your local build?
> Error: MDX compilation failed for file "/harness/kb/platform/harness-platform-faqs.md"
> Cause: Unexpected character `+` (U+002B) before name, expected a character that can start a name, such as a letter, `$`, or `_`
> "line": 3385

2024-12-08 01:11 UTC, closed without merging

2024-12-08 01:11 UTC, bot2-harness commented
This pull request has been automatically closed due to 30 days of inactivity. If you believe this was done in error, please feel free to reopen the PR or reach out to the BT team for further assistance. Thank you for your contributions!