new releasse notes
harness/developer-hub pull request #8510
Opened 2024-11-06 13:42 UTC by joeyouss

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-11-06 18:07 UTC, Rohit-Kaliki requested changes

2024-11-06 18:07 UTC, Rohit-Kaliki commented on release-notes/cloud-cost-management.md
> +- AWS Payer Account ID Field Added: We’ve introduced the AWS Payer Account ID in the AWS fields dropdown for Perspectives and CC Rules. Only account IDs will be shown, excluding account names. [CCM-1
Can we call out CC as cost categories

2024-11-06 18:07 UTC, Rohit-Kaliki commented on release-notes/cloud-cost-management.md
> +- Increased Connector Limit for GCP: We raised the default limit to 6,000 for GCP cross combinations (target account * target region) to prevent unannounced system loads, aligning with the 200 accoun
Let's add that this is got Governance

2024-11-06 18:07 UTC, Rohit-Kaliki commented on release-notes/cloud-cost-management.md
> +- ‘Select All’ Option for Filtered Search: A new ‘Select All’ option allows users to select an entire filtered list, automatically updating based on the filtered options. [CCM-19794]
Again for what feature?

2024-11-06 18:07 UTC, Rohit-Kaliki commented on release-notes/cloud-cost-management.md
> +- Ad-Hoc Enforcement Runs: Users can now dry run or execute enforcements directly from the Enforcements list or details page, improving control over ad-hoc enforcement. [CCM-19438]
Can we move this to the top above bugs

2024-11-06 18:07 UTC, Rohit-Kaliki commented on release-notes/cloud-cost-management.md
> +- Ad-Hoc Enforcement Runs: Users can now dry run or execute enforcements directly from the Enforcements list or details page, improving control over ad-hoc enforcement. [CCM-19438]
This should be a feature

2024-11-07 06:27 UTC, joeyouss commented on release-notes/cloud-cost-management.md
> +- AWS Payer Account ID Field Added: We’ve introduced the AWS Payer Account ID in the AWS fields dropdown for Perspectives and CC Rules. Only account IDs will be shown, excluding account names. [CCM-1
done

2024-11-07 06:27 UTC, joeyouss commented on release-notes/cloud-cost-management.md
> +- Increased Connector Limit for GCP: We raised the default limit to 6,000 for GCP cross combinations (target account * target region) to prevent unannounced system loads, aligning with the 200 accoun
done

2024-11-07 06:31 UTC, joeyouss commented on release-notes/cloud-cost-management.md
> +- ‘Select All’ Option for Filtered Search: A new ‘Select All’ option allows users to select an entire filtered list, automatically updating based on the filtered options. [CCM-19794]
done

2024-11-07 06:32 UTC, joeyouss commented on release-notes/cloud-cost-management.md
> +- Ad-Hoc Enforcement Runs: Users can now dry run or execute enforcements directly from the Enforcements list or details page, improving control over ad-hoc enforcement. [CCM-19438]
done

2024-11-07 17:10 UTC, iamanmolm commented on release-notes/cloud-cost-management.md
> +- New Resource Name Column in Recommendations View: A new column, Resource Name (No drilldown) has been added to the Governance recommendations view. This allows users to group Governance Recommendat
“specific rule in Dashboards.”

2024-11-07 17:12 UTC, iamanmolm approved these changes

2024-11-07 17:40 UTC, merged