Added Port Forwarding Docs
harness/developer-hub pull request #8712
Opened 2024-11-27 09:31 UTC by khushisharmaharness

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-11-27 09:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=8712) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=8712) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=8712) it.</sub>

2024-11-27 12:27 UTC, rohanmaharjan100 submitted a review, later dismissed

2024-12-02 18:43 UTC, manishas approved these changes

2024-12-03 06:19 UTC, khushisharmaharness commented
Hi @wei-harness 
Need a quick review and approval for this PR. Thanks!

2024-12-06 19:53 UTC, wei-harness requested changes

2024-12-06 19:53 UTC, wei-harness commented on docs/cloud-development-environments/deep-dive-into-gitspaces/lifecycle-of-gitspaces.md
> +<img width="650" src="https://github.com/user-attachments/assets/e6a6f759-7165-4d09-9dc9-21cb6d5d3049"/>
@khushisharmaharness please notice it's suggested to add an image in markdown doc with the MarkDown syntax.
e.g.: `![Tux, the Linux mascot](/assets/images/tux.png)`
see more at https://www.markdownguide.org/basic-syntax/#images-1

2024-12-06 19:54 UTC, wei-harness approved these changes

2024-12-06 19:55 UTC, wei-harness commented on docs/cloud-development-environments/deep-dive-into-gitspaces/lifecycle-of-gitspaces.md
> +<img width="650" src="https://github.com/user-attachments/assets/e6a6f759-7165-4d09-9dc9-21cb6d5d3049"/>
I see you might want to set a specific width for the image

2024-12-09 06:02 UTC, merged