CDS-45268-tas-swimlane
harness/developer-hub pull request #874
Opened 2023-03-06 13:11 UTC by roshnisarangadharan

added tas swimlane quickstart information

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-03-06 20:25 UTC, michaelcretzman requested changes
great start, but it needs work. There are some technical issues with the manifests.
let's meet and discuss.

2023-03-06 20:25 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +  <TabItem value="Blue Green" label="Blue Green">
The problem here is that you need routes for Blue Green to work and we didn't tell them to add a manifest with routes in it.

So, we could add that here.

I describe it in the FG docs: https://developer.harness.io/docs/first-gen/continuous-delivery/pcf-deployments/create-a-blue-green-pcf-deployment#step-1-specify-the-tas-service-routes

There's actually a lot you can borrow from that doc.

I think this need a brief summary of what a BG deployment is in TAS.

2023-03-06 20:25 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +  <TabItem value="Rolling" label="Rolling" default>
I think this need a brief summary of what a rolling deployment is in TAS.

2023-03-06 20:25 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +  <TabItem value="Canary" label="Canary">
I think this need a brief summary of what a canary deployment is in TAS.

See https://developer.harness.io/docs/first-gen/continuous-delivery/pcf-deployments/create-a-canary-pcf-deployment#review-app-resizing-in-canary-deployments

2023-03-06 20:25 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +## Step 5: Deploy and review
```suggestion
## Deploy and review
```

2023-03-07 07:20 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +* Create a TAS project for your new CD pipeline. Ensure that you add the **Continuous Delivery** module to the project. Go to [Create Organizations and Projects](../../../platform/organizations-and-p
it worked for me locally

2023-03-07 12:57 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +   [![](./static/kubernetes-cd-quickstart-83.png)](./static/kubernetes-cd-quickstart-83.png)
Engineering says any delegate is ok. They prefer Kubernetes because we have to add some CF CLI commands to the delegate.yaml. I did see the new UI. There is also an option to switch to the old view where this screenshot is relevant. I'll update the image anyway to match the latest UI. Or may be skip few screenshots that don't add a lot of value.

2023-03-16 18:42 UTC, deepakbolangady requested changes
I have looked at most of the document. If I get a chance to look at the rest of the document before you have to publish it, I will add more comments. But don't wait. Please apply the feedback to the rest of the document. That should address most of the issues I saw, which were minor anyway. Good document!

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +4. Apply the profile to the delegate profile and check logs.
```suggestion
4. Apply the profile to the delegate profile and check the logs.
```

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Once you have created a service, it is persistent and can be used throughout the stages of this or any other pipeline in the project.
```suggestion
Services are persistent and can be used throughout the stages of this pipeline or any other pipeline in the project.
```
("pipeline" is not required but the original construction sometimes needs to be read twice.)

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +    3. Enter the following in the `manifest` file, then click **Save**.
```suggestion
    1. Select **New**, select **New Folder**, enter a folder name, and then select **Create**.
    2. Select the new folder, select **New**, select **New File**, and then enter a file name. For example, enter `manifest`.
    3. Enter the following in the `manifest` file, and then click **Save**.
```

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +11. Select **AutoScaler.yaml** and repeat step 6.1 to 6.2 to create an `autoscaler` file and enter the following information.
```suggestion
11. Select **AutoScaler.yaml** and repeat steps 6.1 and 6.2 to create an `autoscaler` file. Then, enter the following information:
```

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +9.  Once the test connection succeeds, select **Continue**.
```suggestion
9.  After the test connection succeeds, select **Continue**.
```

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +    1.  Enter an **Artifact Source Name**
```suggestion
    1.  Enter an **Artifact Source Name**.
```
(Prefer "In **Artifact Source Name**, enter a name for the artifact source. That way, you avoid using the UI element's name to spell out an instruction.)

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +    6.  Enter the image tag artifact name.
What's the image tag artifact name? Is that what it's called? Or is there a better way to write it? Three adjectives is one too many, no?

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +2. Enter the environment name **TAS tutorial** and select **Pre-Production**.
```suggestion
2. Enter the name **TAS tutorial** and select **Pre-Production**.
```
The env does not exist yet.

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +6. Enter a name, and verify if **Tanzu Application Type** deployment type is selected.
```suggestion
6. Enter a name, and then verify that the selected deployment type is **Tanzu Application Type**.
```
("Application type deployment type" is a mouthful. Does my suggestion work?)

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +8. In **Organization**, select the TAS org where you want to deploy.
General comment about "where": check whether "in which" is better. In this case, an organization is not a location. It's a container. "In which" seems appropriate. I was tempted to make the same observation when I read "repository where" earlier. 
Also, the sentence seems to end abruptly. Can we write "select the TAS org that you want to use for the deployment"? 
(apply globally, including the next step)

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +The TAS workflow performing a basic deployment takes your Harness TAS service and deploys it on your TAS infrastructure definition.
```suggestion
The TAS workflow for performing a basic deployment takes your Harness TAS service and deploys it on your TAS infrastructure definition. 
```
Correct? I felt something was missing. Ignore if I did not parse it correctly.

2023-03-16 18:42 UTC, deepakbolangady commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +6. Add a **App Rollback** step to your stage if you want to rollback to an older version of the application in case of deployment failure.
```suggestion
6. Add an **App Rollback** step to your stage if you want to roll back to an older version of the application in case of deployment failure.
```

2023-03-17 05:49 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +6. Enter a name, and verify if **Tanzu Application Type** deployment type is selected.
should we use and and then together. In my previous orgs, I used to use either and or ',then'. What do you think?

2023-03-20 16:39 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +* Connect Harness with a public image hosted on artifactory.
Capitalised A in artifactory

2023-03-21 06:48 UTC, shylajasun submitted a review, later dismissed

2023-03-21 08:00 UTC, RishabhGupta34 commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +    4. **Desired Instances - Old Version** - Set the number or percentage of instances for the previous version of the application you want to keep. By default, the application will downsize to the s
`By default, the application will downsize to the same number as the number of new application instances` 
This is not the actual logic, it is:
If left empty, the count will be the diff. between the max instance count possible(from manifest/match running instance) and the number of new application instances.
^Same for all strategies

2023-03-21 08:00 UTC, RishabhGupta34 commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +The blue/green deployment deploys the applications using the temporary route first using the **App Setup** configuration. Next, in the **App Resize** configuration, Harness maintains the number of in
This is not 100% always, we populate 100% by default if we select strategy, but it depends on the number defined by the user

2023-03-21 08:00 UTC, RishabhGupta34 commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +   The rollback step in the blue/green deployment contains two default steps, **Swap Routes** and **App Rollback**.
This was CG behaviour, in NG we only have `Swap Rollback` step which will do the rollback for BG strategy. We don't use `App Rollback` for BG in NG

2023-03-21 10:56 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Currently, CF CLI v7 support is behind the feature flag `CF_CLI7`. Contact [Harness Support](mailto:support@harness.io) to enable CF CLI v7 support.
Done

2023-03-21 11:32 UTC, RishabhGupta34 submitted a review, later dismissed

2023-03-22 04:11 UTC, SmritiSatya approved these changes

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +The TAS canary deployment is a phased approach to deploy application instances gradually, ensuring the stability of a small percentage of instances before rolling out to your desired instance count.
Is it Canary Deployment or canary deployment?

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +## Next Steps
Next steps

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Now the pipeline stage is complete and you can deploy.
Now the pipeline stage is complete and can be deployed.

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +       Additional routes has two uses in blue/green deployments.
Additional routes have two uses in blue or green deployments.

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Harness TAS blue/green deployments use the route(s) in the TAS manifest and a temporary route you specify in the deployment configuration.
Can we say blue or green instead of blue/green? (global)

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +    6. **Temporarty Routes** - Add temporary routes in addition to additional routes.
Temporary

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Now the pipeline stage is complete and you can deploy.
Now the pipeline stage is complete and can be deployed. OR Now the pipeline stage is complete and ready to be deployed.

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Now the pipeline stage is complete and you can deploy.
Now the pipeline stage is complete and can be deployed.

2023-03-22 04:11 UTC, SmritiSatya commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +The deployment was successful.
Some step or message that indicates that the deployment was successful? Can we rephrase this statement?

2023-03-22 05:19 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +* Specify the manifest to use for the app.
done

2023-03-22 05:24 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Harness services represent your microservices or applications. You can add the same service to as many stages as you need. Services contain your artifacts, manifests, config files, and variables. For
it is config files

2023-03-22 05:27 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +The TAS canary deployment is a phased approach to deploy application instances gradually, ensuring the stability of a small percentage of instances before rolling out to your desired instance count.
canary deployment. Made the change.

2023-03-22 05:28 UTC, roshnisarangadharan commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Harness TAS blue/green deployments use the route(s) in the TAS manifest and a temporary route you specify in the deployment configuration.
it is blue/green only

2023-03-22 10:39 UTC, SmritiSatya submitted a review, later dismissed

2023-03-22 12:29 UTC, deepakbolangady approved these changes
Approving with the assumption that you have been able to incorporate most comments and have a plan for those that you could not incorporate this time round.

2023-03-22 16:46 UTC, michaelcretzman submitted a review, later dismissed
approved with suggestions

2023-03-22 16:46 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +## Create a Harness service
```suggestion
## Create the Harness TAS service
```

2023-03-22 16:46 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +## Define your target environment
```suggestion
## Define the TAS target environment
```

2023-03-22 16:46 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +## Add a deployment step
Making this suggestion because the steps are added automatically. They don't have to add anything.

2023-03-22 16:46 UTC, michaelcretzman commented on docs/continuous-delivery/onboard-cd/cd-quickstarts/tanzu-app-services-quickstart.md
> +Harness TAS blue/green deployments use the route(s) in the TAS manifest and a temporary route you specify in the deployment configuration.
we use "blue green".

2023-03-23 14:27 UTC, javeeth-basha approved these changes

2023-03-23 14:32 UTC, merged