gitops by environment docs
harness/developer-hub pull request #8767
Opened 2024-12-03 23:12 UTC by jenniferopal

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \_gitops by environment docs for db devops
* Jira/GitHub Issue numbers (if any): \_DBOPS-428
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [X] Successful preview build.
- [X] Code owner review.
- [X] No merge conflicts.
- [X] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-12-17 07:03 UTC, archit-harness commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +2. **Environment-Specific Configurations**: Each environment (dev, staging, prod) can have different database configurations, managed independently through separate branches.
@stephenatwell @AnshuH while this is true, we cant manage db instance currently using GitOps right as connector configuration customer to has to come to harness and add it.
Only database changes applied on that env is different

2024-12-17 07:08 UTC, archit-harness commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +## Conclusion
@AnshuH @stephenatwell seems like we promote trunk based development rather than branch based? which i think should be opposite as i don't see any cons added to this approach as well as seems complex process.
Mentioning env based variable whereas there is no such currently as of yet.

2025-01-15 14:38 UTC, jenniferopal commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +2. **Environment-Specific Configurations**: Each environment (dev, staging, prod) can have different database configurations, managed independently through separate branches.
@archit-harness I'll remove this detail from the doc.

2025-01-15 14:39 UTC, jenniferopal commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +## Conclusion
I'll remove this detail too, @archit-harness .

2025-01-30 06:25 UTC, hemanthbsridhar requested changes

2025-01-30 06:25 UTC, hemanthbsridhar commented on docs/database-devops/use-database-devops/gitops-by-env.md
> + - storing configurations, database schemas, and migration scrips in Git repos,
spelling mistake : scripts*

2025-01-30 06:41 UTC, archit-harness approved these changes, later dismissed

2025-01-30 16:13 UTC, hemanthbsridhar requested changes

2025-01-30 16:13 UTC, hemanthbsridhar commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +5. **Audit Trail**: Each branch provides a clear history of changes, enhancing traceability in Harness Database DevOps.
@jenniferopal audit trail is not complete yet. Do you feel that we should add this after the feature is complete?

2025-01-30 16:18 UTC, jenniferopal commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +5. **Audit Trail**: Each branch provides a clear history of changes, enhancing traceability in Harness Database DevOps.
If it's not available yet, I can definitely remove for now and we can add it back once it's available?

2025-02-05 19:05 UTC, stephenatwell commented on docs/database-devops/use-database-devops/gitops-by-env.md
> +---
we should update the URL to be 'Gitops in Database DevOps'

2025-02-05 19:07 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +4. **Easier Rollbacks**: Harness Database DevOps can quickly roll back changes by reverting to a previous commit in the environment's branch.
I don't believe we have built this yet/ I do not believe statement #4 is true. @archit-harness do you know a way to do this that I don't? (if so, lets doc it).

2025-02-05 19:08 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +5. **Audit Trail**: Each branch provides a clear history of changes, enhancing traceability in Harness Database DevOps.
this reads like it is referring to the audit trail provided by git itself.... so I think this bullet is ok personally.

2025-02-05 19:10 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> + 4. **Overhead**: Maintaining separate branches for each environment requires more resources and management.
5. (this is a big one) it is difficult to have a set of changes that NEVER reaches all branches because merging between branches will pick up all changes. If you have development/ staging only changes (such as test data), you can still restrict them through the use of the 'context' parameter on a database instance, even when using branch per environment.

2025-02-05 19:13 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> + 3. In your Git repository, you will create pull requests that merge changes from your development branch into your staging branch. When you merge a pull request, Harness will automatically detect th
the steps need to include setting up the pipeline trigger that would cause Harness to detect that something changed in git....

2025-02-05 19:13 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> + 2. In your schema configuration, specify the branch for each environment. You will specify the branch of the code from which you want to deploy.
this is in the db instance configuration, not the schema configuration.

2025-02-05 19:14 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> + 2. In your schema configuration, specify the branch for each environment. You will specify the branch of the code from which you want to deploy.
@jenniferopal have we tested this configuration procedure to ensure it is working and not missing any steps? Asking due to my last two comments. if not, please ensure that happens before you finalize the doc (that should be happening with all docs...)

2025-02-05 19:15 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> + 4. When a change is committed (e.g., a merge from development to staging), the trigger will initiate the deployment pipeline for that specific environment.
if we had created it I agree.

2025-02-05 19:16 UTC, stephenatwell commented on docs/database-devops/use-database-devops/environment-by-branch.md
> + 5. In your deployment pipeline, define the steps that specify which database changes to apply based on the environment.
Assume the user has never used harness before..... How do they do this. I suggest providing step-by step guidance to the user on how to get this information from the git trigger, and how to pass it into the 'apply' step.

2025-02-05 19:18 UTC, stephenatwell commented on docs/database-devops/use-database-devops/gitops-by-env.md
> +Choose the approach that best aligns with your existing development practices and organizational needs. You can learn more about [Environment by Branch](./environment-by-branch.md) and [Trunk-Based D
suggestion, add something like 'if you are not currently using an approach, Harness reccomends leveraging trunk based development'

2025-02-05 19:20 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Create environment-specific pipelines tailored to the needs of each deployment stage.
or alternately make 'database instance' and input to a pipeline that is not environment specific.

2025-02-05 19:21 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Configure deployment triggers to automate the deployment process.
how? perhaps link to relevant content.

2025-02-05 19:22 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +    - Set up context-specific variables to tailor deployments to each environment.
how? perhaps link to relevant content.

2025-02-05 19:22 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +    - Define contexts for different environments (e.g., development, QA, production).
how? perhaps link to relevant content.

2025-02-05 19:22 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Set up approval workflows to ensure changes are reviewed before deployment.
how? perhaps link to relevant content.

2025-02-05 19:24 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Set up approval workflows to ensure changes are reviewed before deployment.
maybee this is the next sectionl.

2025-02-05 19:27 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +## Setting Up Trunk-Based Development
this section should be providing step by step guidance that is adequate for a user who has never used harness before to follow without help. Where useful, it can link to external documentation that provides more detail about any given task it discusses. It should provide enough instruction that a user can setup any of the above scenarios based on only information in this section, or in other harness documentation to which it directs them for more information.

2025-02-05 19:28 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Create database instances for each environment to support isolated testing and deployment.
I believe we have docs on how to do them. perhaps add 'more info' at the end to link to those.

2025-02-05 19:28 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Configure deployment pipelines that align with your development workflow.
How? perhaps link to relevant content.

2025-02-05 19:28 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Set up environment-specific variables to ensure that deployments are tailored to the needs of each environment.
How? perhaps link to relevant content.

2025-02-05 19:29 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Define deployment strategies that align with your organization's release management practices.
How? you gave me two options above. How do I configure each?

2025-02-05 19:30 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Use Harness Database DevOps pipelines to control the flow of deployments, ensuring that changes are applied in a controlled manner.
how? I think you want something like 'heres how to configure a trigger' and then 'Now when you commit to 'main' the pipeline will run, and deploy your changes...

2025-02-05 19:30 UTC, stephenatwell commented on docs/database-devops/use-database-devops/trunk-based-development.md
> +   - Monitor deployments through the Harness interface, providing visibility into the status and success of each deployment.
perhaps link to the doc on how to understand changes across environments?

2025-02-13 12:55 UTC, archit-harness commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +4. **Easier Rollbacks**: Harness Database DevOps can quickly roll back changes by reverting to a previous commit in the environment's branch.
No we have not built this feature yet, to be designed how we want to make it look for customers

2025-02-20 08:13 UTC, rohanmaharjan100 commented
Hey, this PR has been open for a while. Please coordinate with the reviewers to get it approved by February 28th; otherwise, we will have to close it.

2025-03-04 08:52 UTC, ankittiwari-harness commented on docs/database-devops/use-database-devops/environment-by-branch.md
> +4. **Easier Rollbacks**: Harness Database DevOps can quickly roll back changes by reverting to a previous commit in the environment's branch.
removed the line

2025-03-04 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=8767) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=8767) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: jenniferopal<br/>:white_check_mark: rohanmaharjan100<br/>:x: ankittiwari-harness<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=8767) it.</sub>

2025-04-03 14:08 UTC, dewan-ahmed commented
@stephenatwell since the author of the PR is no longer with Harness, let's close this PR?

2026-04-16 16:08 UTC, closed without merging