updating codeowners for ff and db devops
harness/developer-hub pull request #8802
Opened 2024-12-05 23:08 UTC by jenniferopal

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \ updating codeowners for ff and db devops
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [x] Successful preview build.
- [x] Code owner review.
- [x] No merge conflicts.
- [x] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-12-06 00:07 UTC, pratmit commented on package.json
> +    "@docusaurus/core": "^3.6.3",
Why are these changes in the json file?

2024-12-06 00:07 UTC, pratmit commented on package.json
> +    "@docusaurus/core": "^3.6.3",
@wei-harness can you confirm on the above?

2024-12-06 00:32 UTC, wei-harness requested changes

2024-12-06 00:32 UTC, wei-harness commented on yarn.lock
@jenniferopal please don't commit the .lock files

2024-12-06 00:32 UTC, wei-harness commented on package.json
> +    "@docusaurus/core": "^3.6.3",
same question, @jenniferopal,
We'll handle the dependencies in a more cautious manner,
If there are any features you require from the newer version of Docusaurus, please let us know.

2024-12-06 23:53 UTC, jenniferopal commented on yarn.lock
My apologies. I didn't realise my updates also merged with the branches. I'll fix that.

2024-12-09 19:35 UTC, pratmit approved these changes

2024-12-10 08:16 UTC, wei-harness approved these changes

2024-12-10 18:23 UTC, merged