Enhancing env type built-in variable documentation
harness/developer-hub pull request #881
Opened 2023-03-06 23:06 UTC by gacerioni

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [X] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [X] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-03-06 23:19 UTC, michaelcretzman requested changes
please incorp the suggestions and I will merge.

2023-03-06 23:19 UTC, michaelcretzman commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +- Production
```suggestion
- `PreProduction`
- `Production`
```

2023-03-06 23:19 UTC, michaelcretzman commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
>  The environment type, such as production or non-production.
```suggestion
The environment type, such as `Production` or `PreProduction`.
```

2023-03-06 23:19 UTC, michaelcretzman commented on docs/platform/12_Variables-and-Expressions/harness-variables.md
> +You can evaluate it with JEXL expressions in the **Conditional Execution** Settings:
```suggestion
You can evaluate the expression using JEXL in the **Conditional Execution** settings of steps or stages:
```

2023-03-06 23:21 UTC, gabrielcerioni approved these changes

2023-03-06 23:26 UTC, michaelcretzman approved these changes

2023-03-07 13:00 UTC, gabrielcerioni commented
Thanks, Michael!

2023-03-07 21:05 UTC, merged