Added the Images and Updated a text for the SBOM Drift
harness/developer-hub pull request #8911
Opened 2024-12-17 09:40 UTC by lavakush07

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: Added the images for the SBOM-Drift 
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-12-17 09:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/harness/developer-hub?pullRequest=8911) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/harness/developer-hub?pullRequest=8911) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/harness/developer-hub?pullRequest=8911) it.</sub>

2024-12-17 11:43 UTC, tejakummarikuntla requested changes
@lavakush07 , we might need to update the content aligning to the changes on drift feature. For now we are good.

Please revert the changes on `yarn.lock`, it's preferred to keep it untouched.

2024-12-18 00:15 UTC, wei-harness requested changes

2024-12-18 00:15 UTC, wei-harness commented on yarn.lock
@lavakush07 please don't commit .lock files

2024-12-18 03:25 UTC, lavakush07 commented on yarn.lock
Yeah sure @wei-harness

2024-12-19 19:44 UTC, wei-harness approved these changes

2024-12-19 19:44 UTC, wei-harness commented on docs/software-supply-chain-assurance/static/SBOM-Drift-Tag.png
@lavakush07 suggest using kebab-case with all lowercase letters for naming static files.
-
@rohanmaharjan100 would you please add a GH action rule for this case?

2024-12-23 09:43 UTC, closed without merging

2024-12-23 09:44 UTC, lavakush07 commented
Facing the issues while adding images. Will be creating a new PR.