Updated the SBOM Drift
harness/developer-hub pull request #8948
Opened 2024-12-23 10:20 UTC by lavakush07

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-12-23 10:53 UTC, rohanmaharjan100 commented
@lavakush07 
![image](https://github.com/user-attachments/assets/e6920f07-4440-4383-abe8-fab9f33ccf88)

2024-12-23 10:56 UTC, lavakush07 commented
> @lavakush07 ![image](https://private-user-images.githubusercontent.com/139572165/398139940-e6920f07-4440-4383-abe8-fab9f33ccf88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NTE1ODgsIm5iZiI6MTczNDk1MTI4OCwicGF0aCI6Ii8xMzk1NzIxNjUvMzk4MTM5OTQwLWU2OTIwZjA3LTQ0NDAtNDM4My1hYmU4LWZhYjlmMzNjY2Y4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyM1QxMDU0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MDQwOGVlZDMwMWVlYmQwMzYyNGU5MGVjNzUyMTY3YWU0MTc1OTZiMDZiNWRiYTYxYjlmYTcxZDE3MDFkNzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dE9hudYWzyhIFt1ok4GJ9QaUPkA3CPT2oalA-XSnxcg)

But it is working fine on local. The paths are correct.

2024-12-23 11:05 UTC, rohanmaharjan100 commented
@lavakush07  I think you forgot to add images to the static folder. Please make sure static folder has the required images.

2024-12-23 11:10 UTC, rohanmaharjan100 commented on docs/software-supply-chain-assurance/sbom/sbom-drift.md
> +<DocImage path={require('../static/initiate-drift-analysis.png')} width="90%" height="60%" title="Click to view full size image" />
The case for the image name appears incorrect. It should be: `../static/Initiate-Drift-Analysis.png`.

2024-12-23 11:10 UTC, rohanmaharjan100 reviewed
case for the image name looks wrong. It should be =>docs/software-supply-chain-assurance/static/Initiate-Drift-Analysis.png

2024-12-23 15:36 UTC, lavakush07 commented
> case for the image name looks wrong. It should be =>../static/Initiate-Drift-Analysis.png

In my local it is the same. I pushed the changes with the correct path. 
<img width="246" alt="Screenshot 2024-12-23 at 9 01 20 PM" src="https://github.com/user-attachments/assets/e627532b-e40d-4482-8751-fa8c8ecc17fe" />

2024-12-23 17:57 UTC, wei-harness requested changes

2024-12-23 17:57 UTC, wei-harness commented on docs/software-supply-chain-assurance/sbom/sbom-drift.md
> +<DocImage path={require('../static/initiate-drift-analysis.png')} width="90%" height="60%" title="Click to view full size image" />
suggest to use kebab case for static files, e.g.: `initiate-drift-analysis.png`, please rename the png file instead.
@rohanmaharjan100 please add a GHA rule for it.

2024-12-24 17:14 UTC, tejakummarikuntla approved these changes

2024-12-26 19:06 UTC, wei-harness approved these changes

2024-12-27 06:11 UTC, merged