docs: [AH-809]: Add AH troubleshooting section and horizontal sidebars
harness/developer-hub pull request #8950
Opened 2024-12-23 13:10 UTC by richardblack-Harness

## Description

* Add new AH Troubleshooting doc section, as well as horizontal sidebar items for various topics depending on usage stage:
- New to Artifact Registry?
- Use Artifact Registry
- Troubleshooting

* [JIRA](https://harness.atlassian.net/browse/AH-809)

### Screenshot / Preview
https://github.com/user-attachments/assets/4e768663-e5db-4dcd-9314-2aa6f6c7bc61

PRs must meet these requirements to be merged:
- [x] Successful preview build.
- [x] Code owner review.
- [x] No merge conflicts.
- [x] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-12-23 13:50 UTC, richardblack-Harness commented
@lenasano would you mind reviewing this, please?
It's nearly there, but I noticed I've lost the Artifact Registry landing page component at the top of the sidebar.
![CleanShot 2024-12-23 at 13 47 15](https://github.com/user-attachments/assets/6bf9d07c-ea17-4531-802d-3376be83a702)

2024-12-23 17:44 UTC, wei-harness requested changes
Sidebar is missing on AR landing page:
https://67696351d3b34058eebb7e4b--harness-developer.netlify.app/docs/artifact-registry
<img width="1794" alt="Screenshot 2024-12-23 at 9 42 54 AM" src="https://github.com/user-attachments/assets/a75cd6d2-d639-40f1-a22d-c9bea919a476" />

2025-01-02 08:08 UTC, richardblack-Harness commented
Morning @wei-harness, the build you referenced is an earlier one. This issue was fixed in newer commits. 
Here is the latest build: https://67697ceca794023c2f47c0b1--harness-developer.netlify.app/

2025-01-06 18:13 UTC, wei-harness approved these changes

2025-01-07 12:46 UTC, closed without merging