SCS: Fixed the Manage-Access-Control-Flow
harness/developer-hub pull request #8963
Opened 2024-12-25 14:30 UTC by lavakush07

Thanks for contributing to the Harness Developer Hub! Our code owners will review your submission.

## Description

* Please describe your changes: \__________________________________
* Jira/GitHub Issue numbers (if any): \______________________________
* Preview links/images (Internal contributors only): \__________________

## PR lifecycle

We aim to merge PRs within one week or less, but delays happen sometimes.

If your PR is open longer than two weeks without any human activity, please tag a [code owner](https://github.com/harness/developer-hub/blob/main/.github/CODEOWNERS) in a comment.

PRs must meet these requirements to be merged:

- [ ] Successful preview build.
- [ ] Code owner review.
- [ ] No merge conflicts.
- [ ] Release notes/new features docs: Feature/version released to at least one prod environment.

2024-12-26 05:51 UTC, pranay-harness commented
This section needs to be updated

> 
> For the Organization level, open the same account settings and proceed to Organizations. Choose your organization and under Organization Level Access Control and Audit Trail, select Access Control. Here, configure the roles and permissions at the organization level in a manner similar to the account level process.
> To set roles and permissions at the Project level, navigate to the Project section from the module navigation bar, and select Access Control. Follow similar steps as above to establish the roles and permissions for the project level.

2024-12-26 06:01 UTC, lavakush07 commented
> This section needs to be updated
> 
> > For the Organization level, open the same account settings and proceed to Organizations. Choose your organization and under Organization Level Access Control and Audit Trail, select Access Control. Here, configure the roles and permissions at the organization level in a manner similar to the account level process.
> > To set roles and permissions at the Project level, navigate to the Project section from the module navigation bar, and select Access Control. Follow similar steps as above to establish the roles and permissions for the project level.

Sure, Will update this section

2024-12-26 06:59 UTC, tejakummarikuntla requested changes

2024-12-26 06:59 UTC, tejakummarikuntla commented on docs/software-supply-chain-assurance/ssca-access-control.md
> +![SCS RBAC](./static/access-control.png "SCS RBAC")
Use Doc tags for images

2025-01-03 11:38 UTC, pranay-harness approved these changes
LGTM

2025-01-06 05:26 UTC, tejakummarikuntla approved these changes

2025-01-06 05:26 UTC, merged