New topic for audit streaming.
harness/developer-hub pull request #933
Opened 2023-03-10 04:19 UTC by rashminandasahoo

# Harness Developer Pull Request
Thanks for helping us make the Developer Hub better. The PR will be looked at
by the maintainers. 

## What Type of PR is This?

- [ ] Issue
- [ ] Feature
- [ ] Maintenance/Chore

If tied to an Issue, list the Issue(s) here:

* *Issue(s)*

## House Keeping
Some items to keep track of. Screen shots of changes are optional but would help the maintainers review quicker. 

- [ ] Tested Locally
- [ ] *Optional* Screen Shoot.

2023-03-13 04:22 UTC, nishantsaini20 commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +6. After the connection test is successful, select **Finish**.
The test connection currently doesn't account the bucket used.Also it is doing test connection for the connector used and not doing the actual test connection for streaming destination i.e. the bucket in AWS.

2023-03-13 04:24 UTC, nishantsaini20 requested changes

2023-03-13 04:24 UTC, nishantsaini20 commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +3. You can pause audit streaming, preventing any new audit events from being streamed to the configured endpoint by setting the status to **Inactive**.
Currently it will start streaming from where it was paused. In future we are going to limit it to a threshold value. As an e.g. it can be paused (inactive) for a max of duration of X hrs. If it is marked active within X hrs from marking inactive then the streaming will start from where it was paused. else it will start for the time its marked active.

2023-03-13 04:24 UTC, nishantsaini20 commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +- Delete: You can delete the audit stream destination, which will clear any data relating to the audit stream and prevent any new audit events from being streamed.
Th history of batched is currently not deleted. So if a used creates a streaming destination again with same identifier then it will pick the state which is already present in db. We need to discuss and close on the behaviour of delete.

2023-03-13 04:24 UTC, nishantsaini20 commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +6. After the connection test is successful, select **Finish**.
The test connection currently doesn't account the bucket used.Also it is doing test connection for the connector used and not doing the actual test connection for streaming destination i.e. the bucket in AWS.

2023-03-20 03:20 UTC, nishantsaini20 approved these changes

2023-03-20 04:52 UTC, SudheendraKatte approved these changes
Approved with couple of suggestions.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +- Store more than 2 years worth of auditing data, which is the maximum amount of data that Harness keeps for your accounts.
```suggestion
- Store more than 2 years audit data, which is the maximum amount of data that Harness keeps for your accounts.
```

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +You can configure the audit stream from the **Audit Log Streaming** option in **Audit Trail**.
As this is part of the steps, can we just say "To add a streaming destination in Harness:"

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +5. Harness automatically populates the Id for the destination. You can choose to retain the Id or modify it.
Harness populates the destination's Id automatically. You can retain or change the Id.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +   This is where Harness will write all the streaming records.
Harness writes all the streaming records to this destination.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +5. Select Save and Continue.
```suggestion
5. Select **Save** and **Continue**.
```

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +   AWS buckets are not taken into account during the test connection. Also, it tests the connector used without testing the bucket.
Harness does not consider AWS buckets while testing the connection. Only the connector is tested.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +1. After you configure the streaming destination, it appears in the list of destinations in **Audit Log Streaming**.
"The streaming destination gets configured and appears in the list of destinations under **Audit Log Streaming**. By default setting of this destination is inactive."

Please move this to Step 6 above (this is the result of that step).

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +2. To activate streaming to this destination, toggle the status to **Active** besides the streaming destination.
Please consider if you can make this section a single paragraph instead of a list.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +   After you activate the destination, Harness starts writing audit logs in the destination.
Harness starts writing audit logs after the destination is activated.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +   Post that every 30 mins audit logs are streamed.
Harness streams audit logs to destination at 30-minute intervals.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +3. You can pause audit streaming, preventing any new audit events from being streamed to the configured endpoint by setting the status to **Inactive**.
By pausing audit streaming, you can prevent new audit events from being transmitted to the configured endpoint. To do this, set the streaming destination status to **Inactive**.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +   Harness streams audit logs from where it was paused later when you reactivate such a streaming destination.
When you reactivate the streaming destination, Harness starts streaming the audit logs from the point where it was paused.

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +You can change the audit stream configuration by clicking three dots beside the stream destination. This will open a pop-up menu with the following options:
1. stream destination or streaming destination? Please review.

2. A pop-up menu appears with the followoing options:

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +- Edit: You can select a different streaming destination or make changes to the configured destination.
```suggestion
- **Edit**: Select a different streaming destination or make changes to the existing destination.
```

2023-03-20 04:52 UTC, SudheendraKatte commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +- Delete: You can delete the audit stream destination.
```suggestion
- Delete: Delete the audit stream destination.
```

2023-03-20 08:45 UTC, rashminandasahoo commented on docs/platform/15_Audit-Trail/audit-streaming.md
> +3. You can pause audit streaming, preventing any new audit events from being streamed to the configured endpoint by setting the status to **Inactive**.
I will retain what I have written here. It is more about the available actions.

2023-03-20 09:18 UTC, charanya-j approved these changes

2023-03-20 09:18 UTC, merged