CCM-11540-Added a new page for AutoStopping in dry-run mode
harness/developer-hub pull request #935
Opened 2023-03-10 05:30 UTC by charanya-j

The local build is successful.
Created a new page for AutoStopping in dry-run mode.
Updated the other create Autostopping ru

2023-03-10 06:27 UTC, shalinlk commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-ecs.md
> +Toggle the button to enable or disable the instances warming up progress status. If you turn this on, the progress status will not be displayed.
I think we need more details about why the option is required and in what context users can use it. Gist of it should be like this. This option is included to avoid mis interpretation of progress page as actual intended response from a service we are onboarding to AutoStopping, by any of the automation component or client scripts. Once this option is enabled, the first response of warming up a rule after a down time will be delayed until the intended service is actually up and running.

2023-03-10 06:28 UTC, shalinlk reviewed
Looks okay. Better to get it reviewed by Ravi on the wordings.

2023-03-10 11:38 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-ecs.md
> +Toggle the button to enable or disable the instances warming up progress status. If you turn this on, the progress status will not be displayed.
Done

2023-03-10 12:19 UTC, navaneeth commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/autostopping-dry-run-mode.md
> +The dry-run mode is a feature that enables you to try out AutoStopping without actually terminating your cloud resources. This option allows you to evaluate the impact of AutoStopping and estimate th
Don't say terminating. It should be without actually stopping cloud resources

2023-03-10 12:33 UTC, navaneeth requested changes

2023-03-10 12:33 UTC, navaneeth commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/autostopping-dry-run-mode.md
> +To evaluate the cost savings of a rule, click on the rule to navigate to the rule's summary page. To activate the rule and begin optimizing costs, toggle off the **Dry Run** switch located on the pag
I think this whole paragraph is not clear. We should explain the following:

1. A dry run rule behaves the same way as a normal AutoStopping rule without the actual shutdown of cloud resources
2. Estimated savings data takes up to 24hrs to generate
3. You can verify the savings data either in the rule summary page or in the rule details page
4. Once data is looking good, Dry run mode can be turned off to actually start saving

2023-03-16 09:39 UTC, navaneeth approved these changes

2023-03-16 10:31 UTC, SudheendraKatte submitted a review, later dismissed
Approved with few suggestions.

2023-03-16 10:31 UTC, SudheendraKatte commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/autostopping-dry-run-mode.md
> +description: AutoStopping Rules make sure that your non-production resources run only when used, and never when idle. This topic describes how to create AutoStopping rules in dry-run mode.
This sentence is repeated inside the topic also. Please see if the first sentence can be removed from here considering that this is the tile space.

2023-03-16 10:31 UTC, SudheendraKatte commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/autostopping-dry-run-mode.md
> +If the data is satisfactory, you can turn off the **Dry Run** mode to start saving costs.
A suggestion - If the data is satisfactory, you can turn off the **Dry Run** mode to apply the AutoStopping rule to your cloud resources and start saving costs.

2023-03-16 10:31 UTC, SudheendraKatte commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-azure.md
>  Set dependencies between two or more AutoStopping Rules when you want one Rule to make one or more Rules to be active based on the traffic that it receives. For example for an application server depe
This is confusing. How about this rephrase:

Establish dependencies between two or more AutoStopping Rules when you want one Rule to activate one or more Rules based on the traffic it receives.

2023-03-16 10:48 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/autostopping-dry-run-mode.md
> +description: AutoStopping Rules make sure that your non-production resources run only when used, and never when idle. This topic describes how to create AutoStopping rules in dry-run mode.
Agreed

2023-03-16 10:51 UTC, charanya-j commented on docs/cloud-cost-management/2-use-cloud-cost-management/1-optimize-cloud-costs-with-intelligent-cloud-auto-stopping-rules/3-create-auto-stopping-rules/create-auto-stopping-rules-for-azure.md
>  Set dependencies between two or more AutoStopping Rules when you want one Rule to make one or more Rules to be active based on the traffic that it receives. For example for an application server depe
This is existing content. However, I've incorporated your comments. :)

2023-03-16 13:11 UTC, merged